Inference Engine (Clocher): engine/src/quant/act_fp8.c File Reference
act_fp8.c File Reference
FP8 activation quantization (E4M3 and E5M2).
#include "ie_quant_act.h"
#include <math.h>
#include <stdint.h>
#include <string.h>
Data Structures
union ie_f32u32
Functions
static uint32_t ie_u32_from_f (float x)
static float ie_f_from_u32 (uint32_t u)
static int ie_is_nan_u32 (uint32_t u)
static int ie_is_inf_u32 (uint32_t u)
static uint8_t ie_pack_fp8_e4m3 (float x)
static float ie_unpack_fp8_e4m3 (uint8_t v)
static uint8_t ie_pack_fp8_e5m2 (float x)
static float ie_unpack_fp8_e5m2 (uint8_t v)
void ie_quantize_act_fp8 (const float *src, uint8_t *dst, size_t n, ie_fp8_format fmt)
Quantize fp32 activations to FP8.
void ie_dequantize_act_fp8 (const uint8_t *src, float *dst, size_t n, ie_fp8_format fmt)
Dequantize FP8 bytes to fp32.
Detailed Description
FP8 activation quantization (E4M3 and E5M2).
Software implementation of FP8 encoders/decoders to support runtime activation compression (and KV-cache if desired) without external dependencies. The E4M3 variant is treated as finite-only with saturating overflow; E5M2 preserves Inf/NaN where possible.
Definition in file act_fp8.c.
Function Documentation
ie_dequantize_act_fp8()
void ie_dequantize_act_fp8 (const uint8_t * src, float * dst, size_t n, ie_fp8_format fmt)
Dequantize FP8 bytes to fp32.
Parameters
src Source FP8 bytes (bit patterns).
dst Destination float buffer.
n Number of elements.
fmt FP8 format selector.
Definition at line 195 of file act_fp8.c.
{
   if (fmt == IE_FP8_E4M3) {
     for (size_t i = 0; i < n; ++i) {
       dst[i] = ie_unpack_fp8_e4m3(src[i]);
     }
   } else {
     for (size_t i = 0; i < n; ++i) {
       dst[i] = ie_unpack_fp8_e5m2(src[i]);
     }
   }
 }
References IE_FP8_E4M3, ie_unpack_fp8_e4m3(), and ie_unpack_fp8_e5m2().
Referenced by bench_fp8(), ie_kv_load_token_f32(), and test_fp8_sweep().
ie_f_from_u32()
static float ie_f_from_u32 (uint32_t u) inline static
Definition at line 24 of file act_fp8.c.
{
   ie_f32u32 v; v.u = u; return v.f;
 }
References ie_f32u32::f, and ie_f32u32::u.
ie_is_inf_u32()
static int ie_is_inf_u32 (uint32_t u) inline static
Definition at line 32 of file act_fp8.c.
{
   return ((u & 0x7FFFFFFFu) == 0x7F800000u);
 }
Referenced by ie_pack_fp8_e4m3(), and ie_pack_fp8_e5m2().
ie_is_nan_u32()
static int ie_is_nan_u32 (uint32_t u) inline static
Definition at line 28 of file act_fp8.c.
{
   return ((u & 0x7FFFFFFFu) > 0x7F800000u);
 }
Referenced by ie_pack_fp8_e4m3(), and ie_pack_fp8_e5m2().
ie_pack_fp8_e4m3()
static uint8_t ie_pack_fp8_e4m3 (float x) inline static
Definition at line 44 of file act_fp8.c.
{
   /* Finite-only E4M3 with bias 7. */
   if (x == 0.0f) return 0u;
   uint32_t u = ie_u32_from_f(x);
   uint8_t sign = (u >> 31) & 0x1;
   if (ie_is_nan_u32(u)) {
     /* Treat NaN as max finite with payload dropped. */
     const uint8_t payload = 0x1; /* minimal mantissa to signal "non-zero" */
     return (uint8_t)((sign << 7) | (0xE << 3) | (payload & 0x7));
   }
   if (ie_is_inf_u32(u)) {
     /* Saturate to max finite. */
     return (uint8_t)((sign << 7) | (0xE << 3) | 0x7);
   }
   float ax = fabsf(x);
   int e2;
   float m = frexpf(ax, &e2); /* ax = m * 2^e2, m in [0.5,1) */
   /* Convert to 1.xxx with mantissa in [1,2) by shifting: */
   float m_shift = m * 2.0f; /* [1,2) */
   int   e = e2 - 1;         /* adjust because of the shift */
   const int bias = 7;
   int exp_fp8 = e + bias;
   /* Round mantissa to 3 bits on [1,2): mant = 1 + frac; q = round(frac * 2^3) */
   float frac = m_shift - 1.0f;
   float qf   = nearbyintf(frac * 8.0f); /* 2^3 = 8 */
   int   qm   = (int)qf;
   if (qm == 8) { /* carry into exponent */
     qm = 0;
     exp_fp8 += 1;
   }
   if (exp_fp8 <= 0) {
     /* Underflow to zero (we skip subnormals for simplicity/perf). */
     return (uint8_t)(sign << 7);
   }
   if (exp_fp8 >= 0xE) {
     /* 0xF would be reserved; clamp to max finite exponent (0xE) and mant=7 */
     return (uint8_t)((sign << 7) | (0xE << 3) | 0x7);
   }
   return (uint8_t)((sign << 7) | ((uint8_t)exp_fp8 << 3) | ((uint8_t)qm & 0x7));
 }
References ie_is_inf_u32(), ie_is_nan_u32(), and ie_u32_from_f().
Referenced by ie_quantize_act_fp8().
ie_pack_fp8_e5m2()
static uint8_t ie_pack_fp8_e5m2 (float x) inline static
Definition at line 112 of file act_fp8.c.
{
   /* E5M2 with bias 15; supports Inf/NaN. */
   uint32_t u = ie_u32_from_f(x);
   uint8_t sign = (u >> 31) & 0x1;
   if (x == 0.0f) return (uint8_t)(sign << 7);
   if (ie_is_nan_u32(u)) {
     return (uint8_t)((sign << 7) | (0x1F << 2) | 0x1); /* quiet NaN surrogate */
   }
   if (ie_is_inf_u32(u)) {
     return (uint8_t)((sign << 7) | (0x1F << 2) | 0x0); /* infinity */
   }
   float ax = fabsf(x);
   int e2;
   float m = frexpf(ax, &e2);  /* ax = m * 2^e2, m in [0.5,1) */
   float m_shift = m * 2.0f;   /* [1,2) */
   int   e = e2 - 1;
   const int bias = 15;
   int exp_fp8 = e + bias;
   /* 2 mantissa bits on [1,2): */
   float frac = m_shift - 1.0f;
   float qf   = nearbyintf(frac * 4.0f); /* 2^2 = 4 */
   int   qm   = (int)qf;
   if (qm == 4) { /* carry */
     qm = 0;
     exp_fp8 += 1;
   }
   if (exp_fp8 <= 0) {
     /* Underflow -> flush to zero (skip subnormals). */
     return (uint8_t)(sign << 7);
   }
   if (exp_fp8 >= 0x1F) {
     /* Overflow -> infinity. */
     return (uint8_t)((sign << 7) | (0x1F << 2));
   }
   return (uint8_t)((sign << 7) | ((uint8_t)exp_fp8 << 2) | ((uint8_t)qm & 0x3));
 }
References ie_is_inf_u32(), ie_is_nan_u32(), and ie_u32_from_f().
Referenced by ie_quantize_act_fp8().
ie_quantize_act_fp8()
void ie_quantize_act_fp8 (const float * src, uint8_t * dst, size_t n, ie_fp8_format fmt)
Quantize fp32 activations to FP8.
E4M3: non-finite inputs saturate to max finite.
E5M2: attempts to preserve Inf/NaN encodings.
Parameters
src Source float buffer.
dst Destination FP8 bytes (bit patterns).
n Number of elements.
fmt FP8 format selector.
Definition at line 182 of file act_fp8.c.
{
   if (fmt == IE_FP8_E4M3) {
     for (size_t i = 0; i < n; ++i) {
       dst[i] = ie_pack_fp8_e4m3(src[i]);
     }
   } else {
     for (size_t i = 0; i < n; ++i) {
       dst[i] = ie_pack_fp8_e5m2(src[i]);
     }
   }
 }
References IE_FP8_E4M3, ie_pack_fp8_e4m3(), and ie_pack_fp8_e5m2().
Referenced by bench_fp8(), ie_kv_store_token_fp8(), and test_fp8_sweep().
ie_u32_from_f()
static uint32_t ie_u32_from_f (float x) inline static
Definition at line 21 of file act_fp8.c.
{
   ie_f32u32 v; v.f = x; return v.u;
 }
References ie_f32u32::f, and ie_f32u32::u.
Referenced by ie_pack_fp8_e4m3(), and ie_pack_fp8_e5m2().
ie_unpack_fp8_e4m3()
static float ie_unpack_fp8_e4m3 (uint8_t v) inline static
Definition at line 93 of file act_fp8.c.
{
   if (v == 0u) return 0.0f;
   uint8_t sign = (v >> 7) & 0x1;
   uint8_t exp  = (v >> 3) & 0xF;
   uint8_t man  = (v & 0x7);
   if (exp == 0) {
     /* We do not encode subnormals; interpret as +/- 0. */
     return sign ? -0.0f : 0.0f;
   }
   /* Finite-only: exp==0xF unused; exp==0xE is largest finite. */
   const int bias = 7;
   int e = ((int)exp) - bias;
   float frac = (float)man / 8.0f; /* 2^3 */
   float val  = (1.0f + frac) * ldexpf(1.0f, e); /* (1 + frac) * 2^e */
   return sign ? -val : val;
 }
Referenced by ie_dequantize_act_fp8().
ie_unpack_fp8_e5m2()
static float ie_unpack_fp8_e5m2 (uint8_t v) inline static
Definition at line 156 of file act_fp8.c.
{
   uint8_t sign = (v >> 7) & 0x1;
   uint8_t exp  = (v >> 2) & 0x1F;
   uint8_t man  = (v & 0x3);
   if (exp == 0) {
     /* We do not produce subnormals; interpret as +/- 0. */
     return sign ? -0.0f : 0.0f;
   }
   if (exp == 0x1F) {
     if (man == 0) return sign ? -INFINITY : INFINITY;
     /* NaN: return a quiet NaN. */
     volatile float qnan = NAN;
     return qnan;
   }
   const int bias = 15;
   int e = ((int)exp) - bias;
   float frac = (float)man / 4.0f; /* 2^2 */
   float val  = (1.0f + frac) * ldexpf(1.0f, e);
   return sign ? -val : val;
 }
Referenced by ie_dequantize_act_fp8().