Inference Engine (Clocher): engine/src/quant/act_int8.c File Reference
act_int8.c File Reference
INT8 activation quantization (per-tensor and per-group).
#include "ie_quant_act.h"
#include <math.h>
#include <stddef.h>
#include <stdint.h>
Functions
static float ie_fabsf (float x)
static float ie_maxf (float a, float b)
static float ie_minf (float a, float b)
static float ie_rne (float x)
static int8_t ie_sat_i8 (int v)
static int8_t ie_sat_sym_i8 (int v)
void ie_act_i8_params_from_minmax (float minv, float maxv, int symmetric, float *out_scale, int8_t *out_zero)
Compute per-tensor INT8 parameters from observed min/max.
void ie_quantize_act_int8 (const float *src, int8_t *dst, size_t n, ie_act_i8_params params, int symmetric)
Quantize fp32 activations to INT8 using per-tensor parameters.
void ie_dequantize_act_int8 (const int8_t *src, float *dst, size_t n, ie_act_i8_params params)
Dequantize INT8 activations to fp32 using per-tensor parameters.
void ie_act_i8_group_params_from_data (const float *src, size_t n, size_t group_size, int symmetric, float *out_scales, int8_t *out_zeros)
Compute per-group INT8 parameters from data.
void ie_quantize_act_int8_per_group (const float *src, int8_t *dst, size_t n, size_t group_size, const float *scales, const int8_t *zeros, int symmetric)
Quantize fp32 activations to INT8 using per-group parameters.
void ie_dequantize_act_int8_per_group (const int8_t *src, float *dst, size_t n, size_t group_size, const float *scales, const int8_t *zeros)
Dequantize per-group INT8 activations to fp32.
Detailed Description
INT8 activation quantization (per-tensor and per-group).
This file implements fast saturating affine INT8 quantization paths for activations. The API supports both per-tensor and per-group parameterization with symmetric (zero_point=0) and asymmetric modes.
Definition in file act_int8.c.
Function Documentation
ie_act_i8_group_params_from_data()
void ie_act_i8_group_params_from_data (const float * src, size_t n, size_t group_size, int symmetric, float * out_scales, int8_t * out_zeros)
Compute per-group INT8 parameters from data.
Splits src into contiguous groups of group_size (last group may be shorter) and computes parameters for each group.
Parameters
src Source float buffer.
n Number of elements.
group_size Group size (>= 1).
symmetric Non-zero for symmetric quantization.
out_scales Output scales array (ceil(n/group_size)).
out_zeros Output zero-points array (ceil(n/group_size)).
Definition at line 109 of file act_int8.c.
{
   if (group_size == 0) return;
   const size_t groups = (n + group_size - 1) / group_size;
   for (size_t g = 0; g < groups; ++g) {
     const size_t start = g * group_size;
     const size_t end   = (start + group_size <= n) ? (start + group_size) : n;
     float mn = src[start];
     float mx = src[start];
     for (size_t i = start + 1; i < end; ++i) {
       mn = ie_minf(mn, src[i]);
       mx = ie_maxf(mx, src[i]);
     }
     float s; int8_t z;
     ie_act_i8_params_from_minmax(mn, mx, symmetric, &s, &z);
     out_scales[g] = s;
     out_zeros[g]  = z;
   }
 }
References ie_act_i8_params_from_minmax(), ie_maxf(), and ie_minf().
Referenced by ie_kv_store_token_int8_per_group(), and test_int8_per_group().
ie_act_i8_params_from_minmax()
void ie_act_i8_params_from_minmax (float minv, float maxv, int symmetric, float * out_scale, int8_t * out_zero)
Compute per-tensor INT8 parameters from observed min/max.
If symmetric != 0:
zero_point is set to 0
scale is derived from max(|minv|,|maxv|)/127
If symmetric == 0:
parameters map minv -> -128 and maxv -> 127 using an affine transform
Parameters
minv Observed minimum.
maxv Observed maximum.
symmetric Non-zero for symmetric quantization.
out_scale Output scale (non-NULL).
out_zero Output zero point (non-NULL).
Definition at line 51 of file act_int8.c.
{
   /* Ensure valid range; if degenerate, pick unit scale. */
   if (!(maxv > minv)) {
     *out_scale = 1.0f;
     *out_zero  = 0;
     return;
   }
   if (symmetric) {
     const float amax = ie_maxf(ie_fabsf(minv), ie_fabsf(maxv));
     /* Map amax -> 127, avoid divide-by-zero. */
     const float denom = (amax > 0.0f) ? amax : 1.0f;
     *out_scale = denom / 127.0f;
     *out_zero  = 0;
   } else {
     /* Map minv -> -128, maxv -> 127 */
     const float qrange = 127.0f - (-128.0f); /* 255 */
     const float scale  = (maxv - minv) / qrange;
     const float zp_f   = -(-128.0f) - (minv / (scale > 0.0f ? scale : 1.0f));
     /* Round and clamp zero point into INT8 range. */
     int zp_i = (int)ie_rne(zp_f);
     if (zp_i < -128) zp_i = -128;
     if (zp_i > 127)  zp_i = 127;
     *out_scale = (scale > 0.0f ? scale : 1.0f);
     *out_zero  = (int8_t)zp_i;
   }
 }
References ie_fabsf(), ie_maxf(), and ie_rne().
Referenced by bench_int8(), ie_act_i8_group_params_from_data(), ie_kv_store_token_int8_per_tensor(), and test_int8_per_tensor().
ie_dequantize_act_int8()
void ie_dequantize_act_int8 (const int8_t * src, float * dst, size_t n, ie_act_i8_params params)
Dequantize INT8 activations to fp32 using per-tensor parameters.
Parameters
src Source INT8 buffer.
dst Destination float buffer (length n).
n Number of elements.
params Dequantization parameters.
Definition at line 100 of file act_int8.c.
{
   const float s = params.scale;
   const int   z = (int)params.zero_point;
   for (size_t i = 0; i < n; ++i) {
     dst[i] = s * ((int)src[i] - z);
   }
 }
References ie_act_i8_params::scale, and ie_act_i8_params::zero_point.
Referenced by bench_int8(), and test_int8_per_tensor().
ie_dequantize_act_int8_per_group()
void ie_dequantize_act_int8_per_group (const int8_t * src, float * dst, size_t n, size_t group_size, const float * scales, const int8_t * zeros)
Dequantize per-group INT8 activations to fp32.
Parameters
src Source INT8 buffer.
dst Destination float buffer.
n Number of elements.
group_size Group size (>= 1).
scales Scales array (ceil(n/group_size)).
zeros Zero-points array (ceil(n/group_size)).
Definition at line 155 of file act_int8.c.
{
   if (group_size == 0) return;
   const size_t groups = (n + group_size - 1) / group_size;
   for (size_t g = 0; g < groups; ++g) {
     const size_t start = g * group_size;
     const size_t end   = (start + group_size <= n) ? (start + group_size) : n;
     const float s = scales[g];
     const int   z = (int)zeros[g];
     for (size_t i = start; i < end; ++i) {
       dst[i] = s * ((int)src[i] - z);
     }
   }
 }
Referenced by test_int8_per_group().
ie_fabsf()
static float ie_fabsf (float x) inline static
Definition at line 18 of file act_int8.c.
{
   return x < 0.0f ? -x : x;
 }
Referenced by ie_act_i8_params_from_minmax().
ie_maxf()
static float ie_maxf (float a, float b) inline static
Definition at line 22 of file act_int8.c.
{
   return a > b ? a : b;
 }
Referenced by ie_act_i8_group_params_from_data(), and ie_act_i8_params_from_minmax().
ie_minf()
static float ie_minf (float a, float b) inline static
Definition at line 26 of file act_int8.c.
{
   return a < b ? a : b;
 }
Referenced by ie_act_i8_group_params_from_data().
ie_quantize_act_int8()
void ie_quantize_act_int8 (const float * src, int8_t * dst, size_t n, ie_act_i8_params params, int symmetric)
Quantize fp32 activations to INT8 using per-tensor parameters.
Parameters
src Source float buffer.
dst Destination INT8 buffer (length n).
n Number of elements.
params Quantization parameters.
symmetric Non-zero to enforce symmetric saturation policy.
Definition at line 81 of file act_int8.c.
{
   const float inv_scale = (params.scale > 0.0f) ? (1.0f / params.scale) : 1.0f;
   if (symmetric) {
     for (size_t i = 0; i < n; ++i) {
       const float v = src[i] * inv_scale;
       const int   q = (int)ie_rne(v);
       dst[i] = ie_sat_sym_i8(q);
     }
   } else {
     const int z = (int)params.zero_point;
     for (size_t i = 0; i < n; ++i) {
       const float v = src[i] * inv_scale + (float)z;
       const int   q = (int)ie_rne(v);
       dst[i] = ie_sat_i8(q);
     }
   }
 }
References ie_rne(), ie_sat_i8(), ie_sat_sym_i8(), ie_act_i8_params::scale, and ie_act_i8_params::zero_point.
Referenced by bench_int8(), ie_kv_store_token_int8_per_tensor(), and test_int8_per_tensor().
ie_quantize_act_int8_per_group()
void ie_quantize_act_int8_per_group (const float * src, int8_t * dst, size_t n, size_t group_size, const float * scales, const int8_t * zeros, int symmetric)
Quantize fp32 activations to INT8 using per-group parameters.
Parameters
src Source float buffer.
dst Destination INT8 buffer.
n Number of elements.
group_size Group size (>= 1).
scales Scales array (ceil(n/group_size)).
zeros Zero-points array (ceil(n/group_size)).
symmetric Non-zero to enforce symmetric saturation policy.
Definition at line 130 of file act_int8.c.
{
   if (group_size == 0) return;
   const size_t groups = (n + group_size - 1) / group_size;
   for (size_t g = 0; g < groups; ++g) {
     const size_t start = g * group_size;
     const size_t end   = (start + group_size <= n) ? (start + group_size) : n;
     const float inv_s  = (scales[g] > 0.0f) ? 1.0f / scales[g] : 1.0f;
     if (symmetric) {
       for (size_t i = start; i < end; ++i) {
         const int q = (int)ie_rne(src[i] * inv_s);
         dst[i] = ie_sat_sym_i8(q);
       }
     } else {
       const int z = (int)zeros[g];
       for (size_t i = start; i < end; ++i) {
         const int q = (int)ie_rne(src[i] * inv_s + (float)z);
         dst[i] = ie_sat_i8(q);
       }
     }
   }
 }
References ie_rne(), ie_sat_i8(), and ie_sat_sym_i8().
Referenced by ie_kv_store_token_int8_per_group(), and test_int8_per_group().
ie_rne()
static float ie_rne (float x) inline static
Definition at line 31 of file act_int8.c.
{
   /* Using nearbyintf honors current rounding mode; default is ties-to-even. */
   return nearbyintf(x);
 }
Referenced by ie_act_i8_params_from_minmax(), ie_quantize_act_int8(), and ie_quantize_act_int8_per_group().
ie_sat_i8()
static int8_t ie_sat_i8 (int v) inline static
Definition at line 36 of file act_int8.c.
{
   if (v > 127) return 127;
   if (v < -128) return -128;
   return (int8_t)v;
 }
Referenced by ie_quantize_act_int8(), and ie_quantize_act_int8_per_group().
ie_sat_sym_i8()
static int8_t ie_sat_sym_i8 (int v) inline static
Definition at line 43 of file act_int8.c.
{
   if (v > 127) return 127;
   if (v < -127) return -127;
   return (int8_t)v;
 }
Referenced by ie_quantize_act_int8(), and ie_quantize_act_int8_per_group().