Inference Engine (Clocher): test_cli_flags.CLIFeatureFlagsTests Class Reference
test_cli_flags.CLIFeatureFlagsTests Class Reference
Public Member Functions
run_cli (self, args)
test_threads_flag_accepts_values (self)
test_precision_flag (self)
test_affinity_flag_no_crash (self)
Detailed Description
Definition at line 9 of file test_cli_flags.py.
Member Function Documentation
run_cli()
test_cli_flags.CLIFeatureFlagsTests.run_cli (self, args)
Definition at line 10 of file test_cli_flags.py.
    def run_cli(self, args):
        cp = subprocess.run([BIN] + args, text=True, capture_output=True, check=True)
        return cp.stdout
References ie_gemv_rowwise_f32_kernel().
Referenced by test_cli_flags.CLIFeatureFlagsTests.test_affinity_flag_no_crash(), test_cli_flags.CLIFeatureFlagsTests.test_precision_flag(), and test_cli_flags.CLIFeatureFlagsTests.test_threads_flag_accepts_values().
test_affinity_flag_no_crash()
test_cli_flags.CLIFeatureFlagsTests.test_affinity_flag_no_crash (self)
Definition at line 26 of file test_cli_flags.py.
    def test_affinity_flag_no_crash(self):
        # accepted values, even se ignorado por default
        for mode in ["auto", "compact", "scatter"]:
            out = self.run_cli(["--prompt", "x", "--max-new", "1", "--affinity", mode])
            self.assertIn('"tokens_generated"', out)
References test_cli_flags.CLIFeatureFlagsTests.run_cli().
test_precision_flag()
test_cli_flags.CLIFeatureFlagsTests.test_precision_flag (self)
Definition at line 20 of file test_cli_flags.py.
    def test_precision_flag(self):
        out = self.run_cli(["--prompt", "hello", "--max-new", "2", "--precision", "fp32"])
        self.assertIn('"tokens_generated"', out)
        out = self.run_cli(["--prompt", "hello", "--max-new", "2", "--precision", "bf16"])
        self.assertIn('"tokens_generated"', out)
References test_cli_flags.CLIFeatureFlagsTests.run_cli().
test_threads_flag_accepts_values()
test_cli_flags.CLIFeatureFlagsTests.test_threads_flag_accepts_values (self)
Definition at line 14 of file test_cli_flags.py.
    def test_threads_flag_accepts_values(self):
        out = self.run_cli(["--prompt", "hello", "--max-new", "4", "--threads", "1"])
        self.assertIn('"tokens_generated"', out)
        out2 = self.run_cli(["--prompt", "hello", "--max-new", "4", "--threads", "2"])
        self.assertIn('"tokens_generated"', out2)
References test_cli_flags.CLIFeatureFlagsTests.run_cli().
The documentation for this class was generated from the following file:
tests/python/test_cli_flags.py