Inference Engine (Clocher): metrics_exporter.Handler Class Reference
metrics_exporter.Handler Class Reference
Public Member Functions
None do_GET (self)
Static Public Attributes
Optional summary_path = None
Optional dir_path = None
Detailed Description
HTTP handler serving /metrics from either a summary file or dir.
Definition at line 187 of file metrics_exporter.py.
Member Function Documentation
do_GET()
None metrics_exporter.Handler.do_GET (self)
Definition at line 193 of file metrics_exporter.py.
    def do_GET(self) -> None:  # noqa: N802
        try:
            if self.path != "/metrics":
                self.send_response(404)
                self.end_headers()
                self.wfile.write(b"not found\n")
                return
            obj: Dict[str, Any] = {}
            if self.summary_path is not None:
                obj = _load_one_json_file(self.summary_path)
            elif self.dir_path is not None:
                latest = _find_latest_json(self.dir_path)
                if latest is not None:
                    obj = _load_one_json_file(latest)
            txt = collect_metrics_from_summary(obj if obj else {})
            payload = txt.encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "text/plain; version=0.0.4")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            self.wfile.write(payload)
        except Exception as e:
            err = f"# exporter_error{{msg=\"{type(e).__name__}\"}} 1\n"
            payload = err.encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "text/plain; version=0.0.4")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            self.wfile.write(payload)
References metrics_exporter._find_latest_json(), metrics_exporter._load_one_json_file(), metrics_exporter.collect_metrics_from_summary(), metrics_exporter.Handler.dir_path, k_gemv_rowwise_f32(), ie_mmap_file.path, and metrics_exporter.Handler.summary_path.
Field Documentation
dir_path
Optional metrics_exporter.Handler.dir_path = None static
Definition at line 191 of file metrics_exporter.py.
Referenced by metrics_exporter.Handler.do_GET().
summary_path
Optional metrics_exporter.Handler.summary_path = None static
Definition at line 190 of file metrics_exporter.py.
Referenced by metrics_exporter.Handler.do_GET().
The documentation for this class was generated from the following file:
scripts/metrics_exporter.py