Inference Engine (Clocher): test_cli_error_paths.CLIErrorPathsTests Class Reference
test_cli_error_paths.CLIErrorPathsTests Class Reference
Public Member Functions
None test_invalid_flag_is_rejected (self)
None test_zero_tokens_graceful (self)
Detailed Description
Definition at line 14 of file test_cli_error_paths.py.
Member Function Documentation
test_invalid_flag_is_rejected()
None test_cli_error_paths.CLIErrorPathsTests.test_invalid_flag_is_rejected (self)
Definition at line 15 of file test_cli_error_paths.py.
    def test_invalid_flag_is_rejected(self) -> None:
        bin_path = _engine_bin()
        if not os.path.exists(bin_path):
            self.skipTest(f"engine binary not found: {bin_path}")
        cp = subprocess.run(
            [bin_path, "--this-flag-does-not-exist"],
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertNotEqual(cp.returncode, 0)
        # Message text may vary; just ensure it didn't silently succeed.
        self.assertTrue(cp.stderr.strip() or cp.stdout.strip())
References test_cli_error_paths._engine_bin(), and ie_gemv_rowwise_f32_kernel().
test_zero_tokens_graceful()
None test_cli_error_paths.CLIErrorPathsTests.test_zero_tokens_graceful (self)
Definition at line 30 of file test_cli_error_paths.py.
    def test_zero_tokens_graceful(self) -> None:
        bin_path = _engine_bin()
        if not os.path.exists(bin_path):
            self.skipTest(f"engine binary not found: {bin_path}")
        cp = subprocess.run(
            [bin_path, "--prompt", "hi", "--max-new", "0"],
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(cp.returncode, 0)
        # Parse JSON instead of string-matching spacing.
        out = cp.stdout.strip()
        self.assertTrue(out, "expected JSON on stdout")
        obj = json.loads(out)
        self.assertIn("tokens_generated", obj)
        self.assertEqual(int(obj["tokens_generated"]), 0)
References test_cli_error_paths._engine_bin(), and ie_gemv_rowwise_f32_kernel().
The documentation for this class was generated from the following file:
tests/python/test_cli_error_paths.py