Inference Engine (Clocher): test_ptq_calib_pipeline.PTQCalibPipelineTests Class Reference
test_ptq_calib_pipeline.PTQCalibPipelineTests Class Reference
Public Member Functions
run_ptq (self, int rows, int cols, str mode, Path out_prefix)
test_per_row_pipeline (self)
test_per_tensor_pipeline (self)
Detailed Description
Definition at line 38 of file test_ptq_calib_pipeline.py.
Member Function Documentation
run_ptq()
test_ptq_calib_pipeline.PTQCalibPipelineTests.run_ptq (self, int rows, int cols, str mode, Path out_prefix)
Definition at line 39 of file test_ptq_calib_pipeline.py.
    def run_ptq(self, rows: int, cols: int, mode: str, out_prefix: Path):
        w = out_prefix.with_suffix(".f32.bin")
        w.parent.mkdir(parents=True, exist_ok=True)
        write_f32_bin(w, rows, cols)
        cp = subprocess.run(
            ["python3", str(PTQ),
             "--weights", str(w),
             "--rows", str(rows),
             "--cols", str(cols),
             "--mode", mode,
             "--out-prefix", str(out_prefix),
             "--accuracy-threshold", "0.99"],
            text=True, capture_output=True
        )
        self.assertEqual(cp.returncode, 0, msg=f"stderr:\n{cp.stderr}\nstdout:\n{cp.stdout}")
        int8_bin = Path(str(out_prefix) + ".int8.bin")
        scales_bin = Path(str(out_prefix) + ".scales.bin")
        report_json = Path(str(out_prefix) + ".report.json")
        for p in (int8_bin, scales_bin, report_json):
            self.assertTrue(p.exists(), msg=f"missing artifact: {p}")
        rpt = read_json(report_json)
        self.assertIn("cosine_sim", rpt)
        self.assertIn("mse", rpt)
        self.assertGreaterEqual(rpt["cosine_sim"], 0.99)
        self.assertLess(rpt["mse"], 1e-2)
References ie_gemv_rowwise_f32_kernel(), test_ptq_calib_pipeline.read_json(), and test_ptq_calib_pipeline.write_f32_bin().
Referenced by test_ptq_calib_pipeline.PTQCalibPipelineTests.test_per_row_pipeline(), and test_ptq_calib_pipeline.PTQCalibPipelineTests.test_per_tensor_pipeline().
test_per_row_pipeline()
test_ptq_calib_pipeline.PTQCalibPipelineTests.test_per_row_pipeline (self)
Definition at line 69 of file test_ptq_calib_pipeline.py.
    def test_per_row_pipeline(self):
        with tempfile.TemporaryDirectory() as td:
            outp = Path(td) / "perrow"
            self.run_ptq(rows=16, cols=32, mode="per_row", out_prefix=outp)
References ie_gemv_rowwise_f32_kernel(), and test_ptq_calib_pipeline.PTQCalibPipelineTests.run_ptq().
test_per_tensor_pipeline()
test_ptq_calib_pipeline.PTQCalibPipelineTests.test_per_tensor_pipeline (self)
Definition at line 74 of file test_ptq_calib_pipeline.py.
    def test_per_tensor_pipeline(self):
        with tempfile.TemporaryDirectory() as td:
            outp = Path(td) / "pertensor"
            self.run_ptq(rows=16, cols=32, mode="per_tensor", out_prefix=outp)
References ie_gemv_rowwise_f32_kernel(), and test_ptq_calib_pipeline.PTQCalibPipelineTests.run_ptq().
The documentation for this class was generated from the following file:
tests/python/test_ptq_calib_pipeline.py