Inference Engine (Clocher): engine/include/dedup_spec.h File Reference
dedup_spec.h File Reference
Lossless deduplication specification for "defaults + masks + exceptions".
#include <stdint.h>
#include <stddef.h>
Data Structures
struct ie_dedup_target_s
struct ie_dedup_group_s
struct ie_dedup_spec_s
struct ie_dedup_spec_arena_s
Macros
#define IE_DEDUP_MAGIC 0x44554450u
Magic value for validating a parsed spec in memory ("DUDP").
#define IE_DEDUP_VERSION 1u
Spec version supported by this header.
Typedefs
typedef struct ie_dedup_target_s ie_dedup_target_t
typedef struct ie_dedup_group_s ie_dedup_group_t
typedef struct ie_dedup_spec_s ie_dedup_spec_t
typedef struct ie_dedup_spec_arena_s ie_dedup_spec_arena_t
Functions
static void ie_dedup_arena_init (ie_dedup_spec_arena_t *a, void *mem, size_t cap)
Initialize a spec arena using caller-provided storage.
void * ie_dedup_arena_alloc (ie_dedup_spec_arena_t *a, size_t nbytes, size_t align)
Allocate aligned memory from a bump arena.
static uint64_t ie_dedup_mask_nbytes (uint64_t nbytes)
Compute mask size in bytes for a tensor byte length.
int ie_dedup_spec_validate (const ie_dedup_spec_t *s)
Validate basic invariants of a parsed spec.
Detailed Description
Lossless deduplication specification for "defaults + masks + exceptions".
This header defines the in-memory representation of a deduplication specification and the binary file layout used to store deduplicated weights losslessly.
The design is intentionally byte-oriented:
A "tensor" is treated as a raw byte blob (works for FP16, BF16, INT8, packed INT4, etc.).
The mask has 1 bit per byte in the tensor blob.
The exception payload stores the exact original bytes at masked positions in ascending byte index order.
Reconstruction rule for a target tensor: target_bytes = default_bytes (same size) patched by (mask, exceptions).
Files (relative to model directory):
model.defaults.bin concatenated default blobs (raw bytes)
model.masks.bin concatenated bitmasks (ceil(nbytes/8) bytes each)
model.exceptions.bin concatenated exception bytes (popcount(mask) bytes each)
The JSON spec (model.dedup.json) links logical tensors to slices of those files.
Definition in file dedup_spec.h.
Macro Definition Documentation
IE_DEDUP_MAGIC
#define IE_DEDUP_MAGIC 0x44554450u
Magic value for validating a parsed spec in memory ("DUDP").
Definition at line 35 of file dedup_spec.h.
IE_DEDUP_VERSION
#define IE_DEDUP_VERSION 1u
Spec version supported by this header.
Definition at line 38 of file dedup_spec.h.
Typedef Documentation
ie_dedup_group_t
typedef struct ie_dedup_group_s ie_dedup_group_t
ie_dedup_spec_arena_t
typedef struct ie_dedup_spec_arena_s ie_dedup_spec_arena_t
ie_dedup_spec_t
typedef struct ie_dedup_spec_s ie_dedup_spec_t
ie_dedup_target_t
typedef struct ie_dedup_target_s ie_dedup_target_t
Function Documentation
ie_dedup_arena_alloc()
void* ie_dedup_arena_alloc (ie_dedup_spec_arena_t * a, size_t nbytes, size_t align)
Allocate aligned memory from a bump arena.
Parameters
a Arena instance.
nbytes Number of bytes requested.
align Alignment (power of two).
Returns
Pointer to allocated space, or NULL on out-of-memory.
Definition at line 21 of file dedup_cache.c.
{
   if (!a || !a->base || align == 0u) return NULL;
   size_t p = ie_align_up(a->len, align);
   if (p > a->cap) return NULL;
   if (nbytes > (a->cap - p)) return NULL;
   void* out = (uint8_t*)a->base + p;
   a->len = p + nbytes;
   return out;
 }
References ie_align_up().
ie_dedup_arena_init()
static void ie_dedup_arena_init (ie_dedup_spec_arena_t * a, void * mem, size_t cap) inline static
Initialize a spec arena using caller-provided storage.
Parameters
a Arena instance.
mem Backing storage.
cap Capacity in bytes.
Definition at line 154 of file dedup_spec.h.
{
   a->base = mem;
   a->cap = cap;
   a->len = 0;
 }
ie_dedup_mask_nbytes()
static uint64_t ie_dedup_mask_nbytes (uint64_t nbytes) inline static
Compute mask size in bytes for a tensor byte length.
Parameters
nbytes Tensor size in bytes.
Returns
ceil(nbytes/8).
Definition at line 175 of file dedup_spec.h.
{
   return (nbytes + 7u) / 8u;
 }
Referenced by ie_dedup_reconstruct_into(), and ie_dedup_spec_validate().
ie_dedup_spec_validate()
int ie_dedup_spec_validate (const ie_dedup_spec_t * s)
Validate basic invariants of a parsed spec.
This checks only structural constraints; it does not require opening files.
Parameters
s Spec pointer.
Returns
0 on success, non-zero on validation error.
Definition at line 31 of file dedup_cache.c.
{
   if (!s) return -1;
   if (s->magic != IE_DEDUP_MAGIC) return -2;
   if (s->version != IE_DEDUP_VERSION) return -3;
   if (s->ngroups == 0 || !s->groups) return -4;
   uint64_t seen_targets = 0;
   for (uint32_t gi = 0; gi < s->ngroups; ++gi) {
     const ie_dedup_group_t* g = &s->groups[gi];
     if (g->default_nbytes == 0) return -5;
     if (g->ntargets == 0 || !g->targets) return -6;
     for (uint32_t ti = 0; ti < g->ntargets; ++ti) {
       const ie_dedup_target_t* t = &g->targets[ti];
       if (t->nbytes != g->default_nbytes) return -7;
       if (t->mask_nbytes != ie_dedup_mask_nbytes(t->nbytes)) return -8;
       seen_targets++;
     }
   }
   if (s->targets_flat_count != (uint32_t)seen_targets) return -9;
   return 0;
 }
References IE_DEDUP_MAGIC, ie_dedup_mask_nbytes(), and IE_DEDUP_VERSION.
Referenced by ie_dedup_cache_init().