Inference Engine (Clocher): engine/include/dedup_cache.h File Reference
dedup_cache.h File Reference
Runtime cache and reconstruction helpers for lossless deduplicated weights.
#include <stdint.h>
#include <stddef.h>
#include "dedup_spec.h"
Data Structures
struct ie_dedup_files_s
struct ie_dedup_cache_entry_s
struct ie_dedup_cache_s
Typedefs
typedef struct ie_dedup_files_s ie_dedup_files_t
typedef struct ie_dedup_cache_entry_s ie_dedup_cache_entry_t
typedef struct ie_dedup_cache_s ie_dedup_cache_t
Functions
int ie_dedup_cache_init (ie_dedup_cache_t *c, const ie_dedup_spec_t *spec, const ie_dedup_files_t *files, uint32_t max_tensor_index, uint32_t entry_cap, uint64_t bytes_limit)
Initialize a dedup cache.
void ie_dedup_cache_destroy (ie_dedup_cache_t *c)
Destroy a dedup cache and free any owned memory.
const ie_dedup_target_t * ie_dedup_cache_find_target (const ie_dedup_cache_t *c, uint32_t tensor_index)
Find a target record for a given tensor_index.
const ie_dedup_group_t * ie_dedup_cache_find_group_for_target (const ie_dedup_cache_t *c, const ie_dedup_target_t *t)
Find the group that owns a given target record.
int ie_dedup_reconstruct_into (uint8_t *dst, const uint8_t *default_bytes, const uint8_t *mask, const uint8_t *exceptions, uint64_t nbytes)
Reconstruct a target tensor into a caller-provided buffer (lossless).
const uint8_t * ie_dedup_cache_get_bytes (ie_dedup_cache_t *c, uint32_t tensor_index, uint8_t *scratch, uint64_t scratch_cap, uint64_t *out_nbytes)
Get a reconstructed weight blob for a tensor.
Detailed Description
Runtime cache and reconstruction helpers for lossless deduplicated weights.
This module provides:
Fast lookup: map a tensor_index -> (group, target) metadata.
Lossless reconstruction: patch a default blob using mask + exceptions.
Optional caching: keep reconstructed tensors in a fixed-capacity cache (LRU-ish).
The API is byte-oriented and intentionally does not assume a specific tensor dtype.
Definition in file dedup_cache.h.
Typedef Documentation
ie_dedup_cache_entry_t
typedef struct ie_dedup_cache_entry_s ie_dedup_cache_entry_t
ie_dedup_cache_t
typedef struct ie_dedup_cache_s ie_dedup_cache_t
ie_dedup_files_t
typedef struct ie_dedup_files_s ie_dedup_files_t
Function Documentation
ie_dedup_cache_destroy()
void ie_dedup_cache_destroy (ie_dedup_cache_t * c)
Destroy a dedup cache and free any owned memory.
Parameters
c Cache instance.
Definition at line 190 of file dedup_cache.c.
{
   if (!c) return;
   if (c->entries) {
     for (uint32_t i = 0; i < c->entry_cap; ++i) {
       ie_cache_entry_clear(c, &c->entries[i]);
     }
     free(c->entries);
   }
   free(c->target_by_index);
   memset(c, 0, sizeof(*c));
 }
References ie_cache_entry_clear().
ie_dedup_cache_find_group_for_target()
const ie_dedup_group_t* ie_dedup_cache_find_group_for_target (const ie_dedup_cache_t * c, const ie_dedup_target_t * t)
Find the group that owns a given target record.
Parameters
c Cache instance.
t Target metadata pointer (must come from this cache/spec).
Returns
Pointer to owning group, or NULL if not found (should not happen if spec is valid).
Definition at line 207 of file dedup_cache.c.
{
   if (!c || !c->spec || !t) return NULL;
   for (uint32_t gi = 0; gi < c->spec->ngroups; ++gi) {
     const ie_dedup_group_t* g = &c->spec->groups[gi];
     for (uint32_t ti = 0; ti < g->ntargets; ++ti) {
       if (&g->targets[ti] == t) return g;
     }
   }
   return NULL;
 }
Referenced by ie_dedup_cache_get_bytes().
ie_dedup_cache_find_target()
const ie_dedup_target_t* ie_dedup_cache_find_target (const ie_dedup_cache_t * c, uint32_t tensor_index)
Find a target record for a given tensor_index.
Parameters
c Cache instance.
tensor_index Target tensor index.
Returns
Pointer to target metadata, or NULL if the tensor is not deduplicated.
Definition at line 202 of file dedup_cache.c.
{
   if (!c || !c->target_by_index || tensor_index >= c->target_by_index_len) return NULL;
   return c->target_by_index[tensor_index];
 }
Referenced by ie_dedup_cache_get_bytes().
ie_dedup_cache_get_bytes()
const uint8_t* ie_dedup_cache_get_bytes (ie_dedup_cache_t * c, uint32_t tensor_index, uint8_t * scratch, uint64_t scratch_cap, uint64_t * out_nbytes)
Get a reconstructed weight blob for a tensor.
If caching is enabled (bytes_limit > 0), this may return a pointer to cached storage. Otherwise, this reconstructs into the provided scratch buffer.
Parameters
c Cache instance.
tensor_index Target tensor index.
scratch Scratch buffer (required if caching disabled, optional otherwise).
scratch_cap Scratch capacity in bytes.
out_nbytes Output tensor size in bytes.
Returns
Pointer to reconstructed bytes (either cache-owned or scratch), or NULL on error.
Definition at line 230 of file dedup_cache.c.
 {
   if (out_nbytes) *out_nbytes = 0;
   if (!c || !c->spec) return NULL;
   const ie_dedup_target_t* t = ie_dedup_cache_find_target(c, tensor_index);
   if (!t) return NULL;
   const ie_dedup_group_t* g = ie_dedup_cache_find_group_for_target(c, t);
   if (!g) return NULL;
   const uint64_t nbytes = t->nbytes;
   /* Validate file slices are within bounds. */
   if (g->default_off + nbytes > c->files.defaults_size) return NULL;
   if (t->mask_off + t->mask_nbytes > c->files.masks_size) return NULL;
   if (t->exc_off + t->exc_nbytes > c->files.exceptions_size) return NULL;
   const uint8_t* defp = c->files.defaults + g->default_off;
   const uint8_t* maskp = c->files.masks + t->mask_off;
   const uint8_t* excp = c->files.exceptions + t->exc_off;
   /* Sanity check: popcount(mask) must match exc_nbytes. */
   {
     const uint64_t expected = ie_mask_popcount_bytes(maskp, t->mask_nbytes);
     if (expected != t->exc_nbytes) return NULL;
   }
   /* If caching disabled, reconstruct into scratch. */
   if (c->bytes_limit == 0 || c->entry_cap == 0) {
     if (!scratch || scratch_cap < nbytes) return NULL;
     if (ie_dedup_reconstruct_into(scratch, defp, maskp, excp, nbytes) != 0) return NULL;
     if (out_nbytes) *out_nbytes = nbytes;
     return scratch;
   }
   /* Check cache hit. */
   for (uint32_t i = 0; i < c->entry_cap; ++i) {
     ie_dedup_cache_entry_t* e = &c->entries[i];
     if (e->data && e->tensor_index == tensor_index && e->nbytes == nbytes) {
       e->stamp = ++c->stamp_now;
       if (out_nbytes) *out_nbytes = nbytes;
       return e->data;
     }
   }
   /* Cache miss: evict if needed, then allocate and reconstruct. */
   uint32_t slot = ie_cache_find_evict(c);
   ie_dedup_cache_entry_t* e = &c->entries[slot];
   /* Free entry if occupied. */
   if (e->data) ie_cache_entry_clear(c, e);
   /* Enforce soft byte limit by evicting more if required. */
   while (c->bytes_cached + nbytes > c->bytes_limit) {
     uint32_t victim = ie_cache_find_evict(c);
     if (!c->entries[victim].data) break;
     ie_cache_entry_clear(c, &c->entries[victim]);
   }
   e->data = (uint8_t*)malloc((size_t)nbytes);
   if (!e->data) {
     ie_cache_entry_clear(c, e);
     return NULL;
   }
   if (ie_dedup_reconstruct_into(e->data, defp, maskp, excp, nbytes) != 0) {
     ie_cache_entry_clear(c, e);
     return NULL;
   }
   e->tensor_index = tensor_index;
   e->nbytes = nbytes;
   e->stamp = ++c->stamp_now;
   c->bytes_cached += nbytes;
   if (out_nbytes) *out_nbytes = nbytes;
   return e->data;
 }
References ie_cache_entry_clear(), ie_cache_find_evict(), ie_dedup_cache_find_group_for_target(), ie_dedup_cache_find_target(), ie_dedup_reconstruct_into(), and ie_mask_popcount_bytes().
ie_dedup_cache_init()
int ie_dedup_cache_init (ie_dedup_cache_t * c, const ie_dedup_spec_t * spec, const ie_dedup_files_t * files, uint32_t max_tensor_index, uint32_t entry_cap, uint64_t bytes_limit)
Initialize a dedup cache.
This builds fast lookup tables for tensor_index -> target metadata. If bytes_limit is 0, the cache storage is not used (but the lookup and reconstruction helpers still work).
Parameters
c Cache instance.
spec Parsed and validated dedup spec.
files Memory views of defaults/masks/exceptions (must stay valid for cache lifetime).
max_tensor_index Maximum tensor index in the model (used to size lookup tables).
entry_cap Number of cache slots to allocate (used only if bytes_limit > 0).
bytes_limit Soft cap on cached reconstructed bytes. Set to 0 to disable caching.
Returns
0 on success, non-zero on error.
Definition at line 142 of file dedup_cache.c.
 {
   if (!c || !spec || !files) return -1;
   memset(c, 0, sizeof(*c));
   c->spec = spec;
   c->files = *files;
   if (ie_dedup_spec_validate(spec) != 0) return -2;
   /* Allocate target_by_index lookup. */
   c->target_by_index_len = max_tensor_index + 1u;
   c->target_by_index = (const ie_dedup_target_t**)calloc((size_t)c->target_by_index_len, sizeof(void*));
   if (!c->target_by_index) return -3;
   /* Build target lookup table. */
   for (uint32_t gi = 0; gi < spec->ngroups; ++gi) {
     const ie_dedup_group_t* g = &spec->groups[gi];
     for (uint32_t ti = 0; ti < g->ntargets; ++ti) {
       const ie_dedup_target_t* t = &g->targets[ti];
       if (t->tensor_index <= max_tensor_index) {
         c->target_by_index[t->tensor_index] = t;
       }
     }
   }
   /* Cache configuration. */
   c->bytes_limit = bytes_limit;
   c->entry_cap = (bytes_limit > 0 && entry_cap > 0) ? entry_cap : 0;
   if (c->entry_cap > 0) {
     c->entries = (ie_dedup_cache_entry_t*)calloc((size_t)c->entry_cap, sizeof(ie_dedup_cache_entry_t));
     if (!c->entries) {
       free(c->target_by_index);
       memset(c, 0, sizeof(*c));
       return -4;
     }
   }
   return 0;
 }
References ie_dedup_spec_validate().
ie_dedup_reconstruct_into()
int ie_dedup_reconstruct_into (uint8_t * dst, const uint8_t * default_bytes, const uint8_t * mask, const uint8_t * exceptions, uint64_t nbytes)
Reconstruct a target tensor into a caller-provided buffer (lossless).
This performs:
memcpy(default -> dst)
scan mask bits; for each 1-bit at byte index i, overwrite dst[i] from exceptions stream
Parameters
dst Destination buffer (size must be t->nbytes).
default_bytes Pointer to the default blob bytes (size must be t->nbytes).
mask Pointer to mask bytes (size must be t->mask_nbytes).
exceptions Pointer to exception payload bytes (size must be t->exc_nbytes).
nbytes Tensor size in bytes.
Returns
0 on success, non-zero on mismatch (e.g., ran out of exceptions).
Definition at line 65 of file dedup_cache.c.
 {
   if (!dst || !default_bytes || !mask || (!exceptions && nbytes != 0)) return -1;
   if (nbytes == 0) return 0;
   /* Copy default into dst. */
   memcpy(dst, default_bytes, (size_t)nbytes);
   const uint64_t mask_n = ie_dedup_mask_nbytes(nbytes);
   /* Patch exceptions. */
   uint64_t exc_i = 0;
   uint64_t byte_i = 0;
   for (uint64_t mi = 0; mi < mask_n; ++mi) {
     const uint8_t m = mask[mi];
     if (m == 0) {
       byte_i += 8;
       continue;
     }
     /* Process the 8 bits in this mask byte. */
     for (uint32_t bit = 0; bit < 8; ++bit) {
       const uint64_t idx = byte_i + (uint64_t)bit;
       if (idx >= nbytes) break;
       if ((m >> bit) & 1u) {
         dst[idx] = exceptions[exc_i++];
       }
     }
     byte_i += 8;
   }
   /* Optional: caller can compare exc_i with expected exc_nbytes separately. */
   return 0;
 }
References ie_dedup_mask_nbytes().
Referenced by ie_dedup_cache_get_bytes().