Inference Engine (Clocher): engine/src/math/fast_tanh.c File Reference
fast_tanh.c File Reference
Fast tanh approximation (scalar and vector forms) with strict [-1, 1] clamping.
#include "ie_math.h"
#include <math.h>
#include <stddef.h>
Functions
float ie_fast_tanhf (float x)
Fast approximation of hyperbolic tangent with hard clamping.
void ie_vec_tanh_f32 (float *v, size_t n, int fast_tanh)
In-place vector tanh on a contiguous array (legacy API).
void ie_vec_tanh_f32_out (const float *x, float *out, size_t n)
Out-of-place vector tanh on a contiguous array (fast approximation).
void ie_vec_tanh_f32_strided (const float *x, size_t x_stride, float *out, size_t out_stride, size_t n)
Out-of-place vector tanh on strided arrays (fast approximation).
Detailed Description
Fast tanh approximation (scalar and vector forms) with strict [-1, 1] clamping.
The scalar uses a cheap rational approximation for moderate |x| and early saturation for large |x|. Vector helpers call the scalar per element to keep the implementation simple and portable; SIMD paths can be added later.
Definition in file fast_tanh.c.
Function Documentation
ie_fast_tanhf()
float ie_fast_tanhf (float x)
Fast approximation of hyperbolic tangent with hard clamping.
Fast approximation of hyperbolic tanh with strict [-1, 1] range.
Fast scalar tanh approximation.
For large |x| we short-circuit to +/-1.0f. For moderate |x| we use a small rational function that gives a smooth S-curve:
tanh(x) ≈ x * (27 + x^2) / (27 + 9 x^2)
Finally, the result is clamped to [-1, 1] to guarantee range correctness.
Parameters
x Input value.
Returns
Approximated tanh(x) in [-1.0f, 1.0f].
Definition at line 28 of file fast_tanh.c.
{
  /* Early clamp for large magnitude to avoid overflow and extra work. */
  if (x > 5.0f)  return 1.0f;
  if (x < -5.0f) return -1.0f;
  /* Rational approximation (cheap and monotonic on [-3,3]) */
  const float x2  = x * x;
  const float num = x * (27.0f + x2);
  const float den = 27.0f + 9.0f * x2;
  float y = num / den;
  /* Safety clamp for strict range compliance. */
  if (y > 1.0f)  y = 1.0f;
  if (y < -1.0f) y = -1.0f;
  return y;
}
References ie_gemv_rowwise_f32_kernel().
Referenced by ie_vec_tanh_f32(), ie_vec_tanh_f32_out(), and ie_vec_tanh_f32_strided().
ie_vec_tanh_f32()
void ie_vec_tanh_f32 (float * v, size_t n, int fast_tanh)
In-place vector tanh on a contiguous array (legacy API).
Vector tanh on fp32 data (in-place).
If fast_tanh != 0, uses ie_fast_tanhf; otherwise uses libm tanhf. Output values are clamped to [-1, 1] in both modes to satisfy strict bounds.
Parameters
v Pointer to the vector (length n). Modified in-place.
n Number of elements in v.
fast_tanh Non-zero to use the fast approximation; 0 to use libm.
Definition at line 55 of file fast_tanh.c.
{
  if (!v || n == 0) return;
  if (fast_tanh) {
    for (size_t i = 0; i < n; ++i) {
      v[i] = ie_fast_tanhf(v[i]);
    }
  } else {
    for (size_t i = 0; i < n; ++i) {
      float y = tanhf(v[i]);
      if (y > 1.0f)  y = 1.0f;
      if (y < -1.0f) y = -1.0f;
      v[i] = y;
    }
  }
}
References ie_fast_tanhf(), and ie_gemv_rowwise_f32_kernel().
Referenced by main().
ie_vec_tanh_f32_out()
void ie_vec_tanh_f32_out (const float * x, float * out, size_t n)
Out-of-place vector tanh on a contiguous array (fast approximation).
Out-of-place vector tanh on a contiguous array.
Parameters
x Pointer to input array (length n).
out Pointer to output array (length n).
n Number of elements.
Definition at line 78 of file fast_tanh.c.
{
  if (!x || !out || n == 0) return;
  for (size_t i = 0; i < n; ++i) {
    out[i] = ie_fast_tanhf(x[i]);
  }
}
References ie_fast_tanhf(), and ie_gemv_rowwise_f32_kernel().
ie_vec_tanh_f32_strided()
void ie_vec_tanh_f32_strided (const float * x, size_t x_stride, float * out, size_t out_stride, size_t n)
Out-of-place vector tanh on strided arrays (fast approximation).
Out-of-place vector tanh on strided arrays.
Computes for i in [0, n): out[i*out_stride] = tanh(x[i*x_stride]).
Parameters
x Pointer to input array.
x_stride Stride (in elements) between consecutive inputs.
out Pointer to output array.
out_stride Stride (in elements) between consecutive outputs.
n Number of elements to process.
Definition at line 96 of file fast_tanh.c.
{
  if (!x || !out || n == 0) return;
  for (size_t i = 0; i < n; ++i) {
    out[i * out_stride] = ie_fast_tanhf(x[i * x_stride]);
  }
}
References ie_fast_tanhf(), and ie_gemv_rowwise_f32_kernel().