Inference Engine (Clocher): engine/src/gemm_block_sparse.c File Reference
gemm_block_sparse.c File Reference
Block-sparse GEMV kernel for single-precision weights.
#include "sparse_format.h"
#include <stddef.h>
Functions
static const float * block_values_ptr (const ie_block_sparse_matrix_t *m, uint32_t blk_id)
Compute the pointer to the first element of a given block.
void ie_gemv_block_sparse_f32 (const ie_block_sparse_matrix_t *m, const float *x, float *y, const float *bias)
Perform a single-precision block-sparse matrix-vector product.
Detailed Description
Block-sparse GEMV kernel for single-precision weights.
This translation unit implements a reference GEMV kernel for matrices stored in ie_block_sparse_matrix_t (block-row CSR / BSR format). It is intended as a baseline, portable implementation:
Single-threaded by design; higher-level code is responsible for sharding work across threads if desired.
Numerically identical to the dense product (up to floating-point roundoff) when the block-sparse representation is exact.
Safe in the presence of tail blocks (partial coverage at the edges).
The main entry point is:
ie_gemv_block_sparse_f32
Definition in file gemm_block_sparse.c.
Function Documentation
block_values_ptr()
static const float* block_values_ptr (const ie_block_sparse_matrix_t * m, uint32_t blk_id) inline static
Compute the pointer to the first element of a given block.
Parameters
m Block-sparse matrix descriptor (must not be NULL).
blk_id Block index in the [0, m->nnzb) range.
Returns
Pointer into ie_block_sparse_matrix_t::values for the first element of the requested block.
Definition at line 40 of file gemm_block_sparse.c.
{
   const size_t block_elems =
       (size_t)m->block_rows * (size_t)m->block_cols;
   return m->values + (size_t)blk_id * block_elems;
 }
References ie_block_sparse_matrix::block_cols, ie_block_sparse_matrix::block_rows, and ie_block_sparse_matrix::values.
Referenced by ie_gemv_block_sparse_f32().
ie_gemv_block_sparse_f32()
void ie_gemv_block_sparse_f32 (const ie_block_sparse_matrix_t * m, const float * x, float * y, const float * bias)
Perform a single-precision block-sparse matrix-vector product.
This function computes:
y = W * x  (+ bias, if provided)
where W is represented in block-sparse form using ie_block_sparse_matrix_t. The input vector x has length m->cols, and the output y has length m->rows.
Tail blocks:
If the matrix size is not an exact multiple of the block dimensions, the implementation clips accesses to rows and cols, ensuring no out-of-bounds reads/writes occur.
Threading:
This function is intentionally single-threaded. Thread-level parallelism should be managed by higher-level components (e.g., a thread pool).
Parameters
m Block-sparse matrix descriptor (must be fully initialized).
x Input vector of length m->cols (must not be NULL).
y Output vector of length m->rows (must not be NULL).
bias Optional bias vector of length m->rows (may be NULL).
Definition at line 77 of file gemm_block_sparse.c.
{
   if (!m || !x || !y) {
     return;
   }
   const uint32_t rows         = m->rows;
   const uint32_t cols         = m->cols;
   const uint32_t block_rows   = m->block_rows;
   const uint32_t block_cols   = m->block_cols;
   const uint32_t n_block_rows = m->n_block_rows;
   if (rows == 0u || cols == 0u ||
       block_rows == 0u || block_cols == 0u ||
       n_block_rows == 0u) {
     return;
   }
   /* For each block-row, process its constituent row stripes. */
   for (uint32_t br = 0u; br < n_block_rows; ++br) {
     const uint32_t row_start = br * block_rows;
     const uint32_t row_end   = row_start + block_rows;
     /* Iterate within the block-row over actual rows (tail-safe). */
     for (uint32_t local_r = 0u; local_r < block_rows; ++local_r) {
       const uint32_t row = row_start + local_r;
       if (row >= rows) {
         break;
       }
       float acc = bias ? bias[row] : 0.0f;
       const uint32_t blk_begin = m->row_ptr[br];
       const uint32_t blk_end   = m->row_ptr[br + 1u];
       /* Accumulate contributions from all non-zero blocks in this block-row. */
       for (uint32_t bi = blk_begin; bi < blk_end; ++bi) {
         const uint32_t bc = m->col_idx[bi];
         const uint32_t col_block_start = bc * block_cols;
         const float *block = block_values_ptr(m, bi);
         const float *block_row = block + (size_t)local_r * (size_t)block_cols;
         /* Inner product of the local block row with the corresponding
          * slice of x, with clipping for tail columns. */
         for (uint32_t local_c = 0u; local_c < block_cols; ++local_c) {
           const uint32_t col = col_block_start + local_c;
           if (col >= cols) {
             break;
           }
           acc += block_row[local_c] * x[col];
         }
       }
       y[row] = acc;
     }
     (void)row_end; /* suppress unused-variable warning if not referenced */
   }
 }
References ie_block_sparse_matrix::block_cols, ie_block_sparse_matrix::block_rows, block_values_ptr(), ie_block_sparse_matrix::col_idx, ie_block_sparse_matrix::cols, ie_block_sparse_matrix::n_block_rows, ie_block_sparse_matrix::row_ptr, and ie_block_sparse_matrix::rows.
Referenced by cpu_gemv_block_sparse_f32(), main(), and test_block_sparse_gemv_basic().