Inference Engine (Clocher): engine/src/kernels/gemv_generic.c File Reference
gemv_generic.c File Reference
#include "ie_kernels.h"
#include "ie_quant_act.h"
#include <stddef.h>
#include <stdint.h>
#include <string.h>
Functions
void ie_gemv_f32_avx2_impl (const float *W, const float *x, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k)
AVX2/FMA GEMV (float path), provided by gemv_avx2.c.
void ie_gemv_qi8_f32_avx2_impl (const float *W, const int8_t *x_q, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k, ie_act_i8_params params, int symmetric)
AVX2/FMA GEMV with INT8 activations (per-tensor params).
static void gemv_generic_impl (const float *W, const float *x, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k)
Generic C GEMV: y = W * x (+bias), optional blocked-K layout.
static void gemv_qi8_f32_fused_c_impl (const float *W, const int8_t *x_q, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k, ie_act_i8_params params, int symmetric)
GEMV with per-tensor INT8 activations (fused dequantization), C path.
static void gemv_qi8pg_f32_fused_c_impl (const float *W, const int8_t *x_q, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k, size_t group_size, const float *scales, const int8_t *zeros, int symmetric)
GEMV with per-group INT8 activations (fused dequantization), C path.
static float ie_decode_fp8_e4m3 (uint8_t v)
Decode FP8 E4M3 value to float (flush subnormals).
static float ie_decode_fp8_e5m2 (uint8_t v)
Decode FP8 E5M2 value to float (IEEE-like; NaNs/Inf handled).
void ie_kernels_install (int use_avx2)
Install the best available float GEMV kernel for this process.
void ie_gemv_f32 (const float *W, const float *x, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k)
Dispatch GEMV (float path) to the installed kernel.
void ie_gemv_qi8_f32 (const float *W, const int8_t *x_q, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k, ie_act_i8_params params, int symmetric)
GEMV with per-tensor INT8 activations, auto-dispatch (AVX2 or C).
void ie_gemv_qi8pg_f32 (const float *W, const int8_t *x_q, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k, size_t group_size, const float *scales, const int8_t *zeros, int symmetric)
GEMV with per-group INT8 activations (fused), C fallback.
void ie_gemv_qfp8_f32 (const float *W, const uint8_t *x_fp8, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k, ie_fp8_format fmt)
GEMV with FP8 activations (E4M3/E5M2), fused decode (C fallback).
Variables
static void(* s_gemv_f32)(const float *, const float *, float *, size_t, size_t, const float *, size_t) = NULL
Installed float GEMV kernel (defaults to generic C).
Function Documentation
gemv_generic_impl()
static void gemv_generic_impl (const float * W, const float * x, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k) static
Generic C GEMV: y = W * x (+bias), optional blocked-K layout.
The routine multiplies a row-major (or "blocked-K contiguous") matrix W by a dense vector x, accumulating into y. If blk_k is non-zero, the inner loop processes chunks of size blk_k to better match cache lines.
Parameters
W Pointer to weights (row-major; each row has cols floats).
x Input vector (length cols).
y Output vector (length rows).
rows Number of rows in W and y.
cols Number of columns in W and length of x.
bias Optional bias to add per-output row (may be NULL).
blk_k Column block size; set 0 to disable blocking.
Definition at line 73 of file gemv_generic.c.
{
   const size_t BK = (blk_k > 0 ? blk_k : cols);
   for (size_t r = 0; r < rows; ++r) {
     const float *wrow = W + r * cols;
     float acc = 0.0f;
     size_t kofs = 0;
     for (size_t k0 = 0; k0 < cols; k0 += BK) {
       const size_t klen = (k0 + BK <= cols) ? BK : (cols - k0);
       const float *wblk = wrow + kofs;
       const float *xblk = x + k0;
       for (size_t k = 0; k < klen; ++k) acc += wblk[k] * xblk[k];
       kofs += klen;
     }
     if (bias) acc += bias[r];
     y[r] = acc;
   }
 }
Referenced by ie_kernels_install().
gemv_qi8_f32_fused_c_impl()
static void gemv_qi8_f32_fused_c_impl (const float * W, const int8_t * x_q, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k, ie_act_i8_params params, int symmetric) static
GEMV with per-tensor INT8 activations (fused dequantization), C path.
Dequantization model: real = scale * (q - zero_point). This function multiplies float weights by dequantized INT8 activations without materializing a separate float vector.
Parameters
W Weights (row-major).
x_q INT8 activations (length cols).
y Output (length rows).
rows Rows.
cols Cols.
bias Optional bias (may be NULL).
blk_k Column block size; 0 means plain row-major.
params Per-tensor INT8 parameters (scale, zero_point).
symmetric Non-zero if symmetric (zero_point=0). Informational only.
Definition at line 114 of file gemv_generic.c.
{
   (void)symmetric;
   const size_t BK = (blk_k > 0 ? blk_k : cols);
   const float s = params.scale;
   const int z = (int)params.zero_point;
   for (size_t r = 0; r < rows; ++r) {
     const float *wrow = W + r * cols;
     float acc = 0.0f;
     size_t kofs = 0;
     for (size_t k0 = 0; k0 < cols; k0 += BK) {
       const size_t klen = (k0 + BK <= cols) ? BK : (cols - k0);
       const float *wblk = wrow + kofs;
       const int8_t *xblk = x_q + k0;
       for (size_t k = 0; k < klen; ++k) {
         const float xv = s * ((int)xblk[k] - z);
         acc += wblk[k] * xv;
       }
       kofs += klen;
     }
     if (bias) acc += bias[r];
     y[r] = acc;
   }
 }
References ie_act_i8_params::scale, and ie_act_i8_params::zero_point.
Referenced by ie_gemv_qi8_f32().
gemv_qi8pg_f32_fused_c_impl()
static void gemv_qi8pg_f32_fused_c_impl (const float * W, const int8_t * x_q, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k, size_t group_size, const float * scales, const int8_t * zeros, int symmetric) static
GEMV with per-group INT8 activations (fused dequantization), C path.
Each contiguous group of group_size elements in x_q uses its own (scale, zero). The last group may be shorter.
Parameters
W Weights (row-major).
x_q INT8 activations.
y Output.
rows Rows.
cols Cols.
bias Optional bias (may be NULL).
blk_k Column block size.
group_size Activation quantization group size.
scales Scales array, length ceil(cols/group_size).
zeros Zero-points array, length ceil(cols/group_size).
symmetric Non-zero if symmetric (informational only).
Definition at line 163 of file gemv_generic.c.
{
   (void)symmetric;
   const size_t BK = (blk_k > 0 ? blk_k : cols);
   for (size_t r = 0; r < rows; ++r) {
     const float *wrow = W + r * cols;
     float acc = 0.0f;
     size_t kofs = 0;
     for (size_t k0 = 0; k0 < cols; k0 += BK) {
       const size_t klen = (k0 + BK <= cols) ? BK : (cols - k0);
       const float *wblk = wrow + kofs;
       const int8_t *xblk = x_q + k0;
       for (size_t k = 0; k < klen; ++k) {
         const size_t g = (k0 + k) / group_size;
         const float s = scales[g];
         const int z = (int)zeros[g];
         const float xv = s * ((int)xblk[k] - z);
         acc += wblk[k] * xv;
       }
       kofs += klen;
     }
     if (bias) acc += bias[r];
     y[r] = acc;
   }
 }
Referenced by ie_gemv_qi8pg_f32().
ie_decode_fp8_e4m3()
static float ie_decode_fp8_e4m3 (uint8_t v) inline static
Decode FP8 E4M3 value to float (flush subnormals).
Parameters
v 8-bit FP8 E4M3 value.
Returns
32-bit float approximation.
Definition at line 201 of file gemv_generic.c.
{
   if (v == 0u) return 0.0f;
   const uint8_t sign = (v >> 7) & 0x1;
   const uint8_t exp = (v >> 3) & 0xF;
   const uint8_t man = (v & 0x7);
   if (exp == 0) return sign ? -0.0f : 0.0f;
   const int bias = 7;
   const int e = (int)exp - bias;
   const float frac = (float)man / 8.0f;
   const float val = (1.0f + frac) * (float)(1u << e);
   return sign ? -val : val;
 }
Referenced by ie_gemv_qfp8_f32().
ie_decode_fp8_e5m2()
static float ie_decode_fp8_e5m2 (uint8_t v) inline static
Decode FP8 E5M2 value to float (IEEE-like; NaNs/Inf handled).
Parameters
v 8-bit FP8 E5M2 value.
Returns
32-bit float approximation (quiet NaN for FP8 NaN payloads).
Definition at line 219 of file gemv_generic.c.
{
   const uint8_t sign = (v >> 7) & 0x1;
   const uint8_t exp = (v >> 2) & 0x1F;
   const uint8_t man = (v & 0x3);
   if (exp == 0) return sign ? -0.0f : 0.0f;
   if (exp == 0x1F) {
     if (man == 0) return sign ? -(__builtin_inff()) : (__builtin_inff());
     volatile float qnan = __builtin_nanf("0x1");
     return qnan;
   }
   const int bias = 15;
   const int e = (int)exp - bias;
   const float frac = (float)man / 4.0f;
   const float val = (1.0f + frac) * (float)(1u << e);
   return sign ? -val : val;
 }
Referenced by ie_gemv_qfp8_f32().
ie_gemv_f32()
void ie_gemv_f32 (const float * W, const float * x, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k)
Dispatch GEMV (float path) to the installed kernel.
GEMV: y[r] = dot(W[r, :], x) [+ bias[r]] for r in [0, rows).
Parameters
W Weights pointer.
x Input vector.
y Output vector.
rows Rows in W/y.
cols Cols in W/x.
bias Optional bias (may be NULL).
blk_k Column-block size; 0 for plain row-major.
Definition at line 279 of file gemv_generic.c.
{
   if (!s_gemv_f32) ie_kernels_install(/*use_avx2=*/1);
   s_gemv_f32(W, x, y, rows, cols, bias, blk_k);
 }
References ie_kernels_install(), and s_gemv_f32.
Referenced by cpu_gemv_f32(), test_gemv_rowmajor_no_bias(), and test_gemv_rowmajor_with_bias().
ie_gemv_f32_avx2_impl()
void ie_gemv_f32_avx2_impl (const float * W, const float * x, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k)
AVX2/FMA GEMV (float path), provided by gemv_avx2.c.
Note
This symbol is optional; the dispatcher checks CPU features before use.
AVX2/FMA GEMV (float path), provided by gemv_avx2.c.
The implementation accepts either plain row-major W or rows packed as "blocked-K contiguous" (see pretranspose docs). In the latter case, each row still has cols elements but the inner loop can iterate in chunks of blk_k to promote cache locality.
Parameters
W Weights (row-major or blocked-K contiguous per row).
x Input vector (length cols).
y Output vector (length rows).
rows Number of rows.
cols Number of cols.
bias Optional bias (length rows), may be NULL.
blk_k Column block size; 0 => treat as single block of size cols.
Definition at line 39 of file gemv_avx2.c.
{
   const size_t BK = (blk_k > 0 ? blk_k : cols);
   for (size_t r = 0; r < rows; ++r) {
     const float *wrow = W + r * cols;
     float acc_scalar = 0.0f;
     __m256 vacc0 = _mm256_setzero_ps();
     __m256 vacc1 = _mm256_setzero_ps();
     __m256 vacc2 = _mm256_setzero_ps();
     __m256 vacc3 = _mm256_setzero_ps();
     for (size_t k0 = 0; k0 < cols; k0 += BK) {
       const size_t klen = (k0 + BK <= cols) ? BK : (cols - k0);
       const float *wblk = wrow + k0;
       const float *xblk = x + k0;
       /* Prefetch next chunk (temporal hint) */
       if (k0 + 2 * BK < cols) {
         _mm_prefetch((const char *)(wblk + BK), _MM_HINT_T0);
         _mm_prefetch((const char *)(xblk + BK), _MM_HINT_T0);
       }
       size_t k = 0;
       for (; k + 32 <= klen; k += 32) {
         __m256 w0 = _mm256_loadu_ps(wblk + k + 0);
         __m256 x0 = _mm256_loadu_ps(xblk + k + 0);
         vacc0 = _mm256_fmadd_ps(w0, x0, vacc0);
         __m256 w1 = _mm256_loadu_ps(wblk + k + 8);
         __m256 x1 = _mm256_loadu_ps(xblk + k + 8);
         vacc1 = _mm256_fmadd_ps(w1, x1, vacc1);
         __m256 w2 = _mm256_loadu_ps(wblk + k + 16);
         __m256 x2 = _mm256_loadu_ps(xblk + k + 16);
         vacc2 = _mm256_fmadd_ps(w2, x2, vacc2);
         __m256 w3 = _mm256_loadu_ps(wblk + k + 24);
         __m256 x3 = _mm256_loadu_ps(xblk + k + 24);
         vacc3 = _mm256_fmadd_ps(w3, x3, vacc3);
       }
       for (; k + 8 <= klen; k += 8) {
         __m256 wv = _mm256_loadu_ps(wblk + k);
         __m256 xv = _mm256_loadu_ps(xblk + k);
         vacc0 = _mm256_fmadd_ps(wv, xv, vacc0);
       }
       for (; k < klen; ++k) {
         acc_scalar += wblk[k] * xblk[k];
       }
     }
     /* Reduce four accumulators to one scalar */
     __m256 t01 = _mm256_add_ps(vacc0, vacc1);
     __m256 t23 = _mm256_add_ps(vacc2, vacc3);
     __m256 t = _mm256_add_ps(t01, t23);
     __m128 low = _mm256_castps256_ps128(t);
     __m128 high = _mm256_extractf128_ps(t, 1);
     __m128 sum = _mm_add_ps(low, high);
     __m128 shf = _mm_movehdup_ps(sum);
     sum = _mm_add_ps(sum, shf);
     shf = _mm_movehl_ps(shf, sum);
     sum = _mm_add_ss(sum, shf);
     float acc = _mm_cvtss_f32(sum) + acc_scalar;
     if (bias) acc += bias[r];
     y[r] = acc;
   }
 }
Referenced by ie_gemv_qi8_f32_avx2_impl(), and ie_kernels_install().
ie_gemv_qfp8_f32()
void ie_gemv_qfp8_f32 (const float * W, const uint8_t * x_fp8, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k, ie_fp8_format fmt)
GEMV with FP8 activations (E4M3/E5M2), fused decode (C fallback).
Parameters
W Weights (row-major or blocked-K).
x_fp8 FP8 activations (bytes).
y Output.
rows Rows.
cols Cols.
bias Optional bias (may be NULL).
blk_k Column block size; 0 means plain row-major.
fmt FP8 format selector (IE_FP8_E4M3 or IE_FP8_E5M2).
Definition at line 347 of file gemv_generic.c.
{
   const size_t BK = (blk_k > 0 ? blk_k : cols);
   const int use_e4m3 = (fmt == IE_FP8_E4M3);
   for (size_t r = 0; r < rows; ++r) {
     const float *wrow = W + r * cols;
     float acc = 0.0f;
     size_t kofs = 0;
     for (size_t k0 = 0; k0 < cols; k0 += BK) {
       const size_t klen = (k0 + BK <= cols) ? BK : (cols - k0);
       const float *wblk = wrow + kofs;
       const uint8_t *xblk = x_fp8 + k0;
       for (size_t k = 0; k < klen; ++k) {
         const uint8_t b = xblk[k];
         const float xv =
             use_e4m3 ? ie_decode_fp8_e4m3(b) : ie_decode_fp8_e5m2(b);
         acc += wblk[k] * xv;
       }
       kofs += klen;
     }
     if (bias) acc += bias[r];
     y[r] = acc;
   }
 }
References ie_decode_fp8_e4m3(), ie_decode_fp8_e5m2(), and IE_FP8_E4M3.
ie_gemv_qi8_f32()
void ie_gemv_qi8_f32 (const float * W, const int8_t * x_q, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k, ie_act_i8_params params, int symmetric)
GEMV with per-tensor INT8 activations, auto-dispatch (AVX2 or C).
Parameters
W Weights (row-major or blocked-K).
x_q INT8 activations (length cols).
y Output (length rows).
rows Rows.
cols Cols.
bias Optional bias (may be NULL).
blk_k Column block size; 0 means plain row-major.
params Per-tensor INT8 parameters (scale, zero_point).
symmetric Non-zero if symmetric (zero_point=0). Informational.
Definition at line 298 of file gemv_generic.c.
{
 #if defined(__GNUC__) || defined(__clang__)
   if (__builtin_cpu_supports("avx2") && __builtin_cpu_supports("fma")) {
     ie_gemv_qi8_f32_avx2_impl(W, x_q, y, rows, cols, bias, blk_k, params,
                               symmetric);
     return;
   }
 #endif
   gemv_qi8_f32_fused_c_impl(W, x_q, y, rows, cols, bias, blk_k, params,
                             symmetric);
 }
References gemv_qi8_f32_fused_c_impl(), and ie_gemv_qi8_f32_avx2_impl().
ie_gemv_qi8_f32_avx2_impl()
void ie_gemv_qi8_f32_avx2_impl (const float * W, const int8_t * x_q, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k, ie_act_i8_params params, int symmetric)
AVX2/FMA GEMV with INT8 activations (per-tensor params).
Note
Optional symbol. The dispatcher guards its use with a CPU feature test.
AVX2/FMA GEMV with INT8 activations (per-tensor params).
This path dequantizes activations into a temporary aligned float buffer, then calls the AVX2 float GEMV core ie_gemv_f32_avx2_impl().
Parameters
W Weights (row-major).
x_q INT8 activations.
y Output.
rows Rows.
cols Cols.
bias Optional bias (may be NULL).
blk_k Column block size; 0 => treat as single block.
params INT8 per-tensor params (scale, zero_point).
symmetric Non-zero if symmetric (informational).
Definition at line 127 of file gemv_avx2.c.
{
   (void)symmetric;
 #if defined(_MSC_VER)
   float *x = (float *)_aligned_malloc(cols * sizeof(float), 64);
   if (!x) return;
 #else
   float *x = (float *)aligned_alloc(64, cols * sizeof(float));
   if (!x) return;
 #endif
   const float s = params.scale;
   const int z = (int)params.zero_point;
   size_t i = 0;
   for (; i + 8 <= cols; i += 8) {
     __m128i q = _mm_loadl_epi64((const __m128i *)(x_q + i)); /* 8x i8 */
     __m256i qi = _mm256_cvtepi8_epi32(q);                    /* -> 8x i32 */
     __m256 qf = _mm256_cvtepi32_ps(qi);                      /* -> 8x f32 */
     __m256 zf = _mm256_set1_ps((float)z);
     __m256 sf = _mm256_set1_ps(s);
     __m256 xf = _mm256_mul_ps(sf, _mm256_sub_ps(qf, zf));
     _mm256_storeu_ps(x + i, xf);
   }
   for (; i < cols; ++i) x[i] = s * ((int)x_q[i] - z);
   ie_gemv_f32_avx2_impl(W, x, y, rows, cols, bias, blk_k);
 #if defined(_MSC_VER)
   _aligned_free(x);
 #else
   free(x);
 #endif
 }
References ie_gemv_f32_avx2_impl(), ie_act_i8_params::scale, and ie_act_i8_params::zero_point.
Referenced by ie_gemv_qi8_f32().
ie_gemv_qi8pg_f32()
void ie_gemv_qi8pg_f32 (const float * W, const int8_t * x_q, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k, size_t group_size, const float * scales, const int8_t * zeros, int symmetric)
GEMV with per-group INT8 activations (fused), C fallback.
Parameters
W Weights.
x_q INT8 activations.
y Output.
rows Rows.
cols Cols.
bias Optional bias (may be NULL).
blk_k Column block size.
group_size Activation quantization group size.
scales Array of scales (ceil(cols/group_size)).
zeros Array of zero points (ceil(cols/group_size)).
symmetric Non-zero if symmetric (informational).
Definition at line 327 of file gemv_generic.c.
{
   gemv_qi8pg_f32_fused_c_impl(W, x_q, y, rows, cols, bias, blk_k, group_size,
                               scales, zeros, symmetric);
 }
References gemv_qi8pg_f32_fused_c_impl().
ie_kernels_install()
void ie_kernels_install (int use_avx2)
Install the best available float GEMV kernel for this process.
Install the best available CPU kernels at runtime.
On x86 with GCC/Clang, the dispatcher uses __builtin_cpu_supports("avx2") and prefers the AVX2 implementation when available; otherwise it installs the generic C fallback.
Parameters
use_avx2 Non-zero to allow AVX2 selection when supported.
Definition at line 249 of file gemv_generic.c.
{
   int use_avx2_runtime = 0;
 #if defined(__x86_64__) || defined(_M_X64) || defined(__i386__)
 #if defined(__GNUC__) || defined(__clang__)
   if (use_avx2) {
     if (__builtin_cpu_supports("avx2") && __builtin_cpu_supports("fma")) {
       use_avx2_runtime = 1;
     }
   }
 #endif
 #endif
   if (use_avx2_runtime) {
     s_gemv_f32 = ie_gemv_f32_avx2_impl;
   } else {
     s_gemv_f32 = gemv_generic_impl;
   }
 }
References gemv_generic_impl(), ie_gemv_f32_avx2_impl(), and s_gemv_f32.
Referenced by ie_gemv_f32(), and main().
Variable Documentation
s_gemv_f32
void(* s_gemv_f32) (const float *, const float *, float *, size_t, size_t, const float *, size_t) (const float * , const float * , float * , size_t , size_t , const float * , size_t) = NULL static
Installed float GEMV kernel (defaults to generic C).
Definition at line 51 of file gemv_generic.c.
Referenced by ie_gemv_f32(), and ie_kernels_install().