Inference Engine (Clocher): engine/src/runtime/generate_gptoss.c File Reference
generate_gptoss.c File Reference
Convenience token generation wrapper for the GPT-OSS forward pass.
#include "generate_gptoss.h"
#include <stdlib.h>
#include <string.h>
#include "gptoss_hparams.h"
#include "ie_kv_cache.h"
#include "ie_sampling.h"
#include "ie_tokenizer_gptoss.h"
Functions
ie_sample_cfg_t ie_default_sample_cfg (void)
static void ie_free_ptr (void **p)
int ie_generate_gptoss (const ie_device_t *dev, const ie_weights_t *weights, const char *model_dir, const ie_tok_gptoss_t *tok, const char *prompt, uint32_t max_new, const ie_sample_cfg_t *cfg, uint64_t seed, int *out_ids, uint32_t *out_count)
Generate up to max_new tokens for a prompt string using GPT-OSS.
Detailed Description
Convenience token generation wrapper for the GPT-OSS forward pass.
Definition in file generate_gptoss.c.
Function Documentation
ie_default_sample_cfg()
ie_sample_cfg_t ie_default_sample_cfg (void)
Definition at line 20 of file generate_gptoss.c.
{
  ie_sample_cfg_t c;
  memset(&c, 0, sizeof(c));
  c.kind = IE_SAMPLE_TOPP;
  c.temperature = 1.0f;
  c.top_k = 40u;
  c.top_p = 0.95f;
  c.disallow_token0 = 0;
  return c;
}
References ie_sample_cfg_s::disallow_token0, IE_SAMPLE_TOPP, ie_sample_cfg_s::kind, ie_sample_cfg_s::temperature, ie_sample_cfg_s::top_k, and ie_sample_cfg_s::top_p.
Referenced by ie_generate_gptoss().
ie_free_ptr()
static void ie_free_ptr (void ** p) static
Definition at line 31 of file generate_gptoss.c.
{
  if (p && *p) {
    free(*p);
    *p = NULL;
  }
}
Referenced by ie_generate_gptoss().
ie_generate_gptoss()
int ie_generate_gptoss (const ie_device_t * dev, const ie_weights_t * w, const char * model_dir, const ie_tok_gptoss_t * tok, const char * prompt, uint32_t max_new, const ie_sample_cfg_t * sample_cfg, uint64_t seed, int * out_tokens, uint32_t * out_n_tokens)
Generate up to max_new tokens for a prompt string using GPT-OSS.
This function performs: 1) Load minimal hyperparameters from model_dir/config.json. 2) Encode prompt into token IDs using tok. 3) Create an inference context via ie_gptoss_infer_create(). 4) Allocate a KV cache sized from hyperparameters. 5) Run prefill over the prompt, then step+sample to generate new tokens.
The generation loop is:
logits = prefill(prompt)
repeat max_new: next = sample(logits) out_tokens[i] = next logits = step(next)
Requirements:
tok must be a valid tokenizer handle capable of encoding the prompt.
Real inference must exist in ie_gptoss_infer_prefill/step.
Parameters
dev Device backend handle (required).
w Loaded weights handle (required).
model_dir Model directory containing config.json (required).
tok Tokenizer handle opened from tokenizer.json (required).
prompt UTF-8 prompt string (non-NULL; may be empty).
max_new Maximum number of tokens to generate.
sample_cfg Sampling configuration (may be NULL for defaults).
seed RNG seed (0 is remapped to a non-zero value).
out_tokens Output buffer (length at least max_new when max_new > 0).
out_n_tokens Receives number of generated tokens.
Returns
Status code from ie_generate_gptoss_status_t.
Definition at line 38 of file generate_gptoss.c.
{
  if (out_count) *out_count = 0;
  if (!dev || !weights || !model_dir || !tok || !prompt || !out_ids || !out_count) return -1;
  if (max_new == 0) return 0;
  int rc = 0;
  ie_gptoss_hparams_t hp;
  memset(&hp, 0, sizeof(hp));
  if (gptoss_hparams_load(model_dir, &hp) != 0) return -2;
  /* Encode the prompt. */
  uint32_t prompt_n = 0;
  if (ie_tok_gptoss_encode(tok, prompt, NULL, &prompt_n) != 0) return -3;
  if (prompt_n == 0) return -4;
  uint32_t *prompt_ids = (uint32_t *)malloc((size_t)prompt_n * sizeof(uint32_t));
  if (!prompt_ids) return -5;
  {
    uint32_t tmp = prompt_n;
    if (ie_tok_gptoss_encode(tok, prompt, prompt_ids, &tmp) != 0) {
      ie_free_ptr((void **)&prompt_ids);
      return -6;
    }
    prompt_n = tmp;
    if (prompt_n == 0) {
      ie_free_ptr((void **)&prompt_ids);
      return -7;
    }
  }
  /* Create inference context. */
  ie_gptoss_infer_t *inf = NULL;
  if (ie_gptoss_infer_create(dev, weights, &hp, &inf) != 0 || !inf) {
    ie_free_ptr((void **)&prompt_ids);
    return -8;
  }
  /* KV cache: one layer object per transformer layer. */
  const uint32_t n_layers = (hp.n_layers > 0) ? (uint32_t)hp.n_layers : 0u;
  if (n_layers == 0) {
    ie_gptoss_infer_destroy(inf);
    ie_free_ptr((void **)&prompt_ids);
    return -9;
  }
  ie_kv_cache *kv = (ie_kv_cache *)calloc((size_t)n_layers, sizeof(ie_kv_cache));
  if (!kv) {
    ie_gptoss_infer_destroy(inf);
    ie_free_ptr((void **)&prompt_ids);
    return -10;
  }
  ie_kv_opts kv_opts;
  memset(&kv_opts, 0, sizeof(kv_opts));
  kv_opts.max_seq = (uint32_t)((hp.max_seq > 0) ? hp.max_seq : 1);
  kv_opts.heads = (uint32_t)((hp.n_kv_heads > 0) ? hp.n_kv_heads : hp.n_heads);
  kv_opts.head_dim = (uint32_t)((hp.d_head > 0) ? hp.d_head : 1);
  kv_opts.storage = IE_KV_STORAGE_F32;
  kv_opts.group_size = 0;
  kv_opts.symmetric = 0;
  kv_opts.fp8_format = IE_FP8_E4M3;
  if (ie_kv_init_layers(kv, n_layers, &kv_opts) != 0) {
    ie_kv_free_layers(kv, n_layers);
    ie_free_ptr((void **)&kv);
    ie_gptoss_infer_destroy(inf);
    ie_free_ptr((void **)&prompt_ids);
    return -11;
  }
  const size_t vocab = (size_t)((hp.vocab_size > 0) ? hp.vocab_size : 0);
  if (vocab == 0) {
    ie_kv_free_layers(kv, n_layers);
    ie_free_ptr((void **)&kv);
    ie_gptoss_infer_destroy(inf);
    ie_free_ptr((void **)&prompt_ids);
    return -12;
  }
  float *logits = (float *)malloc(vocab * sizeof(float));
  if (!logits) {
    ie_kv_free_layers(kv, n_layers);
    ie_free_ptr((void **)&kv);
    ie_gptoss_infer_destroy(inf);
    ie_free_ptr((void **)&prompt_ids);
    return -13;
  }
  if (ie_gptoss_infer_prefill(inf, kv, prompt_ids, (size_t)prompt_n, logits) != 0) {
    ie_free_ptr((void **)&logits);
    ie_kv_free_layers(kv, n_layers);
    ie_free_ptr((void **)&kv);
    ie_gptoss_infer_destroy(inf);
    ie_free_ptr((void **)&prompt_ids);
    return -14;
  }
  ie_rng_t rng;
  ie_rng_init(&rng, (seed == 0) ? 1u : seed);
  ie_sample_cfg_t local_cfg;
  if (cfg) {
    local_cfg = *cfg;
  } else {
    local_cfg = ie_default_sample_cfg();
  }
  uint32_t *idx_scratch = NULL;
  float *prob_scratch = NULL;
  if (local_cfg.kind != IE_SAMPLE_GREEDY) {
    idx_scratch = (uint32_t *)malloc(vocab * sizeof(uint32_t));
    prob_scratch = (float *)malloc(vocab * sizeof(float));
    if (!idx_scratch || !prob_scratch) {
      ie_free_ptr((void **)&prob_scratch);
      ie_free_ptr((void **)&idx_scratch);
      ie_free_ptr((void **)&logits);
      ie_kv_free_layers(kv, n_layers);
      ie_free_ptr((void **)&kv);
      ie_gptoss_infer_destroy(inf);
      ie_free_ptr((void **)&prompt_ids);
      return -15;
    }
  }
  uint32_t produced = 0;
  for (uint32_t i = 0; i < max_new; ++i) {
    uint32_t next_id = 0;
    if (ie_sample_next(logits,
                       vocab,
                       &local_cfg,
                       &rng,
                       idx_scratch,
                       prob_scratch,
                       vocab,
                       &next_id) != 0)
    {
      rc = -16;
      break;
    }
    out_ids[produced] = (int)next_id;
    produced++;
    if (ie_gptoss_infer_step(inf, kv, next_id, logits) != 0) {
      rc = -17;
      break;
    }
  }
  *out_count = produced;
  ie_free_ptr((void **)&prob_scratch);
  ie_free_ptr((void **)&idx_scratch);
  ie_free_ptr((void **)&logits);
  ie_kv_free_layers(kv, n_layers);
  ie_free_ptr((void **)&kv);
  ie_gptoss_infer_destroy(inf);
  ie_free_ptr((void **)&prompt_ids);
  return rc;
}
References ie_gptoss_hparams::d_head, ie_kv_opts::fp8_format, gptoss_hparams_load(), ie_kv_opts::group_size, ie_kv_opts::head_dim, ie_kv_opts::heads, ie_default_sample_cfg(), IE_FP8_E4M3, ie_free_ptr(), ie_gptoss_infer_create(), ie_gptoss_infer_destroy(), ie_gptoss_infer_prefill(), ie_gptoss_infer_step(), ie_kv_free_layers(), ie_kv_init_layers(), IE_KV_STORAGE_F32, ie_rng_init(), IE_SAMPLE_GREEDY, ie_sample_next(), ie_tok_gptoss_encode(), ie_gptoss_hparams::max_seq, ie_kv_opts::max_seq, ie_gptoss_hparams::n_heads, ie_gptoss_hparams::n_kv_heads, ie_gptoss_hparams::n_layers, ie_kv_opts::storage, ie_kv_opts::symmetric, and ie_gptoss_hparams::vocab_size.