Inference Engine (Clocher): Level Zero (oneAPI) GPU backend
Level Zero (oneAPI) GPU backend
C-callable API to launch kernels via Intel Level Zero.
Typedefs
typedef enum ie_act_kind_e ie_act_kind_t
Activation kinds (must match the kernel’s expectations).
Enumerations
enum ie_act_kind_e { IE_ACT_NONE = 0 , IE_ACT_RELU = 1 , IE_ACT_TANH = 2 }
Activation kinds (must match the kernel’s expectations).
Functions
const char * ie_ze_last_error_string (void)
Get the last error message set by this backend (thread-local).
int ie_ze_launch_gemv_rowwise_f32 (const float *W, const float *x, float *y, int rows, int cols, int ldW, float alpha, float beta)
Row-wise GEMV FP32: y = alpha * W * x + beta * y.
int ie_ze_launch_gemv_bias_act_f32 (const float *W, const float *x, const float *bias, float *y, int rows, int cols, int ldW, float alpha, float beta, ie_act_kind_t act)
Fused GEMV + bias + activation: y = act(alpha*W*x + bias + beta*y).
int ie_ze_launch_vec_tanh_f32 (float *y, const float *x, int n)
Vector tanh: y[i] = tanh(x[i]) for i in [0, n).
int ie_ze_launch_pack_w_blockedk_f32 (float *Wp, const float *W, int rows, int cols, int ldW, int block_k)
Pack W (row-major) into Blocked-K layout into Wp.
Detailed Description
C-callable API to launch kernels via Intel Level Zero.
Typedef Documentation
ie_act_kind_t
typedef enum ie_act_kind_e ie_act_kind_t
#include <engine/src/kernels/ze/ie_kernel_ze.cpp>
Activation kinds (must match the kernel’s expectations).
Enumeration Type Documentation
ie_act_kind_e
enum ie_act_kind_e
#include <engine/src/kernels/ze/ie_kernel_ze.cpp>
Activation kinds (must match the kernel’s expectations).
Enumerator
IE_ACT_NONE
Identity.
IE_ACT_RELU
ReLU.
IE_ACT_TANH
tanh().
Definition at line 56 of file ie_kernel_ze.cpp.
{
  IE_ACT_NONE = 0,
  IE_ACT_RELU = 1,
  IE_ACT_TANH = 2
} ie_act_kind_t;
Function Documentation
ie_ze_last_error_string()
const char * ie_ze_last_error_string (void)
#include <engine/src/kernels/ze/ie_kernel_ze.cpp>
Get the last error message set by this backend (thread-local).
Returns
NUL-terminated message; never NULL (may be empty string).
Definition at line 400 of file ie_kernel_ze.cpp.
{
  return g_err;
}
References g_err.
ie_ze_launch_gemv_bias_act_f32()
int ie_ze_launch_gemv_bias_act_f32 (const float * W, const float * x, const float * bias, float * y, int rows, int cols, int ldW, float alpha, float beta, ie_act_kind_t act)
#include <engine/src/kernels/ze/ie_kernel_ze.cpp>
Fused GEMV + bias + activation: y = act(alpha*W*x + bias + beta*y).
Fused GEMV + bias + activation: y = act(alpha*W*x + bias + beta*y).
Parameters
W Host pointer to row-major matrix (rows x ldW).
x Host pointer to vector (length cols).
bias Host pointer to per-row bias (length rows) or NULL.
y Host pointer to output vector (length rows).
rows Number of rows.
cols Number of cols.
ldW Leading dimension of W (>= cols).
alpha Scale for W*x.
beta Scale for existing y (0 to overwrite).
act Activation kind (ie_act_kind_t).
Returns
0 on success; negative on error.
Parameters
W Host pointer to row-major matrix (rows x ldW).
x Host pointer to vector (length cols).
bias Host pointer to per-row bias (length rows) or NULL.
y Host pointer to output vector (length rows).
rows Number of rows.
cols Number of cols.
ldW Leading dimension of W (>= cols).
alpha Scale for W*x.
beta Scale for existing y (0 to overwrite).
act Activation kind (ie_act_kind_t).
Returns
0 on success; negative on error.
Definition at line 462 of file ie_kernel_ze.cpp.
{
  set_err(nullptr);
  if (!W || !x || !y || rows <= 0 || cols <= 0 || ldW < cols) {
    set_err("invalid arguments");
    return -1;
  }
  int rc = ensure_module_ready();
  if (rc < 0) return rc;
  size_t szW = (size_t)rows * (size_t)ldW * sizeof(float);
  size_t szx = (size_t)cols * sizeof(float);
  size_t szy = (size_t)rows * sizeof(float);
  size_t szb = (size_t)rows * sizeof(float);
  void *dW=nullptr, *dx=nullptr, *dy=nullptr, *db=nullptr;
  if ((rc = dalloc(szW, &dW)) < 0) return rc;
  if ((rc = dalloc(szx, &dx)) < 0) { dfree(dW); return rc; }
  if ((rc = dalloc(szy, &dy)) < 0) { dfree(dx); dfree(dW); return rc; }
  if (bias) {
    if ((rc = dalloc(szb, &db)) < 0) { dfree(dy); dfree(dx); dfree(dW); return rc; }
  }
  if ((rc = memcpy_imm(dW, W, szW)) < 0) goto CLEANUP;
  if ((rc = memcpy_imm(dx, x, szx)) < 0) goto CLEANUP;
  if (bias)     { if ((rc = memcpy_imm(db, bias, szb)) < 0) goto CLEANUP; }
  if (beta!=0.f){ if ((rc = memcpy_imm(dy, y, szy)) < 0) goto CLEANUP; }
  /* Args: W,x,bias,y,rows,cols,ldW,alpha,beta,act */
  ZE_GUARD(set_arg(g_k_gemv_ba, 0, dW),   "set_arg W failed");
  ZE_GUARD(set_arg(g_k_gemv_ba, 1, dx),   "set_arg x failed");
  ZE_GUARD(set_arg(g_k_gemv_ba, 2, db),   "set_arg bias failed");
  ZE_GUARD(set_arg(g_k_gemv_ba, 3, dy),   "set_arg y failed");
  ZE_GUARD(set_arg(g_k_gemv_ba, 4, rows), "set_arg rows failed");
  ZE_GUARD(set_arg(g_k_gemv_ba, 5, cols), "set_arg cols failed");
  ZE_GUARD(set_arg(g_k_gemv_ba, 6, ldW),  "set_arg ldW failed");
  ZE_GUARD(set_arg(g_k_gemv_ba, 7, alpha),"set_arg alpha failed");
  ZE_GUARD(set_arg(g_k_gemv_ba, 8, beta), "set_arg beta failed");
  ZE_GUARD(set_arg(g_k_gemv_ba, 9, act),  "set_arg act failed");
  ze_group_count_t gc = { (uint32_t)rows, 1u, 1u };
  ZE_GUARD(zeCommandListAppendLaunchKernel(g_cl, g_k_gemv_ba, &gc, nullptr, 0, nullptr),
           "launch gemv_bias_act_f32 failed");
  if ((rc = memcpy_imm(y, dy, szy)) < 0) goto CLEANUP;
CLEANUP:
  dfree(db); dfree(dy); dfree(dx); dfree(dW);
  return rc;
}
References dalloc(), dfree(), ensure_module_ready(), g_cl, g_k_gemv_ba, ie_gemv_rowwise_f32_kernel(), memcpy_imm(), set_arg(), set_err(), and ZE_GUARD.
ie_ze_launch_gemv_rowwise_f32()
int ie_ze_launch_gemv_rowwise_f32 (const float * W, const float * x, float * y, int rows, int cols, int ldW, float alpha, float beta)
#include <engine/src/kernels/ze/ie_kernel_ze.cpp>
Row-wise GEMV FP32: y = alpha * W * x + beta * y.
Row-wise GEMV FP32: y = alpha * W * x + beta * y.
Parameters
W Host pointer to row-major matrix (rows x ldW).
x Host pointer to vector (length cols).
y Host pointer to output vector (length rows).
rows Number of rows in W and elements in y (>=1).
cols Number of columns in W and elements in x (>=1).
ldW Leading dimension of W (>= cols).
alpha Scale for W*x.
beta Scale for existing y (0 to overwrite).
Returns
0 on success; negative on error (see ie_ze_last_error_string()).
Parameters
W Host pointer to row-major matrix (rows x ldW).
x Host pointer to vector (length cols).
y Host pointer to output vector (length rows).
rows Number of rows in W and elements in y (>=1).
cols Number of columns in W and elements in x (>=1).
ldW Leading dimension of W (>= cols).
alpha Scale for W*x.
beta Scale for existing y (0 to overwrite).
Returns
0 on success; negative on error (see ie_ze_last_error_string()).
Definition at line 409 of file ie_kernel_ze.cpp.
{
  set_err(nullptr);
  if (!W || !x || !y || rows <= 0 || cols <= 0 || ldW < cols) {
    set_err("invalid arguments");
    return -1;
  }
  int rc = ensure_module_ready();
  if (rc < 0) return rc;
  size_t szW = (size_t)rows * (size_t)ldW * sizeof(float);
  size_t szx = (size_t)cols * sizeof(float);
  size_t szy = (size_t)rows * sizeof(float);
  void *dW=nullptr, *dx=nullptr, *dy=nullptr;
  if ((rc = dalloc(szW, &dW)) < 0) return rc;
  if ((rc = dalloc(szx, &dx)) < 0) { dfree(dW); return rc; }
  if ((rc = dalloc(szy, &dy)) < 0) { dfree(dx); dfree(dW); return rc; }
  if ((rc = memcpy_imm(dW, W, szW)) < 0) goto CLEANUP;
  if ((rc = memcpy_imm(dx, x, szx)) < 0) goto CLEANUP;
  if (beta != 0.f) { if ((rc = memcpy_imm(dy, y, szy)) < 0) goto CLEANUP; }
  /* Set arguments: (W, x, y, rows, cols, ldW, alpha, beta) */
  ZE_GUARD(set_arg(g_k_gemv, 0, dW),   "set_arg W failed");
  ZE_GUARD(set_arg(g_k_gemv, 1, dx),   "set_arg x failed");
  ZE_GUARD(set_arg(g_k_gemv, 2, dy),   "set_arg y failed");
  ZE_GUARD(set_arg(g_k_gemv, 3, rows), "set_arg rows failed");
  ZE_GUARD(set_arg(g_k_gemv, 4, cols), "set_arg cols failed");
  ZE_GUARD(set_arg(g_k_gemv, 5, ldW),  "set_arg ldW failed");
  ZE_GUARD(set_arg(g_k_gemv, 6, alpha),"set_arg alpha failed");
  ZE_GUARD(set_arg(g_k_gemv, 7, beta), "set_arg beta failed");
  ze_group_count_t gc = { (uint32_t)rows, 1u, 1u };
  ZE_GUARD(zeCommandListAppendLaunchKernel(g_cl, g_k_gemv, &gc, nullptr, 0, nullptr),
           "launch gemv_rowwise_f32 failed");
  if ((rc = memcpy_imm(y, dy, szy)) < 0) goto CLEANUP;
CLEANUP:
  dfree(dy); dfree(dx); dfree(dW);
  return rc;
}
References dalloc(), dfree(), ensure_module_ready(), g_cl, g_k_gemv, ie_gemv_rowwise_f32_kernel(), memcpy_imm(), set_arg(), set_err(), and ZE_GUARD.
ie_ze_launch_pack_w_blockedk_f32()
int ie_ze_launch_pack_w_blockedk_f32 (float * Wp, const float * W, int rows, int cols, int ldW, int block_k)
#include <engine/src/kernels/ze/ie_kernel_ze.cpp>
Pack W (row-major) into Blocked-K layout into Wp.
Pack W (row-major) into Blocked-K layout into Wp.
Parameters
Wp Host pointer to destination (size rows*cols).
W Host pointer to source row-major matrix.
rows Rows (>=1).
cols Cols (>=1).
ldW Leading dimension of W (>= cols).
block_k Tile size along K (e.g., 32/64/128; >0).
Returns
0 on success; negative on error.
Parameters
Wp Host pointer to destination (size rows*cols).
W Host pointer to source row-major matrix.
rows Rows (>=1).
cols Cols (>=1).
ldW Leading dimension of W (>= cols).
block_k Tile size along K (e.g., 32/64/128; >0).
Returns
0 on success; negative on error.
Definition at line 565 of file ie_kernel_ze.cpp.
{
  set_err(nullptr);
  if (!Wp || !W || rows <= 0 || cols <= 0 || ldW < cols || block_k <= 0) {
    set_err("invalid arguments");
    return -1;
  }
  int rc = ensure_module_ready();
  if (rc < 0) return rc;
  size_t szW  = (size_t)rows * (size_t)ldW   * sizeof(float);
  size_t szWp = (size_t)rows * (size_t)cols  * sizeof(float);
  void *dW=nullptr, *dWp=nullptr;
  if ((rc = dalloc(szW,  &dW))  < 0) return rc;
  if ((rc = dalloc(szWp, &dWp)) < 0) { dfree(dW); return rc; }
  if ((rc = memcpy_imm(dW, W, szW)) < 0) goto CLEANUP;
  ZE_GUARD(set_arg(g_k_pack, 0, dWp),     "set Wp failed");
  ZE_GUARD(set_arg(g_k_pack, 1, dW),      "set W  failed");
  ZE_GUARD(set_arg(g_k_pack, 2, rows),    "set rows failed");
  ZE_GUARD(set_arg(g_k_pack, 3, cols),    "set cols failed");
  ZE_GUARD(set_arg(g_k_pack, 4, ldW),     "set ldW failed");
  ZE_GUARD(set_arg(g_k_pack, 5, block_k), "set block_k failed");
  /* 2D grid over (cols, rows) with groups (32,8) → same as CUDA choice */
  uint32_t gx = (cols + 32u - 1u) / 32u;
  uint32_t gy = (rows +  8u - 1u) /  8u;
  ze_group_count_t gc = { gx, gy, 1u };
  ZE_GUARD(zeCommandListAppendLaunchKernel(g_cl, g_k_pack, &gc, nullptr, 0, nullptr),
           "launch pack_w_blockedk_f32 failed");
  if ((rc = memcpy_imm(Wp, dWp, szWp)) < 0) goto CLEANUP;
CLEANUP:
  dfree(dWp); dfree(dW);
  return rc;
}
References dalloc(), dfree(), ensure_module_ready(), g_cl, g_k_pack, ie_gemv_rowwise_f32_kernel(), memcpy_imm(), set_arg(), set_err(), and ZE_GUARD.
ie_ze_launch_vec_tanh_f32()
int ie_ze_launch_vec_tanh_f32 (float * y, const float * x, int n)
#include <engine/src/kernels/ze/ie_kernel_ze.cpp>
Vector tanh: y[i] = tanh(x[i]) for i in [0, n).
Vector tanh: y[i] = tanh(x[i]) for i in [0, n).
Parameters
y Host pointer to output (length n).
x Host pointer to input (length n).
n Number of elements (>=1).
Returns
0 on success; negative on error.
Parameters
y Host pointer to output (length n).
x Host pointer to input (length n).
n Number of elements (>=1).
Returns
0 on success; negative on error.
Definition at line 526 of file ie_kernel_ze.cpp.
{
  set_err(nullptr);
  if (!x || !y || n <= 0) { set_err("invalid arguments"); return -1; }
  int rc = ensure_module_ready();
  if (rc < 0) return rc;
  size_t sz = (size_t)n * sizeof(float);
  void *dx=nullptr,*dy=nullptr;
  if ((rc = dalloc(sz,&dx)) < 0) return rc;
  if ((rc = dalloc(sz,&dy)) < 0) { dfree(dx); return rc; }
  if ((rc = memcpy_imm(dx, x, sz)) < 0) goto CLEANUP;
  ZE_GUARD(set_arg(g_k_tanh, 0, dy), "set y failed");
  ZE_GUARD(set_arg(g_k_tanh, 1, dx), "set x failed");
  ZE_GUARD(set_arg(g_k_tanh, 2, n ), "set n failed");
  /* 1D grid: ceil(n / 256) groups of 256 threads */
  uint32_t groups = (n + 255u) / 256u;
  if (groups == 0) groups = 1;
  ze_group_count_t gc = { groups, 1u, 1u };
  ZE_GUARD(zeCommandListAppendLaunchKernel(g_cl, g_k_tanh, &gc, nullptr, 0, nullptr),
           "launch vec_tanh_f32 failed");
  if ((rc = memcpy_imm(y, dy, sz)) < 0) goto CLEANUP;
CLEANUP:
  dfree(dy); dfree(dx);
  return rc;
}
References dalloc(), dfree(), ensure_module_ready(), g_cl, g_k_tanh, ie_gemv_rowwise_f32_kernel(), memcpy_imm(), set_arg(), set_err(), and ZE_GUARD.