Inference Engine (Clocher): Tokenizer (Stub)
Tokenizer (Stub)
Lightweight, dependency-free tokenizer used in tests and harness.
Data Structures
struct ie_vocab_s
Lightweight vocabulary descriptor.
Typedefs
typedef struct ie_vocab_s ie_vocab_t
Functions
int ie_vocab_load (const char *vocab_path, ie_vocab_t *out)
Load a vocabulary from vocab_path (or default to a stub).
int ie_tok_encode (const ie_vocab_t *v, const char *text, uint32_t *ids, uint32_t *out_count)
Encode UTF-8 text into token IDs (whitespace split, hashed IDs).
int ie_tok_decode (const ie_vocab_t *v, const uint32_t *ids, uint32_t count, char *out, size_t out_sz)
Decode token IDs into a printable placeholder string.
void ie_vocab_free (ie_vocab_t *v)
Release resources held by a vocabulary.
Detailed Description
Lightweight, dependency-free tokenizer used in tests and harness.
Typedef Documentation
ie_vocab_t
typedef struct ie_vocab_s ie_vocab_t
#include <engine/include/ie_io.h>
Function Documentation
ie_tok_decode()
int ie_tok_decode (const ie_vocab_t * v, const uint32_t * ids, uint32_t count, char * out, size_t out_sz)
#include <engine/include/ie_io.h>
Decode token IDs into a printable placeholder string.
Implementations may produce a stable, testing-friendly textual form rather than true detokenization. The reference implementation returns "T<ID0> T<ID1> ..." into out.
Parameters
v Loaded vocabulary.
ids Array of token IDs.
count Number of IDs (elements in ids).
out Output character buffer (NUL-terminated on success).
out_sz Capacity of out in bytes.
Return values
0 on success.
-1 on invalid arguments or zero-sized buffer.
-2 if out is too small to hold the formatted sequence.
Decode token IDs into a printable placeholder string.
Format: "T<ID0> T<ID1> ... T<IDn>" (space-separated). This is sufficient for unit-test invariants that check spacing and a predictable prefix.
Parameters
v Loaded vocabulary (unused but reserved).
ids Array of token IDs.
count Number of IDs.
out Output buffer for the textual form.
out_sz Capacity of out in bytes.
Return values
0 on success.
-1 on invalid arguments (e.g., NULL out or zero out_sz).
-2 if out is too small to hold the formatted string.
Definition at line 231 of file tokenizer.c.
{
   (void)v;
   if (!out || out_sz == 0) return -1;
   /* Handle empty sequence. */
   if (!ids || count == 0) {
     if (out_sz > 0) out[0] = '\0';
     return 0;
   }
   /* Conservative sizing: worst case "T4294967295 " per token + NUL. */
   const size_t worst_per = sizeof("T4294967295 ") - 1; /* 12 bytes */
   size_t worst = (size_t)count * worst_per + 1;
   if (out_sz < worst) {
     /* Strict contract for tests: return error if too small. */
     return -2;
   }
   char *p = out;
   size_t rem = out_sz;
   for (uint32_t i = 0; i < count; ++i) {
     int n = (i == 0)
       ? snprintf(p, rem, "T%u", ids[i])
       : snprintf(p, rem, " T%u", ids[i]);
     if (n < 0 || (size_t)n >= rem) {
       return -2;
     }
     p   += (size_t)n;
     rem -= (size_t)n;
   }
   /* Ensure NUL-termination. */
   if (rem == 0) return -2;
   *p = '\0';
   return 0;
 }
Referenced by main().
ie_tok_encode()
int ie_tok_encode (const ie_vocab_t * v, const char * text, uint32_t * ids, uint32_t * out_count)
#include <engine/include/ie_io.h>
Encode UTF-8 text into token IDs (whitespace split, hashed IDs).
Size-only mode: pass ids == NULL to compute the required length in *out_count without writing token data.
Parameters
v Loaded vocabulary (must have positive vocab_size).
text NUL-terminated UTF-8 input string.
ids Output buffer of length *out_count (or NULL for size query).
out_count In: capacity of ids when ids != NULL. Out: number of tokens written (or needed).
Return values
0 on success.
-1 on invalid arguments.
-2 if provided capacity is insufficient to hold all tokens.
Encode UTF-8 text into token IDs (whitespace split, hashed IDs).
Tokenization rule: split on one or more whitespace characters (ASCII). Consecutive whitespace collapses to a single separator, producing no empty tokens. For example, "hello world" yields 2 tokens.
Size-only mode: pass ids == NULL to receive the required length in *out_count without writing IDs.
Parameters
v Loaded vocabulary descriptor (only vocab_size is used).
text NUL-terminated UTF-8 string. Must not be NULL.
ids Output buffer of length *out_count (or NULL for size query).
out_count In: capacity of ids when ids != NULL.
Out: number of tokens written (or needed).
Return values
0 on success.
-1 on invalid arguments.
-2 if provided capacity is insufficient to hold all tokens.
Definition at line 162 of file tokenizer.c.
{
   (void)v; /* vocab_size is not required for hashing but reserved for future use */
   if (!text || !out_count) return -1;
   const unsigned char *s = (const unsigned char*)text;
   uint32_t needed = 0;
   /* First pass: count tokens. */
   size_t i = 0;
   const size_t L = strlen(text);
   while (i < L) {
     /* Skip leading whitespace between tokens. */
     while (i < L && is_space_byte(s[i])) ++i;
     if (i >= L) break;
     /* Start of token. */
     size_t start = i;
     while (i < L && !is_space_byte(s[i])) ++i;
     size_t tok_len = i - start;
     if (tok_len > 0) {
       ++needed;
     }
   }
   if (!ids) {
     *out_count = needed;
     return 0;
   }
   /* Second pass: produce IDs; respect capacity in *out_count. */
   uint32_t cap = *out_count;
   uint32_t wrote = 0;
   i = 0;
   while (i < L && wrote < cap) {
     while (i < L && is_space_byte(s[i])) ++i;
     if (i >= L) break;
     size_t start = i;
     while (i < L && !is_space_byte(s[i])) ++i;
     size_t tok_len = i - start;
     if (tok_len > 0) {
       uint32_t h = fnv1a_32(s + start, tok_len);
       ids[wrote++] = clamp_to_pos31(h);
     }
   }
   *out_count = wrote;
   /* If capacity was insufficient, signal failure. Tests pre-size correctly. */
   return (wrote == needed) ? 0 : -2;
 }
References clamp_to_pos31(), fnv1a_32(), and is_space_byte().
Referenced by main().
ie_vocab_free()
void ie_vocab_free (ie_vocab_t * v)
#include <engine/include/ie_io.h>
Release resources held by a vocabulary.
The current tokenizer implementation does not heap-allocate inside ie_vocab_t, so this function is a no-op. It exists for symmetry and forward compatibility if the tokenizer later gains owned resources.
Parameters
v Vocabulary pointer (may be NULL; no-op).
Definition at line 134 of file tokenizer.c.
{
   (void)v;
 }
ie_vocab_load()
int ie_vocab_load (const char * vocab_path, ie_vocab_t * out)
#include <engine/include/ie_io.h>
Load a vocabulary from vocab_path (or default to a stub).
Implementations should never fail hard: for reproducible CI, returning a small stub vocab is valid. The function attempts to parse a vocabSize integer if a JSON-like file is provided; otherwise a default size is used.
Parameters
vocab_path Path to a vocab file (e.g., vocab.json); may be NULL.
out Output vocabulary (written on success).
Return values
0 on success (including stub fallback).
negative on unrecoverable failure (e.g., out is NULL).
Load a vocabulary from vocab_path (or default to a stub).
The implementation accepts any readable file but only attempts to detect a simple JSON-like "vocabSize": <int> field. If the file is missing or unparsable, a small stub vocab is returned to keep execution deterministic.
Parameters
vocab_path Path to a vocabulary file (may be NULL).
out Output vocabulary (written on success).
Return values
0 on success (including stub fallback).
-1 on invalid arguments (e.g., out is NULL).
Definition at line 97 of file tokenizer.c.
{
   if (!out) return -1;
   /* Default stub value if anything goes wrong. */
   out->vocab_size = 50000;
   if (!vocab_path || !*vocab_path) {
     return 0;
   }
   FILE *f = fopen(vocab_path, "rb");
   if (!f) {
     /* Keep stub; report success to remain permissive. */
     return 0;
   }
   /* Read a small prefix to try and find "vocabSize". */
   char buf[4096];
   size_t n = fread(buf, 1, sizeof(buf)-1, f);
   fclose(f);
   buf[n] = '\0';
   /* Very relaxed scan for a number after "vocabSize". */
   const char *key = "vocabSize";
   char *hit = strstr(buf, key);
   if (hit) {
     /* Move to the first digit after key. */
     char *p = hit + (int)strlen(key);
     while (*p && (*p == ' ' || *p == '\t' || *p == '"' || *p == '\'' || *p == ':' )) ++p;
     long val = 0;
     if (sscanf(p, "%ld", &val) == 1 && val > 0 && val < 100000000L) {
       out->vocab_size = (int)val;
     }
   }
   return 0;
 }
References ie_vocab_s::vocab_size.
Referenced by main().