Inference Engine (Clocher): IEBIN v1 Weights Loader
IEBIN v1 Weights Loader
Open/inspect lightweight model container files.
Data Structures
struct ie_weights_s
In-memory descriptor for IEBIN v1 metadata and resolved paths.
Typedefs
typedef struct ie_weights_s ie_weights_t
Functions
int ie_weights_open (const char *json_path, const char *bin_path, ie_weights_t *out)
Open and parse IEBIN v1 metadata and resolve the weights path.
int ie_weights_touch (const ie_weights_t *w)
Touch the weights binary to verify readability (and optionally warm caches).
void ie_weights_close (ie_weights_t *w)
Close weights resources (reserved for future use).
Detailed Description
Open/inspect lightweight model container files.
Typedef Documentation
ie_weights_t
typedef struct ie_weights_s ie_weights_t
#include <engine/include/ie_io.h>
Function Documentation
ie_weights_close()
void ie_weights_close (ie_weights_t * w)
#include <engine/include/ie_io.h>
Close weights resources (reserved for future use).
Currently, the descriptor does not keep the weights binary open. This function exists for symmetry and forward compatibility.
Deduplicated weights:
If a dedup handle was opened, this function releases it and clears ie_weights_t::is_dedup and ie_weights_t::dedup_handle.
Parameters
w Weights descriptor previously opened with ie_weights_open (may be NULL).
Close weights resources (reserved for future use).
Close weights resources (reserved for future use).
This now closes the dedup handle if one was opened.
This now closes the dedup handle if one was opened.
Definition at line 536 of file weights.c.
{
   if (!w) return;
   if (w->is_dedup && w->dedup_handle) {
     ie_weights_dedup_t *dh = (ie_weights_dedup_t *)w->dedup_handle;
     ie_weights_dedup_close(&dh);
     w->dedup_handle = NULL;
     w->is_dedup = 0;
   }
 }
References ie_weights_s::dedup_handle, ie_weights_dedup_close(), and ie_weights_s::is_dedup.
Referenced by main().
ie_weights_open()
int ie_weights_open (const char * json_path, const char * bin_path, ie_weights_t * out)
#include <engine/include/ie_io.h>
Open and parse IEBIN v1 metadata and resolve the weights path.
The loader reads model.ie.json, extracts minimal header metadata, and resolves the corresponding weights binary path. The binary is not kept open.
Deduplicated weights (lossless):
If the directory containing json_path also contains model.dedup.json, the implementation may open a dedup loader and mark out with ie_weights_t::is_dedup and ie_weights_t::dedup_handle.
If dedup metadata is present but cannot be opened, the implementation may fail the open to avoid silent mismatch.
Parameters
json_path Path to model.ie.json (must be readable).
bin_path Optional override path for the binary (model.ie.bin); if NULL, the JSON bin field (or default) is used.
out Output descriptor; zero-initialized on entry by the function.
Return values
IE_IO_OK on success.
IE_IO_ERR_ARGS if arguments are invalid.
IE_IO_ERR_JSON if JSON cannot be read/parsed.
IE_IO_ERR_BIN_UNSPEC if a weights path cannot be determined.
IE_IO_ERR_STAT if the binary cannot be stat()-ed.
Open and parse IEBIN v1 metadata and resolve the weights path.
Open and parse IEBIN v1 metadata and resolve the weights path.
Behavior:
Loads model.ie.json exactly as before.
Additionally checks whether a sibling model.dedup.json exists in the same directory. If present, it opens the dedup loader and records that this weights handle is backed by deduplicated artifacts.
Notes:
This function does not change the public ABI in ie_io.h. It relies on existing spare/opaque fields in ie_weights_t to store the dedup handle.
If your ie_weights_t does not have such a field yet, add: void *dedup_handle; int is_dedup; to ie_io.h (or a private extension struct) and recompile.
Behavior:
Loads model.ie.json exactly as before.
Additionally checks whether a sibling model.dedup.json exists in the same directory. If present, it opens the dedup loader and records that this weights handle is backed by deduplicated artifacts.
Notes:
This function does not change the public ABI in ie_io.h. It relies on existing spare/opaque fields in ie_weights_t to store the dedup handle.
If your ie_weights_t does not have such a field yet, add: void *dedup_handle; int is_dedup; to ie_io.h (or a private extension struct) and recompile.
Definition at line 413 of file weights.c.
{
   if (!out) return IE_IO_ERR_ARGS;
   memset(out, 0, sizeof(*out));
   if (!json_path || !*json_path) return IE_IO_ERR_ARGS;
   cpyz(out->json_path, sizeof(out->json_path), json_path);
   /* Read JSON text */
   char *jbuf = NULL; size_t jlen = 0;
   if (read_all_text(json_path, &jbuf, &jlen) != 0 || !jbuf || jlen == 0) {
     return IE_IO_ERR_JSON;
   }
   /* Parse relaxed header keys */
   int ver = 0; (void)scan_json_key_int(jbuf, "version", &ver);
   if (ver <= 0) ver = 1;
   out->version = ver;
   char dtype[16]; dtype[0] = '\0';
   (void)scan_json_key_string(jbuf, "dtype", dtype, sizeof(dtype));
   if (dtype[0] == '\0') strcpy(dtype, "float32");
   cpyz(out->dtype, sizeof(out->dtype), dtype);
   /* Determine weights path (absolute or relative to JSON dir) */
   char resolved_bin[512]; resolved_bin[0] = '\0';
   if (bin_path && *bin_path) {
     cpyz(resolved_bin, sizeof(resolved_bin), bin_path);
   } else {
     char bin_key[256]; bin_key[0] = '\0';
     (void)scan_json_key_string(jbuf, "bin", bin_key, sizeof(bin_key));
     if (bin_key[0] == '\0') { free(jbuf); return IE_IO_ERR_BIN_UNSPEC; }
     const char *slash = last_slash(json_path);
     if (slash) {
       char dir[512]; size_t dn = (size_t)(slash - json_path);
       if (dn >= sizeof(dir)) dn = sizeof(dir) - 1;
       memcpy(dir, json_path, dn); dir[dn] = '\0';
       join_path(resolved_bin, sizeof(resolved_bin), dir, bin_key);
     } else {
       cpyz(resolved_bin, sizeof(resolved_bin), bin_key);
     }
   }
   cpyz(out->weights_path, sizeof(out->weights_path), resolved_bin);
   /* Stat the weights file to get its size */
   struct stat st;
   if (stat(out->weights_path, &st) != 0 || st.st_size < 0) {
     free(jbuf);
     return IE_IO_ERR_STAT;
   }
   out->bin_size_bytes = (size_t)st.st_size;
   out->loaded = 1;
   /* Dedup branch: open model.dedup.json if present next to model.ie.json. */
   {
     const char *slash = last_slash(json_path);
     char dir[512]; dir[0] = '\0';
     if (slash) {
       size_t dn = (size_t)(slash - json_path);
       if (dn >= sizeof(dir)) dn = sizeof(dir) - 1;
       memcpy(dir, json_path, dn);
       dir[dn] = '\0';
     } else {
       /* If json_path has no slash, treat current working directory as the dir. */
       cpyz(dir, sizeof(dir), ".");
     }
     char dedup_json[512]; dedup_json[0] = '\0';
     join_path(dedup_json, sizeof(dedup_json), dir, "model.dedup.json");
     if (file_exists_readable(dedup_json)) {
       ie_weights_dedup_opts_t opts;
       memset(&opts, 0, sizeof(opts));
       opts.prefault_policy = 0;
       ie_weights_dedup_t *dh = NULL;
       ie_wdedup_status_t dst = ie_weights_dedup_open(&dh, dir, &opts);
       if (dst != IE_WDEDUP_OK) {
         /* Hard fail: if dedup artifacts exist but cannot be opened, treat as load error. */
         free(jbuf);
         return IE_IO_ERR_JSON;
       }
       /* Store into the weights handle (requires fields to exist in ie_weights_t). */
       out->is_dedup = 1;
       out->dedup_handle = (void *)dh;
     }
   }
   free(jbuf);
   return IE_IO_OK;
 }
References ie_weights_s::bin_size_bytes, cpyz(), ie_weights_s::dedup_handle, ie_weights_s::dtype, file_exists_readable(), IE_IO_ERR_ARGS, IE_IO_ERR_BIN_UNSPEC, IE_IO_ERR_JSON, IE_IO_ERR_STAT, IE_WDEDUP_OK, ie_weights_dedup_open(), ie_weights_s::is_dedup, join_path(), ie_weights_s::json_path, last_slash(), ie_weights_s::loaded, ie_weights_dedup_opts::prefault_policy, read_all_text(), scan_json_key_int(), scan_json_key_string(), ie_weights_s::version, and ie_weights_s::weights_path.
Referenced by main().
ie_weights_touch()
int ie_weights_touch (const ie_weights_t * w)
#include <engine/include/ie_io.h>
Touch the weights binary to verify readability (and optionally warm caches).
Performs a small positional read near offset 0 and near the end of the file (if large enough). Intended as a fast sanity check during startup or tests. The implementation may be a no-op on platforms without pread.
Deduplicated weights:
This API is intentionally conservative: it touches the primary weights backing file recorded in ie_weights_t::weights_path. Any additional prefault/warm-up behavior for dedup artifacts is handled internally by the dedup subsystem.
Parameters
w Opened weights descriptor (must come from ie_weights_open).
Return values
IE_IO_OK on success (binary considered readable).
IE_IO_ERR_ARGS on invalid arguments or unopened descriptor.
IE_IO_ERR_OPEN if the binary cannot be opened.
IE_IO_ERR_READ if the binary cannot be read.
Touch the weights binary to verify readability (and optionally warm caches).
Touch the weights binary to verify readability (and optionally warm caches).
For deduplicated weights, this function touches the primary backing file (the regular model.ie.bin) exactly as before. The dedup path warm-up is expected to be handled by the dedup loader and/or the mmap layer.
For deduplicated weights, this function touches the primary backing file (the regular model.ie.bin) exactly as before. The dedup path warm-up is expected to be handled by the dedup loader and/or the mmap layer.
Definition at line 513 of file weights.c.
{
   if (!w || !w->weights_path[0]) return IE_IO_ERR_ARGS;
   int fd = open(w->weights_path, O_RDONLY);
   if (fd < 0) return IE_IO_ERR_OPEN;
   unsigned char buf[4096];
   ssize_t r1 = ie_pread(fd, buf, sizeof(buf), 0);
   ssize_t r2 = 0;
   if (w->bin_size_bytes > sizeof(buf)) {
     off_t off = (off_t)(w->bin_size_bytes - sizeof(buf));
     r2 = ie_pread(fd, buf, sizeof(buf), off);
   }
   close(fd);
   if (r1 < 0 || r2 < 0) return IE_IO_ERR_READ;
   return IE_IO_OK;
 }
References ie_weights_s::bin_size_bytes, IE_IO_ERR_ARGS, IE_IO_ERR_OPEN, IE_IO_ERR_READ, IE_IO_OK, ie_pread(), and ie_weights_s::weights_path.
Referenced by main().