Inference Engine (Clocher): Ie_int4_quant
Ie_int4_quant
Typedefs
typedef enum ie_int4_status_t ie_int4_status_t
Enumerations
enum ie_int4_status_t { IE_INT4_STATUS_OK = 0 , IE_INT4_STATUS_BADARG = -1 , IE_INT4_STATUS_NUMERIC = -2 }
Status codes for INT4 quantization routines.
Functions
size_t ie_int4_rowbytes (size_t cols)
Compute the number of packed bytes required to store a single row of cols 4-bit values (two per byte).
int ie_int4_absmax (const float *src, size_t rows, size_t cols, float *out_absmax)
Compute the absolute-maximum value of a float32 matrix.
int ie_int4_absmax_per_row (const float *src, size_t rows, size_t cols, float *out_absmax_rows)
Compute per-row absolute-maximums of a float32 matrix.
int ie_int4_quantize_per_tensor (const float *src, size_t rows, size_t cols, uint8_t *dst_packed, float *out_scale)
Quantize a float32 matrix to packed INT4 using a single (per-tensor) scale.
int ie_int4_dequantize_per_tensor (const uint8_t *src_packed, size_t rows, size_t cols, float scale, float *dst)
Dequantize a packed INT4 matrix using a single (per-tensor) scale.
int ie_int4_quantize_per_row (const float *src, size_t rows, size_t cols, uint8_t *dst_packed, float *out_scales)
Quantize a float32 matrix to packed INT4 with per-row scales.
int ie_int4_dequantize_per_row (const uint8_t *src_packed, size_t rows, size_t cols, const float *scales, float *dst)
Dequantize a packed INT4 matrix with per-row scales.
int ie_int4_error_metrics (const float *ref, const float *test, size_t n, double *out_mse, double *out_cosine)
Compute error metrics between two float32 vectors of equal length: mean squared error (MSE) and cosine similarity.
Detailed Description
Typedef Documentation
ie_int4_status_t
typedef enum ie_int4_status_t ie_int4_status_t
#include <engine/include/ie_quant_int4.h>
Enumeration Type Documentation
ie_int4_status_t
enum ie_int4_status_t
#include <engine/include/ie_quant_int4.h>
Status codes for INT4 quantization routines.
Enumerator
IE_INT4_STATUS_OK
Success.
IE_INT4_STATUS_BADARG
Invalid argument (NULL pointers, zero sizes, etc.).
IE_INT4_STATUS_NUMERIC
Numeric issue (NaN scales, infinities, etc.).
Definition at line 70 of file ie_quant_int4.h.
{
   IE_INT4_STATUS_OK = 0,
   IE_INT4_STATUS_BADARG = -1,
   IE_INT4_STATUS_NUMERIC = -2
 } ie_int4_status_t;
Function Documentation
ie_int4_absmax()
int ie_int4_absmax (const float * src, size_t rows, size_t cols, float * out_absmax)
#include <engine/include/ie_quant_int4.h>
Compute the absolute-maximum value of a float32 matrix.
Parameters
src Pointer to the source matrix (row-major), length = rows*cols.
rows Number of rows.
cols Number of columns.
out_absmax Output pointer for the absolute-maximum value.
Returns
0 on success, negative on error.
Definition at line 73 of file int4_ptq.c.
{
   if (!src || !out_absmax || rows == 0 || cols == 0) return IE_INT4_STATUS_BADARG;
   size_t n = rows * cols;
   float m = 0.0f;
   for (size_t i = 0; i < n; ++i) {
     float v = fabsf(src[i]);
     if (v > m) m = v;
   }
   *out_absmax = m;
   return IE_INT4_STATUS_OK;
 }
References IE_INT4_STATUS_BADARG, and IE_INT4_STATUS_OK.
Referenced by ie_int4_quantize_per_tensor().
ie_int4_absmax_per_row()
int ie_int4_absmax_per_row (const float * src, size_t rows, size_t cols, float * out_absmax_rows)
#include <engine/include/ie_quant_int4.h>
Compute per-row absolute-maximums of a float32 matrix.
Parameters
src Pointer to the source matrix (row-major), length = rows*cols.
rows Number of rows.
cols Number of columns.
out_absmax_rows Output array of length rows.
Returns
0 on success, negative on error.
Definition at line 85 of file int4_ptq.c.
{
   if (!src || !out_absmax_rows || rows == 0 || cols == 0) return IE_INT4_STATUS_BADARG;
   for (size_t r = 0; r < rows; ++r) {
     const float *row = src + r * cols;
     float m = 0.0f;
     for (size_t c = 0; c < cols; ++c) {
       float v = fabsf(row[c]);
       if (v > m) m = v;
     }
     out_absmax_rows[r] = m;
   }
   return IE_INT4_STATUS_OK;
 }
References IE_INT4_STATUS_BADARG, and IE_INT4_STATUS_OK.
ie_int4_dequantize_per_row()
int ie_int4_dequantize_per_row (const uint8_t * src_packed, size_t rows, size_t cols, const float * scales, float * dst)
#include <engine/include/ie_quant_int4.h>
Dequantize a packed INT4 matrix with per-row scales.
Parameters
src_packed Pointer to packed INT4 input buffer of size rows * ie_int4_rowbytes(cols) bytes.
rows Number of rows.
cols Number of columns.
scales Pointer to per-row scales (length = rows).
dst Output buffer of length rows*cols (float32).
Returns
0 on success, negative on error.
Definition at line 206 of file int4_ptq.c.
{
   if (!src_packed || !dst || !scales || rows == 0 || cols == 0)
     return IE_INT4_STATUS_BADARG;
   const size_t rb = ie_int4_rowbytes(cols);
   for (size_t r = 0; r < rows; ++r) {
     float scale = scales[r];
     if (!(scale > 0.0f) || !isfinite(scale)) return IE_INT4_STATUS_NUMERIC;
     const uint8_t *in = src_packed + r * rb;
     float *row = dst + r * cols;
     size_t c = 0;
     for (; c + 1 < cols; c += 2) {
       int q0, q1;
       unpack_q4_pair(in[c / 2], &q0, &q1);
       row[c]     = (float)q0 * scale;
       row[c + 1] = (float)q1 * scale;
     }
     if (c < cols) {
       int q0, q1;
       unpack_q4_pair(in[c / 2], &q0, &q1);
       row[c] = (float)q0 * scale;
     }
   }
   return IE_INT4_STATUS_OK;
 }
References ie_int4_rowbytes(), IE_INT4_STATUS_BADARG, IE_INT4_STATUS_NUMERIC, IE_INT4_STATUS_OK, and unpack_q4_pair().
Referenced by ie_weights_decode_int4().
ie_int4_dequantize_per_tensor()
int ie_int4_dequantize_per_tensor (const uint8_t * src_packed, size_t rows, size_t cols, float scale, float * dst)
#include <engine/include/ie_quant_int4.h>
Dequantize a packed INT4 matrix using a single (per-tensor) scale.
Parameters
src_packed Pointer to packed INT4 input buffer of size rows * ie_int4_rowbytes(cols) bytes.
rows Number of rows.
cols Number of columns.
scale Per-tensor scale that was used during quantization.
dst Output buffer of length rows*cols (float32).
Returns
0 on success, negative on error.
Definition at line 136 of file int4_ptq.c.
{
   if (!src_packed || !dst || rows == 0 || cols == 0) return IE_INT4_STATUS_BADARG;
   if (!(scale > 0.0f) || !isfinite(scale)) return IE_INT4_STATUS_NUMERIC;
   const size_t rb = ie_int4_rowbytes(cols);
   for (size_t r = 0; r < rows; ++r) {
     const uint8_t *in = src_packed + r * rb;
     float *row = dst + r * cols;
     size_t c = 0;
     for (; c + 1 < cols; c += 2) {
       int q0, q1;
       unpack_q4_pair(in[c / 2], &q0, &q1);
       row[c]     = (float)q0 * scale;
       row[c + 1] = (float)q1 * scale;
     }
     if (c < cols) {
       int q0, q1;
       unpack_q4_pair(in[c / 2], &q0, &q1);
       row[c] = (float)q0 * scale;
       /* ignore q1 for odd tail */
     }
   }
   return IE_INT4_STATUS_OK;
 }
References ie_int4_rowbytes(), IE_INT4_STATUS_BADARG, IE_INT4_STATUS_NUMERIC, IE_INT4_STATUS_OK, and unpack_q4_pair().
Referenced by ie_weights_decode_int4().
ie_int4_error_metrics()
int ie_int4_error_metrics (const float * ref, const float * test, size_t n, double * out_mse, double * out_cosine)
#include <engine/include/ie_quant_int4.h>
Compute error metrics between two float32 vectors of equal length: mean squared error (MSE) and cosine similarity.
Parameters
ref Pointer to the reference vector.
test Pointer to the test vector.
n Number of elements.
out_mse Output pointer for mean squared error (double).
out_cosine Output pointer for cosine similarity (double, in [-1,1]).
Returns
0 on success, negative on error.
Definition at line 240 of file int4_ptq.c.
{
   if (!ref || !test || !out_mse || !out_cosine || n == 0) return IE_INT4_STATUS_BADARG;
   long double se = 0.0L;
   long double dot = 0.0L;
   long double nr = 0.0L;
   long double nt = 0.0L;
   for (size_t i = 0; i < n; ++i) {
     long double r = ref[i];
     long double t = test[i];
     long double d = r - t;
     se  += d * d;
     dot += r * t;
     nr  += r * r;
     nt  += t * t;
   }
   double mse = (double)(se / (long double)n);
   double denom = sqrt((double)nr) * sqrt((double)nt);
   double cosine = (denom > 0.0) ? (double)(dot / denom) : 0.0;
   if (bad_float3(mse, cosine, denom)) return IE_INT4_STATUS_NUMERIC;
   *out_mse = mse;
   *out_cosine = cosine;
   return IE_INT4_STATUS_OK;
 }
References bad_float3(), IE_INT4_STATUS_BADARG, IE_INT4_STATUS_NUMERIC, IE_INT4_STATUS_OK, and ptq_calib::mse().
ie_int4_quantize_per_row()
int ie_int4_quantize_per_row (const float * src, size_t rows, size_t cols, uint8_t * dst_packed, float * out_scales)
#include <engine/include/ie_quant_int4.h>
Quantize a float32 matrix to packed INT4 with per-row scales.
Scales[i] = max(|row_i|)/7. For an all-zero row, the scale is 1.0f and the packed output row is encoded as zeros.
Parameters
src Pointer to the source matrix (row-major), length = rows*cols.
rows Number of rows.
cols Number of columns.
dst_packed Output buffer for packed INT4 data. Must be at least rows * ie_int4_rowbytes(cols) bytes.
out_scales Output buffer of length rows to receive per-row scales.
Returns
0 on success, negative on error.
Definition at line 167 of file int4_ptq.c.
{
   if (!src || !dst_packed || !out_scales || rows == 0 || cols == 0)
     return IE_INT4_STATUS_BADARG;
   const size_t rb = ie_int4_rowbytes(cols);
   for (size_t r = 0; r < rows; ++r) {
     const float *row = src + r * cols;
     float absmax = 0.0f;
     /* compute row absmax */
     for (size_t c = 0; c < cols; ++c) {
       float v = fabsf(row[c]);
       if (v > absmax) absmax = v;
     }
     float scale = (absmax > 0.0f) ? (absmax / 7.0f) : 1.0f;
     if (!isfinite(scale) || scale <= 0.0f) return IE_INT4_STATUS_NUMERIC;
     out_scales[r] = scale;
     uint8_t *out = dst_packed + r * rb;
     size_t c = 0;
     for (; c + 1 < cols; c += 2) {
       int q0 = clamp_q4(row[c]     / scale);
       int q1 = clamp_q4(row[c + 1] / scale);
       out[c / 2] = pack_q4_pair(q0, q1);
     }
     if (c < cols) {
       int q0 = clamp_q4(row[c] / scale);
       out[c / 2] = pack_q4_pair(q0, 0);
     }
   }
   return IE_INT4_STATUS_OK;
 }
References clamp_q4(), ie_int4_rowbytes(), IE_INT4_STATUS_BADARG, IE_INT4_STATUS_NUMERIC, IE_INT4_STATUS_OK, and pack_q4_pair().
ie_int4_quantize_per_tensor()
int ie_int4_quantize_per_tensor (const float * src, size_t rows, size_t cols, uint8_t * dst_packed, float * out_scale)
#include <engine/include/ie_quant_int4.h>
Quantize a float32 matrix to packed INT4 using a single (per-tensor) scale.
The scale is computed as max(|W|)/7. If the matrix is all zeros, the scale is set to 1.0f and the output is all zeros.
Parameters
src Pointer to the source matrix (row-major), length = rows*cols.
rows Number of rows.
cols Number of columns.
dst_packed Output buffer for packed INT4 data. Must be at least rows * ie_int4_rowbytes(cols) bytes.
out_scale Output pointer to receive the per-tensor scale.
Returns
0 on success, negative on error.
Definition at line 99 of file int4_ptq.c.
{
   if (!src || !dst_packed || !out_scale || rows == 0 || cols == 0)
     return IE_INT4_STATUS_BADARG;
   float absmax = 0.0f;
   int st = ie_int4_absmax(src, rows, cols, &absmax);
   if (st != IE_INT4_STATUS_OK) return st;
   float scale = (absmax > 0.0f) ? (absmax / 7.0f) : 1.0f;
   if (!isfinite(scale) || scale <= 0.0f) return IE_INT4_STATUS_NUMERIC;
   *out_scale = scale;
   const size_t rb = ie_int4_rowbytes(cols);
   for (size_t r = 0; r < rows; ++r) {
     const float *row = src + r * cols;
     uint8_t *out = dst_packed + r * rb;
     size_t c = 0;
     for (; c + 1 < cols; c += 2) {
       int q0 = clamp_q4(row[c]     / scale);
       int q1 = clamp_q4(row[c + 1] / scale);
       out[c / 2] = pack_q4_pair(q0, q1);
     }
     if (c < cols) {
       /* Odd tail: encode last even column and set high nibble to zero code. */
       int q0 = clamp_q4(row[c] / scale);
       out[c / 2] = pack_q4_pair(q0, 0 /* high nibble = 0 -> encoded as 8 after bias */);
     }
   }
   return IE_INT4_STATUS_OK;
 }
References clamp_q4(), ie_int4_absmax(), ie_int4_rowbytes(), IE_INT4_STATUS_BADARG, IE_INT4_STATUS_NUMERIC, IE_INT4_STATUS_OK, and pack_q4_pair().
ie_int4_rowbytes()
size_t ie_int4_rowbytes (size_t cols)
#include <engine/include/ie_quant_int4.h>
Compute the number of packed bytes required to store a single row of cols 4-bit values (two per byte).
Parameters
cols Number of columns (elements) in the row.
Returns
Bytes required to store the packed row.
Definition at line 69 of file int4_ptq.c.
{
   return (cols + 1u) / 2u;
 }
Referenced by ie_int4_dequantize_per_row(), ie_int4_dequantize_per_tensor(), ie_int4_quantize_per_row(), ie_int4_quantize_per_tensor(), and ie_weights_decode_int4().