Inference Engine (Clocher): CUDA kernels & launchers
CUDA kernels & launchers
Public API to invoke CUDA kernels for GEMV, activations and packing.
Files
file ie_kernels_cuda.h
CUDA GPU kernels and C-ABI launchers for hot-path vector/matrix ops.
Macros
#define IE_CUDA_STREAM_T_DEFINED
Opaque CUDA stream handle used by this C API.
Typedefs
typedef void * ie_cuda_stream_t
typedef enum ie_act_kind_e ie_act_kind_t
Activation types supported by fused kernels.
Enumerations
enum ie_act_kind_e {
IE_ACT_NONE = 0 , IE_ACT_RELU = 1 , IE_ACT_TANH = 2 , IE_ACT_NONE = 0 ,
IE_ACT_RELU = 1 , IE_ACT_TANH = 2
}
Activation types supported by fused kernels.
Functions
const char * ie_cuda_last_error_string (void)
Return a thread-local message describing the last CUDA error.
int ie_cuda_launch_gemv_rowwise_f32 (const float *W, const float *x, float *y, int rows, int cols, int ldW, float alpha, float beta, ie_cuda_stream_t stream)
Compute y = alpha * W * x + beta * y (row-wise GEMV).
int ie_cuda_launch_gemv_bias_act_f32 (const float *W, const float *x, const float *bias, float *y, int rows, int cols, int ldW, float alpha, float beta, ie_act_kind_t act, ie_cuda_stream_t stream)
Compute y = act(alpha * W*x + bias + beta*y) in one pass.
int ie_cuda_launch_gemv_rowwise_qi8_f32 (const float *W, const int8_t *xq, float *y, int rows, int cols, int ldW, float scale, int zp, float alpha, float beta, ie_cuda_stream_t stream)
Row-wise GEMV with INT8 activations (per-tensor), fused dequantization.
int ie_cuda_launch_gemv_rowwise_qfp8_f32 (const float *W, const uint8_t *x8, float *y, int rows, int cols, int ldW, ie_fp8_format fmt, float alpha, float beta, ie_cuda_stream_t stream)
Row-wise GEMV with FP8 activations (E4M3/E5M2), fused byte decode.
int ie_cuda_launch_vec_tanh_f32 (float *y, const float *x, int n, ie_cuda_stream_t stream)
Compute y[i] = tanh(x[i]) for i in [0, n).
int ie_cuda_launch_pack_w_blockedk_f32 (float *Wp, const float *W, int rows, int cols, int ldW, int block_k, ie_cuda_stream_t stream)
Pack a row-major matrix into Blocked-K layout for better memory access.
Detailed Description
Public API to invoke CUDA kernels for GEMV, activations and packing.
Macro Definition Documentation
IE_CUDA_STREAM_T_DEFINED
#define IE_CUDA_STREAM_T_DEFINED
#include <engine/include/ie_kernels_cuda.h>
Opaque CUDA stream handle used by this C API.
In non-CUDA translation units this is a void*. In the CUDA TU it is replaced by cudaStream_t. You may pass NULL to use the default stream.
Definition at line 50 of file ie_kernels_cuda.h.
Typedef Documentation
ie_act_kind_t
typedef enum ie_act_kind_e ie_act_kind_t
#include <engine/include/ie_kernels_cuda.h>
Activation types supported by fused kernels.
ie_cuda_stream_t
typedef void* ie_cuda_stream_t
#include <engine/include/ie_kernels_cuda.h>
Definition at line 51 of file ie_kernels_cuda.h.
Enumeration Type Documentation
ie_act_kind_e
enum ie_act_kind_e
#include <engine/include/ie_kernels_cuda.h>
Activation types supported by fused kernels.
Enumerator
IE_ACT_NONE
Identity.
IE_ACT_RELU
ReLU: max(0, x).
IE_ACT_TANH
Hyperbolic tangent.
IE_ACT_NONE
Identity.
IE_ACT_RELU
ReLU.
IE_ACT_TANH
tanh().
Definition at line 57 of file ie_kernels_cuda.h.
{
   IE_ACT_NONE = 0,
   IE_ACT_RELU = 1,
   IE_ACT_TANH = 2
 } ie_act_kind_t;
Function Documentation
ie_cuda_last_error_string()
const char* ie_cuda_last_error_string (void)
#include <engine/include/ie_kernels_cuda.h>
Return a thread-local message describing the last CUDA error.
The pointer remains valid until the next launcher call on the same thread. An empty string means "no error".
Returns
NUL-terminated error message (never NULL).
Return a thread-local message describing the last CUDA error.
Returns
Pointer to a thread-local, NUL-terminated message (may be "").
Definition at line 67 of file ie_kernels_cuda.cu.
{
   return g_ie_cuda_err;
 }
References g_ie_cuda_err.
ie_cuda_launch_gemv_bias_act_f32()
int ie_cuda_launch_gemv_bias_act_f32 (const float * W, const float * x, const float * bias, float * y, int rows, int cols, int ldW, float alpha, float beta, ie_act_kind_t act, ie_cuda_stream_t stream)
#include <engine/include/ie_kernels_cuda.h>
Compute y = act(alpha * W*x + bias + beta*y) in one pass.
Applies optional per-row bias (may be NULL → treated as zeros).
Applies activation specified by ie_act_kind_t.
Parameters
W Device pointer to row-major matrix (rows x ldW).
x Device pointer to input vector (length cols).
bias Device pointer to per-row bias (length rows) or NULL.
y Device pointer to output vector (length rows).
rows Number of rows in W/y/bias (>= 1).
cols Number of columns in W and elements in x (>= 1).
ldW Leading dimension of W in elements (>= cols).
alpha Scalar multiplier for W*x.
beta Scalar multiplier for existing y (use 0.f to overwrite).
act Activation kind (see ie_act_kind_t).
stream CUDA stream handle (may be NULL).
Returns
0 on success, negative on error.
Precondition
Pointers are non-NULL device pointers (except bias, which may be NULL).
rows > 0, cols > 0, ldW >= cols.
Postcondition
y contains the result with activation applied.
Compute y = act(alpha * W*x + bias + beta*y) in one pass.
Definition at line 391 of file ie_kernels_cuda.cu.
{
   ie_cuda_set_err(NULL);
   if (!W || !x || !y || rows <= 0 || cols <= 0 || ldW < cols) {
     ie_cuda_set_err("invalid arguments");
     return -1;
   }
   dim3 block(256, 1, 1);
   dim3 grid(rows, 1, 1);
   k_gemv_bias_act_f32<<<grid, block, 0, stream>>>(W, x, bias, y,
                                                   rows, cols, ldW,
                                                   alpha, beta, act);
   CUDA_GUARD(cudaGetLastError());
   return IE_CUDA_OK;
 }
References CUDA_GUARD, IE_CUDA_OK, and ie_cuda_set_err().
ie_cuda_launch_gemv_rowwise_f32()
int ie_cuda_launch_gemv_rowwise_f32 (const float * W, const float * x, float * y, int rows, int cols, int ldW, float alpha, float beta, ie_cuda_stream_t stream)
#include <engine/include/ie_kernels_cuda.h>
Compute y = alpha * W * x + beta * y (row-wise GEMV).
W is dense row-major with rows rows and ldW columns stride.
Each row is reduced in parallel; one block per output row.
Parameters
W Device pointer to row-major matrix (rows x ldW).
x Device pointer to input vector (length cols).
y Device pointer to output vector (length rows).
rows Number of rows in W and elements in y (>= 1).
cols Number of columns in W and elements in x (>= 1).
ldW Leading dimension of W in elements (>= cols).
alpha Scalar multiplier for W*x.
beta Scalar multiplier for existing y (use 0.f to overwrite).
stream CUDA stream handle (may be NULL).
Returns
0 on success, negative on error (see ie_cuda_last_error_string()).
Precondition
Pointers are non-NULL and reference device memory.
rows > 0, cols > 0, ldW >= cols.
Postcondition
y contains the result.
Compute y = alpha * W * x + beta * y (row-wise GEMV).
Definition at line 365 of file ie_kernels_cuda.cu.
{
   ie_cuda_set_err(NULL);
   if (!W || !x || !y || rows <= 0 || cols <= 0 || ldW < cols) {
     ie_cuda_set_err("invalid arguments");
     return -1;
   }
   dim3 block(256, 1, 1);
   dim3 grid(rows, 1, 1);
   k_gemv_rowwise_f32<<<grid, block, 0, stream>>>(W, x, y, rows, cols, ldW,
                                                  alpha, beta);
   CUDA_GUARD(cudaGetLastError());
   return IE_CUDA_OK;
 }
References CUDA_GUARD, IE_CUDA_OK, and ie_cuda_set_err().
ie_cuda_launch_gemv_rowwise_qfp8_f32()
int ie_cuda_launch_gemv_rowwise_qfp8_f32 (const float * W, const uint8_t * x8, float * y, int rows, int cols, int ldW, ie_fp8_format fmt, float alpha, float beta, ie_cuda_stream_t stream)
#include <engine/include/ie_kernels_cuda.h>
Row-wise GEMV with FP8 activations (E4M3/E5M2), fused byte decode.
Parameters
W Float weights on device (row-major), size rows x ldW.
x8 FP8 activations on device (bytes), length cols.
y Output on device, length rows.
rows Rows.
cols Cols.
ldW Leading dimension (>= cols).
fmt FP8 format (IE_FP8_E4M3 or IE_FP8_E5M2).
alpha Scale for W*x.
beta Scale for existing y.
stream CUDA stream (may be NULL).
Returns
0 on success, negative on error.
Row-wise GEMV with FP8 activations (E4M3/E5M2), fused byte decode.
Definition at line 450 of file ie_kernels_cuda.cu.
{
   ie_cuda_set_err(NULL);
   if (!W || !x8 || !y || rows <= 0 || cols <= 0 || ldW < cols) {
     ie_cuda_set_err("invalid arguments");
     return -1;
   }
   dim3 block(256, 1, 1);
   dim3 grid(rows, 1, 1);
   k_gemv_rowwise_qfp8_f32<<<grid, block, 0, stream>>>(W, x8, y,
                                                       rows, cols, ldW,
                                                       fmt, alpha, beta);
   CUDA_GUARD(cudaGetLastError());
   return IE_CUDA_OK;
 }
References CUDA_GUARD, IE_CUDA_OK, and ie_cuda_set_err().
ie_cuda_launch_gemv_rowwise_qi8_f32()
int ie_cuda_launch_gemv_rowwise_qi8_f32 (const float * W, const int8_t * xq, float * y, int rows, int cols, int ldW, float scale, int zp, float alpha, float beta, ie_cuda_stream_t stream)
#include <engine/include/ie_kernels_cuda.h>
Row-wise GEMV with INT8 activations (per-tensor), fused dequantization.
Dequantization model: real = scale * (q - zero_point).
Parameters
W Float weights on device (row-major), size rows x ldW.
xq INT8 activations on device, length cols.
y Output on device, length rows.
rows Rows.
cols Cols.
ldW Leading dimension (>= cols).
scale Per-tensor scale.
zp Per-tensor zero-point.
alpha Scale for W*x.
beta Scale for existing y.
stream CUDA stream (may be NULL).
Returns
0 on success, negative on error.
Row-wise GEMV with INT8 activations (per-tensor), fused dequantization.
Definition at line 420 of file ie_kernels_cuda.cu.
{
   ie_cuda_set_err(NULL);
   if (!W || !xq || !y || rows <= 0 || cols <= 0 || ldW < cols) {
     ie_cuda_set_err("invalid arguments");
     return -1;
   }
   dim3 block(256, 1, 1);
   dim3 grid(rows, 1, 1);
   k_gemv_rowwise_qi8_f32<<<grid, block, 0, stream>>>(W, xq, y,
                                                      rows, cols, ldW,
                                                      scale, zp,
                                                      alpha, beta);
   CUDA_GUARD(cudaGetLastError());
   return IE_CUDA_OK;
 }
References CUDA_GUARD, IE_CUDA_OK, and ie_cuda_set_err().
ie_cuda_launch_pack_w_blockedk_f32()
int ie_cuda_launch_pack_w_blockedk_f32 (float * Wp, const float * W, int rows, int cols, int ldW, int block_k, ie_cuda_stream_t stream)
#include <engine/include/ie_kernels_cuda.h>
Pack a row-major matrix into Blocked-K layout for better memory access.
The K dimension (columns) is partitioned into tiles of size block_k. Data are stored as contiguous tiles:
int kb = k / block_k;  // tile index along K
int ko = k % block_k;  // in-tile offset
size_t dst = ((size_t)kb * rows + r) * (size_t)block_k + (size_t)ko;
Wp[dst] = W[(size_t)r * ldW + (size_t)k];
Parameters
Wp Device pointer to destination buffer (size = rows*cols).
W Device pointer to source row-major matrix.
rows Number of rows (>= 1).
cols Number of columns (>= 1).
ldW Leading dimension of W in elements (>= cols).
block_k Tile size along K (e.g., 32/64/128; must be > 0).
stream CUDA stream handle (may be NULL).
Returns
0 on success, negative on error.
Precondition
Wp and W are device pointers with sufficient capacity.
Postcondition
Wp contains the packed matrix in Blocked-K layout.
Pack a row-major matrix into Blocked-K layout for better memory access.
Definition at line 500 of file ie_kernels_cuda.cu.
{
   ie_cuda_set_err(NULL);
   if (!Wp || !W || rows <= 0 || cols <= 0 || ldW < cols || block_k <= 0) {
     ie_cuda_set_err("invalid arguments");
     return -1;
   }
   dim3 block(32, 8, 1); /* 256 threads per block */
   dim3 grid((cols + block.x - 1) / block.x,
             (rows + block.y - 1) / block.y,
             1);
   k_pack_w_blockedk_f32<<<grid, block, 0, stream>>>(Wp, W,
                                                     rows, cols,
                                                     ldW, block_k);
   CUDA_GUARD(cudaGetLastError());
   return IE_CUDA_OK;
 }
References CUDA_GUARD, IE_CUDA_OK, and ie_cuda_set_err().
ie_cuda_launch_vec_tanh_f32()
int ie_cuda_launch_vec_tanh_f32 (float * y, const float * x, int n, ie_cuda_stream_t stream)
#include <engine/include/ie_kernels_cuda.h>
Compute y[i] = tanh(x[i]) for i in [0, n).
Parameters
y Device pointer to output vector (length n).
x Device pointer to input vector (length n).
n Number of elements (>= 1).
stream CUDA stream handle (may be NULL).
Returns
0 on success, negative on error.
Precondition
x and y are valid device pointers with at least n elements.
Postcondition
y contains elementwise tanh(x).
Compute y[i] = tanh(x[i]) for i in [0, n).
Definition at line 478 of file ie_kernels_cuda.cu.
{
   ie_cuda_set_err(NULL);
   if (!x || !y || n <= 0) {
     ie_cuda_set_err("invalid arguments");
     return -1;
   }
   const int block = 256;
   int grid = (n + block - 1) / block;
   if (grid > 65535) grid = 65535;
   k_vec_tanh_f32<<<grid, block, 0, stream>>>(y, x, n);
   CUDA_GUARD(cudaGetLastError());
   return IE_CUDA_OK;
 }
References CUDA_GUARD, IE_CUDA_OK, and ie_cuda_set_err().