Inference Engine (Clocher): engine/include/ie_device_cuda.h File Reference
ie_device_cuda.h File Reference
C ABI wrapper for CUDA runtime functionality used by the engine.
#include <stddef.h>
#include <stdint.h>
Typedefs
typedef enum ie_cuda_copy_kind ie_cuda_copy_kind_t
Copy direction selector for ie_cuda_memcpy().
Enumerations
enum ie_cuda_copy_kind { IE_CUDA_COPY_DEFAULT = 0 , IE_CUDA_COPY_H2D = 1 , IE_CUDA_COPY_D2H = 2 , IE_CUDA_COPY_D2D = 3 }
Copy direction selector for ie_cuda_memcpy().
Functions
int ie_cuda_is_available (void)
Returns non-zero if at least one CUDA device is available.
int ie_cuda_init (int device_ordinal, char *out_name, size_t name_cap, char *out_driver, size_t driver_cap)
Initialize CUDA for a given device ordinal and return basic identity strings.
void * ie_cuda_malloc (size_t nbytes)
Allocate device memory.
void ie_cuda_free (void *p)
Free device memory allocated by ie_cuda_malloc().
int ie_cuda_memcpy (void *dst, const void *src, size_t nbytes, ie_cuda_copy_kind_t kind)
Copy memory using CUDA.
int ie_cuda_gemv_f32 (const float *dW, const float *dx, float *dy, size_t rows, size_t cols, const float *dbias)
Launch a GEMV FP32 kernel: y = W*x + bias (bias optional).
int ie_cuda_gemv_q4_0_f32 (const uint8_t *dW_q4, const uint8_t *dW_scales, size_t scale_bytes, const float *dx, float *dy, size_t rows, size_t cols, const uint16_t *dbias_bf16)
Launch a GEMV Q4_0 kernel: y = dequant(Wq4) * x (+ optional BF16 bias).
const char * ie_cuda_last_error_string (void)
Return a human-readable description of the last CUDA error seen by this wrapper.
Detailed Description
C ABI wrapper for CUDA runtime functionality used by the engine.
This header intentionally exposes a small, C-callable surface so that C translation units (compiled with a C compiler) can drive CUDA work without including CUDA headers.
The implementation is provided by a .cu translation unit compiled by NVCC.
Definition in file ie_device_cuda.h.
Typedef Documentation
ie_cuda_copy_kind_t
typedef enum ie_cuda_copy_kind ie_cuda_copy_kind_t
Copy direction selector for ie_cuda_memcpy().
IE_CUDA_COPY_DEFAULT uses cudaMemcpyDefault, which relies on unified virtual addressing when available. If you know the direction, prefer the explicit modes.
Enumeration Type Documentation
ie_cuda_copy_kind
enum ie_cuda_copy_kind
Copy direction selector for ie_cuda_memcpy().
IE_CUDA_COPY_DEFAULT uses cudaMemcpyDefault, which relies on unified virtual addressing when available. If you know the direction, prefer the explicit modes.
Enumerator
IE_CUDA_COPY_DEFAULT
Use cudaMemcpyDefault.
IE_CUDA_COPY_H2D
Host to device.
IE_CUDA_COPY_D2H
Device to host.
IE_CUDA_COPY_D2D
Device to device.
Definition at line 28 of file ie_device_cuda.h.
{
  IE_CUDA_COPY_DEFAULT = 0,
  IE_CUDA_COPY_H2D     = 1,
  IE_CUDA_COPY_D2H     = 2,
  IE_CUDA_COPY_D2D     = 3
} ie_cuda_copy_kind_t;
Function Documentation
ie_cuda_free()
void ie_cuda_free (void * p)
Free device memory allocated by ie_cuda_malloc().
Parameters
p Device pointer (may be NULL).
Free device memory allocated by ie_cuda_malloc().
Parameters
p Device pointer (may be NULL).
Definition at line 297 of file ie_device_cuda.cu.
{
  if (!p) return;
  const cudaError_t st = cudaFree(p);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaFree", st);
    return;
  }
  ie_cuda_clear_last_error();
}
References ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_destroy_thunk(), and cuda_ensure_capacity().
ie_cuda_gemv_f32()
int ie_cuda_gemv_f32 (const float * dW, const float * dx, float * dy, size_t rows, size_t cols, const float * dbias)
Launch a GEMV FP32 kernel: y = W*x + bias (bias optional).
All pointers must be device pointers. bias may be NULL.
Parameters
dW Device pointer to row-major matrix W (rows x cols).
dx Device pointer to vector x (cols).
dy Device pointer to vector y (rows).
rows Number of rows in W / entries in y.
cols Number of cols in W / entries in x.
dbias Optional device pointer to bias (rows) or NULL.
Returns
0 on success, negative on failure.
Launch a GEMV FP32 kernel: y = W*x + bias (bias optional).
Parameters
dW Device pointer to row-major weights (rows x cols).
dx Device pointer to input vector (cols).
dy Device pointer to output vector (rows).
rows Rows.
cols Cols.
dbias Optional bias vector (rows) or NULL.
Returns
0 on success, negative on failure.
Definition at line 346 of file ie_device_cuda.cu.
{
  if (!dW || !dx || !dy || rows == 0 || cols == 0) {
    std::snprintf(g_last_err, sizeof(g_last_err), "%s", "ie_cuda_gemv_f32: invalid args");
    return -1;
  }
  const int block = 256;
  const int grid = (int)((rows + (size_t)block - 1) / (size_t)block);
  ie_gemv_rowwise_f32_kernel<<<grid, block>>>(dW, dx, dy, dbias, rows, cols);
  cudaError_t st = cudaGetLastError();
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("kernel launch", st);
    return -2;
  }
  st = cudaDeviceSynchronize();
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaDeviceSynchronize", st);
    return -3;
  }
  ie_cuda_clear_last_error();
  return 0;
}
References g_last_err, ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_gemv_f32_thunk().
ie_cuda_gemv_q4_0_f32()
int ie_cuda_gemv_q4_0_f32 (const uint8_t * dW_q4, const uint8_t * dW_scales, size_t scale_bytes, const float * dx, float * dy, size_t rows, size_t cols, const uint16_t * dbias_bf16)
Launch a GEMV Q4_0 kernel: y = dequant(Wq4) * x (+ optional BF16 bias).
All pointers must be device pointers. bias may be NULL.
Parameters
dW_q4 Device pointer to packed Q4_0 weights.
dW_scales Device pointer to per-block scales.
scale_bytes Bytes per scale (1 or 2).
dx Device pointer to input vector (FP32).
dy Device pointer to output vector (FP32).
rows Rows.
cols Cols (multiple of 32).
dbias_bf16 Optional device pointer to BF16 bias (rows) or NULL.
Returns
0 on success, negative on failure.
Launch a GEMV Q4_0 kernel: y = dequant(Wq4) * x (+ optional BF16 bias).
Definition at line 381 of file ie_device_cuda.cu.
{
  if (!dW_q4 || !dW_scales || !dx || !dy || rows == 0 || cols == 0) {
    std::snprintf(g_last_err, sizeof(g_last_err), "%s", "ie_cuda_gemv_q4_0_f32: invalid args");
    return -1;
  }
  const int block = 256;
  const int grid = (int)((rows + (size_t)block - 1) / (size_t)block);
  ie_gemv_q4_0_f32_kernel<<<grid, block>>>(dW_q4, dW_scales, scale_bytes,
                                          dx, dy, rows, cols, dbias_bf16);
  cudaError_t st = cudaGetLastError();
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("q4 kernel launch", st);
    return -2;
  }
  st = cudaDeviceSynchronize();
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaDeviceSynchronize", st);
    return -3;
  }
  ie_cuda_clear_last_error();
  return 0;
}
References g_last_err, ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_gemv_q4_0_f32_thunk().
ie_cuda_init()
int ie_cuda_init (int device_ordinal, char * out_name, size_t name_cap, char * out_driver, size_t driver_cap)
Initialize CUDA for a given device ordinal and return basic identity strings.
This performs cudaSetDevice() and a minimal runtime initialization (cudaFree(0)) so that driver activity is observable (e.g., /dev/nvidiactl gets touched).
Parameters
device_ordinal CUDA device ordinal (0..N-1).
out_name Output buffer for the GPU name (may be NULL if name_cap=0).
name_cap Capacity of out_name in bytes.
out_driver Output buffer for a driver/runtime version string (may be NULL if driver_cap=0).
driver_cap Capacity of out_driver in bytes.
Returns
0 on success, negative on failure.
Initialize CUDA for a given device ordinal and return basic identity strings.
This forces runtime/driver initialization via cudaFree(0) so preflight checks can observe real driver activity.
Parameters
device_ordinal CUDA device ordinal.
out_name Output buffer for device name (may be NULL).
name_cap Capacity of out_name in bytes.
out_driver Output buffer for driver/runtime versions (may be NULL).
driver_cap Capacity of out_driver in bytes.
Returns
0 on success, negative on failure.
Definition at line 236 of file ie_device_cuda.cu.
{
  cudaError_t st = cudaSetDevice(device_ordinal);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaSetDevice", st);
    return -1;
  }
  st = cudaFree(0);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaFree(0)", st);
    return -2;
  }
  cudaDeviceProp prop;
  std::memset(&prop, 0, sizeof(prop));
  st = cudaGetDeviceProperties(&prop, device_ordinal);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaGetDeviceProperties", st);
    return -3;
  }
  if (out_name && name_cap) {
    std::snprintf(out_name, name_cap, "%s", prop.name);
  }
  int drv = 0, rt = 0;
  (void)cudaDriverGetVersion(&drv);
  (void)cudaRuntimeGetVersion(&rt);
  if (out_driver && driver_cap) {
    std::snprintf(out_driver, driver_cap, "driver=%d runtime=%d", drv, rt);
  }
  ie_cuda_clear_last_error();
  return 0;
}
References ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_try_create().
ie_cuda_is_available()
int ie_cuda_is_available (void)
Returns non-zero if at least one CUDA device is available.
This call will initialize the CUDA runtime enough to query device count.
Returns
1 if devices exist, 0 otherwise.
Returns non-zero if at least one CUDA device is available.
Returns
1 if at least one CUDA device is visible, 0 otherwise.
Definition at line 212 of file ie_device_cuda.cu.
{
  int n = 0;
  const cudaError_t st = cudaGetDeviceCount(&n);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaGetDeviceCount", st);
    return 0;
  }
  ie_cuda_clear_last_error();
  return (n > 0) ? 1 : 0;
}
References ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_try_create().
ie_cuda_last_error_string()
const char * ie_cuda_last_error_string (void)
Return a human-readable description of the last CUDA error seen by this wrapper.
Returns
Pointer to an internal static string (valid until next CUDA wrapper call).
Return a human-readable description of the last CUDA error seen by this wrapper.
Returns
Pointer to a NUL-terminated static buffer (never NULL).
Definition at line 72 of file ie_device_cuda.cu.
{
  return g_last_err;
}
ie_cuda_malloc()
void * ie_cuda_malloc (size_t nbytes)
Allocate device memory.
Parameters
nbytes Number of bytes.
Returns
Device pointer on success, NULL on failure.
Allocate device memory.
Parameters
nbytes Number of bytes.
Returns
Device pointer on success, NULL on failure.
Definition at line 281 of file ie_device_cuda.cu.
{
  void *p = nullptr;
  const cudaError_t st = cudaMalloc(&p, nbytes);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaMalloc", st);
    return nullptr;
  }
  ie_cuda_clear_last_error();
  return p;
}
References ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_ensure_capacity().
ie_cuda_memcpy()
int ie_cuda_memcpy (void * dst, const void * src, size_t nbytes, ie_cuda_copy_kind_t kind)
Copy memory using CUDA.
For IE_CUDA_COPY_DEFAULT, cudaMemcpyDefault is used.
Parameters
dst Destination pointer.
src Source pointer.
nbytes Number of bytes.
kind Copy kind.
Returns
0 on success, negative on failure.
Copy memory using CUDA.
Parameters
dst Destination pointer.
src Source pointer.
nbytes Number of bytes.
kind Copy direction.
Returns
0 on success, negative on failure.
Definition at line 316 of file ie_device_cuda.cu.
{
  cudaMemcpyKind ck = cudaMemcpyDefault;
  switch (kind) {
    case IE_CUDA_COPY_H2D: ck = cudaMemcpyHostToDevice; break;
    case IE_CUDA_COPY_D2H: ck = cudaMemcpyDeviceToHost; break;
    case IE_CUDA_COPY_D2D: ck = cudaMemcpyDeviceToDevice; break;
    case IE_CUDA_COPY_DEFAULT: default: ck = cudaMemcpyDefault; break;
  }
  const cudaError_t st = cudaMemcpy(dst, src, nbytes, ck);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaMemcpy", st);
    return -1;
  }
  ie_cuda_clear_last_error();
  return 0;
}
References ie_cuda_clear_last_error(), IE_CUDA_COPY_D2D, IE_CUDA_COPY_D2H, IE_CUDA_COPY_DEFAULT, IE_CUDA_COPY_H2D, and ie_cuda_set_last_error_cuda().
Referenced by cuda_gemv_f32_thunk(), cuda_gemv_q4_0_f32_thunk(), and cuda_memcpy_thunk().