Inference Engine (Clocher): engine/include/ie_batcher.h File Reference
ie_batcher.h File Reference
Public API for asynchronous prompt prefetch + tokenization batcher.
#include <stddef.h>
#include <stdint.h>
Data Structures
struct ie_batcher_item_t
Tokenized item produced by the batcher.
struct ie_batcher_view
Microbatch view returned by ie_batcher_get.
Typedefs
typedef struct ie_batcher_view ie_batcher_view_t
Microbatch view returned by ie_batcher_get.
typedef struct ie_batcher ie_batcher_t
Opaque batcher handle.
typedef int(* ie_batcher_tokenize_fn) (const char *prompt, uint32_t **out_ids, size_t *out_n, void *user_ctx)
Tokenizer callback signature used by the batcher workers.
Functions
ie_batcher_t * ie_batcher_create (const char **prompts, size_t n_prompts, size_t microbatch, size_t queue_capacity, unsigned n_workers, ie_batcher_tokenize_fn tokenize_cb, void *user_ctx)
Create a new asynchronous tokenizer batcher.
int ie_batcher_get (ie_batcher_t *b, ie_batcher_view_t *out_view)
Obtain a contiguous slice of ready items without copying.
void ie_batcher_advance (ie_batcher_t *b, size_t n_consumed)
Release items previously returned by ie_batcher_get.
void ie_batcher_destroy (ie_batcher_t *b)
Destroy a batcher, joining workers and freeing all resources.
Detailed Description
Public API for asynchronous prompt prefetch + tokenization batcher.
The batcher asynchronously tokenizes input prompts on background worker threads and enqueues results in a bounded ring buffer. The consumer reads contiguous microbatches (views) directly from the ring without copying, then advances to release those items.
Ownership:
The tokenizer callback must allocate *out_ids for each item.
The batcher takes ownership on enqueue and frees payloads on advance.
Definition in file ie_batcher.h.
Typedef Documentation
ie_batcher_t
typedef struct ie_batcher ie_batcher_t
Opaque batcher handle.
Definition at line 1 of file ie_batcher.h.
ie_batcher_tokenize_fn
typedef int(* ie_batcher_tokenize_fn) (const char *prompt, uint32_t **out_ids, size_t *out_n, void *user_ctx)
Tokenizer callback signature used by the batcher workers.
The implementation must allocate *out_ids (e.g., via malloc) and set *out_n. The batcher takes ownership of *out_ids after enqueue.
Parameters
prompt Zero-terminated input string to tokenize.
out_ids Output: allocated array of token IDs.
out_n Output: number of IDs in *out_ids.
user_ctx Opaque pointer passed through from ie_batcher_create.
Returns
int 0 on success, non-zero on failure.
Definition at line 64 of file ie_batcher.h.
ie_batcher_view_t
typedef struct ie_batcher_view ie_batcher_view_t
Microbatch view returned by ie_batcher_get.
The view points into the batcher's ring; do not free or retain the pointers beyond the call to ie_batcher_advance.
Function Documentation
ie_batcher_advance()
void ie_batcher_advance (ie_batcher_t * b, size_t n_consumed)
Release items previously returned by ie_batcher_get.
Frees payloads and advances the ring read pointer, then signals producers that space is available.
Parameters
b Batcher handle (non-NULL).
n_consumed Number of items to release; must not exceed the last view count.
Definition at line 250 of file ie_batcher.c.
{
   if (!b || n_consumed == 0) return;
   pthread_mutex_lock(&b->mu);
   for (size_t i = 0; i < n_consumed; ++i) {
     size_t idx = (b->r + i) % b->cap;
     clear_item(&b->ring[idx]);
   }
   b->r = (b->r + n_consumed) % b->cap;
   b->size -= n_consumed;
   pthread_cond_signal(&b->cv_not_full);
   pthread_mutex_unlock(&b->mu);
 }
References ie_batcher::cap, clear_item(), ie_batcher::cv_not_full, ie_batcher::mu, ie_batcher::r, ie_batcher::ring, and ie_batcher::size.
Referenced by test_basic_prefetch_and_order(), and test_wrap_and_view_limits().
ie_batcher_create()
ie_batcher_t* ie_batcher_create (const char ** prompts, size_t n_prompts, size_t microbatch, size_t queue_capacity, unsigned n_workers, ie_batcher_tokenize_fn tokenize_cb, void * user_ctx)
Create a new asynchronous tokenizer batcher.
Spawns up to n_workers threads that prefetch and tokenize prompts into a bounded ring buffer. The consumer should call ie_batcher_get followed by ie_batcher_advance in a loop until the stream is drained.
Defaults:
If microbatch == 0, it is treated as 1.
If queue_capacity == 0, it is treated as max(microbatch, 8).
If n_workers == 0, it is treated as 1.
Parameters
prompts Array of input UTF-8 prompt strings (not owned; must outlive the batcher).
n_prompts Number of prompts in prompts.
microbatch Maximum items returned per view. Use 0 for default.
queue_capacity Ring capacity in items. Use 0 for default.
n_workers Number of tokenizer worker threads. Use 0 for default.
tokenize_cb User tokenizer callback (must not be NULL).
user_ctx Opaque pointer forwarded to tokenize_cb; may be NULL.
Returns
ie_batcher_t* Handle on success, or NULL on allocation/spawn error.
Definition at line 171 of file ie_batcher.c.
{
   (void)n_workers; /* determinism: always 1 producer thread */
   if (!prompts || n_prompts == 0 || !tokenize_cb) return NULL;
   if (queue_capacity == 0) queue_capacity = microbatch ? microbatch : 8;
   ie_batcher_t *b = (ie_batcher_t*)xcalloc(1, sizeof(*b));
   if (!b) return NULL;
   b->prompts = prompts;
   b->n_prompts = n_prompts;
   b->microbatch = microbatch ? microbatch : 1;
   b->cap = queue_capacity;
   b->ring = (ie_batcher_item_t*)xcalloc(b->cap, sizeof(*b->ring));
   if (!b->ring) { free(b); return NULL; }
   pthread_mutex_init(&b->mu, NULL);
   pthread_cond_init(&b->cv_not_full, NULL);
   pthread_cond_init(&b->cv_not_empty, NULL);
   b->tokenize = tokenize_cb;
   b->user_ctx = user_ctx;
   b->n_workers = 1;
   b->threads = (pthread_t*)xcalloc(b->n_workers, sizeof(pthread_t));
   if (!b->threads) {
     free(b->ring);
     free(b);
     return NULL;
   }
   if (pthread_create(&b->threads[0], NULL, worker_main, b) != 0) {
     free(b->threads);
     free(b->ring);
     free(b);
     return NULL;
   }
   return b;
 }
References ie_batcher::cap, ie_batcher::cv_not_empty, ie_batcher::cv_not_full, ie_batcher::microbatch, ie_batcher::mu, ie_batcher::n_prompts, ie_batcher::n_workers, ie_batcher::prompts, ie_batcher::ring, ie_batcher::threads, ie_batcher::tokenize, ie_batcher::user_ctx, worker_main(), and xcalloc().
Referenced by test_basic_prefetch_and_order(), test_partial_teardown(), and test_wrap_and_view_limits().
ie_batcher_destroy()
void ie_batcher_destroy (ie_batcher_t * b)
Destroy a batcher, joining workers and freeing all resources.
Safe to call with NULL.
Parameters
b Batcher handle (may be NULL).
Definition at line 267 of file ie_batcher.c.
{
   if (!b) return;
   pthread_mutex_lock(&b->mu);
   b->stop = 1;
   pthread_cond_broadcast(&b->cv_not_full);
   pthread_cond_broadcast(&b->cv_not_empty);
   pthread_mutex_unlock(&b->mu);
   for (unsigned i = 0; i < b->n_workers; ++i) {
     if (b->threads[i]) pthread_join(b->threads[i], NULL);
   }
   /* Free any remaining items in the ring. */
   for (size_t i = 0; i < b->cap; ++i) clear_item(&b->ring[i]);
   pthread_cond_destroy(&b->cv_not_full);
   pthread_cond_destroy(&b->cv_not_empty);
   pthread_mutex_destroy(&b->mu);
   free(b->threads);
   free(b->ring);
   free(b);
 }
References ie_batcher::cap, clear_item(), ie_batcher::cv_not_empty, ie_batcher::cv_not_full, ie_batcher::mu, ie_batcher::n_workers, ie_batcher::ring, ie_batcher::stop, and ie_batcher::threads.
Referenced by test_basic_prefetch_and_order(), test_partial_teardown(), and test_wrap_and_view_limits().
ie_batcher_get()
int ie_batcher_get (ie_batcher_t * b, ie_batcher_view_t * out_view)
Obtain a contiguous slice of ready items without copying.
If no items are ready but production is still in progress, this function blocks until an item is available (or the batcher is stopping).
When this function returns 0, the stream is drained; out_view->done will be set to 1 and out_view->items will be NULL.
Parameters
b Batcher handle (non-NULL).
out_view Output view describing a contiguous span of items.
Returns
int 1 if a non-empty view was produced; 0 if the stream is drained.
Definition at line 217 of file ie_batcher.c.
{
   if (!b || !out_view) return 0;
   pthread_mutex_lock(&b->mu);
   while (b->size == 0 && !b->producer_done && !b->stop) {
     pthread_cond_wait(&b->cv_not_empty, &b->mu);
   }
   if (b->size == 0 && (b->producer_done || b->stop)) {
     out_view->items = NULL;
     out_view->count = 0;
     out_view->done = 1;
     pthread_mutex_unlock(&b->mu);
     return 0;
   }
   size_t avail = b->size;
   size_t first = b->r;
   size_t can_take = b->microbatch;
   if (can_take > avail) can_take = avail;
   /* Return a contiguous tail segment only (no wrap across r->end). */
   size_t tail = b->cap - first;
   if (can_take > tail) can_take = tail;
   out_view->items = &b->ring[first];
   out_view->count = can_take;
   out_view->done = (b->producer_done && (b->size == can_take));
   pthread_mutex_unlock(&b->mu);
   return 1;
 }
References ie_batcher::cap, ie_batcher_view::count, ie_batcher::cv_not_empty, ie_batcher_view::done, ie_batcher_view::items, ie_batcher::microbatch, ie_batcher::mu, ie_batcher::producer_done, ie_batcher::r, ie_batcher::ring, ie_batcher::size, and ie_batcher::stop.
Referenced by test_basic_prefetch_and_order(), test_partial_teardown(), and test_wrap_and_view_limits().