Inference Engine (Clocher): engine/include/ie_config.h File Reference
ie_config.h File Reference
Tiny, header-only helpers for engine configuration defaults and env overrides.
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct ie_config_env
Macros
#define IE_ENV_REQUIRE_MODEL "IE_REQUIRE_MODEL"
Require IEBIN presence (strict mode) when set to "1".
#define IE_ENV_BYTES_PER_TOKEN "IE_BYTES_PER_TOKEN"
Bytes to touch per token during the measured window (0 disables).
#define IE_ENV_STRIDE_BYTES "IE_STRIDE_BYTES"
Stride in bytes for the work-touch loop.
#define IE_ENV_VERIFY_TOUCH "IE_VERIFY_TOUCH"
When non-zero, prevents the compiler from eliding the touch accumulator.
#define IE_ENV_PRECISION "IE_PRECISION"
Precision label override (fp32|bf16|fp16|int8w|int4|int4w).
#define IE_ENV_PRECISION_ALT "PRECISION"
Compatibility alias for precision; lower precedence than IE_ENV_PRECISION.
Typedefs
typedef struct ie_config_env ie_config_env_t
Functions
static const char * ie_cfg_env_str (const char *name, const char *defv)
Return an environment variable value or a default when unset/empty.
static long ie_cfg_env_long (const char *name, long defv)
Parse an environment variable as long; fall back to a default on error.
static void ie_cfg_load_env (ie_config_env_t *out)
Load a snapshot of environment-driven configuration into out.
Detailed Description
Tiny, header-only helpers for engine configuration defaults and env overrides.
This header centralizes:
Canonical names for environment variables used by the CLI/harness.
Safe getters for integers and strings from the environment.
A small struct (ie_config_env_t) that aggregates common env-driven knobs.
It is header-only by design to avoid adding a new compilation unit. All functions are static inline and can be included from multiple TUs.
Definition in file ie_config.h.
Macro Definition Documentation
IE_ENV_BYTES_PER_TOKEN
#define IE_ENV_BYTES_PER_TOKEN "IE_BYTES_PER_TOKEN"
Bytes to touch per token during the measured window (0 disables).
Definition at line 31 of file ie_config.h.
IE_ENV_PRECISION
#define IE_ENV_PRECISION "IE_PRECISION"
Precision label override (fp32|bf16|fp16|int8w|int4|int4w).
Definition at line 37 of file ie_config.h.
IE_ENV_PRECISION_ALT
#define IE_ENV_PRECISION_ALT "PRECISION"
Compatibility alias for precision; lower precedence than IE_ENV_PRECISION.
Definition at line 39 of file ie_config.h.
IE_ENV_REQUIRE_MODEL
#define IE_ENV_REQUIRE_MODEL "IE_REQUIRE_MODEL"
Require IEBIN presence (strict mode) when set to "1".
Definition at line 29 of file ie_config.h.
IE_ENV_STRIDE_BYTES
#define IE_ENV_STRIDE_BYTES "IE_STRIDE_BYTES"
Stride in bytes for the work-touch loop.
Definition at line 33 of file ie_config.h.
IE_ENV_VERIFY_TOUCH
#define IE_ENV_VERIFY_TOUCH "IE_VERIFY_TOUCH"
When non-zero, prevents the compiler from eliding the touch accumulator.
Definition at line 35 of file ie_config.h.
Typedef Documentation
ie_config_env_t
typedef struct ie_config_env ie_config_env_t
Function Documentation
ie_cfg_env_long()
static long ie_cfg_env_long (const char * name, long defv) inline static
Parse an environment variable as long; fall back to a default on error.
Accepts base-10 only. Overflow/underflow are handled by strtol clamping.
Parameters
name Environment variable name.
defv Default value when unset/invalid.
Returns
Parsed value or defv.
Definition at line 99 of file ie_config.h.
{
   const char *s = getenv(name);
   if (!s || !*s) return defv;
   char *end = NULL;
   long v = strtol(s, &end, 10);
   return (end && *end == '\0') ? v : defv;
 }
Referenced by ie_cfg_load_env().
ie_cfg_env_str()
static const char* ie_cfg_env_str (const char * name, const char * defv) inline static
Return an environment variable value or a default when unset/empty.
Parameters
name Environment variable name.
defv Default string when unset/empty.
Returns
Pointer to environment string or defv (never NULL).
Definition at line 85 of file ie_config.h.
{
   const char *s = getenv(name);
   return (s && *s) ? s : defv;
 }
Referenced by ie_cfg_load_env().
ie_cfg_load_env()
static void ie_cfg_load_env (ie_config_env_t * out) inline static
Load a snapshot of environment-driven configuration into out.
Resolution order for precision is: 1) IE_PRECISION if set/non-empty 2) PRECISION if set/non-empty 3) "fp32" otherwise
Parameters
out Output struct (must be non-NULL).
Definition at line 117 of file ie_config.h.
{
   if (!out) return;
   out->require_model  = (int)ie_cfg_env_long(IE_ENV_REQUIRE_MODEL, 0);
   long bpt            = ie_cfg_env_long(IE_ENV_BYTES_PER_TOKEN, 0);
   long stride         = ie_cfg_env_long(IE_ENV_STRIDE_BYTES, 256);
   out->bytes_per_token= (bpt > 0 ? (size_t)bpt : 0u);
   out->stride_bytes   = (stride > 0 ? (size_t)stride : 1u);
   out->verify_touch   = (int)ie_cfg_env_long(IE_ENV_VERIFY_TOUCH, 0);
   const char *p = ie_cfg_env_str(IE_ENV_PRECISION,
                    ie_cfg_env_str(IE_ENV_PRECISION_ALT, IE_PREC_FP32));
   out->precision = p;
 }
References ie_cfg_env_long(), ie_cfg_env_str(), IE_ENV_BYTES_PER_TOKEN, IE_ENV_PRECISION, IE_ENV_PRECISION_ALT, IE_ENV_REQUIRE_MODEL, IE_ENV_STRIDE_BYTES, IE_ENV_VERIFY_TOUCH, and IE_PREC_FP32.