Inference Engine (Clocher): engine/src/kernels/ie_kernels_cuda.cu File Reference
ie_kernels_cuda.cu File Reference
CUDA implementations of GEMV/activation/packing kernels + C-ABI launchers.
#include <cuda_runtime.h>
#include <math_constants.h>
#include <stddef.h>
#include <stdint.h>
#include "ie_kernels_cuda.h"
#include "ie_quant_act.h"
Macros
#define IE_CUDA_OK 0
#define IE_CUDA_STREAM_T_DEFINED
#define CUDA_GUARD(call)
CUDA error guard macro that stores the error string and returns.
Typedefs
typedef cudaStream_t ie_cuda_stream_t
Functions
static void ie_cuda_set_err (const char *msg)
Set or clear the per-thread CUDA error string buffer.
const char * ie_cuda_last_error_string (void)
Retrieve the last CUDA error string set by a launcher in this TU.
__device__ float ie_apply_activation (float x, ie_act_kind_t act)
Apply a simple activation kind to a scalar.
__device__ float ie_decode_fp8_e4m3_u8 (uint8_t v)
Decode one E4M3 FP8 byte on device (subnormals flushed to zero).
__device__ float ie_decode_fp8_e5m2_u8 (uint8_t v)
Decode one E5M2 FP8 byte on device (IEEE-like special cases).
__global__ void k_gemv_rowwise_f32 (const float *__restrict__ W, const float *__restrict__ x, float *__restrict__ y, int rows, int cols, int ldW, float alpha, float beta)
Row-wise GEMV kernel: y = alpha * W * x + beta * y.
__global__ void k_gemv_bias_act_f32 (const float *__restrict__ W, const float *__restrict__ x, const float *__restrict__ bias, float *__restrict__ y, int rows, int cols, int ldW, float alpha, float beta, ie_act_kind_t act)
Fused GEMV + bias + activation kernel (float activations).
__global__ void k_gemv_rowwise_qi8_f32 (const float *__restrict__ W, const int8_t *__restrict__ xq, float *__restrict__ y, int rows, int cols, int ldW, float scale, int zp, float alpha, float beta)
Row-wise GEMV with INT8 activations (per-tensor), fused dequantization.
__global__ void k_gemv_rowwise_qfp8_f32 (const float *__restrict__ W, const uint8_t *__restrict__ x8, float *__restrict__ y, int rows, int cols, int ldW, ie_fp8_format fmt, float alpha, float beta)
Row-wise GEMV with FP8 activations (E4M3/E5M2), fused decode.
__global__ void k_vec_tanh_f32 (float *__restrict__ y, const float *__restrict__ x, int n)
Elementwise hyperbolic tangent on a vector.
__global__ void k_pack_w_blockedk_f32 (float *__restrict__ Wp, const float *__restrict__ W, int rows, int cols, int ldW, int block_k)
Pack row-major W into Blocked-K layout on device.
int ie_cuda_launch_gemv_rowwise_f32 (const float *W, const float *x, float *y, int rows, int cols, int ldW, float alpha, float beta, ie_cuda_stream_t stream)
Launch row-wise GEMV (float path).
int ie_cuda_launch_gemv_bias_act_f32 (const float *W, const float *x, const float *bias, float *y, int rows, int cols, int ldW, float alpha, float beta, ie_act_kind_t act, ie_cuda_stream_t stream)
Launch fused GEMV + bias + activation (float).
int ie_cuda_launch_gemv_rowwise_qi8_f32 (const float *W, const int8_t *xq, float *y, int rows, int cols, int ldW, float scale, int zp, float alpha, float beta, ie_cuda_stream_t stream)
Launch GEMV with INT8 activations (per-tensor), fused dequantization.
int ie_cuda_launch_gemv_rowwise_qfp8_f32 (const float *W, const uint8_t *x8, float *y, int rows, int cols, int ldW, ie_fp8_format fmt, float alpha, float beta, ie_cuda_stream_t stream)
Launch GEMV with FP8 activations (E4M3/E5M2), fused byte decode.
int ie_cuda_launch_vec_tanh_f32 (float *y, const float *x, int n, ie_cuda_stream_t stream)
Launch elementwise tanh on device.
int ie_cuda_launch_pack_w_blockedk_f32 (float *Wp, const float *W, int rows, int cols, int ldW, int block_k, ie_cuda_stream_t stream)
Launch packing of row-major W into Blocked-K layout on device.
Variables
static __thread char g_ie_cuda_err [256] = {0}
Detailed Description
CUDA implementations of GEMV/activation/packing kernels + C-ABI launchers.
This is the only translation unit that includes CUDA headers. The public header ie_kernels_cuda.h keeps the rest of the codebase CUDA-agnostic.
Kernel policy (baseline, safe defaults)
GEMV row-wise: one block per output row, 256 threads per block, strided K loop with shared-memory reduction.
Fused GEMV+bias+activation: same grid policy with a short epilogue.
Vector tanh: grid-stride loop with 256-thread blocks, large grid.
Packing (Blocked-K): 2D grid over (cols, rows) with 32x8 threads.
Additions in this file:
Fused INT8 activation GEMV (per-tensor parameters).
Fused FP8 activation GEMV (E4M3/E5M2) with on-device decoders.
These settings favor portability and predictability. They are easy to tune per architecture once you profile on target GPUs.
Definition in file ie_kernels_cuda.cu.
Macro Definition Documentation
CUDA_GUARD
#define CUDA_GUARD (call)
Value:
  do {                                                                       \
    cudaError_t _st = (call);                                                \
    if (_st != cudaSuccess) {                                                \
      ie_cuda_set_err(cudaGetErrorString(_st));                              \
      return -(int)_st;                                                      \
    }                                                                        \
  } while (0)
CUDA error guard macro that stores the error string and returns.
Use this after launching kernels to convert CUDA errors into negative integer codes and a readable message retrievable via ie_cuda_last_error_string().
Definition at line 78 of file ie_kernels_cuda.cu.
     {                                                                       \
    cudaError_t _st = (call);                                                \
    if (_st != cudaSuccess) {                                                \
      ie_cuda_set_err(cudaGetErrorString(_st));                              \
      return -(int)_st;                                                      \
    }                                                                        \
  } while (0)
IE_CUDA_OK
#define IE_CUDA_OK 0
Definition at line 28 of file ie_kernels_cuda.cu.
IE_CUDA_STREAM_T_DEFINED
#define IE_CUDA_STREAM_T_DEFINED
Definition at line 31 of file ie_kernels_cuda.cu.
Typedef Documentation
ie_cuda_stream_t
typedef cudaStream_t ie_cuda_stream_t
Definition at line 32 of file ie_kernels_cuda.cu.
Function Documentation
ie_apply_activation()
__device__ float ie_apply_activation (float x, ie_act_kind_t act) inline
Apply a simple activation kind to a scalar.
Parameters
x Input value.
act Activation selector (IE_ACT_NONE, IE_ACT_RELU, IE_ACT_TANH).
Returns
Activated output.
Definition at line 97 of file ie_kernels_cuda.cu.
{
  if (act == IE_ACT_RELU) {
    return x > 0.f ? x : 0.f;
  } else if (act == IE_ACT_TANH) {
    return tanhf(x);
  }
  return x; /* IE_ACT_NONE */
}
References IE_ACT_RELU, and IE_ACT_TANH.
Referenced by k_gemv_bias_act_f32().
ie_cuda_set_err()
static void ie_cuda_set_err (const char * msg) inline static
Set or clear the per-thread CUDA error string buffer.
Parameters
msg NULL to clear; otherwise a short literal/diagnostic string.
Definition at line 51 of file ie_kernels_cuda.cu.
{
  if (!msg) {
    g_ie_cuda_err[0] = '\0';
    return;
  }
  size_t i = 0;
  for (; i + 1 < sizeof(g_ie_cuda_err) && msg[i]; ++i) {
    g_ie_cuda_err[i] = msg[i];
  }
  g_ie_cuda_err[i] = '\0';
}
References g_ie_cuda_err.
Referenced by ie_cuda_launch_gemv_bias_act_f32(), ie_cuda_launch_gemv_rowwise_f32(), ie_cuda_launch_gemv_rowwise_qfp8_f32(), ie_cuda_launch_gemv_rowwise_qi8_f32(), ie_cuda_launch_pack_w_blockedk_f32(), and ie_cuda_launch_vec_tanh_f32().
ie_decode_fp8_e4m3_u8()
__device__ float ie_decode_fp8_e4m3_u8 (uint8_t v) inline
Decode one E4M3 FP8 byte on device (subnormals flushed to zero).
Parameters
v Encoded E4M3 byte.
Returns
Decoded 32-bit float.
Definition at line 113 of file ie_kernels_cuda.cu.
{
  if (v == 0u) return 0.0f;
  const uint8_t sign = (v >> 7) & 0x1;
  const uint8_t exp  = (v >> 3) & 0xF;
  const uint8_t man  = (v & 0x7);
  if (exp == 0) return sign ? -0.0f : 0.0f;
  const int bias = 7;
  const int e    = (int)exp - bias;
  const float frac = (float)man / 8.0f;
  const float val  = (1.0f + frac) * __int2float_rn(1 << e);
  return sign ? -val : val;
}
Referenced by k_gemv_rowwise_qfp8_f32().
ie_decode_fp8_e5m2_u8()
__device__ float ie_decode_fp8_e5m2_u8 (uint8_t v) inline
Decode one E5M2 FP8 byte on device (IEEE-like special cases).
Parameters
v Encoded E5M2 byte.
Returns
Decoded 32-bit float (NaN/Inf propagated).
Definition at line 131 of file ie_kernels_cuda.cu.
{
  const uint8_t sign = (v >> 7) & 0x1;
  const uint8_t exp  = (v >> 2) & 0x1F;
  const uint8_t man  = (v & 0x3);
  if (exp == 0) return sign ? -0.0f : 0.0f;
  if (exp == 0x1F) {
    if (man == 0) return sign ? -CUDART_INF_F : CUDART_INF_F;
    return CUDART_NAN_F;
  }
  const int bias = 15;
  const int e    = (int)exp - bias;
  const float frac = (float)man / 4.0f;
  const float val  = (1.0f + frac) * __int2float_rn(1 << e);
  return sign ? -val : val;
}
Referenced by k_gemv_rowwise_qfp8_f32().
k_gemv_bias_act_f32()
__global__ void k_gemv_bias_act_f32 (const float *__restrict__ W, const float *__restrict__ x, const float *__restrict__ bias, float *__restrict__ y, int rows, int cols, int ldW, float alpha, float beta, ie_act_kind_t act)
Fused GEMV + bias + activation kernel (float activations).
Definition at line 194 of file ie_kernels_cuda.cu.
{
  int r = blockIdx.x;
  if (r >= rows) return;
  float acc = 0.f;
  for (int k = threadIdx.x; k < cols; k += blockDim.x) {
    acc += W[(size_t)r * (size_t)ldW + (size_t)k] * x[k];
  }
  __shared__ float buf[256];
  buf[threadIdx.x] = acc;
  __syncthreads();
  for (int s = blockDim.x >> 1; s > 0; s >>= 1) {
    if (threadIdx.x < s) {
      buf[threadIdx.x] += buf[threadIdx.x + s];
    }
    __syncthreads();
  }
  if (threadIdx.x == 0) {
    float b = bias ? bias[r] : 0.f;
    float out = alpha * buf[0] + b;
    if (beta != 0.f) out += beta * y[r];
    y[r] = ie_apply_activation(out, act);
  }
}
References ie_apply_activation().
k_gemv_rowwise_f32()
__global__ void k_gemv_rowwise_f32 (const float *__restrict__ W, const float *__restrict__ x, float *__restrict__ y, int rows, int cols, int ldW, float alpha, float beta)
Row-wise GEMV kernel: y = alpha * W * x + beta * y.
Mapping: 1 block per row. Threads accumulate a strided reduction over K and reduce via shared memory. Assumes ldW >= cols.
Definition at line 157 of file ie_kernels_cuda.cu.
{
  int r = blockIdx.x;
  if (r >= rows) return;
  float acc = 0.f;
  for (int k = threadIdx.x; k < cols; k += blockDim.x) {
    acc += W[(size_t)r * (size_t)ldW + (size_t)k] * x[k];
  }
  __shared__ float buf[256];
  buf[threadIdx.x] = acc;
  __syncthreads();
  for (int s = blockDim.x >> 1; s > 0; s >>= 1) {
    if (threadIdx.x < s) {
      buf[threadIdx.x] += buf[threadIdx.x + s];
    }
    __syncthreads();
  }
  if (threadIdx.x == 0) {
    float out = alpha * buf[0];
    if (beta != 0.f) out += beta * y[r];
    y[r] = out;
  }
}
Referenced by update_performance_md::_agg(), update_performance_md::_agg_numeric(), update_performance_md::_agg_sum(), dedup_prepare_and_extract_all::_as_list_tensors(), build_dedup_source_from_manifest::_bf16_to_f32(), dedup_extract_int4::_bitset_popcount(), build_dedup_source_from_manifest::_build_dedup_source(), dedup_prepare_and_extract_all::_build_name_to_index(), update_performance_md::_bytes_touched(), dedup_extract_int4::_diff_default_target(), update_performance_md::_discover_cpu_model(), build_dedup_source_from_manifest::_discover_expert_count(), update_performance_md::_discover_git(), update_performance_md::_discover_kernel(), update_performance_md::_discover_mem_total_gb(), update_performance_md::_discover_os(), dedup_prepare_and_extract_all::_dtype_size(), build_dedup_source_from_manifest::_encode_scales_fp16(), build_dedup_source_from_manifest::_encode_scales_log2_u8_q3(), update_performance_md::_filesize(), metrics_exporter::_find_latest_json(), update_performance_md::_find_model_bin(), update_performance_md::_fmt_float(), metrics_exporter::_gauge_line(), build_dedup_source_from_manifest::_infer_expert_weight_names(), gen_q4_bytes_stream::_iter_shards(), metrics_exporter::_label_str(), build_dedup_source_from_manifest::_load_json(), dedup_extract_int4::_load_json(), dedup_prepare_and_extract_all::_load_json(), dedup_verify_int4::_load_json(), metrics_exporter::_load_one_json_file(), gen_q4_bytes_stream::_load_state_dict(), dedup_prepare_and_extract_all::_make_virtual_slices(), build_dedup_source_from_manifest::_manifest_required_tensors(), update_performance_md::_max_or_none(), update_performance_md::_mean(), update_performance_md::_merge_shared(), update_performance_md::_min_or_none(), update_performance_md::_now_utc_str(), gen_q4_bytes_stream::_pack_int4_from_int8(), build_dedup_source_from_manifest::_pack_int4_nibbles(), update_performance_md::_parse(), build_dedup_source_from_manifest::_parse_ie(), dedup_extract_int4::_parse_tensor_map(), dedup_verify_int4::_parse_tensor_map(), update_performance_md::_partition_runs_and_summary(), dedup_prepare_and_extract_all::_prepare_groups_and_tensor_map(), build_dedup_source_from_manifest::_quant_int4_groupwise(), dedup_verify_int4::_read_all(), update_performance_md::_read_json_lines(), dedup_extract_int4::_read_slice(), dedup_verify_int4::_read_slice(), build_dedup_source_from_manifest::_read_tensor_bytes(), build_dedup_source_from_manifest::_read_weight_matrix_f32(), dedup_verify_int4::_reconstruct(), update_performance_md::_render_memory_details(), update_performance_md::_render_system(), update_performance_md::_render_table(), build_dedup_source_from_manifest::_save_json(), dedup_prepare_and_extract_all::_save_json(), update_performance_md::_sum_f(), update_performance_md::_sum_i(), dedup_extract_int4::_write_json(), advise_sequential(), all_in_sym_int8_range(), all_marked_once(), alloc_replica_first_touch(), apply_cpulist_to_node(), bad_float3(), blobs_free(), blobs_push(), block_is_nonzero(), build_block_sparse_4x4(), build_dense_4x4(), build_groups_auto(), ceil_div_sz(), cfg_bytes(), cfg_stride(), checksum_bytes(), clamp_q4(), clamp_sym_int8(), cli_extras_defaults(), metrics_exporter::collect_metrics_from_summary(), compute_first_cpu_per_socket(), dalloc(), dbg(), dense_to_block_sparse(), dfree(), die(), discover_nodes_sysfs(), discover_sockets_sysfs(), metrics_exporter.Handler::do_GET(), dump_topology(), dump_vec(), ensure_module_ready(), env_flag(), exercise_advice_and_walk(), ptq_from_source::export_onnx(), ptq_from_source::export_torch(), extract_one(), feq(), file_exists(), fill_matrix(), fill_range(), fill_vector(), ptq_from_hf::find_checkpoint(), fp16_to_fp32(), free_replicas_internal(), fwrite_all(), get_online_cpus(), group_add_member(), groups_free(), groups_push(), hash_bytes(), hash_view(), validate_ie_json::human_bytes(), ie_act_i8_group_params_from_data(), ie_act_i8_params_from_minmax(), ie_bitset_get(), ie_block_sparse_density(), ie_block_sparse_init(), ie_block_sparse_load(), ie_block_sparse_release(), ie_clamp01(), ie_cuda_launch_gemv_bias_act_f32(), ie_cuda_launch_gemv_rowwise_f32(), ie_cuda_launch_gemv_rowwise_qfp8_f32(), ie_cuda_launch_gemv_rowwise_qi8_f32(), ie_cuda_launch_pack_w_blockedk_f32(), ie_cuda_launch_vec_tanh_f32(), ie_dequantize_act_fp8(), ie_dequantize_act_int8(), ie_dequantize_act_int8_per_group(), ie_detect_caches_linux(), ie_dtype_elem_size(), ie_fabsf(), ie_find_file_index(), ie_find_tensor(), ie_hot_replica_for_socket(), ie_hot_replica_memcpy(), ie_hot_replicas_free(), ie_hot_replicate_build(), ie_hot_replicate_build_fill(), ie_iejson_tensor_free(), ie_int4_absmax(), ie_int4_absmax_per_row(), ie_int4_dequantize_per_row(), ie_int4_dequantize_per_tensor(), ie_int4_error_metrics(), ie_int4_get_nibble(), ie_int4_quantize_per_row(), ie_int4_quantize_per_tensor(), ie_int4_set_nibble(), ie_kv_element_size(), ie_kv_free(), ie_kv_hit_add_local(), ie_kv_init(), ie_kv_load_token_f32(), ie_kv_miss_add_local(), ie_kv_raw_ptrs(), ie_kv_store_token_f32(), ie_kv_store_token_fp8(), ie_kv_store_token_int8_per_group(), ie_kv_store_token_int8_per_tensor(), ie_layout_build_blockedK(), ie_layout_free(), ie_log_debug(), ie_log_info(), ie_log_set_level(), ie_maxf(), ie_metrics_add_kv(), ie_metrics_add_kv_hit(), ie_metrics_add_kv_miss(), ie_metrics_reset(), ie_metrics_sample_rss_peak(), ie_metrics_snapshot(), ie_minf(), ie_nt_copy_f32_avx2(), ie_nt_copy_f32_avx512(), ie_nt_set_f32_avx2(), ie_nt_set_f32_avx512(), ie_numa_policy_replica_count(), ie_numa_policy_should_replicate_hot(), ie_pack_fp8_e4m3(), ie_pack_fp8_e5m2(), ie_parse_files_object(), ie_parse_iejson_one_tensor(), ie_parse_iejson_tensors(), ie_parse_one_tensor(), ie_parse_tensors_array(), ie_ptq_compute_scales_minmax(), ie_ptq_dequant_int8(), ie_ptq_quantize_int8(), ie_quantize_act_fp8(), ie_quantize_act_int8(), ie_quantize_act_int8_per_group(), ie_read_cache_size_file(), ie_rne(), ie_sat_i8(), ie_sat_sym_i8(), ie_scalar_copy_f32(), ie_scalar_set_f32(), ie_set_affinity(), ie_shape_elem_count(), ie_sparse_status_str(), ie_stream_copy_f32(), ie_stream_memset_f32(), ie_stream_policy_init(), ie_stream_prefetch_nta(), ie_stream_prefetch_range_nta(), ie_stream_prefetch_range_t0(), ie_stream_prefetch_t0(), ie_stream_recommend_prefetch_distance(), ie_stream_should_use_nt(), ie_task_main(), ie_tensor_cmp_name(), ie_topology_bind_thread_to_socket(), ie_topology_cpu_to_node(), ie_topology_cpu_to_socket(), ie_topology_cpus(), ie_topology_destroy(), ie_topology_first_cpu_on_socket(), ie_topology_init(), ie_topology_nodes(), ie_topology_sockets(), ie_tp_create(), ie_tp_destroy(), ie_tp_parallel_for(), ie_u32_from_f(), ie_unpack_fp8_e4m3(), ie_unpack_fp8_e5m2(), ie_weights_close(), ie_weights_decode_int4(), ie_weights_dedup_close(), ie_weights_dedup_get_weight_view(), ie_weights_dedup_materialize(), ie_weights_dedup_open(), ie_weights_read_int4_meta(), ie_weights_touch(), ie_worker_main(), ie_ze_launch_gemv_bias_act_f32(), ie_ze_launch_gemv_rowwise_f32(), ie_ze_launch_pack_w_blockedk_f32(), ie_ze_launch_vec_tanh_f32(), join_path(), js_parse_blobref(), js_parse_shape(), js_read_str_member(), js_read_u64_member(), json_find_string(), json_find_u64(), kib_to_mib_ceil(), kind_from_string(), kv_validate_and_derive(), load_dense_matrix(), hf_to_iebin_stream::load_index(), load_manifest(), ptq_from_hf::load_state_dict(), convert_safetensors_to_pt_bin::main(), export_tensors_onnx::main(), export_tensors_torch::main(), gen_q4_bytes_stream::main(), gen_q4_bytes_worker::main(), hf_to_iebin::main(), hf_to_iebin_raw::main(), hf_to_iebin_stream::main(), hf_to_iebin_stream_pt::main(), make_baseline_md::main(), metrics_exporter::main(), ptq_from_bin::main(), ptq_from_hf::main(), ptq_from_source::main(), q4_pack_stream::main(), split_q4_manifest_to_files::main(), update_performance_md::main(), build_dedup_source_from_manifest::main(), dedup_extract_int4::main(), dedup_prepare_and_extract_all::main(), dedup_verify_int4::main(), validate_ie_json::main(), main(), main(), make_temp_file(), mark_task(), mask_set(), memcpy_imm(), mse(), mse(), make_baseline_md::newest_report_dir(), normalize_name(), hf_to_iebin_stream::np_ensure_contig(), open_and_touch(), open_rb(), gen_q4_bytes_worker::pack_int4_rows(), pack_q4_pair(), q4_pack_stream::pack_row_int4_sym(), param_index(), gen_q4_bytes_stream::parse_args(), parse_args(), parse_cli(), parse_flags(), parse_status_kb_line(), path_join(), payload_index(), pread_exact(), print_json_result(), validate_ie_json::prod(), q4_pack_stream::quantize_2d_per_row(), read_file_all(), read_first_nonempty_line(), read_fully(), read_int_file(), hf_to_iebin_stream::read_json(), test_ptq_calib_pipeline::read_json(), read_proc_kb_single(), hf_to_iebin_raw::read_safetensors_header(), make_baseline_md::read_samples(), make_baseline_md::read_summary(), ref_gemv_bias(), ref_gemv_nominal(), resolve_model_paths(), test_cli_flags.CLIFeatureFlagsTests::run_cli(), test_ptq_calib_pipeline.PTQCalibPipelineTests::run_ptq(), q4_pack_stream::safe(), safe_atoi(), split_q4_manifest_to_files::safe_name(), save_cache_atomic(), set_arg(), hf_to_iebin::sizeof_dtype(), hf_to_iebin_stream_pt::tensor_dtype_tag(), hf_to_iebin_stream_pt::tensor_to_bytes(), ptq_from_hf::tensor_to_fp32_bin(), test_basic_prefetch_and_order(), test_block_sparse_gemv_basic(), test_block_sparse_helpers(), test_block_sparse_init_release(), test_block_sparse_load_missing(), test_cli.CLITests::test_cli_runs_and_emits_json(), test_cpu_caps(), test_harness_more.HarnessMoreTests::test_custom_samples_and_promptlen(), test_fp8_sweep(), test_gemv_rowmajor_no_bias(), test_gemv_rowmajor_with_bias(), test_gpu_fallback(), test_harness.HarnessTests::test_harness_generates_reports(), test_int8_per_group(), test_int8_per_tensor(), test_cli_error_paths.CLIErrorPathsTests::test_invalid_flag_is_rejected(), test_kind_parse(), test_metrics_ring.MetricsRingTests::test_p50_p95_present_and_consistent(), test_partial_teardown(), test_per_row_independent_scales(), test_ptq_calib_pipeline.PTQCalibPipelineTests::test_per_row_pipeline(), test_ptq_calib_pipeline.PTQCalibPipelineTests::test_per_tensor_pipeline(), test_per_tensor_roundtrip(), test_determinism.DeterminismTests::test_same_prompt_same_output_short_run(), test_saturation_symmetric(), test_tokenize_cb(), test_wrap_and_view_limits(), test_cli_error_paths.CLIErrorPathsTests::test_zero_tokens_graceful(), u64_ceil_div(), unpack_q4_pair(), usage(), usage(), vec_allclose(), verify_pattern(), gen_q4_bytes_stream::wanted(), gen_q4_bytes_worker::wanted(), q4_pack_stream::wanted(), write_block_sparse_file(), and test_ptq_calib_pipeline::write_f32_bin().
k_gemv_rowwise_qfp8_f32()
__global__ void k_gemv_rowwise_qfp8_f32 (const float *__restrict__ W, const uint8_t *__restrict__ x8, float *__restrict__ y, int rows, int cols, int ldW, ie_fp8_format fmt, float alpha, float beta)
Row-wise GEMV with FP8 activations (E4M3/E5M2), fused decode.
Definition at line 276 of file ie_kernels_cuda.cu.
{
  int r = blockIdx.x;
  if (r >= rows) return;
  const bool e4m3 = (fmt == IE_FP8_E4M3);
  float acc = 0.f;
  for (int k = threadIdx.x; k < cols; k += blockDim.x) {
    const uint8_t b = x8[k];
    const float xv =
        e4m3 ? ie_decode_fp8_e4m3_u8(b) : ie_decode_fp8_e5m2_u8(b);
    acc += W[(size_t)r * (size_t)ldW + (size_t)k] * xv;
  }
  __shared__ float buf[256];
  buf[threadIdx.x] = acc;
  __syncthreads();
  for (int s = blockDim.x >> 1; s > 0; s >>= 1) {
    if (threadIdx.x < s) {
      buf[threadIdx.x] += buf[threadIdx.x + s];
    }
    __syncthreads();
  }
  if (threadIdx.x == 0) {
    float out = alpha * buf[0];
    if (beta != 0.f) out += beta * y[r];
    y[r] = out;
  }
}
References ie_decode_fp8_e4m3_u8(), ie_decode_fp8_e5m2_u8(), and IE_FP8_E4M3.
k_gemv_rowwise_qi8_f32()
__global__ void k_gemv_rowwise_qi8_f32 (const float *__restrict__ W, const int8_t *__restrict__ xq, float *__restrict__ y, int rows, int cols, int ldW, float scale, int zp, float alpha, float beta)
Row-wise GEMV with INT8 activations (per-tensor), fused dequantization.
Dequantization model: real = scale * (q - zero_point).
Definition at line 236 of file ie_kernels_cuda.cu.
{
  int r = blockIdx.x;
  if (r >= rows) return;
  float acc = 0.f;
  for (int k = threadIdx.x; k < cols; k += blockDim.x) {
    const float xv = scale * ((int)xq[k] - zp);
    acc += W[(size_t)r * (size_t)ldW + (size_t)k] * xv;
  }
  __shared__ float buf[256];
  buf[threadIdx.x] = acc;
  __syncthreads();
  for (int s = blockDim.x >> 1; s > 0; s >>= 1) {
    if (threadIdx.x < s) {
      buf[threadIdx.x] += buf[threadIdx.x + s];
    }
    __syncthreads();
  }
  if (threadIdx.x == 0) {
    float out = alpha * buf[0];
    if (beta != 0.f) out += beta * y[r];
    y[r] = out;
  }
}
k_pack_w_blockedk_f32()
__global__ void k_pack_w_blockedk_f32 (float *__restrict__ Wp, const float *__restrict__ W, int rows, int cols, int ldW, int block_k)
Pack row-major W into Blocked-K layout on device.
Layout: kb = k / block_k; // tile index along K ko = k % block_k; // in-tile offset dst = ((kb * rows + r) * block_k + ko) Wp[dst] = W[r * ldW + k]
Definition at line 338 of file ie_kernels_cuda.cu.
{
  int r0 = blockIdx.y * blockDim.y + threadIdx.y;
  int k0 = blockIdx.x * blockDim.x + threadIdx.x;
  for (int r = r0; r < rows; r += blockDim.y * gridDim.y) {
    for (int k = k0; k < cols; k += blockDim.x * gridDim.x) {
      int kb = k / block_k;
      int ko = k % block_k;
      size_t dst = ((size_t)kb * (size_t)rows + (size_t)r) * (size_t)block_k +
                   (size_t)ko;
      Wp[dst] = W[(size_t)r * (size_t)ldW + (size_t)k];
    }
  }
}
k_vec_tanh_f32()
__global__ void k_vec_tanh_f32 (float *__restrict__ y, const float *__restrict__ x, int n)
Elementwise hyperbolic tangent on a vector.
Definition at line 319 of file ie_kernels_cuda.cu.
{
  for (int i = blockIdx.x * blockDim.x + threadIdx.x;
       i < n;
       i += blockDim.x * gridDim.x) {
    y[i] = tanhf(x[i]);
  }
}
Variable Documentation
g_ie_cuda_err
__thread char g_ie_cuda_err[256] = {0} static
Definition at line 45 of file ie_kernels_cuda.cu.
{0};
Referenced by ie_cuda_last_error_string(), and ie_cuda_set_err().