Inference Engine (Clocher): engine/include/ie_math.h File Reference
ie_math.h File Reference
Math utilities for activation functions and vector helpers.
#include <stddef.h>
Functions
float ie_fast_tanhf (float x)
Fast approximation of hyperbolic tanh with strict [-1, 1] range.
void ie_vec_tanh_f32 (float *v, size_t n, int fast_tanh)
In-place vector tanh on a contiguous array (legacy API).
void ie_vec_tanh_f32_out (const float *x, float *out, size_t n)
Out-of-place vector tanh on a contiguous array.
void ie_vec_tanh_f32_strided (const float *x, size_t x_stride, float *out, size_t out_stride, size_t n)
Out-of-place vector tanh on strided arrays.
Detailed Description
Math utilities for activation functions and vector helpers.
Definition in file ie_math.h.
Function Documentation
ie_fast_tanhf()
float ie_fast_tanhf (float x)
Fast approximation of hyperbolic tanh with strict [-1, 1] range.
Parameters
x Input value.
Returns
Approximated tanh(x) in [-1.0f, 1.0f].
Fast approximation of hyperbolic tanh with strict [-1, 1] range.
Fast scalar tanh approximation.
For large |x| we short-circuit to +/-1.0f. For moderate |x| we use a small rational function that gives a smooth S-curve:
tanh(x) ≈ x * (27 + x^2) / (27 + 9 x^2)
Finally, the result is clamped to [-1, 1] to guarantee range correctness.
Parameters
x Input value.
Returns
Approximated tanh(x) in [-1.0f, 1.0f].
Definition at line 28 of file fast_tanh.c.
{
  /* Early clamp for large magnitude to avoid overflow and extra work. */
  if (x > 5.0f)  return 1.0f;
  if (x < -5.0f) return -1.0f;
  /* Rational approximation (cheap and monotonic on [-3,3]) */
  const float x2  = x * x;
  const float num = x * (27.0f + x2);
  const float den = 27.0f + 9.0f * x2;
  float y = num / den;
  /* Safety clamp for strict range compliance. */
  if (y > 1.0f)  y = 1.0f;
  if (y < -1.0f) y = -1.0f;
  return y;
}
Referenced by ie_vec_tanh_f32(), ie_vec_tanh_f32_out(), and ie_vec_tanh_f32_strided().
ie_vec_tanh_f32()
void ie_vec_tanh_f32 (float * v, size_t n, int fast_tanh)
In-place vector tanh on a contiguous array (legacy API).
When fast_tanh != 0, uses ie_fast_tanhf; otherwise uses the standard library tanhf for higher accuracy.
Parameters
v Pointer to the vector (length n). Modified in-place.
n Number of elements in v.
fast_tanh Non-zero to use the fast approximation; 0 to use libm.
Vector tanh on fp32 data (in-place).
If fast_tanh != 0, uses ie_fast_tanhf; otherwise uses libm tanhf. Output values are clamped to [-1, 1] in both modes to satisfy strict bounds.
Parameters
v Pointer to the vector (length n). Modified in-place.
n Number of elements in v.
fast_tanh Non-zero to use the fast approximation; 0 to use libm.
Definition at line 55 of file fast_tanh.c.
{
  if (!v || n == 0) return;
  if (fast_tanh) {
    for (size_t i = 0; i < n; ++i) {
      v[i] = ie_fast_tanhf(v[i]);
    }
  } else {
    for (size_t i = 0; i < n; ++i) {
      float y = tanhf(v[i]);
      if (y > 1.0f)  y = 1.0f;
      if (y < -1.0f) y = -1.0f;
      v[i] = y;
    }
  }
}
ie_vec_tanh_f32_out()
void ie_vec_tanh_f32_out (const float * x, float * out, size_t n)
Out-of-place vector tanh on a contiguous array.
Always uses the fast approximation (ie_fast_tanhf). Output is strictly clamped to [-1, 1].
Parameters
x Pointer to input array (length n).
out Pointer to output array (length n).
n Number of elements.
Out-of-place vector tanh on a contiguous array.
Parameters
x Pointer to input array (length n).
out Pointer to output array (length n).
n Number of elements.
Definition at line 78 of file fast_tanh.c.
{
  if (!x || !out || n == 0) return;
  for (size_t i = 0; i < n; ++i) {
    out[i] = ie_fast_tanhf(x[i]);
  }
}
References ie_fast_tanhf().
ie_vec_tanh_f32_strided()
void ie_vec_tanh_f32_strided (const float * x, size_t x_stride, float * out, size_t out_stride, size_t n)
Out-of-place vector tanh on strided arrays.
Computes for i in [0, n): out[i*out_stride] = tanh(x[i*x_stride]). Always uses the fast approximation with strict clamping.
Parameters
x Pointer to input array.
x_stride Stride (in elements) between consecutive inputs.
out Pointer to output array.
out_stride Stride (in elements) between consecutive outputs.
n Number of elements to process.
Out-of-place vector tanh on strided arrays.
Computes for i in [0, n): out[i*out_stride] = tanh(x[i*x_stride]).
Parameters
x Pointer to input array.
x_stride Stride (in elements) between consecutive inputs.
out Pointer to output array.
out_stride Stride (in elements) between consecutive outputs.
n Number of elements to process.
Definition at line 96 of file fast_tanh.c.
{
  if (!x || !out || n == 0) return;
  for (size_t i = 0; i < n; ++i) {
    out[i * out_stride] = ie_fast_tanhf(x[i * x_stride]);
  }
}
References ie_fast_tanhf().