Inference Engine (Clocher): engine/include/ie_topology.h File Reference
ie_topology.h File Reference
#include <stddef.h>
#include <stdint.h>
Typedefs
typedef struct ie_topology ie_topology_t
Opaque handle for discovered CPU topology.
Functions
int ie_topology_init (ie_topology_t **topo)
Initialize and build a topology handle.
void ie_topology_destroy (ie_topology_t *topo)
Free a previously created topology handle.
int ie_topology_cpus (const ie_topology_t *topo)
Return the number of online CPUs observed during discovery.
int ie_topology_sockets (const ie_topology_t *topo)
Return the number of sockets (physical packages).
int ie_topology_nodes (const ie_topology_t *topo)
Return the number of NUMA nodes discovered.
int ie_topology_cpu_to_socket (const ie_topology_t *topo, int cpu)
Map a CPU id to its socket id.
int ie_topology_cpu_to_node (const ie_topology_t *topo, int cpu)
Map a CPU id to its NUMA node id.
int ie_topology_first_cpu_on_socket (const ie_topology_t *topo, int socket)
Return a representative CPU id that belongs to the given socket.
int ie_topology_bind_thread_to_socket (const ie_topology_t *topo, int socket)
Bind the current thread/process to a representative CPU of a socket.
Typedef Documentation
ie_topology_t
typedef struct ie_topology ie_topology_t
Opaque handle for discovered CPU topology.
Definition at line 1 of file ie_topology.h.
Function Documentation
ie_topology_bind_thread_to_socket()
int ie_topology_bind_thread_to_socket (const ie_topology_t * topo, int socket)
Bind the current thread/process to a representative CPU of a socket.
This is a thin helper: it picks ie_topology_first_cpu_on_socket(topo, socket) and calls sched_setaffinity() for the current thread/process.
Parameters
topo Topology handle (non-NULL).
socket Socket id (0 .. ie_topology_sockets()-1).
Returns
0 on success; negative errno-like value on failure.
Picks ie_topology_first_cpu_on_socket() and applies sched_setaffinity().
Parameters
topo Handle (non-NULL).
socket Socket id (0..n_sockets-1).
Returns
0 on success; negative errno-like on failure.
Definition at line 338 of file topology.c.
{
   if (!topo) return -EINVAL;
   if (socket < 0 || socket >= topo->n_sockets) return -EINVAL;
   int cpu = ie_topology_first_cpu_on_socket(topo, socket);
   if (cpu < 0) return -EINVAL;
   cpu_set_t set;
   CPU_ZERO(&set);
   CPU_SET((unsigned)cpu, &set);
   if (sched_setaffinity(0, sizeof(set), &set) != 0) {
     return -errno ? -errno : -1;
   }
   return 0;
 }
References ie_topology_first_cpu_on_socket(), and ie_topology::n_sockets.
Referenced by ie_hot_replicate_build(), and ie_hot_replicate_build_fill().
ie_topology_cpu_to_node()
int ie_topology_cpu_to_node (const ie_topology_t * topo, int cpu)
Map a CPU id to its NUMA node id.
If the CPU id is out of range, returns -1.
Parameters
topo Topology handle (non-NULL).
cpu Zero-based CPU id.
Returns
NUMA node id (>= 0), or -1 if invalid.
Map a CPU id to its NUMA node id.
Parameters
topo Handle (non-NULL).
cpu Zero-based CPU id.
Returns
Node id (>=0) or -1 if invalid.
Definition at line 313 of file topology.c.
{
   if (!topo || cpu < 0 || cpu >= topo->n_cpus) return -1;
   return topo->cpu_to_node[cpu];
 }
References ie_topology::cpu_to_node, and ie_topology::n_cpus.
Referenced by dump_topology().
ie_topology_cpu_to_socket()
int ie_topology_cpu_to_socket (const ie_topology_t * topo, int cpu)
Map a CPU id to its socket id.
If the CPU id is out of range, returns -1.
Parameters
topo Topology handle (non-NULL).
cpu Zero-based CPU id.
Returns
Socket id (>= 0), or -1 if invalid.
Map a CPU id to its socket id.
Parameters
topo Handle (non-NULL).
cpu Zero-based CPU id.
Returns
Socket id (>=0) or -1 if invalid.
Definition at line 302 of file topology.c.
{
   if (!topo || cpu < 0 || cpu >= topo->n_cpus) return -1;
   return topo->cpu_to_socket[cpu];
 }
References ie_topology::cpu_to_socket, and ie_topology::n_cpus.
Referenced by dump_topology().
ie_topology_cpus()
int ie_topology_cpus (const ie_topology_t * topo)
Return the number of online CPUs observed during discovery.
Parameters
topo Topology handle (non-NULL).
Returns
Number of CPUs (>= 1).
Return the number of online CPUs observed during discovery.
Parameters
topo Handle (non-NULL).
Returns
CPU count (>=1).
Definition at line 274 of file topology.c.
{
   return topo ? topo->n_cpus : 0;
 }
References ie_topology::n_cpus.
Referenced by dump_topology(), and main().
ie_topology_destroy()
void ie_topology_destroy (ie_topology_t * topo)
Free a previously created topology handle.
It is safe to pass NULL; no action will be taken.
Parameters
topo Topology handle returned by ie_topology_init.
Free a previously created topology handle.
Parameters
topo Topology handle (nullable).
Definition at line 261 of file topology.c.
{
   if (!topo) return;
   free(topo->cpu_to_socket);
   free(topo->cpu_to_node);
   free(topo->first_cpu_socket);
   free(topo);
 }
References ie_topology::cpu_to_node, ie_topology::cpu_to_socket, and ie_topology::first_cpu_socket.
Referenced by main().
ie_topology_first_cpu_on_socket()
int ie_topology_first_cpu_on_socket (const ie_topology_t * topo, int socket)
Return a representative CPU id that belongs to the given socket.
This is typically the smallest CPU id observed in that socket during discovery. Useful for pinning one thread per socket.
Parameters
topo Topology handle (non-NULL).
socket Socket id (0 .. ie_topology_sockets()-1).
Returns
CPU id (>= 0) on success; -1 if socket is invalid or empty.
Return a representative CPU id that belongs to the given socket.
Parameters
topo Handle (non-NULL).
socket Socket id.
Returns
CPU id (>=0) or -1 on invalid socket.
Definition at line 324 of file topology.c.
{
   if (!topo || socket < 0 || socket >= topo->n_sockets) return -1;
   return topo->first_cpu_socket[socket];
 }
References ie_topology::first_cpu_socket, and ie_topology::n_sockets.
Referenced by dump_topology(), and ie_topology_bind_thread_to_socket().
ie_topology_init()
int ie_topology_init (ie_topology_t ** topo)
Initialize and build a topology handle.
This probes the host to discover:
total online CPUs
socket id for each CPU
NUMA node id for each CPU A best-effort approach is used; missing information is replaced by a consistent single-socket, single-node fallback.
Parameters
[out] topo Output pointer to receive a newly allocated handle (non-NULL).
Returns
0 on success; negative errno-like value on failure (e.g., -12 for OOM).
Definition at line 205 of file topology.c.
{
   if (!out_topo) return -EINVAL;
   int n_cpus = get_online_cpus();
   ie_topology_t *t = (ie_topology_t *)calloc(1, sizeof(*t));
   if (!t) return -ENOMEM;
   t->n_cpus = n_cpus;
   t->cpu_to_socket = (int *)malloc(sizeof(int) * n_cpus);
   t->cpu_to_node   = (int *)malloc(sizeof(int) * n_cpus);
   if (!t->cpu_to_socket || !t->cpu_to_node) {
     free(t->cpu_to_socket);
     free(t->cpu_to_node);
     free(t);
     return -ENOMEM;
   }
   for (int i = 0; i < n_cpus; ++i) {
     t->cpu_to_socket[i] = -1;
     t->cpu_to_node[i] = -1;
   }
   /* Best-effort discovery */
   int sockets = discover_sockets_sysfs(n_cpus, t->cpu_to_socket);
   int nodes   = discover_nodes_sysfs(n_cpus, t->cpu_to_node);
   if (sockets <= 0) {
     sockets = 1;
     for (int i = 0; i < n_cpus; ++i) t->cpu_to_socket[i] = 0;
   }
   if (nodes <= 0) {
     nodes = 1;
     for (int i = 0; i < n_cpus; ++i) t->cpu_to_node[i] = 0;
   }
   t->n_sockets = sockets;
   t->n_nodes   = nodes;
   t->first_cpu_socket = (int *)malloc(sizeof(int) * sockets);
   if (!t->first_cpu_socket) {
     free(t->cpu_to_socket);
     free(t->cpu_to_node);
     free(t);
     return -ENOMEM;
   }
   compute_first_cpu_per_socket(n_cpus, sockets, t->cpu_to_socket, t->first_cpu_socket);
   *out_topo = t;
   return 0;
 }
References compute_first_cpu_per_socket(), ie_topology::cpu_to_node, ie_topology::cpu_to_socket, discover_nodes_sysfs(), discover_sockets_sysfs(), ie_topology::first_cpu_socket, get_online_cpus(), ie_topology::n_cpus, ie_topology::n_nodes, and ie_topology::n_sockets.
Referenced by main().
ie_topology_nodes()
int ie_topology_nodes (const ie_topology_t * topo)
Return the number of NUMA nodes discovered.
Parameters
topo Topology handle (non-NULL).
Returns
Number of NUMA nodes (>= 1).
Return the number of NUMA nodes discovered.
Parameters
topo Handle (non-NULL).
Returns
Node count (>=1).
Definition at line 292 of file topology.c.
{
   return topo ? topo->n_nodes : 0;
 }
References ie_topology::n_nodes.
Referenced by dump_topology(), and main().
ie_topology_sockets()
int ie_topology_sockets (const ie_topology_t * topo)
Return the number of sockets (physical packages).
Parameters
topo Topology handle (non-NULL).
Returns
Number of sockets (>= 1).
Return the number of sockets (physical packages).
Parameters
topo Handle (non-NULL).
Returns
Socket count (>=1).
Definition at line 283 of file topology.c.
{
   return topo ? topo->n_sockets : 0;
 }
References ie_topology::n_sockets.
Referenced by dump_topology(), ie_hot_replicate_build(), ie_hot_replicate_build_fill(), ie_numa_policy_init(), and main().