Inference Engine (Clocher): engine/include/ie_quant.h File Reference
ie_quant.h File Reference
Post-Training Quantization (PTQ) helpers for INT8 weight-only paths.
#include <stddef.h>
#include <stdint.h>
Typedefs
typedef enum ie_ptq_scale_mode_e ie_ptq_scale_mode_t
Enumerations
enum ie_ptq_scale_mode_e { IE_PTQ_SCALE_PER_TENSOR = 0 , IE_PTQ_SCALE_PER_ROW = 1 }
Functions
void ie_ptq_compute_scales_minmax (const float *w, size_t rows, size_t cols, ie_ptq_scale_mode_t mode, float *scales)
Compute INT8 scales using a symmetric min-max rule.
void ie_ptq_quantize_int8 (const float *w, size_t rows, size_t cols, ie_ptq_scale_mode_t mode, const float *scales, int8_t *q8)
Quantize FP32 weights to INT8 using precomputed scales.
void ie_ptq_dequant_int8 (const int8_t *q8, size_t rows, size_t cols, ie_ptq_scale_mode_t mode, const float *scales, float *w_out)
Dequantize INT8 weights back to FP32 using provided scales.
Detailed Description
Post-Training Quantization (PTQ) helpers for INT8 weight-only paths.
This header declares utilities to compute scaling factors and to (de)quantize FP32 weight tensors into INT8 using simple, reproducible rules. The API is dependency-free and backend-agnostic so it can be used from CPU and GPU code paths.
Definition in file ie_quant.h.
Typedef Documentation
ie_ptq_scale_mode_t
typedef enum ie_ptq_scale_mode_e ie_ptq_scale_mode_t
Enumeration Type Documentation
ie_ptq_scale_mode_e
enum ie_ptq_scale_mode_e
Enumerator
IE_PTQ_SCALE_PER_TENSOR
Single scale for the entire tensor.
IE_PTQ_SCALE_PER_ROW
One scale per row (for row-major 2D matrices).
Definition at line 25 of file ie_quant.h.
{
   IE_PTQ_SCALE_PER_TENSOR = 0,
   IE_PTQ_SCALE_PER_ROW    = 1
 } ie_ptq_scale_mode_t;
Function Documentation
ie_ptq_compute_scales_minmax()
void ie_ptq_compute_scales_minmax (const float * w, size_t rows, size_t cols, ie_ptq_scale_mode_t mode, float * scales)
Compute INT8 scales using a symmetric min-max rule.
For each scale domain D (tensor or row), we compute: scale(D) = max(abs(min(D)), abs(max(D))) / 127.0f If D is all zeros, the scale is set to 1.0f to avoid division by zero.
Parameters
[in] w Pointer to FP32 weights in row-major layout.
[in] rows Number of rows (use 1 for a flat vector).
[in] cols Number of columns (use N for a flat vector).
[in] mode Scale granularity to use.
[out] scales Output buffer for scales:
length 1 if mode == IE_PTQ_SCALE_PER_TENSOR
length rows if mode == IE_PTQ_SCALE_PER_ROW
Compute INT8 scales using a symmetric min-max rule.
For each scaling domain D (the entire tensor when IE_PTQ_SCALE_PER_TENSOR, or each row when IE_PTQ_SCALE_PER_ROW), this routine computes:
If , the scale falls back to 1.0 to avoid division by zero during quantization.
Parameters
[in] w Pointer to FP32 weights (row-major), length = rows*cols.
[in] rows Number of rows (use 1 for flat vectors).
[in] cols Number of columns (use N for flat vectors).
[in] mode Scale granularity (tensor- or row-wise).
[out] scales Output buffer for scales:
length 1 when mode == IE_PTQ_SCALE_PER_TENSOR
length rows when mode == IE_PTQ_SCALE_PER_ROW
Note
Inputs are not validated beyond null/zero checks for performance. Callers must ensure the buffers are correctly sized.
Definition at line 57 of file int8_ptq.c.
{
   if (!w || !scales || rows == 0 || cols == 0) return;
   if (mode == IE_PTQ_SCALE_PER_TENSOR) {
     float lo = FLT_MAX, hi = -FLT_MAX;
     const size_t n = rows * cols;
     for (size_t i = 0; i < n; ++i) {
       const float v = w[i];
       if (v < lo) lo = v;
       if (v > hi) hi = v;
     }
     const float amax = fmaxf(fabsf(lo), fabsf(hi));
     scales[0] = (amax > 0.0f) ? (amax / 127.0f) : 1.0f;
     return;
   }
   /* Per-row scaling. */
   for (size_t r = 0; r < rows; ++r) {
     float lo = FLT_MAX, hi = -FLT_MAX;
     const float *row = w + r * cols;
     for (size_t c = 0; c < cols; ++c) {
       const float v = row[c];
       if (v < lo) lo = v;
       if (v > hi) hi = v;
     }
     const float amax = fmaxf(fabsf(lo), fabsf(hi));
     scales[r] = (amax > 0.0f) ? (amax / 127.0f) : 1.0f;
   }
 }
References IE_PTQ_SCALE_PER_TENSOR.
Referenced by test_per_row_independent_scales(), and test_per_tensor_roundtrip().
ie_ptq_dequant_int8()
void ie_ptq_dequant_int8 (const int8_t * q8, size_t rows, size_t cols, ie_ptq_scale_mode_t mode, const float * scales, float * w_out)
Dequantize INT8 weights back to FP32 using provided scales.
Parameters
[in] q8 Pointer to INT8 weights (row-major).
[in] rows Number of rows.
[in] cols Number of columns.
[in] mode Scale granularity, must match scales shape.
[in] scales Buffer of scales used on quantization.
[out] w_out Output buffer for FP32 weights (length rows*cols).
This function reverses ie_ptq_quantize_int8 by multiplying each INT8 element with its associated scale.
Parameters
[in] q8 Pointer to INT8 weights (row-major), length = rows*cols.
[in] rows Number of rows.
[in] cols Number of columns.
[in] mode Granularity of scales (tensor or per-row).
[in] scales Scale buffer that was used during quantization.
[out] w_out Output FP32 buffer (row-major), length = rows*cols.
Note
Dequantization is exact with respect to the chosen scale; any loss is due to the quantization rounding/clamping step.
Definition at line 154 of file int8_ptq.c.
{
   if (!q8 || !w_out || !scales || rows == 0 || cols == 0) return;
   if (mode == IE_PTQ_SCALE_PER_TENSOR) {
     const float s = scales[0] > 0.0f ? scales[0] : 1.0f;
     const size_t n = rows * cols;
     for (size_t i = 0; i < n; ++i) {
       w_out[i] = (float)q8[i] * s;
     }
     return;
   }
   /* Per-row scaling. */
   for (size_t r = 0; r < rows; ++r) {
     const float s = scales[r] > 0.0f ? scales[r] : 1.0f;
     const int8_t *qrow = q8 + r * cols;
     float *row = w_out + r * cols;
     for (size_t c = 0; c < cols; ++c) {
       row[c] = (float)qrow[c] * s;
     }
   }
 }
References IE_PTQ_SCALE_PER_TENSOR.
Referenced by test_per_row_independent_scales(), and test_per_tensor_roundtrip().
ie_ptq_quantize_int8()
void ie_ptq_quantize_int8 (const float * w, size_t rows, size_t cols, ie_ptq_scale_mode_t mode, const float * scales, int8_t * q8)
Quantize FP32 weights to INT8 using precomputed scales.
When mode == IE_PTQ_SCALE_PER_TENSOR, scales[0] is applied to all elements. When mode == IE_PTQ_SCALE_PER_ROW, scales[r] applies to row r. Values are clamped to the symmetric INT8 range [-127, 127].
Parameters
[in] w Pointer to FP32 weights (row-major).
[in] rows Number of rows.
[in] cols Number of columns.
[in] mode Scale granularity, must match scales shape.
[in] scales Buffer of scales computed by ie_ptq_compute_scales_minmax.
[out] q8 Output buffer for INT8 weights (length rows*cols).
Quantize FP32 weights to INT8 using precomputed scales.
When mode == IE_PTQ_SCALE_PER_TENSOR, scales[0] is used for all values. When mode == IE_PTQ_SCALE_PER_ROW, scales[r] is used for row r. Values are multiplied by the reciprocal scale, rounded to nearest, and clamped to the symmetric INT8 range [-127, 127].
Parameters
[in] w Pointer to FP32 weights (row-major), length = rows*cols.
[in] rows Number of rows.
[in] cols Number of columns.
[in] mode Granularity of scales (tensor or per-row).
[in] scales Scale buffer from ie_ptq_compute_scales_minmax.
[out] q8 Output INT8 buffer (row-major), length = rows*cols.
Note
This is a pure weight-only quantization step: no zero-points; the quantization is symmetric around zero.
Definition at line 109 of file int8_ptq.c.
{
   if (!w || !q8 || !scales || rows == 0 || cols == 0) return;
   if (mode == IE_PTQ_SCALE_PER_TENSOR) {
     const float inv = (scales[0] > 0.0f) ? (1.0f / scales[0]) : 1.0f;
     const size_t n = rows * cols;
     for (size_t i = 0; i < n; ++i) {
       q8[i] = clamp_sym_int8(w[i] * inv);
     }
     return;
   }
   /* Per-row scaling. */
   for (size_t r = 0; r < rows; ++r) {
     const float s = scales[r];
     const float inv = (s > 0.0f) ? (1.0f / s) : 1.0f;
     const float *row = w + r * cols;
     int8_t *qrow = q8 + r * cols;
     for (size_t c = 0; c < cols; ++c) {
       qrow[c] = clamp_sym_int8(row[c] * inv);
     }
   }
 }
References clamp_sym_int8(), and IE_PTQ_SCALE_PER_TENSOR.
Referenced by test_per_row_independent_scales(), test_per_tensor_roundtrip(), and test_saturation_symmetric().