Inference Engine (Clocher): engine/include/ie_tokenizer_gptoss.h File Reference
ie_tokenizer_gptoss.h File Reference
GPT-OSS tokenizer loader + encode/decode for:
#include <stddef.h>
#include <stdint.h>
Typedefs
typedef struct ie_tok_gptoss_s ie_tok_gptoss_t
typedef enum ie_tok_gptoss_status_e ie_tok_gptoss_status_t
Enumerations
enum ie_tok_gptoss_status_e {
IE_TOK_GPTOSS_OK = 0 , IE_TOK_GPTOSS_ERR_ARGS = -1 , IE_TOK_GPTOSS_ERR_IO = -2 , IE_TOK_GPTOSS_ERR_JSON = -3 ,
IE_TOK_GPTOSS_ERR_NOMEM = -4 , IE_TOK_GPTOSS_ERR_RANGE = -5 , IE_TOK_GPTOSS_ERR_INTERNAL = -6
}
Functions
int ie_tok_gptoss_open (const char *tokenizer_path, ie_tok_gptoss_t **out_tok)
Open a tokenizer from:
void ie_tok_gptoss_close (ie_tok_gptoss_t *tok)
uint32_t ie_tok_gptoss_vocab_size (const ie_tok_gptoss_t *tok)
int ie_tok_gptoss_encode (const ie_tok_gptoss_t *tok, const char *text, uint32_t *ids, uint32_t *inout_count)
int ie_tok_gptoss_decode (const ie_tok_gptoss_t *tok, const uint32_t *ids, uint32_t count, char *out, size_t *inout_bytes)
Detailed Description
GPT-OSS tokenizer loader + encode/decode for:
HuggingFace tokenizer.json (GPT-2 Byte-Level BPE style)
OpenAI-style .tiktoken rank files (base64 token bytes + rank)
Packed IETOK1 format (recommended)
Design notes:
No third-party JSON library is used.
.tiktoken tokens are stored as raw bytes (binary-safe).
Decode must be correct for "token ids -> coherent text".
Encode is correctness-first. For .tiktoken, we apply byte-level BPE per whitespace/non-whitespace segments (conservative split) to avoid merging across obvious boundaries.
Thread-safety:
A tokenizer handle is read-only after open. Encode/decode are re-entrant as long as the caller provides independent output buffers.
Definition in file ie_tokenizer_gptoss.h.
Typedef Documentation
ie_tok_gptoss_status_t
typedef enum ie_tok_gptoss_status_e ie_tok_gptoss_status_t
ie_tok_gptoss_t
typedef struct ie_tok_gptoss_s ie_tok_gptoss_t
Definition at line 35 of file ie_tokenizer_gptoss.h.
Enumeration Type Documentation
ie_tok_gptoss_status_e
enum ie_tok_gptoss_status_e
Enumerator
IE_TOK_GPTOSS_OK
IE_TOK_GPTOSS_ERR_ARGS
IE_TOK_GPTOSS_ERR_IO
IE_TOK_GPTOSS_ERR_JSON
IE_TOK_GPTOSS_ERR_NOMEM
IE_TOK_GPTOSS_ERR_RANGE
IE_TOK_GPTOSS_ERR_INTERNAL
Definition at line 37 of file ie_tokenizer_gptoss.h.
{
  IE_TOK_GPTOSS_OK = 0,
  IE_TOK_GPTOSS_ERR_ARGS = -1,
  IE_TOK_GPTOSS_ERR_IO = -2,
  IE_TOK_GPTOSS_ERR_JSON = -3,
  IE_TOK_GPTOSS_ERR_NOMEM = -4,
  IE_TOK_GPTOSS_ERR_RANGE = -5,
  IE_TOK_GPTOSS_ERR_INTERNAL = -6
} ie_tok_gptoss_status_t;
Function Documentation
ie_tok_gptoss_close()
void ie_tok_gptoss_close (ie_tok_gptoss_t * tok)
Definition at line 1795 of file tokenizer_gptoss.c.
{
  if (!tok) return;
  if (tok->id_to_tok) {
    for (uint32_t i = 0; i < tok->vocab_size; ++i) free(tok->id_to_tok[i]);
    free(tok->id_to_tok);
  }
  free(tok->tok_to_id);
  free(tok->pair_to_rank);
  intern_free(&tok->intern);
  free(tok->id_to_bytes);
  free(tok->bytes_to_id);
  bytearena_free(&tok->tt_arena);
  free(tok);
}
References bytearena_free(), ie_tok_gptoss_s::bytes_to_id, ie_tok_gptoss_s::id_to_bytes, ie_tok_gptoss_s::id_to_tok, ie_tok_gptoss_s::intern, intern_free(), ie_tok_gptoss_s::pair_to_rank, ie_tok_gptoss_s::tok_to_id, ie_tok_gptoss_s::tt_arena, and ie_tok_gptoss_s::vocab_size.
Referenced by decode_tokens_best_effort(), ie_engine_create(), ie_engine_destroy(), ie_tok_gptoss_open(), and main().
ie_tok_gptoss_decode()
int ie_tok_gptoss_decode (const ie_tok_gptoss_t * tok, const uint32_t * ids, uint32_t count, char * out, size_t * inout_bytes)
Definition at line 1818 of file tokenizer_gptoss.c.
{
  if (!tok || (!ids && count) || !inout_bytes) return IE_TOK_GPTOSS_ERR_ARGS;
  strbuf_t bytes = {0};
  if (tok->mode == IE_TOK_MODE_TIKTOKEN) {
    for (uint32_t i = 0; i < count; ++i) {
      uint32_t id = ids[i];
      if (id >= tok->vocab_size) { strbuf_free(&bytes); return IE_TOK_GPTOSS_ERR_RANGE; }
      const uint8_t *p = tok->id_to_bytes[id].p;
      uint32_t n = tok->id_to_bytes[id].n;
      if (n && (!p)) { strbuf_free(&bytes); return IE_TOK_GPTOSS_ERR_INTERNAL; }
      if (n) {
        if (strbuf_append_bytes(&bytes, (const char *)p, (size_t)n) != 0) { strbuf_free(&bytes); return IE_TOK_GPTOSS_ERR_NOMEM; }
      }
    }
    if (strbuf_reserve(&bytes, 1) != 0) { strbuf_free(&bytes); return IE_TOK_GPTOSS_ERR_NOMEM; }
    bytes.v[bytes.n] = '\0';
    size_t need = bytes.n + 1;
    if (!out || *inout_bytes == 0) { *inout_bytes = need; strbuf_free(&bytes); return IE_TOK_GPTOSS_OK; }
    if (*inout_bytes < need) { *inout_bytes = need; strbuf_free(&bytes); return IE_TOK_GPTOSS_ERR_RANGE; }
    memcpy(out, bytes.v, need);
    *inout_bytes = need;
    strbuf_free(&bytes);
    return IE_TOK_GPTOSS_OK;
  }
  for (uint32_t i = 0; i < count; ++i) {
    uint32_t id = ids[i];
    if (id >= tok->vocab_size) { strbuf_free(&bytes); return IE_TOK_GPTOSS_ERR_RANGE; }
    const char *t = tok->id_to_tok[id];
    if (!t) t = "";
    const size_t tlen = strlen(t);
    size_t pos = 0;
    while (pos < tlen) {
      uint32_t cp = 0;
      int st = utf8_next_cp(t, tlen, &pos, &cp);
      if (st != 0) { strbuf_free(&bytes); return IE_TOK_GPTOSS_ERR_INTERNAL; }
      uint8_t b = 0;
      if (byteunicode_cp_to_byte(&tok->bu, cp, &b) == 0) {
        char c = (char)b;
        if (strbuf_append_bytes(&bytes, &c, 1) != 0) { strbuf_free(&bytes); return IE_TOK_GPTOSS_ERR_NOMEM; }
      } else {
        char tmp[4];
        size_t wn = utf8_put_cp(tmp, sizeof(tmp), cp);
        if (wn == 0) { strbuf_free(&bytes); return IE_TOK_GPTOSS_ERR_INTERNAL; }
        if (strbuf_append_bytes(&bytes, tmp, wn) != 0) { strbuf_free(&bytes); return IE_TOK_GPTOSS_ERR_NOMEM; }
      }
    }
  }
  if (strbuf_reserve(&bytes, 1) != 0) { strbuf_free(&bytes); return IE_TOK_GPTOSS_ERR_NOMEM; }
  bytes.v[bytes.n] = '\0';
  size_t need = bytes.n + 1;
  if (!out || *inout_bytes == 0) { *inout_bytes = need; strbuf_free(&bytes); return IE_TOK_GPTOSS_OK; }
  if (*inout_bytes < need) { *inout_bytes = need; strbuf_free(&bytes); return IE_TOK_GPTOSS_ERR_RANGE; }
  memcpy(out, bytes.v, need);
  *inout_bytes = need;
  strbuf_free(&bytes);
  return IE_TOK_GPTOSS_OK;
}
References ie_tok_gptoss_s::bu, byteunicode_cp_to_byte(), ie_tok_gptoss_s::id_to_bytes, ie_tok_gptoss_s::id_to_tok, IE_TOK_GPTOSS_ERR_ARGS, IE_TOK_GPTOSS_ERR_INTERNAL, IE_TOK_GPTOSS_ERR_NOMEM, IE_TOK_GPTOSS_ERR_RANGE, IE_TOK_GPTOSS_OK, IE_TOK_MODE_TIKTOKEN, ie_tok_gptoss_s::mode, strbuf_s::n, bytes_view_s::n, bytes_view_s::p, strbuf_append_bytes(), strbuf_free(), strbuf_reserve(), utf8_next_cp(), utf8_put_cp(), strbuf_s::v, and ie_tok_gptoss_s::vocab_size.
Referenced by cmd_decode(), cmd_roundtrip(), decode_piece_preview_(), decode_tokens_best_effort(), and ie_engine_generate_ex().
ie_tok_gptoss_encode()
int ie_tok_gptoss_encode (const ie_tok_gptoss_t * tok, const char * text, uint32_t * ids, uint32_t * inout_count)
Definition at line 1891 of file tokenizer_gptoss.c.
{
  if (!tok || !text || !inout_count) return IE_TOK_GPTOSS_ERR_ARGS;
  u32buf_t out_ids = {0};
  if (tok->mode == IE_TOK_MODE_TIKTOKEN) {
    if (tt_encode_text(tok, text, &out_ids) != 0) { free(out_ids.v); return IE_TOK_GPTOSS_ERR_INTERNAL; }
  } else {
    char **parts = NULL;
    size_t nparts = 0;
    if (pretokenize_basic(text, &parts, &nparts) != 0) { free(out_ids.v); return IE_TOK_GPTOSS_ERR_INTERNAL; }
    for (size_t i = 0; i < nparts; ++i) {
      const char *seg = parts[i];
      if (!seg || !*seg) { free(parts[i]); continue; }
      strbuf_t bl = {0};
      if (to_bytelevel_unicode(&tok->bu, seg, strlen(seg), &bl) != 0) { strbuf_free(&bl); goto fail_gpt2; }
      if (strbuf_reserve(&bl, 1) != 0) { strbuf_free(&bl); goto fail_gpt2; }
      bl.v[bl.n] = '\0';
      if (bpe_encode_to_ids_gpt2(tok, bl.v, &out_ids) != 0) { strbuf_free(&bl); goto fail_gpt2; }
      strbuf_free(&bl);
      free(parts[i]);
    }
    free(parts);
    parts = NULL;
    nparts = 0;
  }
  uint32_t need = (uint32_t)out_ids.n;
  if (!ids || *inout_count == 0) {
    *inout_count = need;
    free(out_ids.v);
    return IE_TOK_GPTOSS_OK;
  }
  if (*inout_count < need) {
    *inout_count = need;
    free(out_ids.v);
    return IE_TOK_GPTOSS_ERR_RANGE;
  }
  memcpy(ids, out_ids.v, (size_t)need * sizeof(uint32_t));
  *inout_count = need;
  free(out_ids.v);
  return IE_TOK_GPTOSS_OK;
fail_gpt2:
  free(out_ids.v);
  return IE_TOK_GPTOSS_ERR_INTERNAL;
}
References bpe_encode_to_ids_gpt2(), ie_tok_gptoss_s::bu, IE_TOK_GPTOSS_ERR_ARGS, IE_TOK_GPTOSS_ERR_INTERNAL, IE_TOK_GPTOSS_ERR_RANGE, IE_TOK_GPTOSS_OK, IE_TOK_MODE_TIKTOKEN, ie_tok_gptoss_s::mode, u32buf_s::n, strbuf_s::n, pretokenize_basic(), strbuf_free(), strbuf_reserve(), to_bytelevel_unicode(), tt_encode_text(), u32buf_s::v, and strbuf_s::v.
Referenced by cmd_encode(), cmd_roundtrip(), ie_engine_generate_ex(), and ie_generate_gptoss().
ie_tok_gptoss_open()
int ie_tok_gptoss_open (const char * tokenizer_path, ie_tok_gptoss_t ** out_tok)
Open a tokenizer from:
tokenizer.json
tokenizer.tiktoken
packed IETOK1 file
Parameters
[in] tokenizer_path Path to tokenizer file.
[out] out_tok Tokenizer handle.
Returns
IE_TOK_GPTOSS_OK on success, negative error otherwise.
Definition at line 1761 of file tokenizer_gptoss.c.
{
  if (!tokenizer_path || !out_tok) return IE_TOK_GPTOSS_ERR_ARGS;
  *out_tok = NULL;
  char *buf = NULL;
  size_t len = 0;
  if (read_all_bytes(tokenizer_path, &buf, &len) != 0) return IE_TOK_GPTOSS_ERR_IO;
  ie_tok_gptoss_t *tok = (ie_tok_gptoss_t *)xcalloc(1, sizeof(*tok));
  if (!tok) { free(buf); return IE_TOK_GPTOSS_ERR_NOMEM; }
  byteunicode_init(&tok->bu);
  int rc = IE_TOK_GPTOSS_ERR_JSON;
  if (is_packed_tokenizer((const unsigned char *)buf, len)) {
    rc = parse_tokenizer_packed((const unsigned char *)buf, len, tok);
  } else if (path_ends_with(tokenizer_path, ".tiktoken")) {
    rc = parse_tokenizer_tiktoken(buf, len, tok);
  } else {
    rc = parse_tokenizer_json(buf, tok);
  }
  free(buf);
  if (rc != IE_TOK_GPTOSS_OK) {
    ie_tok_gptoss_close(tok);
    return rc;
  }
  *out_tok = tok;
  return IE_TOK_GPTOSS_OK;
}
References ie_tok_gptoss_s::bu, byteunicode_init(), ie_tok_gptoss_close(), IE_TOK_GPTOSS_ERR_ARGS, IE_TOK_GPTOSS_ERR_IO, IE_TOK_GPTOSS_ERR_JSON, IE_TOK_GPTOSS_ERR_NOMEM, IE_TOK_GPTOSS_OK, is_packed_tokenizer(), parse_tokenizer_json(), parse_tokenizer_packed(), parse_tokenizer_tiktoken(), path_ends_with(), read_all_bytes(), and xcalloc().
Referenced by decode_tokens_best_effort(), ie_engine_create(), and main().
ie_tok_gptoss_vocab_size()
uint32_t ie_tok_gptoss_vocab_size (const ie_tok_gptoss_t * tok)
Definition at line 1813 of file tokenizer_gptoss.c.
{
  if (!tok) return 0;
  return tok->vocab_size;
}
References ie_tok_gptoss_s::vocab_size.
Referenced by ie_engine_create().