Inference Engine (Clocher): engine/include/ie_cpu.h File Reference
ie_cpu.h File Reference
Runtime CPU feature detection utilities.
#include <stdbool.h>
#include <stddef.h>
Data Structures
struct ie_cpu_features
Set of x86 SIMD capabilities used by the inference engine.
Typedefs
typedef struct ie_cpu_features ie_cpu_features_t
Set of x86 SIMD capabilities used by the inference engine.
Functions
bool ie_cpu_detect (ie_cpu_features_t *out)
Detect CPU features at runtime.
bool ie_cpu_features_detect (ie_cpu_features_t *out)
Alias for ie_cpu_detect for clearer call sites.
size_t ie_cpu_features_to_string (const ie_cpu_features_t *feats, char *buf, size_t cap)
Format a feature set as a compact, stable string.
Detailed Description
Runtime CPU feature detection utilities.
This header defines a small, dependency-free API to detect ISA capabilities relevant to CPU inference kernels at runtime (e.g., selecting AVX2 GEMV).
The implementation is best-effort:
On x86/x86_64: uses CPUID and XGETBV to confirm both HW support and OS- enabled register state (XMM/YMM/ZMM).
On non-x86: reports all capabilities as false.
The detected flags are intended for:
Choosing kernel variants (generic vs AVX2 vs AVX-512).
Logging/instrumentation to confirm which fast paths are available.
Definition in file ie_cpu.h.
Typedef Documentation
ie_cpu_features_t
typedef struct ie_cpu_features ie_cpu_features_t
Set of x86 SIMD capabilities used by the inference engine.
Note
avx512_bf16 implies avx512f + OS ZMM state enabled, but the struct keeps each flag explicit so callers can emit clear logs.
Function Documentation
ie_cpu_detect()
bool ie_cpu_detect (ie_cpu_features_t * out)
Detect CPU features at runtime.
Parameters
[out] out Receives the detected capabilities.
Returns
true if detection ran (even if all flags are false), false on invalid arguments.
Referenced by main().
ie_cpu_features_detect()
bool ie_cpu_features_detect (ie_cpu_features_t * out)
Alias for ie_cpu_detect for clearer call sites.
Some call sites prefer "features_detect" naming (e.g., instrumentation).
Parameters
[out] out Receives the detected capabilities.
Returns
See ie_cpu_detect.
Definition at line 111 of file cpu_features.c.
{
  if (!out) return false;
  out->avx2 = false;
  out->fma  = false;
  /* If your ie_cpu_features_t includes this field, we fill it. */
#if defined(__GNUC__) || defined(_MSC_VER)
  /* Some builds may not include avx512_bf16 in the struct; keep this guarded
   * at the source level by only referencing the member name used in your ABI.
   */
  out->avx512_bf16 = false;
#endif
#if defined(__x86_64__) || defined(__i386__) || defined(_M_X64) || defined(_M_IX86)
  unsigned a=0,b=0,c=0,d=0;
  /* Leaf 0: max leaf availability */
  ie_cpuid_ex(0, 0, &a, &b, &c, &d);
  if (a == 0) {
    return true; /* CPUID unsupported or unavailable */
  }
  /* Leaf 1: baseline features (AVX, OSXSAVE, FMA) */
  ie_cpuid_ex(1, 0, &a, &b, &c, &d);
  const int osxsave = (int)((c >> 27) & 1u);
  const int avx     = (int)((c >> 28) & 1u);
  const int fma     = (int)((c >> 12) & 1u);
  /* Validate OS has enabled XMM/YMM via XGETBV */
  unsigned xcr0 = osxsave ? ie_xgetbv_xcr0() : 0u;
  const int ymm_ok = ((xcr0 & 0x6u) == 0x6u);
  /* Leaf 7 subleaf 0: extended features (AVX2) */
  ie_cpuid_ex(7, 0, &a, &b, &c, &d);
  const int avx2 = (int)((b >> 5) & 1u);
  out->avx2 = (avx && ymm_ok && avx2);
  out->fma  = (fma != 0);
  /* Leaf 7 subleaf 1: AVX512_BF16 is in EAX bit 5 on supporting CPUs.
   * We still store it even if the OS might not enable ZMM state; this flag is
   * primarily used as a capability indicator for "do we even try BF16 kernels".
   */
  ie_cpuid_ex(7, 1, &a, &b, &c, &d);
  {
    const int avx512bf16 = (int)((a >> 5) & 1u);
    out->avx512_bf16 = (avx512bf16 != 0);
  }
#endif
  if (ie_env_flag("IE_DEBUG_KERNELS")) {
    char buf[256];
    (void)ie_cpu_features_to_string(out, buf, sizeof buf);
    fprintf(stderr, "[cpu] %s\n", buf);
  }
  return true;
}
References ie_cpu_features_to_string(), ie_cpuid_ex(), ie_env_flag(), and ie_xgetbv_xcr0().
Referenced by ie_gemv_q4_0_f32(), ie_kernels_install(), and ie_q4_kernel_selected_name().
ie_cpu_features_to_string()
size_t ie_cpu_features_to_string (const ie_cpu_features_t * f, char * buf, size_t cap)
Format a feature set as a compact, stable string.
Example: avx=1 avx2=1 fma=1 avx512f=0 avx512dq=0 avx512bw=0 avx512vl=0 avx512_bf16=0
Parameters
feats Feature set (may be NULL, treated as all zeros).
buf Output buffer.
cap Capacity of buf in bytes.
Returns
Number of bytes written (excluding NUL), or 0 on invalid buffer.
Format a feature set as a compact, stable string.
Parameters
f Feature struct.
buf Output buffer.
cap Output capacity in bytes.
Returns
Number of bytes written (excluding NUL), clamped to cap-1.
Definition at line 179 of file cpu_features.c.
{
  if (!buf || cap == 0) return 0;
  if (!f) {
    buf[0] = 0;
    return 0;
  }
  const int n = snprintf(buf, cap,
                         "avx2=%d fma=%d avx512_bf16=%d",
                         f->avx2 ? 1 : 0,
                         f->fma ? 1 : 0,
                         f->avx512_bf16 ? 1 : 0);
  if (n < 0) {
    buf[0] = 0;
    return 0;
  }
  /* Clamp without signedness warnings under -Werror. */
  return ((size_t)n >= cap) ? (cap - 1) : (size_t)n;
}
References ie_cpu_features::avx2, ie_cpu_features::avx512_bf16, and ie_cpu_features::fma.
Referenced by ie_cpu_features_detect().