Inference Engine (Clocher): engine/include/ie_quant_act.h File Reference
ie_quant_act.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct ie_act_i8_params
Per-tensor INT8 affine parameters.
Typedefs
typedef enum ie_fp8_format ie_fp8_format
typedef struct ie_act_i8_params ie_act_i8_params
Enumerations
enum ie_fp8_format { IE_FP8_E4M3 = 0 , IE_FP8_E5M2 = 1 }
FP8 format selector.
Functions
void ie_act_i8_params_from_minmax (float minv, float maxv, int symmetric, float *out_scale, int8_t *out_zero)
Compute per-tensor INT8 parameters from observed min/max.
void ie_quantize_act_int8 (const float *src, int8_t *dst, size_t n, ie_act_i8_params params, int symmetric)
Quantize fp32 activations to INT8 using per-tensor parameters.
void ie_dequantize_act_int8 (const int8_t *src, float *dst, size_t n, ie_act_i8_params params)
Dequantize INT8 activations to fp32 using per-tensor parameters.
void ie_act_i8_group_params_from_data (const float *src, size_t n, size_t group_size, int symmetric, float *out_scales, int8_t *out_zeros)
Compute per-group INT8 parameters from data.
void ie_quantize_act_int8_per_group (const float *src, int8_t *dst, size_t n, size_t group_size, const float *scales, const int8_t *zeros, int symmetric)
Quantize fp32 activations to INT8 using per-group parameters.
void ie_dequantize_act_int8_per_group (const int8_t *src, float *dst, size_t n, size_t group_size, const float *scales, const int8_t *zeros)
Dequantize per-group INT8 activations to fp32.
void ie_quantize_act_fp8 (const float *src, uint8_t *dst, size_t n, ie_fp8_format fmt)
Quantize fp32 activations to FP8.
void ie_dequantize_act_fp8 (const uint8_t *src, float *dst, size_t n, ie_fp8_format fmt)
Dequantize FP8 bytes to fp32.
Typedef Documentation
ie_act_i8_params
typedef struct ie_act_i8_params ie_act_i8_params
ie_fp8_format
typedef enum ie_fp8_format ie_fp8_format
Enumeration Type Documentation
ie_fp8_format
enum ie_fp8_format
FP8 format selector.
Enumerator
IE_FP8_E4M3
1 sign, 4 exponent (bias 7), 3 mantissa; finite-only saturation policy.
IE_FP8_E5M2
1 sign, 5 exponent (bias 15), 2 mantissa; Inf/NaN representable.
Definition at line 26 of file ie_quant_act.h.
{
   IE_FP8_E4M3 = 0,
   IE_FP8_E5M2 = 1
 } ie_fp8_format;
Function Documentation
ie_act_i8_group_params_from_data()
void ie_act_i8_group_params_from_data (const float * src, size_t n, size_t group_size, int symmetric, float * out_scales, int8_t * out_zeros)
Compute per-group INT8 parameters from data.
Splits src into contiguous groups of group_size (last group may be shorter) and computes parameters for each group.
Parameters
src Source float buffer.
n Number of elements.
group_size Group size (>= 1).
symmetric Non-zero for symmetric quantization.
out_scales Output scales array (ceil(n/group_size)).
out_zeros Output zero-points array (ceil(n/group_size)).
Definition at line 109 of file act_int8.c.
{
   if (group_size == 0) return;
   const size_t groups = (n + group_size - 1) / group_size;
   for (size_t g = 0; g < groups; ++g) {
     const size_t start = g * group_size;
     const size_t end   = (start + group_size <= n) ? (start + group_size) : n;
     float mn = src[start];
     float mx = src[start];
     for (size_t i = start + 1; i < end; ++i) {
       mn = ie_minf(mn, src[i]);
       mx = ie_maxf(mx, src[i]);
     }
     float s; int8_t z;
     ie_act_i8_params_from_minmax(mn, mx, symmetric, &s, &z);
     out_scales[g] = s;
     out_zeros[g]  = z;
   }
 }
References ie_act_i8_params_from_minmax(), ie_maxf(), and ie_minf().
Referenced by ie_kv_store_token_int8_per_group(), and test_int8_per_group().
ie_act_i8_params_from_minmax()
void ie_act_i8_params_from_minmax (float minv, float maxv, int symmetric, float * out_scale, int8_t * out_zero)
Compute per-tensor INT8 parameters from observed min/max.
If symmetric != 0:
zero_point is set to 0
scale is derived from max(|minv|,|maxv|)/127
If symmetric == 0:
parameters map minv -> -128 and maxv -> 127 using an affine transform
Parameters
minv Observed minimum.
maxv Observed maximum.
symmetric Non-zero for symmetric quantization.
out_scale Output scale (non-NULL).
out_zero Output zero point (non-NULL).
Definition at line 51 of file act_int8.c.
{
   /* Ensure valid range; if degenerate, pick unit scale. */
   if (!(maxv > minv)) {
     *out_scale = 1.0f;
     *out_zero  = 0;
     return;
   }
   if (symmetric) {
     const float amax = ie_maxf(ie_fabsf(minv), ie_fabsf(maxv));
     /* Map amax -> 127, avoid divide-by-zero. */
     const float denom = (amax > 0.0f) ? amax : 1.0f;
     *out_scale = denom / 127.0f;
     *out_zero  = 0;
   } else {
     /* Map minv -> -128, maxv -> 127 */
     const float qrange = 127.0f - (-128.0f); /* 255 */
     const float scale  = (maxv - minv) / qrange;
     const float zp_f   = -(-128.0f) - (minv / (scale > 0.0f ? scale : 1.0f));
     /* Round and clamp zero point into INT8 range. */
     int zp_i = (int)ie_rne(zp_f);
     if (zp_i < -128) zp_i = -128;
     if (zp_i > 127)  zp_i = 127;
     *out_scale = (scale > 0.0f ? scale : 1.0f);
     *out_zero  = (int8_t)zp_i;
   }
 }
References ie_fabsf(), ie_maxf(), and ie_rne().
Referenced by bench_int8(), ie_act_i8_group_params_from_data(), ie_kv_store_token_int8_per_tensor(), and test_int8_per_tensor().
ie_dequantize_act_fp8()
void ie_dequantize_act_fp8 (const uint8_t * src, float * dst, size_t n, ie_fp8_format fmt)
Dequantize FP8 bytes to fp32.
Parameters
src Source FP8 bytes (bit patterns).
dst Destination float buffer.
n Number of elements.
fmt FP8 format selector.
Definition at line 195 of file act_fp8.c.
{
   if (fmt == IE_FP8_E4M3) {
     for (size_t i = 0; i < n; ++i) {
       dst[i] = ie_unpack_fp8_e4m3(src[i]);
     }
   } else {
     for (size_t i = 0; i < n; ++i) {
       dst[i] = ie_unpack_fp8_e5m2(src[i]);
     }
   }
 }
References IE_FP8_E4M3, ie_unpack_fp8_e4m3(), and ie_unpack_fp8_e5m2().
Referenced by bench_fp8(), ie_kv_load_token_f32(), and test_fp8_sweep().
ie_dequantize_act_int8()
void ie_dequantize_act_int8 (const int8_t * src, float * dst, size_t n, ie_act_i8_params params)
Dequantize INT8 activations to fp32 using per-tensor parameters.
Parameters
src Source INT8 buffer.
dst Destination float buffer (length n).
n Number of elements.
params Dequantization parameters.
Definition at line 100 of file act_int8.c.
{
   const float s = params.scale;
   const int   z = (int)params.zero_point;
   for (size_t i = 0; i < n; ++i) {
     dst[i] = s * ((int)src[i] - z);
   }
 }
References ie_act_i8_params::scale, and ie_act_i8_params::zero_point.
Referenced by bench_int8(), and test_int8_per_tensor().
ie_dequantize_act_int8_per_group()
void ie_dequantize_act_int8_per_group (const int8_t * src, float * dst, size_t n, size_t group_size, const float * scales, const int8_t * zeros)
Dequantize per-group INT8 activations to fp32.
Parameters
src Source INT8 buffer.
dst Destination float buffer.
n Number of elements.
group_size Group size (>= 1).
scales Scales array (ceil(n/group_size)).
zeros Zero-points array (ceil(n/group_size)).
Definition at line 155 of file act_int8.c.
{
   if (group_size == 0) return;
   const size_t groups = (n + group_size - 1) / group_size;
   for (size_t g = 0; g < groups; ++g) {
     const size_t start = g * group_size;
     const size_t end   = (start + group_size <= n) ? (start + group_size) : n;
     const float s = scales[g];
     const int   z = (int)zeros[g];
     for (size_t i = start; i < end; ++i) {
       dst[i] = s * ((int)src[i] - z);
     }
   }
 }
Referenced by test_int8_per_group().
ie_quantize_act_fp8()
void ie_quantize_act_fp8 (const float * src, uint8_t * dst, size_t n, ie_fp8_format fmt)
Quantize fp32 activations to FP8.
E4M3: non-finite inputs saturate to max finite.
E5M2: attempts to preserve Inf/NaN encodings.
Parameters
src Source float buffer.
dst Destination FP8 bytes (bit patterns).
n Number of elements.
fmt FP8 format selector.
Definition at line 182 of file act_fp8.c.
{
   if (fmt == IE_FP8_E4M3) {
     for (size_t i = 0; i < n; ++i) {
       dst[i] = ie_pack_fp8_e4m3(src[i]);
     }
   } else {
     for (size_t i = 0; i < n; ++i) {
       dst[i] = ie_pack_fp8_e5m2(src[i]);
     }
   }
 }
References IE_FP8_E4M3, ie_pack_fp8_e4m3(), and ie_pack_fp8_e5m2().
Referenced by bench_fp8(), ie_kv_store_token_fp8(), and test_fp8_sweep().
ie_quantize_act_int8()
void ie_quantize_act_int8 (const float * src, int8_t * dst, size_t n, ie_act_i8_params params, int symmetric)
Quantize fp32 activations to INT8 using per-tensor parameters.
Parameters
src Source float buffer.
dst Destination INT8 buffer (length n).
n Number of elements.
params Quantization parameters.
symmetric Non-zero to enforce symmetric saturation policy.
Definition at line 81 of file act_int8.c.
{
   const float inv_scale = (params.scale > 0.0f) ? (1.0f / params.scale) : 1.0f;
   if (symmetric) {
     for (size_t i = 0; i < n; ++i) {
       const float v = src[i] * inv_scale;
       const int   q = (int)ie_rne(v);
       dst[i] = ie_sat_sym_i8(q);
     }
   } else {
     const int z = (int)params.zero_point;
     for (size_t i = 0; i < n; ++i) {
       const float v = src[i] * inv_scale + (float)z;
       const int   q = (int)ie_rne(v);
       dst[i] = ie_sat_i8(q);
     }
   }
 }
References ie_rne(), ie_sat_i8(), ie_sat_sym_i8(), ie_act_i8_params::scale, and ie_act_i8_params::zero_point.
Referenced by bench_int8(), ie_kv_store_token_int8_per_tensor(), and test_int8_per_tensor().
ie_quantize_act_int8_per_group()
void ie_quantize_act_int8_per_group (const float * src, int8_t * dst, size_t n, size_t group_size, const float * scales, const int8_t * zeros, int symmetric)
Quantize fp32 activations to INT8 using per-group parameters.
Parameters
src Source float buffer.
dst Destination INT8 buffer.
n Number of elements.
group_size Group size (>= 1).
scales Scales array (ceil(n/group_size)).
zeros Zero-points array (ceil(n/group_size)).
symmetric Non-zero to enforce symmetric saturation policy.
Definition at line 130 of file act_int8.c.
{
   if (group_size == 0) return;
   const size_t groups = (n + group_size - 1) / group_size;
   for (size_t g = 0; g < groups; ++g) {
     const size_t start = g * group_size;
     const size_t end   = (start + group_size <= n) ? (start + group_size) : n;
     const float inv_s  = (scales[g] > 0.0f) ? 1.0f / scales[g] : 1.0f;
     if (symmetric) {
       for (size_t i = start; i < end; ++i) {
         const int q = (int)ie_rne(src[i] * inv_s);
         dst[i] = ie_sat_sym_i8(q);
       }
     } else {
       const int z = (int)zeros[g];
       for (size_t i = start; i < end; ++i) {
         const int q = (int)ie_rne(src[i] * inv_s + (float)z);
         dst[i] = ie_sat_i8(q);
       }
     }
   }
 }
References ie_rne(), ie_sat_i8(), and ie_sat_sym_i8().
Referenced by ie_kv_store_token_int8_per_group(), and test_int8_per_group().