Inference Engine (Clocher): engine/include/ie_infer.h File Reference
ie_infer.h File Reference
Inference interface for the GPT-OSS runtime.
#include <stdint.h>
#include "ie_device.h"
#include "ie_io.h"
#include "ie_kv_cache.h"
Data Structures
struct ie_gptoss_hparams
Minimal hyperparameters required by a GPT-OSS style forward pass.
Typedefs
typedef struct ie_gptoss_hparams ie_gptoss_hparams_t
Minimal hyperparameters required by a GPT-OSS style forward pass.
typedef struct ie_gptoss_infer ie_gptoss_infer_t
Opaque inference context.
Functions
int ie_gptoss_infer_create (const ie_device_t *dev, const ie_weights_t *w, const ie_gptoss_hparams_t *hp, ie_gptoss_infer_t **out_ctx)
Create an inference context.
void ie_gptoss_infer_destroy (ie_gptoss_infer_t *ctx)
Destroy an inference context.
int ie_gptoss_infer_prefill (ie_gptoss_infer_t *ctx, ie_kv_cache *kv, const uint32_t *prompt, uint32_t n_prompt, float *out_logits)
Prefill: consume a prompt, update the KV cache, and produce logits.
int ie_gptoss_infer_step (ie_gptoss_infer_t *ctx, ie_kv_cache *kv, uint32_t token_id, float *out_logits)
Step: consume one token, update the KV cache, and produce next logits.
uint32_t ie_gptoss_infer_get_pos (const ie_gptoss_infer_t *ctx)
Get the current position (number of tokens already consumed).
void ie_gptoss_infer_set_pos (ie_gptoss_infer_t *ctx, uint32_t pos)
Set the current position.
Detailed Description
Inference interface for the GPT-OSS runtime.
Performance notes:
INT4 runs use Q4_0 weight GEMV kernels (runtime-dispatched to AVX2/FMA when available).
Per-32-column scales may be stored as BF16 (2 bytes) or FP8(E4M3) (1 byte) depending on artifacts.
This header defines the stable ABI used by the public API layer (ie_api.c) and by the CLI harness (main_infer.c) to run inference.
The runtime implementation is model-specific and lives under engine/src/runtime. The interface is intentionally minimal:
Create/destroy an inference context bound to a device + weights + hparams.
Prefill a prompt (multi-token).
Step one token at a time.
The KV cache storage is provided by the caller (one cache per layer) via ie_kv_cache so the runtime can update attention state incrementally.
Definition in file ie_infer.h.
Typedef Documentation
ie_gptoss_hparams_t
typedef struct ie_gptoss_hparams ie_gptoss_hparams_t
Minimal hyperparameters required by a GPT-OSS style forward pass.
ie_gptoss_infer_t
typedef struct ie_gptoss_infer ie_gptoss_infer_t
Opaque inference context.
Definition at line 55 of file ie_infer.h.
Function Documentation
ie_gptoss_infer_create()
int ie_gptoss_infer_create (const ie_device_t * dev, const ie_weights_t * w, const ie_gptoss_hparams_t * hp, ie_gptoss_infer_t ** out_ctx)
Create an inference context.
Parameters
dev Device backend (CPU/CUDA).
w Opened weights handle.
hp Hyperparameters.
out_ctx Receives the newly created context on success.
Returns
0 on success; non-zero on failure.
Definition at line 1700 of file infer_gptoss.c.
{
  if (!out_ctx) return -1;
  *out_ctx = NULL;
  if (!w || !hp) return -2;
  if (w->json_path[0] == '\0') {
    IE_LOGE("create: missing w->json_path");
    return -2;
  }
  if (w->weights_path[0] == '\0') {
    IE_LOGE("create: missing w->weights_path");
    return -2;
  }
  IE_LOGI("create: json_path=%s", w->json_path);
  IE_LOGI("create: weights_path=%s", w->weights_path);
  struct ie_gptoss_infer_impl *impl = (struct ie_gptoss_infer_impl *)calloc(1, sizeof(*impl));
  if (!impl) return -3;
  impl->dev = (ie_device_t *)dev_const;
  impl->weights = w;
  impl->hp = hp;
  impl->pos = 0;
  /*
   * NOTE: ie_gptoss_hparams_t does not carry RoPE/RMS fields in this codebase.
   * Keep runtime parameters internal and configurable via environment variables.
   */
  impl->rms_eps = ie_env_f32_clamped("IE_RMS_EPS", IE_GPTOSS_RMS_EPS_DEFAULT, 1.0e-8f, 1.0e-2f);
  impl->rope_theta = ie_env_f32_clamped("IE_ROPE_THETA", IE_GPTOSS_ROPE_THETA_DEFAULT, 1.0f, 1.0e8f);
  impl->rope_scale = ie_env_f32_clamped("IE_ROPE_SCALE", 1.0f, 0.125f, 128.0f);
  impl->use_f32_attn = ie_env_flag("IE_F32_ATTN");
  impl->use_f32_router = ie_env_flag("IE_F32_ROUTER");
  impl->use_f32_lm_head = ie_env_flag("IE_F32_LM_HEAD");
  impl->use_f32_rmsnorm = ie_env_flag("IE_F32_RMSNORM");
  IE_LOGI("create: f32_cache attn=%d router=%d lm_head=%d rmsnorm=%d",
          impl->use_f32_attn, impl->use_f32_router,
          impl->use_f32_lm_head, impl->use_f32_rmsnorm);
  /* Initialize Q4 LUTs up front to avoid pthread_once in hot path. */
  ie_q4_log2_u8_q3_init_generic();
  ie_q4_log2_u8_q3_init_avx2();
  /* Step B: match model routing behavior (top-4 experts). Do not allow overrides here. */
  impl->moe_topk = IE_GPTOSS_MOE_TOPK_DEFAULT;
  impl->max_experts = 0;
  char *model_dir = ie_dirname_alloc(w->json_path);
  if (!model_dir) {
    free(impl);
    return -4;
  }
  IE_LOGD("create: inferred model_dir=%s", model_dir);
  const char *const tmap_rel[] = {
      "model.ie.compat.json",
      "tensor_map.json",
      "dedup_out/tensor_map.json",
      "hf/original/tensor_map.json",
  };
  char *tmap_path = NULL;
  int tmap_ok = -1;
  memset(&impl->tmap, 0, sizeof(impl->tmap));
  impl->tmap_path_used = NULL;
  for (size_t i = 0; i < (sizeof(tmap_rel) / sizeof(tmap_rel[0])); ++i) {
    free(tmap_path);
    tmap_path = ie_path_join_alloc(model_dir, tmap_rel[i]);
    if (!tmap_path) continue;
    IE_LOGI("create: trying tensor_map=%s", tmap_path);
    if (tensor_map_load(tmap_path, &impl->tmap) == 0) {
      tmap_ok = 0;
      impl->tmap_path_used = tmap_path;
      tmap_path = NULL;
      IE_LOGI("create: loaded tensor_map=%s (count=%u)",
              impl->tmap_path_used, (unsigned)impl->tmap.count);
      break;
    }
    IE_LOGW("create: failed to load tensor_map=%s", tmap_path);
    tensor_map_free(&impl->tmap);
    memset(&impl->tmap, 0, sizeof(impl->tmap));
  }
  free(tmap_path);
  if (tmap_ok != 0) {
    IE_LOGE("create: failed to load tensor_map.json (model_dir=%s)", model_dir);
    IE_LOGE("create: tried: %s/tensor_map.json", model_dir);
    IE_LOGE("create: tried: %s/dedup_out/tensor_map.json", model_dir);
    IE_LOGE("create: tried: %s/hf/original/tensor_map.json", model_dir);
    free(model_dir);
    free(impl);
    return -5;
  }
  {
    int rc_mm = ie_mmap_ro(w->weights_path, &impl->bin_base, &impl->bin_size);
    if (rc_mm != 0) {
      IE_LOGE("create: failed to mmap weights file: path=%s rc=%d", w->weights_path, rc_mm);
      tensor_map_free(&impl->tmap);
      free(impl->tmap_path_used);
      free(model_dir);
      free(impl);
      return -6;
    }
    IE_LOGI("create: mapped model.ie.bin size_bytes=%llu",
            (unsigned long long)impl->bin_size);
  }
  free(model_dir);
  const uint32_t d_model = hp->d_model;
  const uint32_t vocab = hp->vocab_size;
  const uint32_t n_layers = hp->n_layers;
  const uint32_t d_head = hp->d_head;
  const uint32_t n_heads = hp->n_heads;
  const uint32_t n_kv_heads = hp->n_kv_heads;
  const uint32_t d_ff = hp->d_ff;
  IE_LOGI("create: hp n_layers=%u d_model=%u d_head=%u n_heads=%u n_kv_heads=%u d_ff=%u vocab=%u max_seq=%u",
          (unsigned)n_layers, (unsigned)d_model, (unsigned)d_head, (unsigned)n_heads,
          (unsigned)n_kv_heads, (unsigned)d_ff, (unsigned)vocab, (unsigned)hp->max_seq);
  IE_LOGI("create: rms_eps=%g rope_theta=%g rope_scale=%g moe_topk=%u",
          (double)impl->rms_eps, (double)impl->rope_theta, (double)impl->rope_scale,
          (unsigned)impl->moe_topk);
  {
    ie_tensor_view_t v;
    const char *const embed_candidates[] = {
      "model.embed_tokens.weight",
      "transformer.wte.weight",
      "tok_embeddings.weight"
    };
    if (ie_w_get_first_view(impl, embed_candidates, 3, &v) != 0) {
      IE_LOGE("create: missing embedding tensor (tried common candidates)");
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -7;
    }
    if (!v.desc || ie_require_size_eq(v.desc, (uint64_t)vocab * (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: embedding size check failed: want=%llu",
              (unsigned long long)((uint64_t)vocab * (uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -8;
    }
    impl->w_embed_bf16 = (const uint16_t *)v.ptr;
  }
  {
    ie_tensor_view_t v;
    const char *const norm_candidates[] = {
      "model.norm.weight",
      "transformer.ln_f.weight",
      "norm.weight"
    };
    if (ie_w_get_first_view(impl, norm_candidates, 3, &v) != 0) {
      IE_LOGE("create: missing final norm tensor (tried common candidates)");
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -9;
    }
    if (!v.desc || ie_require_size_eq(v.desc, (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: final norm size check failed: want=%llu",
              (unsigned long long)((uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -10;
    }
    impl->w_norm_bf16 = (const uint16_t *)v.ptr;
    if (impl->use_f32_rmsnorm) {
      if (ie_alloc_f32_from_bf16(impl->w_norm_bf16, (size_t)d_model, &impl->w_norm_f32) != 0) {
        IE_LOGE("create: failed to allocate final norm f32");
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -10;
      }
    }
  }
  {
    ie_tensor_view_t v;
    const char *const lm_candidates[] = {
      "lm_head.weight",
      "model.lm_head.weight",
      "transformer.lm_head.weight",
      "model.embed_tokens.weight"
    };
    if (ie_w_get_first_view(impl, lm_candidates, 4, &v) != 0) {
      IE_LOGE("create: missing lm_head tensor (tried common candidates)");
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -11;
    }
    if (!v.desc || ie_require_size_eq(v.desc, (uint64_t)vocab * (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: lm_head size check failed: want=%llu",
              (unsigned long long)((uint64_t)vocab * (uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -12;
    }
    impl->w_lm_bf16 = (const uint16_t *)v.ptr;
    {
      ie_tensor_view_t v_q4_blocks;
      ie_tensor_view_t v_q4_scales;
      const char *const q4_blocks_candidates[] = {
        "lm_head.weight_blocks",
        "model.lm_head.weight_blocks",
        "transformer.lm_head.weight_blocks",
        "model.embed_tokens.weight_blocks"
      };
      const char *const q4_scales_candidates[] = {
        "lm_head.weight_scales",
        "model.lm_head.weight_scales",
        "transformer.lm_head.weight_scales",
        "model.embed_tokens.weight_scales"
      };
      const int has_blocks = (ie_w_get_first_view(impl, q4_blocks_candidates, 4, &v_q4_blocks) == 0 &&
                              v_q4_blocks.desc);
      const int has_scales = (ie_w_get_first_view(impl, q4_scales_candidates, 4, &v_q4_scales) == 0 &&
                              v_q4_scales.desc);
      if (has_blocks && has_scales) {
        uint8_t scale_bytes = 0;
        if (v_q4_scales.desc->dtype == TENSOR_DTYPE_BF16) scale_bytes = 2u;
        else if (v_q4_scales.desc->dtype == TENSOR_DTYPE_U8) scale_bytes = 1u;
        else {
          uint64_t want_blocks = 0, want_scales_1 = 0, want_scales_2 = 0;
          if (ie_q4_expected_bytes(vocab, d_model, 1u, &want_blocks, &want_scales_1) != 0 ||
              ie_q4_expected_bytes(vocab, d_model, 2u, &want_blocks, &want_scales_2) != 0) {
            IE_LOGE("create: lm_head q4 expected size failed");
            ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
            return -12;
          }
          if (v_q4_scales.desc->size_bytes == want_scales_1) scale_bytes = 1u;
          else if (v_q4_scales.desc->size_bytes == want_scales_2) scale_bytes = 2u;
        }
        if (scale_bytes != 0u) {
          uint64_t want_blocks = 0, want_scales = 0;
          if (ie_q4_expected_bytes(vocab, d_model, scale_bytes, &want_blocks, &want_scales) != 0 ||
              ie_require_size_eq(v_q4_blocks.desc, want_blocks) != 0 ||
              ie_require_size_eq(v_q4_scales.desc, want_scales) != 0) {
            IE_LOGE("create: lm_head q4 size mismatch");
            ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
            return -12;
          }
          impl->w_lm_q4_blocks = (const uint8_t *)v_q4_blocks.ptr;
          impl->w_lm_q4_scales = (const uint8_t *)v_q4_scales.ptr;
          impl->w_lm_q4_scale_bytes = scale_bytes;
          IE_LOGI("create: lm_head q4 enabled (scale_bytes=%u)", (unsigned)scale_bytes);
        }
      }
    }
    if (impl->use_f32_lm_head && !impl->w_lm_q4_blocks) {
      const uint64_t n64 = (uint64_t)vocab * (uint64_t)d_model;
      if (n64 > (uint64_t)SIZE_MAX) {
        IE_LOGE("create: lm_head f32 size overflow (vocab=%u d_model=%u)",
                (unsigned)vocab, (unsigned)d_model);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -12;
      }
      if (ie_alloc_f32_from_bf16(impl->w_lm_bf16, (size_t)n64, &impl->w_lm_f32) != 0) {
        IE_LOGE("create: failed to allocate lm_head f32");
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -12;
      }
    }
  }
  impl->layers = (ie_gptoss_layer_w_t *)calloc((size_t)n_layers, sizeof(*impl->layers));
  if (!impl->layers) {
    IE_LOGE("create: failed to allocate layer table (n_layers=%u)", (unsigned)n_layers);
    ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
    return -13;
  }
  const uint64_t q_dim = (uint64_t)n_heads * (uint64_t)d_head;
  const uint64_t kv_dim = (uint64_t)n_kv_heads * (uint64_t)d_head;
#if SIZE_MAX < UINT64_MAX
  if (q_dim > (uint64_t)SIZE_MAX || kv_dim > (uint64_t)SIZE_MAX) {
    IE_LOGE("create: attn dim overflow for size_t (q_dim=%llu kv_dim=%llu)",
            (unsigned long long)q_dim, (unsigned long long)kv_dim);
    ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
    return -13;
  }
#endif
  for (uint32_t l = 0; l < n_layers; ++l) {
    ie_gptoss_layer_w_t *LW = &impl->layers[l];
    ie_tensor_view_t v;
    IE_LOGD("create: resolving layer=%u", (unsigned)l);
    const char *const ln1_fmts[] = {
      "model.layers.%u.input_layernorm.weight",
      "model.layers.%u.attention_norm.weight"
    };
    if (ie_w_get_layer_fmt_view(impl, l, ln1_fmts, 2, &v, 1) != 0) {
      IE_LOGE("create: missing ln1 for layer=%u", (unsigned)l);
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -14;
    }
    if (!v.desc || ie_require_size_eq(v.desc, (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: ln1 size mismatch layer=%u want=%llu",
              (unsigned)l, (unsigned long long)((uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -15;
    }
    LW->ln1_w = (const uint16_t *)v.ptr;
    if (impl->use_f32_rmsnorm) {
      if (ie_alloc_f32_from_bf16(LW->ln1_w, (size_t)d_model, &LW->ln1_w_f32) != 0) {
        IE_LOGE("create: failed to allocate ln1 f32 layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -15;
      }
    }
    const char *const q_w_fmts[] = {"model.layers.%u.self_attn.q_proj.weight"};
    const char *const q_b_fmts[] = {"model.layers.%u.self_attn.q_proj.bias"};
    if (ie_w_get_layer_fmt_view(impl, l, q_w_fmts, 1, &v, 1) != 0) {
      IE_LOGE("create: missing q_proj.weight layer=%u", (unsigned)l);
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -16;
    }
    if (!v.desc || ie_require_size_eq(v.desc, q_dim * (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: q_proj.weight size mismatch layer=%u want=%llu",
              (unsigned)l, (unsigned long long)(q_dim * (uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -17;
    }
    LW->q_w = (const uint16_t *)v.ptr;
    if (ie_w_get_layer_fmt_view(impl, l, q_b_fmts, 1, &v, 0) == 0 && v.desc) {
      if (ie_require_size_eq(v.desc, q_dim * 2u) != 0) {
        IE_LOGE("create: q_proj.bias size mismatch layer=%u want=%llu",
                (unsigned)l, (unsigned long long)(q_dim * 2u));
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -18;
      }
      LW->q_b = (const uint16_t *)v.ptr;
    } else {
      LW->q_b = NULL;
    }
    const char *const k_w_fmts[] = {"model.layers.%u.self_attn.k_proj.weight"};
    const char *const k_b_fmts[] = {"model.layers.%u.self_attn.k_proj.bias"};
    if (ie_w_get_layer_fmt_view(impl, l, k_w_fmts, 1, &v, 1) != 0) {
      IE_LOGE("create: missing k_proj.weight layer=%u", (unsigned)l);
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -19;
    }
    if (!v.desc || ie_require_size_eq(v.desc, kv_dim * (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: k_proj.weight size mismatch layer=%u want=%llu",
              (unsigned)l, (unsigned long long)(kv_dim * (uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -20;
    }
    LW->k_w = (const uint16_t *)v.ptr;
    if (ie_w_get_layer_fmt_view(impl, l, k_b_fmts, 1, &v, 0) == 0 && v.desc) {
      if (ie_require_size_eq(v.desc, kv_dim * 2u) != 0) {
        IE_LOGE("create: k_proj.bias size mismatch layer=%u want=%llu",
                (unsigned)l, (unsigned long long)(kv_dim * 2u));
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -21;
      }
      LW->k_b = (const uint16_t *)v.ptr;
    } else {
      LW->k_b = NULL;
    }
    const char *const v_w_fmts[] = {"model.layers.%u.self_attn.v_proj.weight"};
    const char *const v_b_fmts[] = {"model.layers.%u.self_attn.v_proj.bias"};
    if (ie_w_get_layer_fmt_view(impl, l, v_w_fmts, 1, &v, 1) != 0) {
      IE_LOGE("create: missing v_proj.weight layer=%u", (unsigned)l);
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -22;
    }
    if (!v.desc || ie_require_size_eq(v.desc, kv_dim * (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: v_proj.weight size mismatch layer=%u want=%llu",
              (unsigned)l, (unsigned long long)(kv_dim * (uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -23;
    }
    LW->v_w = (const uint16_t *)v.ptr;
    if (ie_w_get_layer_fmt_view(impl, l, v_b_fmts, 1, &v, 0) == 0 && v.desc) {
      if (ie_require_size_eq(v.desc, kv_dim * 2u) != 0) {
        IE_LOGE("create: v_proj.bias size mismatch layer=%u want=%llu",
                (unsigned)l, (unsigned long long)(kv_dim * 2u));
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -24;
      }
      LW->v_b = (const uint16_t *)v.ptr;
    } else {
      LW->v_b = NULL;
    }
    const char *const o_w_fmts[] = {"model.layers.%u.self_attn.o_proj.weight"};
    const char *const o_b_fmts[] = {"model.layers.%u.self_attn.o_proj.bias"};
    if (ie_w_get_layer_fmt_view(impl, l, o_w_fmts, 1, &v, 1) != 0) {
      IE_LOGE("create: missing o_proj.weight layer=%u", (unsigned)l);
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -25;
    }
    if (!v.desc || ie_require_size_eq(v.desc, (uint64_t)d_model * q_dim * 2u) != 0) {
      IE_LOGE("create: o_proj.weight size mismatch layer=%u want=%llu",
              (unsigned)l, (unsigned long long)((uint64_t)d_model * q_dim * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -26;
    }
    LW->o_w = (const uint16_t *)v.ptr;
    if (ie_w_get_layer_fmt_view(impl, l, o_b_fmts, 1, &v, 0) == 0 && v.desc) {
      if (ie_require_size_eq(v.desc, (uint64_t)d_model * 2u) != 0) {
        IE_LOGE("create: o_proj.bias size mismatch layer=%u want=%llu",
                (unsigned)l, (unsigned long long)((uint64_t)d_model * 2u));
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
      LW->o_b = (const uint16_t *)v.ptr;
    } else {
      LW->o_b = NULL;
    }
    const char *const q_q4_blocks_fmts[] = {"model.layers.%u.self_attn.q_proj.weight_blocks"};
    const char *const q_q4_scales_fmts[] = {"model.layers.%u.self_attn.q_proj.weight_scales"};
    {
      int rc_q4 = ie_resolve_q4_attn_weight(
            impl, l, q_q4_blocks_fmts, q_q4_scales_fmts,
            (uint32_t)q_dim, d_model, "q",
            &LW->q_q4_blocks, &LW->q_q4_scales, &LW->q_q4_scale_bytes);
      if (rc_q4 < 0) {
        IE_LOGE("create: invalid q_proj q4 tensors layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
    }
    const char *const k_q4_blocks_fmts[] = {"model.layers.%u.self_attn.k_proj.weight_blocks"};
    const char *const k_q4_scales_fmts[] = {"model.layers.%u.self_attn.k_proj.weight_scales"};
    {
      int rc_q4 = ie_resolve_q4_attn_weight(
            impl, l, k_q4_blocks_fmts, k_q4_scales_fmts,
            (uint32_t)kv_dim, d_model, "k",
            &LW->k_q4_blocks, &LW->k_q4_scales, &LW->k_q4_scale_bytes);
      if (rc_q4 < 0) {
        IE_LOGE("create: invalid k_proj q4 tensors layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
    }
    const char *const v_q4_blocks_fmts[] = {"model.layers.%u.self_attn.v_proj.weight_blocks"};
    const char *const v_q4_scales_fmts[] = {"model.layers.%u.self_attn.v_proj.weight_scales"};
    {
      int rc_q4 = ie_resolve_q4_attn_weight(
            impl, l, v_q4_blocks_fmts, v_q4_scales_fmts,
            (uint32_t)kv_dim, d_model, "v",
            &LW->v_q4_blocks, &LW->v_q4_scales, &LW->v_q4_scale_bytes);
      if (rc_q4 < 0) {
        IE_LOGE("create: invalid v_proj q4 tensors layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
    }
    const char *const o_q4_blocks_fmts[] = {"model.layers.%u.self_attn.o_proj.weight_blocks"};
    const char *const o_q4_scales_fmts[] = {"model.layers.%u.self_attn.o_proj.weight_scales"};
    {
      int rc_q4 = ie_resolve_q4_attn_weight(
            impl, l, o_q4_blocks_fmts, o_q4_scales_fmts,
            d_model, (uint32_t)q_dim, "o",
            &LW->o_q4_blocks, &LW->o_q4_scales, &LW->o_q4_scale_bytes);
      if (rc_q4 < 0) {
        IE_LOGE("create: invalid o_proj q4 tensors layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
    }
    if (impl->use_f32_attn) {
      const size_t q_dim_sz = (size_t)q_dim;
      const size_t kv_dim_sz = (size_t)kv_dim;
      const size_t d_model_sz = (size_t)d_model;
      const uint64_t q_w_n64 = q_dim * (uint64_t)d_model;
      const uint64_t kv_w_n64 = kv_dim * (uint64_t)d_model;
      const uint64_t o_w_n64 = (uint64_t)d_model * q_dim;
#if SIZE_MAX < UINT64_MAX
      if (q_w_n64 > (uint64_t)SIZE_MAX || kv_w_n64 > (uint64_t)SIZE_MAX || o_w_n64 > (uint64_t)SIZE_MAX) {
        IE_LOGE("create: f32 attn weight size overflow layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
#endif
      if (ie_alloc_f32_from_bf16(LW->q_w, (size_t)q_w_n64, &LW->q_w_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->q_b, q_dim_sz, &LW->q_b_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->k_w, (size_t)kv_w_n64, &LW->k_w_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->k_b, kv_dim_sz, &LW->k_b_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->v_w, (size_t)kv_w_n64, &LW->v_w_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->v_b, kv_dim_sz, &LW->v_b_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->o_w, (size_t)o_w_n64, &LW->o_w_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->o_b, d_model_sz, &LW->o_b_f32) != 0) {
        IE_LOGE("create: failed to allocate f32 attn weights layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
    }
    const char *const ln2_fmts[] = {
      "model.layers.%u.post_attention_layernorm.weight",
      "model.layers.%u.ffn_norm.weight"
    };
    if (ie_w_get_layer_fmt_view(impl, l, ln2_fmts, 2, &v, 1) != 0) {
      IE_LOGE("create: missing ln2 for layer=%u", (unsigned)l);
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -28;
    }
    if (!v.desc || ie_require_size_eq(v.desc, (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: ln2 size mismatch layer=%u want=%llu",
              (unsigned)l, (unsigned long long)((uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -29;
    }
    LW->ln2_w = (const uint16_t *)v.ptr;
    if (impl->use_f32_rmsnorm) {
      if (ie_alloc_f32_from_bf16(LW->ln2_w, (size_t)d_model, &LW->ln2_w_f32) != 0) {
        IE_LOGE("create: failed to allocate ln2 f32 layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -29;
      }
    }
    {
      const int rc_moe = ie_resolve_moe_layer(impl, l, LW);
      if (rc_moe != 0) {
        IE_LOGE("create: moe resolve failed: layer=%u rc=%d d_model=%u d_ff=%u",
                (unsigned)l, rc_moe, (unsigned)d_model, (unsigned)d_ff);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -30;
      }
    }
    if (impl->use_f32_router) {
      const uint64_t n_exp = (uint64_t)LW->moe.n_experts;
      const uint64_t router_n64 = n_exp * (uint64_t)d_model;
      if (n_exp > 0 && router_n64 <= (uint64_t)SIZE_MAX) {
        if (ie_alloc_f32_from_bf16(LW->moe.router_w, (size_t)router_n64, &LW->moe.router_w_f32) != 0 ||
            ie_alloc_f32_from_bf16(LW->moe.router_b, (size_t)n_exp, &LW->moe.router_b_f32) != 0) {
          IE_LOGE("create: failed to allocate f32 router weights layer=%u", (unsigned)l);
          ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
          return -30;
        }
      } else if (n_exp > 0) {
        IE_LOGE("create: f32 router size overflow layer=%u n_exp=%u d_model=%u",
                (unsigned)l, (unsigned)LW->moe.n_experts, (unsigned)d_model);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -30;
      }
    }
  }
  const size_t d_model_sz = (size_t)d_model;
  const size_t q_dim_sz = (size_t)n_heads * (size_t)d_head;
  const size_t kv_dim_sz = (size_t)n_kv_heads * (size_t)d_head;
  const size_t d_ff_sz = (size_t)d_ff;
  impl->x = (float *)malloc(d_model_sz * sizeof(float));
  impl->x1 = (float *)malloc(d_model_sz * sizeof(float));
  impl->x2 = (float *)malloc(d_model_sz * sizeof(float));
  impl->q = (float *)malloc(q_dim_sz * sizeof(float));
  impl->k = (float *)malloc(kv_dim_sz * sizeof(float));
  impl->v = (float *)malloc(kv_dim_sz * sizeof(float));
  impl->attn_out = (float *)malloc(q_dim_sz * sizeof(float));
  impl->mlp_gate = (float *)malloc(d_ff_sz * sizeof(float));
  impl->mlp_up = (float *)malloc((2u * d_ff_sz) * sizeof(float));
  impl->scores = (float *)malloc((size_t)hp->max_seq * sizeof(float));
  impl->router_logits = (impl->max_experts > 0u) ? (float *)malloc((size_t)impl->max_experts * sizeof(float)) : NULL;
  if (!impl->x || !impl->x1 || !impl->x2 || !impl->q || !impl->k || !impl->v || !impl->attn_out ||
      !impl->mlp_gate || !impl->mlp_up || !impl->scores || (impl->max_experts > 0u && !impl->router_logits)) {
    IE_LOGE("create: activation allocation failed (max_experts=%u)", (unsigned)impl->max_experts);
    ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
    return -31;
  }
  IE_LOGI("create: success");
  *out_ctx = (ie_gptoss_infer_t *)impl;
  return 0;
}
References ie_gptoss_infer_impl::attn_out, ie_gptoss_infer_impl::bin_base, ie_gptoss_infer_impl::bin_size, tensor_map_s::count, ie_gptoss_hparams::d_ff, ie_gptoss_hparams::d_head, ie_gptoss_hparams::d_model, ie_tensor_view::desc, ie_gptoss_infer_impl::dev, tensor_desc_s::dtype, ie_gptoss_infer_impl::hp, ie_alloc_f32_from_bf16(), ie_dirname_alloc(), ie_env_f32_clamped(), ie_env_flag(), ie_gptoss_infer_destroy(), IE_GPTOSS_MOE_TOPK_DEFAULT, IE_GPTOSS_RMS_EPS_DEFAULT, IE_GPTOSS_ROPE_THETA_DEFAULT, IE_LOGD, IE_LOGE, IE_LOGI, IE_LOGW, ie_mmap_ro(), ie_path_join_alloc(), ie_q4_expected_bytes(), ie_q4_log2_u8_q3_init_avx2(), ie_q4_log2_u8_q3_init_generic(), ie_require_size_eq(), ie_resolve_moe_layer(), ie_resolve_q4_attn_weight(), ie_w_get_first_view(), ie_w_get_layer_fmt_view(), ie_weights_s::json_path, ie_gptoss_infer_impl::k, ie_gptoss_layer_w::k_b, ie_gptoss_layer_w::k_b_f32, ie_gptoss_layer_w::k_q4_blocks, ie_gptoss_layer_w::k_q4_scale_bytes, ie_gptoss_layer_w::k_q4_scales, ie_gptoss_layer_w::k_w, ie_gptoss_layer_w::k_w_f32, ie_gptoss_infer_impl::layers, ie_gptoss_layer_w::ln1_w, ie_gptoss_layer_w::ln1_w_f32, ie_gptoss_layer_w::ln2_w, ie_gptoss_layer_w::ln2_w_f32, ie_gptoss_infer_impl::max_experts, ie_gptoss_hparams::max_seq, ie_gptoss_infer_impl::mlp_gate, ie_gptoss_infer_impl::mlp_up, ie_gptoss_layer_w::moe, ie_gptoss_infer_impl::moe_topk, ie_moe_w::n_experts, ie_gptoss_hparams::n_heads, ie_gptoss_hparams::n_kv_heads, ie_gptoss_hparams::n_layers, ie_gptoss_layer_w::o_b, ie_gptoss_layer_w::o_b_f32, ie_gptoss_layer_w::o_q4_blocks, ie_gptoss_layer_w::o_q4_scale_bytes, ie_gptoss_layer_w::o_q4_scales, ie_gptoss_layer_w::o_w, ie_gptoss_layer_w::o_w_f32, ie_gptoss_infer_impl::pos, ie_tensor_view::ptr, ie_gptoss_infer_impl::q, ie_gptoss_layer_w::q_b, ie_gptoss_layer_w::q_b_f32, ie_gptoss_layer_w::q_q4_blocks, ie_gptoss_layer_w::q_q4_scale_bytes, ie_gptoss_layer_w::q_q4_scales, ie_gptoss_layer_w::q_w, ie_gptoss_layer_w::q_w_f32, ie_gptoss_infer_impl::rms_eps, ie_gptoss_infer_impl::rope_scale, ie_gptoss_infer_impl::rope_theta, ie_moe_w::router_b, ie_moe_w::router_b_f32, ie_gptoss_infer_impl::router_logits, ie_moe_w::router_w, ie_moe_w::router_w_f32, ie_gptoss_infer_impl::scores, tensor_desc_s::size_bytes, TENSOR_DTYPE_BF16, TENSOR_DTYPE_U8, tensor_map_free(), tensor_map_load(), ie_gptoss_infer_impl::tmap, ie_gptoss_infer_impl::tmap_path_used, ie_gptoss_infer_impl::use_f32_attn, ie_gptoss_infer_impl::use_f32_lm_head, ie_gptoss_infer_impl::use_f32_rmsnorm, ie_gptoss_infer_impl::use_f32_router, ie_gptoss_infer_impl::v, ie_gptoss_layer_w::v_b, ie_gptoss_layer_w::v_b_f32, ie_gptoss_layer_w::v_q4_blocks, ie_gptoss_layer_w::v_q4_scale_bytes, ie_gptoss_layer_w::v_q4_scales, ie_gptoss_layer_w::v_w, ie_gptoss_layer_w::v_w_f32, ie_gptoss_hparams::vocab_size, ie_gptoss_infer_impl::w_embed_bf16, ie_gptoss_infer_impl::w_lm_bf16, ie_gptoss_infer_impl::w_lm_f32, ie_gptoss_infer_impl::w_lm_q4_blocks, ie_gptoss_infer_impl::w_lm_q4_scale_bytes, ie_gptoss_infer_impl::w_lm_q4_scales, ie_gptoss_infer_impl::w_norm_bf16, ie_gptoss_infer_impl::w_norm_f32, ie_gptoss_infer_impl::weights, ie_weights_s::weights_path, ie_gptoss_infer_impl::x, ie_gptoss_infer_impl::x1, and ie_gptoss_infer_impl::x2.
Referenced by ie_engine_create(), and ie_generate_gptoss().
ie_gptoss_infer_destroy()
void ie_gptoss_infer_destroy (ie_gptoss_infer_t * ctx)
Destroy an inference context.
Parameters
ctx Context handle (may be NULL).
Definition at line 2292 of file infer_gptoss.c.
{
  if (!ctx) return;
  struct ie_gptoss_infer_impl *impl = (struct ie_gptoss_infer_impl *)ctx;
  if (impl->bin_base) ie_munmap_ro(impl->bin_base, impl->bin_size);
  tensor_map_free(&impl->tmap);
  if (impl->layers) {
    for (uint32_t l = 0; l < impl->hp->n_layers; ++l) {
      ie_gptoss_layer_w_t *LW = &impl->layers[l];
      free(LW->ln1_w_f32);
      free(LW->ln2_w_f32);
      free(LW->q_w_f32);
      free(LW->q_b_f32);
      free(LW->k_w_f32);
      free(LW->k_b_f32);
      free(LW->v_w_f32);
      free(LW->v_b_f32);
      free(LW->o_w_f32);
      free(LW->o_b_f32);
      free(LW->moe.router_w_f32);
      free(LW->moe.router_b_f32);
    }
  }
  free(impl->w_norm_f32);
  free(impl->w_lm_f32);
  free(impl->tmap_path_used);
  free(impl->layers);
  free(impl->x);
  free(impl->x1);
  free(impl->x2);
  free(impl->q);
  free(impl->k);
  free(impl->v);
  free(impl->attn_out);
  free(impl->mlp_gate);
  free(impl->mlp_up);
  free(impl->scores);
  free(impl->router_logits);
  free(impl);
}
References ie_gptoss_infer_impl::attn_out, ie_gptoss_infer_impl::bin_base, ie_gptoss_infer_impl::bin_size, ie_gptoss_infer_impl::hp, ie_munmap_ro(), ie_gptoss_infer_impl::k, ie_gptoss_layer_w::k_b_f32, ie_gptoss_layer_w::k_w_f32, ie_gptoss_infer_impl::layers, ie_gptoss_layer_w::ln1_w_f32, ie_gptoss_layer_w::ln2_w_f32, ie_gptoss_infer_impl::mlp_gate, ie_gptoss_infer_impl::mlp_up, ie_gptoss_layer_w::moe, ie_gptoss_hparams::n_layers, ie_gptoss_layer_w::o_b_f32, ie_gptoss_layer_w::o_w_f32, ie_gptoss_infer_impl::q, ie_gptoss_layer_w::q_b_f32, ie_gptoss_layer_w::q_w_f32, ie_moe_w::router_b_f32, ie_gptoss_infer_impl::router_logits, ie_moe_w::router_w_f32, ie_gptoss_infer_impl::scores, tensor_map_free(), ie_gptoss_infer_impl::tmap, ie_gptoss_infer_impl::tmap_path_used, ie_gptoss_infer_impl::v, ie_gptoss_layer_w::v_b_f32, ie_gptoss_layer_w::v_w_f32, ie_gptoss_infer_impl::w_lm_f32, ie_gptoss_infer_impl::w_norm_f32, ie_gptoss_infer_impl::x, ie_gptoss_infer_impl::x1, and ie_gptoss_infer_impl::x2.
Referenced by ie_engine_create(), ie_engine_destroy(), ie_generate_gptoss(), and ie_gptoss_infer_create().
ie_gptoss_infer_get_pos()
uint32_t ie_gptoss_infer_get_pos (const ie_gptoss_infer_t * ctx)
Get the current position (number of tokens already consumed).
Performance notes:
INT4 runs use Q4_0 weight GEMV kernels (runtime-dispatched to AVX2/FMA when available).
Per-32-column scales may be stored as BF16 (2 bytes) or FP8(E4M3) (1 byte) depending on artifacts.
The runtime maintains a position counter internally. This is used to index into the KV cache (time dimension) and to drive rotary embeddings.
Definition at line 2418 of file infer_gptoss.c.
{
  return ie_gptoss_infer_pos(ctx);
}
References ie_gptoss_infer_pos().
ie_gptoss_infer_prefill()
int ie_gptoss_infer_prefill (ie_gptoss_infer_t * ctx, ie_kv_cache * kv, const uint32_t * prompt, uint32_t n_prompt, float * out_logits)
Prefill: consume a prompt, update the KV cache, and produce logits.
Parameters
ctx Inference context.
kv Array of KV caches, one per layer.
prompt Prompt token IDs.
n_prompt Number of prompt tokens.
out_logits Output logits for the last position (vocab-sized).
Returns
0 on success; non-zero on failure.
Definition at line 2337 of file infer_gptoss.c.
{
  if (!ctx || !kv || (!prompt && n_prompt > 0) || !out_logits) return -1;
  struct ie_gptoss_infer_impl *impl = (struct ie_gptoss_infer_impl *)ctx;
  impl->pos = 0;
  if (n_prompt == 0u) return -2;
  const uint32_t limit = (uint32_t)ie_min_size((size_t)n_prompt, (size_t)impl->hp->max_seq);
  if (limit != n_prompt) {
    IE_LOGW("prefill: prompt truncated from %u to %u due to max_seq=%u",
            (unsigned)n_prompt, (unsigned)limit, (unsigned)impl->hp->max_seq);
  }
  for (uint32_t i = 0; i < limit; ++i) {
    const int rc = ie_forward_one_token(impl, kv, prompt[i], impl->pos, out_logits);
    if (rc != 0) {
      IE_LOGE("prefill: failed at i=%u token=%u pos=%u rc=%d",
              (unsigned)i, (unsigned)prompt[i], (unsigned)impl->pos, rc);
      return rc;
    }
    impl->pos += 1u;
  }
  return 0;
}
References ie_gptoss_infer_impl::hp, ie_forward_one_token(), IE_LOGE, IE_LOGW, ie_min_size(), ie_gptoss_hparams::max_seq, and ie_gptoss_infer_impl::pos.
Referenced by ie_engine_generate_ex(), and ie_generate_gptoss().
ie_gptoss_infer_set_pos()
void ie_gptoss_infer_set_pos (ie_gptoss_infer_t * ctx, uint32_t pos)
Set the current position.
Performance notes:
INT4 runs use Q4_0 weight GEMV kernels (runtime-dispatched to AVX2/FMA when available).
Per-32-column scales may be stored as BF16 (2 bytes) or FP8(E4M3) (1 byte) depending on artifacts.
This exists to enable persistent prompt-prefix reuse: if the KV cache already contains valid K/V entries for positions [0, pos-1], the caller can rewind the runtime position to pos and continue generation without recomputing the prefix.
Definition at line 2422 of file infer_gptoss.c.
{
  (void)ie_gptoss_infer_seek(ctx, pos);
}
References ie_gptoss_infer_seek(), and ie_gptoss_infer_impl::pos.
ie_gptoss_infer_step()
int ie_gptoss_infer_step (ie_gptoss_infer_t * ctx, ie_kv_cache * kv, uint32_t token_id, float * out_logits)
Step: consume one token, update the KV cache, and produce next logits.
Parameters
ctx Inference context.
kv Array of KV caches, one per layer.
token_id The token to consume.
out_logits Output logits for the next token (vocab-sized).
Returns
0 on success; non-zero on failure.
Definition at line 2365 of file infer_gptoss.c.
{
  if (!ctx || !kv || !out_logits) return -1;
  struct ie_gptoss_infer_impl *impl = (struct ie_gptoss_infer_impl *)ctx;
  const uint32_t pos = impl->pos;
  const int rc = ie_forward_one_token(impl, kv, token_id, pos, out_logits);
  if (rc != 0) {
    IE_LOGE("step: failed token=%u pos=%u rc=%d", (unsigned)token_id, (unsigned)pos, rc);
    return rc;
  }
  impl->pos = pos + 1u;
  return 0;
}
References ie_forward_one_token(), IE_LOGE, and ie_gptoss_infer_impl::pos.
Referenced by ie_engine_generate_ex(), and ie_generate_gptoss().