Inference Engine (Clocher): engine/src/devices/ie_device_cuda.cu File Reference
ie_device_cuda.cu File Reference
CUDA runtime implementation for the engine's C ABI CUDA wrapper layer.
#include "ie_device_cuda.h"
#include <cuda_runtime.h>
#include <cstdio>
#include <cstring>
Functions
static void ie_cuda_set_last_error_cuda (const char *what, cudaError_t st)
Store the last error message into the global static buffer.
void ie_cuda_set_last_error_string (const char *s)
Set the last error string directly (C ABI).
void ie_cuda_clear_last_error (void)
Clear the last error string (C ABI).
const char * ie_cuda_last_error_string (void)
Retrieve the last CUDA error string (C ABI).
__global__ void ie_gemv_rowwise_f32_kernel (const float *W, const float *x, float *y, const float *bias, size_t rows, size_t cols)
Row-wise GEMV kernel: each thread computes one output row.
int ie_cuda_is_available (void)
Check if CUDA is available by querying device count.
int ie_cuda_init (int device_ordinal, char *out_name, size_t name_cap, char *out_driver, size_t driver_cap)
Initialize CUDA on a given device and return device/driver info.
void * ie_cuda_malloc (size_t nbytes)
Allocate GPU memory.
void ie_cuda_free (void *p)
Free GPU memory (no-op for NULL).
int ie_cuda_memcpy (void *dst, const void *src, size_t nbytes, ie_cuda_copy_kind_t kind)
Copy memory between host/device with an explicit kind.
int ie_cuda_gemv_f32 (const float *dW, const float *dx, float *dy, size_t rows, size_t cols, const float *dbias)
Launch a simple row-wise GEMV in FP32 and synchronize.
Variables
static char g_last_err [256] = "OK"
Global last-error string buffer (process-wide, owned by this TU).
Detailed Description
CUDA runtime implementation for the engine's C ABI CUDA wrapper layer.
This translation unit is compiled with NVCC and provides a strict C ABI so that C code can invoke CUDA functionality without including CUDA headers.
Error handling:
A single process-wide static buffer stores the last CUDA error string.
ie_cuda_last_error_string() exposes it via C ABI.
ie_cuda_set_last_error_string() and ie_cuda_clear_last_error() are also exported so other CUDA translation units can report errors without defining duplicate symbols.
Definition in file ie_device_cuda.cu.
Function Documentation
ie_cuda_clear_last_error()
void ie_cuda_clear_last_error (void)
Clear the last error string (C ABI).
Definition at line 62 of file ie_device_cuda.cu.
{
  std::snprintf(g_last_err, sizeof(g_last_err), "%s", "OK");
}
References g_last_err.
Referenced by ie_cuda_free(), ie_cuda_gemv_f32(), ie_cuda_init(), ie_cuda_is_available(), ie_cuda_launch_gemv_rowwise_f32(), ie_cuda_launch_gemv_rowwise_int4(), ie_cuda_launch_gemv_rowwise_int8(), ie_cuda_malloc(), ie_cuda_memcpy(), ie_cuda_pack_w_blockedk_f32(), and ie_cuda_touch_bytes().
ie_cuda_free()
void ie_cuda_free (void * p)
Free GPU memory (no-op for NULL).
Free device memory allocated by ie_cuda_malloc().
Parameters
p Device pointer (may be NULL).
Definition at line 206 of file ie_device_cuda.cu.
{
  if (!p) return;
  const cudaError_t st = cudaFree(p);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaFree", st);
    return;
  }
  ie_cuda_clear_last_error();
}
ie_cuda_gemv_f32()
int ie_cuda_gemv_f32 (const float * dW, const float * dx, float * dy, size_t rows, size_t cols, const float * dbias)
Launch a simple row-wise GEMV in FP32 and synchronize.
Launch a GEMV FP32 kernel: y = W*x + bias (bias optional).
Parameters
dW Device pointer to row-major weights (rows x cols).
dx Device pointer to input vector (cols).
dy Device pointer to output vector (rows).
rows Rows.
cols Cols.
dbias Optional bias vector (rows) or NULL.
Returns
0 on success, negative on failure.
Definition at line 255 of file ie_device_cuda.cu.
{
  if (!dW || !dx || !dy || rows == 0 || cols == 0) {
    std::snprintf(g_last_err, sizeof(g_last_err), "%s", "ie_cuda_gemv_f32: invalid args");
    return -1;
  }
  const int block = 256;
  const int grid = (int)((rows + (size_t)block - 1) / (size_t)block);
  ie_gemv_rowwise_f32_kernel<<<grid, block>>>(dW, dx, dy, dbias, rows, cols);
  cudaError_t st = cudaGetLastError();
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("kernel launch", st);
    return -2;
  }
  st = cudaDeviceSynchronize();
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaDeviceSynchronize", st);
    return -3;
  }
  ie_cuda_clear_last_error();
  return 0;
}
References g_last_err, ie_cuda_clear_last_error(), ie_cuda_set_last_error_cuda(), and ie_gemv_rowwise_f32_kernel().
Referenced by cuda_gemv_f32_thunk().
ie_cuda_init()
int ie_cuda_init (int device_ordinal, char * out_name, size_t name_cap, char * out_driver, size_t driver_cap)
Initialize CUDA on a given device and return device/driver info.
Initialize CUDA for a given device ordinal and return basic identity strings.
This forces runtime/driver initialization via cudaFree(0) so preflight checks can observe real driver activity.
Parameters
device_ordinal CUDA device ordinal.
out_name Output buffer for device name (may be NULL).
name_cap Capacity of out_name in bytes.
out_driver Output buffer for driver/runtime versions (may be NULL).
driver_cap Capacity of out_driver in bytes.
Returns
0 on success, negative on failure.
Definition at line 145 of file ie_device_cuda.cu.
{
  cudaError_t st = cudaSetDevice(device_ordinal);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaSetDevice", st);
    return -1;
  }
  st = cudaFree(0);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaFree(0)", st);
    return -2;
  }
  cudaDeviceProp prop;
  std::memset(&prop, 0, sizeof(prop));
  st = cudaGetDeviceProperties(&prop, device_ordinal);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaGetDeviceProperties", st);
    return -3;
  }
  if (out_name && name_cap) {
    std::snprintf(out_name, name_cap, "%s", prop.name);
  }
  int drv = 0, rt = 0;
  (void)cudaDriverGetVersion(&drv);
  (void)cudaRuntimeGetVersion(&rt);
  if (out_driver && driver_cap) {
    std::snprintf(out_driver, driver_cap, "driver=%d runtime=%d", drv, rt);
  }
  ie_cuda_clear_last_error();
  return 0;
}
References ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_try_create().
ie_cuda_is_available()
int ie_cuda_is_available (void)
Check if CUDA is available by querying device count.
Returns non-zero if at least one CUDA device is available.
Returns
1 if at least one CUDA device is visible, 0 otherwise.
Definition at line 121 of file ie_device_cuda.cu.
{
  int n = 0;
  const cudaError_t st = cudaGetDeviceCount(&n);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaGetDeviceCount", st);
    return 0;
  }
  ie_cuda_clear_last_error();
  return (n > 0) ? 1 : 0;
}
ie_cuda_malloc()
void * ie_cuda_malloc (size_t nbytes)
Allocate GPU memory.
Allocate device memory.
Parameters
nbytes Number of bytes.
Returns
Device pointer on success, NULL on failure.
Definition at line 190 of file ie_device_cuda.cu.
{
  void *p = nullptr;
  const cudaError_t st = cudaMalloc(&p, nbytes);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaMalloc", st);
    return nullptr;
  }
  ie_cuda_clear_last_error();
  return p;
}
References ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_ensure_capacity().
ie_cuda_memcpy()
int ie_cuda_memcpy (void * dst, const void * src, size_t nbytes, ie_cuda_copy_kind_t kind)
Copy memory between host/device with an explicit kind.
Copy memory using CUDA.
Parameters
dst Destination pointer.
src Source pointer.
nbytes Number of bytes.
kind Copy direction.
Returns
0 on success, negative on failure.
Definition at line 225 of file ie_device_cuda.cu.
{
  cudaMemcpyKind ck = cudaMemcpyDefault;
  switch (kind) {
    case IE_CUDA_COPY_H2D: ck = cudaMemcpyHostToDevice; break;
    case IE_CUDA_COPY_D2H: ck = cudaMemcpyDeviceToHost; break;
    case IE_CUDA_COPY_D2D: ck = cudaMemcpyDeviceToDevice; break;
    case IE_CUDA_COPY_DEFAULT: default: ck = cudaMemcpyDefault; break;
  }
  const cudaError_t st = cudaMemcpy(dst, src, nbytes, ck);
  if (st != cudaSuccess) {
    ie_cuda_set_last_error_cuda("cudaMemcpy", st);
    return -1;
  }
  ie_cuda_clear_last_error();
  return 0;
}
References ie_cuda_clear_last_error(), IE_CUDA_COPY_D2D, IE_CUDA_COPY_D2H, IE_CUDA_COPY_DEFAULT, IE_CUDA_COPY_H2D, and ie_cuda_set_last_error_cuda().
Referenced by cuda_gemv_f32_thunk(), and cuda_memcpy_thunk().
ie_cuda_set_last_error_cuda()
static void ie_cuda_set_last_error_cuda (const char * what, cudaError_t st) static
Store the last error message into the global static buffer.
Parameters
what Context string (may be NULL).
st CUDA status code.
Definition at line 36 of file ie_device_cuda.cu.
{
  const char *msg = cudaGetErrorString(st);
  std::snprintf(g_last_err, sizeof(g_last_err), "%s: %s",
                what ? what : "CUDA",
                msg ? msg : "Unknown");
}
References g_last_err.
Referenced by ie_cuda_free(), ie_cuda_gemv_f32(), ie_cuda_init(), ie_cuda_is_available(), ie_cuda_malloc(), and ie_cuda_memcpy().
ie_cuda_set_last_error_string()
void ie_cuda_set_last_error_string (const char * s)
Set the last error string directly (C ABI).
This is intended for other CUDA translation units to report errors without defining their own ie_cuda_last_error_string symbol.
Parameters
s Error string (may be NULL).
Definition at line 51 of file ie_device_cuda.cu.
{
  if (!s || !*s) {
    std::snprintf(g_last_err, sizeof(g_last_err), "%s", "unknown CUDA error");
    return;
  }
  std::snprintf(g_last_err, sizeof(g_last_err), "%s", s);
}
References g_last_err.
Referenced by ie_cuda_record_cuda_error(), and ie_cuda_touch_bytes().
ie_gemv_rowwise_f32_kernel()
__global__ void ie_gemv_rowwise_f32_kernel (const float * W, const float * x, float * y, const float * bias, size_t rows, size_t cols)
Row-wise GEMV kernel: each thread computes one output row.
This is a correctness-first kernel intended to validate real GPU execution. Performance work (tiling, vectorization, shared memory, etc.) can follow.
Parameters
W Row-major matrix (rows x cols).
x Input vector (cols).
y Output vector (rows).
bias Optional bias (rows) or NULL.
rows Number of rows.
cols Number of columns.
Definition at line 92 of file ie_device_cuda.cu.
{
  const size_t r = (size_t)blockIdx.x * (size_t)blockDim.x + (size_t)threadIdx.x;
  if (r >= rows) return;
  const float *Wr = W + r * cols;
  float acc = 0.0f;
  for (size_t c = 0; c < cols; ++c) {
    acc += Wr[c] * x[c];
  }
  if (bias) acc += bias[r];
  y[r] = acc;
}
Referenced by update_performance_md::_agg(), update_performance_md::_agg_numeric(), update_performance_md::_agg_sum(), dedup_prepare_and_extract_all::_as_list_tensors(), build_dedup_source_from_manifest::_bf16_to_f32(), dedup_extract_int4::_bitset_popcount(), build_dedup_source_from_manifest::_build_dedup_source(), dedup_prepare_and_extract_all::_build_name_to_index(), update_performance_md::_bytes_touched(), update_performance_md::_dedup_artifact_stats(), dedup_extract_int4::_diff_default_target(), update_performance_md::_discover_cpu_model(), build_dedup_source_from_manifest::_discover_expert_count(), update_performance_md::_discover_git(), update_performance_md::_discover_kernel(), update_performance_md::_discover_mem_total_gb(), update_performance_md::_discover_os(), dedup_prepare_and_extract_all::_dtype_size(), build_dedup_source_from_manifest::_encode_scales_fp16(), build_dedup_source_from_manifest::_encode_scales_log2_u8_q3(), test_cli_error_paths::_engine_bin(), update_performance_md::_filesize_follow(), metrics_exporter::_find_latest_json(), update_performance_md::_find_model_bin(), update_performance_md::_fmt_float(), metrics_exporter::_gauge_line(), build_dedup_source_from_manifest::_infer_expert_weight_names(), gen_q4_bytes_stream::_iter_shards(), metrics_exporter::_label_str(), build_dedup_source_from_manifest::_load_json(), dedup_extract_int4::_load_json(), dedup_prepare_and_extract_all::_load_json(), dedup_verify_int4::_load_json(), metrics_exporter::_load_one_json_file(), gen_q4_bytes_stream::_load_state_dict(), dedup_prepare_and_extract_all::_make_virtual_slices(), build_dedup_source_from_manifest::_manifest_required_tensors(), update_performance_md::_max_or_none(), update_performance_md::_mean(), update_performance_md::_merge_shared(), update_performance_md::_min_or_none(), update_performance_md::_now_utc_str(), gen_q4_bytes_stream::_pack_int4_from_int8(), build_dedup_source_from_manifest::_pack_int4_nibbles(), update_performance_md::_parse(), build_dedup_source_from_manifest::_parse_ie(), dedup_extract_int4::_parse_tensor_map(), dedup_verify_int4::_parse_tensor_map(), update_performance_md::_partition_runs_and_summary(), dedup_prepare_and_extract_all::_prepare_groups_and_tensor_map(), build_dedup_source_from_manifest::_quant_int4_groupwise(), dedup_verify_int4::_read_all(), update_performance_md::_read_json_lines(), dedup_extract_int4::_read_slice(), dedup_verify_int4::_read_slice(), build_dedup_source_from_manifest::_read_tensor_bytes(), build_dedup_source_from_manifest::_read_weight_matrix_f32(), dedup_verify_int4::_reconstruct(), update_performance_md::_render_dedup_section(), update_performance_md::_render_memory_details(), update_performance_md::_render_system(), update_performance_md::_render_table(), build_dedup_source_from_manifest::_save_json(), dedup_prepare_and_extract_all::_save_json(), update_performance_md::_sum_f(), update_performance_md::_sum_i(), dedup_extract_int4::_write_json(), advise_sequential(), advise_willneed(), all_in_sym_int8_range(), all_marked_once(), alloc_replica_first_touch(), apply_cpulist_to_node(), ascii_ieq(), ascii_ieq(), bad_float3(), blobs_free(), blobs_push(), block_is_nonzero(), build_block_sparse_4x4(), build_dense_4x4(), build_groups_auto(), canon_dir(), ceil_div_sz(), cfg_bytes(), cfg_stride(), checksum_bytes(), clamp_q4(), clamp_sym_int8(), clamp_to_pos31(), cli_extras_defaults(), metrics_exporter::collect_metrics_from_summary(), compute_first_cpu_per_socket(), cpuid_ex(), cpyz(), cuda_destroy_thunk(), cuda_gemv_block_sparse_f32_unimpl(), cuda_gemv_f32_thunk(), cuda_try_create(), cudart_get_api(), cudart_smoke_free0(), cudart_touch_bytes(), dalloc(), dbg(), dedup_fnv1a64(), dedup_spec_builder_write_file(), dense_to_block_sparse(), device_is_cpu(), device_is_cuda(), dfree(), die(), dir_accessible(), discover_nodes_sysfs(), discover_sockets_sysfs(), metrics_exporter.Handler::do_GET(), dump_topology(), dump_vec(), ensure_dedup_manifest_link(), ensure_module_ready(), ensure_ze_ready(), env_flag(), env_flag_get(), env_flag_get(), env_int_get(), env_long(), env_sizet_get(), env_str(), exercise_advice_and_walk(), ptq_from_source::export_onnx(), ptq_from_source::export_torch(), extract_one(), feq(), file_exists(), file_exists_readable(), fill_matrix(), fill_range(), fill_vector(), ptq_from_hf::find_checkpoint(), first_touch_write(), fp16_to_fp32(), free_replicas_internal(), fwrite_all(), gemv_bias_act_f32(), gemv_generic_impl(), gemv_qi8_f32_fused_c_impl(), gemv_qi8pg_f32_fused_c_impl(), gemv_rowwise_f32(), gemv_rowwise_f32_kernel(), gemv_rowwise_int4_kernel(), gemv_rowwise_int8_kernel(), get_online_cpus(), group_add_member(), groups_free(), groups_push(), hash_bytes(), hash_view(), validate_ie_json::human_bytes(), ie_act_i8_group_params_from_data(), ie_act_i8_params_from_minmax(), ie_aligned_free_64(), ie_aligned_malloc_64(), ie_apply_activation(), ie_batcher_advance(), ie_batcher_create(), ie_batcher_destroy(), ie_batcher_get(), ie_bf16_to_fp32(), ie_bitset_get(), ie_block_sparse_density(), ie_block_sparse_init(), ie_block_sparse_load(), ie_block_sparse_release(), ie_clamp01(), ie_cpu_detect(), ie_cuda_gemv_f32(), ie_cuda_launch_gemv_rowwise_f32(), ie_cuda_launch_gemv_rowwise_int4(), ie_cuda_launch_gemv_rowwise_int8(), ie_cuda_pack_w_blockedk_f32(), ie_cuda_record_cuda_error(), ie_cuda_touch_bytes(), ie_cuda_touch_kernel(), ie_decode_fp8_e4m3(), ie_decode_fp8_e5m2(), ie_dequantize_act_fp8(), ie_dequantize_act_int8(), ie_dequantize_act_int8_per_group(), ie_detect_caches_linux(), ie_device_caps(), ie_device_create(), ie_device_destroy(), ie_device_gemv_block_sparse_f32(), ie_device_gemv_f32(), ie_device_kind_from_str(), ie_device_memcpy(), ie_dtype_elem_size(), ie_engine_generate(), ie_fabsf(), ie_fast_tanhf(), ie_find_file_index(), ie_find_tensor(), ie_fp16_to_fp32(), ie_fp32_to_bf16(), ie_fp32_to_fp16(), ie_gemv_block_sparse_f32(), ie_gemv_f32(), ie_gemv_f32_avx2_impl(), ie_gemv_qfp8_f32(), ie_gemv_qi8_f32(), ie_gemv_qi8_f32_avx2_impl(), ie_gemv_qi8pg_f32(), ie_hot_replica_for_socket(), ie_hot_replica_memcpy(), ie_hot_replicas_free(), ie_hot_replicate_build(), ie_hot_replicate_build_fill(), ie_iejson_tensor_free(), ie_int4_absmax(), ie_int4_absmax_per_row(), ie_int4_dequantize_per_row(), ie_int4_dequantize_per_tensor(), ie_int4_error_metrics(), ie_int4_get_nibble(), ie_int4_quantize_per_row(), ie_int4_quantize_per_tensor(), ie_int4_set_nibble(), ie_kernels_install(), ie_kv_begin_round(), ie_kv_element_size(), ie_kv_finish_round(), ie_kv_free(), ie_kv_hit_add_local(), ie_kv_init(), ie_kv_load_token_f32(), ie_kv_miss_add_local(), ie_kv_on_token(), ie_kv_raw_ptrs(), ie_kv_store_token_f32(), ie_kv_store_token_fp8(), ie_kv_store_token_int8_per_group(), ie_kv_store_token_int8_per_tensor(), ie_layout_build_blockedK(), ie_layout_cache_name(), ie_layout_free(), ie_log_debug(), ie_log_info(), ie_log_set_level(), ie_madvise_policy(), ie_maxf(), ie_metrics_add_kv(), ie_metrics_add_kv_hit(), ie_metrics_add_kv_miss(), ie_metrics_reset(), ie_metrics_sample_rss_peak(), ie_metrics_snapshot(), ie_minf(), ie_mmap_advise_thp(), ie_mmap_apply_advise(), ie_mmap_close(), ie_mmap_close(), ie_mmap_close_many(), ie_mmap_fadvise(), ie_mmap_kernel_hugepagesize(), ie_mmap_open(), ie_mmap_open_many(), ie_mmap_prefault_touch_ro(), ie_mmap_readahead(), ie_mmap_ro(), ie_mmap_touch(), ie_nt_copy_f32_avx2(), ie_nt_copy_f32_avx512(), ie_nt_set_f32_avx2(), ie_nt_set_f32_avx512(), ie_numa_detect_nodes(), ie_numa_policy_init(), ie_numa_policy_replica_count(), ie_numa_policy_should_replicate_hot(), ie_pack_fp8_e4m3(), ie_pack_fp8_e5m2(), ie_parse_files_object(), ie_parse_iejson_one_tensor(), ie_parse_iejson_tensors(), ie_parse_one_tensor(), ie_parse_tensors_array(), ie_path_join(), ie_pread(), ie_ptq_compute_scales_minmax(), ie_ptq_dequant_int8(), ie_ptq_quantize_int8(), ie_quantize_act_fp8(), ie_quantize_act_int8(), ie_quantize_act_int8_per_group(), ie_read_cache_size_file(), ie_read_file_text(), ie_rne(), ie_round_up_pow2(), ie_sat_i8(), ie_sat_sym_i8(), ie_scalar_copy_f32(), ie_scalar_set_f32(), ie_set_affinity(), ie_shape_elem_count(), ie_sparse_status_str(), ie_strdup(), ie_stream_copy_f32(), ie_stream_memset_f32(), ie_stream_policy_init(), ie_stream_prefetch_nta(), ie_stream_prefetch_range_nta(), ie_stream_prefetch_range_t0(), ie_stream_prefetch_t0(), ie_stream_recommend_prefetch_distance(), ie_stream_should_use_nt(), ie_task_main(), ie_tensor_cmp_name(), ie_tok_decode(), ie_tok_encode(), ie_topology_bind_thread_to_socket(), ie_topology_cpu_to_node(), ie_topology_cpu_to_socket(), ie_topology_cpus(), ie_topology_destroy(), ie_topology_first_cpu_on_socket(), ie_topology_init(), ie_topology_nodes(), ie_topology_sockets(), ie_tp_create(), ie_tp_destroy(), ie_tp_parallel_for(), ie_u32_from_f(), ie_unpack_fp8_e4m3(), ie_unpack_fp8_e5m2(), ie_vec_tanh_f32(), ie_vec_tanh_f32_out(), ie_vec_tanh_f32_strided(), ie_vocab_free(), ie_vocab_load(), ie_wdedup_debug_enabled(), ie_wdedup_errno_str(), ie_wdedup_logf(), ie_wdedup_status_str(), ie_wdedup_vlogf(), ie_weights_close(), ie_weights_decode_int4(), ie_weights_dedup_close(), ie_weights_dedup_get_weight_view(), ie_weights_dedup_materialize(), ie_weights_dedup_open(), ie_weights_dedup_parse_dtype(), ie_weights_open(), ie_weights_read_int4_meta(), ie_weights_touch(), ie_worker_main(), ie_ze_launch_gemv_bias_act_f32(), ie_ze_launch_gemv_rowwise_f32(), ie_ze_launch_pack_w_blockedk_f32(), ie_ze_launch_vec_tanh_f32(), is_int4_precision(), join_path(), join_path(), join_path(), js_find_member_value(), js_match_lit(), js_parse_blobref(), js_parse_i64(), js_parse_shape(), js_parse_string(), js_read_str_member(), js_read_u64_member(), js_skip_array(), js_skip_object(), js_skip_value(), js_skip_ws(), json_find_string(), json_find_u64(), kib_to_mib_ceil(), kind_from_string(), kv_validate_and_derive(), last_slash(), load_cache(), load_dense_matrix(), hf_to_iebin_stream::load_index(), load_manifest(), ptq_from_hf::load_state_dict(), convert_safetensors_to_pt_bin::main(), export_tensors_onnx::main(), export_tensors_torch::main(), gen_q4_bytes_stream::main(), gen_q4_bytes_worker::main(), hf_to_iebin::main(), hf_to_iebin_raw::main(), hf_to_iebin_stream::main(), hf_to_iebin_stream_pt::main(), make_baseline_md::main(), metrics_exporter::main(), ptq_from_bin::main(), ptq_from_hf::main(), ptq_from_source::main(), q4_pack_stream::main(), split_q4_manifest_to_files::main(), update_performance_md::main(), build_dedup_source_from_manifest::main(), dedup_extract_int4::main(), dedup_prepare_and_extract_all::main(), dedup_verify_int4::main(), validate_ie_json::main(), main(), main(), make_temp_file(), mark_task(), mask_set(), memcpy_imm(), min_size(), model_touch_bytes(), model_touch_close(), model_touch_open(), mse(), mse(), make_baseline_md::newest_report_dir(), normalize_name(), now_sec(), hf_to_iebin_stream::np_ensure_contig(), open_and_touch(), open_rb(), gen_q4_bytes_worker::pack_int4_rows(), pack_q4_pair(), q4_pack_stream::pack_row_int4_sym(), pack_w_blockedk_f32(), pack_w_blockedk_f32_kernel(), param_index(), gen_q4_bytes_stream::parse_args(), parse_args(), parse_cli(), parse_flags(), parse_range_list(), parse_status_kb_line(), path_exists(), path_is_abs(), path_join(), payload_index(), pread_exact(), print_json_result(), validate_ie_json::prod(), q4_pack_stream::quantize_2d_per_row(), read_all_text(), read_file(), read_file_all(), read_first_nonempty_line(), read_fully(), read_int_file(), hf_to_iebin_stream::read_json(), test_ptq_calib_pipeline::read_json(), read_proc_kb_single(), hf_to_iebin_raw::read_safetensors_header(), make_baseline_md::read_samples(), make_baseline_md::read_summary(), ref_gemv_bias(), ref_gemv_nominal(), resolve_model_paths(), rss_peak_mib(), test_cli_flags.CLIFeatureFlagsTests::run_cli(), test_ptq_calib_pipeline.PTQCalibPipelineTests::run_ptq(), q4_pack_stream::safe(), safe_atoi(), split_q4_manifest_to_files::safe_name(), safe_strcpy(), save_cache_atomic(), scan_json_key_int(), scan_json_key_string(), scan_json_key_string_in_range(), scan_json_object_range(), set_arg(), set_err(), hf_to_iebin::sizeof_dtype(), starts_with(), str_ieq(), hf_to_iebin_stream_pt::tensor_dtype_tag(), hf_to_iebin_stream_pt::tensor_to_bytes(), ptq_from_hf::tensor_to_fp32_bin(), test_basic_prefetch_and_order(), test_block_sparse_gemv_basic(), test_block_sparse_helpers(), test_block_sparse_init_release(), test_block_sparse_load_missing(), test_cli.CLITests::test_cli_runs_and_emits_json(), test_cpu_caps(), test_harness_more.HarnessMoreTests::test_custom_samples_and_promptlen(), test_fp8_sweep(), test_gemv_rowmajor_no_bias(), test_gemv_rowmajor_with_bias(), test_gpu_fallback(), test_harness.HarnessTests::test_harness_generates_reports(), test_int8_per_group(), test_int8_per_tensor(), test_cli_error_paths.CLIErrorPathsTests::test_invalid_flag_is_rejected(), test_kind_parse(), test_metrics_ring.MetricsRingTests::test_p50_p95_present_and_consistent(), test_partial_teardown(), test_per_row_independent_scales(), test_ptq_calib_pipeline.PTQCalibPipelineTests::test_per_row_pipeline(), test_ptq_calib_pipeline.PTQCalibPipelineTests::test_per_tensor_pipeline(), test_per_tensor_roundtrip(), test_determinism.DeterminismTests::test_same_prompt_same_output_short_run(), test_saturation_symmetric(), test_tokenize_cb(), test_wrap_and_view_limits(), test_cli_error_paths.CLIErrorPathsTests::test_zero_tokens_graceful(), touch_file_small(), u64_ceil_div(), unpack_int4(), unpack_q4_pair(), usage(), usage(), vec_allclose(), vec_tanh_f32(), verify_pattern(), gen_q4_bytes_stream::wanted(), gen_q4_bytes_worker::wanted(), q4_pack_stream::wanted(), worker_main(), write_block_sparse_file(), test_ptq_calib_pipeline::write_f32_bin(), xgetbv_xcr0(), ze_caps_thunk(), ze_destroy_thunk(), ze_gemv_block_sparse_f32_stub(), ze_gemv_f32_stub(), ze_memcpy_stub(), and ze_try_create().
Variable Documentation
g_last_err
char g_last_err[256] = "OK" static
Global last-error string buffer (process-wide, owned by this TU).
Definition at line 28 of file ie_device_cuda.cu.
Referenced by ie_cuda_clear_last_error(), ie_cuda_gemv_f32(), ie_cuda_last_error_string(), ie_cuda_set_last_error_cuda(), and ie_cuda_set_last_error_string().