Inference Engine (Clocher): engine/include/ie_metrics.h File Reference
ie_metrics.h File Reference
Public API for runtime metrics (KV cache and memory/RSS sampling).
#include <stdint.h>
Data Structures
struct ie_metrics_t
Snapshot of engine metrics for a measurement interval.
Macros
#define IE_KV_HIT(n) ie_metrics_add_kv_hit((uint64_t)(n))
Cheap inline increment of the KV hit counter.
#define IE_KV_MISS(n) ie_metrics_add_kv_miss((uint64_t)(n))
Cheap inline increment of the KV miss counter.
Typedefs
typedef struct ie_metrics_t ie_metrics_t
Snapshot of engine metrics for a measurement interval.
Functions
void ie_metrics_reset (void)
Reset all metrics accumulators to zero.
void ie_metrics_add_kv_hit (uint64_t n)
Atomically add to the KV hit counter.
void ie_metrics_add_kv_miss (uint64_t n)
Atomically add to the KV miss counter.
void ie_metrics_add_kv (uint64_t hits, uint64_t misses)
Atomically add to both KV counters.
void ie_metrics_snapshot (ie_metrics_t *out, int reset_after)
Copy current counters into out and optionally reset them.
uint32_t ie_metrics_sample_rss_peak (void)
Best-effort sampling of peak RSS (resident set size).
Detailed Description
Public API for runtime metrics (KV cache and memory/RSS sampling).
This header exposes:
Cheap, thread-safe KV cache counters (hits/misses).
A portable best-effort function to sample peak RSS (resident set size).
Typical usage:
Call ie_metrics_reset at the start of a benchmark round.
In hot paths, call IE_KV_HIT / IE_KV_MISS.
At the end, call ie_metrics_snapshot(reset_after=1).
Optionally call ie_metrics_sample_rss_peak() once per run/round to populate RSS numbers for reporting.
Definition in file ie_metrics.h.
Macro Definition Documentation
IE_KV_HIT
#define IE_KV_HIT (n) ie_metrics_add_kv_hit((uint64_t)(n))
Cheap inline increment of the KV hit counter.
Parameters
n Number of hits to add.
Definition at line 84 of file ie_metrics.h.
IE_KV_MISS
#define IE_KV_MISS (n) ie_metrics_add_kv_miss((uint64_t)(n))
Cheap inline increment of the KV miss counter.
Parameters
n Number of misses to add.
Definition at line 92 of file ie_metrics.h.
Typedef Documentation
ie_metrics_t
typedef struct ie_metrics_t ie_metrics_t
Snapshot of engine metrics for a measurement interval.
All fields are monotonic counters accumulated during an interval (typically one benchmark/inference round).
Function Documentation
ie_metrics_add_kv()
void ie_metrics_add_kv (uint64_t hits, uint64_t misses)
Atomically add to both KV counters.
Parameters
hits Hits to add.
misses Misses to add.
Definition at line 158 of file util_metrics.c.
{
   if (hits)   (void)atomic_fetch_add_explicit(&g_kv_hits, hits,  memory_order_relaxed);
   if (misses) (void)atomic_fetch_add_explicit(&g_kv_miss, misses, memory_order_relaxed);
 }
References g_kv_hits, and g_kv_miss.
ie_metrics_add_kv_hit()
void ie_metrics_add_kv_hit (uint64_t n)
Atomically add to the KV hit counter.
Parameters
n Number of hits to add (may be zero).
Definition at line 148 of file util_metrics.c.
{
   if (!n) return;
   (void)atomic_fetch_add_explicit(&g_kv_hits, n, memory_order_relaxed);
 }
References g_kv_hits.
ie_metrics_add_kv_miss()
void ie_metrics_add_kv_miss (uint64_t n)
Atomically add to the KV miss counter.
Parameters
n Number of misses to add (may be zero).
Definition at line 153 of file util_metrics.c.
{
   if (!n) return;
   (void)atomic_fetch_add_explicit(&g_kv_miss, n, memory_order_relaxed);
 }
References g_kv_miss.
ie_metrics_reset()
void ie_metrics_reset (void)
Reset all metrics accumulators to zero.
Postcondition
Subsequent snapshots will report zeros until producers add counts.
@thread_safety Safe; uses C11 atomics.
Definition at line 143 of file util_metrics.c.
{
   atomic_store_explicit(&g_kv_hits, 0, memory_order_relaxed);
   atomic_store_explicit(&g_kv_miss, 0, memory_order_relaxed);
 }
References g_kv_hits, and g_kv_miss.
ie_metrics_sample_rss_peak()
uint32_t ie_metrics_sample_rss_peak (void)
Best-effort sampling of peak RSS (resident set size).
On Linux, prefers reading /proc/self/status (VmHWM). If unavailable, falls back to getrusage(RUSAGE_SELF).ru_maxrss. On non-Linux, only the getrusage fallback is used where available. Returns 0 if unsupported.
Returns
Peak RSS in megabytes (MB), rounded down; 0 if unknown.
Definition at line 181 of file util_metrics.c.
{
   uint32_t best_mib = 0;
 #if defined(__linux__)
   /* 1) Prefer VmHWM (kB) — process peak resident set size. */
   {
     uint64_t kb = 0;
     int rc = read_proc_kb_single("/proc/self/status", "VmHWM:", &kb);
     if (rc == 0) {
       uint32_t mib = kib_to_mib_ceil(kb);
       if (mib > best_mib) best_mib = mib;
       dbg("[RSS] VmHWM: %llu kB -> %u MiB\n",
           (unsigned long long)kb, mib);
     } else {
       dbg("[RSS] VmHWM not found (rc=%d)\n", rc);
     }
   }
   /* 2) Fallback: current VmRSS (kB) as lower bound if HWM is unavailable. */
   if (best_mib == 0) {
     uint64_t kb = 0;
     int rc = read_proc_kb_single("/proc/self/status", "VmRSS:", &kb);
     if (rc == 0) {
       uint32_t mib = kib_to_mib_ceil(kb);
       if (mib > best_mib) best_mib = mib;
       dbg("[RSS] VmRSS: %llu kB -> %u MiB\n",
           (unsigned long long)kb, mib);
     } else {
       dbg("[RSS] VmRSS not found (rc=%d)\n", rc);
     }
   }
   /* 3) Try smaps_rollup Rss: (kB) — often more accurate with mmaps. */
   if (best_mib == 0) {
     uint64_t kb = 0;
     int rc = read_proc_kb_single("/proc/self/smaps_rollup", "Rss:", &kb);
     if (rc == 0) {
       uint32_t mib = kib_to_mib_ceil(kb);
       if (mib > best_mib) best_mib = mib;
       dbg("[RSS] smaps_rollup Rss: %llu kB -> %u MiB\n",
           (unsigned long long)kb, mib);
     } else {
       dbg("[RSS] smaps_rollup Rss not found (rc=%d)\n", rc);
     }
   }
   /* 4) Final fallback: getrusage (Linux ru_maxrss is kB). */
   if (best_mib == 0) {
     struct rusage ru;
     if (getrusage(RUSAGE_SELF, &ru) == 0) {
       uint64_t kb = (uint64_t)ru.ru_maxrss;
       uint32_t mib = kib_to_mib_ceil(kb);
       if (mib > best_mib) best_mib = mib;
       dbg("[RSS] getrusage ru_maxrss: %llu kB -> %u MiB\n",
           (unsigned long long)kb, mib);
     } else {
       dbg("[RSS] getrusage failed: errno=%d\n", errno);
     }
   }
 #elif defined(__APPLE__)
   /* macOS primary: mach_task_basic_info (bytes). */
   {
     mach_task_basic_info info;
     mach_msg_type_number_t count = MACH_TASK_BASIC_INFO_COUNT;
     kern_return_t kr = task_info(mach_task_self(), MACH_TASK_BASIC_INFO,
                                  (task_info_t)&info, &count);
     if (kr == KERN_SUCCESS) {
       /* resident_size_max is peak if supported; otherwise 0. */
       uint64_t bytes = (uint64_t)info.resident_size_max;
       if (bytes == 0) bytes = (uint64_t)info.resident_size; /* at least current */
       uint32_t mib = (uint32_t)((bytes + (1024u*1024u - 1)) / (1024u*1024u));
       if (mib > best_mib) best_mib = mib;
       dbg("[RSS] mach_task_basic_info: %llu bytes -> %u MiB\n",
           (unsigned long long)bytes, mib);
     } else {
       dbg("[RSS] mach task_info failed: kr=%d\n", (int)kr);
     }
   }
   /* Fallback: getrusage (on macOS ru_maxrss is bytes). */
   if (best_mib == 0) {
     struct rusage ru;
     if (getrusage(RUSAGE_SELF, &ru) == 0) {
       uint64_t bytes = (uint64_t)ru.ru_maxrss;
       uint32_t mib = (uint32_t)((bytes + (1024u*1024u - 1)) / (1024u*1024u));
       if (mib > best_mib) best_mib = mib;
       dbg("[RSS] getrusage ru_maxrss(bytes): %llu -> %u MiB\n",
           (unsigned long long)bytes, mib);
     }
   }
 #else
   /* Other OS: try getrusage and assume kB (conservative). */
   {
     struct rusage ru;
     if (getrusage(RUSAGE_SELF, &ru) == 0) {
       uint64_t kb = (uint64_t)ru.ru_maxrss;
       uint32_t mib = kib_to_mib_ceil(kb);
       if (mib > best_mib) best_mib = mib;
       dbg("[RSS] generic getrusage ru_maxrss: %llu kB -> %u MiB\n",
           (unsigned long long)kb, mib);
     }
   }
 #endif
   return best_mib;
 }
References dbg(), kib_to_mib_ceil(), and read_proc_kb_single().
Referenced by main().
ie_metrics_snapshot()
void ie_metrics_snapshot (ie_metrics_t * out, int reset_after)
Copy current counters into out and optionally reset them.
Parameters
[out] out Destination snapshot structure (must not be NULL).
[in] reset_after If non-zero, zeroes accumulators after copying.
Definition at line 163 of file util_metrics.c.
{
   if (!out) return;
   const uint64_t hits = atomic_load_explicit(&g_kv_hits, memory_order_relaxed);
   const uint64_t miss = atomic_load_explicit(&g_kv_miss, memory_order_relaxed);
   out->kv_hits   = hits;
   out->kv_misses = miss;
   if (reset_after) {
     atomic_store_explicit(&g_kv_hits, 0, memory_order_relaxed);
     atomic_store_explicit(&g_kv_miss, 0, memory_order_relaxed);
   }
 }
References g_kv_hits, g_kv_miss, ie_metrics_t::kv_hits, and ie_metrics_t::kv_misses.