Inference Engine (Clocher): engine/src/kernels/ze/ie_kernel_ze.cpp File Reference
ie_kernel_ze.cpp File Reference
#include <level_zero/ze_api.h>
#include <cassert>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <fstream>
#include <sstream>
#include <algorithm>
Macros
#define ZE_GUARD(expr, msg)
ZE guard macro: store message and return negative code on failure.
Typedefs
typedef enum ie_act_kind_e ie_act_kind_t
Activation kinds (must match the kernel’s expectations).
Enumerations
enum ie_act_kind_e { IE_ACT_NONE = 0 , IE_ACT_RELU = 1 , IE_ACT_TANH = 2 }
Activation kinds (must match the kernel’s expectations).
Functions
const char * ie_ze_last_error_string (void)
Get the last error message set by this backend (thread-local).
int ie_ze_launch_gemv_rowwise_f32 (const float *W, const float *x, float *y, int rows, int cols, int ldW, float alpha, float beta)
Row-wise GEMV FP32: y = alpha * W * x + beta * y.
int ie_ze_launch_gemv_bias_act_f32 (const float *W, const float *x, const float *bias, float *y, int rows, int cols, int ldW, float alpha, float beta, ie_act_kind_t act)
Fused GEMV + bias + activation: y = act(alpha*W*x + bias + beta*y).
int ie_ze_launch_vec_tanh_f32 (float *y, const float *x, int n)
Vector tanh: y[i] = tanh(x[i]) for i in [0, n).
int ie_ze_launch_pack_w_blockedk_f32 (float *Wp, const float *W, int rows, int cols, int ldW, int block_k)
Pack W (row-major) into Blocked-K layout into Wp.
static void set_err (const char *s)
Set last error (thread-local); truncates if needed.
static bool read_file (const std::string &path, std::vector< uint8_t > &out)
Read a whole binary file into memory.
static int ensure_ze_ready ()
Ensure Level Zero context, device and immediate command list exist.
static int ensure_module_ready ()
Ensure the SPIR-V module and all kernel handles are created.
static int dalloc (size_t bytes, void **ptr)
Allocate device memory.
static void dfree (void *p)
Free USM pointer if non-null.
static int memcpy_imm (void *dst, const void *src, size_t bytes)
Copy host→device or device→host using immediate command list.
template<typename T >
static ze_result_t set_arg (ze_kernel_handle_t k, uint32_t idx, const T &v)
Helper to set a POD kernel argument.
Variables
static thread_local char g_err [512] = {0}
Thread-local error buffer.
static ze_context_handle_t g_ctx = nullptr
static ze_device_handle_t g_dev = nullptr
static ze_command_queue_handle_t g_q = nullptr
static ze_command_list_handle_t g_cl = nullptr
static ze_module_handle_t g_mod = nullptr
static ze_kernel_handle_t g_k_gemv = nullptr
static ze_kernel_handle_t g_k_gemv_ba = nullptr
static ze_kernel_handle_t g_k_tanh = nullptr
static ze_kernel_handle_t g_k_pack = nullptr
static const char * kDefaultSPVPath = "engine/src/kernels/ze/ie_kernels_ze.spv"
Macro Definition Documentation
ZE_GUARD
#define ZE_GUARD (expr, msg)
Value:
  do {                                                              \
    ze_result_t _st = (expr);                                       \
    if (_st != ZE_RESULT_SUCCESS) {                                 \
      std::ostringstream _oss;                                      \
      _oss << (msg) << " (ze_result=" << (int)_st << ")";           \
      set_err(_oss.str().c_str());                                  \
      return -(int)_st;                                             \
    }                                                               \
  } while (0)
ZE guard macro: store message and return negative code on failure.
Definition at line 164 of file ie_kernel_ze.cpp.
     {                                                              \
    ze_result_t _st = (expr);                                       \
    if (_st != ZE_RESULT_SUCCESS) {                                 \
      std::ostringstream _oss;                                      \
      _oss << (msg) << " (ze_result=" << (int)_st << ")";           \
      set_err(_oss.str().c_str());                                  \
      return -(int)_st;                                             \
    }                                                               \
  } while (0)
Function Documentation
dalloc()
static int dalloc (size_t bytes, void ** ptr) static
Allocate device memory.
Parameters
bytes Size.
ptr Out device pointer.
Returns
0 on success; negative on error.
Definition at line 354 of file ie_kernel_ze.cpp.
{
  ze_device_mem_alloc_desc_t ad = {ZE_STRUCTURE_TYPE_DEVICE_MEM_ALLOC_DESC};
  ad.flags = 0; ad.ordinal = 0;
  ZE_GUARD(zeMemAllocDevice(g_ctx, &ad, bytes, /*alignment*/64, g_dev, ptr),
           "zeMemAllocDevice failed");
  return 0;
}
References g_ctx, g_dev, and ZE_GUARD.
Referenced by ie_ze_launch_gemv_bias_act_f32(), ie_ze_launch_gemv_rowwise_f32(), ie_ze_launch_pack_w_blockedk_f32(), and ie_ze_launch_vec_tanh_f32().
dfree()
static void dfree (void * p) static
Free USM pointer if non-null.
Parameters
p pointer.
Definition at line 366 of file ie_kernel_ze.cpp.
{
  if (p) zeMemFree(g_ctx, p);
}
References g_ctx.
Referenced by ie_ze_launch_gemv_bias_act_f32(), ie_ze_launch_gemv_rowwise_f32(), ie_ze_launch_pack_w_blockedk_f32(), and ie_ze_launch_vec_tanh_f32().
ensure_module_ready()
static int ensure_module_ready () static
Ensure the SPIR-V module and all kernel handles are created.
Returns
0 on success; negative on error.
Definition at line 286 of file ie_kernel_ze.cpp.
{
  if (g_mod && g_k_gemv && g_k_gemv_ba && g_k_tanh && g_k_pack) return 0;
  int rc = ensure_ze_ready();
  if (rc < 0) return rc;
  std::string path;
  if (const char* env = std::getenv("IE_ZE_SPV")) path = env;
  if (path.empty()) path = kDefaultSPVPath;
  std::vector<uint8_t> bin;
  if (!read_file(path, bin)) {
    set_err(("failed to read SPIR-V: " + path).c_str());
    return -1;
  }
  ze_module_desc_t md = {};
  md.stype        = ZE_STRUCTURE_TYPE_MODULE_DESC;
  md.format       = ZE_MODULE_FORMAT_IL_SPIRV;
  md.pInputModule = bin.data();
  md.inputSize    = bin.size();
  md.pBuildFlags  = "";
  ze_module_build_log_handle_t blog = nullptr;
  ze_result_t mrc = zeModuleCreate(g_ctx, g_dev, &md, &g_mod, &blog);
  /* If there is a build log, fetch it on error for diagnostics. */
  if (mrc != ZE_RESULT_SUCCESS) {
    size_t lsz = 0;
    if (blog) zeModuleBuildLogGetString(blog, &lsz, nullptr);
    std::string log;
    if (blog && lsz > 1) {
      log.resize(lsz);
      zeModuleBuildLogGetString(blog, &lsz, log.data());
    }
    if (blog) zeModuleBuildLogDestroy(blog);
    std::ostringstream oss; oss << "zeModuleCreate failed; log: " << log;
    set_err(oss.str().c_str());
    return -(int)mrc;
  }
  if (blog) zeModuleBuildLogDestroy(blog);
  auto mk = [&](const char* name, ze_kernel_handle_t& out,
                uint32_t gx, uint32_t gy, uint32_t gz) -> int {
    ze_kernel_desc_t kd = {ZE_STRUCTURE_TYPE_KERNEL_DESC, nullptr, 0, name};
    ZE_GUARD(zeKernelCreate(g_mod, &kd, &out), "zeKernelCreate failed");
    /* Use fixed group size for predictability (tuned to 256 threads total). */
    ZE_GUARD(zeKernelSetGroupSize(out, gx, gy, gz), "zeKernelSetGroupSize failed");
    return 0;
  };
  /* Names must match ie_kernels_ze.cl */
  ZE_GUARD(mk("gemv_rowwise_f32", g_k_gemv,    256, 1, 1), "mk(gemv_rowwise_f32) failed");
  ZE_GUARD(mk("gemv_bias_act_f32", g_k_gemv_ba, 256, 1, 1), "mk(gemv_bias_act_f32) failed");
  ZE_GUARD(mk("vec_tanh_f32",      g_k_tanh,    256, 1, 1), "mk(vec_tanh_f32) failed");
  ZE_GUARD(mk("pack_w_blockedk_f32", g_k_pack,   32,  8, 1), "mk(pack_w_blockedk_f32) failed");
  return 0;
}
References ensure_ze_ready(), g_ctx, g_dev, g_k_gemv, g_k_gemv_ba, g_k_pack, g_k_tanh, g_mod, kDefaultSPVPath, read_file(), set_err(), and ZE_GUARD.
Referenced by ie_ze_launch_gemv_bias_act_f32(), ie_ze_launch_gemv_rowwise_f32(), ie_ze_launch_pack_w_blockedk_f32(), and ie_ze_launch_vec_tanh_f32().
ensure_ze_ready()
static int ensure_ze_ready () static
Ensure Level Zero context, device and immediate command list exist.
Picks the first GPU device on the first driver found.
Returns
0 on success; negative on error.
Definition at line 215 of file ie_kernel_ze.cpp.
{
  if (g_ctx && g_dev && g_q && g_cl) return 0;
  ZE_GUARD(zeInit(0), "zeInit failed");
  uint32_t nd = 0;
  ZE_GUARD(zeDriverGet(&nd, nullptr), "zeDriverGet(count) failed");
  if (nd == 0) { set_err("no Level Zero drivers found"); return -1; }
  std::vector<ze_driver_handle_t> drivers(nd);
  ZE_GUARD(zeDriverGet(&nd, drivers.data()), "zeDriverGet(list) failed");
  ze_driver_handle_t drv = drivers[0];
  uint32_t ndev = 0;
  ZE_GUARD(zeDeviceGet(drv, &ndev, nullptr), "zeDeviceGet(count) failed");
  if (ndev == 0) { set_err("no Level Zero devices found"); return -1; }
  std::vector<ze_device_handle_t> devs(ndev);
  ZE_GUARD(zeDeviceGet(drv, &ndev, devs.data()), "zeDeviceGet(list) failed");
  /* pick first GPU if possible */
  for (auto d : devs) {
    ze_device_properties_t p = {ZE_STRUCTURE_TYPE_DEVICE_PROPERTIES};
    zeDeviceGetProperties(d, &p);
    if (p.type == ZE_DEVICE_TYPE_GPU) { g_dev = d; break; }
  }
  if (!g_dev) g_dev = devs[0]; /* fallback */
  ze_context_desc_t cdesc = {ZE_STRUCTURE_TYPE_CONTEXT_DESC};
  ZE_GUARD(zeContextCreate(drv, &cdesc, &g_ctx), "zeContextCreate failed");
  /* find a compute queue group ordinal */
  uint32_t ng = 0;
  zeDeviceGetCommandQueueGroupProperties(g_dev, &ng, nullptr);
  std::vector<ze_command_queue_group_properties_t> gps(
      ng, {ZE_STRUCTURE_TYPE_COMMAND_QUEUE_GROUP_PROPERTIES});
  zeDeviceGetCommandQueueGroupProperties(g_dev, &ng, gps.data());
  uint32_t ord = 0;
  for (uint32_t i = 0; i < ng; ++i) {
    if (gps[i].flags & ZE_COMMAND_QUEUE_GROUP_PROPERTY_FLAG_COMPUTE) {
      ord = i; break;
    }
  }
  ze_command_queue_desc_t qd = {
    ZE_STRUCTURE_TYPE_COMMAND_QUEUE_DESC, /* stype            */
    nullptr,                               /* pNext            */
    ord,                                   /* ordinal          */
    0,                                     /* index            */
    ZE_COMMAND_QUEUE_MODE_DEFAULT,
    ZE_COMMAND_QUEUE_PRIORITY_NORMAL
  };
  ZE_GUARD(zeCommandQueueCreate(g_ctx, g_dev, &qd, &g_q), "zeCommandQueueCreate failed");
  /* Immediate command list to reduce submission overhead. */
  ze_command_list_desc_t ld = {
    ZE_STRUCTURE_TYPE_COMMAND_LIST_DESC, nullptr, ord, 0
  };
  ZE_GUARD(zeCommandListCreateImmediate(g_ctx, g_dev, &ld, &g_cl),
           "zeCommandListCreateImmediate failed");
  return 0;
}
References g_cl, g_ctx, g_dev, g_q, set_err(), and ZE_GUARD.
Referenced by ensure_module_ready().
memcpy_imm()
static int memcpy_imm (void * dst, const void * src, size_t bytes) static
Copy host→device or device→host using immediate command list.
Parameters
dst destination pointer.
src source pointer.
bytes size in bytes.
Returns
0 on success; negative on error.
Definition at line 377 of file ie_kernel_ze.cpp.
{
  ZE_GUARD(zeCommandListAppendMemoryCopy(g_cl, dst, src, bytes, nullptr, 0, nullptr),
           "zeCommandListAppendMemoryCopy failed");
  /* Immediate list executes synchronously; no extra sync required. */
  return 0;
}
References g_cl, and ZE_GUARD.
Referenced by ie_ze_launch_gemv_bias_act_f32(), ie_ze_launch_gemv_rowwise_f32(), ie_ze_launch_pack_w_blockedk_f32(), and ie_ze_launch_vec_tanh_f32().
read_file()
static bool read_file (const std::string & path, std::vector< uint8_t > & out) static
Read a whole binary file into memory.
Parameters
path filesystem path.
out vector to fill.
Returns
true on success.
Definition at line 196 of file ie_kernel_ze.cpp.
{
  std::ifstream f(path, std::ios::binary);
  if (!f) return false;
  f.seekg(0, std::ios::end);
  std::streampos sz = f.tellg();
  if (sz <= 0) return false;
  out.resize((size_t)sz);
  f.seekg(0, std::ios::beg);
  f.read(reinterpret_cast<char*>(out.data()), sz);
  return f.good();
}
Referenced by ensure_module_ready().
set_arg()
template<typename T > static ze_result_t set_arg (ze_kernel_handle_t k, uint32_t idx, const T & v) inline static
Helper to set a POD kernel argument.
Definition at line 390 of file ie_kernel_ze.cpp.
{
  return zeKernelSetArgumentValue(k, idx, sizeof(T), &v);
}
Referenced by ie_ze_launch_gemv_bias_act_f32(), ie_ze_launch_gemv_rowwise_f32(), ie_ze_launch_pack_w_blockedk_f32(), and ie_ze_launch_vec_tanh_f32().
set_err()
static void set_err (const char * s) static
Set last error (thread-local); truncates if needed.
Parameters
s Message or NULL to clear.
Definition at line 158 of file ie_kernel_ze.cpp.
{
  if (!s) { g_err[0] = '\0'; return; }
  std::snprintf(g_err, sizeof(g_err), "%s", s);
}
References g_err.
Referenced by ensure_module_ready(), ensure_ze_ready(), ie_ze_launch_gemv_bias_act_f32(), ie_ze_launch_gemv_rowwise_f32(), ie_ze_launch_pack_w_blockedk_f32(), and ie_ze_launch_vec_tanh_f32().
Variable Documentation
g_cl
ze_command_list_handle_t g_cl = nullptr static
Definition at line 180 of file ie_kernel_ze.cpp.
Referenced by ensure_ze_ready(), ie_ze_launch_gemv_bias_act_f32(), ie_ze_launch_gemv_rowwise_f32(), ie_ze_launch_pack_w_blockedk_f32(), ie_ze_launch_vec_tanh_f32(), and memcpy_imm().
g_ctx
ze_context_handle_t g_ctx = nullptr static
Definition at line 177 of file ie_kernel_ze.cpp.
Referenced by dalloc(), dfree(), ensure_module_ready(), and ensure_ze_ready().
g_dev
ze_device_handle_t g_dev = nullptr static
Definition at line 178 of file ie_kernel_ze.cpp.
Referenced by dalloc(), ensure_module_ready(), and ensure_ze_ready().
g_err
thread_local char g_err[512] = {0} static
Thread-local error buffer.
Definition at line 152 of file ie_kernel_ze.cpp.
{0};
Referenced by ie_ze_last_error_string(), and set_err().
g_k_gemv
ze_kernel_handle_t g_k_gemv = nullptr static
Definition at line 183 of file ie_kernel_ze.cpp.
Referenced by ensure_module_ready(), and ie_ze_launch_gemv_rowwise_f32().
g_k_gemv_ba
ze_kernel_handle_t g_k_gemv_ba = nullptr static
Definition at line 184 of file ie_kernel_ze.cpp.
Referenced by ensure_module_ready(), and ie_ze_launch_gemv_bias_act_f32().
g_k_pack
ze_kernel_handle_t g_k_pack = nullptr static
Definition at line 186 of file ie_kernel_ze.cpp.
Referenced by ensure_module_ready(), and ie_ze_launch_pack_w_blockedk_f32().
g_k_tanh
ze_kernel_handle_t g_k_tanh = nullptr static
Definition at line 185 of file ie_kernel_ze.cpp.
Referenced by ensure_module_ready(), and ie_ze_launch_vec_tanh_f32().
g_mod
ze_module_handle_t g_mod = nullptr static
Definition at line 182 of file ie_kernel_ze.cpp.
Referenced by ensure_module_ready().
g_q
ze_command_queue_handle_t g_q = nullptr static
Definition at line 179 of file ie_kernel_ze.cpp.
Referenced by ensure_ze_ready().
kDefaultSPVPath
const char* kDefaultSPVPath = "engine/src/kernels/ze/ie_kernels_ze.spv" static
Definition at line 280 of file ie_kernel_ze.cpp.
Referenced by ensure_module_ready().