Inference Engine (Clocher): engine/include/ie_kv_instrumentation.h File Reference
ie_kv_instrumentation.h File Reference
Lightweight KV cache hit/miss instrumentation for benchmarks.
#include <stdint.h>
#include <stddef.h>
Functions
int ie_kv_begin_round (void)
Initialize KV counters and allocate a token set for the round.
void ie_kv_on_token (uint32_t token)
Report a produced token to the KV tracker.
void ie_kv_finish_round (uint64_t total_tokens, uint64_t *out_hits, uint64_t *out_misses)
Finalize the round and return hit/miss counters.
Detailed Description
Lightweight KV cache hit/miss instrumentation for benchmarks.
This module provides a very small, header-only friendly API used by the CLI and by the engine core to count "KV cache" hits and misses during generation.
Model and intent
We model the KV as a fixed-capacity FIFO set of 32-bit token IDs.
A token is a hit if it is already present in the set; otherwise it's a miss, and the token is inserted (evicting the oldest when full).
Capacity is per-process/round (i.e., per benchmark invocation).
Lifecycle
Call ie_kv_begin_round() exactly once before the first token of a round.
For each produced token, call ie_kv_on_token().
At the end, call ie_kv_finish_round() to obtain the counters and release internal buffers.
The implementation is intentionally simple (single-threaded), deterministic, and has O(capacity) membership checks. This is sufficient to give meaningful hit/miss ratios for benchmarking without pulling complex dependencies.
Definition in file ie_kv_instrumentation.h.
Function Documentation
ie_kv_begin_round()
int ie_kv_begin_round (void)
Initialize KV counters and allocate a token set for the round.
Capacity is read from the environment variable IE_KV_CAP if present; otherwise a default capacity of 4096 tokens is used. Passing this function multiple times resets the state (counters and set) for a new round.
Returns
0 on success; non-zero on allocation failure.
Definition at line 87 of file ie_kv_instrumentation.c.
{
   /* Reset counters and (re)allocate set as needed. */
   const size_t cap = env_size("IE_KV_CAP", 4096); /* default: 4K tokens */
   if (g_kv.slots && g_kv.capacity != cap) {
     free(g_kv.slots);
     g_kv.slots = NULL;
   }
   if (!g_kv.slots) {
     g_kv.slots = (uint32_t *)malloc(sizeof(uint32_t) * cap);
     if (!g_kv.slots) {
       g_kv.capacity = 0;
       g_kv.count = g_kv.head = 0;
       g_kv.hits = g_kv.misses = 0;
       g_kv.ready = 0;
       return -1;
     }
   }
   g_kv.capacity = cap;
   g_kv.count = 0;
   g_kv.head = 0;
   g_kv.hits = 0;
   g_kv.misses = 0;
   g_kv.ready = 1;
   return 0;
 }
References ie_kv_state_t::capacity, ie_kv_state_t::count, env_size(), g_kv, ie_kv_state_t::head, ie_kv_state_t::hits, ie_kv_state_t::misses, ie_kv_state_t::ready, and ie_kv_state_t::slots.
Referenced by main().
ie_kv_finish_round()
void ie_kv_finish_round (uint64_t total_tokens, uint64_t * out_hits, uint64_t * out_misses)
Finalize the round and return hit/miss counters.
If no tokens were reported (counters are both zero) but total_tokens is non-zero, this function conservatively assumes all tokens were misses.
This call also frees any internal buffers allocated by ie_kv_begin_round().
Parameters
total_tokens Total tokens generated in the round (for fallback).
out_hits Output: total hit count (non-NULL).
out_misses Output: total miss count (non-NULL).
Definition at line 123 of file ie_kv_instrumentation.c.
{
   assert(out_hits   != NULL);
   assert(out_misses != NULL);
   if (!g_kv.ready) {
     /* Not initialized: conservative fallback. */
     *out_hits = 0;
     *out_misses = total_tokens;
     return;
   }
   /* Fallback if no tokens were observed but caller claims otherwise. */
   uint64_t hits   = g_kv.hits;
   uint64_t misses = g_kv.misses;
   if ((hits + misses) == 0 && total_tokens > 0) {
     misses = total_tokens;
   }
   *out_hits   = hits;
   *out_misses = misses;
   /* Free the set to keep memory footprint low across short-lived runs. */
   free(g_kv.slots);
   g_kv.slots = NULL;
   g_kv.capacity = g_kv.count = g_kv.head = 0;
   g_kv.hits = g_kv.misses = 0;
   g_kv.ready = 0;
 }
References ie_kv_state_t::capacity, ie_kv_state_t::count, g_kv, ie_kv_state_t::head, ie_kv_state_t::hits, ie_kv_state_t::misses, ie_kv_state_t::ready, and ie_kv_state_t::slots.
Referenced by main().
ie_kv_on_token()
void ie_kv_on_token (uint32_t token)
Report a produced token to the KV tracker.
If the token is already present in the FIFO set, this increments the hit counter. Otherwise it increments miss and inserts the token (evicting the oldest element when the set is full).
Parameters
token 32-bit token identifier generated by the model.
Definition at line 113 of file ie_kv_instrumentation.c.
{
   if (!g_kv.ready || g_kv.capacity == 0) return;
   if (kv_contains(token)) {
     g_kv.hits++;
     return;
   }
   g_kv.misses++;
   kv_insert_fifo(token);
 }
References ie_kv_state_t::capacity, g_kv, ie_kv_state_t::hits, kv_contains(), kv_insert_fifo(), ie_kv_state_t::misses, and ie_kv_state_t::ready.
Referenced by ie_engine_generate().