Inference Engine (Clocher): engine/include/ie_threadpool.h File Reference
ie_threadpool.h File Reference
Minimal thread-pool interface with optional Linux CPU affinity.
#include <stddef.h>
Typedefs
typedef struct ie_threadpool ie_threadpool_t
Opaque thread-pool handle.
typedef void(* ie_tp_for_body_fn) (void *ctx, unsigned start, unsigned end)
Function type for a parallel-for body over a half-open range [start, end).
Functions
ie_threadpool_t * ie_tp_create (unsigned nth, const char *affinity)
Create a thread pool.
void ie_tp_destroy (ie_threadpool_t *tp)
Destroy a thread pool and join all worker threads.
void ie_tp_parallel_for (ie_threadpool_t *tp, unsigned n, unsigned grainsize, ie_tp_for_body_fn body_fn, void *ctx)
Execute a synchronous parallel-for over n iterations.
Detailed Description
Minimal thread-pool interface with optional Linux CPU affinity.
This API purposely keeps the contract small:
Create / destroy a pool.
Run a synchronous parallel-for with contiguous partition.
Notes:
ie_tp_parallel_for() is synchronous; it returns when all work is done.
If tp == NULL or the pool has only one worker, it runs single-threaded.
Affinity is applied only on Linux when the environment variable IE_TP_USE_AFFINITY=1 is set at runtime.
Definition in file ie_threadpool.h.
Typedef Documentation
ie_threadpool_t
typedef struct ie_threadpool ie_threadpool_t
Opaque thread-pool handle.
Definition at line 1 of file ie_threadpool.h.
ie_tp_for_body_fn
typedef void(* ie_tp_for_body_fn) (void *ctx, unsigned start, unsigned end)
Function type for a parallel-for body over a half-open range [start, end).
The implementation guarantees that start < end for non-empty subranges and that the union of all issued subranges exactly covers [0, n).
Parameters
ctx User context pointer passed through from ie_tp_parallel_for().
start Inclusive start index for this worker.
end Exclusive end index for this worker.
Definition at line 56 of file ie_threadpool.h.
Function Documentation
ie_tp_create()
ie_threadpool_t* ie_tp_create (unsigned nth, const char * affinity)
Create a thread pool.
Parameters
nth Desired number of worker threads (>= 1). Values < 1 are clamped to 1.
affinity Optional policy string: "auto", "compact", or "scatter". The value is advisory; non-Linux builds ignore affinity.
Returns
Newly created thread-pool handle, or NULL on allocation failure.
Definition at line 115 of file thread_pool.c.
{
   if (nth < 1) nth = 1;
   struct ie_threadpool *tp = (struct ie_threadpool*)calloc(1, sizeof(*tp));
   if (!tp) return NULL;
   tp->nth = nth;
   tp->affinity = (affinity && *affinity) ? affinity : "auto";
 #ifdef __linux__
   const char *env = getenv("IE_TP_USE_AFFINITY");
   tp->use_affinity = (env && strcmp(env, "1") == 0) ? 1 : 0;
 #else
   tp->use_affinity = 0;
 #endif
   /* Spawn long-lived idle workers (not strictly required for the baseline). */
   tp->threads = (pthread_t*)calloc(nth, sizeof(pthread_t));
   if (!tp->threads) { free(tp); return NULL; }
   for (unsigned i = 0; i < nth; ++i) {
     ie_worker_arg_t *wa = (ie_worker_arg_t*)malloc(sizeof(*wa));
     if (!wa) continue;
     wa->tp = tp; wa->tidx = i;
     if (pthread_create(&tp->threads[i], NULL, ie_worker_main, wa) != 0) {
       free(wa);
     }
   }
   return (ie_threadpool_t*)tp;
 }
References ie_threadpool::affinity, ie_worker_main(), ie_threadpool::nth, ie_threadpool::threads, ie_worker_arg_t::tidx, ie_worker_arg_t::tp, and ie_threadpool::use_affinity.
Referenced by main().
ie_tp_destroy()
void ie_tp_destroy (ie_threadpool_t * tp)
Destroy a thread pool and join all worker threads.
Parameters
tp Thread-pool handle (NULL allowed; no-op).
Definition at line 146 of file thread_pool.c.
{
   if (!h) return;
   struct ie_threadpool *tp = (struct ie_threadpool*)h;
   if (tp->threads) {
     for (unsigned i = 0; i < tp->nth; ++i) {
       if (tp->threads[i]) pthread_join(tp->threads[i], NULL);
     }
     free(tp->threads);
   }
   free(tp);
 }
References ie_threadpool::nth, and ie_threadpool::threads.
Referenced by main().
ie_tp_parallel_for()
void ie_tp_parallel_for (ie_threadpool_t * tp, unsigned n, unsigned grainsize, ie_tp_for_body_fn body_fn, void * ctx)
Execute a synchronous parallel-for over n iterations.
The iteration space [0, n) is partitioned into contiguous chunks. If grainsize > 0, each chunk will be at least grainsize iterations (except possibly the last). If grainsize == 0, the function partitions the space as evenly as possible across the pool's workers.
On non-Linux systems (or when IE_TP_USE_AFFINITY != 1), no CPU affinity is applied. On Linux with IE_TP_USE_AFFINITY=1, worker threads may bind to specific CPUs using the policy provided at creation ("auto"/"compact"/"scatter").
Parameters
tp Thread-pool handle (may be NULL for single-threaded).
n Number of iterations in the global range [0, n).
grainsize Minimum chunk size (use 0 for auto).
body_fn Function called for each chunk.
ctx Opaque user pointer passed to body_fn.
Definition at line 194 of file thread_pool.c.
{
   if (n == 0 || !body_fn) return;
   /* Preferred worker count and affinity policy for mapping. */
   unsigned nth_pref = 1;
   const char *aff = "auto";
   int use_aff = 0;
   if (h) {
     struct ie_threadpool *tp = (struct ie_threadpool*)h;
     nth_pref = tp->nth ? tp->nth : 1u;
     aff = tp->affinity ? tp->affinity : "auto";
     use_aff = tp->use_affinity;
   }
   if (nth_pref <= 1) {
     body_fn(ctx, 0u, n);
     return;
   }
   /* Determine chunk size and total number of chunks. */
   unsigned min_chunk = (grainsize > 0 ? grainsize : (n + nth_pref - 1) / nth_pref);
   if (min_chunk == 0) min_chunk = 1;
   unsigned nchunks = (n + min_chunk - 1) / min_chunk;
   /* Launch one task thread per chunk to guarantee full coverage. */
   pthread_t *ths = (pthread_t*)calloc(nchunks, sizeof(pthread_t));
   if (!ths) {
     /* Fallback: single-threaded if allocation fails. */
     body_fn(ctx, 0u, n);
     return;
   }
   for (unsigned c = 0; c < nchunks; ++c) {
     unsigned start = c * min_chunk;
     unsigned end   = start + min_chunk;
     if (start >= n) { ths[c] = (pthread_t)0; continue; }
     if (end > n) end = n;
     ie_task_arg_t *ta = (ie_task_arg_t*)malloc(sizeof(*ta));
     if (!ta) { ths[c] = (pthread_t)0; continue; }
     /* Map chunk index to a virtual worker index for affinity purposes. */
     ta->affinity  = aff;
     ta->use_affinity = use_aff;
     ta->nth_map   = nth_pref;
     ta->tidx_map  = (nth_pref ? (c % nth_pref) : 0u);
     ta->start     = start;
     ta->end       = end;
     ta->body      = body_fn;
     ta->ctx       = ctx;
     if (pthread_create(&ths[c], NULL, ie_task_main, ta) != 0) {
       free(ta);
       ths[c] = (pthread_t)0;
     }
   }
   for (unsigned c = 0; c < nchunks; ++c) {
     if (ths[c]) pthread_join(ths[c], NULL);
   }
   free(ths);
 }
References ie_threadpool::affinity, ie_task_arg_t::affinity, ie_task_arg_t::body, ie_task_arg_t::ctx, ie_task_arg_t::end, ie_task_main(), ie_threadpool::nth, ie_task_arg_t::nth_map, ie_task_arg_t::start, ie_task_arg_t::tidx_map, ie_threadpool::use_affinity, and ie_task_arg_t::use_affinity.
Referenced by main().