Inference Engine (Clocher): engine/include/ie_floatx.h File Reference
ie_floatx.h File Reference
FP32↔BF16/FP16 conversion helpers (vector forms).
#include <stddef.h>
#include <stdint.h>
Functions
void ie_fp32_to_bf16 (const float *in, uint16_t *out, size_t n)
Convert an array of float (FP32) to bfloat16 (BF16).
void ie_bf16_to_fp32 (const uint16_t *in, float *out, size_t n)
Convert an array of bfloat16 (BF16) to float (FP32).
void ie_fp32_to_fp16 (const float *in, uint16_t *out, size_t n)
Convert an array of float (FP32) to IEEE half (FP16).
void ie_fp16_to_fp32 (const uint16_t *in, float *out, size_t n)
Convert an array of IEEE half (FP16) to float (FP32).
Detailed Description
FP32↔BF16/FP16 conversion helpers (vector forms).
All routines are pure and do not allocate. They operate on contiguous arrays. Rounding:
FP32→BF16 uses round-to-nearest-even (ties to even).
FP32→FP16 uses IEEE 754 round-to-nearest-even; infinities/NaNs preserved.
Definition in file ie_floatx.h.
Function Documentation
ie_bf16_to_fp32()
void ie_bf16_to_fp32 (const uint16_t * in, float * out, size_t n)
Convert an array of bfloat16 (BF16) to float (FP32).
Parameters
in Pointer to BF16 input array of length n (uint16_t per elem).
out Pointer to FP32 output array of length n.
n Number of elements to convert.
Convert an array of bfloat16 (BF16) to float (FP32).
Parameters
in BF16 input array (uint16_t per element).
out FP32 output array.
n Number of elements.
Definition at line 42 of file floatx.c.
{
  if (!in || !out || n == 0) return;
  for (size_t i = 0; i < n; ++i) {
    union { uint32_t u; float f; } v;
    v.u = ((uint32_t)in[i]) << 16;
    out[i] = v.f;
  }
}
References ie_gemv_rowwise_f32_kernel().
ie_fp16_to_fp32()
void ie_fp16_to_fp32 (const uint16_t * in, float * out, size_t n)
Convert an array of IEEE half (FP16) to float (FP32).
Parameters
in Pointer to FP16 input array of length n (uint16_t per elem).
out Pointer to FP32 output array of length n.
n Number of elements to convert.
Convert an array of IEEE half (FP16) to float (FP32).
Parameters
in FP16 input array (uint16_t per element).
out FP32 output array.
n Number of elements.
Definition at line 120 of file floatx.c.
{
  if (!in || !out || n == 0) return;
  for (size_t i = 0; i < n; ++i) {
    uint16_t h = in[i];
    uint32_t sign = (h >> 15) & 0x1u;
    uint32_t exp  = (h >> 10) & 0x1Fu;
    uint32_t frac = h & 0x3FFu;
    uint32_t out_sign = sign << 31;
    uint32_t out_exp, out_frac;
    if (exp == 0) {
      if (frac == 0) {
        out_exp = 0;
        out_frac = 0;
      } else {
        /* subnormal -> normalize */
        int e = -14;
        uint32_t f = frac;
        while ((f & 0x400u) == 0) { f <<= 1; e--; }
        f &= 0x3FFu;
        out_exp  = (uint32_t)(e + 127) << 23;
        out_frac = f << 13;
      }
    } else if (exp == 31) {
      out_exp  = 0xFFu << 23;
      out_frac = (frac ? (frac << 13) : 0);
    } else {
      out_exp  = (uint32_t)(exp - 15 + 127) << 23;
      out_frac = frac << 13;
    }
    union { uint32_t u; float f; } v = { .u = out_sign | out_exp | out_frac };
    out[i] = v.f;
  }
}
References ie_gemv_rowwise_f32_kernel().
ie_fp32_to_bf16()
void ie_fp32_to_bf16 (const float * in, uint16_t * out, size_t n)
Convert an array of float (FP32) to bfloat16 (BF16).
Parameters
in Pointer to FP32 input array of length n.
out Pointer to BF16 output array of length n (uint16_t per elem).
n Number of elements to convert.
Convert an array of float (FP32) to bfloat16 (BF16).
Parameters
in FP32 input array.
out BF16 output array (uint16_t per element).
n Number of elements.
Definition at line 20 of file floatx.c.
{
  if (!in || !out || n == 0) return;
  for (size_t i = 0; i < n; ++i) {
    union { float f; uint32_t u; } v = { .f = in[i] };
    uint32_t x = v.u;
    /* Round-to-nearest-even on the lower 16 bits. */
    uint32_t lsb = (x >> 16) & 1u;
    uint32_t rounding_bias = 0x7FFFu + lsb;
    x += rounding_bias;
    out[i] = (uint16_t)(x >> 16);
  }
}
References ie_gemv_rowwise_f32_kernel().
ie_fp32_to_fp16()
void ie_fp32_to_fp16 (const float * in, uint16_t * out, size_t n)
Convert an array of float (FP32) to IEEE half (FP16).
Parameters
in Pointer to FP32 input array of length n.
out Pointer to FP16 output array of length n (uint16_t per elem).
n Number of elements to convert.
Convert an array of float (FP32) to IEEE half (FP16).
Parameters
in FP32 input array.
out FP16 output array (uint16_t per element).
n Number of elements.
Definition at line 62 of file floatx.c.
{
  if (!in || !out || n == 0) return;
  for (size_t i = 0; i < n; ++i) {
    union { float f; uint32_t u; } v = { .f = in[i] };
    uint32_t x = v.u;
    uint32_t sign = (x >> 31) & 0x1u;
    int32_t  exp  = (int32_t)((x >> 23) & 0xFFu) - 127;   /* unbiased exp */
    uint32_t frac = x & 0x7FFFFFu;                        /* 23 bits */
    uint16_t h;
    if (exp == 128) { /* Inf / NaN */
      h = (uint16_t)((sign << 15) | 0x7C00u | (frac ? 0x200u : 0));
    } else if (exp > 15) { /* Overflow -> Inf */
      h = (uint16_t)((sign << 15) | 0x7C00u);
    } else if (exp >= -14) { /* Normalized half */
      /* Put implicit leading 1 back and round to 10 bits. */
      uint32_t mant = (frac | 0x800000u); /* 24 bits */
      int shift = 13 - exp;               /* align to 10-bit mantissa */
      uint32_t rounding = (shift > 0) ? ((1u << (shift - 1)) - 1u) : 0;
      uint32_t half_mant = (shift > 0) ? ((mant + rounding + ((mant >> shift) & 1u)) >> shift)
                                       : (mant << (-shift));
      if (half_mant & 0x400u) { /* mantissa overflow after rounding */
        half_mant >>= 1;
        exp += 1;
      }
      if (exp > 15) { /* overflow to Inf */
        h = (uint16_t)((sign << 15) | 0x7C00u);
      } else {
        uint16_t he = (uint16_t)((exp + 15) & 0x1Fu);
        h = (uint16_t)((sign << 15) | (he << 10) | (half_mant & 0x3FFu));
      }
    } else if (exp >= -24) { /* Subnormal half */
      uint32_t mant = (frac | 0x800000u);
      int rshift = (-14 - exp) + 1; /* +1 to position for subnormal */
      uint32_t sub = mant >> (rshift + 13); /* to 10 bits */
      /* round-to-nearest-even */
      uint32_t rem = mant & ((1u << (rshift + 13)) - 1u);
      uint32_t halfway = 1u << (rshift + 12);
      if (rem > halfway || (rem == halfway && (sub & 1u))) sub++;
      h = (uint16_t)((sign << 15) | (sub & 0x3FFu));
    } else {
      /* Underflow -> signed zero */
      h = (uint16_t)(sign << 15);
    }
    out[i] = h;
  }
}
References ie_gemv_rowwise_f32_kernel().