Inference Engine (Clocher): engine/include/ie_io.h File Reference
ie_io.h File Reference
Public I/O interfaces for model artifacts and lightweight tooling.
#include <stddef.h>
#include <stdint.h>
Data Structures
struct ie_weights_s
Descriptor for an opened IEBIN v1 model.
struct ie_vocab_s
Minimal vocabulary descriptor.
Macros
#define _POSIX_C_SOURCE 200809L
Typedefs
typedef enum ie_io_status_e ie_io_status_t
typedef struct ie_weights_s ie_weights_t
typedef struct ie_vocab_s ie_vocab_t
Enumerations
enum ie_io_status_e {
IE_IO_OK = 0 , IE_IO_ERR_ARGS = -1 , IE_IO_ERR_JSON = -2 , IE_IO_ERR_BIN_UNSPEC = -3 ,
IE_IO_ERR_STAT = -4 , IE_IO_ERR_OPEN = -5 , IE_IO_ERR_READ = -6 , IE_IO_ERR_ALLOC = -7 ,
IE_IO_ERR_OOM = IE_IO_ERR_ALLOC , IE_IO_ERR_DECODE = -8
}
Status codes returned by I/O and artifact-loading helpers.
Functions
int ie_weights_open (const char *json_path, const char *bin_path, ie_weights_t *out)
Open and parse an IEBIN v1 model description.
int ie_weights_touch (const ie_weights_t *w)
Touch the weights binary to verify readability and warm OS caches.
void ie_weights_close (ie_weights_t *w)
Close an opened weights descriptor.
int ie_vocab_load (const char *vocab_path, ie_vocab_t *out)
Load a vocabulary file or fall back to a stub.
int ie_tok_encode (const ie_vocab_t *v, const char *text, uint32_t *ids, uint32_t *out_count)
Encode UTF-8 text into token IDs (stub implementation).
int ie_tok_decode (const ie_vocab_t *v, const uint32_t *ids, uint32_t count, char *out, size_t out_sz)
Decode token IDs into a printable placeholder string.
void ie_vocab_free (ie_vocab_t *v)
Release vocabulary resources.
Detailed Description
Public I/O interfaces for model artifacts and lightweight tooling.
This header defines the only stable public interface for:
IEBIN v1 weight loading (model.ie.json + model.ie.bin)
Optional deduplicated-weight artifact handling
INT4 metadata inspection helpers
Lightweight tokenizer / vocabulary helpers used by tests and harnesses
Design constraints
No heap ownership is exposed to callers.
All descriptors are POD structs suitable for stack allocation.
Cleanup is deterministic and idempotent.
No third-party dependencies (no JSON libraries).
What this header deliberately does NOT provide
No tensor lookup by name (handled by tensor_map).
No inference-time APIs.
No HuggingFace tokenizer (handled by tokenizer_hf).
This file is part of Path 2 (real inference) but remains usable by diagnostic tools, benchmarks, and CI without CUDA or inference enabled.
Definition in file ie_io.h.
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 36 of file ie_io.h.
Typedef Documentation
ie_io_status_t
typedef enum ie_io_status_e ie_io_status_t
ie_vocab_t
typedef struct ie_vocab_s ie_vocab_t
ie_weights_t
typedef struct ie_weights_s ie_weights_t
Enumeration Type Documentation
ie_io_status_e
enum ie_io_status_e
Status codes returned by I/O and artifact-loading helpers.
All non-zero values indicate failure. The categories are stable and suitable for:
CLI diagnostics
benchmark harness error reporting
Implementations may set errno for OS-level failures, but this is not guaranteed for every failure mode.
Enumerator
IE_IO_OK
Success.
IE_IO_ERR_ARGS
Invalid arguments.
IE_IO_ERR_JSON
JSON parse failure or missing required fields.
IE_IO_ERR_BIN_UNSPEC
Binary path unspecified and not inferable.
IE_IO_ERR_STAT
stat(2) failure or invalid file metadata.
IE_IO_ERR_OPEN
open(2) failure.
IE_IO_ERR_READ
read(2) failure or short read.
IE_IO_ERR_ALLOC
Memory allocation failure.
IE_IO_ERR_OOM
Alias for older/newer code expecting OOM name.
IE_IO_ERR_DECODE
Decode failure (corrupt or incompatible data).
Definition at line 63 of file ie_io.h.
{
  IE_IO_OK = 0,
  IE_IO_ERR_ARGS = -1,
  IE_IO_ERR_JSON = -2,
  IE_IO_ERR_BIN_UNSPEC = -3,
  IE_IO_ERR_STAT = -4,
  IE_IO_ERR_OPEN = -5,
  IE_IO_ERR_READ = -6,
  IE_IO_ERR_ALLOC = -7,
  IE_IO_ERR_OOM = IE_IO_ERR_ALLOC,
  IE_IO_ERR_DECODE = -8
} ie_io_status_t;
Function Documentation
ie_tok_decode()
int ie_tok_decode (const ie_vocab_t * v, const uint32_t * ids, uint32_t count, char * out, size_t out_sz)
Decode token IDs into a printable placeholder string.
Produces a deterministic, human-readable representation for diagnostics.
Parameters
v Vocabulary descriptor.
ids Token ID array.
count Number of token IDs.
out Output buffer.
out_sz Output buffer capacity in bytes.
Returns
0 on success, negative on error.
Decode token IDs into a printable placeholder string.
Output format:
"T<ID0> T<ID1> ... T<IDn>" (space-separated)
This is intended for unit tests and harness debugging, not for real model text.
Parameters
v Loaded vocabulary descriptor (unused by this implementation).
ids Array of token IDs (may be NULL when count == 0).
count Number of IDs.
out Output buffer (must not be NULL).
out_sz Capacity of out in bytes (must be > 0).
Return values
0 Success.
-1 Invalid arguments.
-2 Output buffer too small or formatting truncated.
Definition at line 357 of file tokenizer.c.
{
  (void)v;
  if (!out || out_sz == 0) {
    ie_log_error("ie_tok_decode: bad args (out=%p out_sz=%zu)", (void *)out, out_sz);
    return -1;
  }
  const int verbose = tok_env_flag_("IE_TOKENIZER_VERBOSE", 0);
  /* Handle empty sequence. */
  if (!ids || count == 0) {
    out[0] = '\0';
    if (verbose) ie_log_info("ie_tok_decode: empty input");
    return 0;
  }
  /* Conservative sizing: worst case "T4294967295 " per token + NUL. */
  const size_t worst_per = sizeof("T4294967295 ") - 1; /* 12 bytes */
  const size_t worst = (size_t)count * worst_per + 1;
  if (out_sz < worst) {
    ie_log_error("ie_tok_decode: output buffer too small (count=%" PRIu32 " out_sz=%zu need_at_least=%zu)",
                 count,
                 out_sz,
                 worst);
    return -2;
  }
  char *p = out;
  size_t rem = out_sz;
  for (uint32_t i = 0; i < count; ++i) {
    const int n = (i == 0)
      ? snprintf(p, rem, "T%u", (unsigned)ids[i])
      : snprintf(p, rem, " T%u", (unsigned)ids[i]);
    if (n < 0 || (size_t)n >= rem) {
      ie_log_error("ie_tok_decode: snprintf failed/truncated (i=%" PRIu32 " rem=%zu n=%d)", i, rem, n);
      return -2;
    }
    p += (size_t)n;
    rem -= (size_t)n;
  }
  if (rem == 0) {
    ie_log_error("ie_tok_decode: no space for NUL terminator (count=%" PRIu32 " out_sz=%zu)", count, out_sz);
    return -2;
  }
  *p = '\0';
  if (verbose) tok_log_preview_("ie_tok_decode output", out);
  return 0;
}
References ie_log_error(), ie_log_info(), tok_env_flag_(), and tok_log_preview_().
Referenced by main().
ie_tok_encode()
int ie_tok_encode (const ie_vocab_t * v, const char * text, uint32_t * ids, uint32_t * out_count)
Encode UTF-8 text into token IDs (stub implementation).
This tokenizer:
splits on ASCII whitespace,
hashes tokens to stable integer IDs.
It is not compatible with BPE or HF tokenizers and must never be used for real inference.
Parameters
v Vocabulary descriptor.
text NUL-terminated UTF-8 input.
ids Output buffer, or NULL for size-only query.
out_count In: capacity; Out: tokens written or required.
Returns
0 on success, negative on error.
Encode UTF-8 text into token IDs (stub implementation).
Tokenization rule: split on one or more ASCII whitespace characters. Empty tokens are never produced.
Size-only mode:
Pass ids == NULL to receive the required token count in out_count.
Parameters
v Loaded vocabulary descriptor (unused by this implementation).
text NUL-terminated UTF-8 string (must not be NULL).
ids Output buffer (or NULL for size query).
out_count In: capacity of ids when ids != NULL. Out: number of tokens written (or needed when ids == NULL).
Return values
0 Success.
-1 Invalid arguments.
-2 Insufficient capacity when ids != NULL.
Definition at line 266 of file tokenizer.c.
{
  (void)v;
  if (!text || !out_count) {
    ie_log_error("ie_tok_encode: bad args (text=%p out_count=%p)", (const void *)text, (void *)out_count);
    return -1;
  }
  const int verbose = tok_env_flag_("IE_TOKENIZER_VERBOSE", 0);
  if (verbose) tok_log_preview_("ie_tok_encode input", text);
  const unsigned char *s = (const unsigned char *)text;
  const size_t L = strlen(text);
  uint32_t needed = 0;
  /* First pass: count tokens. */
  size_t i = 0;
  while (i < L) {
    while (i < L && is_space_byte_(s[i])) ++i;
    if (i >= L) break;
    size_t start = i;
    while (i < L && !is_space_byte_(s[i])) ++i;
    if (i > start) ++needed;
  }
  if (!ids) {
    *out_count = needed;
    if (verbose) {
      ie_log_info("ie_tok_encode: size-query result needed=%" PRIu32, needed);
    }
    return 0;
  }
  /* Second pass: produce IDs; respect capacity in *out_count. */
  const uint32_t cap = *out_count;
  uint32_t wrote = 0;
  i = 0;
  while (i < L && wrote < cap) {
    while (i < L && is_space_byte_(s[i])) ++i;
    if (i >= L) break;
    size_t start = i;
    while (i < L && !is_space_byte_(s[i])) ++i;
    const size_t tok_len = i - start;
    if (tok_len > 0) {
      const uint32_t h = fnv1a_32_(s + start, tok_len);
      ids[wrote++] = clamp_to_pos31_(h);
    }
  }
  *out_count = wrote;
  if (wrote != needed) {
    ie_log_error("ie_tok_encode: insufficient capacity (needed=%" PRIu32 " cap=%" PRIu32 " wrote=%" PRIu32 ")",
                 needed,
                 cap,
                 wrote);
    return -2;
  }
  if (verbose) {
    ie_log_info("ie_tok_encode: ok (tokens=%" PRIu32 ")", wrote);
  }
  return 0;
}
References clamp_to_pos31_(), fnv1a_32_(), ie_log_error(), ie_log_info(), is_space_byte_(), tok_env_flag_(), and tok_log_preview_().
Referenced by main().
ie_vocab_free()
void ie_vocab_free (ie_vocab_t * v)
Release vocabulary resources.
Currently a no-op; present for API symmetry and future extensibility.
Parameters
v Vocabulary descriptor (may be NULL).
Release vocabulary resources.
This tokenizer implementation does not allocate dynamic resources for the vocab. This function is kept for API symmetry and future expansion.
Parameters
v Vocabulary handle (may be NULL).
Definition at line 239 of file tokenizer.c.
{
  (void)v;
}
ie_vocab_load()
int ie_vocab_load (const char * vocab_path, ie_vocab_t * out)
Load a vocabulary file or fall back to a stub.
If vocab_path is NULL or unreadable, a deterministic stub vocabulary is provided to keep tests and benchmarks operational.
Parameters
vocab_path Optional path to vocabulary file.
out Output vocabulary descriptor.
Returns
0 on success, negative on unrecoverable failure.
Load a vocabulary file or fall back to a stub.
This implementation does not parse a full tokenizer model. It only attempts a best-effort scan for a JSON-like field "vocabSize": <int> in the first few KB of the file.
If the file is missing/unreadable/unparsable, a deterministic stub value is returned to keep tests stable.
Parameters
vocab_path Path to a vocabulary file (may be NULL or empty).
out Output vocabulary (must not be NULL).
Return values
0 Success (including stub fallback).
-1 Invalid arguments.
Definition at line 176 of file tokenizer.c.
{
  if (!out) {
    ie_log_error("ie_vocab_load: bad args (out=NULL)");
    return -1;
  }
  /* Default stub value if anything goes wrong. */
  out->vocab_size = 50000;
  if (!vocab_path || !*vocab_path) {
    ie_log_info("ie_vocab_load: no path provided; using stub vocab_size=%d", out->vocab_size);
    return 0;
  }
  FILE *f = fopen(vocab_path, "rb");
  if (!f) {
    ie_log_info("ie_vocab_load: cannot open \"%s\" (errno=%d: %s); using stub vocab_size=%d",
                vocab_path,
                errno,
                strerror(errno),
                out->vocab_size);
    return 0;
  }
  /* Read a small prefix to try and find "vocabSize". */
  char buf[4096];
  size_t n = fread(buf, 1, sizeof(buf) - 1, f);
  fclose(f);
  buf[n] = '\0';
  /* Very relaxed scan for a number after "vocabSize". */
  const char *key = "vocabSize";
  char *hit = strstr(buf, key);
  if (hit) {
    char *p = hit + (int)strlen(key);
    while (*p && (*p == ' ' || *p == '\t' || *p == '"' || *p == '\'' || *p == ':')) ++p;
    long val = 0;
    if (sscanf(p, "%ld", &val) == 1 && val > 0 && val < 100000000L) {
      out->vocab_size = (int)val;
      ie_log_info("ie_vocab_load: parsed vocab_size=%d from \"%s\"", out->vocab_size, vocab_path);
      return 0;
    }
    ie_log_info("ie_vocab_load: found key \"%s\" but failed to parse number; using stub vocab_size=%d",
                key,
                out->vocab_size);
    return 0;
  }
  ie_log_info("ie_vocab_load: key \"%s\" not found; using stub vocab_size=%d", key, out->vocab_size);
  return 0;
}
References ie_log_error(), and ie_log_info().
Referenced by main().
ie_weights_close()
void ie_weights_close (ie_weights_t * w)
Close an opened weights descriptor.
This function releases any optional deduplication handles. It is idempotent and safe to call on zero-initialized or partially initialized descriptors.
Parameters
w Descriptor to close (may be NULL).
Close an opened weights descriptor.
This function is idempotent and safe to call on partially initialized structures. It does not unlink or delete any files; it only releases in-memory handles.
Parameters
w Weights descriptor (may be NULL).
Definition at line 1356 of file weights.c.
{
  if (!w) return;
  WLOGD("ie_weights_close: begin loaded=%d is_dedup=%d", w->loaded, w->is_dedup);
#if (IE_WEIGHTS_HAS_DEDUP_FIELDS == 1)
  if (w->is_dedup && w->dedup_handle) {
    ie_weights_dedup_t *dh = (ie_weights_dedup_t *)w->dedup_handle;
    ie_weights_dedup_close(&dh);
    w->dedup_handle = NULL;
    w->is_dedup = 0;
    WLOGD("ie_weights_close: dedup handle released");
  }
#endif
}
References ie_weights_s::dedup_handle, ie_weights_dedup_close(), ie_weights_s::is_dedup, ie_weights_s::loaded, and WLOGD.
Referenced by ie_engine_create(), ie_engine_destroy(), main(), main(), and open_and_touch().
ie_weights_open()
int ie_weights_open (const char * json_path, const char * bin_path, ie_weights_t * out)
Open and parse an IEBIN v1 model description.
On success:
out->loaded is set to non-zero,
JSON and BIN paths are resolved and stored,
basic metadata (dtype, version, size) is available for diagnostics.
Optional deduplication artifacts are opened if enabled via environment flags.
Parameters
json_path Path to model.ie.json (must be readable).
bin_path Optional override for model.ie.bin; may be NULL.
out Output descriptor (written on success).
Returns
IE_IO_OK on success, negative ie_io_status_t otherwise.
This function:
reads model.ie.json,
parses minimal metadata (version, dtype),
resolves the path to model.ie.bin using overrides and schema variants,
validates the weights binary size via stat(2),
optionally opens dedup artifacts when enabled.
In all error cases, the output structure is left in a safe-to-close state.
Parameters
json_path Path to model.ie.json.
bin_path Optional override for the binary path (may be NULL).
out Output weights descriptor.
Returns
IE_IO_OK on success; negative ie_io_status_t on failure.
Definition at line 988 of file weights.c.
{
  if (!out) return IE_IO_ERR_ARGS;
  memset(out, 0, sizeof(*out));
  if (!json_path || !*json_path) return IE_IO_ERR_ARGS;
  cpyz(out->json_path, sizeof(out->json_path), json_path);
  WLOGI("ie_weights_open: begin json_path='%s' bin_override='%s'", json_path,
        (bin_path && *bin_path) ? bin_path : "");
  char *jbuf = NULL;
  size_t jlen = 0;
  if (read_all_text(json_path, &jbuf, &jlen) != 0 || !jbuf || jlen == 0) {
    WLOGE("ie_weights_open: failed to read json (path='%s')", json_path);
    return IE_IO_ERR_JSON;
  }
  WLOGD("ie_weights_open: loaded json bytes=%zu", jlen);
  int ver = 0;
  int found_ver = scan_json_key_int(jbuf, "version", &ver);
  if (ver <= 0) ver = 1;
  out->version = ver;
  char dtype[16];
  dtype[0] = '\0';
  (void)scan_json_key_string(jbuf, "dtype", dtype, sizeof(dtype));
  if (dtype[0] == '\0') cpyz(dtype, sizeof(dtype), "float32");
  cpyz(out->dtype, sizeof(out->dtype), dtype);
  WLOGI("ie_weights_open: parsed version=%d (found=%d) dtype='%s'", out->version, found_ver,
        out->dtype);
  char resolved_bin[512];
  resolved_bin[0] = '\0';
  /* Priority order:
   *  1) explicit bin_path parameter
   *  2) IE_WEIGHTS_BIN env override
   *  3) JSON keys (bin / weights_bin / nested weights{bin} / iebin{bin})
   *  4) fallback: sibling 'model.ie.bin' next to json_path
   */
  if (bin_path && *bin_path) {
    cpyz(resolved_bin, sizeof(resolved_bin), bin_path);
    WLOGI("ie_weights_open: using bin override (arg) path='%s'", resolved_bin);
  } else {
    const char *env_bin = getenv("IE_WEIGHTS_BIN");
    if (env_bin && *env_bin) {
      cpyz(resolved_bin, sizeof(resolved_bin), env_bin);
      WLOGI("ie_weights_open: using bin override (env IE_WEIGHTS_BIN) path='%s'", resolved_bin);
    } else {
      char bin_key[256];
      bin_key[0] = '\0';
      const int found_bin_key = scan_json_best_effort_bin(jbuf, bin_key, sizeof(bin_key));
      if (found_bin_key == 1 && bin_key[0] != '\0') {
        const char *slash = last_slash(json_path);
        if (slash) {
          char dir[512];
          size_t dn = (size_t)(slash - json_path);
          if (dn >= sizeof(dir)) dn = sizeof(dir) - 1;
          memcpy(dir, json_path, dn);
          dir[dn] = '\0';
          join_path(resolved_bin, sizeof(resolved_bin), dir, bin_key);
          WLOGI("ie_weights_open: resolved bin from json key='%s' dir='%s' => '%s'", bin_key, dir,
                resolved_bin);
        } else {
          cpyz(resolved_bin, sizeof(resolved_bin), bin_key);
          WLOGI("ie_weights_open: resolved bin from json key='%s' => '%s'", bin_key, resolved_bin);
        }
      } else {
        const char *slash = last_slash(json_path);
        char dir[512];
        dir[0] = '\0';
        if (slash) {
          size_t dn = (size_t)(slash - json_path);
          if (dn >= sizeof(dir)) dn = sizeof(dir) - 1;
          memcpy(dir, json_path, dn);
          dir[dn] = '\0';
        } else {
          cpyz(dir, sizeof(dir), ".");
        }
        char fallback[512];
        fallback[0] = '\0';
        join_path(fallback, sizeof(fallback), dir, "model.ie.bin");
        if (file_exists_readable(fallback)) {
          cpyz(resolved_bin, sizeof(resolved_bin), fallback);
          WLOGW(
              "ie_weights_open: JSON did not specify weights bin path; defaulting to sibling "
              "model.ie.bin path='%s'",
              resolved_bin);
        } else {
          WLOGE("ie_weights_open: missing weights bin path in JSON (no known key matched)");
          WLOGE("ie_weights_open: also missing fallback sibling path='%s'", fallback);
          free(jbuf);
          return IE_IO_ERR_BIN_UNSPEC;
        }
      }
    }
  }
  cpyz(out->weights_path, sizeof(out->weights_path), resolved_bin);
  struct stat st;
  if (stat(out->weights_path, &st) != 0 || st.st_size < 0) {
    wlog_errno_("stat", out->weights_path);
    WLOGE("ie_weights_open: weights binary not accessible path='%s'", out->weights_path);
    free(jbuf);
    return IE_IO_ERR_STAT;
  }
  out->bin_size_bytes = (size_t)st.st_size;
  out->loaded = 1;
  WLOGI("ie_weights_open: weights binary ok path='%s' size_bytes=%zu", out->weights_path,
        out->bin_size_bytes);
#if (IE_WEIGHTS_HAS_DEDUP_FIELDS == 1)
  {
    const int dedup_enabled = env_flag_get("IE_DEDUP", 0);
    const int dedup_strict = env_flag_get("IE_DEDUP_STRICT", 0);
    WLOGD("ie_weights_open: dedup flags IE_DEDUP=%d IE_DEDUP_STRICT=%d", dedup_enabled,
          dedup_strict);
    if (dedup_enabled) {
      const char *slash = last_slash(json_path);
      char dir[512];
      dir[0] = '\0';
      if (slash) {
        size_t dn = (size_t)(slash - json_path);
        if (dn >= sizeof(dir)) dn = sizeof(dir) - 1;
        memcpy(dir, json_path, dn);
        dir[dn] = '\0';
      } else {
        cpyz(dir, sizeof(dir), ".");
      }
      char dedup_json[512];
      dedup_json[0] = '\0';
      join_path(dedup_json, sizeof(dedup_json), dir, "model.dedup.json");
      if (!file_exists_readable(dedup_json)) {
        WLOGI("ie_weights_open: dedup enabled but model.dedup.json missing; attempting link");
        (void)ensure_dedup_manifest_link(dir);
      }
      if (file_exists_readable(dedup_json)) {
        ie_weights_dedup_opts_t opts;
        memset(&opts, 0, sizeof(opts));
        opts.prefault_policy = 0;
        ie_weights_dedup_t *dh = NULL;
        ie_wdedup_status_t dst = ie_weights_dedup_open(&dh, dir, &opts);
        if (dst == IE_WDEDUP_OK && dh) {
          out->is_dedup = 1;
          out->dedup_handle = (void *)dh;
          WLOGI("ie_weights_open: dedup artifacts opened (dir='%s')", dir);
        } else {
          WLOGW("ie_weights_open: dedup open failed (status=%d dir='%s')", (int)dst, dir);
          if (dedup_strict) {
            WLOGE("ie_weights_open: dedup strict mode: failing open");
            free(jbuf);
            return IE_IO_ERR_JSON;
          }
          out->is_dedup = 0;
          out->dedup_handle = NULL;
        }
      } else {
        WLOGW("ie_weights_open: dedup enabled but model.dedup.json still missing (dir='%s')", dir);
        if (dedup_strict) {
          WLOGE("ie_weights_open: dedup strict mode: failing open");
          free(jbuf);
          return IE_IO_ERR_JSON;
        }
      }
    }
  }
#endif
  free(jbuf);
  WLOGI("ie_weights_open: success");
  return IE_IO_OK;
}
References cpyz(), ensure_dedup_manifest_link(), env_flag_get(), file_exists_readable(), IE_IO_ERR_ARGS, IE_IO_ERR_BIN_UNSPEC, IE_IO_ERR_JSON, IE_IO_ERR_STAT, IE_IO_OK, IE_WDEDUP_OK, ie_weights_dedup_open(), join_path(), last_slash(), ie_weights_dedup_opts_t::prefault_policy, read_all_text(), scan_json_best_effort_bin(), scan_json_key_int(), scan_json_key_string(), wlog_errno_(), WLOGD, WLOGE, WLOGI, and WLOGW.
Referenced by ie_engine_create(), main(), main(), and open_and_touch().
ie_weights_touch()
int ie_weights_touch (const ie_weights_t * w)
Touch the weights binary to verify readability and warm OS caches.
Implementations perform small positional reads near the start and end of the file to:
detect permission or corruption issues early,
optionally fault pages into memory.
When deduplication is enabled, this also verifies the presence of auxiliary artifacts (defaults, exceptions, masks).
Parameters
w Opened weights descriptor.
Returns
IE_IO_OK on success, negative ie_io_status_t otherwise.
This performs small reads near the start and end of the binary. When dedup is enabled, also checks auxiliary dedup files.
Parameters
w Opened weights descriptor.
Returns
IE_IO_OK on success; negative ie_io_status_t on failure.
Definition at line 1183 of file weights.c.
{
  if (!w || !w->weights_path[0]) return IE_IO_ERR_ARGS;
  WLOGI("ie_weights_touch: begin path='%s' size_bytes=%zu", w->weights_path, w->bin_size_bytes);
  int fd = open(w->weights_path, O_RDONLY);
  if (fd < 0) {
    wlog_errno_("open", w->weights_path);
    return IE_IO_ERR_OPEN;
  }
  unsigned char buf[4096];
  ssize_t r1 = ie_pread(fd, buf, sizeof(buf), 0);
  ssize_t r2 = 0;
  if (w->bin_size_bytes > sizeof(buf)) {
    off_t off = (off_t)(w->bin_size_bytes - sizeof(buf));
    r2 = ie_pread(fd, buf, sizeof(buf), off);
  }
  close(fd);
  if (r1 < 0 || r2 < 0) {
    WLOGE("ie_weights_touch: read failed (r1=%zd r2=%zd) path='%s'", r1, r2, w->weights_path);
    return IE_IO_ERR_READ;
  }
  WLOGD("ie_weights_touch: ok primary binary reads (r1=%zd r2=%zd)", r1, r2);
#if (IE_WEIGHTS_HAS_DEDUP_FIELDS == 1)
  {
    const int dedup_enabled = env_flag_get("IE_DEDUP", 0);
    const int dedup_strict = env_flag_get("IE_DEDUP_STRICT", 0);
    WLOGD("ie_weights_touch: dedup flags IE_DEDUP=%d IE_DEDUP_STRICT=%d", dedup_enabled,
          dedup_strict);
    if (dedup_enabled) {
      const char *base = (w->json_path[0] ? w->json_path : w->weights_path);
      const char *slash = last_slash(base);
      char dir[512];
      dir[0] = '\0';
      if (slash) {
        size_t dn = (size_t)(slash - base);
        if (dn >= sizeof(dir)) dn = sizeof(dir) - 1;
        memcpy(dir, base, dn);
        dir[dn] = '\0';
      } else {
        cpyz(dir, sizeof(dir), ".");
      }
      /*
       * Touch dedup artifacts.
       *
       * Instead of hardcoding filenames, prefer reading relpaths from
       * model.dedup.json (it contains a files[] table).
       */
      char dedup_manifest[512];
      dedup_manifest[0] = '\0';
      join_path(dedup_manifest, sizeof(dedup_manifest), dir, "model.dedup.json");
      if (!file_exists_readable(dedup_manifest)) {
        WLOGI("ie_weights_touch: dedup enabled but model.dedup.json missing; attempting link");
        (void)ensure_dedup_manifest_link(dir);
      }
      int ok_manifest = touch_file_small(dedup_manifest);
      int ok_all = ok_manifest;
      char *mjson = NULL;
      size_t mlen = 0;
      if (ok_manifest && read_all_text(dedup_manifest, &mjson, &mlen) == 0 && mjson && mlen > 0) {
        /* Scan for \"relpath\" entries and touch each referenced file. */
        size_t touched = 0;
        const char *p = mjson;
        while ((p = strstr(p, "\"relpath\"")) != NULL) {
          p += strlen("\"relpath\"");
          while (*p && (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n')) ++p;
          if (*p != ':') continue;
          ++p;
          while (*p && (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n')) ++p;
          if (*p != '"') continue;
          ++p;
          char rel[512];
          size_t rn = 0;
          int esc = 0;
          for (; *p && rn + 1 < sizeof(rel); ++p) {
            char ch = *p;
            if (esc) {
              /* Minimal unescape (we only expect simple paths). */
              if (ch == '"' || ch == '\\' || ch == '/') {
                rel[rn++] = ch;
              } else if (ch == 'n') {
                rel[rn++] = '\n';
              } else if (ch == 'r') {
                rel[rn++] = '\r';
              } else if (ch == 't') {
                rel[rn++] = '\t';
              } else {
                rel[rn++] = ch;
              }
              esc = 0;
              continue;
            }
            if (ch == '\\') {
              esc = 1;
              continue;
            }
            if (ch == '"') {
              break;
            }
            rel[rn++] = ch;
          }
          rel[rn] = '\0';
          if (rel[0] != '\0') {
            char abs[512];
            abs[0] = '\0';
            join_path(abs, sizeof(abs), dir, rel);
            int ok = touch_file_small(abs);
            ok_all = ok_all && ok;
            ++touched;
          }
          if (*p == '"') ++p;
          if (touched > 128) break; /* sanity bound */
        }
        WLOGI("ie_weights_touch: dedup touch results manifest=%d ok_all=%d", ok_manifest, ok_all);
        if (touched == 0) {
          /* Fallback to canonical filenames used by the reference pipeline. */
          char p_def[512], p_exc[512], p_msk[512];
          p_def[0] = p_exc[0] = p_msk[0] = '\0';
          join_path(p_def, sizeof(p_def), dir, "model.defaults.bin");
          join_path(p_exc, sizeof(p_exc), dir, "model.exceptions.bin");
          join_path(p_msk, sizeof(p_msk), dir, "model.masks.bin");
          int ok_def = touch_file_small(p_def);
          int ok_exc = touch_file_small(p_exc);
          int ok_msk = touch_file_small(p_msk);
          ok_all = ok_all && ok_def && ok_exc && ok_msk;
          WLOGI("ie_weights_touch: dedup fallback touch defaults=%d exceptions=%d masks=%d", ok_def, ok_exc,
                ok_msk);
        }
      } else {
        WLOGW("ie_weights_touch: could not read dedup manifest '%s'", dedup_manifest);
        ok_all = 0;
      }
      free(mjson);
      if (dedup_strict && !ok_all) {
        WLOGE("ie_weights_touch: dedup strict mode: missing or unreadable artifact(s)");
        return IE_IO_ERR_JSON;
      }
    }
  }
#endif
  WLOGI("ie_weights_touch: success");
  return IE_IO_OK;
}
References ie_weights_s::bin_size_bytes, cpyz(), ensure_dedup_manifest_link(), env_flag_get(), file_exists_readable(), IE_IO_ERR_ARGS, IE_IO_ERR_JSON, IE_IO_ERR_OPEN, IE_IO_ERR_READ, IE_IO_OK, ie_pread(), join_path(), ie_weights_s::json_path, last_slash(), read_all_text(), touch_file_small(), ie_weights_s::weights_path, wlog_errno_(), WLOGD, WLOGE, WLOGI, and WLOGW.
Referenced by open_and_touch().