Inference Engine (Clocher): engine/src/io/ie_batcher.c File Reference
ie_batcher.c File Reference
Prefetch + tokenization batcher with preserved output order.
#include "ie_batcher.h"
#include <pthread.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct ie_batcher
Concrete batcher (matches the opaque tag in the public header).
Functions
static void * xcalloc (size_t n, size_t sz)
calloc wrapper (zero-initialized).
static void clear_item (ie_batcher_item_t *it)
Free an item's payload (token ids) and reset its fields.
static int pop_next (ie_batcher_t *b, size_t *out_idx)
Thread-safe fetch of the next prompt index to process.
static void enqueue_item (ie_batcher_t *b, const ie_batcher_item_t *it)
Enqueue a tokenized item into the ring (blocks if full).
static void * worker_main (void *arg)
Producer thread entry: tokenizes prompts in ascending index order.
ie_batcher_t * ie_batcher_create (const char **prompts, size_t n_prompts, size_t microbatch, size_t queue_capacity, unsigned n_workers, ie_batcher_tokenize_fn tokenize_cb, void *user_ctx)
Create a new asynchronous tokenizer batcher.
int ie_batcher_get (ie_batcher_t *b, ie_batcher_view_t *out_view)
Obtain a contiguous slice of ready items without copying.
void ie_batcher_advance (ie_batcher_t *b, size_t n_consumed)
Release items previously returned by ie_batcher_get.
void ie_batcher_destroy (ie_batcher_t *b)
Destroy a batcher, joining workers and freeing all resources.
Detailed Description
Prefetch + tokenization batcher with preserved output order.
Implementation notes:
The public header declares an opaque type via typedef struct ie_batcher ie_batcher_t;. This file defines that struct as struct ie_batcher { ... } (same tag name), avoiding any conflicting typedefs.
To preserve strict input order == output order and to keep unit tests deterministic, this implementation runs with a single producer worker regardless of the requested n_workers. If you want parallel tokenization later, add an ordered merge stage.
The consumer obtains contiguous slices from a ring buffer up to microbatch items and never across the ring wrap boundary.
Definition in file ie_batcher.c.
Function Documentation
clear_item()
static void clear_item (ie_batcher_item_t * it) static
Free an item's payload (token ids) and reset its fields.
Parameters
it The item to clear (may be NULL).
Definition at line 81 of file ie_batcher.c.
{
   if (!it) return;
   if (it->ids) free(it->ids);
   it->ids = NULL;
   it->n_ids = 0;
   it->status = 0;
   it->prompt = NULL;
 }
References ie_batcher_item_t::ids, ie_batcher_item_t::n_ids, ie_batcher_item_t::prompt, and ie_batcher_item_t::status.
Referenced by ie_batcher_advance(), and ie_batcher_destroy().
enqueue_item()
static void enqueue_item (ie_batcher_t * b, const ie_batcher_item_t * it) static
Enqueue a tokenized item into the ring (blocks if full).
Ownership of it->ids transfers to the ring on success. If the batcher is stopping, the function frees it->ids to avoid leaking the payload.
Parameters
b Batcher handle.
it Item to enqueue (copied by value).
Definition at line 123 of file ie_batcher.c.
{
   pthread_mutex_lock(&b->mu);
   while (b->size == b->cap && !b->stop) {
     pthread_cond_wait(&b->cv_not_full, &b->mu);
   }
   if (!b->stop) {
     b->ring[b->w] = *it; /* struct copy; moves pointer ownership */
     b->w = (b->w + 1) % b->cap;
     b->size++;
     pthread_cond_signal(&b->cv_not_empty);
   } else {
     if (it->ids) free((void*)it->ids);
   }
   pthread_mutex_unlock(&b->mu);
 }
References ie_batcher::cap, ie_batcher::cv_not_empty, ie_batcher::cv_not_full, ie_batcher_item_t::ids, ie_batcher::mu, ie_batcher::ring, ie_batcher::size, ie_batcher::stop, and ie_batcher::w.
Referenced by worker_main().
ie_batcher_advance()
void ie_batcher_advance (ie_batcher_t * b, size_t n_consumed)
Release items previously returned by ie_batcher_get.
Frees payloads and advances the ring read pointer, then signals producers that space is available.
Parameters
b Batcher handle (non-NULL).
n_consumed Number of items to release; must not exceed the last view count.
Definition at line 250 of file ie_batcher.c.
{
   if (!b || n_consumed == 0) return;
   pthread_mutex_lock(&b->mu);
   for (size_t i = 0; i < n_consumed; ++i) {
     size_t idx = (b->r + i) % b->cap;
     clear_item(&b->ring[idx]);
   }
   b->r = (b->r + n_consumed) % b->cap;
   b->size -= n_consumed;
   pthread_cond_signal(&b->cv_not_full);
   pthread_mutex_unlock(&b->mu);
 }
References ie_batcher::cap, clear_item(), ie_batcher::cv_not_full, ie_batcher::mu, ie_batcher::r, ie_batcher::ring, and ie_batcher::size.
Referenced by test_basic_prefetch_and_order(), and test_wrap_and_view_limits().
ie_batcher_create()
ie_batcher_t* ie_batcher_create (const char ** prompts, size_t n_prompts, size_t microbatch, size_t queue_capacity, unsigned n_workers, ie_batcher_tokenize_fn tokenize_cb, void * user_ctx)
Create a new asynchronous tokenizer batcher.
Spawns up to n_workers threads that prefetch and tokenize prompts into a bounded ring buffer. The consumer should call ie_batcher_get followed by ie_batcher_advance in a loop until the stream is drained.
Defaults:
If microbatch == 0, it is treated as 1.
If queue_capacity == 0, it is treated as max(microbatch, 8).
If n_workers == 0, it is treated as 1.
Parameters
prompts Array of input UTF-8 prompt strings (not owned; must outlive the batcher).
n_prompts Number of prompts in prompts.
microbatch Maximum items returned per view. Use 0 for default.
queue_capacity Ring capacity in items. Use 0 for default.
n_workers Number of tokenizer worker threads. Use 0 for default.
tokenize_cb User tokenizer callback (must not be NULL).
user_ctx Opaque pointer forwarded to tokenize_cb; may be NULL.
Returns
ie_batcher_t* Handle on success, or NULL on allocation/spawn error.
Definition at line 171 of file ie_batcher.c.
{
   (void)n_workers; /* determinism: always 1 producer thread */
   if (!prompts || n_prompts == 0 || !tokenize_cb) return NULL;
   if (queue_capacity == 0) queue_capacity = microbatch ? microbatch : 8;
   ie_batcher_t *b = (ie_batcher_t*)xcalloc(1, sizeof(*b));
   if (!b) return NULL;
   b->prompts = prompts;
   b->n_prompts = n_prompts;
   b->microbatch = microbatch ? microbatch : 1;
   b->cap = queue_capacity;
   b->ring = (ie_batcher_item_t*)xcalloc(b->cap, sizeof(*b->ring));
   if (!b->ring) { free(b); return NULL; }
   pthread_mutex_init(&b->mu, NULL);
   pthread_cond_init(&b->cv_not_full, NULL);
   pthread_cond_init(&b->cv_not_empty, NULL);
   b->tokenize = tokenize_cb;
   b->user_ctx = user_ctx;
   b->n_workers = 1;
   b->threads = (pthread_t*)xcalloc(b->n_workers, sizeof(pthread_t));
   if (!b->threads) {
     free(b->ring);
     free(b);
     return NULL;
   }
   if (pthread_create(&b->threads[0], NULL, worker_main, b) != 0) {
     free(b->threads);
     free(b->ring);
     free(b);
     return NULL;
   }
   return b;
 }
References ie_batcher::cap, ie_batcher::cv_not_empty, ie_batcher::cv_not_full, ie_batcher::microbatch, ie_batcher::mu, ie_batcher::n_prompts, ie_batcher::n_workers, ie_batcher::prompts, ie_batcher::ring, ie_batcher::threads, ie_batcher::tokenize, ie_batcher::user_ctx, worker_main(), and xcalloc().
Referenced by test_basic_prefetch_and_order(), test_partial_teardown(), and test_wrap_and_view_limits().
ie_batcher_destroy()
void ie_batcher_destroy (ie_batcher_t * b)
Destroy a batcher, joining workers and freeing all resources.
Safe to call with NULL.
Parameters
b Batcher handle (may be NULL).
Definition at line 267 of file ie_batcher.c.
{
   if (!b) return;
   pthread_mutex_lock(&b->mu);
   b->stop = 1;
   pthread_cond_broadcast(&b->cv_not_full);
   pthread_cond_broadcast(&b->cv_not_empty);
   pthread_mutex_unlock(&b->mu);
   for (unsigned i = 0; i < b->n_workers; ++i) {
     if (b->threads[i]) pthread_join(b->threads[i], NULL);
   }
   /* Free any remaining items in the ring. */
   for (size_t i = 0; i < b->cap; ++i) clear_item(&b->ring[i]);
   pthread_cond_destroy(&b->cv_not_full);
   pthread_cond_destroy(&b->cv_not_empty);
   pthread_mutex_destroy(&b->mu);
   free(b->threads);
   free(b->ring);
   free(b);
 }
References ie_batcher::cap, clear_item(), ie_batcher::cv_not_empty, ie_batcher::cv_not_full, ie_batcher::mu, ie_batcher::n_workers, ie_batcher::ring, ie_batcher::stop, and ie_batcher::threads.
Referenced by test_basic_prefetch_and_order(), test_partial_teardown(), and test_wrap_and_view_limits().
ie_batcher_get()
int ie_batcher_get (ie_batcher_t * b, ie_batcher_view_t * out_view)
Obtain a contiguous slice of ready items without copying.
If no items are ready but production is still in progress, this function blocks until an item is available (or the batcher is stopping).
When this function returns 0, the stream is drained; out_view->done will be set to 1 and out_view->items will be NULL.
Parameters
b Batcher handle (non-NULL).
out_view Output view describing a contiguous span of items.
Returns
int 1 if a non-empty view was produced; 0 if the stream is drained.
Definition at line 217 of file ie_batcher.c.
{
   if (!b || !out_view) return 0;
   pthread_mutex_lock(&b->mu);
   while (b->size == 0 && !b->producer_done && !b->stop) {
     pthread_cond_wait(&b->cv_not_empty, &b->mu);
   }
   if (b->size == 0 && (b->producer_done || b->stop)) {
     out_view->items = NULL;
     out_view->count = 0;
     out_view->done = 1;
     pthread_mutex_unlock(&b->mu);
     return 0;
   }
   size_t avail = b->size;
   size_t first = b->r;
   size_t can_take = b->microbatch;
   if (can_take > avail) can_take = avail;
   /* Return a contiguous tail segment only (no wrap across r->end). */
   size_t tail = b->cap - first;
   if (can_take > tail) can_take = tail;
   out_view->items = &b->ring[first];
   out_view->count = can_take;
   out_view->done = (b->producer_done && (b->size == can_take));
   pthread_mutex_unlock(&b->mu);
   return 1;
 }
References ie_batcher::cap, ie_batcher_view::count, ie_batcher::cv_not_empty, ie_batcher_view::done, ie_batcher_view::items, ie_batcher::microbatch, ie_batcher::mu, ie_batcher::producer_done, ie_batcher::r, ie_batcher::ring, ie_batcher::size, and ie_batcher::stop.
Referenced by test_basic_prefetch_and_order(), test_partial_teardown(), and test_wrap_and_view_limits().
pop_next()
static int pop_next (ie_batcher_t * b, size_t * out_idx) static
Thread-safe fetch of the next prompt index to process.
Parameters
b Batcher handle.
out_idx Output index in [0, n_prompts).
Returns
1 if an index was produced; 0 if there is no more work.
Definition at line 100 of file ie_batcher.c.
{
   int ret = 0;
   pthread_mutex_lock(&b->mu);
   if (b->produced < b->n_prompts) {
     *out_idx = b->produced++;
     ret = 1;
     if (b->produced == b->n_prompts) {
       b->producer_done = 1;
     }
   }
   pthread_mutex_unlock(&b->mu);
   return ret;
 }
References ie_batcher::mu, ie_batcher::n_prompts, ie_batcher::produced, and ie_batcher::producer_done.
Referenced by worker_main().
worker_main()
static void* worker_main (void * arg) static
Producer thread entry: tokenizes prompts in ascending index order.
Parameters
arg ie_batcher_t* passed as void*.
Returns
NULL
Definition at line 144 of file ie_batcher.c.
{
   ie_batcher_t *b = (ie_batcher_t*)arg;
   for (;;) {
     size_t idx = 0;
     if (!pop_next(b, &idx)) break;
     ie_batcher_item_t it;
     memset(&it, 0, sizeof(it));
     it.prompt = b->prompts[idx];
     uint32_t *ids = NULL;
     size_t n = 0;
     int st = b->tokenize(it.prompt, &ids, &n, b->user_ctx);
     it.ids = ids;
     it.n_ids = n;
     it.status = st;
     enqueue_item(b, &it);
   }
   return NULL;
 }
References enqueue_item(), ie_batcher_item_t::ids, ie_batcher_item_t::n_ids, pop_next(), ie_batcher_item_t::prompt, ie_batcher::prompts, ie_batcher_item_t::status, ie_batcher::tokenize, and ie_batcher::user_ctx.
Referenced by ie_batcher_create().
xcalloc()
static void* xcalloc (size_t n, size_t sz) static
calloc wrapper (zero-initialized).
Parameters
n Number of elements.
sz Size of each element in bytes.
Returns
Pointer to allocated memory or NULL.
Definition at line 75 of file ie_batcher.c.
 { return calloc(n, sz); }
Referenced by ie_batcher_create().