Inference Engine (Clocher): engine/include/ie_kernels.h File Reference
ie_kernels.h File Reference
#include <stddef.h>
#include <stdint.h>
#include "ie_quant_act.h"
Functions
void ie_kernels_install (int use_avx2)
Install the best available CPU kernels for this process.
void ie_gemv_f32 (const float *W, const float *x, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k)
GEMV (fp32): y[r] = dot(W[r,:], x) + (bias ? bias[r] : 0).
void ie_vec_bf16_to_f32 (const uint16_t *in, float *out, size_t n)
Convert BF16 vector to FP32.
int ie_gemv_bf16_f32 (const uint16_t *W_bf16, const float *x, float *y, size_t rows, size_t cols, const uint16_t *bias_bf16)
GEMV with BF16 weights and FP32 activations.
int ie_gemv_q4_0_f32 (const uint8_t *W_q4, const uint8_t *W_scales, size_t scale_bytes, const float *x, float *y, size_t rows, size_t cols, const uint16_t *bias_bf16)
GEMV with Q4_0 weights and FP32 activations.
void ie_q4_log2_u8_q3_init_generic (void)
Initialize log2(u8, q3) LUT for Q4 kernels (generic path).
void ie_q4_log2_u8_q3_init_avx2 (void)
Initialize log2(u8, q3) LUT for Q4 kernels (AVX2 path).
int ie_gemv_q4_0_f32_fscale (const uint8_t *W_q4, const float *W_scales, const float *x, float *y, size_t rows, size_t cols, const uint16_t *bias_bf16)
GEMV with Q4_0 weights and predecoded FP32 scales.
void ie_gemv_qi8_f32 (const float *W, const int8_t *x_q, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k, ie_act_i8_params params, int symmetric)
GEMV with per-tensor INT8 activations (fused dequantization).
void ie_gemv_qi8pg_f32 (const float *W, const int8_t *x_q, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k, size_t group_size, const float *scales, const int8_t *zeros, int symmetric)
GEMV with per-group INT8 activations (blockwise parameters).
void ie_gemv_qfp8_f32 (const float *W, const uint8_t *x_fp8, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k, ie_fp8_format fmt)
GEMV with FP8 activations (software decode, fused).
int ie_attn_cpu_causal_f32 (const float *Q, const float *K, const float *V, size_t seq_len, size_t heads, size_t head_dim, float inv_sqrt_d, float *out, float *scratch)
Causal self-attention (FP32 reference).
int ie_mlp_cpu_swiglu_f32 (const float *W_gate, const float *W_up, const float *W_down, const float *x, size_t in_dim, size_t hidden_dim, size_t out_dim, const float *b_gate, const float *b_up, const float *b_down, float *out, float *tmp_gate, float *tmp_up)
SwiGLU MLP forward (FP32 reference).
int ie_rmsnorm_cpu_f32 (const float *x, const float *w, size_t n, float eps, float *y)
RMSNorm (FP32) for a single vector.
int ie_rope_apply_f32 (float *q, float *k, size_t heads, size_t head_dim, uint32_t pos, float theta)
Apply Rotary Positional Embedding (RoPE) to Q and K for a single position.
void ie_vec_tanh_f32 (float *v, size_t n, int fast_tanh)
Vector tanh on fp32 data (in-place).
float ie_fast_tanhf (float x)
Fast scalar tanh approximation.
Function Documentation
ie_attn_cpu_causal_f32()
int ie_attn_cpu_causal_f32 (const float * Q, const float * K, const float * V, size_t seq_len, size_t heads, size_t head_dim, float inv_sqrt_d, float * out, float * scratch)
Causal self-attention (FP32 reference).
Computes per-head softmax(QK^T * inv_sqrt_d) V over seq_len tokens.
Layout:
Q and out are [heads, head_dim] flattened (head_dim fastest).
K and V are [seq_len, heads, head_dim] flattened (head_dim fastest).
scratch must have length >= seq_len (floats) and is reused per head.
Returns
0 on success, non-zero on invalid args.
Causal self-attention (FP32 reference).
Parameters
Q Pointer to Q slice [heads*head_dim].
K Pointer to K cache [seq_len*heads*head_dim].
V Pointer to V cache [seq_len*heads*head_dim].
seq_len Number of cached tokens to attend over (>= 1).
heads Number of heads (>= 1).
head_dim Dimension per head (>= 1).
inv_sqrt_d Scale factor (typically 1/sqrt(head_dim)).
out Output buffer [heads*head_dim].
scratch Scratch buffer [seq_len] floats (reused per head).
Returns
0 on success, non-zero on invalid args.
Definition at line 76 of file attn_cpu.c.
{
  if (!Q || !K || !V || !out || !scratch) return -1;
  if (seq_len == 0 || heads == 0 || head_dim == 0) return -1;
  if (inv_sqrt_d == 0.0f) inv_sqrt_d = 1.0f;
  memset(out, 0, heads * head_dim * sizeof(float));
  for (size_t h = 0; h < heads; ++h) {
    const float *Qh = Q + h * head_dim;
    for (size_t t = 0; t < seq_len; ++t) {
      const float *Kh = K + kv_index(t, h, 0, heads, head_dim);
      scratch[t] = dot_f32(Qh, Kh, head_dim) * inv_sqrt_d;
    }
    softmax_inplace_f32(scratch, seq_len);
    float *Oh = out + h * head_dim;
    for (size_t t = 0; t < seq_len; ++t) {
      const float w = scratch[t];
      const float *Vh = V + kv_index(t, h, 0, heads, head_dim);
      for (size_t d = 0; d < head_dim; ++d) {
        Oh[d] += w * Vh[d];
      }
    }
  }
  return 0;
}
References dot_f32(), ie_dot_f32(), ie_softmax_inplace_f32(), kv_index(), and softmax_inplace_f32().
Referenced by ie_forward_one_token().
ie_fast_tanhf()
float ie_fast_tanhf (float x)
Fast scalar tanh approximation.
Parameters
x Input value.
Returns
Approximated tanh(x).
Fast scalar tanh approximation.
For large |x| we short-circuit to +/-1.0f. For moderate |x| we use a small rational function that gives a smooth S-curve:
tanh(x) ≈ x * (27 + x^2) / (27 + 9 x^2)
Finally, the result is clamped to [-1, 1] to guarantee range correctness.
Parameters
x Input value.
Returns
Approximated tanh(x) in [-1.0f, 1.0f].
Definition at line 28 of file fast_tanh.c.
{
  /* Early clamp for large magnitude to avoid overflow and extra work. */
  if (x > 5.0f)  return 1.0f;
  if (x < -5.0f) return -1.0f;
  /* Rational approximation (cheap and monotonic on [-3,3]) */
  const float x2  = x * x;
  const float num = x * (27.0f + x2);
  const float den = 27.0f + 9.0f * x2;
  float y = num / den;
  /* Safety clamp for strict range compliance. */
  if (y > 1.0f)  y = 1.0f;
  if (y < -1.0f) y = -1.0f;
  return y;
}
ie_gemv_bf16_f32()
int ie_gemv_bf16_f32 (const uint16_t * W_bf16, const float * x, float * y, size_t rows, size_t cols, const uint16_t * bias_bf16)
GEMV with BF16 weights and FP32 activations.
Parameters
W_bf16 BF16 weights (row-major).
x FP32 input vector.
y FP32 output vector.
rows Rows.
cols Cols.
bias_bf16 Optional BF16 bias or NULL.
Returns
0 on success, non-zero on invalid args.
Definition at line 225 of file gemv_generic.c.
{
  ie_kernels_lazy_init();
  ie_bf16_tp_init();
  if (g_bf16_tp && g_bf16_threads > 1u && rows >= g_bf16_threads * 2u) {
    ie_gemv_bf16_job_t job = {
      .W_bf16 = W_bf16,
      .x = x,
      .y = y,
      .rows = rows,
      .cols = cols,
      .bias_bf16 = bias_bf16,
      .impl = g_gemv_bf16,
    };
    unsigned grainsize = (unsigned)((rows + g_bf16_threads - 1u) / g_bf16_threads);
    ie_tp_parallel_for(g_bf16_tp, (unsigned)rows, grainsize, ie_gemv_bf16_job_run, &job);
    return 0;
  }
  return g_gemv_bf16(W_bf16, x, y, rows, cols, bias_bf16);
}
References g_bf16_threads, g_bf16_tp, g_gemv_bf16, ie_bf16_tp_init(), ie_gemv_bf16_job_run(), ie_kernels_lazy_init(), ie_tp_parallel_for(), and ie_gemv_bf16_job_t::W_bf16.
Referenced by ie_forward_one_token().
ie_gemv_f32()
void ie_gemv_f32 (const float * W, const float * x, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k)
GEMV (fp32): y[r] = dot(W[r,:], x) + (bias ? bias[r] : 0).
Computes a matrix-vector product using the best installed implementation.
Layout:
Default is row-major: W is rows*cols floats, each row contiguous.
Some kernels also accept a "blocked-K contiguous" interpretation per row; pass blk_k to describe the block size. Passing 0 disables blocking.
Parameters
W Pointer to weights (row-major or compatible packed layout).
x Input vector (length cols).
y Output vector (length rows).
rows Number of rows.
cols Number of columns.
bias Optional bias vector (length rows) or NULL.
blk_k Column block size for blocked-K layout; 0 for plain row-major.
Definition at line 247 of file gemv_generic.c.
{
  ie_kernels_lazy_init();
  g_gemv_f32(W, x, y, rows, cols, bias, bias_stride);
}
References g_gemv_f32, and ie_kernels_lazy_init().
Referenced by cpu_gemv_f32(), ie_forward_one_token(), ie_mlp_cpu_swiglu_f32(), test_gemv_rowmajor_no_bias(), and test_gemv_rowmajor_with_bias().
ie_gemv_q4_0_f32()
int ie_gemv_q4_0_f32 (const uint8_t * W_blocks, const uint8_t * W_scales, size_t scale_bytes, const float * x, float * y, size_t rows, size_t cols, const uint16_t * bias_bf16)
GEMV with Q4_0 weights and FP32 activations.
Parameters
W_q4 Q4 blocks (row-major).
W_scales Q4 scales (row-major, BF16 or FP8).
scale_bytes Bytes per scale element (1 or 2).
x FP32 input vector.
y FP32 output vector.
rows Rows.
cols Cols.
bias_bf16 Optional BF16 bias or NULL.
Returns
0 on success, non-zero on invalid args.
GEMV with Q4_0 weights and FP32 activations.
The dispatch decision is cached after the first call. This avoids the need to modify global kernel initialization routines and ensures the symbol always resolves at link time.
Definition at line 228 of file gemv_q4_generic.c.
{
  typedef int (*gemv_fn_t)(const uint8_t *, const uint8_t *, size_t, const float *, float *,
                          size_t, size_t, const uint16_t *);
  static gemv_fn_t fn = NULL;
  if (!fn) {
    ie_cpu_features_t feat;
    ie_cpu_features_detect(&feat);
    const char *force_generic = getenv("IE_Q4_FORCE_GENERIC");
    if (force_generic && force_generic[0] && strcmp(force_generic, "0") != 0) {
      fn = ie_gemv_q4_0_f32_generic_impl;
    } else if (feat.avx2 && feat.fma) {
      fn = ie_gemv_q4_0_f32_avx2_impl;
    } else {
      fn = ie_gemv_q4_0_f32_generic_impl;
    }
  }
  return fn(W_blocks, W_scales, scale_bytes, x, y, rows, cols, bias_bf16);
}
References ie_cpu_features::avx2, ie_cpu_features::fma, ie_cpu_features_detect(), ie_gemv_q4_0_f32_avx2_impl(), and ie_gemv_q4_0_f32_generic_impl().
Referenced by cpu_gemv_q4_0_f32(), and ie_forward_one_token().
ie_gemv_q4_0_f32_fscale()
int ie_gemv_q4_0_f32_fscale (const uint8_t * W_q4, const float * W_scales, const float * x, float * y, size_t rows, size_t cols, const uint16_t * bias_bf16)
GEMV with Q4_0 weights and predecoded FP32 scales.
Parameters
W_q4 Q4 blocks (row-major).
W_scales FP32 scales (row-major).
x FP32 input vector.
y FP32 output vector.
rows Rows.
cols Cols.
bias_bf16 Optional BF16 bias or NULL.
Returns
0 on success, non-zero on invalid args.
ie_gemv_qfp8_f32()
void ie_gemv_qfp8_f32 (const float * W, const uint8_t * x_fp8, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k, ie_fp8_format fmt)
GEMV with FP8 activations (software decode, fused).
Decodes FP8 bytes (E4M3 or E5M2) on the fly while accumulating the dot product.
Parameters
W Weights (float).
x_fp8 FP8 activations (bytes, length cols).
y Output (float, length rows).
rows Rows.
cols Cols.
bias Optional bias or NULL.
blk_k Column block size; 0 disables blocking.
fmt FP8 format selector.
ie_gemv_qi8_f32()
void ie_gemv_qi8_f32 (const float * W, const int8_t * x_q, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k, ie_act_i8_params params, int symmetric)
GEMV with per-tensor INT8 activations (fused dequantization).
Interprets activations with the affine model: real = scale * (q - zero_point) Implementations may fuse dequantization into the dot product or dequantize into a temporary float buffer depending on ISA.
Parameters
W Weights (float).
x_q INT8 activations (length cols).
y Output (float, length rows).
rows Number of rows.
cols Number of columns.
bias Optional bias (length rows) or NULL.
blk_k Column block size; 0 disables blocking.
params Per-tensor quantization parameters.
symmetric Informational flag (unused by some paths).
ie_gemv_qi8pg_f32()
void ie_gemv_qi8pg_f32 (const float * W, const int8_t * x_q, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k, size_t group_size, const float * scales, const int8_t * zeros, int symmetric)
GEMV with per-group INT8 activations (blockwise parameters).
Each group of group_size elements uses its own (scale, zero_point): g = index / group_size real = scales[g] * (q - zeros[g])
Parameters
W Weights (float).
x_q INT8 activations (length cols).
y Output (float, length rows).
rows Rows.
cols Cols.
bias Optional bias or NULL.
blk_k Column block size; 0 disables blocking.
group_size Activation group size (>= 1).
scales Scales array (ceil(cols/group_size)).
zeros Zero-points array (ceil(cols/group_size)).
symmetric Informational flag.
ie_kernels_install()
void ie_kernels_install (int use_avx2)
Install the best available CPU kernels for this process.
Selects optimized implementations based on runtime CPU feature detection and updates an internal dispatch table. Safe to call multiple times; last call wins.
Parameters
use_avx2 Non-zero to allow selecting AVX2/FMA-optimized paths.
Definition at line 168 of file gemv_generic.c.
{
  g_gemv_f32 = &ie_gemv_f32_generic_impl;
  g_gemv_bf16 = &ie_gemv_bf16_generic_impl;
  g_vec_bf16_to_f32 = &ie_vec_bf16_to_f32_generic_impl;
  g_gemv_qi8 = &ie_gemv_qi8_stub_impl;
  const char *sel_f32 = "generic";
  const char *sel_bf16 = "generic";
  const char *sel_vec_bf16 = "generic";
  const char *sel_qi8 = "stub";
  if (use_avx2) {
    ie_cpu_features_t f;
    ie_cpu_features_detect(&f);
    if (f.avx2 && f.fma) {
      extern void ie_gemv_f32_avx2_impl(const float *W, const float *x, float *y,
                                       size_t rows, size_t cols,
                                       const float *bias, size_t bias_stride);
      extern int ie_gemv_bf16_f32_avx2_impl(const uint16_t *W_bf16, const float *x, float *y,
                                            size_t rows, size_t cols,
                                            const uint16_t *bias_bf16);
      extern void ie_vec_bf16_to_f32_avx2_impl(const uint16_t *in, float *out, size_t n);
      extern void ie_gemv_qi8_avx2_impl(const int8_t *W_qi8, const float *W_scales,
                                       const float *x, float *y,
                                       size_t rows, size_t cols,
                                       size_t block_cols,
                                       const float *bias, size_t bias_stride);
      g_gemv_f32 = &ie_gemv_f32_avx2_impl;
      g_gemv_bf16 = &ie_gemv_bf16_f32_avx2_impl;
      g_vec_bf16_to_f32 = &ie_vec_bf16_to_f32_avx2_impl;
      g_gemv_qi8 = &ie_gemv_qi8_avx2_impl;
      sel_f32 = "avx2";
      sel_bf16 = "avx2";
      sel_vec_bf16 = "avx2";
      sel_qi8 = "avx2";
    }
  }
  ie_log_kernel_once(sel_f32, sel_bf16, sel_vec_bf16, sel_qi8);
}
References ie_cpu_features::avx2, ie_cpu_features::fma, g_gemv_bf16, g_gemv_f32, g_gemv_qi8, g_vec_bf16_to_f32, ie_cpu_features_detect(), ie_gemv_bf16_f32_avx2_impl(), ie_gemv_bf16_generic_impl(), ie_gemv_f32_avx2_impl(), ie_gemv_f32_generic_impl(), ie_gemv_qi8_avx2_impl(), ie_gemv_qi8_stub_impl(), ie_log_kernel_once(), ie_vec_bf16_to_f32_avx2_impl(), and ie_vec_bf16_to_f32_generic_impl().
Referenced by ie_kernels_lazy_init(), and main().
ie_mlp_cpu_swiglu_f32()
int ie_mlp_cpu_swiglu_f32 (const float * W_gate, const float * W_up, const float * W_down, const float * x, size_t in_dim, size_t hidden_dim, size_t out_dim, const float * b_gate, const float * b_up, const float * b_down, float * out, float * tmp_gate, float * tmp_up)
SwiGLU MLP forward (FP32 reference).
gate = W_gate * x + b_gate up = W_up * x + b_up act = silu(gate) * up out = W_down * act + b_down
W_* are row-major matrices.
tmp_gate and tmp_up must have length >= hidden_dim.
Returns
0 on success, non-zero on invalid args.
SwiGLU MLP forward (FP32 reference).
Shapes: x: [in_dim] W_gate: [hidden_dim, in_dim] W_up: [hidden_dim, in_dim] W_down: [out_dim, hidden_dim] tmp_gate: [hidden_dim] tmp_up: [hidden_dim] out: [out_dim]
Bias pointers may be NULL.
Returns
0 on success, non-zero on invalid args.
Definition at line 44 of file mlp_cpu.c.
{
  if (!W_gate || !W_up || !W_down || !x || !out || !tmp_gate || !tmp_up) return -1;
  if (in_dim == 0 || hidden_dim == 0 || out_dim == 0) return -1;
  ie_gemv_f32(W_gate, x, tmp_gate, hidden_dim, in_dim, b_gate, 0);
  ie_gemv_f32(W_up,   x, tmp_up,   hidden_dim, in_dim, b_up,   0);
  for (size_t i = 0; i < hidden_dim; ++i) {
    tmp_gate[i] = silu_f32(tmp_gate[i]) * tmp_up[i];
  }
  ie_gemv_f32(W_down, tmp_gate, out, out_dim, hidden_dim, b_down, 0);
  return 0;
}
References ie_gemv_f32(), and silu_f32().
ie_q4_log2_u8_q3_init_avx2()
void ie_q4_log2_u8_q3_init_avx2 (void)
Initialize log2(u8, q3) LUT for Q4 kernels (AVX2 path).
Definition at line 76 of file gemv_q4_avx2.c.
{
  if (!ie_log2_u8_q3_ready_) {
    ie_log2_u8_q3_init_impl_();
  }
}
References ie_log2_u8_q3_init_impl_(), and ie_log2_u8_q3_ready_.
Referenced by ie_gptoss_infer_create().
ie_q4_log2_u8_q3_init_generic()
void ie_q4_log2_u8_q3_init_generic (void)
Initialize log2(u8, q3) LUT for Q4 kernels (generic path).
Definition at line 90 of file gemv_q4_generic.c.
{
  if (!ie_log2_u8_q3_ready_) {
    ie_log2_u8_q3_init_impl_();
  }
}
References ie_log2_u8_q3_init_impl_(), and ie_log2_u8_q3_ready_.
Referenced by ie_gptoss_infer_create().
ie_rmsnorm_cpu_f32()
int ie_rmsnorm_cpu_f32 (const float * x, const float * w, size_t n, float eps, float * y)
RMSNorm (FP32) for a single vector.
Computes: y[i] = x[i] * w[i] / sqrt(mean(x^2) + eps)
This is the reference CPU implementation used by the GPT-OSS orchestration. Implementations may be swapped by the build in the future, but the signature is stable for the runtime.
Parameters
x Input vector (length n).
w Weight vector (length n).
n Number of elements.
eps Epsilon added to the mean square before sqrt.
y Output vector (length n). May alias x for in-place behavior.
Returns
0 on success, negative on invalid args.
RMSNorm (FP32) for a single vector.
This function performs:
mean-square accumulation with a double accumulator for improved stability,
a single sqrtf and reciprocal,
per-element scaling by the provided weight vector.
The function is designed to be allocation-free and deterministic. It does not attempt SIMD vectorization; higher-performance backends may be added later.
Parameters
x Input vector of length n.
w Per-channel scale vector of length n.
n Number of elements in x and w.
eps Small epsilon added inside the sqrt for numerical stability.
y Output vector of length n (may alias x).
Returns
0 on success, non-zero on invalid arguments.
Definition at line 49 of file rmsnorm_cpu.c.
{
  if (!x || !w || !y || n == 0) return -1;
  double ss = 0.0;
  for (size_t i = 0; i < n; ++i) {
    const double v = (double)x[i];
    ss += v * v;
  }
  const double mean = ss / (double)n;
  const float inv_rms = 1.0f / sqrtf((float)mean + eps);
  for (size_t i = 0; i < n; ++i) {
    y[i] = (x[i] * inv_rms) * w[i];
  }
  return 0;
}
Referenced by ie_forward_one_token().
ie_rope_apply_f32()
int ie_rope_apply_f32 (float * q, float * k, size_t heads, size_t head_dim, uint32_t pos, float theta)
Apply Rotary Positional Embedding (RoPE) to Q and K for a single position.
This function applies RoPE on the first head_dim elements, interpreted as interleaved pairs (even, odd): (x0, x1) -> (x0*cos - x1*sin, x0*sin + x1*cos)
The caller passes Q and K shaped as [heads, head_dim] flattened.
Parameters
q Q buffer, [heads * head_dim].
k K buffer, [heads * head_dim].
heads Number of heads in q/k.
head_dim Head dimension (must be even for paired rotation).
pos Sequence position (0-based).
theta RoPE base (commonly 10000.0f).
Returns
0 on success, negative on invalid args.
Definition at line 171 of file rope.c.
{
  if (!q && !k) return 0;
  if (heads == 0u) return -1;
  if ((head_dim & 1u) != 0u) return -2;
  if (head_dim < 2u) return -3;
  if (!(theta > 0.0f)) return -4;
  for (size_t h = 0; h < heads; ++h) {
    if (q) {
      const int rc = ie_rope_apply_one_f32(q + h * head_dim, head_dim, pos, theta);
      if (rc != 0) return rc;
    }
    if (k) {
      const int rc = ie_rope_apply_one_f32(k + h * head_dim, head_dim, pos, theta);
      if (rc != 0) return rc;
    }
  }
  return 0;
}
References ie_rope_apply_one_f32().
ie_vec_bf16_to_f32()
void ie_vec_bf16_to_f32 (const uint16_t * in, float * out, size_t n)
Convert BF16 vector to FP32.
Parameters
in BF16 input (length n).
out FP32 output (length n).
n Number of elements.
Definition at line 220 of file gemv_generic.c.
{
  ie_kernels_lazy_init();
  g_vec_bf16_to_f32(in, out, n);
}
References g_vec_bf16_to_f32, and ie_kernels_lazy_init().
Referenced by ie_alloc_f32_from_bf16().
ie_vec_tanh_f32()
void ie_vec_tanh_f32 (float * v, size_t n, int fast_tanh)
Vector tanh on fp32 data (in-place).
Parameters
v Input/output vector.
n Number of elements.
fast_tanh Non-zero to use a fast approximation; zero to use tanhf().
Vector tanh on fp32 data (in-place).
If fast_tanh != 0, uses ie_fast_tanhf; otherwise uses libm tanhf. Output values are clamped to [-1, 1] in both modes to satisfy strict bounds.
Parameters
v Pointer to the vector (length n). Modified in-place.
n Number of elements in v.
fast_tanh Non-zero to use the fast approximation; 0 to use libm.
Definition at line 55 of file fast_tanh.c.
{
  if (!v || n == 0) return;
  if (fast_tanh) {
    for (size_t i = 0; i < n; ++i) {
      v[i] = ie_fast_tanhf(v[i]);
    }
  } else {
    for (size_t i = 0; i < n; ++i) {
      float y = tanhf(v[i]);
      if (y > 1.0f)  y = 1.0f;
      if (y < -1.0f) y = -1.0f;
      v[i] = y;
    }
  }
}
References ie_fast_tanhf().
Referenced by main().