Inference Engine (Clocher): engine/include/ie_layout.h File Reference
ie_layout.h File Reference
Helpers for pretransposing and caching weight matrices in blocked-K layout.
#include <stddef.h>
Data Structures
struct ie_wblocked_desc
Descriptor for a blocked-K layout buffer.
Typedefs
typedef struct ie_wblocked_desc ie_wblocked_desc_t
Descriptor for a blocked-K layout buffer.
Functions
int ie_layout_cache_name (const char *base_path, const char *tag, size_t rows, size_t cols, size_t blk_k, char *out_buf, size_t out_cap)
Create a filename for the on-disk cache of a blocked matrix.
int ie_layout_build_blockedK (const float *W, size_t rows, size_t cols, size_t blk_k, const char *cache_path, ie_wblocked_desc_t *out)
Allocate and build a blocked-K copy of row-major W.
void ie_layout_free (ie_wblocked_desc_t *desc)
Free resources owned by a blocked descriptor.
Detailed Description
Helpers for pretransposing and caching weight matrices in blocked-K layout.
Definition in file ie_layout.h.
Typedef Documentation
ie_wblocked_desc_t
typedef struct ie_wblocked_desc ie_wblocked_desc_t
Descriptor for a blocked-K layout buffer.
Function Documentation
ie_layout_build_blockedK()
int ie_layout_build_blockedK (const float * W, size_t rows, size_t cols, size_t blk_k, const char * cache_path, ie_wblocked_desc_t * out)
Allocate and build a blocked-K copy of row-major W.
Memory is allocated with malloc() and must be freed by the caller. If a cache file exists at cache_path, this function attempts to load it; otherwise it constructs the blocked layout and saves the cache atomically.
Parameters
W Pointer to source in row-major (rows x cols).
rows Row count.
cols Column count.
blk_k Column block size (e.g., 64 or 128). Must divide cols or last block is short.
cache_path Optional cache file path (may be NULL to skip disk cache).
out Output descriptor (data pointer, rows/cols/blk_k).
Returns
0 on success; -1 on failure.
Allocate and build a blocked-K copy of row-major W.
Layout definition (per row): For k0 in {0, blk_k, 2*blk_k, ...} copy the contiguous slice W[r, k0 .. k0 + klen - 1] where klen = min(blk_k, cols - k0) into the destination row buffer. The order of elements within a row is unchanged, merely grouped by contiguous blk_k segments.
Performance note:
This packing does not introduce padding; the last block is short.
Consumers can use blk_k as an inner-loop tile when iterating K.
Cache interaction:
If cache_path is non-NULL and a readable file exists with exactly rows*cols floats, the function loads it and returns immediately.
Otherwise the function computes the layout, attempts to save it atomically to cache_path (if provided), and returns the new buffer.
Parameters
W Pointer to row-major input matrix (rows x cols).
rows Number of rows in W.
cols Number of columns in W.
blk_k Column block size (>= 1).
cache_path Optional filename for cache read/write (may be NULL).
out Output descriptor to be filled on success.
Returns
0 on success (with out->data != NULL); -1 on invalid args or OOM.
Definition at line 169 of file pretranspose.c.
{
  if (!W || !out || rows == 0 || cols == 0 || blk_k == 0) return -1;
  float *buf = NULL;
  if (cache_path && load_cache(cache_path, rows, cols, &buf) == 0) {
    out->rows = rows;
    out->cols = cols;
    out->blk_k = blk_k;
    out->data = buf;
    return 0;
  }
  buf = (float *)malloc(rows * cols * sizeof(float));
  if (!buf) return -1;
  for (size_t r = 0; r < rows; ++r) {
    const float *src_row = W + r * cols;
    float *dst_row = buf + r * cols;
    size_t written = 0;
    for (size_t k0 = 0; k0 < cols; k0 += blk_k) {
      const size_t klen = (k0 + blk_k <= cols) ? blk_k : (cols - k0);
      memcpy(dst_row + written, src_row + k0, klen * sizeof(float));
      written += klen;
    }
  }
  if (cache_path) {
    (void)save_cache_atomic(cache_path, buf, rows, cols);
  }
  out->rows = rows;
  out->cols = cols;
  out->blk_k = blk_k;
  out->data = buf;
  return 0;
}
References ie_gemv_rowwise_f32_kernel(), load_cache(), and save_cache_atomic().
ie_layout_cache_name()
int ie_layout_cache_name (const char * base_path, const char * tag, size_t rows, size_t cols, size_t blk_k, char * out_buf, size_t out_cap)
Create a filename for the on-disk cache of a blocked matrix.
Parameters
base_path Path to original weights file (used to namespace cache).
tag Short tag like "wxh" or "woh".
rows Row count.
cols Column count.
blk_k Column block size.
out_buf Output buffer for the resulting path string.
out_cap Capacity of out_buf including NUL terminator.
Returns
0 on success; -1 if arguments are invalid or buffer is too small.
The generated name is deterministic and includes the structural parameters so that changes in shape or block-size naturally invalidate older caches.
Parameters
base_path Path or stem to namespace the cache (may be NULL/empty).
tag Short, human-readable tag (e.g., "wxh", "woh").
rows Row count in the logical matrix.
cols Column count in the logical matrix.
blk_k Column block size used for packing.
out_buf Destination buffer for the resulting path.
out_cap Capacity of out_buf in bytes (including NUL).
Returns
0 on success; -1 on invalid arguments or buffer too small.
Definition at line 48 of file pretranspose.c.
{
  if (!tag || !out_buf || out_cap < 8) return -1;
  const char *stem = (base_path && *base_path) ? base_path : "weights.bin";
  int n = snprintf(out_buf, out_cap, "%s.%s.r%zu.c%zu.bk%zu.cache.bin",
                   stem, tag, rows, cols, blk_k);
  return (n > 0 && (size_t)n < out_cap) ? 0 : -1;
}
References ie_gemv_rowwise_f32_kernel().
ie_layout_free()
void ie_layout_free (ie_wblocked_desc_t * desc)
Free resources owned by a blocked descriptor.
Parameters
desc Descriptor to free (NULL allowed).
Free resources owned by a blocked descriptor.
Safe to call with NULL. After the call, desc fields are zeroed.
Parameters
desc Descriptor pointer (may be NULL).
Definition at line 217 of file pretranspose.c.
{
  if (!desc) return;
  free(desc->data);
  desc->data = NULL;
  desc->rows = 0;
  desc->cols = 0;
  desc->blk_k = 0;
}
References ie_gemv_rowwise_f32_kernel().