Inference Engine (Clocher): engine/src/ie_kv_instrumentation.c File Reference
ie_kv_instrumentation.c File Reference
FIFO-set based KV cache hit/miss counters (single-threaded).
#include "ie_kv_instrumentation.h"
#include <assert.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct ie_kv_state_t
Functions
static size_t env_size (const char *name, size_t defv)
Strict-decimal environment reader with fallback.
static int kv_contains (uint32_t token)
Linear membership test in the FIFO set.
static void kv_insert_fifo (uint32_t token)
Insert token into the FIFO set, evicting the oldest if full.
int ie_kv_begin_round (void)
Initialize KV counters and allocate a token set for the round.
void ie_kv_on_token (uint32_t token)
Report a produced token to the KV tracker.
void ie_kv_finish_round (uint64_t total_tokens, uint64_t *out_hits, uint64_t *out_misses)
Finalize the round and return hit/miss counters.
Variables
static ie_kv_state_t g_kv
Detailed Description
FIFO-set based KV cache hit/miss counters (single-threaded).
See ie_kv_instrumentation.h for the high-level description.
Definition in file ie_kv_instrumentation.c.
Function Documentation
env_size()
static size_t env_size (const char * name, size_t defv) static
Strict-decimal environment reader with fallback.
Parameters
name Env var name.
defv Default value when unset/invalid.
Returns
Parsed non-negative value.
Definition at line 45 of file ie_kv_instrumentation.c.
{
  const char *s = getenv(name);
  if (!s || !*s) return defv;
  char *end = NULL;
  long long v = strtoll(s, &end, 10);
  if (end == s || (end && *end)) return defv;
  if (v <= 0) return defv;
  return (size_t)v;
}
Referenced by ie_kv_begin_round().
ie_kv_begin_round()
int ie_kv_begin_round (void)
Initialize KV counters and allocate a token set for the round.
Capacity is read from the environment variable IE_KV_CAP if present; otherwise a default capacity of 4096 tokens is used. Passing this function multiple times resets the state (counters and set) for a new round.
Returns
0 on success; non-zero on allocation failure.
Definition at line 87 of file ie_kv_instrumentation.c.
{
  /* Reset counters and (re)allocate set as needed. */
  const size_t cap = env_size("IE_KV_CAP", 4096); /* default: 4K tokens */
  if (g_kv.slots && g_kv.capacity != cap) {
    free(g_kv.slots);
    g_kv.slots = NULL;
  }
  if (!g_kv.slots) {
    g_kv.slots = (uint32_t *)malloc(sizeof(uint32_t) * cap);
    if (!g_kv.slots) {
      g_kv.capacity = 0;
      g_kv.count = g_kv.head = 0;
      g_kv.hits = g_kv.misses = 0;
      g_kv.ready = 0;
      return -1;
    }
  }
  g_kv.capacity = cap;
  g_kv.count = 0;
  g_kv.head = 0;
  g_kv.hits = 0;
  g_kv.misses = 0;
  g_kv.ready = 1;
  return 0;
}
References ie_kv_state_t::capacity, ie_kv_state_t::count, env_size(), g_kv, ie_kv_state_t::head, ie_kv_state_t::hits, ie_gemv_rowwise_f32_kernel(), ie_kv_state_t::misses, ie_kv_state_t::ready, and ie_kv_state_t::slots.
Referenced by main().
ie_kv_finish_round()
void ie_kv_finish_round (uint64_t total_tokens, uint64_t * out_hits, uint64_t * out_misses)
Finalize the round and return hit/miss counters.
If no tokens were reported (counters are both zero) but total_tokens is non-zero, this function conservatively assumes all tokens were misses.
This call also frees any internal buffers allocated by ie_kv_begin_round().
Parameters
total_tokens Total tokens generated in the round (for fallback).
out_hits Output: total hit count (non-NULL).
out_misses Output: total miss count (non-NULL).
Definition at line 123 of file ie_kv_instrumentation.c.
{
  assert(out_hits   != NULL);
  assert(out_misses != NULL);
  if (!g_kv.ready) {
    /* Not initialized: conservative fallback. */
    *out_hits = 0;
    *out_misses = total_tokens;
    return;
  }
  /* Fallback if no tokens were observed but caller claims otherwise. */
  uint64_t hits   = g_kv.hits;
  uint64_t misses = g_kv.misses;
  if ((hits + misses) == 0 && total_tokens > 0) {
    misses = total_tokens;
  }
  *out_hits   = hits;
  *out_misses = misses;
  /* Free the set to keep memory footprint low across short-lived runs. */
  free(g_kv.slots);
  g_kv.slots = NULL;
  g_kv.capacity = g_kv.count = g_kv.head = 0;
  g_kv.hits = g_kv.misses = 0;
  g_kv.ready = 0;
}
References ie_kv_state_t::capacity, ie_kv_state_t::count, g_kv, ie_kv_state_t::head, ie_kv_state_t::hits, ie_gemv_rowwise_f32_kernel(), ie_kv_state_t::misses, ie_kv_state_t::ready, and ie_kv_state_t::slots.
Referenced by main().
ie_kv_on_token()
void ie_kv_on_token (uint32_t token)
Report a produced token to the KV tracker.
If the token is already present in the FIFO set, this increments the hit counter. Otherwise it increments miss and inserts the token (evicting the oldest element when the set is full).
Parameters
token 32-bit token identifier generated by the model.
Definition at line 113 of file ie_kv_instrumentation.c.
{
  if (!g_kv.ready || g_kv.capacity == 0) return;
  if (kv_contains(token)) {
    g_kv.hits++;
    return;
  }
  g_kv.misses++;
  kv_insert_fifo(token);
}
References ie_kv_state_t::capacity, g_kv, ie_kv_state_t::hits, ie_gemv_rowwise_f32_kernel(), kv_contains(), kv_insert_fifo(), ie_kv_state_t::misses, and ie_kv_state_t::ready.
kv_contains()
static int kv_contains (uint32_t token) static
Linear membership test in the FIFO set.
Parameters
token Token to check.
Returns
1 if found, 0 otherwise.
Definition at line 61 of file ie_kv_instrumentation.c.
{
  for (size_t i = 0; i < g_kv.count; ++i) {
    if (g_kv.slots[i] == token) return 1;
  }
  return 0;
}
References ie_kv_state_t::count, g_kv, and ie_kv_state_t::slots.
Referenced by ie_kv_on_token().
kv_insert_fifo()
static void kv_insert_fifo (uint32_t token) static
Insert token into the FIFO set, evicting the oldest if full.
Parameters
token Token to insert.
Definition at line 73 of file ie_kv_instrumentation.c.
{
  if (g_kv.capacity == 0) return;
  if (g_kv.count < g_kv.capacity) {
    g_kv.slots[g_kv.count++] = token;
  } else {
    /* Evict oldest at head, write new token, advance head */
    g_kv.slots[g_kv.head] = token;
    g_kv.head = (g_kv.head + 1) % g_kv.capacity;
  }
}
References ie_kv_state_t::capacity, ie_kv_state_t::count, g_kv, ie_kv_state_t::head, ie_gemv_rowwise_f32_kernel(), and ie_kv_state_t::slots.
Referenced by ie_kv_on_token().
Variable Documentation
g_kv
ie_kv_state_t g_kv static
Definition at line 33 of file ie_kv_instrumentation.c.
Referenced by ie_kv_begin_round(), ie_kv_finish_round(), ie_kv_on_token(), kv_contains(), and kv_insert_fifo().