Inference Engine (Clocher): engine/include/ie_device.h File Reference
ie_device.h File Reference
Device abstraction for CPU/GPU backends selected at runtime.
#include <stddef.h>
#include <stdint.h>
Data Structures
struct ie_device_caps
Capabilities reported by a device backend.
Typedefs
typedef enum ie_device_kind ie_device_kind_t
Device kinds supported by the abstraction layer.
typedef struct ie_device ie_device_t
Opaque device handle (implementation-specific).
typedef struct ie_block_sparse_matrix ie_block_sparse_matrix_t
Forward declaration of block-sparse matrix descriptor.
typedef struct ie_device_caps ie_device_caps_t
Capabilities reported by a device backend.
Enumerations
enum ie_device_kind { IE_DEV_CPU = 0 , IE_DEV_CUDA = 1 , IE_DEV_ZE = 2 }
Device kinds supported by the abstraction layer.
Functions
int ie_device_create (ie_device_kind_t kind, ie_device_t **out_dev)
Create a device handle for the requested kind (with fallback).
void ie_device_destroy (ie_device_t *dev)
Destroy a device handle and release resources.
int ie_device_caps (const ie_device_t *dev, ie_device_caps_t *out_caps)
Query device capabilities.
ie_device_kind_t ie_device_kind (const ie_device_t *dev)
Return the logical kind of a device handle.
int ie_device_gemv_f32 (ie_device_t *dev, const float *W, const float *x, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k)
Device-side GEMV (FP32): y = W * x (+ optional bias).
int ie_device_gemv_q4_0_f32 (ie_device_t *dev, const uint8_t *w_q4, const uint8_t *w_scales, size_t scale_bytes, const float *x, float *y, size_t rows, size_t cols, const uint16_t *bias_bf16)
Device-side GEMV (Q4_0 weights, FP32 activations).
int ie_device_gemv_block_sparse_f32 (ie_device_t *dev, const ie_block_sparse_matrix_t *m, const float *x, float *y, const float *bias)
Block-sparse GEMV (FP32): y = W * x (+ optional bias).
int ie_device_memcpy (ie_device_t *dev, void *dst, const void *src, size_t nbytes)
Copy memory using the device backend.
ie_device_kind_t ie_device_kind_from_str (const char *s)
Parse a device kind from a string.
Detailed Description
Device abstraction for CPU/GPU backends selected at runtime.
Definition in file ie_device.h.
Typedef Documentation
ie_block_sparse_matrix_t
typedef struct ie_block_sparse_matrix ie_block_sparse_matrix_t
Forward declaration of block-sparse matrix descriptor.
The full definition lives in sparse_format.h. This forward declaration is sufficient for pointer-based APIs.
Definition at line 36 of file ie_device.h.
ie_device_caps_t
typedef struct ie_device_caps ie_device_caps_t
Capabilities reported by a device backend.
ie_device_kind_t
typedef enum ie_device_kind ie_device_kind_t
Device kinds supported by the abstraction layer.
ie_device_t
typedef struct ie_device ie_device_t
Opaque device handle (implementation-specific).
Definition at line 28 of file ie_device.h.
Enumeration Type Documentation
ie_device_kind
enum ie_device_kind
Device kinds supported by the abstraction layer.
Enumerator
IE_DEV_CPU
CPU backend (always available).
IE_DEV_CUDA
NVIDIA CUDA backend (loaded via dlopen at runtime).
IE_DEV_ZE
oneAPI Level Zero backend (loaded via dlopen).
Definition at line 19 of file ie_device.h.
{
  IE_DEV_CPU = 0,
  IE_DEV_CUDA = 1,
  IE_DEV_ZE   = 2
} ie_device_kind_t;
Function Documentation
ie_device_caps()
int ie_device_caps (const ie_device_t * dev, ie_device_caps_t * out_caps)
Query device capabilities.
Parameters
dev Device handle.
out_caps Output capabilities structure (non-NULL).
Returns
0 on success; non-zero on error.
Definition at line 615 of file ie_device_common.c.
{
  if (!dev || !out_caps) return -1;
  return dev->vt.caps ? dev->vt.caps(dev->impl, out_caps) : -2;
}
References ie_device_vtbl::caps, ie_device::impl, and ie_device::vt.
ie_device_create()
int ie_device_create (ie_device_kind_t kind, ie_device_t ** out_dev)
Create a device handle for the requested kind (with fallback).
If the requested GPU backend is unavailable at runtime, a CPU device is created instead so that inference can proceed.
Parameters
kind Requested device kind.
out_dev Output: device handle on success (non-NULL).
Returns
0 on success; non-zero on error.
Create a device handle for the requested kind (with fallback).
If CUDA is requested and cannot be initialized, this returns an error to avoid producing CPU output labeled as CUDA.
Definition at line 554 of file ie_device_common.c.
{
  if (!out_dev) return -1;
  ie_device_t *d = (ie_device_t*)calloc(1, sizeof(*d));
  if (!d) return -2;
  if (kind == IE_DEV_CPU) {
    cpu_impl_t *ci = cpu_new();
    if (!ci) {
      free(d);
      return -3;
    }
    d->impl                     = ci;
    d->vt.caps                  = cpu_caps;
    d->vt.gemv_f32              = cpu_gemv_f32;
    d->vt.gemv_q4_0_f32          = cpu_gemv_q4_0_f32;
    d->vt.memcpy                = cpu_memcpy;
    d->vt.gemv_block_sparse_f32 = cpu_gemv_block_sparse_f32;
    d->vt.destroy               = cpu_destroy;
    d->kind                     = IE_DEV_CPU;
    *out_dev = d;
    return 0;
  }
  if (kind == IE_DEV_CUDA) {
    if (cuda_try_create(&d->impl, &d->vt) != 0) {
      free(d);
      return -4;
    }
    d->kind = IE_DEV_CUDA;
    *out_dev = d;
    return 0;
  }
  if (kind == IE_DEV_ZE) {
    if (ze_try_create(&d->impl, &d->vt) != 0) {
      free(d);
      return -5;
    }
    d->kind = IE_DEV_ZE;
    *out_dev = d;
    return 0;
  }
  free(d);
  return -6;
}
References ie_device_vtbl::caps, cpu_caps(), cpu_destroy(), cpu_gemv_block_sparse_f32(), cpu_gemv_f32(), cpu_gemv_q4_0_f32(), cpu_memcpy(), cpu_new(), cuda_try_create(), ie_device_vtbl::destroy, ie_device_vtbl::gemv_block_sparse_f32, ie_device_vtbl::gemv_f32, ie_device_vtbl::gemv_q4_0_f32, IE_DEV_CPU, IE_DEV_CUDA, IE_DEV_ZE, ie_device::impl, ie_device::kind, ie_device_vtbl::memcpy, ie_device::vt, and ze_try_create().
Referenced by ie_engine_create(), test_cpu_caps(), and test_gpu_fallback().
ie_device_destroy()
void ie_device_destroy (ie_device_t * dev)
Destroy a device handle and release resources.
Parameters
dev Device handle previously created by ie_device_create().
Destroy a device handle and release resources.
Definition at line 606 of file ie_device_common.c.
{
  if (!dev) return;
  if (dev->vt.destroy) dev->vt.destroy(dev->impl);
  free(dev);
}
References ie_device_vtbl::destroy, ie_device::impl, and ie_device::vt.
Referenced by ie_engine_create(), ie_engine_destroy(), test_cpu_caps(), and test_gpu_fallback().
ie_device_gemv_block_sparse_f32()
int ie_device_gemv_block_sparse_f32 (ie_device_t * dev, const ie_block_sparse_matrix_t * m, const float * x, float * y, const float * bias)
Block-sparse GEMV (FP32): y = W * x (+ optional bias).
This entry point operates on matrices stored in block-row CSR (BSR) layout described by ie_block_sparse_matrix_t. Backends are free to implement native sparse kernels; if a backend does not implement this method, the implementation falls back to a CPU block-sparse kernel when possible.
Parameters
dev Device handle.
m Block-sparse matrix descriptor (must be fully initialized).
x Input vector of length m->cols.
y Output vector of length m->rows.
bias Optional bias vector of length m->rows (may be NULL).
Returns
0 on success; non-zero if unimplemented or error.
Block-sparse GEMV (FP32): y = W * x (+ optional bias).
Definition at line 651 of file ie_device_common.c.
{
  if (!dev || !dev->vt.gemv_block_sparse_f32) return -1;
  return dev->vt.gemv_block_sparse_f32(dev->impl, m, x, y, bias);
}
References ie_device_vtbl::gemv_block_sparse_f32, ie_device::impl, and ie_device::vt.
ie_device_gemv_f32()
int ie_device_gemv_f32 (ie_device_t * dev, const float * W, const float * x, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k)
Device-side GEMV (FP32): y = W * x (+ optional bias).
Dimensions: W is (rows x cols), x is (cols), y is (rows). Backends may copy buffers or operate in-place if memory is resident on the device.
Parameters
dev Device handle.
W Row-major FP32 weights matrix of size rows*cols.
x FP32 input vector of length cols.
y FP32 output vector of length rows.
rows Number of rows in W (and y).
cols Number of columns in W (and x).
bias Optional FP32 bias vector of length rows (NULL if none).
blk_k Optional blocked-K hint (0 to ignore).
Returns
0 on success; non-zero if unimplemented or error.
Device-side GEMV (FP32): y = W * x (+ optional bias).
Definition at line 623 of file ie_device_common.c.
{
  if (!dev || !dev->vt.gemv_f32) return -1;
  return dev->vt.gemv_f32(dev->impl, W, x, y, rows, cols, bias, blk_k);
}
References ie_device_vtbl::gemv_f32, ie_device::impl, and ie_device::vt.
Referenced by test_gpu_fallback().
ie_device_gemv_q4_0_f32()
int ie_device_gemv_q4_0_f32 (ie_device_t * dev, const uint8_t * w_q4, const uint8_t * w_scales, size_t scale_bytes, const float * x, float * y, size_t rows, size_t cols, const uint16_t * bias_bf16)
Device-side GEMV (Q4_0 weights, FP32 activations).
The Q4_0 layout matches ie_gemv_q4_0_f32() (see ie_kernels.h).
Parameters
dev Device handle.
w_q4 Packed Q4_0 weights.
w_scales Per-block scales (BF16 or log2_u8_q3).
scale_bytes Bytes per scale (1 or 2).
x FP32 input vector.
y FP32 output vector.
rows Rows.
cols Cols (multiple of 32).
bias_bf16 Optional BF16 bias vector (rows) or NULL.
Returns
0 on success; non-zero on error.
Device-side GEMV (Q4_0 weights, FP32 activations).
Definition at line 634 of file ie_device_common.c.
{
  if (!dev || !dev->vt.gemv_q4_0_f32) return -1;
  return dev->vt.gemv_q4_0_f32(dev->impl, w_q4, w_scales, scale_bytes,
                              x, y, rows, cols, bias_bf16);
}
References ie_device_vtbl::gemv_q4_0_f32, ie_device::impl, and ie_device::vt.
ie_device_kind()
ie_device_kind_t ie_device_kind (const ie_device_t * dev)
Return the logical kind of a device handle.
Parameters
dev Device handle.
Returns
Device kind (CPU, CUDA, ZE).
Return the logical kind of a device handle.
Definition at line 671 of file ie_device_common.c.
{
  if (!dev) return IE_DEV_CPU;
  return dev->kind;
}
References IE_DEV_CPU, and ie_device::kind.
ie_device_kind_from_str()
ie_device_kind_t ie_device_kind_from_str (const char * s)
Parse a device kind from a string.
Accepts "cpu", "cuda", "ze" (case-insensitive). Unknown strings return CPU.
Parameters
s Input string (may be NULL).
Returns
Parsed device kind (defaults to IE_DEV_CPU).
Parse a device kind from a string.
Definition at line 679 of file ie_device_common.c.
{
  if (!s) return IE_DEV_CPU;
  char tmp[16] = {0};
  size_t n = strlen(s);
  if (n >= sizeof(tmp)) n = sizeof(tmp) - 1;
  for (size_t i = 0; i < n; ++i) {
    tmp[i] = (char)tolower((unsigned char)s[i]);
  }
  if (!strcmp(tmp, "cpu"))  return IE_DEV_CPU;
  if (!strcmp(tmp, "cuda")) return IE_DEV_CUDA;
  if (!strcmp(tmp, "ze"))   return IE_DEV_ZE;
  return IE_DEV_CPU;
}
References IE_DEV_CPU, IE_DEV_CUDA, and IE_DEV_ZE.
Referenced by ie_engine_create(), and test_kind_parse().
ie_device_memcpy()
int ie_device_memcpy (ie_device_t * dev, void * dst, const void * src, size_t nbytes)
Copy memory using the device backend.
For CPU this is a plain memcpy; for GPU this would schedule host/device copies when implemented. Direction is backend-defined for now.
Parameters
dev Device handle.
dst Destination pointer (host pointer in current implementation).
src Source pointer (host pointer in current implementation).
nbytes Number of bytes to copy.
Returns
0 on success; non-zero on error.
Copy memory using the device backend.
Definition at line 663 of file ie_device_common.c.
{
  if (!dev || !dev->vt.memcpy) return -1;
  return dev->vt.memcpy(dev->impl, dst, src, nbytes);
}
References ie_device::impl, ie_device_vtbl::memcpy, and ie_device::vt.