Inference Engine (Clocher): engine/include/ie_stream.h File Reference
ie_stream.h File Reference
Portable wrappers for controlled prefetching and non-temporal (streaming) stores.
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
Data Structures
struct ie_stream_policy
Policy controlling prefetch and streaming behavior.
Macros
#define IE_CACHELINE_BYTES 64u
Conventional cache line size used for distance heuristics (bytes).
Functions
int ie_stream_policy_init (struct ie_stream_policy *p)
Initialize policy with detected cache sizes and sane defaults.
bool ie_stream_should_use_nt (size_t bytes, const struct ie_stream_policy *p)
Decide if non-temporal stores should be used for a given transfer size.
size_t ie_stream_recommend_prefetch_distance (const struct ie_stream_policy *p, size_t stride_bytes)
Recommend a prefetch distance in bytes for the given stride.
void ie_stream_prefetch_t0 (const void *base, size_t distance)
Issue a T0 (cache-hot) prefetch distance bytes ahead of base.
void ie_stream_prefetch_nta (const void *base, size_t distance)
Issue a non-temporal (NTA) prefetch distance bytes ahead of base.
void ie_stream_prefetch_range_t0 (const void *base, size_t bytes, size_t stride, size_t distance)
Prefetch a range using T0 hint at a given stride and lead distance.
void ie_stream_prefetch_range_nta (const void *base, size_t bytes, size_t stride, size_t distance)
Prefetch a range using NTA hint at a given stride and lead distance.
void ie_stream_copy_f32 (float *dst, const float *src, size_t n, const struct ie_stream_policy *p, double nt_ratio)
Copy n floats from src to dst using optional non-temporal stores.
void ie_stream_memset_f32 (float *dst, float value, size_t n, const struct ie_stream_policy *p, double nt_ratio)
Set n floats at dst to value using optional non-temporal stores.
Detailed Description
Portable wrappers for controlled prefetching and non-temporal (streaming) stores.
This header provides:
Thin wrappers around _mm_prefetch with cache-level hints.
Heuristics for choosing prefetch distances and when to use non-temporal stores.
High-level streaming copy/set helpers that mix regular and streaming stores via a ratio.
Design notes (safety & portability):
All intrinsics are guarded by architecture macros. On non-x86 or when a feature is unavailable at compile time, safe scalar fallbacks are used.
Streaming stores require attention to alignment for best results. The helpers handle a small scalar "prologue/epilogue" to avoid alignment faults and still benefit from wide stores on the bulk region when available.
Prefetching uses byte distances relative to the base pointer. Distances should be chosen as multiples of the cache line size (commonly 64 bytes on x86).
Environment variables (optional):
IE_STREAM_PREFETCH=<bytes> : override recommended prefetch distance.
IE_STREAM_NT_THRESHOLD=<bytes> : size threshold above which non-temporal stores are preferred.
IE_STREAM_FORCE_NT=0/1 : force-disable or force-enable streaming stores.
Definition in file ie_stream.h.
Macro Definition Documentation
IE_CACHELINE_BYTES
#define IE_CACHELINE_BYTES 64u
Conventional cache line size used for distance heuristics (bytes).
Definition at line 38 of file ie_stream.h.
Function Documentation
ie_stream_copy_f32()
void ie_stream_copy_f32 (float * dst, const float * src, size_t n, const struct ie_stream_policy * p, double nt_ratio)
Copy n floats from src to dst using optional non-temporal stores.
If ie_stream_should_use_nt decides for streaming, the function uses wide non-temporal stores when available (AVX2/AVX-512). The nt_ratio allows mixing regular and streaming stores (e.g., 0.5 means half of the bulk uses streaming). For small tails or when features are unavailable, a scalar fallback is used.
Parameters
dst Destination pointer (non-null).
src Source pointer (non-null).
n Number of float elements to copy.
p Non-null policy pointer.
nt_ratio Fraction in [0,1]; 0=never stream, 1=always stream (when allowed).
Copy n floats from src to dst using optional non-temporal stores.
The function uses policy thresholds plus nt_ratio to decide whether to use non-temporal streaming stores. If nt_ratio is 0, the function forces a scalar copy even if the policy would otherwise stream.
Parameters
dst Destination float array.
src Source float array.
n Number of float elements.
p Stream policy (must be non-NULL).
nt_ratio Ratio in [0,1]; 0 disables NT, >0 enables if policy allows.
Definition at line 543 of file stream.c.
{
  if (!dst || !src || !p) return;
  const size_t bytes = n * sizeof(float);
  const bool want_nt =
      ie_stream_should_use_nt(bytes, p) && (ie_clamp01(nt_ratio) > 0.0);
  if (!want_nt) {
    ie_scalar_copy_f32(dst, src, n);
    return;
  }
#if IE_X86
  const struct ie_cpu_features *f = ie_stream_cpu_features();
  /* Field names are expected to match ie_cpu_features_detect() output. */
  if (f && f->avx512f) {
    ie_nt_copy_f32_avx512(dst, src, n);
    return;
  }
  if (f && f->avx2) {
    ie_nt_copy_f32_avx2(dst, src, n);
    return;
  }
#endif
  ie_scalar_copy_f32(dst, src, n);
}
References ie_cpu_features::avx2, ie_cpu_features::avx512f, ie_clamp01(), ie_scalar_copy_f32(), and ie_stream_should_use_nt().
Referenced by main().
ie_stream_memset_f32()
void ie_stream_memset_f32 (float * dst, float value, size_t n, const struct ie_stream_policy * p, double nt_ratio)
Set n floats at dst to value using optional non-temporal stores.
Parameters
dst Destination pointer (non-null).
value Value to set.
n Number of float elements to set.
p Non-null policy pointer.
nt_ratio Fraction in [0,1] controlling the mix of streaming stores.
Set n floats at dst to value using optional non-temporal stores.
The function uses policy thresholds plus nt_ratio to decide whether to use non-temporal streaming stores. If nt_ratio is 0, the function forces a scalar set even if the policy would otherwise stream.
Parameters
dst Destination float array.
value Value to write.
n Number of float elements.
p Stream policy (must be non-NULL).
nt_ratio Ratio in [0,1]; 0 disables NT, >0 enables if policy allows.
Definition at line 587 of file stream.c.
{
  if (!dst || !p) return;
  const size_t bytes = n * sizeof(float);
  const bool want_nt =
      ie_stream_should_use_nt(bytes, p) && (ie_clamp01(nt_ratio) > 0.0);
  if (!want_nt) {
    ie_scalar_set_f32(dst, value, n);
    return;
  }
#if IE_X86
  const struct ie_cpu_features *f = ie_stream_cpu_features();
  /* Field names are expected to match ie_cpu_features_detect() output. */
  if (f && f->avx512f) {
    ie_nt_set_f32_avx512(dst, value, n);
    return;
  }
  if (f && f->avx2) {
    ie_nt_set_f32_avx2(dst, value, n);
    return;
  }
#endif
  ie_scalar_set_f32(dst, value, n);
}
References ie_cpu_features::avx2, ie_cpu_features::avx512f, ie_clamp01(), ie_scalar_set_f32(), and ie_stream_should_use_nt().
ie_stream_policy_init()
int ie_stream_policy_init (struct ie_stream_policy * p)
Initialize policy with detected cache sizes and sane defaults.
The function attempts to read cache sizes from Linux sysfs and then applies internal heuristics to set prefetch_distance and nt_threshold_bytes. Environment variables listed in the file header override the computed values.
Parameters
[out] p Non-null policy to be initialized.
Returns
0 on success; negative value on error (e.g., invalid pointer).
Initialize policy with detected cache sizes and sane defaults.
Cache detection is best-effort (Linux sysfs). If detection fails, conservative defaults are used:
L1D: 32 KiB
L2: 1 MiB
L3: 8 MiB
Defaults:
prefetch_distance: 6 cache lines
nt_threshold_bytes: 2x LLC
Env overrides:
IE_STREAM_PREFETCH
IE_STREAM_NT_THRESHOLD
IE_STREAM_FORCE_NT
Parameters
p Output policy to initialize.
Returns
0 on success, or -EINVAL on invalid arguments.
Definition at line 199 of file stream.c.
{
  if (!p) return -EINVAL;
  memset(p, 0, sizeof *p);
  size_t l1 = 0, l2 = 0, l3 = 0;
  ie_detect_caches_linux(&l1, &l2, &l3);
  p->l1_bytes = l1;
  p->l2_bytes = l2;
  p->l3_bytes = l3;
  if (p->l1_bytes == 0) p->l1_bytes = 32u * 1024u;
  if (p->l2_bytes == 0) p->l2_bytes = 1u * 1024u * 1024u;
  if (p->l3_bytes == 0) p->l3_bytes = 8u * 1024u * 1024u;
  p->prefetch_distance = 6u * IE_CACHELINE_BYTES;
  p->nt_threshold_bytes = 2u * p->l3_bytes;
  p->prefetch_hint = 0;
  p->enable_prefetch = true;
  p->force_nt_on = false;
  p->force_nt_off = false;
  const char *s = NULL;
  s = getenv("IE_STREAM_PREFETCH");
  if (s && *s) {
    size_t v = (size_t)strtoull(s, NULL, 10);
    if (v > 0) p->prefetch_distance = v;
  }
  s = getenv("IE_STREAM_NT_THRESHOLD");
  if (s && *s) {
    size_t v = (size_t)strtoull(s, NULL, 10);
    if (v > 0) p->nt_threshold_bytes = v;
  }
  /* IE_STREAM_FORCE_NT:
   *  - "1" => always use non-temporal stores
   *  - "0" => never use non-temporal stores
   *  - otherwise => ignore (keep heuristic)
   */
  s = getenv("IE_STREAM_FORCE_NT");
  if (s && *s) {
    int v = atoi(s);
    if (v == 1) {
      p->force_nt_on = true;
      p->force_nt_off = false;
    } else if (v == 0) {
      p->force_nt_on = false;
      p->force_nt_off = true;
    }
  }
  return 0;
}
References ie_stream_policy::enable_prefetch, ie_stream_policy::force_nt_off, ie_stream_policy::force_nt_on, IE_CACHELINE_BYTES, ie_detect_caches_linux(), ie_stream_policy::l1_bytes, ie_stream_policy::l2_bytes, ie_stream_policy::l3_bytes, ie_stream_policy::nt_threshold_bytes, ie_stream_policy::prefetch_distance, and ie_stream_policy::prefetch_hint.
Referenced by main().
ie_stream_prefetch_nta()
void ie_stream_prefetch_nta (const void * base, size_t distance)
Issue a non-temporal (NTA) prefetch distance bytes ahead of base.
Parameters
base Base address (non-null).
distance Lead distance in bytes (can be zero).
Issue a non-temporal (NTA) prefetch distance bytes ahead of base.
On non-x86 builds this function is a no-op.
Parameters
base Base pointer.
distance Byte offset from base to prefetch.
Definition at line 333 of file stream.c.
{
  const char *p = (const char *)base + distance;
#if IE_X86
  _mm_prefetch(p, _MM_HINT_NTA);
#else
  (void)p;
#endif
}
Referenced by ie_stream_prefetch_range_nta().
ie_stream_prefetch_range_nta()
void ie_stream_prefetch_range_nta (const void * base, size_t bytes, size_t stride, size_t distance)
Prefetch a range using NTA hint at a given stride and lead distance.
Parameters
base Range base (non-null).
bytes Range size in bytes.
stride Step in bytes between prefetches.
distance Lead distance in bytes.
Prefetch a range using NTA hint at a given stride and lead distance.
Walks the byte range [base, base+bytes) and issues prefetches at (current + distance), stepping by stride (or cacheline if stride==0).
Parameters
base Base pointer of the range.
bytes Number of bytes to cover.
stride Step size in bytes (0 => cacheline).
distance Prefetch lead distance in bytes.
Definition at line 375 of file stream.c.
{
  const char *c = (const char *)base;
  size_t step = (stride > 0 ? stride : IE_CACHELINE_BYTES);
  for (size_t off = 0; off < bytes; off += step) {
    ie_stream_prefetch_nta(c + off, distance);
  }
}
References IE_CACHELINE_BYTES, and ie_stream_prefetch_nta().
ie_stream_prefetch_range_t0()
void ie_stream_prefetch_range_t0 (const void * base, size_t bytes, size_t stride, size_t distance)
Prefetch a range using T0 hint at a given stride and lead distance.
Parameters
base Range base (non-null).
bytes Range size in bytes.
stride Step in bytes between prefetches (>= IE_CACHELINE_BYTES recommended).
distance Lead distance in bytes (see ie_stream_recommend_prefetch_distance).
Prefetch a range using T0 hint at a given stride and lead distance.
Walks the byte range [base, base+bytes) and issues prefetches at (current + distance), stepping by stride (or cacheline if stride==0).
Parameters
base Base pointer of the range.
bytes Number of bytes to cover.
stride Step size in bytes (0 => cacheline).
distance Prefetch lead distance in bytes.
Definition at line 354 of file stream.c.
{
  const char *c = (const char *)base;
  size_t step = (stride > 0 ? stride : IE_CACHELINE_BYTES);
  for (size_t off = 0; off < bytes; off += step) {
    ie_stream_prefetch_t0(c + off, distance);
  }
}
References IE_CACHELINE_BYTES, and ie_stream_prefetch_t0().
Referenced by main().
ie_stream_prefetch_t0()
void ie_stream_prefetch_t0 (const void * base, size_t distance)
Issue a T0 (cache-hot) prefetch distance bytes ahead of base.
Parameters
base Base address (non-null).
distance Lead distance in bytes (can be zero).
Issue a T0 (cache-hot) prefetch distance bytes ahead of base.
On non-x86 builds this function is a no-op.
Parameters
base Base pointer.
distance Byte offset from base to prefetch.
Definition at line 315 of file stream.c.
{
  const char *p = (const char *)base + distance;
#if IE_X86
  _mm_prefetch(p, _MM_HINT_T0);
#else
  (void)p;
#endif
}
Referenced by ie_stream_prefetch_range_t0().
ie_stream_recommend_prefetch_distance()
size_t ie_stream_recommend_prefetch_distance (const struct ie_stream_policy * p, size_t stride_bytes)
Recommend a prefetch distance in bytes for the given stride.
The recommendation considers the policy prefetch distance, stride size, and attempts to keep the lead within a few cache lines.
Parameters
p Non-null policy pointer.
stride_bytes Positive stride size in bytes.
Returns
Distance in bytes to pass to the prefetch helpers.
Recommend a prefetch distance in bytes for the given stride.
This clamps the configured distance to a practical range:
at least one cache line,
at most half of L1,
at least stride_bytes when stride_bytes is provided.
Parameters
p Policy (may be NULL).
stride_bytes Access stride in bytes (0 => assume cacheline stride).
Returns
Recommended prefetch lead distance in bytes.
Definition at line 289 of file stream.c.
{
  if (!p) return 4u * IE_CACHELINE_BYTES;
  size_t lead = p->prefetch_distance ? p->prefetch_distance
                                     : (6u * IE_CACHELINE_BYTES);
  if (lead < IE_CACHELINE_BYTES) lead = IE_CACHELINE_BYTES;
  if (lead > p->l1_bytes / 2u) lead = p->l1_bytes / 2u;
  if (stride_bytes > 0 && lead < stride_bytes) lead = stride_bytes;
  return lead;
}
References IE_CACHELINE_BYTES, ie_stream_policy::l1_bytes, and ie_stream_policy::prefetch_distance.
ie_stream_should_use_nt()
bool ie_stream_should_use_nt (size_t bytes, const struct ie_stream_policy * p)
Decide if non-temporal stores should be used for a given transfer size.
The decision observes force_nt_on and force_nt_off first; otherwise it compares bytes with nt_threshold_bytes.
Parameters
bytes Total transfer size in bytes.
p Non-null policy pointer.
Returns
true if non-temporal stores are recommended.
Decide if non-temporal stores should be used for a given transfer size.
The decision uses the policy threshold unless forced on/off via IE_STREAM_FORCE_NT.
Parameters
bytes Size of the memory operation in bytes.
p Policy (must be non-NULL).
Returns
true if non-temporal stores are recommended, else false.
Definition at line 269 of file stream.c.
{
  if (!p) return false;
  if (p->force_nt_on) return true;
  if (p->force_nt_off) return false;
  return bytes >= p->nt_threshold_bytes;
}
References ie_stream_policy::force_nt_off, ie_stream_policy::force_nt_on, and ie_stream_policy::nt_threshold_bytes.
Referenced by ie_stream_copy_f32(), and ie_stream_memset_f32().