Inference Engine (Clocher): engine/src/runtime/infer_gptoss.c File Reference
infer_gptoss.c File Reference
GPT-OSS inference entrypoints with a CPU-first forward pass.
#include <fcntl.h>
#include <limits.h>
#include <math.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
#include "ie_device.h"
#include "ie_infer.h"
#include "ie_kernels.h"
#include "ie_kv_cache.h"
#include "ie_kv_instrumentation.h"
#include "tensor_map.h"
Data Structures
struct ie_moe_w
Per-layer MoE weight views (router + expert matrices).
struct ie_gptoss_layer_w
Per-layer weight views for attention + MoE.
struct ie_gptoss_infer_impl
Internal GPT-OSS inference context.
struct ie_tensor_view
A resolved tensor pointer plus its descriptor.
Macros
#define _POSIX_C_SOURCE 200809L
#define IE_GPTOSS_RMS_EPS_DEFAULT (1e-5f)
Default RMSNorm epsilon (matches common HF defaults).
#define IE_GPTOSS_ROPE_THETA_DEFAULT (10000.0f)
Default RoPE theta (matches common HF defaults).
#define IE_GPTOSS_MOE_TOPK_DEFAULT (4u)
Default MoE routing top-k (most MoE LLMs use 4).
#define IE_LOGE(...) ie_logf(IE_LL_ERROR, __FILE__, __LINE__, __VA_ARGS__)
Emit an ERROR-level log line.
#define IE_LOGW(...) ie_logf(IE_LL_WARN, __FILE__, __LINE__, __VA_ARGS__)
Emit a WARN-level log line.
#define IE_LOGI(...) ie_logf(IE_LL_INFO, __FILE__, __LINE__, __VA_ARGS__)
Emit an INFO-level log line.
#define IE_LOGD(...) ie_logf(IE_LL_DEBUG, __FILE__, __LINE__, __VA_ARGS__)
Emit a DEBUG-level log line.
#define IE_LOGT(...) ie_logf(IE_LL_TRACE, __FILE__, __LINE__, __VA_ARGS__)
Emit a TRACE-level log line.
#define IE_WEAK
Weak symbol attribute fallback (no-op).
Typedefs
typedef struct ie_moe_w ie_moe_w_t
Per-layer MoE weight views (router + expert matrices).
typedef struct ie_gptoss_layer_w ie_gptoss_layer_w_t
Per-layer weight views for attention + MoE.
typedef struct ie_tensor_view ie_tensor_view_t
A resolved tensor pointer plus its descriptor.
Enumerations
enum {
IE_LL_QUIET = 0 , IE_LL_ERROR = 1 , IE_LL_WARN = 2 , IE_LL_INFO = 3 ,
IE_LL_DEBUG = 4 , IE_LL_TRACE = 5
}
Internal log levels (higher means more verbose).
Functions
static int ie_log_level (void)
Read IE_LOG_LEVEL once and cache the result.
static void ie_logf (int lvl, const char *file, int line, const char *fmt,...)
Print a formatted log line if the level is enabled.
void ie_gptoss_infer_destroy (ie_gptoss_infer_t *ctx)
Destroy an inference context.
static size_t ie_min_size (size_t a, size_t b)
Return the minimum of two size_t values.
static uint32_t ie_u32_min (uint32_t a, uint32_t b)
Return the minimum of two uint32_t values.
static char * ie_dirname_alloc (const char *path)
Allocate and return the directory portion of a path.
static char * ie_path_join_alloc (const char *a, const char *b)
Join two path components with exactly one slash.
static int ie_mmap_ro (const char *path, uint8_t **out_base, size_t *out_size)
Memory-map a file read-only.
static void ie_munmap_ro (uint8_t *base, size_t size)
Unmap a previously mapped read-only file.
static uint32_t ie_env_u32_clamped (const char *name, uint32_t def, uint32_t lo, uint32_t hi)
Parse an environment variable as uint32, with bounds and default.
static float ie_env_f32_clamped (const char *name, float def, float lo, float hi)
Parse an environment variable as float, with bounds and default.
static int ie_env_flag (const char *name)
Parse an environment variable as boolean.
static int ie_alloc_f32_from_bf16 (const uint16_t *src, size_t n, float **out)
Allocate and convert BF16 weights to FP32.
static float ie_bf16_to_f32 (uint16_t v)
Convert a BF16 value to float32.
static float ie_silu_f32 (float x)
SiLU activation function.
static int ie_debug_nan_enabled_ (void)
static int ie_trace_bf16_enabled_ (void)
static int ie_check_finite_f32_ (const float *v, size_t n, const char *tag, uint32_t layer, uint32_t pos)
static float ie_dot_f32 (const float *a, const float *b, size_t n)
Dot product of two float32 vectors.
static void ie_softmax_inplace_f32 (float *x, size_t n)
In-place softmax over an array of float32 values.
static const tensor_desc_t * ie_w_find (const tensor_map_t *tmap, const char *name)
Find a tensor descriptor by name in a tensor map.
static int ie_w_get_view (const struct ie_gptoss_infer_impl *impl, const char *name, ie_tensor_view_t *out)
Resolve a tensor pointer by name.
static int ie_w_get_first_view (const struct ie_gptoss_infer_impl *impl, const char *const *names, size_t count, ie_tensor_view_t *out)
Resolve the first tensor found among a list of candidate names.
static int ie_w_get_layer_fmt_view (const struct ie_gptoss_infer_impl *impl, uint32_t layer, const char *const *fmts, size_t count, ie_tensor_view_t *out, int required)
Resolve a layer tensor using a list of snprintf formats.
static int ie_require_size_eq (const tensor_desc_t *td, uint64_t want_bytes)
Require exact byte size for a tensor.
int ie_rmsnorm_cpu_f32 (const float *x, const float *w, size_t n, float eps, float *y)
RMSNorm (FP32) for a single vector.
static int ie_rmsnorm_cpu_f32_bf16w (const float *x, const uint16_t *w_bf16, size_t n, float eps, float *y)
int ie_rope_apply_f32 (float *q, float *k, size_t heads, size_t head_dim, uint32_t pos, float theta)
Apply Rotary Positional Embedding (RoPE) to Q and K for a single position.
int ie_attn_cpu_causal_f32 (const float *Q, const float *K, const float *V, size_t seq_len, size_t n_heads, size_t head_dim, float inv_sqrt_d, float *out, float *scores)
Causal self-attention (FP32 reference).
static void ie_attn_causal_gqa_f32 (const float *Q, const float *K, const float *V, uint32_t seq_len, uint32_t n_heads, uint32_t n_kv_heads, uint32_t head_dim, float inv_sqrt_d, float *out, float *scores)
static int ie_infer_n_experts_from_router (const tensor_desc_t *td_router_w, uint32_t d_model, uint32_t *out_n_experts)
static int ie_moe_expected_bytes (uint32_t n_experts, uint32_t rows, uint32_t cols, uint8_t scale_bytes, uint64_t *out_blocks_bytes, uint64_t *out_scales_bytes)
static int ie_q4_expected_bytes (uint32_t rows, uint32_t cols, uint8_t scale_bytes, uint64_t *out_blocks_bytes, uint64_t *out_scales_bytes)
static void ie_add_bias_f32 (float *dst, const float *bias, size_t n)
static int ie_resolve_moe_layer (struct ie_gptoss_infer_impl *impl, uint32_t l, ie_gptoss_layer_w_t *LW)
static int ie_resolve_q4_attn_weight (struct ie_gptoss_infer_impl *impl, uint32_t l, const char *const blocks_fmts[], const char *const scales_fmts[], uint32_t rows, uint32_t cols, const char *tag, const uint8_t **out_blocks, const uint8_t **out_scales, uint8_t *out_scale_bytes)
static int ie_forward_one_token (struct ie_gptoss_infer_impl *impl, ie_kv_cache *kv_layers, uint32_t token_id, uint32_t pos, float *out_logits)
int ie_gptoss_infer_create (const ie_device_t *dev_const, const ie_weights_t *w, const ie_gptoss_hparams_t *hp, ie_gptoss_infer_t **out_ctx)
Create an inference context.
int ie_gptoss_infer_prefill (ie_gptoss_infer_t *ctx, ie_kv_cache *kv, const uint32_t *prompt, uint32_t n_prompt, float *out_logits)
Prefill: consume a prompt, update the KV cache, and produce logits.
int ie_gptoss_infer_step (ie_gptoss_infer_t *ctx, ie_kv_cache *kv, uint32_t token_id, float *out_logits)
Step: consume one token, update the KV cache, and produce next logits.
void ie_gptoss_infer_reset (ie_gptoss_infer_t *ctx)
int ie_gptoss_infer_seek (ie_gptoss_infer_t *ctx, uint32_t pos)
uint32_t ie_gptoss_infer_pos (const ie_gptoss_infer_t *ctx)
uint32_t ie_gptoss_infer_get_pos (const ie_gptoss_infer_t *ctx)
Get the current position (number of tokens already consumed).
void ie_gptoss_infer_set_pos (ie_gptoss_infer_t *ctx, uint32_t pos)
Set the current position.
Variables
static int ie_log_level_cached = -1
Cached log level parsed from IE_LOG_LEVEL (negative means "unset").
Detailed Description
GPT-OSS inference entrypoints with a CPU-first forward pass.
This implementation is intentionally "tensor_map-minimal":
It does NOT require tensor_map.json to carry dtype/shape metadata.
It only requires (name, offset, size_bytes).
Safety:
We validate tensor sizes against hparams before using them.
We infer MoE n_experts from router weight size.
Notes:
This is correctness-first and CPU-only for BF16/Q4 paths.
Quant assumptions for expert blocks follow a Q4_0-like layout:
cols multiple of 32
blocks: 16 bytes per 32 weights (2x4-bit per byte)
scales: BF16 per block, or FP8(E4M3) packed as u8 per block
Logging:
This file prints detailed diagnostics to stderr on failure paths.
Set IE_LOG_LEVEL to control verbosity: 0=quiet, 1=error, 2=warn, 3=info, 4=debug, 5=trace
Hot-path logging is avoided; errors include rich context (tensor name, expected/actual sizes, layer index, and chosen candidate names).
Definition in file infer_gptoss.c.
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 33 of file infer_gptoss.c.
IE_GPTOSS_MOE_TOPK_DEFAULT
#define IE_GPTOSS_MOE_TOPK_DEFAULT (4u)
Default MoE routing top-k (most MoE LLMs use 4).
Definition at line 65 of file infer_gptoss.c.
IE_GPTOSS_RMS_EPS_DEFAULT
#define IE_GPTOSS_RMS_EPS_DEFAULT (1e-5f)
Default RMSNorm epsilon (matches common HF defaults).
Definition at line 61 of file infer_gptoss.c.
IE_GPTOSS_ROPE_THETA_DEFAULT
#define IE_GPTOSS_ROPE_THETA_DEFAULT (10000.0f)
Default RoPE theta (matches common HF defaults).
Definition at line 63 of file infer_gptoss.c.
IE_LOGD
#define IE_LOGD (...) ie_logf(IE_LL_DEBUG, __FILE__, __LINE__, __VA_ARGS__)
Emit a DEBUG-level log line.
Definition at line 142 of file infer_gptoss.c.
IE_LOGE
#define IE_LOGE (...) ie_logf(IE_LL_ERROR, __FILE__, __LINE__, __VA_ARGS__)
Emit an ERROR-level log line.
Definition at line 136 of file infer_gptoss.c.
IE_LOGI
#define IE_LOGI (...) ie_logf(IE_LL_INFO, __FILE__, __LINE__, __VA_ARGS__)
Emit an INFO-level log line.
Definition at line 140 of file infer_gptoss.c.
IE_LOGT
#define IE_LOGT (...) ie_logf(IE_LL_TRACE, __FILE__, __LINE__, __VA_ARGS__)
Emit a TRACE-level log line.
Definition at line 144 of file infer_gptoss.c.
IE_LOGW
#define IE_LOGW (...) ie_logf(IE_LL_WARN, __FILE__, __LINE__, __VA_ARGS__)
Emit a WARN-level log line.
Definition at line 138 of file infer_gptoss.c.
IE_WEAK
#define IE_WEAK
Weak symbol attribute fallback (no-op).
Definition at line 155 of file infer_gptoss.c.
Typedef Documentation
ie_gptoss_layer_w_t
typedef struct ie_gptoss_layer_w ie_gptoss_layer_w_t
Per-layer weight views for attention + MoE.
All attention weights are BF16 (HF-style linear layout [out, in]). MoE expert weights are Q4_0-like blocks/scales with optional BF16 bias.
ie_moe_w_t
typedef struct ie_moe_w ie_moe_w_t
Per-layer MoE weight views (router + expert matrices).
Expert matrices are assumed to be stored in "expert-major" order: contiguous blocks/scales/bias for each expert, with strides recorded here.
ie_tensor_view_t
typedef struct ie_tensor_view ie_tensor_view_t
A resolved tensor pointer plus its descriptor.
Enumeration Type Documentation
anonymous enum
anonymous enum
Internal log levels (higher means more verbose).
Enumerator
IE_LL_QUIET
IE_LL_ERROR
IE_LL_WARN
IE_LL_INFO
IE_LL_DEBUG
IE_LL_TRACE
Definition at line 74 of file infer_gptoss.c.
     {
  IE_LL_QUIET = 0,
  IE_LL_ERROR = 1,
  IE_LL_WARN  = 2,
  IE_LL_INFO  = 3,
  IE_LL_DEBUG = 4,
  IE_LL_TRACE = 5
};
Function Documentation
ie_add_bias_f32()
static void ie_add_bias_f32 (float * dst, const float * bias, size_t n) static
Definition at line 1120 of file infer_gptoss.c.
{
  if (!dst || !bias) return;
  for (size_t i = 0; i < n; ++i) dst[i] += bias[i];
}
Referenced by ie_forward_one_token().
ie_alloc_f32_from_bf16()
static int ie_alloc_f32_from_bf16 (const uint16_t * src, size_t n, float ** out) static
Allocate and convert BF16 weights to FP32.
Parameters
src BF16 source buffer.
n Number of elements.
out Receives allocated FP32 buffer (or NULL if src/n is empty).
Returns
0 on success, negative on failure.
Definition at line 672 of file infer_gptoss.c.
{
  if (!out) return -1;
  *out = NULL;
  if (!src || n == 0) return 0;
  float *buf = (float *)malloc(n * sizeof(float));
  if (!buf) return -2;
  ie_vec_bf16_to_f32(src, buf, n);
  *out = buf;
  return 0;
}
References ie_vec_bf16_to_f32().
Referenced by ie_gptoss_infer_create().
ie_attn_causal_gqa_f32()
static void ie_attn_causal_gqa_f32 (const float * Q, const float * K, const float * V, uint32_t seq_len, uint32_t n_heads, uint32_t n_kv_heads, uint32_t head_dim, float inv_sqrt_d, float * out, float * scores) static
Definition at line 1031 of file infer_gptoss.c.
{
  const uint32_t group_size = (n_kv_heads > 0) ? (n_heads / n_kv_heads) : 0;
  for (uint32_t hq = 0; hq < n_heads; ++hq) {
    const uint32_t hk = (group_size > 0) ? (hq / group_size) : 0;
    const float *Qh = Q + (size_t)hq * (size_t)head_dim;
    for (uint32_t t = 0; t < seq_len; ++t) {
      const size_t base =
          ((size_t)t * (size_t)n_kv_heads + (size_t)hk) * (size_t)head_dim;
      const float *Kh = K + base;
      scores[t] = ie_dot_f32(Qh, Kh, (size_t)head_dim) * inv_sqrt_d;
    }
    ie_softmax_inplace_f32(scores, (size_t)seq_len);
    float *Oh = out + (size_t)hq * (size_t)head_dim;
    for (uint32_t d = 0; d < head_dim; ++d) Oh[d] = 0.0f;
    for (uint32_t t = 0; t < seq_len; ++t) {
      const float w = scores[t];
      const size_t base =
          ((size_t)t * (size_t)n_kv_heads + (size_t)hk) * (size_t)head_dim;
      const float *Vh = V + base;
      for (uint32_t d = 0; d < head_dim; ++d) Oh[d] += w * Vh[d];
    }
  }
}
References ie_dot_f32(), and ie_softmax_inplace_f32().
Referenced by ie_forward_one_token().
ie_attn_cpu_causal_f32()
int ie_attn_cpu_causal_f32 (const float * Q, const float * K, const float * V, size_t seq_len, size_t n_heads, size_t head_dim, float inv_sqrt_d, float * out, float * scores)
Causal self-attention (FP32 reference).
Computes per-head softmax(QK^T * inv_sqrt_d) V over seq_len tokens.
Layout:
Q and out are [heads, head_dim] flattened (head_dim fastest).
K and V are [seq_len, heads, head_dim] flattened (head_dim fastest).
scratch must have length >= seq_len (floats) and is reused per head.
Returns
0 on success, non-zero on invalid args.
Causal self-attention (FP32 reference).
Parameters
Q Pointer to Q slice [heads*head_dim].
K Pointer to K cache [seq_len*heads*head_dim].
V Pointer to V cache [seq_len*heads*head_dim].
seq_len Number of cached tokens to attend over (>= 1).
heads Number of heads (>= 1).
head_dim Dimension per head (>= 1).
inv_sqrt_d Scale factor (typically 1/sqrt(head_dim)).
out Output buffer [heads*head_dim].
scratch Scratch buffer [seq_len] floats (reused per head).
Returns
0 on success, non-zero on invalid args.
Definition at line 1000 of file infer_gptoss.c.
{
  if (!Q || !K || !V || !out || !scores) return -1;
  if (seq_len == 0u || n_heads == 0u || head_dim == 0u) return -2;
  for (size_t h = 0; h < n_heads; ++h) {
    const float *Qh = Q + h * head_dim;
    for (size_t t = 0; t < seq_len; ++t) {
      const size_t base = (t * n_heads + h) * head_dim;
      const float *Kh = K + base;
      scores[t] = ie_dot_f32(Qh, Kh, head_dim) * inv_sqrt_d;
    }
    ie_softmax_inplace_f32(scores, seq_len);
    float *Oh = out + h * head_dim;
    for (size_t d = 0; d < head_dim; ++d) Oh[d] = 0.0f;
    for (size_t t = 0; t < seq_len; ++t) {
      const float w = scores[t];
      const size_t base = (t * n_heads + h) * head_dim;
      const float *Vh = V + base;
      for (size_t d = 0; d < head_dim; ++d) Oh[d] += w * Vh[d];
    }
  }
  return 0;
}
References dot_f32(), ie_dot_f32(), ie_softmax_inplace_f32(), kv_index(), and softmax_inplace_f32().
Referenced by ie_forward_one_token().
ie_bf16_to_f32()
static float ie_bf16_to_f32 (uint16_t v) inline static
Convert a BF16 value to float32.
Parameters
v BF16 bits.
Returns
float32 value.
Definition at line 692 of file infer_gptoss.c.
{
  union {
    uint32_t u;
    float f;
  } t;
  t.u = ((uint32_t)v) << 16;
  return t.f;
}
Referenced by ie_forward_one_token(), and ie_rmsnorm_cpu_f32_bf16w().
ie_check_finite_f32_()
static int ie_check_finite_f32_ (const float * v, size_t n, const char * tag, uint32_t layer, uint32_t pos) static
Definition at line 726 of file infer_gptoss.c.
{
  if (!v || !tag || n == 0) return 0;
  for (size_t i = 0; i < n; ++i) {
    if (!isfinite(v[i])) {
      IE_LOGE("nan: %s layer=%u pos=%u idx=%zu val=%g",
              tag, (unsigned)layer, (unsigned)pos, i, (double)v[i]);
      return -1;
    }
  }
  return 0;
}
References IE_LOGE.
Referenced by ie_forward_one_token().
ie_debug_nan_enabled_()
static int ie_debug_nan_enabled_ (void) static
Definition at line 708 of file infer_gptoss.c.
{
  static int cached = -1;
  if (cached < 0) {
    const char *s = getenv("IE_DEBUG_NAN");
    cached = (s && s[0] && strcmp(s, "0") != 0) ? 1 : 0;
  }
  return cached;
}
Referenced by ie_forward_one_token().
ie_dirname_alloc()
static char * ie_dirname_alloc (const char * path) static
Allocate and return the directory portion of a path.
If no slash is present, returns ".". If the path is rooted and the only slash is the first character, returns "/".
Parameters
path Input path.
Returns
Newly allocated directory string (caller frees), or NULL on OOM.
Definition at line 514 of file infer_gptoss.c.
{
  if (!path) return NULL;
  const char *slash = strrchr(path, '/');
  if (!slash) {
    char *out = (char *)malloc(2);
    if (!out) return NULL;
    out[0] = '.';
    out[1] = '\0';
    return out;
  }
  const size_t len = (size_t)(slash - path);
  if (len == 0) {
    char *out = (char *)malloc(2);
    if (!out) return NULL;
    out[0] = '/';
    out[1] = '\0';
    return out;
  }
  char *out = (char *)malloc(len + 1);
  if (!out) return NULL;
  memcpy(out, path, len);
  out[len] = '\0';
  return out;
}
Referenced by ie_gptoss_infer_create().
ie_dot_f32()
static float ie_dot_f32 (const float * a, const float * b, size_t n) static
Dot product of two float32 vectors.
Parameters
a Vector A.
b Vector B.
n Number of elements.
Returns
Sum_i a[i] * b[i].
Definition at line 750 of file infer_gptoss.c.
{
  float s = 0.0f;
  for (size_t i = 0; i < n; ++i) s += a[i] * b[i];
  return s;
}
Referenced by ie_attn_causal_gqa_f32(), and ie_attn_cpu_causal_f32().
ie_env_f32_clamped()
static float ie_env_f32_clamped (const char * name, float def, float lo, float hi) static
Parse an environment variable as float, with bounds and default.
Parameters
name Environment variable name.
def Default if unset or invalid.
lo Inclusive lower bound.
hi Inclusive upper bound.
Returns
Parsed and clamped value.
Definition at line 638 of file infer_gptoss.c.
{
  const char *s = getenv(name);
  if (!s || !*s) return def;
  char *end = NULL;
  float v = strtof(s, &end);
  if (end == s) return def;
  if (v < lo) v = lo;
  if (v > hi) v = hi;
  return v;
}
Referenced by ie_gptoss_infer_create().
ie_env_flag()
static int ie_env_flag (const char * name) static
Parse an environment variable as boolean.
Parameters
name Environment variable name.
Returns
1 if enabled, 0 otherwise.
Definition at line 656 of file infer_gptoss.c.
{
  const char *s = getenv(name);
  if (!s || !*s) return 0;
  if (s[0] == '0') return 0;
  if (s[0] == 'f' || s[0] == 'F') return 0;
  if (s[0] == 'n' || s[0] == 'N') return 0;
  return 1;
}
Referenced by ie_gptoss_infer_create().
ie_env_u32_clamped()
static uint32_t ie_env_u32_clamped (const char * name, uint32_t def, uint32_t lo, uint32_t hi) static
Parse an environment variable as uint32, with bounds and default.
Parameters
name Environment variable name.
def Default if unset or invalid.
lo Inclusive lower bound.
hi Inclusive upper bound.
Returns
Parsed and clamped value.
Definition at line 617 of file infer_gptoss.c.
{
  const char *s = getenv(name);
  if (!s || !*s) return def;
  char *end = NULL;
  unsigned long v = strtoul(s, &end, 10);
  if (end == s) return def;
  if (v < (unsigned long)lo) v = (unsigned long)lo;
  if (v > (unsigned long)hi) v = (unsigned long)hi;
  return (uint32_t)v;
}
Referenced by ie_forward_one_token().
ie_forward_one_token()
static int ie_forward_one_token (struct ie_gptoss_infer_impl * impl, ie_kv_cache * kv_layers, uint32_t token_id, uint32_t pos, float * out_logits) static
Definition at line 1359 of file infer_gptoss.c.
{
  static int bf16_trace_done = 0;
  if (!impl || !kv_layers || !out_logits) return -1;
  const ie_gptoss_hparams_t *hp = impl->hp;
  if (!hp) return -2;
  const uint32_t d_model = hp->d_model;
  const uint32_t d_head = hp->d_head;
  const uint32_t n_heads = hp->n_heads;
  const uint32_t n_kv_heads = hp->n_kv_heads;
  const uint32_t vocab = hp->vocab_size;
  const uint32_t n_layers = hp->n_layers;
  if (!impl->w_embed_bf16 || !impl->w_norm_bf16 || !impl->w_lm_bf16) return -3;
  if (token_id >= vocab) return -4;
  if (pos >= hp->max_seq) return -5;
  if ((d_head & 1u) != 0u) return -6;
  {
    const uint16_t *emb = impl->w_embed_bf16 + (size_t)token_id * (size_t)d_model;
    for (uint32_t i = 0; i < d_model; ++i) impl->x[i] = ie_bf16_to_f32(emb[i]);
  }
  const float inv_sqrt_d = 1.0f / sqrtf((float)d_head);
  const size_t q_dim = (size_t)n_heads * (size_t)d_head;
  const size_t kv_dim = (size_t)n_kv_heads * (size_t)d_head;
  const size_t d_ff = (size_t)hp->d_ff;
  const float rope_theta_eff = impl->rope_theta * impl->rope_scale;
  for (uint32_t l = 0; l < n_layers; ++l) {
    const ie_gptoss_layer_w_t *W = &impl->layers[l];
    ie_kv_cache *kv = &kv_layers[l];
    if (kv->storage != IE_KV_STORAGE_F32) {
      IE_LOGE("kv storage mismatch: layer=%u storage=%d (want %d)",
              (unsigned)l, (int)kv->storage, (int)IE_KV_STORAGE_F32);
      return -7;
    }
    if ((uint32_t)kv->heads != n_kv_heads) {
      IE_LOGE("kv heads mismatch: layer=%u heads=%zu want=%u",
              (unsigned)l, kv->heads, (unsigned)n_kv_heads);
      return -8;
    }
    if ((uint32_t)kv->head_dim != d_head) {
      IE_LOGE("kv head_dim mismatch: layer=%u head_dim=%zu want=%u",
              (unsigned)l, kv->head_dim, (unsigned)d_head);
      return -9;
    }
    /* Allow KV max_seq to be smaller than hp->max_seq: normal short-context inference. */
    if ((uint32_t)kv->max_seq == 0u) {
      IE_LOGE("kv max_seq invalid: layer=%u max_seq=%zu", (unsigned)l, kv->max_seq);
      return -10;
    }
    if ((uint32_t)kv->max_seq > hp->max_seq) {
      IE_LOGE("kv max_seq exceeds model max_seq: layer=%u max_seq=%zu hp_seq=%u",
              (unsigned)l, kv->max_seq, (unsigned)hp->max_seq);
      return -10;
    }
    if (pos >= (uint32_t)kv->max_seq) {
      IE_LOGE("kv max_seq too small for pos: layer=%u pos=%u max_seq=%zu",
              (unsigned)l, (unsigned)pos, kv->max_seq);
      return -10;
    }
    if (W->ln1_w_f32) {
      if (ie_rmsnorm_cpu_f32(impl->x, W->ln1_w_f32, (size_t)d_model, impl->rms_eps, impl->x1) != 0) {
        IE_LOGE("rmsnorm1 failed: layer=%u pos=%u", (unsigned)l, (unsigned)pos);
        return -11;
      }
    } else if (ie_rmsnorm_cpu_f32_bf16w(impl->x, W->ln1_w, (size_t)d_model, impl->rms_eps, impl->x1) != 0) {
      IE_LOGE("rmsnorm1 failed: layer=%u pos=%u", (unsigned)l, (unsigned)pos);
      return -11;
    }
    if (ie_debug_nan_enabled_() &&
        ie_check_finite_f32_(impl->x1, (size_t)d_model, "rmsnorm1", l, pos) != 0) {
      return -90;
    }
    const int trace_on = ie_trace_bf16_enabled_() && !bf16_trace_done;
    if (trace_on && !W->q_q4_blocks && !W->q_w_f32) {
      fprintf(stderr, "[TRACE] bf16 gemv: layer=%u op=q rows=%zu cols=%zu\n",
              (unsigned)l, q_dim, (size_t)d_model);
    }
    if (W->q_q4_blocks && W->q_q4_scales) {
      if (ie_gemv_q4_0_f32(W->q_q4_blocks, W->q_q4_scales, W->q_q4_scale_bytes,
                           impl->x1, impl->q, q_dim, (size_t)d_model, W->q_b) != 0) {
        return -12;
      }
      if (!W->q_b && W->q_b_f32) ie_add_bias_f32(impl->q, W->q_b_f32, q_dim);
    } else if (W->q_w_f32) {
      ie_gemv_f32(W->q_w_f32, impl->x1, impl->q, q_dim, (size_t)d_model, W->q_b_f32, 1);
    } else {
      if (ie_gemv_bf16_f32(W->q_w, impl->x1, impl->q, q_dim, (size_t)d_model, W->q_b) != 0) return -12;
    }
    if (trace_on && !W->k_q4_blocks && !W->k_w_f32) {
      fprintf(stderr, "[TRACE] bf16 gemv: layer=%u op=k rows=%zu cols=%zu\n",
              (unsigned)l, kv_dim, (size_t)d_model);
    }
    if (W->k_q4_blocks && W->k_q4_scales) {
      if (ie_gemv_q4_0_f32(W->k_q4_blocks, W->k_q4_scales, W->k_q4_scale_bytes,
                           impl->x1, impl->k, kv_dim, (size_t)d_model, W->k_b) != 0) {
        return -13;
      }
      if (!W->k_b && W->k_b_f32) ie_add_bias_f32(impl->k, W->k_b_f32, kv_dim);
    } else if (W->k_w_f32) {
      ie_gemv_f32(W->k_w_f32, impl->x1, impl->k, kv_dim, (size_t)d_model, W->k_b_f32, 1);
    } else {
      if (ie_gemv_bf16_f32(W->k_w, impl->x1, impl->k, kv_dim, (size_t)d_model, W->k_b) != 0) return -13;
    }
    if (trace_on && !W->v_q4_blocks && !W->v_w_f32) {
      fprintf(stderr, "[TRACE] bf16 gemv: layer=%u op=v rows=%zu cols=%zu\n",
              (unsigned)l, kv_dim, (size_t)d_model);
    }
    if (W->v_q4_blocks && W->v_q4_scales) {
      if (ie_gemv_q4_0_f32(W->v_q4_blocks, W->v_q4_scales, W->v_q4_scale_bytes,
                           impl->x1, impl->v, kv_dim, (size_t)d_model, W->v_b) != 0) {
        return -14;
      }
      if (!W->v_b && W->v_b_f32) ie_add_bias_f32(impl->v, W->v_b_f32, kv_dim);
    } else if (W->v_w_f32) {
      ie_gemv_f32(W->v_w_f32, impl->x1, impl->v, kv_dim, (size_t)d_model, W->v_b_f32, 1);
    } else {
      if (ie_gemv_bf16_f32(W->v_w, impl->x1, impl->v, kv_dim, (size_t)d_model, W->v_b) != 0) return -14;
    }
    if (ie_rope_apply_f32(impl->q, NULL, (size_t)n_heads, (size_t)d_head, pos, rope_theta_eff) != 0) return -15;
    if (ie_rope_apply_f32(NULL, impl->k, (size_t)n_kv_heads, (size_t)d_head, pos, rope_theta_eff) != 0) return -16;
    if (ie_kv_store_token_f32(kv, (size_t)pos, impl->k, impl->v) != 0) {
      IE_LOGE("kv store failed: layer=%u pos=%u", (unsigned)l, (unsigned)pos);
      return -17;
    }
    {
      /* KV reuse instrumentation: per layer, this token attends over (pos) cached tokens. */
      ie_kv_add_hits((uint64_t)pos);
      ie_kv_add_misses(1u);
      const float *Kbase = (const float *)kv->K;
      const float *Vbase = (const float *)kv->V;
      if (n_kv_heads == n_heads) {
        if (ie_attn_cpu_causal_f32(impl->q, Kbase, Vbase, (size_t)(pos + 1u),
                                   (size_t)n_heads, (size_t)d_head, inv_sqrt_d,
                                   impl->attn_out, impl->scores) != 0) {
          IE_LOGE("attn kernel failed: layer=%u pos=%u", (unsigned)l, (unsigned)pos);
          return -18;
        }
      } else {
        ie_attn_causal_gqa_f32(impl->q, Kbase, Vbase, pos + 1u, n_heads, n_kv_heads, d_head,
                               inv_sqrt_d, impl->attn_out, impl->scores);
      }
    }
    if (trace_on && !W->o_q4_blocks && !W->o_w_f32) {
      fprintf(stderr, "[TRACE] bf16 gemv: layer=%u op=o rows=%zu cols=%zu\n",
              (unsigned)l, (size_t)d_model, q_dim);
    }
    if (W->o_q4_blocks && W->o_q4_scales) {
      if (ie_gemv_q4_0_f32(W->o_q4_blocks, W->o_q4_scales, W->o_q4_scale_bytes,
                           impl->attn_out, impl->x2, (size_t)d_model, q_dim, W->o_b) != 0) {
        return -19;
      }
      if (!W->o_b && W->o_b_f32) ie_add_bias_f32(impl->x2, W->o_b_f32, (size_t)d_model);
    } else if (W->o_w_f32) {
      ie_gemv_f32(W->o_w_f32, impl->attn_out, impl->x2, (size_t)d_model, q_dim, W->o_b_f32, 1);
    } else {
      if (ie_gemv_bf16_f32(W->o_w, impl->attn_out, impl->x2, (size_t)d_model, q_dim, W->o_b) != 0) return -19;
    }
    for (uint32_t i = 0; i < d_model; ++i) impl->x[i] += impl->x2[i];
    if (W->ln2_w_f32) {
      if (ie_rmsnorm_cpu_f32(impl->x, W->ln2_w_f32, (size_t)d_model, impl->rms_eps, impl->x1) != 0) {
        IE_LOGE("rmsnorm2 failed: layer=%u pos=%u", (unsigned)l, (unsigned)pos);
        return -20;
      }
    } else if (ie_rmsnorm_cpu_f32_bf16w(impl->x, W->ln2_w, (size_t)d_model, impl->rms_eps, impl->x1) != 0) {
      IE_LOGE("rmsnorm2 failed: layer=%u pos=%u", (unsigned)l, (unsigned)pos);
      return -20;
    }
    {
      const ie_moe_w_t *M = &W->moe;
      const uint32_t n_exp = M->n_experts;
      if (n_exp == 0u || !impl->router_logits) return -21;
      if (trace_on) {
        fprintf(stderr, "[TRACE] bf16 gemv: layer=%u op=router rows=%u cols=%u\n",
                (unsigned)l, (unsigned)n_exp, (unsigned)d_model);
      }
      if (M->router_w_f32) {
        ie_gemv_f32(M->router_w_f32, impl->x1, impl->router_logits,
                    (size_t)n_exp, (size_t)d_model, M->router_b_f32, 1);
      } else if (ie_gemv_bf16_f32(M->router_w, impl->x1, impl->router_logits,
                                  (size_t)n_exp, (size_t)d_model, M->router_b) != 0) {
        IE_LOGE("router gemv failed: layer=%u pos=%u n_experts=%u",
                (unsigned)l, (unsigned)pos, (unsigned)n_exp);
        return -22;
      }
      if (ie_debug_nan_enabled_() &&
          ie_check_finite_f32_(impl->router_logits, (size_t)n_exp, "router_logits", l, pos) != 0) {
        return -90;
      }
      const uint32_t topk = ie_u32_min(impl->moe_topk, n_exp);
      if (topk == 0u) return -23;
      uint32_t idx[IE_GPTOSS_MOE_TOPK_DEFAULT] = {0, 0, 0, 0};
      float val[IE_GPTOSS_MOE_TOPK_DEFAULT] = {-INFINITY, -INFINITY, -INFINITY, -INFINITY};
      for (uint32_t e = 0; e < n_exp; ++e) {
        const float v = impl->router_logits[e];
        for (uint32_t k = 0; k < topk; ++k) {
          if (v > val[k]) {
            for (uint32_t j = topk - 1u; j > k; --j) {
              val[j] = val[j - 1u];
              idx[j] = idx[j - 1u];
            }
            val[k] = v;
            idx[k] = e;
            break;
          }
        }
      }
      ie_softmax_inplace_f32(val, (size_t)topk);
      for (uint32_t i = 0; i < d_model; ++i) impl->x2[i] = 0.0f;
      for (uint32_t sel = 0; sel < topk; ++sel) {
        const uint32_t ex = idx[sel];
        const float p = val[sel];
        if (!(p > 0.0f)) continue;
        const uint8_t *gu_b = M->gate_up_blocks + ex * M->gate_up_blocks_stride;
        const uint8_t *gu_s = M->gate_up_scales + ex * M->gate_up_scales_stride;
        const uint16_t *gu_bias =
            M->gate_up_bias ? (const uint16_t *)((const uint8_t *)M->gate_up_bias + ex * M->gate_up_bias_stride)
                            : NULL;
        const uint8_t *dn_b = M->down_blocks + ex * M->down_blocks_stride;
        const uint8_t *dn_s = M->down_scales + ex * M->down_scales_stride;
        const uint16_t *dn_bias =
            M->down_bias ? (const uint16_t *)((const uint8_t *)M->down_bias + ex * M->down_bias_stride) : NULL;
        if (ie_gemv_q4_0_f32(gu_b, gu_s, M->gate_up_scale_bytes,
                             impl->x1, impl->mlp_up,
                             2u * d_ff, (size_t)d_model, gu_bias) != 0) {
          IE_LOGE("moe gate_up gemv failed: layer=%u pos=%u ex=%u",
                  (unsigned)l, (unsigned)pos, (unsigned)ex);
          return -24;
        }
        if (ie_debug_nan_enabled_() &&
            ie_check_finite_f32_(impl->mlp_up, 2u * d_ff, "mlp_up", l, pos) != 0) {
          return -90;
        }
        for (size_t i = 0; i < d_ff; ++i) {
          const float g = ie_silu_f32(impl->mlp_up[i]);
          const float u = impl->mlp_up[d_ff + i];
          impl->mlp_gate[i] = g * u;
        }
        if (ie_debug_nan_enabled_() &&
            ie_check_finite_f32_(impl->mlp_gate, d_ff, "mlp_gate", l, pos) != 0) {
          return -90;
        }
        if (ie_gemv_q4_0_f32(dn_b, dn_s, M->down_scale_bytes,
                             impl->mlp_gate, impl->attn_out,
                             (size_t)d_model, d_ff, dn_bias) != 0) {
          IE_LOGE("moe down gemv failed: layer=%u pos=%u ex=%u",
                  (unsigned)l, (unsigned)pos, (unsigned)ex);
          return -25;
        }
        if (ie_debug_nan_enabled_() &&
            ie_check_finite_f32_(impl->attn_out, (size_t)d_model, "mlp_down", l, pos) != 0) {
          return -90;
        }
        for (uint32_t i = 0; i < d_model; ++i) impl->x2[i] += p * impl->attn_out[i];
      }
    }
    for (uint32_t i = 0; i < d_model; ++i) impl->x[i] += impl->x2[i];
  }
  if (impl->w_norm_f32) {
    if (ie_rmsnorm_cpu_f32(impl->x, impl->w_norm_f32, (size_t)d_model, impl->rms_eps, impl->x1) != 0)
      return -26;
  } else if (ie_rmsnorm_cpu_f32_bf16w(impl->x, impl->w_norm_bf16, (size_t)d_model, impl->rms_eps, impl->x1) != 0) {
    return -26;
  }
  {
    const int trace_on = ie_trace_bf16_enabled_() && !bf16_trace_done;
    if (trace_on && !impl->w_lm_q4_blocks && !impl->w_lm_f32) {
      fprintf(stderr, "[TRACE] bf16 gemv: op=lm_head rows=%u cols=%u\n",
              (unsigned)vocab, (unsigned)d_model);
      bf16_trace_done = 1;
    }
  }
  if (impl->w_lm_q4_blocks && impl->w_lm_q4_scales) {
    if (ie_gemv_q4_0_f32(impl->w_lm_q4_blocks, impl->w_lm_q4_scales,
                         impl->w_lm_q4_scale_bytes, impl->x1, out_logits,
                         (size_t)vocab, (size_t)d_model, NULL) != 0)
      return -27;
  } else if (impl->w_lm_f32) {
    ie_gemv_f32(impl->w_lm_f32, impl->x1, out_logits, (size_t)vocab, (size_t)d_model, NULL, 0);
  } else {
    if (ie_gemv_bf16_f32(impl->w_lm_bf16, impl->x1, out_logits, (size_t)vocab, (size_t)d_model, NULL) != 0)
      return -27;
  }
  if (getenv("IE_DEBUG_TOPK")) {
    uint32_t K = ie_env_u32_clamped("IE_DEBUG_TOPK", 10u, 1u, 100u);
    for (uint32_t i = 0; i < K; ++i) {
      float maxv = -INFINITY;
      int maxi = -1;
      for (uint32_t j = 0; j < vocab; ++j) {
        if (out_logits[j] > maxv) {
          maxv = out_logits[j];
          maxi = (int)j;
        }
      }
      if (maxi < 0) break;
      fprintf(stderr, "[DBG] top%u id=%d val=%g\n", (unsigned)i, maxi, (double)maxv);
      out_logits[(uint32_t)maxi] = -INFINITY;
    }
  }
  return 0;
}
References ie_gptoss_infer_impl::attn_out, ie_gptoss_hparams::d_ff, ie_gptoss_hparams::d_head, ie_gptoss_hparams::d_model, ie_moe_w::down_bias, ie_moe_w::down_bias_stride, ie_moe_w::down_blocks, ie_moe_w::down_blocks_stride, ie_moe_w::down_scale_bytes, ie_moe_w::down_scales, ie_moe_w::down_scales_stride, ie_moe_w::gate_up_bias, ie_moe_w::gate_up_bias_stride, ie_moe_w::gate_up_blocks, ie_moe_w::gate_up_blocks_stride, ie_moe_w::gate_up_scale_bytes, ie_moe_w::gate_up_scales, ie_moe_w::gate_up_scales_stride, ie_kv_cache::head_dim, ie_kv_cache::heads, ie_gptoss_infer_impl::hp, ie_add_bias_f32(), ie_attn_causal_gqa_f32(), ie_attn_cpu_causal_f32(), ie_bf16_to_f32(), ie_check_finite_f32_(), ie_debug_nan_enabled_(), ie_env_u32_clamped(), ie_gemv_bf16_f32(), ie_gemv_f32(), ie_gemv_q4_0_f32(), IE_GPTOSS_MOE_TOPK_DEFAULT, ie_kv_add_hits(), ie_kv_add_misses(), IE_KV_STORAGE_F32, ie_kv_store_token_f32(), IE_LOGE, ie_rmsnorm_cpu_f32(), ie_rmsnorm_cpu_f32_bf16w(), ie_rope_apply_f32(), ie_silu_f32(), ie_softmax_inplace_f32(), ie_trace_bf16_enabled_(), ie_u32_min(), ie_kv_cache::K, ie_gptoss_infer_impl::k, ie_gptoss_layer_w::k_b, ie_gptoss_layer_w::k_b_f32, ie_gptoss_layer_w::k_q4_blocks, ie_gptoss_layer_w::k_q4_scale_bytes, ie_gptoss_layer_w::k_q4_scales, ie_gptoss_layer_w::k_w, ie_gptoss_layer_w::k_w_f32, ie_gptoss_infer_impl::layers, ie_gptoss_layer_w::ln1_w, ie_gptoss_layer_w::ln1_w_f32, ie_gptoss_layer_w::ln2_w, ie_gptoss_layer_w::ln2_w_f32, ie_gptoss_hparams::max_seq, ie_kv_cache::max_seq, ie_gptoss_infer_impl::mlp_gate, ie_gptoss_infer_impl::mlp_up, ie_gptoss_layer_w::moe, ie_gptoss_infer_impl::moe_topk, ie_moe_w::n_experts, ie_gptoss_hparams::n_heads, ie_gptoss_hparams::n_kv_heads, ie_gptoss_hparams::n_layers, ie_gptoss_layer_w::o_b, ie_gptoss_layer_w::o_b_f32, ie_gptoss_layer_w::o_q4_blocks, ie_gptoss_layer_w::o_q4_scale_bytes, ie_gptoss_layer_w::o_q4_scales, ie_gptoss_layer_w::o_w, ie_gptoss_layer_w::o_w_f32, ie_gptoss_infer_impl::q, ie_gptoss_layer_w::q_b, ie_gptoss_layer_w::q_b_f32, ie_gptoss_layer_w::q_q4_blocks, ie_gptoss_layer_w::q_q4_scale_bytes, ie_gptoss_layer_w::q_q4_scales, ie_gptoss_layer_w::q_w, ie_gptoss_layer_w::q_w_f32, ie_gptoss_infer_impl::rms_eps, ie_gptoss_infer_impl::rope_scale, ie_gptoss_infer_impl::rope_theta, ie_moe_w::router_b, ie_moe_w::router_b_f32, ie_gptoss_infer_impl::router_logits, ie_moe_w::router_w, ie_moe_w::router_w_f32, ie_gptoss_infer_impl::scores, ie_kv_cache::storage, ie_kv_cache::V, ie_gptoss_infer_impl::v, ie_gptoss_layer_w::v_b, ie_gptoss_layer_w::v_b_f32, ie_gptoss_layer_w::v_q4_blocks, ie_gptoss_layer_w::v_q4_scale_bytes, ie_gptoss_layer_w::v_q4_scales, ie_gptoss_layer_w::v_w, ie_gptoss_layer_w::v_w_f32, ie_gptoss_hparams::vocab_size, ie_gptoss_infer_impl::w_embed_bf16, ie_gptoss_infer_impl::w_lm_bf16, ie_gptoss_infer_impl::w_lm_f32, ie_gptoss_infer_impl::w_lm_q4_blocks, ie_gptoss_infer_impl::w_lm_q4_scale_bytes, ie_gptoss_infer_impl::w_lm_q4_scales, ie_gptoss_infer_impl::w_norm_bf16, ie_gptoss_infer_impl::w_norm_f32, ie_gptoss_infer_impl::x, ie_gptoss_infer_impl::x1, and ie_gptoss_infer_impl::x2.
Referenced by ie_gptoss_infer_prefill(), and ie_gptoss_infer_step().
ie_gptoss_infer_create()
int ie_gptoss_infer_create (const ie_device_t * dev, const ie_weights_t * w, const ie_gptoss_hparams_t * hp, ie_gptoss_infer_t ** out_ctx)
Create an inference context.
Parameters
dev Device backend (CPU/CUDA).
w Opened weights handle.
hp Hyperparameters.
out_ctx Receives the newly created context on success.
Returns
0 on success; non-zero on failure.
Definition at line 1700 of file infer_gptoss.c.
{
  if (!out_ctx) return -1;
  *out_ctx = NULL;
  if (!w || !hp) return -2;
  if (w->json_path[0] == '\0') {
    IE_LOGE("create: missing w->json_path");
    return -2;
  }
  if (w->weights_path[0] == '\0') {
    IE_LOGE("create: missing w->weights_path");
    return -2;
  }
  IE_LOGI("create: json_path=%s", w->json_path);
  IE_LOGI("create: weights_path=%s", w->weights_path);
  struct ie_gptoss_infer_impl *impl = (struct ie_gptoss_infer_impl *)calloc(1, sizeof(*impl));
  if (!impl) return -3;
  impl->dev = (ie_device_t *)dev_const;
  impl->weights = w;
  impl->hp = hp;
  impl->pos = 0;
  /*
   * NOTE: ie_gptoss_hparams_t does not carry RoPE/RMS fields in this codebase.
   * Keep runtime parameters internal and configurable via environment variables.
   */
  impl->rms_eps = ie_env_f32_clamped("IE_RMS_EPS", IE_GPTOSS_RMS_EPS_DEFAULT, 1.0e-8f, 1.0e-2f);
  impl->rope_theta = ie_env_f32_clamped("IE_ROPE_THETA", IE_GPTOSS_ROPE_THETA_DEFAULT, 1.0f, 1.0e8f);
  impl->rope_scale = ie_env_f32_clamped("IE_ROPE_SCALE", 1.0f, 0.125f, 128.0f);
  impl->use_f32_attn = ie_env_flag("IE_F32_ATTN");
  impl->use_f32_router = ie_env_flag("IE_F32_ROUTER");
  impl->use_f32_lm_head = ie_env_flag("IE_F32_LM_HEAD");
  impl->use_f32_rmsnorm = ie_env_flag("IE_F32_RMSNORM");
  IE_LOGI("create: f32_cache attn=%d router=%d lm_head=%d rmsnorm=%d",
          impl->use_f32_attn, impl->use_f32_router,
          impl->use_f32_lm_head, impl->use_f32_rmsnorm);
  /* Initialize Q4 LUTs up front to avoid pthread_once in hot path. */
  ie_q4_log2_u8_q3_init_generic();
  ie_q4_log2_u8_q3_init_avx2();
  /* Step B: match model routing behavior (top-4 experts). Do not allow overrides here. */
  impl->moe_topk = IE_GPTOSS_MOE_TOPK_DEFAULT;
  impl->max_experts = 0;
  char *model_dir = ie_dirname_alloc(w->json_path);
  if (!model_dir) {
    free(impl);
    return -4;
  }
  IE_LOGD("create: inferred model_dir=%s", model_dir);
  const char *const tmap_rel[] = {
      "model.ie.compat.json",
      "tensor_map.json",
      "dedup_out/tensor_map.json",
      "hf/original/tensor_map.json",
  };
  char *tmap_path = NULL;
  int tmap_ok = -1;
  memset(&impl->tmap, 0, sizeof(impl->tmap));
  impl->tmap_path_used = NULL;
  for (size_t i = 0; i < (sizeof(tmap_rel) / sizeof(tmap_rel[0])); ++i) {
    free(tmap_path);
    tmap_path = ie_path_join_alloc(model_dir, tmap_rel[i]);
    if (!tmap_path) continue;
    IE_LOGI("create: trying tensor_map=%s", tmap_path);
    if (tensor_map_load(tmap_path, &impl->tmap) == 0) {
      tmap_ok = 0;
      impl->tmap_path_used = tmap_path;
      tmap_path = NULL;
      IE_LOGI("create: loaded tensor_map=%s (count=%u)",
              impl->tmap_path_used, (unsigned)impl->tmap.count);
      break;
    }
    IE_LOGW("create: failed to load tensor_map=%s", tmap_path);
    tensor_map_free(&impl->tmap);
    memset(&impl->tmap, 0, sizeof(impl->tmap));
  }
  free(tmap_path);
  if (tmap_ok != 0) {
    IE_LOGE("create: failed to load tensor_map.json (model_dir=%s)", model_dir);
    IE_LOGE("create: tried: %s/tensor_map.json", model_dir);
    IE_LOGE("create: tried: %s/dedup_out/tensor_map.json", model_dir);
    IE_LOGE("create: tried: %s/hf/original/tensor_map.json", model_dir);
    free(model_dir);
    free(impl);
    return -5;
  }
  {
    int rc_mm = ie_mmap_ro(w->weights_path, &impl->bin_base, &impl->bin_size);
    if (rc_mm != 0) {
      IE_LOGE("create: failed to mmap weights file: path=%s rc=%d", w->weights_path, rc_mm);
      tensor_map_free(&impl->tmap);
      free(impl->tmap_path_used);
      free(model_dir);
      free(impl);
      return -6;
    }
    IE_LOGI("create: mapped model.ie.bin size_bytes=%llu",
            (unsigned long long)impl->bin_size);
  }
  free(model_dir);
  const uint32_t d_model = hp->d_model;
  const uint32_t vocab = hp->vocab_size;
  const uint32_t n_layers = hp->n_layers;
  const uint32_t d_head = hp->d_head;
  const uint32_t n_heads = hp->n_heads;
  const uint32_t n_kv_heads = hp->n_kv_heads;
  const uint32_t d_ff = hp->d_ff;
  IE_LOGI("create: hp n_layers=%u d_model=%u d_head=%u n_heads=%u n_kv_heads=%u d_ff=%u vocab=%u max_seq=%u",
          (unsigned)n_layers, (unsigned)d_model, (unsigned)d_head, (unsigned)n_heads,
          (unsigned)n_kv_heads, (unsigned)d_ff, (unsigned)vocab, (unsigned)hp->max_seq);
  IE_LOGI("create: rms_eps=%g rope_theta=%g rope_scale=%g moe_topk=%u",
          (double)impl->rms_eps, (double)impl->rope_theta, (double)impl->rope_scale,
          (unsigned)impl->moe_topk);
  {
    ie_tensor_view_t v;
    const char *const embed_candidates[] = {
      "model.embed_tokens.weight",
      "transformer.wte.weight",
      "tok_embeddings.weight"
    };
    if (ie_w_get_first_view(impl, embed_candidates, 3, &v) != 0) {
      IE_LOGE("create: missing embedding tensor (tried common candidates)");
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -7;
    }
    if (!v.desc || ie_require_size_eq(v.desc, (uint64_t)vocab * (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: embedding size check failed: want=%llu",
              (unsigned long long)((uint64_t)vocab * (uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -8;
    }
    impl->w_embed_bf16 = (const uint16_t *)v.ptr;
  }
  {
    ie_tensor_view_t v;
    const char *const norm_candidates[] = {
      "model.norm.weight",
      "transformer.ln_f.weight",
      "norm.weight"
    };
    if (ie_w_get_first_view(impl, norm_candidates, 3, &v) != 0) {
      IE_LOGE("create: missing final norm tensor (tried common candidates)");
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -9;
    }
    if (!v.desc || ie_require_size_eq(v.desc, (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: final norm size check failed: want=%llu",
              (unsigned long long)((uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -10;
    }
    impl->w_norm_bf16 = (const uint16_t *)v.ptr;
    if (impl->use_f32_rmsnorm) {
      if (ie_alloc_f32_from_bf16(impl->w_norm_bf16, (size_t)d_model, &impl->w_norm_f32) != 0) {
        IE_LOGE("create: failed to allocate final norm f32");
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -10;
      }
    }
  }
  {
    ie_tensor_view_t v;
    const char *const lm_candidates[] = {
      "lm_head.weight",
      "model.lm_head.weight",
      "transformer.lm_head.weight",
      "model.embed_tokens.weight"
    };
    if (ie_w_get_first_view(impl, lm_candidates, 4, &v) != 0) {
      IE_LOGE("create: missing lm_head tensor (tried common candidates)");
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -11;
    }
    if (!v.desc || ie_require_size_eq(v.desc, (uint64_t)vocab * (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: lm_head size check failed: want=%llu",
              (unsigned long long)((uint64_t)vocab * (uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -12;
    }
    impl->w_lm_bf16 = (const uint16_t *)v.ptr;
    {
      ie_tensor_view_t v_q4_blocks;
      ie_tensor_view_t v_q4_scales;
      const char *const q4_blocks_candidates[] = {
        "lm_head.weight_blocks",
        "model.lm_head.weight_blocks",
        "transformer.lm_head.weight_blocks",
        "model.embed_tokens.weight_blocks"
      };
      const char *const q4_scales_candidates[] = {
        "lm_head.weight_scales",
        "model.lm_head.weight_scales",
        "transformer.lm_head.weight_scales",
        "model.embed_tokens.weight_scales"
      };
      const int has_blocks = (ie_w_get_first_view(impl, q4_blocks_candidates, 4, &v_q4_blocks) == 0 &&
                              v_q4_blocks.desc);
      const int has_scales = (ie_w_get_first_view(impl, q4_scales_candidates, 4, &v_q4_scales) == 0 &&
                              v_q4_scales.desc);
      if (has_blocks && has_scales) {
        uint8_t scale_bytes = 0;
        if (v_q4_scales.desc->dtype == TENSOR_DTYPE_BF16) scale_bytes = 2u;
        else if (v_q4_scales.desc->dtype == TENSOR_DTYPE_U8) scale_bytes = 1u;
        else {
          uint64_t want_blocks = 0, want_scales_1 = 0, want_scales_2 = 0;
          if (ie_q4_expected_bytes(vocab, d_model, 1u, &want_blocks, &want_scales_1) != 0 ||
              ie_q4_expected_bytes(vocab, d_model, 2u, &want_blocks, &want_scales_2) != 0) {
            IE_LOGE("create: lm_head q4 expected size failed");
            ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
            return -12;
          }
          if (v_q4_scales.desc->size_bytes == want_scales_1) scale_bytes = 1u;
          else if (v_q4_scales.desc->size_bytes == want_scales_2) scale_bytes = 2u;
        }
        if (scale_bytes != 0u) {
          uint64_t want_blocks = 0, want_scales = 0;
          if (ie_q4_expected_bytes(vocab, d_model, scale_bytes, &want_blocks, &want_scales) != 0 ||
              ie_require_size_eq(v_q4_blocks.desc, want_blocks) != 0 ||
              ie_require_size_eq(v_q4_scales.desc, want_scales) != 0) {
            IE_LOGE("create: lm_head q4 size mismatch");
            ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
            return -12;
          }
          impl->w_lm_q4_blocks = (const uint8_t *)v_q4_blocks.ptr;
          impl->w_lm_q4_scales = (const uint8_t *)v_q4_scales.ptr;
          impl->w_lm_q4_scale_bytes = scale_bytes;
          IE_LOGI("create: lm_head q4 enabled (scale_bytes=%u)", (unsigned)scale_bytes);
        }
      }
    }
    if (impl->use_f32_lm_head && !impl->w_lm_q4_blocks) {
      const uint64_t n64 = (uint64_t)vocab * (uint64_t)d_model;
      if (n64 > (uint64_t)SIZE_MAX) {
        IE_LOGE("create: lm_head f32 size overflow (vocab=%u d_model=%u)",
                (unsigned)vocab, (unsigned)d_model);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -12;
      }
      if (ie_alloc_f32_from_bf16(impl->w_lm_bf16, (size_t)n64, &impl->w_lm_f32) != 0) {
        IE_LOGE("create: failed to allocate lm_head f32");
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -12;
      }
    }
  }
  impl->layers = (ie_gptoss_layer_w_t *)calloc((size_t)n_layers, sizeof(*impl->layers));
  if (!impl->layers) {
    IE_LOGE("create: failed to allocate layer table (n_layers=%u)", (unsigned)n_layers);
    ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
    return -13;
  }
  const uint64_t q_dim = (uint64_t)n_heads * (uint64_t)d_head;
  const uint64_t kv_dim = (uint64_t)n_kv_heads * (uint64_t)d_head;
#if SIZE_MAX < UINT64_MAX
  if (q_dim > (uint64_t)SIZE_MAX || kv_dim > (uint64_t)SIZE_MAX) {
    IE_LOGE("create: attn dim overflow for size_t (q_dim=%llu kv_dim=%llu)",
            (unsigned long long)q_dim, (unsigned long long)kv_dim);
    ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
    return -13;
  }
#endif
  for (uint32_t l = 0; l < n_layers; ++l) {
    ie_gptoss_layer_w_t *LW = &impl->layers[l];
    ie_tensor_view_t v;
    IE_LOGD("create: resolving layer=%u", (unsigned)l);
    const char *const ln1_fmts[] = {
      "model.layers.%u.input_layernorm.weight",
      "model.layers.%u.attention_norm.weight"
    };
    if (ie_w_get_layer_fmt_view(impl, l, ln1_fmts, 2, &v, 1) != 0) {
      IE_LOGE("create: missing ln1 for layer=%u", (unsigned)l);
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -14;
    }
    if (!v.desc || ie_require_size_eq(v.desc, (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: ln1 size mismatch layer=%u want=%llu",
              (unsigned)l, (unsigned long long)((uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -15;
    }
    LW->ln1_w = (const uint16_t *)v.ptr;
    if (impl->use_f32_rmsnorm) {
      if (ie_alloc_f32_from_bf16(LW->ln1_w, (size_t)d_model, &LW->ln1_w_f32) != 0) {
        IE_LOGE("create: failed to allocate ln1 f32 layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -15;
      }
    }
    const char *const q_w_fmts[] = {"model.layers.%u.self_attn.q_proj.weight"};
    const char *const q_b_fmts[] = {"model.layers.%u.self_attn.q_proj.bias"};
    if (ie_w_get_layer_fmt_view(impl, l, q_w_fmts, 1, &v, 1) != 0) {
      IE_LOGE("create: missing q_proj.weight layer=%u", (unsigned)l);
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -16;
    }
    if (!v.desc || ie_require_size_eq(v.desc, q_dim * (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: q_proj.weight size mismatch layer=%u want=%llu",
              (unsigned)l, (unsigned long long)(q_dim * (uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -17;
    }
    LW->q_w = (const uint16_t *)v.ptr;
    if (ie_w_get_layer_fmt_view(impl, l, q_b_fmts, 1, &v, 0) == 0 && v.desc) {
      if (ie_require_size_eq(v.desc, q_dim * 2u) != 0) {
        IE_LOGE("create: q_proj.bias size mismatch layer=%u want=%llu",
                (unsigned)l, (unsigned long long)(q_dim * 2u));
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -18;
      }
      LW->q_b = (const uint16_t *)v.ptr;
    } else {
      LW->q_b = NULL;
    }
    const char *const k_w_fmts[] = {"model.layers.%u.self_attn.k_proj.weight"};
    const char *const k_b_fmts[] = {"model.layers.%u.self_attn.k_proj.bias"};
    if (ie_w_get_layer_fmt_view(impl, l, k_w_fmts, 1, &v, 1) != 0) {
      IE_LOGE("create: missing k_proj.weight layer=%u", (unsigned)l);
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -19;
    }
    if (!v.desc || ie_require_size_eq(v.desc, kv_dim * (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: k_proj.weight size mismatch layer=%u want=%llu",
              (unsigned)l, (unsigned long long)(kv_dim * (uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -20;
    }
    LW->k_w = (const uint16_t *)v.ptr;
    if (ie_w_get_layer_fmt_view(impl, l, k_b_fmts, 1, &v, 0) == 0 && v.desc) {
      if (ie_require_size_eq(v.desc, kv_dim * 2u) != 0) {
        IE_LOGE("create: k_proj.bias size mismatch layer=%u want=%llu",
                (unsigned)l, (unsigned long long)(kv_dim * 2u));
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -21;
      }
      LW->k_b = (const uint16_t *)v.ptr;
    } else {
      LW->k_b = NULL;
    }
    const char *const v_w_fmts[] = {"model.layers.%u.self_attn.v_proj.weight"};
    const char *const v_b_fmts[] = {"model.layers.%u.self_attn.v_proj.bias"};
    if (ie_w_get_layer_fmt_view(impl, l, v_w_fmts, 1, &v, 1) != 0) {
      IE_LOGE("create: missing v_proj.weight layer=%u", (unsigned)l);
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -22;
    }
    if (!v.desc || ie_require_size_eq(v.desc, kv_dim * (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: v_proj.weight size mismatch layer=%u want=%llu",
              (unsigned)l, (unsigned long long)(kv_dim * (uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -23;
    }
    LW->v_w = (const uint16_t *)v.ptr;
    if (ie_w_get_layer_fmt_view(impl, l, v_b_fmts, 1, &v, 0) == 0 && v.desc) {
      if (ie_require_size_eq(v.desc, kv_dim * 2u) != 0) {
        IE_LOGE("create: v_proj.bias size mismatch layer=%u want=%llu",
                (unsigned)l, (unsigned long long)(kv_dim * 2u));
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -24;
      }
      LW->v_b = (const uint16_t *)v.ptr;
    } else {
      LW->v_b = NULL;
    }
    const char *const o_w_fmts[] = {"model.layers.%u.self_attn.o_proj.weight"};
    const char *const o_b_fmts[] = {"model.layers.%u.self_attn.o_proj.bias"};
    if (ie_w_get_layer_fmt_view(impl, l, o_w_fmts, 1, &v, 1) != 0) {
      IE_LOGE("create: missing o_proj.weight layer=%u", (unsigned)l);
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -25;
    }
    if (!v.desc || ie_require_size_eq(v.desc, (uint64_t)d_model * q_dim * 2u) != 0) {
      IE_LOGE("create: o_proj.weight size mismatch layer=%u want=%llu",
              (unsigned)l, (unsigned long long)((uint64_t)d_model * q_dim * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -26;
    }
    LW->o_w = (const uint16_t *)v.ptr;
    if (ie_w_get_layer_fmt_view(impl, l, o_b_fmts, 1, &v, 0) == 0 && v.desc) {
      if (ie_require_size_eq(v.desc, (uint64_t)d_model * 2u) != 0) {
        IE_LOGE("create: o_proj.bias size mismatch layer=%u want=%llu",
                (unsigned)l, (unsigned long long)((uint64_t)d_model * 2u));
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
      LW->o_b = (const uint16_t *)v.ptr;
    } else {
      LW->o_b = NULL;
    }
    const char *const q_q4_blocks_fmts[] = {"model.layers.%u.self_attn.q_proj.weight_blocks"};
    const char *const q_q4_scales_fmts[] = {"model.layers.%u.self_attn.q_proj.weight_scales"};
    {
      int rc_q4 = ie_resolve_q4_attn_weight(
            impl, l, q_q4_blocks_fmts, q_q4_scales_fmts,
            (uint32_t)q_dim, d_model, "q",
            &LW->q_q4_blocks, &LW->q_q4_scales, &LW->q_q4_scale_bytes);
      if (rc_q4 < 0) {
        IE_LOGE("create: invalid q_proj q4 tensors layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
    }
    const char *const k_q4_blocks_fmts[] = {"model.layers.%u.self_attn.k_proj.weight_blocks"};
    const char *const k_q4_scales_fmts[] = {"model.layers.%u.self_attn.k_proj.weight_scales"};
    {
      int rc_q4 = ie_resolve_q4_attn_weight(
            impl, l, k_q4_blocks_fmts, k_q4_scales_fmts,
            (uint32_t)kv_dim, d_model, "k",
            &LW->k_q4_blocks, &LW->k_q4_scales, &LW->k_q4_scale_bytes);
      if (rc_q4 < 0) {
        IE_LOGE("create: invalid k_proj q4 tensors layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
    }
    const char *const v_q4_blocks_fmts[] = {"model.layers.%u.self_attn.v_proj.weight_blocks"};
    const char *const v_q4_scales_fmts[] = {"model.layers.%u.self_attn.v_proj.weight_scales"};
    {
      int rc_q4 = ie_resolve_q4_attn_weight(
            impl, l, v_q4_blocks_fmts, v_q4_scales_fmts,
            (uint32_t)kv_dim, d_model, "v",
            &LW->v_q4_blocks, &LW->v_q4_scales, &LW->v_q4_scale_bytes);
      if (rc_q4 < 0) {
        IE_LOGE("create: invalid v_proj q4 tensors layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
    }
    const char *const o_q4_blocks_fmts[] = {"model.layers.%u.self_attn.o_proj.weight_blocks"};
    const char *const o_q4_scales_fmts[] = {"model.layers.%u.self_attn.o_proj.weight_scales"};
    {
      int rc_q4 = ie_resolve_q4_attn_weight(
            impl, l, o_q4_blocks_fmts, o_q4_scales_fmts,
            d_model, (uint32_t)q_dim, "o",
            &LW->o_q4_blocks, &LW->o_q4_scales, &LW->o_q4_scale_bytes);
      if (rc_q4 < 0) {
        IE_LOGE("create: invalid o_proj q4 tensors layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
    }
    if (impl->use_f32_attn) {
      const size_t q_dim_sz = (size_t)q_dim;
      const size_t kv_dim_sz = (size_t)kv_dim;
      const size_t d_model_sz = (size_t)d_model;
      const uint64_t q_w_n64 = q_dim * (uint64_t)d_model;
      const uint64_t kv_w_n64 = kv_dim * (uint64_t)d_model;
      const uint64_t o_w_n64 = (uint64_t)d_model * q_dim;
#if SIZE_MAX < UINT64_MAX
      if (q_w_n64 > (uint64_t)SIZE_MAX || kv_w_n64 > (uint64_t)SIZE_MAX || o_w_n64 > (uint64_t)SIZE_MAX) {
        IE_LOGE("create: f32 attn weight size overflow layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
#endif
      if (ie_alloc_f32_from_bf16(LW->q_w, (size_t)q_w_n64, &LW->q_w_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->q_b, q_dim_sz, &LW->q_b_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->k_w, (size_t)kv_w_n64, &LW->k_w_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->k_b, kv_dim_sz, &LW->k_b_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->v_w, (size_t)kv_w_n64, &LW->v_w_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->v_b, kv_dim_sz, &LW->v_b_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->o_w, (size_t)o_w_n64, &LW->o_w_f32) != 0 ||
          ie_alloc_f32_from_bf16(LW->o_b, d_model_sz, &LW->o_b_f32) != 0) {
        IE_LOGE("create: failed to allocate f32 attn weights layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -27;
      }
    }
    const char *const ln2_fmts[] = {
      "model.layers.%u.post_attention_layernorm.weight",
      "model.layers.%u.ffn_norm.weight"
    };
    if (ie_w_get_layer_fmt_view(impl, l, ln2_fmts, 2, &v, 1) != 0) {
      IE_LOGE("create: missing ln2 for layer=%u", (unsigned)l);
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -28;
    }
    if (!v.desc || ie_require_size_eq(v.desc, (uint64_t)d_model * 2u) != 0) {
      IE_LOGE("create: ln2 size mismatch layer=%u want=%llu",
              (unsigned)l, (unsigned long long)((uint64_t)d_model * 2u));
      ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
      return -29;
    }
    LW->ln2_w = (const uint16_t *)v.ptr;
    if (impl->use_f32_rmsnorm) {
      if (ie_alloc_f32_from_bf16(LW->ln2_w, (size_t)d_model, &LW->ln2_w_f32) != 0) {
        IE_LOGE("create: failed to allocate ln2 f32 layer=%u", (unsigned)l);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -29;
      }
    }
    {
      const int rc_moe = ie_resolve_moe_layer(impl, l, LW);
      if (rc_moe != 0) {
        IE_LOGE("create: moe resolve failed: layer=%u rc=%d d_model=%u d_ff=%u",
                (unsigned)l, rc_moe, (unsigned)d_model, (unsigned)d_ff);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -30;
      }
    }
    if (impl->use_f32_router) {
      const uint64_t n_exp = (uint64_t)LW->moe.n_experts;
      const uint64_t router_n64 = n_exp * (uint64_t)d_model;
      if (n_exp > 0 && router_n64 <= (uint64_t)SIZE_MAX) {
        if (ie_alloc_f32_from_bf16(LW->moe.router_w, (size_t)router_n64, &LW->moe.router_w_f32) != 0 ||
            ie_alloc_f32_from_bf16(LW->moe.router_b, (size_t)n_exp, &LW->moe.router_b_f32) != 0) {
          IE_LOGE("create: failed to allocate f32 router weights layer=%u", (unsigned)l);
          ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
          return -30;
        }
      } else if (n_exp > 0) {
        IE_LOGE("create: f32 router size overflow layer=%u n_exp=%u d_model=%u",
                (unsigned)l, (unsigned)LW->moe.n_experts, (unsigned)d_model);
        ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
        return -30;
      }
    }
  }
  const size_t d_model_sz = (size_t)d_model;
  const size_t q_dim_sz = (size_t)n_heads * (size_t)d_head;
  const size_t kv_dim_sz = (size_t)n_kv_heads * (size_t)d_head;
  const size_t d_ff_sz = (size_t)d_ff;
  impl->x = (float *)malloc(d_model_sz * sizeof(float));
  impl->x1 = (float *)malloc(d_model_sz * sizeof(float));
  impl->x2 = (float *)malloc(d_model_sz * sizeof(float));
  impl->q = (float *)malloc(q_dim_sz * sizeof(float));
  impl->k = (float *)malloc(kv_dim_sz * sizeof(float));
  impl->v = (float *)malloc(kv_dim_sz * sizeof(float));
  impl->attn_out = (float *)malloc(q_dim_sz * sizeof(float));
  impl->mlp_gate = (float *)malloc(d_ff_sz * sizeof(float));
  impl->mlp_up = (float *)malloc((2u * d_ff_sz) * sizeof(float));
  impl->scores = (float *)malloc((size_t)hp->max_seq * sizeof(float));
  impl->router_logits = (impl->max_experts > 0u) ? (float *)malloc((size_t)impl->max_experts * sizeof(float)) : NULL;
  if (!impl->x || !impl->x1 || !impl->x2 || !impl->q || !impl->k || !impl->v || !impl->attn_out ||
      !impl->mlp_gate || !impl->mlp_up || !impl->scores || (impl->max_experts > 0u && !impl->router_logits)) {
    IE_LOGE("create: activation allocation failed (max_experts=%u)", (unsigned)impl->max_experts);
    ie_gptoss_infer_destroy((ie_gptoss_infer_t *)impl);
    return -31;
  }
  IE_LOGI("create: success");
  *out_ctx = (ie_gptoss_infer_t *)impl;
  return 0;
}
References ie_gptoss_infer_impl::attn_out, ie_gptoss_infer_impl::bin_base, ie_gptoss_infer_impl::bin_size, tensor_map_s::count, ie_gptoss_hparams::d_ff, ie_gptoss_hparams::d_head, ie_gptoss_hparams::d_model, ie_tensor_view::desc, ie_gptoss_infer_impl::dev, tensor_desc_s::dtype, ie_gptoss_infer_impl::hp, ie_alloc_f32_from_bf16(), ie_dirname_alloc(), ie_env_f32_clamped(), ie_env_flag(), ie_gptoss_infer_destroy(), IE_GPTOSS_MOE_TOPK_DEFAULT, IE_GPTOSS_RMS_EPS_DEFAULT, IE_GPTOSS_ROPE_THETA_DEFAULT, IE_LOGD, IE_LOGE, IE_LOGI, IE_LOGW, ie_mmap_ro(), ie_path_join_alloc(), ie_q4_expected_bytes(), ie_q4_log2_u8_q3_init_avx2(), ie_q4_log2_u8_q3_init_generic(), ie_require_size_eq(), ie_resolve_moe_layer(), ie_resolve_q4_attn_weight(), ie_w_get_first_view(), ie_w_get_layer_fmt_view(), ie_weights_s::json_path, ie_gptoss_infer_impl::k, ie_gptoss_layer_w::k_b, ie_gptoss_layer_w::k_b_f32, ie_gptoss_layer_w::k_q4_blocks, ie_gptoss_layer_w::k_q4_scale_bytes, ie_gptoss_layer_w::k_q4_scales, ie_gptoss_layer_w::k_w, ie_gptoss_layer_w::k_w_f32, ie_gptoss_infer_impl::layers, ie_gptoss_layer_w::ln1_w, ie_gptoss_layer_w::ln1_w_f32, ie_gptoss_layer_w::ln2_w, ie_gptoss_layer_w::ln2_w_f32, ie_gptoss_infer_impl::max_experts, ie_gptoss_hparams::max_seq, ie_gptoss_infer_impl::mlp_gate, ie_gptoss_infer_impl::mlp_up, ie_gptoss_layer_w::moe, ie_gptoss_infer_impl::moe_topk, ie_moe_w::n_experts, ie_gptoss_hparams::n_heads, ie_gptoss_hparams::n_kv_heads, ie_gptoss_hparams::n_layers, ie_gptoss_layer_w::o_b, ie_gptoss_layer_w::o_b_f32, ie_gptoss_layer_w::o_q4_blocks, ie_gptoss_layer_w::o_q4_scale_bytes, ie_gptoss_layer_w::o_q4_scales, ie_gptoss_layer_w::o_w, ie_gptoss_layer_w::o_w_f32, ie_gptoss_infer_impl::pos, ie_tensor_view::ptr, ie_gptoss_infer_impl::q, ie_gptoss_layer_w::q_b, ie_gptoss_layer_w::q_b_f32, ie_gptoss_layer_w::q_q4_blocks, ie_gptoss_layer_w::q_q4_scale_bytes, ie_gptoss_layer_w::q_q4_scales, ie_gptoss_layer_w::q_w, ie_gptoss_layer_w::q_w_f32, ie_gptoss_infer_impl::rms_eps, ie_gptoss_infer_impl::rope_scale, ie_gptoss_infer_impl::rope_theta, ie_moe_w::router_b, ie_moe_w::router_b_f32, ie_gptoss_infer_impl::router_logits, ie_moe_w::router_w, ie_moe_w::router_w_f32, ie_gptoss_infer_impl::scores, tensor_desc_s::size_bytes, TENSOR_DTYPE_BF16, TENSOR_DTYPE_U8, tensor_map_free(), tensor_map_load(), ie_gptoss_infer_impl::tmap, ie_gptoss_infer_impl::tmap_path_used, ie_gptoss_infer_impl::use_f32_attn, ie_gptoss_infer_impl::use_f32_lm_head, ie_gptoss_infer_impl::use_f32_rmsnorm, ie_gptoss_infer_impl::use_f32_router, ie_gptoss_infer_impl::v, ie_gptoss_layer_w::v_b, ie_gptoss_layer_w::v_b_f32, ie_gptoss_layer_w::v_q4_blocks, ie_gptoss_layer_w::v_q4_scale_bytes, ie_gptoss_layer_w::v_q4_scales, ie_gptoss_layer_w::v_w, ie_gptoss_layer_w::v_w_f32, ie_gptoss_hparams::vocab_size, ie_gptoss_infer_impl::w_embed_bf16, ie_gptoss_infer_impl::w_lm_bf16, ie_gptoss_infer_impl::w_lm_f32, ie_gptoss_infer_impl::w_lm_q4_blocks, ie_gptoss_infer_impl::w_lm_q4_scale_bytes, ie_gptoss_infer_impl::w_lm_q4_scales, ie_gptoss_infer_impl::w_norm_bf16, ie_gptoss_infer_impl::w_norm_f32, ie_gptoss_infer_impl::weights, ie_weights_s::weights_path, ie_gptoss_infer_impl::x, ie_gptoss_infer_impl::x1, and ie_gptoss_infer_impl::x2.
Referenced by ie_engine_create(), and ie_generate_gptoss().
ie_gptoss_infer_destroy()
void ie_gptoss_infer_destroy (ie_gptoss_infer_t * ctx)
Destroy an inference context.
Parameters
ctx Context handle (may be NULL).
Definition at line 2292 of file infer_gptoss.c.
{
  if (!ctx) return;
  struct ie_gptoss_infer_impl *impl = (struct ie_gptoss_infer_impl *)ctx;
  if (impl->bin_base) ie_munmap_ro(impl->bin_base, impl->bin_size);
  tensor_map_free(&impl->tmap);
  if (impl->layers) {
    for (uint32_t l = 0; l < impl->hp->n_layers; ++l) {
      ie_gptoss_layer_w_t *LW = &impl->layers[l];
      free(LW->ln1_w_f32);
      free(LW->ln2_w_f32);
      free(LW->q_w_f32);
      free(LW->q_b_f32);
      free(LW->k_w_f32);
      free(LW->k_b_f32);
      free(LW->v_w_f32);
      free(LW->v_b_f32);
      free(LW->o_w_f32);
      free(LW->o_b_f32);
      free(LW->moe.router_w_f32);
      free(LW->moe.router_b_f32);
    }
  }
  free(impl->w_norm_f32);
  free(impl->w_lm_f32);
  free(impl->tmap_path_used);
  free(impl->layers);
  free(impl->x);
  free(impl->x1);
  free(impl->x2);
  free(impl->q);
  free(impl->k);
  free(impl->v);
  free(impl->attn_out);
  free(impl->mlp_gate);
  free(impl->mlp_up);
  free(impl->scores);
  free(impl->router_logits);
  free(impl);
}
References ie_gptoss_infer_impl::attn_out, ie_gptoss_infer_impl::bin_base, ie_gptoss_infer_impl::bin_size, ie_gptoss_infer_impl::hp, ie_munmap_ro(), ie_gptoss_infer_impl::k, ie_gptoss_layer_w::k_b_f32, ie_gptoss_layer_w::k_w_f32, ie_gptoss_infer_impl::layers, ie_gptoss_layer_w::ln1_w_f32, ie_gptoss_layer_w::ln2_w_f32, ie_gptoss_infer_impl::mlp_gate, ie_gptoss_infer_impl::mlp_up, ie_gptoss_layer_w::moe, ie_gptoss_hparams::n_layers, ie_gptoss_layer_w::o_b_f32, ie_gptoss_layer_w::o_w_f32, ie_gptoss_infer_impl::q, ie_gptoss_layer_w::q_b_f32, ie_gptoss_layer_w::q_w_f32, ie_moe_w::router_b_f32, ie_gptoss_infer_impl::router_logits, ie_moe_w::router_w_f32, ie_gptoss_infer_impl::scores, tensor_map_free(), ie_gptoss_infer_impl::tmap, ie_gptoss_infer_impl::tmap_path_used, ie_gptoss_infer_impl::v, ie_gptoss_layer_w::v_b_f32, ie_gptoss_layer_w::v_w_f32, ie_gptoss_infer_impl::w_lm_f32, ie_gptoss_infer_impl::w_norm_f32, ie_gptoss_infer_impl::x, ie_gptoss_infer_impl::x1, and ie_gptoss_infer_impl::x2.
Referenced by ie_engine_create(), ie_engine_destroy(), ie_generate_gptoss(), and ie_gptoss_infer_create().
ie_gptoss_infer_get_pos()
uint32_t ie_gptoss_infer_get_pos (const ie_gptoss_infer_t * ctx)
Get the current position (number of tokens already consumed).
Performance notes:
INT4 runs use Q4_0 weight GEMV kernels (runtime-dispatched to AVX2/FMA when available).
Per-32-column scales may be stored as BF16 (2 bytes) or FP8(E4M3) (1 byte) depending on artifacts.
The runtime maintains a position counter internally. This is used to index into the KV cache (time dimension) and to drive rotary embeddings.
Definition at line 2418 of file infer_gptoss.c.
{
  return ie_gptoss_infer_pos(ctx);
}
References ie_gptoss_infer_pos().
ie_gptoss_infer_pos()
uint32_t ie_gptoss_infer_pos (const ie_gptoss_infer_t * ctx)
Definition at line 2410 of file infer_gptoss.c.
{
  if (!ctx) return 0u;
  const struct ie_gptoss_infer_impl *impl = (const struct ie_gptoss_infer_impl *)ctx;
  return impl->pos;
}
References ie_gptoss_infer_impl::pos.
Referenced by ie_gptoss_infer_get_pos().
ie_gptoss_infer_prefill()
int ie_gptoss_infer_prefill (ie_gptoss_infer_t * ctx, ie_kv_cache * kv, const uint32_t * prompt, uint32_t n_prompt, float * out_logits)
Prefill: consume a prompt, update the KV cache, and produce logits.
Parameters
ctx Inference context.
kv Array of KV caches, one per layer.
prompt Prompt token IDs.
n_prompt Number of prompt tokens.
out_logits Output logits for the last position (vocab-sized).
Returns
0 on success; non-zero on failure.
Definition at line 2337 of file infer_gptoss.c.
{
  if (!ctx || !kv || (!prompt && n_prompt > 0) || !out_logits) return -1;
  struct ie_gptoss_infer_impl *impl = (struct ie_gptoss_infer_impl *)ctx;
  impl->pos = 0;
  if (n_prompt == 0u) return -2;
  const uint32_t limit = (uint32_t)ie_min_size((size_t)n_prompt, (size_t)impl->hp->max_seq);
  if (limit != n_prompt) {
    IE_LOGW("prefill: prompt truncated from %u to %u due to max_seq=%u",
            (unsigned)n_prompt, (unsigned)limit, (unsigned)impl->hp->max_seq);
  }
  for (uint32_t i = 0; i < limit; ++i) {
    const int rc = ie_forward_one_token(impl, kv, prompt[i], impl->pos, out_logits);
    if (rc != 0) {
      IE_LOGE("prefill: failed at i=%u token=%u pos=%u rc=%d",
              (unsigned)i, (unsigned)prompt[i], (unsigned)impl->pos, rc);
      return rc;
    }
    impl->pos += 1u;
  }
  return 0;
}
References ie_gptoss_infer_impl::hp, ie_forward_one_token(), IE_LOGE, IE_LOGW, ie_min_size(), ie_gptoss_hparams::max_seq, and ie_gptoss_infer_impl::pos.
Referenced by ie_engine_generate_ex(), and ie_generate_gptoss().
ie_gptoss_infer_reset()
void ie_gptoss_infer_reset (ie_gptoss_infer_t * ctx)
Definition at line 2386 of file infer_gptoss.c.
{
  if (!ctx) return;
  struct ie_gptoss_infer_impl *impl = (struct ie_gptoss_infer_impl *)ctx;
  impl->pos = 0;
}
References ie_gptoss_infer_impl::pos.
ie_gptoss_infer_seek()
int ie_gptoss_infer_seek (ie_gptoss_infer_t * ctx, uint32_t pos)
Definition at line 2392 of file infer_gptoss.c.
{
  if (!ctx) return -1;
  struct ie_gptoss_infer_impl *impl = (struct ie_gptoss_infer_impl *)ctx;
  if (!impl->hp) return -2;
  if (pos > impl->hp->max_seq) {
    IE_LOGE("seek: invalid pos=%u (max_seq=%u)", (unsigned)pos, (unsigned)impl->hp->max_seq);
    return -3;
  }
  if (pos == impl->hp->max_seq) {
    IE_LOGW("seek: pos==max_seq (%u); next step/prefill will fail if it writes at this position",
            (unsigned)pos);
  }
  impl->pos = pos;
  return 0;
}
References ie_gptoss_infer_impl::hp, IE_LOGE, IE_LOGW, ie_gptoss_hparams::max_seq, and ie_gptoss_infer_impl::pos.
Referenced by ie_gptoss_infer_set_pos().
ie_gptoss_infer_set_pos()
void ie_gptoss_infer_set_pos (ie_gptoss_infer_t * ctx, uint32_t pos)
Set the current position.
Performance notes:
INT4 runs use Q4_0 weight GEMV kernels (runtime-dispatched to AVX2/FMA when available).
Per-32-column scales may be stored as BF16 (2 bytes) or FP8(E4M3) (1 byte) depending on artifacts.
This exists to enable persistent prompt-prefix reuse: if the KV cache already contains valid K/V entries for positions [0, pos-1], the caller can rewind the runtime position to pos and continue generation without recomputing the prefix.
Definition at line 2422 of file infer_gptoss.c.
{
  (void)ie_gptoss_infer_seek(ctx, pos);
}
References ie_gptoss_infer_seek(), and ie_gptoss_infer_impl::pos.
ie_gptoss_infer_step()
int ie_gptoss_infer_step (ie_gptoss_infer_t * ctx, ie_kv_cache * kv, uint32_t token_id, float * out_logits)
Step: consume one token, update the KV cache, and produce next logits.
Parameters
ctx Inference context.
kv Array of KV caches, one per layer.
token_id The token to consume.
out_logits Output logits for the next token (vocab-sized).
Returns
0 on success; non-zero on failure.
Definition at line 2365 of file infer_gptoss.c.
{
  if (!ctx || !kv || !out_logits) return -1;
  struct ie_gptoss_infer_impl *impl = (struct ie_gptoss_infer_impl *)ctx;
  const uint32_t pos = impl->pos;
  const int rc = ie_forward_one_token(impl, kv, token_id, pos, out_logits);
  if (rc != 0) {
    IE_LOGE("step: failed token=%u pos=%u rc=%d", (unsigned)token_id, (unsigned)pos, rc);
    return rc;
  }
  impl->pos = pos + 1u;
  return 0;
}
References ie_forward_one_token(), IE_LOGE, and ie_gptoss_infer_impl::pos.
Referenced by ie_engine_generate_ex(), and ie_generate_gptoss().
ie_infer_n_experts_from_router()
static int ie_infer_n_experts_from_router (const tensor_desc_t * td_router_w, uint32_t d_model, uint32_t * out_n_experts) static
Definition at line 1066 of file infer_gptoss.c.
{
  if (!td_router_w || !out_n_experts || d_model == 0u) return -1;
  const uint64_t bytes = td_router_w->size_bytes;
  const uint64_t denom = (uint64_t)d_model * 2u;
  if (denom == 0u) return -2;
  if ((bytes % denom) != 0u) return -3;
  const uint64_t n = bytes / denom;
  if (n == 0u || n > 65535u) return -4;
  *out_n_experts = (uint32_t)n;
  return 0;
}
References tensor_desc_s::size_bytes.
Referenced by ie_resolve_moe_layer().
ie_log_level()
static int ie_log_level (void) static
Read IE_LOG_LEVEL once and cache the result.
Returns
Cached log level in [0..5].
Definition at line 90 of file infer_gptoss.c.
{
  if (ie_log_level_cached >= 0) return ie_log_level_cached;
  const char *s = getenv("IE_LOG_LEVEL");
  int lvl = IE_LL_WARN;
  if (s && *s) {
    char *end = NULL;
    long v = strtol(s, &end, 10);
    if (end != s) {
      if (v < 0) v = 0;
      if (v > 5) v = 5;
      lvl = (int)v;
    }
  }
  ie_log_level_cached = lvl;
  return lvl;
}
References IE_LL_WARN, and ie_log_level_cached.
Referenced by ie_logf().
ie_logf()
static void ie_logf (int lvl, const char * file, int line, const char * fmt, ...) static
Print a formatted log line if the level is enabled.
Parameters
lvl Message level.
file Source file.
line Source line.
fmt printf-style format string.
Definition at line 115 of file infer_gptoss.c.
{
  if (ie_log_level() < lvl) return;
  const char *tag = "LOG";
  if (lvl == IE_LL_ERROR) tag = "ERR";
  else if (lvl == IE_LL_WARN) tag = "WRN";
  else if (lvl == IE_LL_INFO) tag = "INF";
  else if (lvl == IE_LL_DEBUG) tag = "DBG";
  else if (lvl == IE_LL_TRACE) tag = "TRC";
  fprintf(stderr, "[%s] %s:%d: ", tag, file, line);
  va_list ap;
  va_start(ap, fmt);
  vfprintf(stderr, fmt, ap);
  va_end(ap);
  fputc('\n', stderr);
}
References IE_LL_DEBUG, IE_LL_ERROR, IE_LL_INFO, IE_LL_TRACE, IE_LL_WARN, and ie_log_level().
ie_min_size()
static size_t ie_min_size (size_t a, size_t b) static
Return the minimum of two size_t values.
Parameters
a First value.
b Second value.
Returns
min(a, b).
Definition at line 495 of file infer_gptoss.c.
{ return (a < b) ? a : b; }
Referenced by ie_gptoss_infer_prefill().
ie_mmap_ro()
static int ie_mmap_ro (const char * path, uint8_t ** out_base, size_t * out_size) static
Memory-map a file read-only.
Parameters
path File path.
out_base Receives mapped base address.
out_size Receives mapped size in bytes.
Returns
0 on success, negative error code on failure.
Definition at line 572 of file infer_gptoss.c.
{
  if (!path || !out_base || !out_size) return -1;
  *out_base = NULL;
  *out_size = 0;
  const int fd = open(path, O_RDONLY);
  if (fd < 0) return -2;
  struct stat st;
  if (fstat(fd, &st) != 0) {
    close(fd);
    return -3;
  }
  if (st.st_size <= 0) {
    close(fd);
    return -4;
  }
  void *p = mmap(NULL, (size_t)st.st_size, PROT_READ, MAP_PRIVATE, fd, 0);
  close(fd);
  if (p == MAP_FAILED) return -5;
  *out_base = (uint8_t *)p;
  *out_size = (size_t)st.st_size;
  return 0;
}
Referenced by ie_gptoss_infer_create().
ie_moe_expected_bytes()
static int ie_moe_expected_bytes (uint32_t n_experts, uint32_t rows, uint32_t cols, uint8_t scale_bytes, uint64_t * out_blocks_bytes, uint64_t * out_scales_bytes) static
Definition at line 1082 of file infer_gptoss.c.
{
  if (!out_blocks_bytes || !out_scales_bytes) return -1;
  if (n_experts == 0u || rows == 0u || cols == 0u) return -2;
  if ((cols % 32u) != 0u) return -3;
  if (!(scale_bytes == 1u || scale_bytes == 2u)) return -4;
  const uint64_t qk = 32u;
  const uint64_t qs_bytes = 16u;
  const uint64_t nb = (uint64_t)cols / qk;
  const uint64_t blocks_per_row_bytes = nb * qs_bytes;
  const uint64_t scales_per_row_bytes = nb * (uint64_t)scale_bytes;
  const uint64_t one_blocks = (uint64_t)rows * blocks_per_row_bytes;
  const uint64_t one_scales = (uint64_t)rows * scales_per_row_bytes;
  *out_blocks_bytes = one_blocks * (uint64_t)n_experts;
  *out_scales_bytes = one_scales * (uint64_t)n_experts;
  return 0;
}
Referenced by ie_resolve_moe_layer().
ie_munmap_ro()
static void ie_munmap_ro (uint8_t * base, size_t size) static
Unmap a previously mapped read-only file.
Parameters
base Mapped base address.
size Mapped size in bytes.
Definition at line 604 of file infer_gptoss.c.
{
  if (!base || size == 0) return;
  (void)munmap((void *)base, size);
}
Referenced by ie_gptoss_infer_destroy().
ie_path_join_alloc()
static char * ie_path_join_alloc (const char * a, const char * b) static
Join two path components with exactly one slash.
Parameters
a Left component.
b Right component.
Returns
Newly allocated joined path (caller frees), or NULL on OOM.
Definition at line 548 of file infer_gptoss.c.
{
  if (!a || !b) return NULL;
  const size_t la = strlen(a);
  const size_t lb = strlen(b);
  const int need_slash = (la > 0 && a[la - 1] != '/');
  char *out = (char *)malloc(la + (size_t)need_slash + lb + 1);
  if (!out) return NULL;
  memcpy(out, a, la);
  size_t off = la;
  if (need_slash) out[off++] = '/';
  memcpy(out + off, b, lb);
  out[off + lb] = '\0';
  return out;
}
Referenced by ie_gptoss_infer_create().
ie_q4_expected_bytes()
static int ie_q4_expected_bytes (uint32_t rows, uint32_t cols, uint8_t scale_bytes, uint64_t * out_blocks_bytes, uint64_t * out_scales_bytes) static
Definition at line 1105 of file infer_gptoss.c.
{
  if (!out_blocks_bytes || !out_scales_bytes) return -1;
  if (rows == 0u || cols == 0u) return -2;
  if ((cols % 32u) != 0u) return -3;
  if (!(scale_bytes == 1u || scale_bytes == 2u)) return -4;
  const uint64_t blocks_per_row_bytes = ((uint64_t)cols / 32u) * 16u;
  const uint64_t scales_per_row_bytes = ((uint64_t)cols / 32u) * (uint64_t)scale_bytes;
  *out_blocks_bytes = (uint64_t)rows * blocks_per_row_bytes;
  *out_scales_bytes = (uint64_t)rows * scales_per_row_bytes;
  return 0;
}
Referenced by ie_gptoss_infer_create(), and ie_resolve_q4_attn_weight().
ie_require_size_eq()
static int ie_require_size_eq (const tensor_desc_t * td, uint64_t want_bytes) static
Require exact byte size for a tensor.
Parameters
td Tensor descriptor.
want_bytes Required byte size.
Returns
0 if sizes match, negative code otherwise.
Definition at line 907 of file infer_gptoss.c.
{
  if (!td) return -1;
  if (td->size_bytes == want_bytes) return 0;
  char td_buf[256];
  if (tensor_desc_to_string(td, td_buf, sizeof(td_buf)) >= 0) {
    IE_LOGE("tensor size mismatch: want_bytes=%llu got: %s",
            (unsigned long long)want_bytes, td_buf);
  } else {
    IE_LOGE("tensor size mismatch: want_bytes=%llu got_bytes=%llu name=%s",
            (unsigned long long)want_bytes,
            (unsigned long long)td->size_bytes,
            (td->name ? td->name : "<null>"));
  }
  return -2;
}
References IE_LOGE, tensor_desc_s::name, tensor_desc_s::size_bytes, and tensor_desc_to_string().
Referenced by ie_gptoss_infer_create(), ie_resolve_moe_layer(), and ie_resolve_q4_attn_weight().
ie_resolve_moe_layer()
static int ie_resolve_moe_layer (struct ie_gptoss_infer_impl * impl, uint32_t l, ie_gptoss_layer_w_t * LW) static
Definition at line 1129 of file infer_gptoss.c.
{
  if (!impl || !LW || !impl->hp) return -1;
  const uint32_t d_model = impl->hp->d_model;
  const uint32_t d_ff = impl->hp->d_ff;
  ie_tensor_view_t v_router_w, v_router_b;
  ie_tensor_view_t v_gu_blocks, v_gu_scales, v_gu_bias;
  ie_tensor_view_t v_dn_blocks, v_dn_scales, v_dn_bias;
  const char *const router_w_fmts[] = {"model.layers.%u.mlp.router.weight"};
  const char *const router_b_fmts[] = {"model.layers.%u.mlp.router.bias"};
  const char *const gu_blocks_fmts[] = {"model.layers.%u.mlp.experts.gate_up_proj_blocks"};
  const char *const gu_scales_fmts[] = {"model.layers.%u.mlp.experts.gate_up_proj_scales"};
  const char *const gu_bias_fmts[] = {"model.layers.%u.mlp.experts.gate_up_proj_bias"};
  const char *const dn_blocks_fmts[] = {"model.layers.%u.mlp.experts.down_proj_blocks"};
  const char *const dn_scales_fmts[] = {"model.layers.%u.mlp.experts.down_proj_scales"};
  const char *const dn_bias_fmts[] = {"model.layers.%u.mlp.experts.down_proj_bias"};
  if (ie_w_get_layer_fmt_view(impl, l, router_w_fmts, 1, &v_router_w, 1) != 0) {
    IE_LOGE("moe: missing router.weight layer=%u", (unsigned)l);
    return -2;
  }
  (void)ie_w_get_layer_fmt_view(impl, l, router_b_fmts, 1, &v_router_b, 0);
  if (!v_router_w.desc) return -3;
  uint32_t n_experts = 0;
  if (ie_infer_n_experts_from_router(v_router_w.desc, d_model, &n_experts) != 0) {
    char td_buf[256];
    (void)tensor_desc_to_string(v_router_w.desc, td_buf, sizeof(td_buf));
    IE_LOGE("moe: failed to infer n_experts from router.weight layer=%u d_model=%u td=%s",
            (unsigned)l, (unsigned)d_model, td_buf);
    return -4;
  }
  if (v_router_b.desc) {
    if (ie_require_size_eq(v_router_b.desc, (uint64_t)n_experts * 2u) != 0) {
      IE_LOGE("moe: router.bias size mismatch layer=%u n_experts=%u", (unsigned)l, (unsigned)n_experts);
      return -5;
    }
  }
  if (ie_w_get_layer_fmt_view(impl, l, gu_blocks_fmts, 1, &v_gu_blocks, 1) != 0) return -6;
  if (ie_w_get_layer_fmt_view(impl, l, gu_scales_fmts, 1, &v_gu_scales, 1) != 0) return -7;
  (void)ie_w_get_layer_fmt_view(impl, l, gu_bias_fmts, 1, &v_gu_bias, 0);
  if (ie_w_get_layer_fmt_view(impl, l, dn_blocks_fmts, 1, &v_dn_blocks, 1) != 0) return -8;
  if (ie_w_get_layer_fmt_view(impl, l, dn_scales_fmts, 1, &v_dn_scales, 1) != 0) return -9;
  (void)ie_w_get_layer_fmt_view(impl, l, dn_bias_fmts, 1, &v_dn_bias, 0);
  if (!v_gu_blocks.desc || !v_gu_scales.desc || !v_dn_blocks.desc || !v_dn_scales.desc) {
    IE_LOGE("moe: missing required expert tensors layer=%u", (unsigned)l);
    return -10;
  }
  uint8_t gu_scale_bytes = 0u;
  if (v_gu_scales.desc->dtype == TENSOR_DTYPE_BF16) gu_scale_bytes = 2u;
  else if (v_gu_scales.desc->dtype == TENSOR_DTYPE_U8) gu_scale_bytes = 1u;
  if (gu_scale_bytes == 0u) {
    uint64_t tmp_blocks = 0, tmp_scales_1 = 0, tmp_scales_2 = 0;
    if (ie_moe_expected_bytes(n_experts, 2u * d_ff, d_model, 1u, &tmp_blocks, &tmp_scales_1) != 0) return -11;
    if (ie_moe_expected_bytes(n_experts, 2u * d_ff, d_model, 2u, &tmp_blocks, &tmp_scales_2) != 0) return -11;
    if (v_gu_scales.desc->size_bytes == tmp_scales_1) gu_scale_bytes = 1u;
    else if (v_gu_scales.desc->size_bytes == tmp_scales_2) gu_scale_bytes = 2u;
    else {
      IE_LOGE("moe: cannot infer gate_up scale_bytes layer=%u size_bytes=%llu (want %llu or %llu)",
              (unsigned)l,
              (unsigned long long)v_gu_scales.desc->size_bytes,
              (unsigned long long)tmp_scales_1,
              (unsigned long long)tmp_scales_2);
      return -11;
    }
  }
  uint8_t dn_scale_bytes = 0u;
  if (v_dn_scales.desc->dtype == TENSOR_DTYPE_BF16) dn_scale_bytes = 2u;
  else if (v_dn_scales.desc->dtype == TENSOR_DTYPE_U8) dn_scale_bytes = 1u;
  if (dn_scale_bytes == 0u) {
    uint64_t tmp_blocks = 0, tmp_scales_1 = 0, tmp_scales_2 = 0;
    if (ie_moe_expected_bytes(n_experts, d_model, d_ff, 1u, &tmp_blocks, &tmp_scales_1) != 0) return -12;
    if (ie_moe_expected_bytes(n_experts, d_model, d_ff, 2u, &tmp_blocks, &tmp_scales_2) != 0) return -12;
    if (v_dn_scales.desc->size_bytes == tmp_scales_1) dn_scale_bytes = 1u;
    else if (v_dn_scales.desc->size_bytes == tmp_scales_2) dn_scale_bytes = 2u;
    else {
      IE_LOGE("moe: cannot infer down scale_bytes layer=%u size_bytes=%llu (want %llu or %llu)",
              (unsigned)l,
              (unsigned long long)v_dn_scales.desc->size_bytes,
              (unsigned long long)tmp_scales_1,
              (unsigned long long)tmp_scales_2);
      return -12;
    }
  }
  uint64_t want_gu_blocks = 0, want_gu_scales = 0;
  if (ie_moe_expected_bytes(n_experts, 2u * d_ff, d_model, gu_scale_bytes, &want_gu_blocks, &want_gu_scales) != 0)
    return -11;
  uint64_t want_dn_blocks = 0, want_dn_scales = 0;
  if (ie_moe_expected_bytes(n_experts, d_model, d_ff, dn_scale_bytes, &want_dn_blocks, &want_dn_scales) != 0)
    return -12;
  if (ie_require_size_eq(v_gu_blocks.desc, want_gu_blocks) != 0) return -13;
  if (ie_require_size_eq(v_gu_scales.desc, want_gu_scales) != 0) return -14;
  if (ie_require_size_eq(v_dn_blocks.desc, want_dn_blocks) != 0) return -15;
  if (ie_require_size_eq(v_dn_scales.desc, want_dn_scales) != 0) return -16;
  if (v_gu_bias.desc) {
    if (ie_require_size_eq(v_gu_bias.desc,
                           (uint64_t)n_experts * (uint64_t)(2u * d_ff) * 2u) != 0)
      return -17;
  }
  if (v_dn_bias.desc) {
    if (ie_require_size_eq(v_dn_bias.desc, (uint64_t)n_experts * (uint64_t)d_model * 2u) != 0)
      return -18;
  }
  LW->moe.n_experts = n_experts;
  LW->moe.router_w = (const uint16_t *)v_router_w.ptr;
  LW->moe.router_b = (const uint16_t *)v_router_b.ptr;
  LW->moe.router_transposed = 0;
  LW->moe.gate_up_blocks = (const uint8_t *)v_gu_blocks.ptr;
  LW->moe.gate_up_scales = (const uint8_t *)v_gu_scales.ptr;
  LW->moe.gate_up_scale_bytes = gu_scale_bytes;
  LW->moe.gate_up_bias = (const uint16_t *)v_gu_bias.ptr;
  LW->moe.down_blocks = (const uint8_t *)v_dn_blocks.ptr;
  LW->moe.down_scales = (const uint8_t *)v_dn_scales.ptr;
  LW->moe.down_scale_bytes = dn_scale_bytes;
  LW->moe.down_bias = (const uint16_t *)v_dn_bias.ptr;
  LW->moe.gate_up_blocks_stride = (size_t)(v_gu_blocks.desc->size_bytes / n_experts);
  LW->moe.gate_up_scales_stride = (size_t)(v_gu_scales.desc->size_bytes / n_experts);
  LW->moe.gate_up_bias_stride = v_gu_bias.desc ? (size_t)(v_gu_bias.desc->size_bytes / n_experts) : 0u;
  LW->moe.down_blocks_stride = (size_t)(v_dn_blocks.desc->size_bytes / n_experts);
  LW->moe.down_scales_stride = (size_t)(v_dn_scales.desc->size_bytes / n_experts);
  LW->moe.down_bias_stride = v_dn_bias.desc ? (size_t)(v_dn_bias.desc->size_bytes / n_experts) : 0u;
  if (impl->max_experts < n_experts) impl->max_experts = n_experts;
  IE_LOGI("moe: layer=%u n_experts=%u gu_scale_bytes=%u dn_scale_bytes=%u",
          (unsigned)l, (unsigned)n_experts, (unsigned)gu_scale_bytes, (unsigned)dn_scale_bytes);
  return 0;
}
References ie_gptoss_hparams::d_ff, ie_gptoss_hparams::d_model, ie_tensor_view::desc, ie_moe_w::down_bias, ie_moe_w::down_bias_stride, ie_moe_w::down_blocks, ie_moe_w::down_blocks_stride, ie_moe_w::down_scale_bytes, ie_moe_w::down_scales, ie_moe_w::down_scales_stride, tensor_desc_s::dtype, ie_moe_w::gate_up_bias, ie_moe_w::gate_up_bias_stride, ie_moe_w::gate_up_blocks, ie_moe_w::gate_up_blocks_stride, ie_moe_w::gate_up_scale_bytes, ie_moe_w::gate_up_scales, ie_moe_w::gate_up_scales_stride, ie_gptoss_infer_impl::hp, ie_infer_n_experts_from_router(), IE_LOGE, IE_LOGI, ie_moe_expected_bytes(), ie_require_size_eq(), ie_w_get_layer_fmt_view(), ie_gptoss_infer_impl::max_experts, ie_gptoss_layer_w::moe, ie_moe_w::n_experts, ie_tensor_view::ptr, ie_moe_w::router_b, ie_moe_w::router_transposed, ie_moe_w::router_w, tensor_desc_s::size_bytes, tensor_desc_to_string(), TENSOR_DTYPE_BF16, and TENSOR_DTYPE_U8.
Referenced by ie_gptoss_infer_create().
ie_resolve_q4_attn_weight()
static int ie_resolve_q4_attn_weight (struct ie_gptoss_infer_impl * impl, uint32_t l, const char *const blocks_fmts[], const char *const scales_fmts[], uint32_t rows, uint32_t cols, const char * tag, const uint8_t ** out_blocks, const uint8_t ** out_scales, uint8_t * out_scale_bytes) static
Definition at line 1284 of file infer_gptoss.c.
{
  if (!impl || !blocks_fmts || !scales_fmts || !out_blocks || !out_scales || !out_scale_bytes) return -1;
  ie_tensor_view_t v_blocks, v_scales;
  const int have_blocks =
      (ie_w_get_layer_fmt_view(impl, l, blocks_fmts, 1, &v_blocks, 0) == 0 && v_blocks.desc);
  const int have_scales =
      (ie_w_get_layer_fmt_view(impl, l, scales_fmts, 1, &v_scales, 0) == 0 && v_scales.desc);
  if (!have_blocks && !have_scales) {
    *out_blocks = NULL;
    *out_scales = NULL;
    *out_scale_bytes = 0u;
    return 0;
  }
  if (!have_blocks || !have_scales) {
    IE_LOGE("create: q4 %s missing blocks/scales layer=%u", tag, (unsigned)l);
    return -2;
  }
  uint8_t scale_bytes = 0u;
  if (v_scales.desc->dtype == TENSOR_DTYPE_BF16) scale_bytes = 2u;
  else if (v_scales.desc->dtype == TENSOR_DTYPE_U8) scale_bytes = 1u;
  if (scale_bytes == 0u) {
    uint64_t tmp_blocks = 0, tmp_scales_1 = 0, tmp_scales_2 = 0;
    if (ie_q4_expected_bytes(rows, cols, 1u, &tmp_blocks, &tmp_scales_1) != 0 ||
        ie_q4_expected_bytes(rows, cols, 2u, &tmp_blocks, &tmp_scales_2) != 0) {
      IE_LOGE("create: q4 %s bad dims layer=%u rows=%u cols=%u",
              tag, (unsigned)l, (unsigned)rows, (unsigned)cols);
      return -3;
    }
    if (v_scales.desc->size_bytes == tmp_scales_1) scale_bytes = 1u;
    else if (v_scales.desc->size_bytes == tmp_scales_2) scale_bytes = 2u;
    else {
      IE_LOGE("create: q4 %s cannot infer scale_bytes layer=%u size_bytes=%llu",
              tag, (unsigned)l, (unsigned long long)v_scales.desc->size_bytes);
      return -4;
    }
  }
  uint64_t want_blocks = 0, want_scales = 0;
  if (ie_q4_expected_bytes(rows, cols, scale_bytes, &want_blocks, &want_scales) != 0) {
    IE_LOGE("create: q4 %s bad dims layer=%u rows=%u cols=%u scale_bytes=%u",
            tag, (unsigned)l, (unsigned)rows, (unsigned)cols, (unsigned)scale_bytes);
    return -5;
  }
  if (ie_require_size_eq(v_blocks.desc, want_blocks) != 0 ||
      ie_require_size_eq(v_scales.desc, want_scales) != 0) {
    IE_LOGE("create: q4 %s size mismatch layer=%u want_blocks=%llu want_scales=%llu",
            tag, (unsigned)l,
            (unsigned long long)want_blocks,
            (unsigned long long)want_scales);
    return -6;
  }
  *out_blocks = (const uint8_t *)v_blocks.ptr;
  *out_scales = (const uint8_t *)v_scales.ptr;
  *out_scale_bytes = scale_bytes;
  return 1;
}
References ie_tensor_view::desc, tensor_desc_s::dtype, IE_LOGE, ie_q4_expected_bytes(), ie_require_size_eq(), ie_w_get_layer_fmt_view(), ie_tensor_view::ptr, tensor_desc_s::size_bytes, TENSOR_DTYPE_BF16, and TENSOR_DTYPE_U8.
Referenced by ie_gptoss_infer_create().
ie_rmsnorm_cpu_f32()
int ie_rmsnorm_cpu_f32 (const float * x, const float * w, size_t n, float eps, float * y)
RMSNorm (FP32) for a single vector.
Computes: y[i] = x[i] * w[i] / sqrt(mean(x^2) + eps)
This is the reference CPU implementation used by the GPT-OSS orchestration. Implementations may be swapped by the build in the future, but the signature is stable for the runtime.
Parameters
x Input vector (length n).
w Weight vector (length n).
n Number of elements.
eps Epsilon added to the mean square before sqrt.
y Output vector (length n). May alias x for in-place behavior.
Returns
0 on success, negative on invalid args.
RMSNorm (FP32) for a single vector.
This function performs:
mean-square accumulation with a double accumulator for improved stability,
a single sqrtf and reciprocal,
per-element scaling by the provided weight vector.
The function is designed to be allocation-free and deterministic. It does not attempt SIMD vectorization; higher-performance backends may be added later.
Parameters
x Input vector of length n.
w Per-channel scale vector of length n.
n Number of elements in x and w.
eps Small epsilon added inside the sqrt for numerical stability.
y Output vector of length n (may alias x).
Returns
0 on success, non-zero on invalid arguments.
Definition at line 928 of file infer_gptoss.c.
{
  if (!x || !w || !y || n == 0u) return -1;
  float ss = 0.0f;
  for (size_t i = 0; i < n; ++i) ss += x[i] * x[i];
  const float inv = 1.0f / sqrtf(ss / (float)n + eps);
  for (size_t i = 0; i < n; ++i) y[i] = x[i] * inv * w[i];
  return 0;
}
Referenced by ie_forward_one_token().
ie_rmsnorm_cpu_f32_bf16w()
static int ie_rmsnorm_cpu_f32_bf16w (const float * x, const uint16_t * w_bf16, size_t n, float eps, float * y) static
Definition at line 940 of file infer_gptoss.c.
{
  if (!x || !w_bf16 || !y || n == 0u) return -1;
  float ss = 0.0f;
  for (size_t i = 0; i < n; ++i) ss += x[i] * x[i];
  const float inv = 1.0f / sqrtf(ss / (float)n + eps);
  for (size_t i = 0; i < n; ++i) {
    const float wi = ie_bf16_to_f32(w_bf16[i]);
    y[i] = x[i] * inv * wi;
  }
  return 0;
}
References ie_bf16_to_f32().
Referenced by ie_forward_one_token().
ie_rope_apply_f32()
int ie_rope_apply_f32 (float * q, float * k, size_t heads, size_t head_dim, uint32_t pos, float theta)
Apply Rotary Positional Embedding (RoPE) to Q and K for a single position.
Apply RoPE to Q and/or K for multiple heads.
This function applies RoPE on the first head_dim elements, interpreted as interleaved pairs (even, odd): (x0, x1) -> (x0*cos - x1*sin, x0*sin + x1*cos)
The caller passes Q and K shaped as [heads, head_dim] flattened.
Parameters
q Q buffer, [heads * head_dim].
k K buffer, [heads * head_dim].
heads Number of heads in q/k.
head_dim Head dimension (must be even for paired rotation).
pos Sequence position (0-based).
theta RoPE base (commonly 10000.0f).
Returns
0 on success, negative on invalid args.
Definition at line 955 of file infer_gptoss.c.
{
  if (head_dim == 0u || (head_dim & 1u) != 0u) return -1;
  if (!q && !k) return 0;
  const size_t half = head_dim / 2u;
  const float log_theta = logf(theta);
  for (size_t h = 0; h < heads; ++h) {
    float *vq = q ? (q + h * head_dim) : NULL;
    float *vk = k ? (k + h * head_dim) : NULL;
    for (size_t i = 0; i < half; ++i) {
      const float exponent = -2.0f * (float)i / (float)head_dim;
      const float inv_freq = expf(log_theta * exponent);
      const float ang = (float)pos * inv_freq;
      const float c = cosf(ang);
      const float s = sinf(ang);
      const size_t i0 = 2u * i;
      const size_t i1 = i0 + 1u;
      if (vq) {
        const float x0 = vq[i0];
        const float x1 = vq[i1];
        vq[i0] = x0 * c - x1 * s;
        vq[i1] = x0 * s + x1 * c;
      }
      if (vk) {
        const float x0 = vk[i0];
        const float x1 = vk[i1];
        vk[i0] = x0 * c - x1 * s;
        vk[i1] = x0 * s + x1 * c;
      }
    }
  }
  return 0;
}
References ie_rope_apply_one_f32().
Referenced by ie_forward_one_token().
ie_silu_f32()
static float ie_silu_f32 (float x) inline static
SiLU activation function.
Parameters
x Input.
Returns
SiLU(x).
Definition at line 706 of file infer_gptoss.c.
{ return x / (1.0f + expf(-x)); }
Referenced by ie_forward_one_token().
ie_softmax_inplace_f32()
static void ie_softmax_inplace_f32 (float * x, size_t n) static
In-place softmax over an array of float32 values.
Parameters
x Array (modified in-place).
n Number of elements.
Definition at line 761 of file infer_gptoss.c.
{
  if (!x || n == 0u) return;
  float m = x[0];
  for (size_t i = 1; i < n; ++i)
    if (x[i] > m) m = x[i];
  float sum = 0.0f;
  for (size_t i = 0; i < n; ++i) {
    x[i] = expf(x[i] - m);
    sum += x[i];
  }
  const float inv = (sum > 0.0f) ? (1.0f / sum) : 1.0f;
  for (size_t i = 0; i < n; ++i) x[i] *= inv;
}
Referenced by ie_attn_causal_gqa_f32(), ie_attn_cpu_causal_f32(), and ie_forward_one_token().
ie_trace_bf16_enabled_()
static int ie_trace_bf16_enabled_ (void) static
Definition at line 717 of file infer_gptoss.c.
{
  static int cached = -1;
  if (cached < 0) {
    const char *s = getenv("IE_TRACE_BF16");
    cached = (s && s[0] && strcmp(s, "0") != 0) ? 1 : 0;
  }
  return cached;
}
Referenced by ie_forward_one_token().
ie_u32_min()
static uint32_t ie_u32_min (uint32_t a, uint32_t b) static
Return the minimum of two uint32_t values.
Parameters
a First value.
b Second value.
Returns
min(a, b).
Definition at line 503 of file infer_gptoss.c.
{ return (a < b) ? a : b; }
Referenced by ie_forward_one_token().
ie_w_find()
static const tensor_desc_t * ie_w_find (const tensor_map_t * tmap, const char * name) static
Find a tensor descriptor by name in a tensor map.
Parameters
tmap Tensor map.
name Tensor name.
Returns
Descriptor pointer or NULL if not found.
Definition at line 798 of file infer_gptoss.c.
{
  if (!tmap || !name) return NULL;
  return tensor_map_find(tmap, name);
}
References tensor_map_find().
Referenced by ie_w_get_view().
ie_w_get_first_view()
static int ie_w_get_first_view (const struct ie_gptoss_infer_impl * impl, const char *const * names, size_t count, ie_tensor_view_t * out) static
Resolve the first tensor found among a list of candidate names.
Parameters
impl Inference implementation.
names Candidate name array.
count Candidate count.
out Output view.
Returns
0 on success, negative code on failure.
Definition at line 836 of file infer_gptoss.c.
{
  if (!impl || !names || !out) return -1;
  for (size_t i = 0; i < count; ++i) {
    const int rc = ie_w_get_view(impl, names[i], out);
    if (rc == 0) {
      char td_buf[256];
      if (out->desc && tensor_desc_to_string(out->desc, td_buf, sizeof(td_buf)) >= 0) {
        IE_LOGD("resolved tensor: %s", td_buf);
      } else {
        IE_LOGD("resolved tensor: name=%s", names[i]);
      }
      return 0;
    }
  }
  out->ptr = NULL;
  out->desc = NULL;
  return -2;
}
References IE_LOGD, ie_w_get_view(), and tensor_desc_to_string().
Referenced by ie_gptoss_infer_create().
ie_w_get_layer_fmt_view()
static int ie_w_get_layer_fmt_view (const struct ie_gptoss_infer_impl * impl, uint32_t layer, const char *const * fmts, size_t count, ie_tensor_view_t * out, int required) static
Resolve a layer tensor using a list of snprintf formats.
Parameters
impl Inference implementation.
layer Layer index.
fmts Candidate snprintf formats (must include u for layer).
count Candidate format count.
out Output view.
required If nonzero, missing tensor is an error; otherwise returns success with NULL view.
Returns
0 on success, negative code on failure.
Definition at line 866 of file infer_gptoss.c.
{
  if (!impl || !fmts || !out) return -1;
  out->ptr = NULL;
  out->desc = NULL;
  char name[256];
  for (size_t i = 0; i < count; ++i) {
    int n = snprintf(name, sizeof(name), fmts[i], layer);
    if (n <= 0 || (size_t)n >= sizeof(name)) continue;
    if (ie_w_get_view(impl, name, out) == 0) {
      char td_buf[256];
      if (out->desc && tensor_desc_to_string(out->desc, td_buf, sizeof(td_buf)) >= 0) {
        IE_LOGD("resolved layer tensor: layer=%u %s", (unsigned)layer, td_buf);
      } else {
        IE_LOGD("resolved layer tensor: layer=%u name=%s", (unsigned)layer, name);
      }
      return 0;
    }
  }
  if (!required) {
    out->ptr = NULL;
    out->desc = NULL;
    return 0;
  }
  IE_LOGE("missing required layer tensor: layer=%u (tried %zu formats)", (unsigned)layer, count);
  for (size_t i = 0; i < count; ++i) {
    IE_LOGE("  candidate fmt[%zu]=%s", i, fmts[i]);
  }
  return -2;
}
References IE_LOGD, IE_LOGE, ie_w_get_view(), and tensor_desc_to_string().
Referenced by ie_gptoss_infer_create(), ie_resolve_moe_layer(), and ie_resolve_q4_attn_weight().
ie_w_get_view()
static int ie_w_get_view (const struct ie_gptoss_infer_impl * impl, const char * name, ie_tensor_view_t * out) static
Resolve a tensor pointer by name.
Parameters
impl Inference implementation.
name Tensor name.
out Output view.
Returns
0 on success, negative code on failure.
Definition at line 810 of file infer_gptoss.c.
{
  if (!impl || !name || !out) return -1;
  out->ptr = NULL;
  out->desc = NULL;
  const tensor_desc_t *td = ie_w_find(&impl->tmap, name);
  if (!td) return -2;
  const uint64_t off = td->offset;
  const uint64_t nb = td->size_bytes;
  if ((uint64_t)impl->bin_size < off + nb) return -3;
  out->desc = td;
  out->ptr = (const void *)(impl->bin_base + (size_t)off);
  return 0;
}
References ie_gptoss_infer_impl::bin_base, ie_gptoss_infer_impl::bin_size, ie_w_find(), tensor_desc_s::offset, tensor_desc_s::size_bytes, and ie_gptoss_infer_impl::tmap.
Referenced by ie_w_get_first_view(), and ie_w_get_layer_fmt_view().
Variable Documentation
ie_log_level_cached
int ie_log_level_cached = -1 static
Cached log level parsed from IE_LOG_LEVEL (negative means "unset").
Definition at line 84 of file infer_gptoss.c.
Referenced by ie_log_level().