Inference Engine (Clocher): engine/src/quant/int4_ptq.c File Reference
int4_ptq.c File Reference
Implementation of 4-bit (INT4) weight-only quantization utilities.
#include "ie_quant_int4.h"
#include <math.h>
#include <float.h>
#include <string.h>
Functions
static int clamp_q4 (float x)
Clamp a float to the symmetric INT4 range [-7, +7] and convert to int.
static uint8_t pack_q4_pair (int q0, int q1)
Pack two signed 4-bit integers (in [-7, +7]) into a single byte.
static void unpack_q4_pair (uint8_t byte, int *out_q0, int *out_q1)
Unpack two signed 4-bit integers from a single byte.
static int bad_float3 (double a, double b, double c)
Return true if any of a, b, c is NaN or infinite.
size_t ie_int4_rowbytes (size_t cols)
Compute the number of packed bytes required to store a single row of cols 4-bit values (two per byte).
int ie_int4_absmax (const float *src, size_t rows, size_t cols, float *out_absmax)
Compute the absolute-maximum value of a float32 matrix.
int ie_int4_absmax_per_row (const float *src, size_t rows, size_t cols, float *out_absmax_rows)
Compute per-row absolute-maximums of a float32 matrix.
int ie_int4_quantize_per_tensor (const float *src, size_t rows, size_t cols, uint8_t *dst_packed, float *out_scale)
Quantize a float32 matrix to packed INT4 using a single (per-tensor) scale.
int ie_int4_dequantize_per_tensor (const uint8_t *src_packed, size_t rows, size_t cols, float scale, float *dst)
Dequantize a packed INT4 matrix using a single (per-tensor) scale.
int ie_int4_quantize_per_row (const float *src, size_t rows, size_t cols, uint8_t *dst_packed, float *out_scales)
Quantize a float32 matrix to packed INT4 with per-row scales.
int ie_int4_dequantize_per_row (const uint8_t *src_packed, size_t rows, size_t cols, const float *scales, float *dst)
Dequantize a packed INT4 matrix with per-row scales.
int ie_int4_error_metrics (const float *ref, const float *test, size_t n, double *out_mse, double *out_cosine)
Compute error metrics between two float32 vectors of equal length: mean squared error (MSE) and cosine similarity.
Detailed Description
Implementation of 4-bit (INT4) weight-only quantization utilities.
See Ie_int4_quant for API details and packing rules.
Definition in file int4_ptq.c.
Function Documentation
bad_float3()
static int bad_float3 (double a, double b, double c) inline static
Return true if any of a, b, c is NaN or infinite.
Definition at line 63 of file int4_ptq.c.
{
   return (!isfinite(a) || !isfinite(b) || !isfinite(c));
 }
Referenced by ie_int4_error_metrics().
clamp_q4()
static int clamp_q4 (float x) inline static
Clamp a float to the symmetric INT4 range [-7, +7] and convert to int.
Parameters
x Input value (already divided by scale).
Returns
Rounded and clamped integer in [-7, +7].
Definition at line 22 of file int4_ptq.c.
{
   /* round to nearest even is fine; typical compilers use roundf. */
   float r = roundf(x);
   if (r > 7.0f)  return 7;
   if (r < -7.0f) return -7;
   return (int)r;
 }
Referenced by ie_int4_quantize_per_row(), and ie_int4_quantize_per_tensor().
pack_q4_pair()
static uint8_t pack_q4_pair (int q0, int q1) inline static
Pack two signed 4-bit integers (in [-7, +7]) into a single byte.
Values are first biased by +8 to map them to [1, 15] (0 is unused here), then stored as low/high nibbles: low for even column, high for odd column.
Parameters
q0 First value (even column).
q1 Second value (odd column).
Returns
Packed byte.
Definition at line 40 of file int4_ptq.c.
{
   uint8_t n0 = (uint8_t)(q0 + 8); /* 1..15 (0 reserved for -8, not used) */
   uint8_t n1 = (uint8_t)(q1 + 8);
   return (uint8_t)((n1 << 4) | (n0 & 0x0F));
 }
Referenced by ie_int4_quantize_per_row(), and ie_int4_quantize_per_tensor().
unpack_q4_pair()
static void unpack_q4_pair (uint8_t byte, int * out_q0, int * out_q1) inline static
Unpack two signed 4-bit integers from a single byte.
Parameters
byte Packed byte.
out_q0 Output pointer for low-nibble decoded value in [-8, +7].
out_q1 Output pointer for high-nibble decoded value in [-8, +7].
Definition at line 53 of file int4_ptq.c.
{
   int n0 = (int)(byte & 0x0F);
   int n1 = (int)((byte >> 4) & 0x0F);
   *out_q0 = n0 - 8;
   *out_q1 = n1 - 8;
 }
Referenced by ie_int4_dequantize_per_row(), and ie_int4_dequantize_per_tensor().