Inference Engine (Clocher): engine/src/io/mmap_tuning.c File Reference
mmap_tuning.c File Reference
Implementation of portable mmap tuning helpers.
#include "ie_mmap_tuning.h"
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
Macros
#define _GNU_SOURCE 1
#define _POSIX_C_SOURCE 200809L
Functions
static int map_policy_to_madvise (ie_page_policy p)
Map ie_page_policy to madvise() flag where possible.
static int best_effort_madvise (void *addr, size_t length, int advice)
Safe wrapper around madvise (best-effort).
int ie_mmap_advise (void *addr, size_t length, ie_page_policy policy)
Apply a memory access policy to a mapped region (best-effort).
int ie_mmap_fadvise (int fd, off_t offset, off_t length, ie_page_policy policy)
Provide file-cache hints for a file descriptor (best-effort).
int ie_mmap_advise_thp (void *addr, size_t length, int enable)
Suggest Transparent Huge Pages (THP) for a mapped region (best-effort).
int ie_mmap_readahead (int fd, off_t offset, size_t length)
Try to pre-populate page cache for a file range (best-effort).
size_t ie_mmap_kernel_hugepagesize (void)
Read the kernel HugeTLB default page size in bytes, if known.
int ie_mmap_prefault_touch_ro (const void *addr, size_t length, size_t stride, uint64_t *checksum)
Quick in-place page touching to prefault a region into RSS.
Detailed Description
Implementation of portable mmap tuning helpers.
See ie_mmap_tuning.h for the public API and behavioral contract.
Definition in file mmap_tuning.c.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE 1
Definition at line 12 of file mmap_tuning.c.
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 13 of file mmap_tuning.c.
Function Documentation
best_effort_madvise()
static int best_effort_madvise (void * addr, size_t length, int advice) static
Safe wrapper around madvise (best-effort).
Returns 0 if unsupported (no-op), -1 on hard misuse errors.
Definition at line 54 of file mmap_tuning.c.
{
  if (!addr || length == 0) { errno = EINVAL; return -1; }
#if defined(__linux__)
  if (advice < 0) return 0; /* treat unsupported advice as no-op */
  if (madvise(addr, length, advice) != 0) {
    /* EINVAL for unknown flags/unaligned size: treat as best-effort success. */
    if (errno == EINVAL || errno == ENOSYS || errno == ENOTSUP) return 0;
    return -1;
  }
#else
  (void)addr; (void)length; (void)advice;
#endif
  return 0;
}
Referenced by ie_mmap_advise(), and ie_mmap_advise_thp().
ie_mmap_advise()
int ie_mmap_advise (void * addr, size_t length, ie_page_policy policy)
Apply a memory access policy to a mapped region (best-effort).
Internally attempts madvise() with the nearest matching advice (MADV_NORMAL, MADV_RANDOM, MADV_SEQUENTIAL, MADV_WILLNEED, MADV_DONTNEED). If madvise() is unavailable, the call becomes a no-op.
Parameters
addr Base address of the mapped region (page-aligned recommended).
length Length in bytes of the region (rounded up by the kernel).
policy Desired policy.
Returns
0 on success or harmless no-op, -1 on hard error (errno set).
Definition at line 71 of file mmap_tuning.c.
{
  const int adv = map_policy_to_madvise(policy);
  return best_effort_madvise(addr, length, adv);
}
References best_effort_madvise(), and map_policy_to_madvise().
ie_mmap_advise_thp()
int ie_mmap_advise_thp (void * addr, size_t length, int enable)
Suggest Transparent Huge Pages (THP) for a mapped region (best-effort).
Attempts madvise(addr, len, MADV_HUGEPAGE) when available. If enable is 0, attempts MADV_NOHUGEPAGE. If the kernel lacks these flags, this function becomes a no-op and still returns 0.
Parameters
addr Start of the region.
length Size of the region in bytes.
enable Non-zero to request THP; zero to explicitly disable THP.
Returns
0 on success or harmless no-op, -1 on hard error (errno set).
Definition at line 121 of file mmap_tuning.c.
{
#if defined(__linux__)
  /* Prefer explicit THP advice if available; otherwise no-op. */
  #if defined(MADV_HUGEPAGE) && defined(MADV_NOHUGEPAGE)
    return best_effort_madvise(addr, length, enable ? MADV_HUGEPAGE : MADV_NOHUGEPAGE);
  #else
    (void)addr; (void)length; (void)enable;
    return 0;
  #endif
#else
  (void)addr; (void)length; (void)enable;
  return 0;
#endif
}
References best_effort_madvise().
Referenced by ie_mmap_open().
ie_mmap_fadvise()
int ie_mmap_fadvise (int fd, off_t offset, off_t length, ie_page_policy policy)
Provide file-cache hints for a file descriptor (best-effort).
Internally attempts posix_fadvise() with POSIX_FADV_* equivalents. Not all ie_page_policy values have a 1:1 mapping; unsupported ones degrade to a reasonable fallback or a no-op.
Parameters
fd Open file descriptor for the mapped file.
offset Starting byte offset within the file.
length Number of bytes to advise (0 may mean "to EOF" on Linux).
policy Policy to hint (NORMAL/SEQUENTIAL/RANDOM/WILLNEED/DONTNEED).
Returns
0 on success or harmless no-op, -1 on hard error (errno set).
Definition at line 76 of file mmap_tuning.c.
{
  if (fd < 0) { errno = EBADF; return -1; }
#if defined(__linux__) || defined(_POSIX_VERSION)
  int adv = 0;
  switch (policy) {
    case IE_PAGE_NORMAL:     adv = 0 /* POSIX_FADV_NORMAL */; break;
    case IE_PAGE_RANDOM:     adv = 1 /* POSIX_FADV_RANDOM */; break;
    case IE_PAGE_SEQUENTIAL: adv = 2 /* POSIX_FADV_SEQUENTIAL */; break;
    case IE_PAGE_WILLNEED:   adv = 3 /* POSIX_FADV_WILLNEED */; break;
    case IE_PAGE_DONTNEED:   adv = 4 /* POSIX_FADV_DONTNEED */; break;
    default:                 adv = 0; break;
  }
  /* Use macros if they exist; fall back to literal values otherwise. */
  #if defined(POSIX_FADV_NORMAL)
    if (policy == IE_PAGE_NORMAL)     adv = POSIX_FADV_NORMAL;
  #endif
  #if defined(POSIX_FADV_RANDOM)
    if (policy == IE_PAGE_RANDOM)     adv = POSIX_FADV_RANDOM;
  #endif
  #if defined(POSIX_FADV_SEQUENTIAL)
    if (policy == IE_PAGE_SEQUENTIAL) adv = POSIX_FADV_SEQUENTIAL;
  #endif
  #if defined(POSIX_FADV_WILLNEED)
    if (policy == IE_PAGE_WILLNEED)   adv = POSIX_FADV_WILLNEED;
  #endif
  #if defined(POSIX_FADV_DONTNEED)
    if (policy == IE_PAGE_DONTNEED)   adv = POSIX_FADV_DONTNEED;
  #endif
  /* posix_fadvise returns an errno-style code, not -1. */
  #if defined(__GLIBC__) || defined(__linux__) || defined(__APPLE__) || defined(__FreeBSD__)
    int rc = posix_fadvise(fd, offset, length, adv);
    if (rc == EINVAL || rc == ENOSYS || rc == ENOTSUP) return 0; /* best-effort */
    if (rc != 0) { errno = rc; return -1; }
    return 0;
  #else
    (void)offset; (void)length; (void)adv;
    return 0;
  #endif
#else
  (void)fd; (void)offset; (void)length; (void)policy;
  return 0;
#endif
}
References IE_PAGE_DONTNEED, IE_PAGE_NORMAL, IE_PAGE_RANDOM, IE_PAGE_SEQUENTIAL, and IE_PAGE_WILLNEED.
Referenced by ie_mmap_open(), and ie_mmap_readahead().
ie_mmap_kernel_hugepagesize()
size_t ie_mmap_kernel_hugepagesize (void)
Read the kernel HugeTLB default page size in bytes, if known.
Parses /proc/meminfo line Hugepagesize: on Linux. Returns 0 if unknown.
Returns
HugeTLB page size in bytes, or 0 if not detected.
Definition at line 162 of file mmap_tuning.c.
{
#if defined(__linux__)
  FILE *f = fopen("/proc/meminfo", "r");
  if (!f) return 0;
  char line[256];
  size_t kbytes = 0;
  while (fgets(line, (int)sizeof(line), f)) {
    /* Example: "Hugepagesize:       2048 kB" */
    if (strncmp(line, "Hugepagesize:", 13) == 0) {
      unsigned long v = 0;
      if (sscanf(line + 13, "%lu kB", &v) == 1) {
        kbytes = (size_t)v;
        break;
      }
    }
  }
  fclose(f);
  return kbytes ? (kbytes * 1024u) : 0u;
#else
  return 0u;
#endif
}
ie_mmap_prefault_touch_ro()
int ie_mmap_prefault_touch_ro (const void * addr, size_t length, size_t stride, uint64_t * checksum)
Quick in-place page touching to prefault a region into RSS.
Strides by cache-line (default 64 bytes) to force-demand paging in a bounded manner. Safe for read-only mappings. This is independent from readahead and can be used after mmap() to ensure residency.
Parameters
addr Base pointer of the mapped region.
length Number of bytes to touch.
stride Stride in bytes (use 64 or 128). Zero selects 64.
checksum Optional out pointer to receive a lightweight checksum (may be NULL). Helps compilers keep the loop intact.
Returns
0 on success; -1 if inputs are invalid.
Definition at line 185 of file mmap_tuning.c.
{
  if (!addr || length == 0) { errno = EINVAL; return -1; }
  const size_t step = (stride == 0 ? 64u : stride);
  const volatile unsigned char *p = (const volatile unsigned char *)addr;
  uint64_t acc = 0u;
  /* Bound the loop to [0, length). Use volatile loads to keep it intact. */
  for (size_t i = 0; i < length; i += step) {
    acc += p[i];
  }
  /* Touch the last byte to ensure the tail page is demand-paged too. */
  acc += p[length - 1u];
  if (checksum) *checksum = acc;
  return 0;
}
Referenced by ie_mmap_touch().
ie_mmap_readahead()
int ie_mmap_readahead (int fd, off_t offset, size_t length)
Try to pre-populate page cache for a file range (best-effort).
On Linux, first tries the readahead(2) system call; if unavailable, falls back to posix_fadvise(..., POSIX_FADV_WILLNEED) as a weaker hint.
Parameters
fd Open file descriptor.
offset Start offset in bytes.
length Length in bytes; use a reasonable cap (e.g., mapped size).
Returns
0 on success or harmless no-op, -1 on hard error (errno set).
Definition at line 136 of file mmap_tuning.c.
{
  if (fd < 0) { errno = EBADF; return -1; }
#if defined(__linux__)
  /* Try the Linux readahead(2) syscall first. */
  #ifdef SYS_readahead
    /* NB: readahead returns 0 on success, or -1 with errno on failure. */
    ssize_t rc = (ssize_t)syscall(SYS_readahead, fd, (off64_t)offset, (size_t)length);
    if (rc == 0) return 0;
    if (errno == ENOSYS || errno == EINVAL || errno == EPERM) {
      /* Fall back to posix_fadvise WILLNEED. */
      (void)ie_mmap_fadvise(fd, offset, (off_t)length, IE_PAGE_WILLNEED);
      return 0;
    }
    return -1;
  #else
    /* No SYS_readahead: fall back to posix_fadvise WILLNEED. */
    (void)ie_mmap_fadvise(fd, offset, (off_t)length, IE_PAGE_WILLNEED);
    return 0;
  #endif
#else
  /* Non-Linux: best-effort posix_fadvise if available. */
  (void)ie_mmap_fadvise(fd, offset, (off_t)length, IE_PAGE_WILLNEED);
  return 0;
#endif
}
References ie_mmap_fadvise(), and IE_PAGE_WILLNEED.
Referenced by ie_mmap_open().
map_policy_to_madvise()
static int map_policy_to_madvise (ie_page_policy p) static
Map ie_page_policy to madvise() flag where possible.
Definition at line 33 of file mmap_tuning.c.
{
#if defined(__linux__)
  switch (p) {
    case IE_PAGE_NORMAL:     return MADV_NORMAL;
    case IE_PAGE_RANDOM:     return MADV_RANDOM;
    case IE_PAGE_SEQUENTIAL: return MADV_SEQUENTIAL;
    case IE_PAGE_WILLNEED:   return MADV_WILLNEED;
    case IE_PAGE_DONTNEED:   return MADV_DONTNEED;
    default:                 return MADV_NORMAL;
  }
#else
  (void)p;
  return -1; /* not supported on this platform */
#endif
}
References IE_PAGE_DONTNEED, IE_PAGE_NORMAL, IE_PAGE_RANDOM, IE_PAGE_SEQUENTIAL, and IE_PAGE_WILLNEED.
Referenced by ie_mmap_advise().