Inference Engine (Clocher): pack_moe_q4_from_hf Namespace Reference
pack_moe_q4_from_hf Namespace Reference
Data Structures
class HFIndex
Functions
int align_up (int x, int a=ALIGN)
read_safetensors_header (f)
np.ndarray bf16_to_f32_from_u16 (np.ndarray u16)
np.ndarray f32_to_bf16_u16 (np.ndarray x)
int infer_num_experts_from_index (dict weight_map, int layer)
np.ndarray orient_linear_weight (np.ndarray w, int in_features, int out_features, str name)
quantize_q4_0_blocks (np.ndarray mat_f32, int block_k=BLOCK_K)
Variables
int ALIGN = 64
int BLOCK_K = 32
Function Documentation
align_up()
int pack_moe_q4_from_hf.align_up (int x, int a = ALIGN)
Definition at line 13 of file pack_moe_q4_from_hf.py.
def align_up(x: int, a: int = ALIGN) -> int:
    return (x + (a - 1)) & ~(a - 1)
bf16_to_f32_from_u16()
np.ndarray pack_moe_q4_from_hf.bf16_to_f32_from_u16 (np.ndarray u16)
Definition at line 27 of file pack_moe_q4_from_hf.py.
def bf16_to_f32_from_u16(u16: np.ndarray) -> np.ndarray:
    u32 = (u16.astype(np.uint32) << 16)
    return u32.view(np.float32)
Referenced by pack_moe_q4_from_hf.HFIndex.read_tensor_f32().
f32_to_bf16_u16()
np.ndarray pack_moe_q4_from_hf.f32_to_bf16_u16 (np.ndarray x)
Definition at line 31 of file pack_moe_q4_from_hf.py.
def f32_to_bf16_u16(x: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=np.float32)
    u32 = x.view(np.uint32)
    return (u32 >> 16).astype(np.uint16)
Referenced by quantize_q4_0_blocks().
infer_num_experts_from_index()
int pack_moe_q4_from_hf.infer_num_experts_from_index (dict weight_map, int layer)
Definition at line 105 of file pack_moe_q4_from_hf.py.
def infer_num_experts_from_index(weight_map: dict, layer: int) -> int:
    prefix = f"model.layers.{layer}.mlp.experts."
    max_id = -1
    for k in weight_map.keys():
        if not k.startswith(prefix):
            continue
        rest = k[len(prefix):]
        parts = rest.split(".", 1)
        if not parts:
            continue
        try:
            eid = int(parts[0])
        except ValueError:
            continue
        if eid > max_id:
            max_id = eid
    if max_id < 0:
        raise SystemExit(f"ERROR: could not infer num_experts from index for layer {layer}")
    return max_id + 1
orient_linear_weight()
np.ndarray pack_moe_q4_from_hf.orient_linear_weight (np.ndarray w, int in_features, int out_features, str name)
Definition at line 125 of file pack_moe_q4_from_hf.py.
def orient_linear_weight(w: np.ndarray, in_features: int, out_features: int, name: str) -> np.ndarray:
    if w.ndim != 2:
        raise SystemExit(f"ERROR: '{name}' expected 2D weight, got shape={list(w.shape)}")
    r, c = int(w.shape[0]), int(w.shape[1])
    if r == out_features and c == in_features:
        return w
    if r == in_features and c == out_features:
        return w.T
    raise SystemExit(
        f"ERROR: '{name}' shape={list(w.shape)} does not match "
        f"either [{out_features},{in_features}] or [{in_features},{out_features}]"
    )
quantize_q4_0_blocks()
pack_moe_q4_from_hf.quantize_q4_0_blocks (np.ndarray mat_f32, int block_k = BLOCK_K)
Definition at line 138 of file pack_moe_q4_from_hf.py.
def quantize_q4_0_blocks(mat_f32: np.ndarray, block_k: int = BLOCK_K):
    mat = np.asarray(mat_f32, dtype=np.float32)
    if mat.ndim != 2:
        raise SystemExit(f"ERROR: quantize expects 2D, got {mat.ndim}D")
    rows, cols = int(mat.shape[0]), int(mat.shape[1])
    if cols % block_k != 0:
        raise SystemExit(f"ERROR: cols={cols} not divisible by block_k={block_k}")
    nb = cols // block_k
    scales_u16 = np.empty((rows, nb), dtype=np.uint16)
    blocks_u8 = np.empty((rows, nb, block_k // 2), dtype=np.uint8)  # 16 bytes per 32 cols
    for r in range(rows):
        row = mat[r]
        for b in range(nb):
            x = row[b * block_k : (b + 1) * block_k]
            absmax = float(np.max(np.abs(x))) if x.size else 0.0
            if absmax == 0.0:
                scale = np.float32(1.0)
                q = np.zeros((block_k,), dtype=np.int32)
            else:
                scale = np.float32(absmax / 7.0)
                q = np.rint(x / scale).astype(np.int32)
                q = np.clip(q, -7, 7)
            scales_u16[r, b] = f32_to_bf16_u16(scale)[()]
References f32_to_bf16_u16().
read_safetensors_header()
pack_moe_q4_from_hf.read_safetensors_header (f)
Definition at line 16 of file pack_moe_q4_from_hf.py.
def read_safetensors_header(f):
    hdr_len_bytes = f.read(8)
    if len(hdr_len_bytes) != 8:
        raise RuntimeError("Failed to read safetensors header length")
    (hdr_len,) = struct.unpack("<Q", hdr_len_bytes)
    hdr_json = f.read(hdr_len)
    if len(hdr_json) != hdr_len:
        raise RuntimeError("Failed to read safetensors header JSON")
    header = json.loads(hdr_json.decode("utf-8"))
    return header, 8 + hdr_len
Referenced by pack_moe_q4_from_hf.HFIndex._load_shard_header().
Variable Documentation
ALIGN
int pack_moe_q4_from_hf.ALIGN = 64
Definition at line 10 of file pack_moe_q4_from_hf.py.
BLOCK_K
int pack_moe_q4_from_hf.BLOCK_K = 32
Definition at line 11 of file pack_moe_q4_from_hf.py.