Inference Engine (Clocher): dedup_verify_int4 Namespace Reference
dedup_verify_int4 Namespace Reference
Data Structures
class TensorRec
Functions
object _load_json (str path)
bytes _read_all (str path)
bytes _read_slice (str path, int offset, int nbytes)
int _ceil_div (int a, int b)
int _mask_nbytes (int nbytes)
Tuple[str, Dict[int, TensorRec]] _parse_tensor_map (object tensor_map)
bytes _reconstruct (bytes default_bytes, bytes mask, bytes exc)
int main ()
Detailed Description
dedup_verify_int4.py
Lossless verifier for byte-oriented dedup artifacts.
This tool:
  - Loads model.dedup.json
  - Reads defaults/masks/exceptions binaries
  - Reconstructs each target tensor
  - Reads the original target tensor bytes from weights_bin using tensor map
  - Byte-compares reconstructed vs original
Inputs:
  - --model-dir: model directory containing weights_bin
  - --tensor-map: JSON mapping tensor indices -> (offset,nbytes)
  - --spec: dedup spec JSON (model.dedup.json)
  - --out-prefix: prefix used by extractor (to locate bin files if spec uses basenames)
Usage:
  python3 tools/dedup_verify_int4.py \
    --model-dir models/gpt-oss-20b \
    --tensor-map models/gpt-oss-20b/model.tensor_map.json \
    --spec models/gpt-oss-20b/model.dedup.json
Function Documentation
_ceil_div()
int dedup_verify_int4._ceil_div (int a, int b) protected
Compute ceil(a/b) for non-negative integers.
Definition at line 66 of file dedup_verify_int4.py.
def _ceil_div(a: int, b: int) -> int:
    """Compute ceil(a/b) for non-negative integers."""
    return (a + b - 1) // b
Referenced by _mask_nbytes().
_load_json()
object dedup_verify_int4._load_json (str path) protected
Load and parse a JSON file.
Definition at line 44 of file dedup_verify_int4.py.
def _load_json(path: str) -> object:
    """Load and parse a JSON file."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)
References ie_gemv_rowwise_f32_kernel().
Referenced by main().
_mask_nbytes()
int dedup_verify_int4._mask_nbytes (int nbytes) protected
Return the number of mask bytes needed for a tensor of size nbytes.
Definition at line 71 of file dedup_verify_int4.py.
def _mask_nbytes(nbytes: int) -> int:
    """Return the number of mask bytes needed for a tensor of size nbytes."""
    return _ceil_div(nbytes, 8)
References _ceil_div().
Referenced by _reconstruct().
_parse_tensor_map()
Tuple[str, Dict[int, TensorRec]] dedup_verify_int4._parse_tensor_map (object tensor_map) protected
Parse the tensor map JSON object into a lookup table.
Definition at line 76 of file dedup_verify_int4.py.
def _parse_tensor_map(tensor_map: object) -> Tuple[str, Dict[int, TensorRec]]:
    """Parse the tensor map JSON object into a lookup table."""
    if not isinstance(tensor_map, dict):
        raise ValueError("tensor map JSON must be an object")
    weights_bin = tensor_map.get("weights_bin")
    tensors = tensor_map.get("tensors")
    if not isinstance(weights_bin, str) or not isinstance(tensors, list):
        raise ValueError("tensor map JSON must contain 'weights_bin' (str) and 'tensors' (list)")
    out: Dict[int, TensorRec] = {}
    for t in tensors:
        idx = int(t["index"])
        name = str(t.get("name", f"tensor_{idx}"))
        off = int(t["offset"])
        nb = int(t["nbytes"])
        out[idx] = TensorRec(index=idx, name=name, offset=off, nbytes=nb)
    return weights_bin, out
References ie_gemv_rowwise_f32_kernel().
Referenced by main().
_read_all()
bytes dedup_verify_int4._read_all (str path) protected
Read entire binary file into memory.
Definition at line 50 of file dedup_verify_int4.py.
def _read_all(path: str) -> bytes:
    """Read entire binary file into memory."""
    with open(path, "rb") as f:
        return f.read()
References ie_gemv_rowwise_f32_kernel().
Referenced by main().
_read_slice()
bytes dedup_verify_int4._read_slice (str path, int offset, int nbytes) protected
Read a slice from a file at a given offset.
Definition at line 56 of file dedup_verify_int4.py.
def _read_slice(path: str, offset: int, nbytes: int) -> bytes:
    """Read a slice from a file at a given offset."""
    with open(path, "rb") as f:
        f.seek(offset)
        data = f.read(nbytes)
    if len(data) != nbytes:
        raise RuntimeError(f"Short read from {path}: expected {nbytes}, got {len(data)}")
    return data
References ie_gemv_rowwise_f32_kernel().
Referenced by main().
_reconstruct()
bytes dedup_verify_int4._reconstruct (bytes default_bytes, bytes mask, bytes exc) protected
Reconstruct a target blob from (default_bytes, mask, exc).
Mask semantics:
  - 1 bit per byte in default_bytes
  - if bit is 1 at byte index i, output byte at i comes from exc stream (in ascending i order)
Definition at line 97 of file dedup_verify_int4.py.
def _reconstruct(default_bytes: bytes, mask: bytes, exc: bytes) -> bytes:
    """
    Reconstruct a target blob from (default_bytes, mask, exc).
    Mask semantics:
      - 1 bit per byte in default_bytes
      - if bit is 1 at byte index i, output byte at i comes from exc stream (in ascending i order)
    """
    n = len(default_bytes)
    if len(mask) != _mask_nbytes(n):
        raise ValueError("mask length mismatch")
    out = bytearray(default_bytes)
    exc_i = 0
    byte_i = 0
    for m in mask:
        if m == 0:
            byte_i += 8
            continue
        for bit in range(8):
            idx = byte_i + bit
            if idx >= n:
                break
            if (m >> bit) & 1:
                out[idx] = exc[exc_i]
                exc_i += 1
        byte_i += 8
    if exc_i != len(exc):
        raise RuntimeError(f"exception stream not fully consumed: used {exc_i}, have {len(exc)}")
    return bytes(out)
References _mask_nbytes(), and ie_gemv_rowwise_f32_kernel().
Referenced by main().
main()
int dedup_verify_int4.main (void)
Program entry point.
Definition at line 132 of file dedup_verify_int4.py.
def main() -> int:
    """Program entry point."""
    ap = argparse.ArgumentParser()
    ap.add_argument("--model-dir", required=True, help="Model directory containing weights bin")
    ap.add_argument("--tensor-map", required=True, help="Tensor map JSON file")
    ap.add_argument("--spec", required=True, help="Dedup spec JSON file")
    args = ap.parse_args()
    tensor_map_obj = _load_json(args.tensor_map)
    weights_bin_rel, tensors = _parse_tensor_map(tensor_map_obj)
    weights_bin_path = os.path.join(args.model_dir, weights_bin_rel)
    spec = _load_json(args.spec)
    if not isinstance(spec, dict):
        raise ValueError("spec must be a JSON object")
    if spec.get("magic") != "DUDP" or int(spec.get("version", 0)) != 1:
        raise ValueError("unsupported spec magic/version")
    files = spec.get("files", {})
    defaults_path = os.path.join(os.path.dirname(args.spec), files["defaults"])
    masks_path = os.path.join(os.path.dirname(args.spec), files["masks"])
    exc_path = os.path.join(os.path.dirname(args.spec), files["exceptions"])
    defaults = _read_all(defaults_path)
    masks = _read_all(masks_path)
    exc = _read_all(exc_path)
    groups = spec.get("groups")
    if not isinstance(groups, list):
        raise ValueError("spec.groups must be a list")
    checked = 0
    for g in groups:
        d = g["default"]
        default_index = int(d["tensor_index"])
        default_nbytes = int(d["nbytes"])
        default_off = int(d["default_off"])
        if default_index not in tensors:
            raise KeyError(f"default tensor_index {default_index} missing from tensor map")
        if tensors[default_index].nbytes != default_nbytes:
            raise ValueError("default nbytes mismatch vs tensor map")
        default_bytes = defaults[default_off : default_off + default_nbytes]
        if len(default_bytes) != default_nbytes:
            raise RuntimeError("default slice out of bounds in defaults.bin")
        for t in g["targets"]:
            tidx = int(t["tensor_index"])
            nbytes = int(t["nbytes"])
            mask_off = int(t["mask_off"])
            mask_n = int(t["mask_nbytes"])
            exc_off = int(t["exc_off"])
            exc_n = int(t["exc_nbytes"])
            if tidx not in tensors:
                raise KeyError(f"target tensor_index {tidx} missing from tensor map")
            if tensors[tidx].nbytes != nbytes:
                raise ValueError(f"target nbytes mismatch vs tensor map for {tidx}")
            if nbytes != default_nbytes:
                raise ValueError("target nbytes mismatch vs default nbytes")
            mask_bytes = masks[mask_off : mask_off + mask_n]
            if len(mask_bytes) != mask_n:
                raise RuntimeError("mask slice out of bounds in masks.bin")
            exc_bytes = exc[exc_off : exc_off + exc_n]
            if len(exc_bytes) != exc_n:
                raise RuntimeError("exception slice out of bounds in exceptions.bin")
            rec = _reconstruct(default_bytes, mask_bytes, exc_bytes)
            orig = _read_slice(weights_bin_path, tensors[tidx].offset, nbytes)
            if rec != orig:
                raise RuntimeError(f"mismatch for tensor_index={tidx} name={tensors[tidx].name}")
            checked += 1
    print(f"OK: verified {checked} tensors losslessly")
    return 0
References _load_json(), _parse_tensor_map(), _read_all(), _read_slice(), _reconstruct(), ie_gemv_rowwise_f32_kernel(), and main().
Referenced by main().