Inference Engine (Clocher): engine/src/opt/numa_probe.c File Reference
numa_probe.c File Reference
#include "ie_numa.h"
#include <stdio.h>
#include <stdlib.h>
Macros
#define _POSIX_C_SOURCE 200809L
Functions
static int parse_range_list (const char *s)
Parse a NUMA node range-list and return (max_id + 1).
int ie_numa_detect_nodes (void)
Detect the number of NUMA nodes.
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 17 of file numa_probe.c.
Function Documentation
ie_numa_detect_nodes()
int ie_numa_detect_nodes (void)
Detect the number of NUMA nodes.
Detect the number of NUMA nodes available on the system.
On Linux, reads /sys/devices/system/node/online and parses it. If the file cannot be opened, read, or yields no usable data, returns 1.
On non-Linux systems, always returns 1.
Returns
Detected NUMA node count (>= 1).
Definition at line 85 of file numa_probe.c.
{
 #ifdef __linux__
   FILE *f = fopen("/sys/devices/system/node/online", "r");
   if (!f) return 1;
   char buf[256] = {0};
   size_t n = fread(buf, 1, sizeof(buf) - 1, f);
   fclose(f);
   if (n == 0) return 1;
   buf[n] = '\0';
   int nodes = parse_range_list(buf);
   return (nodes > 0) ? nodes : 1;
 #else
   return 1;
 #endif
 }
References parse_range_list().
Referenced by ie_numa_policy_init().
parse_range_list()
static int parse_range_list (const char * s) static
Parse a NUMA node range-list and return (max_id + 1).
The input is expected to be a NUL-terminated ASCII string containing one or more comma-separated ranges. Each range is either a single integer N or a closed interval A-B where A and B are non-negative integers and A <= B. Examples:
"0" -> returns 1
"0-1" -> returns 2
"0-3,8-9" -> returns 10 (since max id is 9)
Parsing notes:
If the string cannot be fully parsed, the function returns (max_id + 1) for any successfully parsed ranges encountered before the error.
If no valid range is found at all, the function returns 1.
Parameters
s NUL-terminated range-list string to parse (non-NULL).
Returns
(max_id + 1) where max_id is the largest parsed id; at least 1.
Definition at line 44 of file numa_probe.c.
{
   int max_id = 0;
   const char *p = s;
   while (*p) {
     int a = 0;
     int b = 0;
     char *end = NULL;
     a = (int)strtol(p, &end, 10);
     if (end == p) break;
     p = end;
     if (*p == '-') {
       ++p;
       b = (int)strtol(p, &end, 10);
       if (end == p) break;
       p = end;
     } else {
       b = a;
     }
     if (b > max_id) max_id = b;
     if (*p == ',') ++p;
   }
   return max_id + 1;
 }
Referenced by ie_numa_detect_nodes().