Inference Engine (Clocher): engine/src/opt/numa_policy.c File Reference
numa_policy.c File Reference
NUMA-aware policy initialization and helper decisions.
#include "numa_policy.h"
#include "ie_numa.h"
#include "ie_topology.h"
#include "util_logging.h"
#include <ctype.h>
#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
Macros
#define _POSIX_C_SOURCE 200809L
#define IE_LOG_WARN(...) do { fprintf(stderr, "[warn] " __VA_ARGS__); fputc('\n', stderr); } while (0)
Functions
static int str_ieq (const char *a, const char *b)
Case-insensitive ASCII equality helper.
static int env_flag_get (const char *name, int default_value)
Read a boolean-like environment variable.
static int env_int_get (const char *name, int def, int min_v, int max_v)
Read an integer environment variable with clamping.
static size_t env_sizet_get (const char *name, size_t def, size_t min_v, size_t max_v)
Read a size_t environment variable with clamping.
int ie_numa_policy_init (ie_numa_policy_t *out, const ie_topology_t *topo)
Initialize a NUMA policy snapshot.
bool ie_numa_policy_should_replicate_hot (const ie_numa_policy_t *p, size_t bytes)
Decide whether a blob should be replicated per socket.
int ie_numa_policy_replica_count (const ie_numa_policy_t *p)
Compute how many replicas to create under this policy.
Detailed Description
NUMA-aware policy initialization and helper decisions.
This module provides a small policy object used by NUMA-aware subsystems. It:
obtains socket count via ie_topology when available,
obtains NUMA node count via sysfs-based detection (no libnuma),
reads env knobs to decide whether NUMA is enabled and whether to replicate hot blobs per socket,
provides helper decisions used by the loader and hot replication logic.
Environment variables:
IE_NUMA_ENABLE (default: 1)
IE_NUMA_REPLICATE_HOT (default: 1)
IE_NUMA_MAX_REPLICAS (default: detected_sockets, clamped to [1, 64])
IE_NUMA_HOT_MIN_BYTES (default: 33554432 = 32 MiB)
Definition in file numa_policy.c.
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 21 of file numa_policy.c.
IE_LOG_WARN
#define IE_LOG_WARN (...) do { fprintf(stderr, "[warn] " __VA_ARGS__); fputc('\n', stderr); } while (0)
Definition at line 37 of file numa_policy.c.
Function Documentation
env_flag_get()
static int env_flag_get (const char * name, int default_value) static
Read a boolean-like environment variable.
Accepted false values (case-insensitive): "0", "false", "no", "off". Any other non-empty value is treated as true.
Parameters
name Environment variable name.
default_value Value used when the variable is unset/empty.
Returns
0 or 1.
Definition at line 72 of file numa_policy.c.
{
  const char *v = getenv(name);
  if (!v || !*v) return default_value;
  if (str_ieq(v, "0") || str_ieq(v, "false") || str_ieq(v, "no") || str_ieq(v, "off")) return 0;
  return 1;
}
References ie_gemv_rowwise_f32_kernel(), and str_ieq().
Referenced by ie_numa_policy_init().
env_int_get()
static int env_int_get (const char * name, int def, int min_v, int max_v) static
Read an integer environment variable with clamping.
If the variable is unset/empty or unparsable, def is returned. Otherwise, the parsed value is clamped to [min_v, max_v].
Parameters
name Env var name.
def Default if unset or unparsable.
min_v Minimum allowed value.
max_v Maximum allowed value.
Returns
Clamped integer value.
Definition at line 93 of file numa_policy.c.
{
  const char *v = getenv(name);
  if (!v || !*v) return def;
  char *end = NULL;
  long x = strtol(v, &end, 10);
  if (end == v) return def;
  if (x < (long)min_v) x = (long)min_v;
  if (x > (long)max_v) x = (long)max_v;
  return (int)x;
}
References ie_gemv_rowwise_f32_kernel().
Referenced by ie_numa_policy_init().
env_sizet_get()
static size_t env_sizet_get (const char * name, size_t def, size_t min_v, size_t max_v) static
Read a size_t environment variable with clamping.
If the variable is unset/empty or unparsable, def is returned. Otherwise, the parsed value is clamped to [min_v, max_v].
Parameters
name Env var name.
def Default if unset or unparsable.
min_v Minimum allowed value.
max_v Maximum allowed value.
Returns
Clamped size_t value.
Definition at line 119 of file numa_policy.c.
{
  const char *v = getenv(name);
  if (!v || !*v) return def;
  char *end = NULL;
  unsigned long long x = strtoull(v, &end, 10);
  if (end == v) return def;
  if (x < (unsigned long long)min_v) x = (unsigned long long)min_v;
  if (x > (unsigned long long)max_v) x = (unsigned long long)max_v;
  return (size_t)x;
}
References ie_gemv_rowwise_f32_kernel().
Referenced by ie_numa_policy_init().
ie_numa_policy_init()
int ie_numa_policy_init (ie_numa_policy_t * out, const ie_topology_t * topo)
Initialize a NUMA policy snapshot.
Parameters
out Output policy (non-NULL).
topo Optional topology handle (may be NULL).
Returns
0 on success, negative errno-like value on failure.
Definition at line 136 of file numa_policy.c.
{
  if (!out) return -EINVAL;
  memset(out, 0, sizeof(*out));
  int sockets = 1;
  if (topo) {
    sockets = ie_topology_sockets(topo);
    if (sockets <= 0) sockets = 1;
  }
  out->detected_nodes = ie_numa_detect_nodes();
  if (out->detected_nodes <= 0) out->detected_nodes = 1;
  out->detected_sockets = sockets;
  out->enable_numa   = (env_flag_get("IE_NUMA_ENABLE", 1) != 0);
  out->replicate_hot = (env_flag_get("IE_NUMA_REPLICATE_HOT", 1) != 0);
  out->max_replicas = sockets;
  if (out->max_replicas < 1) out->max_replicas = 1;
  if (out->max_replicas > 64) out->max_replicas = 64;
  out->max_replicas = env_int_get("IE_NUMA_MAX_REPLICAS", out->max_replicas, 1, 64);
  out->hot_min_bytes = env_sizet_get("IE_NUMA_HOT_MIN_BYTES",
                                     (size_t)33554432u,
                                     (size_t)0u,
                                     (size_t)1099511627776ull);
  return 0;
}
References env_flag_get(), env_int_get(), env_sizet_get(), ie_gemv_rowwise_f32_kernel(), ie_numa_detect_nodes(), and ie_topology_sockets().
ie_numa_policy_replica_count()
int ie_numa_policy_replica_count (const ie_numa_policy_t * p)
Compute how many replicas to create under this policy.
Parameters
p Policy (non-NULL).
Returns
Replica count (>= 1).
Definition at line 176 of file numa_policy.c.
{
  if (!p) return 1;
  int s = (p->detected_sockets > 0) ? p->detected_sockets : 1;
  int m = (p->max_replicas > 0) ? p->max_replicas : 1;
  return (s < m) ? s : m;
}
References ie_gemv_rowwise_f32_kernel().
ie_numa_policy_should_replicate_hot()
bool ie_numa_policy_should_replicate_hot (const ie_numa_policy_t * p, size_t bytes)
Decide whether a blob should be replicated per socket.
Parameters
p Policy (non-NULL).
bytes Blob size in bytes.
Returns
true if replication should happen.
Definition at line 167 of file numa_policy.c.
{
  if (!p) return false;
  if (!p->enable_numa) return false;
  if (!p->replicate_hot) return false;
  if (p->detected_sockets <= 1) return false;
  if (bytes < p->hot_min_bytes) return false;
  return true;
}
References ie_gemv_rowwise_f32_kernel().
str_ieq()
static int str_ieq (const char * a, const char * b) static
Case-insensitive ASCII equality helper.
Parameters
a NUL-terminated string (may be NULL).
b NUL-terminated string (may be NULL).
Returns
1 if equal (case-insensitive), otherwise 0.
Definition at line 51 of file numa_policy.c.
{
  if (!a || !b) return 0;
  while (*a && *b) {
    if (tolower((unsigned char)*a) != tolower((unsigned char)*b)) return 0;
    ++a;
    ++b;
  }
  return (*a == '\0' && *b == '\0');
}
References ie_gemv_rowwise_f32_kernel().
Referenced by env_flag_get().