Inference Engine (Clocher): engine/include/numa_policy.h File Reference
numa_policy.h File Reference
#include <stdbool.h>
#include <stddef.h>
Data Structures
struct ie_numa_policy_t
Policy/config snapshot for NUMA-aware behavior.
Typedefs
typedef struct ie_topology ie_topology_t
typedef struct ie_numa_policy_t ie_numa_policy_t
Functions
int ie_numa_policy_init (ie_numa_policy_t *out, const ie_topology_t *topo)
Initialize a NUMA policy snapshot from topology detection and env knobs.
bool ie_numa_policy_should_replicate_hot (const ie_numa_policy_t *p, size_t bytes)
Decide if a blob of bytes should be replicated per socket.
int ie_numa_policy_replica_count (const ie_numa_policy_t *p)
Compute the replica count to build under this policy.
Typedef Documentation
ie_numa_policy_t
typedef struct ie_numa_policy_t ie_numa_policy_t
ie_topology_t
typedef struct ie_topology ie_topology_t
Definition at line 1 of file numa_policy.h.
Function Documentation
ie_numa_policy_init()
int ie_numa_policy_init (ie_numa_policy_t * out, const ie_topology_t * topo)
Initialize a NUMA policy snapshot from topology detection and env knobs.
This function populates detected topology facts and reads the environment variables listed in the module documentation. It does not allocate memory.
If topo is NULL (or provides invalid socket information), sockets default to 1. NUMA nodes are detected via ie_numa_detect_nodes() (sysfs-based on Linux), defaulting to 1 on failure.
Parameters
out Output policy object (non-NULL).
topo Optional topology handle (may be NULL).
Returns
0 on success, negative errno-like value on failure (e.g., -EINVAL).
This function is meant to be called during startup to capture a stable policy snapshot. It does not allocate memory and has no side effects beyond reading environment variables.
Socket count is sourced from topo (if provided), using ie_topology_sockets(). Node count is sourced from ie_numa_detect_nodes() (sysfs-based on Linux).
Parameters
out Output policy object (non-NULL).
topo Optional topology handle (may be NULL).
Returns
0 on success, negative errno-like value on failure.
Definition at line 152 of file numa_policy.c.
{
   if (!out) return -EINVAL;
   memset(out, 0, sizeof(*out));
   int sockets = 1;
   if (topo) {
     sockets = ie_topology_sockets(topo);
     if (sockets <= 0) sockets = 1;
   }
   out->detected_nodes = ie_numa_detect_nodes();
   if (out->detected_nodes <= 0) out->detected_nodes = 1;
   out->detected_sockets = sockets;
   out->enable_numa   = (env_flag_get("IE_NUMA_ENABLE", 1) != 0);
   out->replicate_hot = (env_flag_get("IE_NUMA_REPLICATE_HOT", 1) != 0);
   out->max_replicas = sockets;
   if (out->max_replicas < 1) out->max_replicas = 1;
   if (out->max_replicas > 64) out->max_replicas = 64;
   out->max_replicas = env_int_get("IE_NUMA_MAX_REPLICAS", out->max_replicas, 1, 64);
   /* Default: 32 MiB, clamped to 1 TiB. */
   out->hot_min_bytes = env_sizet_get("IE_NUMA_HOT_MIN_BYTES",
                                      (size_t)33554432u,
                                      (size_t)0u,
                                      (size_t)1099511627776ull);
   return 0;
 }
References ie_numa_policy_t::detected_nodes, ie_numa_policy_t::detected_sockets, ie_numa_policy_t::enable_numa, env_flag_get(), env_int_get(), env_sizet_get(), ie_numa_policy_t::hot_min_bytes, ie_numa_detect_nodes(), ie_topology_sockets(), ie_numa_policy_t::max_replicas, and ie_numa_policy_t::replicate_hot.
ie_numa_policy_replica_count()
int ie_numa_policy_replica_count (const ie_numa_policy_t * p)
Compute the replica count to build under this policy.
Typically this returns min(detected_sockets, max_replicas), clamped to at least 1.
Parameters
p Policy object (non-NULL).
Returns
Number of replicas to create (>= 1).
This returns min(detected_sockets, max_replicas), clamped to at least 1. Callers can use this as the number of per-socket replicas to allocate.
Parameters
p Policy object (non-NULL).
Returns
Number of replicas to create (>= 1).
Definition at line 215 of file numa_policy.c.
{
   if (!p) return 1;
   int s = (p->detected_sockets > 0) ? p->detected_sockets : 1;
   int m = (p->max_replicas > 0) ? p->max_replicas : 1;
   return (s < m) ? s : m;
 }
References ie_numa_policy_t::detected_sockets, and ie_numa_policy_t::max_replicas.
ie_numa_policy_should_replicate_hot()
bool ie_numa_policy_should_replicate_hot (const ie_numa_policy_t * p, size_t bytes)
Decide if a blob of bytes should be replicated per socket.
The decision is based on:
enable_numa flag,
replicate_hot flag,
detected_sockets > 1,
bytes >= hot_min_bytes.
Parameters
p Policy object (non-NULL).
bytes Blob size in bytes.
Returns
true if replication should happen, false otherwise.
Replication is intended for large/hot blobs where remote NUMA access would otherwise dominate runtime. This function only provides a policy decision; actual replication and placement are handled elsewhere.
Parameters
p Policy object (non-NULL).
bytes Blob size in bytes.
Returns
true if replication should happen, false otherwise.
Definition at line 196 of file numa_policy.c.
{
   if (!p) return false;
   if (!p->enable_numa) return false;
   if (!p->replicate_hot) return false;
   if (p->detected_sockets <= 1) return false;
   if (bytes < p->hot_min_bytes) return false;
   return true;
 }
References ie_numa_policy_t::detected_sockets, ie_numa_policy_t::enable_numa, and ie_numa_policy_t::replicate_hot.