Inference Engine (Clocher): engine/include/patch_list.h File Reference
patch_list.h File Reference
Patch-list representation and fast application for dedup reconstruction.
#include <stdint.h>
#include <stddef.h>
Data Structures
struct ie_patch_list_s
Macros
#define IE_PATCH_LIST_MAGIC 0x54534C50u
Magic value for patch list headers: 'PLST'.
#define IE_PATCH_LIST_VERSION 1u
Patch list version supported by this module.
Typedefs
typedef struct ie_patch_list_s ie_patch_list_t
Functions
size_t ie_patch_list_bytes (uint64_t nitems)
Compute the required buffer size (in bytes) to store a patch list.
int ie_patch_list_view_init (ie_patch_list_t *out, const void *buf, size_t buf_len)
Initialize a patch list view from a serialized buffer.
int ie_patch_list_serialize (void *dst, size_t dst_len, uint64_t nbytes, uint64_t nitems, const uint32_t *idx, const uint8_t *val)
Serialize a patch list into a caller-provided buffer.
int ie_patch_list_apply_inplace (uint8_t *dst, uint64_t nbytes, const ie_patch_list_t *pl)
Apply a patch list to an existing tensor buffer in-place.
int ie_patch_list_from_mask_exceptions (uint64_t nbytes, const uint8_t *mask, const uint8_t *exceptions, uint32_t *idx_out, uint8_t *val_out, uint64_t *out_nitems)
Convert a bitmask + exception stream into a patch list (indices + values).
Detailed Description
Patch-list representation and fast application for dedup reconstruction.
This module provides an alternative to bitmask-based exceptions: instead of storing a 1-bit-per-byte mask, it stores a compact list of byte indices that differ from the default plus their corresponding bytes.
Use cases:
Extremely sparse exceptions (low exception density).
Faster iteration than scanning a full mask for large tensors when popcount(mask) is small.
Contract (lossless, byte-oriented):
Indices refer to byte offsets in the tensor blob.
Values are the exact original bytes at those offsets.
Applying the patch list to a default blob produces the exact target blob.
Storage format (binary, little-endian):
struct ie_patch_list_hdr { uint32_t magic; // 'PLST' uint32_t version; // 1 uint64_t nbytes; // tensor byte length uint64_t nitems; // number of patched bytes // followed by: // uint32_t idx[nitems]; (byte indices, strictly increasing) // uint8_t val[nitems]; (patched byte values) };
Notes:
idx is uint32_t to reduce size. If tensors exceed 4 GiB, switch to uint64_t.
Strictly increasing indices allow validation and optional SIMD-friendly streaming writes.
Definition in file patch_list.h.
Macro Definition Documentation
IE_PATCH_LIST_MAGIC
#define IE_PATCH_LIST_MAGIC 0x54534C50u
Magic value for patch list headers: 'PLST'.
Definition at line 48 of file patch_list.h.
IE_PATCH_LIST_VERSION
#define IE_PATCH_LIST_VERSION 1u
Patch list version supported by this module.
Definition at line 51 of file patch_list.h.
Typedef Documentation
ie_patch_list_t
typedef struct ie_patch_list_s ie_patch_list_t
Function Documentation
ie_patch_list_apply_inplace()
int ie_patch_list_apply_inplace (uint8_t * dst, uint64_t nbytes, const ie_patch_list_t * pl)
Apply a patch list to an existing tensor buffer in-place.
Typical usage: memcpy(dst, default_bytes, nbytes); ie_patch_list_apply_inplace(dst, nbytes, &pl);
Parameters
dst Destination buffer to modify (must have at least nbytes bytes).
nbytes Destination buffer size in bytes.
pl Patch list view.
Returns
0 on success, non-zero on error (bounds, invalid indices).
Definition at line 158 of file patch_list.c.
{
  if (!dst || !pl) return -1;
  if (pl->nbytes != nbytes) return -2;
  if (pl->nitems == 0) return 0;
  if (!pl->idx || !pl->val) return -3;
  for (uint64_t i = 0; i < pl->nitems; ++i) {
    const uint32_t idx = pl->idx[i];
    if ((uint64_t)idx >= nbytes) return -4;
    dst[idx] = pl->val[i];
  }
  return 0;
}
ie_patch_list_bytes()
size_t ie_patch_list_bytes (uint64_t nitems)
Compute the required buffer size (in bytes) to store a patch list.
Parameters
nitems Number of patched bytes.
Returns
Total bytes for header + indices + values.
Definition at line 77 of file patch_list.c.
{
  const size_t hdr = sizeof(ie_patch_list_hdr_t);
  const size_t idx = (size_t)(nitems * (uint64_t)sizeof(uint32_t));
  const size_t val = (size_t)(nitems * (uint64_t)sizeof(uint8_t));
  return hdr + idx + val;
}
Referenced by ie_patch_list_serialize(), and ie_patch_list_view_init().
ie_patch_list_from_mask_exceptions()
int ie_patch_list_from_mask_exceptions (uint64_t nbytes, const uint8_t * mask, const uint8_t * exceptions, uint32_t * idx_out, uint8_t * val_out, uint64_t * out_nitems)
Convert a bitmask + exception stream into a patch list (indices + values).
This is useful for hybrid formats:
Authoring uses mask+exceptions (cheap to compute).
Runtime uses patch list when exception density is low.
Mask semantics:
1 bit per byte (LSB-first within each mask byte).
exceptions stream provides the patched bytes in ascending byte index order.
Output:
idx_out receives indices (uint32_t per item).
val_out receives values (uint8_t per item).
The caller must allocate idx_out/val_out to hold exactly popcount(mask) items.
Parameters
nbytes Tensor byte length.
mask Pointer to mask bytes (ceil(nbytes/8)).
exceptions Pointer to exception bytes (popcount(mask)).
idx_out Output indices array.
val_out Output values array.
out_nitems Output number of items produced.
Returns
0 on success, non-zero on error.
Definition at line 173 of file patch_list.c.
{
  if (out_nitems) *out_nitems = 0;
  if (!mask || (!exceptions && nbytes != 0) || !idx_out || !val_out || !out_nitems) return -1;
  const uint64_t mask_n = (nbytes + 7u) / 8u;
  uint64_t exc_i = 0;
  uint64_t out_i = 0;
  uint64_t byte_base = 0;
  for (uint64_t mi = 0; mi < mask_n; ++mi) {
    const uint8_t m = mask[mi];
    if (m == 0) {
      byte_base += 8;
      continue;
    }
    for (uint32_t bit = 0; bit < 8; ++bit) {
      const uint64_t idx64 = byte_base + (uint64_t)bit;
      if (idx64 >= nbytes) break;
      if ((m >> bit) & 1u) {
        idx_out[out_i] = (uint32_t)idx64;
        val_out[out_i] = exceptions[exc_i];
        out_i++;
        exc_i++;
      }
    }
    byte_base += 8;
  }
  *out_nitems = out_i;
  return 0;
}
References ie_gemv_rowwise_f32_kernel().
ie_patch_list_serialize()
int ie_patch_list_serialize (void * dst, size_t dst_len, uint64_t nbytes, uint64_t nitems, const uint32_t * idx, const uint8_t * val)
Serialize a patch list into a caller-provided buffer.
The caller provides idx and val arrays. Indices must be strictly increasing and each must be < nbytes.
Parameters
dst Destination buffer.
dst_len Destination buffer capacity.
nbytes Tensor byte length.
nitems Number of patch items.
idx Byte indices array (strictly increasing).
val Byte values array.
Returns
0 on success, non-zero on error (including insufficient dst_len).
Definition at line 121 of file patch_list.c.
{
  if (!dst || (!idx && nitems) || (!val && nitems)) return -1;
  const size_t need = ie_patch_list_bytes(nitems);
  if (dst_len < need) return -2;
  /* Validate input indices. */
  uint32_t prev = 0;
  for (uint64_t i = 0; i < nitems; ++i) {
    const uint32_t cur = idx[i];
    if ((uint64_t)cur >= nbytes) return -3;
    if (i > 0 && cur <= prev) return -4;
    prev = cur;
  }
  uint8_t* p = (uint8_t*)dst;
  ie_store_u32(p + 0, IE_PATCH_LIST_MAGIC);
  ie_store_u32(p + 4, IE_PATCH_LIST_VERSION);
  ie_store_u64(p + 8, nbytes);
  ie_store_u64(p + 16, nitems);
  uint8_t* idxp = p + sizeof(ie_patch_list_hdr_t);
  uint8_t* valp = idxp + (size_t)(nitems * (uint64_t)sizeof(uint32_t));
  memcpy(idxp, idx, (size_t)(nitems * (uint64_t)sizeof(uint32_t)));
  memcpy(valp, val, (size_t)(nitems * (uint64_t)sizeof(uint8_t)));
  return 0;
}
References ie_patch_list_bytes(), IE_PATCH_LIST_MAGIC, IE_PATCH_LIST_VERSION, ie_store_u32(), and ie_store_u64().
ie_patch_list_view_init()
int ie_patch_list_view_init (ie_patch_list_t * out, const void * buf, size_t buf_len)
Initialize a patch list view from a serialized buffer.
The buffer must begin with an ie_patch_list_hdr as described in the file comment. This function validates the header and sets the ie_patch_list_t pointers.
Parameters
out Output patch list view.
buf Serialized buffer.
buf_len Buffer length in bytes.
Returns
0 on success, non-zero on failure.
Definition at line 84 of file patch_list.c.
{
  if (!out || !buf) return -1;
  if (buf_len < sizeof(ie_patch_list_hdr_t)) return -2;
  const uint8_t* p = (const uint8_t*)buf;
  const uint32_t magic = ie_load_u32(p + 0);
  const uint32_t version = ie_load_u32(p + 4);
  const uint64_t nbytes = ie_load_u64(p + 8);
  const uint64_t nitems = ie_load_u64(p + 16);
  if (magic != IE_PATCH_LIST_MAGIC) return -3;
  if (version != IE_PATCH_LIST_VERSION) return -4;
  const size_t need = ie_patch_list_bytes(nitems);
  if (buf_len < need) return -5;
  const uint8_t* idxp = p + sizeof(ie_patch_list_hdr_t);
  const uint8_t* valp = idxp + (size_t)(nitems * (uint64_t)sizeof(uint32_t));
  out->nbytes = nbytes;
  out->nitems = nitems;
  out->idx = (const uint32_t*)idxp;
  out->val = (const uint8_t*)valp;
  /* Validate strict monotonicity and bounds. */
  uint32_t prev = 0;
  for (uint64_t i = 0; i < nitems; ++i) {
    const uint32_t cur = out->idx[i];
    if ((uint64_t)cur >= nbytes) return -6;
    if (i > 0 && cur <= prev) return -7;
    prev = cur;
  }
  return 0;
}
References ie_load_u32(), ie_load_u64(), ie_patch_list_bytes(), IE_PATCH_LIST_MAGIC, and IE_PATCH_LIST_VERSION.