Inference Engine (Clocher): engine/src/opt/replicate_hot.c File Reference
replicate_hot.c File Reference
Replication of hot weight blobs per socket using first-touch placement.
#include <errno.h>
#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "ie_topology.h"
#include "util_logging.h"
Data Structures
struct ie_hot_replica_t
A single per-socket replica.
struct ie_hot_replicas_t
Container of all per-socket replicas.
Macros
#define _POSIX_C_SOURCE 200809L
#define IE_LIKELY(x) __builtin_expect(!!(x), 1)
#define IE_UNLIKELY(x) __builtin_expect(!!(x), 0)
#define IE_LOG_INFO(...) do { fprintf(stderr, "[info] " __VA_ARGS__); fputc('\n', stderr); } while (0)
#define IE_LOG_WARN(...) do { fprintf(stderr, "[warn] " __VA_ARGS__); fputc('\n', stderr); } while (0)
#define IE_LOG_ERROR(...) do { fprintf(stderr, "[error] " __VA_ARGS__); fputc('\n', stderr); } while (0)
Typedefs
typedef struct ie_hot_replica_t ie_hot_replica_t
typedef struct ie_hot_replicas_t ie_hot_replicas_t
typedef int(* ie_hot_replica_fill_fn) (int socket_id, void *dst, size_t dst_size, void *user)
Callback type for fill-mode replica construction.
Functions
static void first_touch_write (void *p, size_t sz)
First-touch a writable buffer to bias NUMA page placement.
static void advise_willneed (void *p, size_t sz)
Best-effort hint to the OS that the buffer will be needed soon.
static void advise_sequential (void *p, size_t sz)
Best-effort hint to the OS that sequential access is expected.
static void * alloc_replica_first_touch (size_t blob_size)
Allocate a replica buffer and establish locality via first-touch.
static void free_replicas_internal (ie_hot_replicas_t *reps)
Free all allocations owned by a replica set (internal helper).
int ie_hot_replicate_build (const ie_topology_t *topo, int n_sockets, const void *blob, size_t blob_size, ie_hot_replicas_t **out)
Create per-socket replicas of blob using first-touch placement (copy mode).
int ie_hot_replicate_build_fill (const ie_topology_t *topo, int n_sockets, size_t replica_size, ie_hot_replica_fill_fn fill, void *user, ie_hot_replicas_t **out)
Create per-socket replicas using a caller-provided fill callback (fill mode).
void ie_hot_replicas_free (ie_hot_replicas_t *reps)
Free replicas previously built by ie_hot_replicate_build() or ie_hot_replicate_build_fill().
void * ie_hot_replica_for_socket (const ie_hot_replicas_t *reps, int socket_id, size_t *size_out)
Retrieve the replica pointer for a socket.
int ie_hot_replica_memcpy (ie_hot_replicas_t *reps, int socket_id, const void *src)
Convenience: memcpy() into a given socket’s replica.
Detailed Description
Replication of hot weight blobs per socket using first-touch placement.
This module implements a small utility to create per-socket replicas of a contiguous "hot" blob so that the inference kernel can read local memory when threads are socket-pinned.
Step-3 (Runtime reconstruction path) integration:
This unit now supports two build modes: 1) Copy mode: replicate an existing source blob via memcpy(). 2) Fill mode: allocate per-socket memory, first-touch it, then let a caller-provided callback populate the replica in-place.
Fill mode exists to avoid a common NUMA pitfall:
If you reconstruct/assemble the hot blob once on socket 0 and then memcpy it to other sockets, you pay cross-socket bandwidth and potentially pull pages into the wrong node before first-touch.
The module depends on ie_topology.h for socket enumeration and thread binding. It does not define any thread-binding symbol by itself; it calls ie_topology_bind_thread_to_socket() from topology.c.
Definition in file replicate_hot.c.
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 29 of file replicate_hot.c.
IE_LIKELY
#define IE_LIKELY (x) __builtin_expect(!!(x), 1)
Definition at line 47 of file replicate_hot.c.
IE_LOG_ERROR
#define IE_LOG_ERROR (...) do { fprintf(stderr, "[error] " __VA_ARGS__); fputc('\n', stderr); } while (0)
Definition at line 61 of file replicate_hot.c.
IE_LOG_INFO
#define IE_LOG_INFO (...) do { fprintf(stderr, "[info] " __VA_ARGS__); fputc('\n', stderr); } while (0)
Definition at line 55 of file replicate_hot.c.
IE_LOG_WARN
#define IE_LOG_WARN (...) do { fprintf(stderr, "[warn] " __VA_ARGS__); fputc('\n', stderr); } while (0)
Definition at line 58 of file replicate_hot.c.
IE_UNLIKELY
#define IE_UNLIKELY (x) __builtin_expect(!!(x), 0)
Definition at line 50 of file replicate_hot.c.
Typedef Documentation
ie_hot_replica_fill_fn
ie_hot_replica_fill_fn
Callback type for fill-mode replica construction.
The callback is invoked once per socket after:
the current thread has been (best-effort) bound to that socket,
memory has been allocated and first-touched for locality.
The callback must fully initialize the provided destination buffer.
Parameters
socket_id Socket id being built.
dst Destination buffer for the replica.
dst_size Destination buffer size in bytes.
user User context pointer provided to the builder.
Returns
0 on success, negative errno-like on failure.
Definition at line 104 of file replicate_hot.c.
ie_hot_replica_t
typedef struct ie_hot_replica_t ie_hot_replica_t
ie_hot_replicas_t
typedef struct ie_hot_replicas_t ie_hot_replicas_t
Function Documentation
advise_sequential()
static void advise_sequential (void * p, size_t sz) static
Best-effort hint to the OS that sequential access is expected.
This can help some kernels choose better readahead / paging heuristics.
Parameters
p Pointer to memory.
sz Size in bytes.
Definition at line 153 of file replicate_hot.c.
{
   (void)p; (void)sz;
 #if defined(POSIX_MADV_SEQUENTIAL)
   (void)posix_madvise(p, sz, POSIX_MADV_SEQUENTIAL);
 #elif defined(__linux__) && defined(MADV_SEQUENTIAL)
   (void)madvise(p, sz, MADV_SEQUENTIAL);
 #else
   (void)p; (void)sz;
 #endif
 }
Referenced by ie_hot_replicate_build(), and ie_hot_replicate_build_fill().
advise_willneed()
static void advise_willneed (void * p, size_t sz) static
Best-effort hint to the OS that the buffer will be needed soon.
Uses POSIX readahead/madvise when available. If the platform does not expose a declaration for posix_madvise (or the specific advice constant), this function degrades to a no-op.
Parameters
p Pointer to memory (non-NULL).
sz Size in bytes.
Definition at line 134 of file replicate_hot.c.
{
   (void)p; (void)sz;
 #if defined(POSIX_MADV_WILLNEED)
   (void)posix_madvise(p, sz, POSIX_MADV_WILLNEED);
 #elif defined(__linux__) && defined(MADV_WILLNEED)
   (void)madvise(p, sz, MADV_WILLNEED);
 #else
   (void)p; (void)sz;
 #endif
 }
Referenced by ie_hot_replicate_build(), and ie_hot_replicate_build_fill().
alloc_replica_first_touch()
static void* alloc_replica_first_touch (size_t blob_size) static
Allocate a replica buffer and establish locality via first-touch.
Parameters
blob_size Size in bytes (> 0).
Returns
Pointer to allocated memory, or NULL on failure.
Definition at line 170 of file replicate_hot.c.
{
   void* buf = malloc(blob_size);
   if (!buf) return NULL;
   first_touch_write(buf, blob_size);
   return buf;
 }
References first_touch_write().
Referenced by ie_hot_replicate_build(), and ie_hot_replicate_build_fill().
first_touch_write()
static void first_touch_write (void * p, size_t sz) static
First-touch a writable buffer to bias NUMA page placement.
Writes one byte per cache line across the region to ensure resident pages are backed by the NUMA node of the current CPU affinity.
Parameters
p Pointer to writable memory (non-NULL).
sz Size in bytes.
Definition at line 117 of file replicate_hot.c.
{
   volatile uint8_t* b = (volatile uint8_t*)p;
   const size_t step = 64;
   for (size_t i = 0; i < sz; i += step) b[i] = 0u;
   if (sz) b[sz - 1] = 0u;
 }
Referenced by alloc_replica_first_touch().
free_replicas_internal()
static void free_replicas_internal (ie_hot_replicas_t * reps) static
Free all allocations owned by a replica set (internal helper).
Parameters
reps Replica set (may be NULL).
Definition at line 182 of file replicate_hot.c.
{
   if (!reps) return;
   if (reps->r) {
     for (int s = 0; s < reps->n_sockets; ++s) {
       free(reps->r[s].ptr);
       reps->r[s].ptr = NULL;
       reps->r[s].size = 0;
       reps->r[s].socket_id = 0;
     }
     free(reps->r);
     reps->r = NULL;
   }
   free(reps);
 }
References ie_hot_replicas_t::n_sockets, ie_hot_replica_t::ptr, ie_hot_replicas_t::r, ie_hot_replica_t::size, and ie_hot_replica_t::socket_id.
Referenced by ie_hot_replicas_free(), ie_hot_replicate_build(), and ie_hot_replicate_build_fill().
ie_hot_replica_for_socket()
void* ie_hot_replica_for_socket (const ie_hot_replicas_t * reps, int socket_id, size_t * size_out)
Retrieve the replica pointer for a socket.
Parameters
reps Replicas object (non-NULL).
socket_id Socket id (>= 0).
size_out Optional size return; may be NULL.
Returns
Pointer to replica memory or NULL on error.
Definition at line 355 of file replicate_hot.c.
 {
   if (!reps || socket_id < 0 || socket_id >= reps->n_sockets) return NULL;
   if (size_out) *size_out = reps->r[socket_id].size;
   return reps->r[socket_id].ptr;
 }
References ie_hot_replicas_t::n_sockets, ie_hot_replica_t::ptr, ie_hot_replicas_t::r, and ie_hot_replica_t::size.
ie_hot_replica_memcpy()
int ie_hot_replica_memcpy (ie_hot_replicas_t * reps, int socket_id, const void * src)
Convenience: memcpy() into a given socket’s replica.
Copies exactly the size of the existing replica buffer for socket_id.
Parameters
reps Replicas object (non-NULL).
socket_id Target socket id (>= 0).
src Source bytes (non-NULL). Must be at least replica size.
Returns
0 on success; -EINVAL on bad args; -ENOBUFS if replica size is zero.
Definition at line 374 of file replicate_hot.c.
{
   if (!reps || !src || socket_id < 0 || socket_id >= reps->n_sockets) return -EINVAL;
   void* dst = reps->r[socket_id].ptr;
   if (!dst) return -EINVAL;
   if (reps->r[socket_id].size == 0) return -ENOBUFS;
   memcpy(dst, src, reps->r[socket_id].size);
   return 0;
 }
References ie_hot_replicas_t::n_sockets, ie_hot_replica_t::ptr, ie_hot_replicas_t::r, and ie_hot_replica_t::size.
ie_hot_replicas_free()
void ie_hot_replicas_free (ie_hot_replicas_t * reps)
Free replicas previously built by ie_hot_replicate_build() or ie_hot_replicate_build_fill().
Releases all memory owned by the replica set.
Parameters
reps Replicas object (NULL is allowed).
Definition at line 343 of file replicate_hot.c.
{
   free_replicas_internal(reps);
 }
References free_replicas_internal().
ie_hot_replicate_build()
int ie_hot_replicate_build (const ie_topology_t * topo, int n_sockets, const void * blob, size_t blob_size, ie_hot_replicas_t ** out)
Create per-socket replicas of blob using first-touch placement (copy mode).
For each socket: 1) bind to that socket via ie_topology_bind_thread_to_socket(); 2) allocate replica memory and first-touch it; 3) memcpy() the source blob; 4) hint the kernel that pages will be needed (best-effort).
This is a good default when the source blob is small enough or already hot, and when you do not have a better per-socket fill path.
Parameters
topo Topology handle (non-NULL recommended).
n_sockets Sockets to build (if <= 0, derived from topo; if topo is NULL or invalid, defaults to 1).
blob Source blob (non-NULL).
blob_size Size of blob in bytes (> 0).
out Output pointer to receive the replicas object (non-NULL).
Returns
0 on success; negative errno-like on failure.
Definition at line 219 of file replicate_hot.c.
 {
   if (!out || !blob || blob_size == 0) return -EINVAL;
   int S = n_sockets;
   if (S <= 0 && topo) S = ie_topology_sockets(topo);
   if (S <= 0) S = 1;
   ie_hot_replicas_t* set = (ie_hot_replicas_t*)calloc(1, sizeof(*set));
   if (!set) return -ENOMEM;
   set->n_sockets = S;
   set->r = (ie_hot_replica_t*)calloc((size_t)S, sizeof(*set->r));
   if (!set->r) { free(set); return -ENOMEM; }
   int rc = 0;
   for (int s = 0; s < S; ++s) {
     int brc = ie_topology_bind_thread_to_socket(topo, s);
     if (brc != 0) IE_LOG_WARN("binding to socket %d failed (%d)", s, brc);
     void* buf = alloc_replica_first_touch(blob_size);
     if (!buf) { rc = -ENOMEM; goto fail; }
     memcpy(buf, blob, blob_size);
     advise_willneed(buf, blob_size);
     advise_sequential(buf, blob_size);
     set->r[s].ptr       = buf;
     set->r[s].size      = blob_size;
     set->r[s].socket_id = s;
   }
   *out = set;
   return 0;
 fail:
   free_replicas_internal(set);
   return rc ? rc : -ENOMEM;
 }
References advise_sequential(), advise_willneed(), alloc_replica_first_touch(), free_replicas_internal(), IE_LOG_WARN, ie_topology_bind_thread_to_socket(), ie_topology_sockets(), ie_hot_replicas_t::n_sockets, ie_hot_replica_t::ptr, ie_hot_replicas_t::r, ie_hot_replica_t::size, and ie_hot_replica_t::socket_id.
ie_hot_replicate_build_fill()
int ie_hot_replicate_build_fill (const ie_topology_t * topo, int n_sockets, size_t replica_size, ie_hot_replica_fill_fn fill, void * user, ie_hot_replicas_t ** out)
Create per-socket replicas using a caller-provided fill callback (fill mode).
This is the preferred mode for Step-3 persistent reconstruction: you can reconstruct/assemble the "hot weights blob" directly into the local per-socket replica after first-touch, avoiding cross-socket memcpy traffic.
For each socket: 1) bind to that socket via ie_topology_bind_thread_to_socket(); 2) allocate replica memory and first-touch it; 3) call fill(socket_id, replica_ptr, replica_size, user); 4) hint the kernel that pages will be needed (best-effort).
Parameters
topo Topology handle (non-NULL recommended).
n_sockets Sockets to build (if <= 0, derived from topo; if topo is NULL or invalid, defaults to 1).
replica_size Size in bytes of each replica (> 0).
fill Callback to populate each per-socket replica (non-NULL).
user Opaque user pointer passed to fill.
out Output pointer to receive the replicas object (non-NULL).
Returns
0 on success; negative errno-like on failure.
Definition at line 285 of file replicate_hot.c.
 {
   if (!out || !fill || replica_size == 0) return -EINVAL;
   int S = n_sockets;
   if (S <= 0 && topo) S = ie_topology_sockets(topo);
   if (S <= 0) S = 1;
   ie_hot_replicas_t* set = (ie_hot_replicas_t*)calloc(1, sizeof(*set));
   if (!set) return -ENOMEM;
   set->n_sockets = S;
   set->r = (ie_hot_replica_t*)calloc((size_t)S, sizeof(*set->r));
   if (!set->r) { free(set); return -ENOMEM; }
   int rc = 0;
   for (int s = 0; s < S; ++s) {
     int brc = ie_topology_bind_thread_to_socket(topo, s);
     if (brc != 0) IE_LOG_WARN("binding to socket %d failed (%d)", s, brc);
     void* buf = alloc_replica_first_touch(replica_size);
     if (!buf) { rc = -ENOMEM; goto fail; }
     rc = fill(s, buf, replica_size, user);
     if (rc != 0) {
       IE_LOG_ERROR("fill callback failed for socket %d (%d)", s, rc);
       free(buf);
       goto fail;
     }
     advise_willneed(buf, replica_size);
     advise_sequential(buf, replica_size);
     set->r[s].ptr       = buf;
     set->r[s].size      = replica_size;
     set->r[s].socket_id = s;
   }
   *out = set;
   return 0;
 fail:
   free_replicas_internal(set);
   return rc ? rc : -ENOMEM;
 }
References advise_sequential(), advise_willneed(), alloc_replica_first_touch(), free_replicas_internal(), IE_LOG_ERROR, IE_LOG_WARN, ie_topology_bind_thread_to_socket(), ie_topology_sockets(), ie_hot_replicas_t::n_sockets, ie_hot_replica_t::ptr, ie_hot_replicas_t::r, ie_hot_replica_t::size, and ie_hot_replica_t::socket_id.