Inference Engine (Clocher): engine/src/runtime/sampling.c File Reference
sampling.c File Reference
Token sampling utilities for next-token selection from logits.
#include "ie_sampling.h"
#include <errno.h>
#include <math.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static int sampling_trace_enabled (void)
Check whether sampling tracing is enabled via environment variable.
static uint64_t sampling_trace_limit (void)
Return the trace call limit set by IE_TRACE_SAMPLING_N.
static int sampling_trace_allow (void)
Decide whether the current call should emit trace output.
static const char * kind_name (ie_sample_kind_t k)
Convert sampler kind enum into a human-readable string.
void ie_rng_init (ie_rng_t *rng, uint64_t seed)
Initialize RNG state.
static uint64_t xorshift64star (uint64_t *s)
xorshift64* core step.
uint32_t ie_rng_u32 (ie_rng_t *rng)
Generate a 32-bit random integer.
float ie_rng_f32 (ie_rng_t *rng)
Generate a float in [0, 1).
static int cfg_sanitize (const ie_sample_cfg_t *cfg, ie_sample_cfg_t *out)
Validate and sanitize a sampling configuration.
static uint32_t argmax_logits (const float *logits, size_t n, int disallow0)
Return the argmax index for a logits array.
static float safe_exp (float x)
Wrapper around expf for clarity and potential later clamping.
static void softmax_inplace (float *p, size_t n)
Normalize an array of non-negative values in-place so they sum to 1.
static uint32_t sample_from_probs (const float *p, const uint32_t *idx, size_t n, ie_rng_t *rng)
Sample an index from a probability distribution.
static void sort_desc_by_prob (uint32_t *idx, const float *prob, size_t n)
Sort indices in descending order by probability.
int ie_sample_next (const float *logits, size_t vocab_size, const ie_sample_cfg_t *cfg_in, ie_rng_t *rng, uint32_t *idx_scratch, float *prob_scratch, size_t scratch_cap, uint32_t *out_id)
Choose next token id from logits using the given configuration.
Detailed Description
Token sampling utilities for next-token selection from logits.
This module provides a small, self-contained sampler used by the runtime to select the next token id from a vector of logits.
Implemented sampling modes:
Greedy (argmax): selects the maximum-logit token.
Top-k: keeps the best k logits via an insertion-style selection, applies a numerically-stable softmax over the selected subset, and samples.
Top-p (nucleus): applies temperature softmax over the full vocabulary, sorts by probability descending, takes the smallest prefix whose cumulative probability is >= p, renormalizes, and samples.
Correctness policy:
This is correctness-first. Expensive operations (full sort in top-p) can be optimized later if needed.
Tracing:
Set IE_TRACE_SAMPLING=1 to trace sampling decisions.
Optional: IE_TRACE_SAMPLING_N limits logs to the first N calls (0 = unlimited).
Definition in file sampling.c.
Function Documentation
argmax_logits()
static uint32_t argmax_logits (const float * logits, size_t n, int disallow0) static
Return the argmax index for a logits array.
Parameters
logits Logits array.
n Number of logits.
disallow0 If non-zero, token id 0 is excluded from consideration.
Returns
Index of the maximum logit (or 0 if no valid index exists).
Definition at line 220 of file sampling.c.
{
  uint32_t best_i = 0;
  float best_v = -INFINITY;
  size_t start = 0;
  if (disallow0 && n > 0) start = 1;
  if (start >= n) return 0;
  best_i = (uint32_t)start;
  best_v = logits[start];
  for (size_t i = start + 1; i < n; ++i) {
    float v = logits[i];
    if (v > best_v) {
      best_v = v;
      best_i = (uint32_t)i;
    }
  }
  return best_i;
}
Referenced by ie_sample_next().
cfg_sanitize()
static int cfg_sanitize (const ie_sample_cfg_t * cfg, ie_sample_cfg_t * out) static
Validate and sanitize a sampling configuration.
Ensures temperature is positive, clamps top-p into (0,1], and normalizes top-k to at least 1.
Parameters
cfg Input config.
out Output config.
Returns
0 on success; non-zero on invalid args.
Definition at line 197 of file sampling.c.
{
  if (!cfg || !out) return -1;
  *out = *cfg;
  if (out->temperature <= 0.0f) out->temperature = 1.0f;
  if (out->kind == IE_SAMPLE_TOPK) {
    if (out->top_k == 0) out->top_k = 1;
  } else if (out->kind == IE_SAMPLE_TOPP) {
    if (out->top_p <= 0.0f) out->top_p = 0.9f;
    if (out->top_p > 1.0f) out->top_p = 1.0f;
  }
  return 0;
}
References IE_SAMPLE_TOPK, and IE_SAMPLE_TOPP.
Referenced by ie_sample_next().
ie_rng_f32()
float ie_rng_f32 (ie_rng_t * rng)
Generate a float in [0, 1).
Return a random float in [0, 1).
Produces 24 bits of mantissa using the high bits of a 32-bit random value.
Parameters
rng RNG state.
Returns
Random float in [0,1). If rng is NULL, returns 0.
Definition at line 176 of file sampling.c.
{
  uint32_t x = ie_rng_u32(rng);
  uint32_t m = x >> 8; /* 24 bits */
  return (float)m / (float)(1u << 24);
}
References ie_rng_u32().
Referenced by sample_from_probs().
ie_rng_init()
void ie_rng_init (ie_rng_t * rng, uint64_t seed)
Initialize RNG state.
Initialize RNG with a seed (must be non-zero; 0 is remapped).
Uses xorshift64* for cheap non-cryptographic randomness. If seed is 0, a fixed non-zero seed is used to avoid the zero lock state.
Parameters
rng RNG state (output).
seed Seed value.
Definition at line 136 of file sampling.c.
{
  if (!rng) return;
  rng->s = (seed == 0) ? 0x9E3779B97F4A7C15ull : seed;
}
References ie_rng_s::s.
Referenced by ie_engine_create(), and ie_generate_gptoss().
ie_rng_u32()
uint32_t ie_rng_u32 (ie_rng_t * rng)
Generate a 32-bit random integer.
Return a random uint32.
Parameters
rng RNG state.
Returns
Random 32-bit value (0 on NULL rng).
Definition at line 162 of file sampling.c.
{
  if (!rng) return 0;
  return (uint32_t)(xorshift64star(&rng->s) >> 32);
}
References ie_rng_s::s, and xorshift64star().
Referenced by ie_rng_f32().
ie_sample_next()
int ie_sample_next (const float * logits, size_t vocab_size, const ie_sample_cfg_t * cfg, ie_rng_t * rng, uint32_t * idx_scratch, float * prob_scratch, size_t scratch_cap, uint32_t * out_id)
Choose next token id from logits using the given configuration.
This function may require scratch buffers for indices and probabilities. The caller provides them to avoid allocations.
Scratch requirements:
idx_scratch: capacity >= vocab_size (used for partial selection / sorting).
prob_scratch: capacity >= vocab_size (used for softmax over candidate set).
If you only use greedy mode, scratch may be NULL.
Parameters
logits Input logits array of length vocab_size.
vocab_size Vocabulary size.
cfg Sampling config.
rng RNG state (used for stochastic sampling).
idx_scratch Scratch indices array (uint32_t).
prob_scratch Scratch probabilities array (float).
scratch_cap Capacity of idx_scratch and prob_scratch.
out_id Output token id.
Returns
0 on success, negative on error.
Definition at line 326 of file sampling.c.
{
  if (!logits || vocab_size == 0 || !cfg_in || !out_id) return -1;
  ie_sample_cfg_t cfg;
  if (cfg_sanitize(cfg_in, &cfg) != 0) return -1;
  if (sampling_trace_allow()) {
    fprintf(stderr,
            "[sampling] kind=%s temp=%.6g top_k=%u top_p=%.6g disallow0=%d vocab=%zu\n",
            kind_name(cfg.kind),
            (double)cfg.temperature,
            (unsigned)cfg.top_k,
            (double)cfg.top_p,
            (int)cfg.disallow_token0,
            vocab_size);
  }
  if (cfg.kind == IE_SAMPLE_GREEDY) {
    const uint32_t id = argmax_logits(logits, vocab_size, cfg.disallow_token0);
    *out_id = id;
    if (sampling_trace_allow()) {
      fprintf(stderr, "[sampling] greedy -> id=%u logit=%.6g\n", (unsigned)id, (double)logits[id]);
    }
    return 0;
  }
  if (!idx_scratch || !prob_scratch || scratch_cap < vocab_size) return -1;
  if (!rng) return -1;
  if (cfg.kind == IE_SAMPLE_TOPK) {
    uint32_t k = cfg.top_k;
    if (k > (uint32_t)vocab_size) k = (uint32_t)vocab_size;
    uint32_t sel_n = 0;
    for (size_t i = 0; i < vocab_size && sel_n < k; ++i) {
      if (cfg.disallow_token0 && i == 0) continue;
      idx_scratch[sel_n++] = (uint32_t)i;
    }
    if (sel_n == 0) {
      *out_id = 0;
      if (sampling_trace_allow()) fprintf(stderr, "[sampling] topk -> empty selection, id=0\n");
      return 0;
    }
    /* Keep selection sorted ascending by logit so idx_scratch[0] is the current worst. */
    for (uint32_t i = 1; i < sel_n; ++i) {
      uint32_t key = idx_scratch[i];
      float v = logits[key];
      uint32_t j = i;
      while (j > 0) {
        uint32_t prev = idx_scratch[j - 1];
        if (logits[prev] <= v) break;
        idx_scratch[j] = prev;
        --j;
      }
      idx_scratch[j] = key;
    }
    for (size_t i = 0; i < vocab_size; ++i) {
      if (cfg.disallow_token0 && i == 0) continue;
      float v = logits[i];
      uint32_t worst = idx_scratch[0];
      if (v <= logits[worst]) continue;
      idx_scratch[0] = (uint32_t)i;
      for (uint32_t j = 1; j < sel_n; ++j) {
        uint32_t a = idx_scratch[j - 1];
        uint32_t b = idx_scratch[j];
        if (logits[a] <= logits[b]) continue;
        idx_scratch[j - 1] = b;
        idx_scratch[j] = a;
      }
    }
    float maxl = -INFINITY;
    for (uint32_t i = 0; i < sel_n; ++i) {
      float v = logits[idx_scratch[i]] / cfg.temperature;
      if (v > maxl) maxl = v;
    }
    for (uint32_t i = 0; i < sel_n; ++i) {
      float v = (logits[idx_scratch[i]] / cfg.temperature) - maxl;
      prob_scratch[i] = safe_exp(v);
    }
    softmax_inplace(prob_scratch, sel_n);
    const uint32_t id = sample_from_probs(prob_scratch, idx_scratch, sel_n, rng);
    *out_id = id;
    if (sampling_trace_allow()) {
      fprintf(stderr, "[sampling] topk(k=%u sel=%u) -> id=%u logit=%.6g\n",
              (unsigned)k, (unsigned)sel_n, (unsigned)id, (double)logits[id]);
    }
    return 0;
  }
  if (cfg.kind == IE_SAMPLE_TOPP) {
    float maxl = -INFINITY;
    for (size_t i = 0; i < vocab_size; ++i) {
      if (cfg.disallow_token0 && i == 0) continue;
      float v = logits[i] / cfg.temperature;
      if (v > maxl) maxl = v;
    }
    float sum = 0.0f;
    for (size_t i = 0; i < vocab_size; ++i) {
      if (cfg.disallow_token0 && i == 0) {
        prob_scratch[i] = 0.0f;
        continue;
      }
      float v = (logits[i] / cfg.temperature) - maxl;
      float e = safe_exp(v);
      prob_scratch[i] = e;
      sum += e;
    }
    if (sum <= 0.0f) {
      const uint32_t id = argmax_logits(logits, vocab_size, cfg.disallow_token0);
      *out_id = id;
      if (sampling_trace_allow()) {
        fprintf(stderr, "[sampling] topp -> degenerate sum, fallback greedy id=%u\n", (unsigned)id);
      }
      return 0;
    }
    float inv = 1.0f / sum;
    for (size_t i = 0; i < vocab_size; ++i) prob_scratch[i] *= inv;
    size_t nidx = 0;
    for (size_t i = 0; i < vocab_size; ++i) {
      if (cfg.disallow_token0 && i == 0) continue;
      idx_scratch[nidx++] = (uint32_t)i;
    }
    sort_desc_by_prob(idx_scratch, prob_scratch, nidx);
    float cum = 0.0f;
    size_t cut = 0;
    for (; cut < nidx; ++cut) {
      cum += prob_scratch[idx_scratch[cut]];
      if (cum >= cfg.top_p) {
        ++cut;
        break;
      }
    }
    if (cut == 0) cut = 1;
    if (cut > nidx) cut = nidx;
    float local_sum = 0.0f;
    for (size_t i = 0; i < cut; ++i) local_sum += prob_scratch[idx_scratch[i]];
    if (local_sum <= 0.0f) {
      *out_id = idx_scratch[0];
      if (sampling_trace_allow()) fprintf(stderr, "[sampling] topp -> degenerate local_sum, id=%u\n", (unsigned)*out_id);
      return 0;
    }
    float linv = 1.0f / local_sum;
    for (size_t i = 0; i < cut; ++i) {
      prob_scratch[i] = prob_scratch[idx_scratch[i]] * linv;
    }
    const uint32_t id = sample_from_probs(prob_scratch, idx_scratch, cut, rng);
    *out_id = id;
    if (sampling_trace_allow()) {
      fprintf(stderr, "[sampling] topp(p=%.6g cut=%zu cum=%.6g) -> id=%u logit=%.6g\n",
              (double)cfg.top_p, cut, (double)cum, (unsigned)id, (double)logits[id]);
    }
    return 0;
  }
  return -1;
}
References argmax_logits(), cfg_sanitize(), ie_sample_cfg_s::disallow_token0, IE_SAMPLE_GREEDY, IE_SAMPLE_TOPK, IE_SAMPLE_TOPP, ie_sample_cfg_s::kind, kind_name(), safe_exp(), sample_from_probs(), sampling_trace_allow(), softmax_inplace(), sort_desc_by_prob(), ie_sample_cfg_s::temperature, ie_sample_cfg_s::top_k, and ie_sample_cfg_s::top_p.
Referenced by ie_engine_generate_ex(), and ie_generate_gptoss().
kind_name()
static const char * kind_name (ie_sample_kind_t k) static
Convert sampler kind enum into a human-readable string.
Parameters
k Sampling kind.
Returns
Static string for logging.
Definition at line 113 of file sampling.c.
{
  switch (k) {
    case IE_SAMPLE_GREEDY: return "greedy";
    case IE_SAMPLE_TOPK:   return "topk";
    case IE_SAMPLE_TOPP:   return "topp";
    default: return "unknown";
  }
}
References IE_SAMPLE_GREEDY, IE_SAMPLE_TOPK, and IE_SAMPLE_TOPP.
Referenced by ie_sample_next().
safe_exp()
static float safe_exp (float x) static
Wrapper around expf for clarity and potential later clamping.
Parameters
x Input.
Returns
expf(x).
Definition at line 247 of file sampling.c.
{
  return expf(x);
}
Referenced by ie_sample_next().
sample_from_probs()
static uint32_t sample_from_probs (const float * p, const uint32_t * idx, size_t n, ie_rng_t * rng) static
Sample an index from a probability distribution.
Uses a linear scan over the CDF.
Parameters
p Probability values (must sum to ~1).
idx Optional index remap array. If non-NULL, returns idx[i].
n Number of probabilities.
rng RNG state.
Returns
Sampled id (or last element if numerical drift leaves r >= cdf).
Definition at line 284 of file sampling.c.
{
  float r = ie_rng_f32(rng);
  float c = 0.0f;
  for (size_t i = 0; i < n; ++i) {
    c += p[i];
    if (r < c) return idx ? idx[i] : (uint32_t)i;
  }
  return idx ? idx[n - 1] : (uint32_t)(n - 1);
}
References ie_rng_f32().
Referenced by ie_sample_next().
sampling_trace_allow()
static int sampling_trace_allow (void) static
Decide whether the current call should emit trace output.
This function enforces IE_TRACE_SAMPLING_N if present. Calls are counted from the first invocation of this function in the process.
Returns
1 if tracing should be emitted for this call; 0 otherwise.
Definition at line 98 of file sampling.c.
{
  if (!sampling_trace_enabled()) return 0;
  static uint64_t calls = 0;
  calls++;
  const uint64_t lim = sampling_trace_limit();
  if (lim == 0) return 1;
  return calls <= lim;
}
References sampling_trace_enabled(), and sampling_trace_limit().
Referenced by ie_sample_next().
sampling_trace_enabled()
static int sampling_trace_enabled (void) static
Check whether sampling tracing is enabled via environment variable.
Tracing is enabled if IE_TRACE_SAMPLING is set and not equal to "0". The value is cached after the first call.
Returns
1 if tracing is enabled; 0 otherwise.
Definition at line 53 of file sampling.c.
{
  static int inited = 0;
  static int enabled = 0;
  if (!inited) {
    const char *s = getenv("IE_TRACE_SAMPLING");
    enabled = (s && s[0] && strcmp(s, "0") != 0) ? 1 : 0;
    inited = 1;
  }
  return enabled;
}
Referenced by sampling_trace_allow().
sampling_trace_limit()
static uint64_t sampling_trace_limit (void) static
Return the trace call limit set by IE_TRACE_SAMPLING_N.
If IE_TRACE_SAMPLING_N is unset or parses to 0, tracing is unlimited. The value is cached after the first call.
Returns
Maximum number of trace events to emit; 0 means unlimited.
Definition at line 73 of file sampling.c.
{
  static int inited = 0;
  static uint64_t lim = 0;
  if (!inited) {
    const char *s = getenv("IE_TRACE_SAMPLING_N");
    if (s && s[0]) {
      errno = 0;
      char *end = NULL;
      unsigned long long v = strtoull(s, &end, 10);
      if (end != s && errno == 0) lim = (uint64_t)v;
    }
    inited = 1;
  }
  return lim;
}
Referenced by sampling_trace_allow().
softmax_inplace()
static void softmax_inplace (float * p, size_t n) static
Normalize an array of non-negative values in-place so they sum to 1.
If the sum is non-positive, the distribution is replaced by uniform.
Parameters
p Array of weights/probabilities.
n Length of array.
Definition at line 260 of file sampling.c.
{
  float sum = 0.0f;
  for (size_t i = 0; i < n; ++i) sum += p[i];
  if (sum <= 0.0f) {
    float inv = (n ? (1.0f / (float)n) : 0.0f);
    for (size_t i = 0; i < n; ++i) p[i] = inv;
    return;
  }
  float inv = 1.0f / sum;
  for (size_t i = 0; i < n; ++i) p[i] *= inv;
}
Referenced by ie_sample_next().
sort_desc_by_prob()
static void sort_desc_by_prob (uint32_t * idx, const float * prob, size_t n) static
Sort indices in descending order by probability.
Stable insertion sort using prob[key] as the key.
Parameters
idx Indices to sort in-place.
prob Probability array indexed by token id.
n Number of indices.
Definition at line 307 of file sampling.c.
{
  for (size_t i = 1; i < n; ++i) {
    uint32_t key = idx[i];
    float pv = prob[key];
    size_t j = i;
    while (j > 0) {
      uint32_t prev = idx[j - 1];
      if (prob[prev] >= pv) break;
      idx[j] = prev;
      --j;
    }
    idx[j] = key;
  }
}
Referenced by ie_sample_next().
xorshift64star()
static uint64_t xorshift64star (uint64_t * s) static
xorshift64* core step.
Parameters
s Pointer to 64-bit RNG state.
Returns
Next 64-bit random value.
Definition at line 147 of file sampling.c.
{
  uint64_t x = *s;
  x ^= x >> 12;
  x ^= x << 25;
  x ^= x >> 27;
  *s = x;
  return x * 2685821657736338717ull;
}
Referenced by ie_rng_u32().