Inference Engine (Clocher): engine/src/sparse_io.c File Reference
sparse_io.c File Reference
Loader for block-sparse weight matrices from a compact binary format.
#include "sparse_format.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct ie_block_sparse_header_disk
On-disk header for block-sparse matrices.
Typedefs
typedef struct ie_block_sparse_header_disk ie_block_sparse_header_disk_t
On-disk header for block-sparse matrices.
Functions
static ie_sparse_status_t read_fully (void *ptr, size_t size, FILE *f)
Safely read size bytes from a stream into ptr.
const char * ie_sparse_status_str (ie_sparse_status_t st)
Human-readable description of an ie_sparse_status_t code.
void ie_block_sparse_init (ie_block_sparse_matrix_t *m)
Initialize a block-sparse matrix descriptor to a safe empty state.
void ie_block_sparse_release (ie_block_sparse_matrix_t *m)
Release all heap-allocated storage owned by a block-sparse matrix.
uint32_t ie_block_sparse_n_block_rows (uint32_t rows, uint32_t block_rows)
Compute the theoretical number of block rows for a given layout.
uint32_t ie_block_sparse_n_block_cols (uint32_t cols, uint32_t block_cols)
Compute the theoretical number of block columns for a given layout.
float ie_block_sparse_density (uint32_t nnzb, uint32_t n_block_rows, uint32_t n_block_cols)
Compute the logical density (non-zero blocks / total blocks).
ie_sparse_status_t ie_block_sparse_load (const char *path, ie_block_sparse_matrix_t *out)
Load a block-sparse matrix from a binary file.
Detailed Description
Loader for block-sparse weight matrices from a compact binary format.
This translation unit implements a minimal on-disk format and corresponding loader for ie_block_sparse_matrix_t. It is designed to be:
Compact: only non-zero blocks and essential metadata are stored.
Portable across typical x86_64 setups: assumes little-endian layout and 32-bit integers for sizes and indices.
Strict but forgiving: basic validation is performed on all fields (magic, version, dimensions, counts). On failure, no partially loaded state is left in the descriptor.
The on-disk layout is:
struct ie_block_sparse_header_disk {
  char     magic[4];      // "IEBS"
  uint32_t version;       // currently 1
  uint32_t rows;          // total dense rows
  uint32_t cols;          // total dense columns
  uint32_t block_rows;    // block height
  uint32_t block_cols;    // block width
  uint32_t nnzb;          // number of non-zero blocks
  uint32_t reserved[4];   // reserved for future use (zeroed)
};
// Followed by:
uint32_t row_ptr[n_block_rows + 1];
uint32_t col_idx[nnzb];
float    values[nnzb * block_rows * block_cols];
where:
n_block_rows = ceil(rows / block_rows)
n_block_cols = ceil(cols / block_cols)
The loader validates that:
block_rows and block_cols are non-zero.
rows and cols are non-zero.
nnzb is consistent with the size of the values array.
Error handling:
Functions return ie_sparse_status_t codes.
On any error, the output descriptor is left in a zeroed state.
Definition in file sparse_io.c.
Typedef Documentation
ie_block_sparse_header_disk_t
typedef struct ie_block_sparse_header_disk ie_block_sparse_header_disk_t
On-disk header for block-sparse matrices.
Note
This type is not exposed in public headers; it is specific to the implementation of ie_block_sparse_load.
Function Documentation
ie_block_sparse_density()
float ie_block_sparse_density (uint32_t nnzb, uint32_t n_block_rows, uint32_t n_block_cols)
Compute the logical density (non-zero blocks / total blocks).
The return value is a floating-point fraction between 0.0 and 1.0. If any of the parameters is zero, this function returns 0.0.
Parameters
nnzb Number of non-zero blocks.
n_block_rows Number of block rows.
n_block_cols Number of block columns.
Returns
Density as a float in [0.0, 1.0].
Definition at line 160 of file sparse_io.c.
{
  const uint64_t total_blocks =
      (uint64_t)n_block_rows * (uint64_t)n_block_cols;
  if (total_blocks == 0u) {
    return 0.0f;
  }
  if (nnzb == 0u) {
    return 0.0f;
  }
  const float num = (float)nnzb;
  const float den = (float)total_blocks;
  return num / den;
}
References ie_gemv_rowwise_f32_kernel().
Referenced by main(), and test_block_sparse_helpers().
ie_block_sparse_init()
void ie_block_sparse_init (ie_block_sparse_matrix_t * m)
Initialize a block-sparse matrix descriptor to a safe empty state.
This function does not allocate any memory. It only sets all fields to zero or NULL, making the descriptor safe to pass to ie_block_sparse_release or to any loader function that expects an initially empty descriptor.
Parameters
m Descriptor to initialize (may be NULL, in which case this function is a no-op).
Definition at line 129 of file sparse_io.c.
{
  if (!m) {
    return;
  }
  memset(m, 0, sizeof(*m));
}
References ie_gemv_rowwise_f32_kernel().
Referenced by build_block_sparse_4x4(), dense_to_block_sparse(), dense_to_block_sparse(), ie_block_sparse_load(), test_block_sparse_init_release(), and test_block_sparse_load_missing().
ie_block_sparse_load()
ie_sparse_status_t ie_block_sparse_load (const char * path, ie_block_sparse_matrix_t * out)
Load a block-sparse matrix from a binary file.
This function reads the on-disk format described in the file header documentation above and populates out with a fully initialized ie_block_sparse_matrix_t instance.
On success:
ie_block_sparse_matrix_t::rows and cols reflect the dense dimensions.
ie_block_sparse_matrix_t::block_rows and block_cols reflect the block layout.
ie_block_sparse_matrix_t::n_block_rows and n_block_cols are derived from the dense dimensions and block sizes.
ie_block_sparse_matrix_t::row_ptr, col_idx, and values are allocated and filled.
On failure:
IE_SPARSE_ERR_* is returned.
out is left in a zeroed / empty state (safe to reuse or release).
Parameters
path Filesystem path to the binary block-sparse matrix.
out Destination descriptor (must not be NULL).
Returns
IE_SPARSE_OK on success, error code otherwise.
Definition at line 206 of file sparse_io.c.
{
  if (!path || !out) {
    return IE_SPARSE_ERR_ARGS;
  }
  ie_block_sparse_init(out);
  FILE *f = fopen(path, "rb");
  if (!f) {
    return IE_SPARSE_ERR_OPEN;
  }
  ie_block_sparse_header_disk_t hdr;
  const ie_sparse_status_t st_hdr = read_fully(&hdr, sizeof(hdr), f);
  if (st_hdr != IE_SPARSE_OK) {
    fclose(f);
    return st_hdr;
  }
  /* Validate magic and version. */
  if (memcmp(hdr.magic, "IEBS", 4) != 0 || hdr.version != 1u) {
    fclose(f);
    return IE_SPARSE_ERR_MAGIC;
  }
  /* Basic sanity checks on dimensions. */
  if (hdr.rows == 0u || hdr.cols == 0u ||
      hdr.block_rows == 0u || hdr.block_cols == 0u) {
    fclose(f);
    return IE_SPARSE_ERR_FORMAT;
  }
  const uint32_t n_block_rows =
      ie_block_sparse_n_block_rows(hdr.rows, hdr.block_rows);
  const uint32_t n_block_cols =
      ie_block_sparse_n_block_cols(hdr.cols, hdr.block_cols);
  const uint32_t nnzb = hdr.nnzb;
  /* Guard against overflow in total values. */
  const uint64_t block_elems =
      (uint64_t)hdr.block_rows * (uint64_t)hdr.block_cols;
  const uint64_t total_vals = block_elems * (uint64_t)nnzb;
  if (n_block_rows == 0u || n_block_cols == 0u || block_elems == 0u) {
    fclose(f);
    return IE_SPARSE_ERR_FORMAT;
  }
  if (total_vals > (uint64_t)SIZE_MAX / sizeof(float)) {
    fclose(f);
    return IE_SPARSE_ERR_FORMAT;
  }
  /* Allocate arrays. */
  uint32_t *row_ptr = (uint32_t *)malloc((size_t)(n_block_rows + 1u) *
                                         sizeof(uint32_t));
  uint32_t *col_idx = (uint32_t *)malloc((size_t)nnzb * sizeof(uint32_t));
  float *values = NULL;
  if (!row_ptr || (!col_idx && nnzb > 0u)) {
    free(row_ptr);
    free(col_idx);
    fclose(f);
    return IE_SPARSE_ERR_NOMEM;
  }
  if (nnzb > 0u) {
    values = (float *)malloc((size_t)total_vals * sizeof(float));
    if (!values) {
      free(row_ptr);
      free(col_idx);
      fclose(f);
      return IE_SPARSE_ERR_NOMEM;
    }
  }
  /* Read arrays from file. */
  ie_sparse_status_t st = IE_SPARSE_OK;
  st = read_fully(row_ptr,
                  (size_t)(n_block_rows + 1u) * sizeof(uint32_t),
                  f);
  if (st != IE_SPARSE_OK) {
    goto fail;
  }
  if (nnzb > 0u) {
    st = read_fully(col_idx, (size_t)nnzb * sizeof(uint32_t), f);
    if (st != IE_SPARSE_OK) {
      goto fail;
    }
    st = read_fully(values, (size_t)total_vals * sizeof(float), f);
    if (st != IE_SPARSE_OK) {
      goto fail;
    }
  }
  fclose(f);
  /* Commit to the output descriptor. */
  out->rows        = hdr.rows;
  out->cols        = hdr.cols;
  out->block_rows  = hdr.block_rows;
  out->block_cols  = hdr.block_cols;
  out->n_block_rows = n_block_rows;
  out->n_block_cols = n_block_cols;
  out->nnzb        = nnzb;
  out->row_ptr     = row_ptr;
  out->col_idx     = col_idx;
  out->values      = values;
  return IE_SPARSE_OK;
fail:
  free(row_ptr);
  free(col_idx);
  free(values);
  fclose(f);
  ie_block_sparse_init(out);
  return st;
}
References ie_block_sparse_init(), ie_block_sparse_n_block_cols(), ie_block_sparse_n_block_rows(), ie_gemv_rowwise_f32_kernel(), IE_SPARSE_ERR_ARGS, IE_SPARSE_ERR_FORMAT, IE_SPARSE_ERR_MAGIC, IE_SPARSE_ERR_NOMEM, IE_SPARSE_ERR_OPEN, IE_SPARSE_OK, and read_fully().
Referenced by test_block_sparse_load_missing().
ie_block_sparse_n_block_cols()
uint32_t ie_block_sparse_n_block_cols (uint32_t cols, uint32_t block_cols)
Compute the theoretical number of block columns for a given layout.
Parameters
cols Total number of columns in the dense matrix.
block_cols Block width (columns per block, must be >0).
Returns
Number of block columns (ceil(cols / block_cols)), or 0 on invalid input.
Definition at line 153 of file sparse_io.c.
{
  if (cols == 0 || block_cols == 0) {
    return 0;
  }
  return (cols + block_cols - 1u) / block_cols;
}
Referenced by build_block_sparse_4x4(), dense_to_block_sparse(), dense_to_block_sparse(), ie_block_sparse_load(), and test_block_sparse_helpers().
ie_block_sparse_n_block_rows()
uint32_t ie_block_sparse_n_block_rows (uint32_t rows, uint32_t block_rows)
Compute the theoretical number of block rows for a given layout.
Parameters
rows Total number of rows in the dense matrix.
block_rows Block height (rows per block, must be >0).
Returns
Number of block rows (ceil(rows / block_rows)), or 0 on invalid input.
Definition at line 146 of file sparse_io.c.
{
  if (rows == 0 || block_rows == 0) {
    return 0;
  }
  return (rows + block_rows - 1u) / block_rows;
}
Referenced by build_block_sparse_4x4(), dense_to_block_sparse(), dense_to_block_sparse(), ie_block_sparse_load(), and test_block_sparse_helpers().
ie_block_sparse_release()
void ie_block_sparse_release (ie_block_sparse_matrix_t * m)
Release all heap-allocated storage owned by a block-sparse matrix.
If m is NULL, this function is a no-op. Otherwise it:
Calls free on ie_block_sparse_matrix_t::row_ptr, ie_block_sparse_matrix_t::col_idx, and ie_block_sparse_matrix_t::values when non-NULL.
Resets all scalar fields to zero.
Sets all pointer fields to NULL.
After this call, the descriptor is in the same state as after ie_block_sparse_init and may be reused.
Parameters
m Descriptor whose storage should be released (may be NULL).
Definition at line 136 of file sparse_io.c.
{
  if (!m) {
    return;
  }
  free(m->row_ptr);
  free(m->col_idx);
  free(m->values);
  memset(m, 0, sizeof(*m));
}
References ie_gemv_rowwise_f32_kernel().
Referenced by main(), test_block_sparse_gemv_basic(), test_block_sparse_init_release(), and test_block_sparse_load_missing().
ie_sparse_status_str()
const char * ie_sparse_status_str (ie_sparse_status_t st)
Human-readable description of an ie_sparse_status_t code.
Parameters
st Status code to describe.
Returns
Pointer to a static, NUL-terminated string describing the status.
Note
The returned pointer is valid for the lifetime of the process and must not be freed by the caller.
Definition at line 116 of file sparse_io.c.
{
  switch (st) {
    case IE_SPARSE_OK:         return "ok";
    case IE_SPARSE_ERR_ARGS:   return "invalid arguments";
    case IE_SPARSE_ERR_OPEN:   return "failed to open file";
    case IE_SPARSE_ERR_READ:   return "failed to read file";
    case IE_SPARSE_ERR_MAGIC:  return "invalid magic or version";
    case IE_SPARSE_ERR_FORMAT: return "invalid or unsupported format";
    case IE_SPARSE_ERR_NOMEM:  return "out of memory";
    default:                   return "unknown sparse status";
  }
}
References ie_gemv_rowwise_f32_kernel(), IE_SPARSE_ERR_ARGS, IE_SPARSE_ERR_FORMAT, IE_SPARSE_ERR_MAGIC, IE_SPARSE_ERR_NOMEM, IE_SPARSE_ERR_OPEN, IE_SPARSE_ERR_READ, and IE_SPARSE_OK.
Referenced by test_block_sparse_load_missing().
read_fully()
static ie_sparse_status_t read_fully (void * ptr, size_t size, FILE * f) static
Safely read size bytes from a stream into ptr.
This helper wraps fread and ensures that exactly size bytes are read (unless the file terminates early or an error occurs).
Parameters
ptr Destination buffer (must not be NULL).
size Number of bytes to read.
f Opened file stream (must not be NULL).
Returns
IE_SPARSE_OK on success, IE_SPARSE_ERR_READ on failure.
Definition at line 98 of file sparse_io.c.
{
  if (!ptr || !f) {
    return IE_SPARSE_ERR_ARGS;
  }
  if (size == 0) {
    return IE_SPARSE_OK;
  }
  const size_t n = fread(ptr, 1, size, f);
  if (n != size) {
    return IE_SPARSE_ERR_READ;
  }
  return IE_SPARSE_OK;
}
References ie_gemv_rowwise_f32_kernel(), IE_SPARSE_ERR_ARGS, IE_SPARSE_ERR_READ, and IE_SPARSE_OK.
Referenced by ie_block_sparse_load().