Inference Engine (Clocher): engine/include/sparse_format.h File Reference
sparse_format.h File Reference
In-memory representation and loader interface for block-sparse matrices.
#include <stddef.h>
#include <stdint.h>
#include "platform.h"
Data Structures
struct ie_block_sparse_matrix
In-memory representation of a block-sparse matrix.
Typedefs
typedef enum ie_sparse_status_e ie_sparse_status_t
Status codes for block-sparse operations.
typedef struct ie_block_sparse_matrix ie_block_sparse_matrix_t
In-memory representation of a block-sparse matrix.
Enumerations
enum ie_sparse_status_e {
IE_SPARSE_OK = 0 , IE_SPARSE_ERR_ARGS = -1 , IE_SPARSE_ERR_OPEN = -2 , IE_SPARSE_ERR_READ = -3 ,
IE_SPARSE_ERR_MAGIC = -4 , IE_SPARSE_ERR_FORMAT = -5 , IE_SPARSE_ERR_NOMEM = -6
}
Status codes for block-sparse operations.
Functions
const char * ie_sparse_status_str (ie_sparse_status_t st)
Human-readable description of an ie_sparse_status_t code.
void ie_block_sparse_init (ie_block_sparse_matrix_t *m)
Initialize a block-sparse matrix descriptor to a safe empty state.
void ie_block_sparse_release (ie_block_sparse_matrix_t *m)
Release all heap-allocated storage owned by a block-sparse matrix.
uint32_t ie_block_sparse_n_block_rows (uint32_t rows, uint32_t block_rows)
Compute the theoretical number of block rows for a given layout.
uint32_t ie_block_sparse_n_block_cols (uint32_t cols, uint32_t block_cols)
Compute the theoretical number of block columns for a given layout.
float ie_block_sparse_density (uint32_t nnzb, uint32_t n_block_rows, uint32_t n_block_cols)
Compute the logical density (non-zero blocks / total blocks).
ie_sparse_status_t ie_block_sparse_load (const char *path, ie_block_sparse_matrix_t *out)
Load a block-sparse matrix from a binary file.
void ie_gemv_block_sparse_f32 (const ie_block_sparse_matrix_t *m, const float *x, float *y, const float *bias)
Perform a single-precision block-sparse matrix-vector product.
Detailed Description
In-memory representation and loader interface for block-sparse matrices.
This header defines:
The in-memory layout for block-sparse matrices used by the engine (see ie_block_sparse_matrix_t).
A small status-code enum for sparse-related operations (see ie_sparse_status_t).
Utility helpers for computing block grid sizes and densities.
The public loader function ie_block_sparse_load, which reads a compact binary representation into an in-memory descriptor.
A reference single-precision GEMV kernel (see ie_gemv_block_sparse_f32).
The chosen layout is a block-row CSR (BSR):
The full matrix has rows x cols elements.
It is partitioned into blocks of block_rows x block_cols.
Block rows are numbered from 0 to n_block_rows-1, where n_block_rows = ceil(rows / block_rows).
Block columns are numbered from 0 to n_block_cols-1, where n_block_cols = ceil(cols / block_cols).
Only non-zero blocks are stored; zero blocks are omitted.
Storage:
ie_block_sparse_matrix_t::row_ptr has size (n_block_rows + 1). For block-row br, the non-zero block indices are in the range: [ row_ptr[br], row_ptr[br + 1]).
ie_block_sparse_matrix_t::col_idx has size nnzb, where each entry stores a block-column index (0-based).
ie_block_sparse_matrix_t::values has size: nnzb * block_rows * block_cols. Values for block j are laid out in row-major order:
offset = j * (block_rows * block_cols);
// element (i, k) inside the block:
values[offset + i * block_cols + k]
Notes:
Tail blocks (on the last block-row/column) may extend beyond the actual matrix dimensions. Consumers must clip accesses using the rows and cols fields.
The on-disk format is defined by the implementation in engine/src/sparse_io.c and consumed via ie_block_sparse_load.
Definition in file sparse_format.h.
Typedef Documentation
ie_block_sparse_matrix_t
typedef struct ie_block_sparse_matrix ie_block_sparse_matrix_t
In-memory representation of a block-sparse matrix.
This structure contains all metadata and storage required to perform matrix-vector products in block-sparse form. It is owned by the caller; loader functions such as ie_block_sparse_load will allocate and populate the arrays and can later be released using ie_block_sparse_release.
Lifetime rules:
All pointer fields are either NULL (when nnzb is zero) or point to heap-allocated memory obtained via malloc.
After a successful load, the caller must eventually call ie_block_sparse_release on the descriptor.
After release, the descriptor is left in a zeroed state and may be reused or safely destroyed.
ie_sparse_status_t
typedef enum ie_sparse_status_e ie_sparse_status_t
Status codes for block-sparse operations.
These codes are returned by functions that manipulate block-sparse matrices, in particular ie_block_sparse_load. They are designed to be lightweight and sufficient for logging and error propagation.
Enumeration Type Documentation
ie_sparse_status_e
enum ie_sparse_status_e
Status codes for block-sparse operations.
These codes are returned by functions that manipulate block-sparse matrices, in particular ie_block_sparse_load. They are designed to be lightweight and sufficient for logging and error propagation.
Enumerator
IE_SPARSE_OK
Operation completed successfully.
IE_SPARSE_ERR_ARGS
Invalid arguments (NULL pointer, size mismatch, etc.).
IE_SPARSE_ERR_OPEN
Failed to open a required file.
IE_SPARSE_ERR_READ
Failed to read from a required file.
IE_SPARSE_ERR_MAGIC
Encountered an unexpected magic number or version.
IE_SPARSE_ERR_FORMAT
Encountered an invalid or unsupported on-disk format.
IE_SPARSE_ERR_NOMEM
Memory allocation failure.
Definition at line 72 of file sparse_format.h.
{
  IE_SPARSE_OK = 0,
  IE_SPARSE_ERR_ARGS = -1,
  IE_SPARSE_ERR_OPEN = -2,
  IE_SPARSE_ERR_READ = -3,
  IE_SPARSE_ERR_MAGIC = -4,
  IE_SPARSE_ERR_FORMAT = -5,
  IE_SPARSE_ERR_NOMEM = -6
} ie_sparse_status_t;
Function Documentation
ie_block_sparse_density()
float ie_block_sparse_density (uint32_t nnzb, uint32_t n_block_rows, uint32_t n_block_cols)
Compute the logical density (non-zero blocks / total blocks).
The return value is a floating-point fraction between 0.0 and 1.0. If any of the parameters is zero, this function returns 0.0.
Parameters
nnzb Number of non-zero blocks.
n_block_rows Number of block rows.
n_block_cols Number of block columns.
Returns
Density as a float in [0.0, 1.0].
Definition at line 160 of file sparse_io.c.
{
  const uint64_t total_blocks =
      (uint64_t)n_block_rows * (uint64_t)n_block_cols;
  if (total_blocks == 0u) {
    return 0.0f;
  }
  if (nnzb == 0u) {
    return 0.0f;
  }
  const float num = (float)nnzb;
  const float den = (float)total_blocks;
  return num / den;
}
References ie_gemv_rowwise_f32_kernel().
Referenced by main(), and test_block_sparse_helpers().
ie_block_sparse_init()
void ie_block_sparse_init (ie_block_sparse_matrix_t * m)
Initialize a block-sparse matrix descriptor to a safe empty state.
This function does not allocate any memory. It only sets all fields to zero or NULL, making the descriptor safe to pass to ie_block_sparse_release or to any loader function that expects an initially empty descriptor.
Parameters
m Descriptor to initialize (may be NULL, in which case this function is a no-op).
Definition at line 129 of file sparse_io.c.
{
  if (!m) {
    return;
  }
  memset(m, 0, sizeof(*m));
}
References ie_gemv_rowwise_f32_kernel().
Referenced by build_block_sparse_4x4(), dense_to_block_sparse(), dense_to_block_sparse(), ie_block_sparse_load(), test_block_sparse_init_release(), and test_block_sparse_load_missing().
ie_block_sparse_load()
ie_sparse_status_t ie_block_sparse_load (const char * path, ie_block_sparse_matrix_t * out)
Load a block-sparse matrix from a binary file.
This function reads the on-disk format defined by the implementation in engine/src/sparse_io.c and populates out with a fully initialized ie_block_sparse_matrix_t instance.
On success:
ie_block_sparse_matrix_t::rows and cols reflect the dense dimensions.
ie_block_sparse_matrix_t::block_rows and block_cols reflect the block layout.
ie_block_sparse_matrix_t::n_block_rows and n_block_cols are derived from the dense dimensions and block sizes.
ie_block_sparse_matrix_t::row_ptr, col_idx, and values are allocated and filled.
On failure:
IE_SPARSE_ERR_* is returned.
out is left in a zeroed / empty state (safe to reuse or release).
Parameters
path Filesystem path to the binary block-sparse matrix.
out Destination descriptor (must not be NULL).
Returns
IE_SPARSE_OK on success, error code otherwise.
This function reads the on-disk format described in the file header documentation above and populates out with a fully initialized ie_block_sparse_matrix_t instance.
On success:
ie_block_sparse_matrix_t::rows and cols reflect the dense dimensions.
ie_block_sparse_matrix_t::block_rows and block_cols reflect the block layout.
ie_block_sparse_matrix_t::n_block_rows and n_block_cols are derived from the dense dimensions and block sizes.
ie_block_sparse_matrix_t::row_ptr, col_idx, and values are allocated and filled.
On failure:
IE_SPARSE_ERR_* is returned.
out is left in a zeroed / empty state (safe to reuse or release).
Parameters
path Filesystem path to the binary block-sparse matrix.
out Destination descriptor (must not be NULL).
Returns
IE_SPARSE_OK on success, error code otherwise.
Definition at line 206 of file sparse_io.c.
{
  if (!path || !out) {
    return IE_SPARSE_ERR_ARGS;
  }
  ie_block_sparse_init(out);
  FILE *f = fopen(path, "rb");
  if (!f) {
    return IE_SPARSE_ERR_OPEN;
  }
  ie_block_sparse_header_disk_t hdr;
  const ie_sparse_status_t st_hdr = read_fully(&hdr, sizeof(hdr), f);
  if (st_hdr != IE_SPARSE_OK) {
    fclose(f);
    return st_hdr;
  }
  /* Validate magic and version. */
  if (memcmp(hdr.magic, "IEBS", 4) != 0 || hdr.version != 1u) {
    fclose(f);
    return IE_SPARSE_ERR_MAGIC;
  }
  /* Basic sanity checks on dimensions. */
  if (hdr.rows == 0u || hdr.cols == 0u ||
      hdr.block_rows == 0u || hdr.block_cols == 0u) {
    fclose(f);
    return IE_SPARSE_ERR_FORMAT;
  }
  const uint32_t n_block_rows =
      ie_block_sparse_n_block_rows(hdr.rows, hdr.block_rows);
  const uint32_t n_block_cols =
      ie_block_sparse_n_block_cols(hdr.cols, hdr.block_cols);
  const uint32_t nnzb = hdr.nnzb;
  /* Guard against overflow in total values. */
  const uint64_t block_elems =
      (uint64_t)hdr.block_rows * (uint64_t)hdr.block_cols;
  const uint64_t total_vals = block_elems * (uint64_t)nnzb;
  if (n_block_rows == 0u || n_block_cols == 0u || block_elems == 0u) {
    fclose(f);
    return IE_SPARSE_ERR_FORMAT;
  }
  if (total_vals > (uint64_t)SIZE_MAX / sizeof(float)) {
    fclose(f);
    return IE_SPARSE_ERR_FORMAT;
  }
  /* Allocate arrays. */
  uint32_t *row_ptr = (uint32_t *)malloc((size_t)(n_block_rows + 1u) *
                                         sizeof(uint32_t));
  uint32_t *col_idx = (uint32_t *)malloc((size_t)nnzb * sizeof(uint32_t));
  float *values = NULL;
  if (!row_ptr || (!col_idx && nnzb > 0u)) {
    free(row_ptr);
    free(col_idx);
    fclose(f);
    return IE_SPARSE_ERR_NOMEM;
  }
  if (nnzb > 0u) {
    values = (float *)malloc((size_t)total_vals * sizeof(float));
    if (!values) {
      free(row_ptr);
      free(col_idx);
      fclose(f);
      return IE_SPARSE_ERR_NOMEM;
    }
  }
  /* Read arrays from file. */
  ie_sparse_status_t st = IE_SPARSE_OK;
  st = read_fully(row_ptr,
                  (size_t)(n_block_rows + 1u) * sizeof(uint32_t),
                  f);
  if (st != IE_SPARSE_OK) {
    goto fail;
  }
  if (nnzb > 0u) {
    st = read_fully(col_idx, (size_t)nnzb * sizeof(uint32_t), f);
    if (st != IE_SPARSE_OK) {
      goto fail;
    }
    st = read_fully(values, (size_t)total_vals * sizeof(float), f);
    if (st != IE_SPARSE_OK) {
      goto fail;
    }
  }
  fclose(f);
  /* Commit to the output descriptor. */
  out->rows        = hdr.rows;
  out->cols        = hdr.cols;
  out->block_rows  = hdr.block_rows;
  out->block_cols  = hdr.block_cols;
  out->n_block_rows = n_block_rows;
  out->n_block_cols = n_block_cols;
  out->nnzb        = nnzb;
  out->row_ptr     = row_ptr;
  out->col_idx     = col_idx;
  out->values      = values;
  return IE_SPARSE_OK;
fail:
  free(row_ptr);
  free(col_idx);
  free(values);
  fclose(f);
  ie_block_sparse_init(out);
  return st;
}
References ie_block_sparse_init(), ie_block_sparse_n_block_cols(), ie_block_sparse_n_block_rows(), ie_gemv_rowwise_f32_kernel(), IE_SPARSE_ERR_ARGS, IE_SPARSE_ERR_FORMAT, IE_SPARSE_ERR_MAGIC, IE_SPARSE_ERR_NOMEM, IE_SPARSE_ERR_OPEN, IE_SPARSE_OK, and read_fully().
Referenced by test_block_sparse_load_missing().
ie_block_sparse_n_block_cols()
uint32_t ie_block_sparse_n_block_cols (uint32_t cols, uint32_t block_cols)
Compute the theoretical number of block columns for a given layout.
Parameters
cols Total number of columns in the dense matrix.
block_cols Block width (columns per block, must be >0).
Returns
Number of block columns (ceil(cols / block_cols)), or 0 on invalid input.
Definition at line 153 of file sparse_io.c.
{
  if (cols == 0 || block_cols == 0) {
    return 0;
  }
  return (cols + block_cols - 1u) / block_cols;
}
Referenced by build_block_sparse_4x4(), dense_to_block_sparse(), dense_to_block_sparse(), ie_block_sparse_load(), and test_block_sparse_helpers().
ie_block_sparse_n_block_rows()
uint32_t ie_block_sparse_n_block_rows (uint32_t rows, uint32_t block_rows)
Compute the theoretical number of block rows for a given layout.
Parameters
rows Total number of rows in the dense matrix.
block_rows Block height (rows per block, must be >0).
Returns
Number of block rows (ceil(rows / block_rows)), or 0 on invalid input.
Definition at line 146 of file sparse_io.c.
{
  if (rows == 0 || block_rows == 0) {
    return 0;
  }
  return (rows + block_rows - 1u) / block_rows;
}
Referenced by build_block_sparse_4x4(), dense_to_block_sparse(), dense_to_block_sparse(), ie_block_sparse_load(), and test_block_sparse_helpers().
ie_block_sparse_release()
void ie_block_sparse_release (ie_block_sparse_matrix_t * m)
Release all heap-allocated storage owned by a block-sparse matrix.
If m is NULL, this function is a no-op. Otherwise it:
Calls free on ie_block_sparse_matrix_t::row_ptr, ie_block_sparse_matrix_t::col_idx, and ie_block_sparse_matrix_t::values when non-NULL.
Resets all scalar fields to zero.
Sets all pointer fields to NULL.
After this call, the descriptor is in the same state as after ie_block_sparse_init and may be reused.
Parameters
m Descriptor whose storage should be released (may be NULL).
Definition at line 136 of file sparse_io.c.
{
  if (!m) {
    return;
  }
  free(m->row_ptr);
  free(m->col_idx);
  free(m->values);
  memset(m, 0, sizeof(*m));
}
References ie_gemv_rowwise_f32_kernel().
Referenced by main(), test_block_sparse_gemv_basic(), test_block_sparse_init_release(), and test_block_sparse_load_missing().
ie_gemv_block_sparse_f32()
void ie_gemv_block_sparse_f32 (const ie_block_sparse_matrix_t * m, const float * x, float * y, const float * bias)
Perform a single-precision block-sparse matrix-vector product.
This function computes:
y = W * x  (+ bias, if provided)
where W is represented in block-sparse form using ie_block_sparse_matrix_t. The input vector x has length m->cols, and the output y has length m->rows.
Tail blocks:
If the matrix size is not an exact multiple of the block dimensions, the implementation clips accesses to rows and cols, ensuring no out-of-bounds reads/writes occur.
Threading:
This function is intentionally single-threaded. Thread-level parallelism should be managed by higher-level components (e.g., a thread pool).
Parameters
m Block-sparse matrix descriptor (must be fully initialized).
x Input vector of length m->cols (must not be NULL).
y Output vector of length m->rows (must not be NULL).
bias Optional bias vector of length m->rows (may be NULL).
Definition at line 77 of file gemm_block_sparse.c.
{
  if (!m || !x || !y) {
    return;
  }
  const uint32_t rows         = m->rows;
  const uint32_t cols         = m->cols;
  const uint32_t block_rows   = m->block_rows;
  const uint32_t block_cols   = m->block_cols;
  const uint32_t n_block_rows = m->n_block_rows;
  if (rows == 0u || cols == 0u ||
      block_rows == 0u || block_cols == 0u ||
      n_block_rows == 0u) {
    return;
  }
  /* For each block-row, process its constituent row stripes. */
  for (uint32_t br = 0u; br < n_block_rows; ++br) {
    const uint32_t row_start = br * block_rows;
    const uint32_t row_end   = row_start + block_rows;
    /* Iterate within the block-row over actual rows (tail-safe). */
    for (uint32_t local_r = 0u; local_r < block_rows; ++local_r) {
      const uint32_t row = row_start + local_r;
      if (row >= rows) {
        break;
      }
      float acc = bias ? bias[row] : 0.0f;
      const uint32_t blk_begin = m->row_ptr[br];
      const uint32_t blk_end   = m->row_ptr[br + 1u];
      /* Accumulate contributions from all non-zero blocks in this block-row. */
      for (uint32_t bi = blk_begin; bi < blk_end; ++bi) {
        const uint32_t bc = m->col_idx[bi];
        const uint32_t col_block_start = bc * block_cols;
        const float *block = block_values_ptr(m, bi);
        const float *block_row = block + (size_t)local_r * (size_t)block_cols;
        /* Inner product of the local block row with the corresponding
         * slice of x, with clipping for tail columns. */
        for (uint32_t local_c = 0u; local_c < block_cols; ++local_c) {
          const uint32_t col = col_block_start + local_c;
          if (col >= cols) {
            break;
          }
          acc += block_row[local_c] * x[col];
        }
      }
      y[row] = acc;
    }
    (void)row_end; /* suppress unused-variable warning if not referenced */
  }
}
References ie_block_sparse_matrix::block_cols, ie_block_sparse_matrix::block_rows, block_values_ptr(), ie_block_sparse_matrix::cols, ie_gemv_rowwise_f32_kernel(), ie_block_sparse_matrix::n_block_rows, and ie_block_sparse_matrix::rows.
Referenced by cpu_gemv_block_sparse_f32(), main(), and test_block_sparse_gemv_basic().
ie_sparse_status_str()
const char * ie_sparse_status_str (ie_sparse_status_t st)
Human-readable description of an ie_sparse_status_t code.
Parameters
st Status code to describe.
Returns
Pointer to a static, NUL-terminated string describing the status.
Note
The returned pointer is valid for the lifetime of the process and must not be freed by the caller.
Definition at line 116 of file sparse_io.c.
{
  switch (st) {
    case IE_SPARSE_OK:         return "ok";
    case IE_SPARSE_ERR_ARGS:   return "invalid arguments";
    case IE_SPARSE_ERR_OPEN:   return "failed to open file";
    case IE_SPARSE_ERR_READ:   return "failed to read file";
    case IE_SPARSE_ERR_MAGIC:  return "invalid magic or version";
    case IE_SPARSE_ERR_FORMAT: return "invalid or unsupported format";
    case IE_SPARSE_ERR_NOMEM:  return "out of memory";
    default:                   return "unknown sparse status";
  }
}
References ie_gemv_rowwise_f32_kernel(), IE_SPARSE_ERR_ARGS, IE_SPARSE_ERR_FORMAT, IE_SPARSE_ERR_MAGIC, IE_SPARSE_ERR_NOMEM, IE_SPARSE_ERR_OPEN, IE_SPARSE_ERR_READ, and IE_SPARSE_OK.
Referenced by test_block_sparse_load_missing().