Inference Engine (Clocher): engine/src/dedup/spec.c File Reference
spec.c File Reference
Implementation of the dedup spec builder and helpers.
#include "spec.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
Data Structures
struct dedup_spec_builder_s
Builder internal representation.
Functions
static int ensure_entries_cap (dedup_spec_builder_t *b, uint64_t need)
Ensure capacity for the entry array.
static int ensure_strings_cap (dedup_spec_builder_t *b, uint64_t need)
Ensure capacity for the string table.
dedup_spec_builder_t * dedup_spec_builder_create (void)
Create a new spec builder.
void dedup_spec_builder_destroy (dedup_spec_builder_t *b)
Destroy a spec builder and release memory.
uint64_t dedup_spec_builder_intern_string (dedup_spec_builder_t *b, const char *s)
Add (or reuse) a string in the builder's string table.
int dedup_spec_builder_add_entry (dedup_spec_builder_t *b, const dedup_spec_entry_t *e)
Append a spec entry.
static int write_all (FILE *f, const void *p, size_t n)
Write bytes to a stream or fail.
int dedup_spec_builder_write_file (dedup_spec_builder_t *b, const char *path, uint64_t defaults_bytes, uint64_t exceptions_bytes, uint64_t masks_bytes)
Write the spec binary file.
uint64_t dedup_fnv1a64 (const void *data, size_t n)
Compute a 64-bit FNV-1a hash for bytes (helper).
Detailed Description
Implementation of the dedup spec builder and helpers.
Definition in file spec.c.
Function Documentation
dedup_fnv1a64()
uint64_t dedup_fnv1a64 (const void * data, size_t n)
Compute a 64-bit FNV-1a hash for bytes (helper).
Parameters
data Byte pointer.
n Bytes length.
Returns
64-bit hash.
Definition at line 156 of file spec.c.
{
   const uint8_t* p = (const uint8_t*)data;
   uint64_t h = 1469598103934665603ULL;
   for (size_t i = 0; i < n; i++) {
     h ^= (uint64_t)p[i];
     h *= 1099511628211ULL;
   }
   return h;
 }
dedup_spec_builder_add_entry()
int dedup_spec_builder_add_entry (dedup_spec_builder_t * b, const dedup_spec_entry_t * e)
Append a spec entry.
Parameters
b Builder.
e Entry to append (copied by value).
Returns
0 on success, non-zero on failure.
Definition at line 98 of file spec.c.
{
   if (!b || !e) return -1;
   if (ensure_entries_cap(b, b->entry_count + 1u) != 0) return -1;
   b->entries[b->entry_count++] = *e;
   return 0;
 }
References ensure_entries_cap(), dedup_spec_builder_s::entries, and dedup_spec_builder_s::entry_count.
Referenced by main().
dedup_spec_builder_create()
dedup_spec_builder_t* dedup_spec_builder_create (void)
Create a new spec builder.
Returns
Pointer to a new builder, or NULL on allocation failure.
Definition at line 56 of file spec.c.
{
   dedup_spec_builder_t* b = (dedup_spec_builder_t*)calloc(1, sizeof(dedup_spec_builder_t));
   if (!b) return NULL;
   /* Reserve offset 0 as failure/sentinel by starting with a '\0'. */
   if (ensure_strings_cap(b, 1u) != 0) {
     free(b);
     return NULL;
   }
   b->strings[0] = '\0';
   b->strings_len = 1u;
   return b;
 }
References ensure_strings_cap(), dedup_spec_builder_s::strings, and dedup_spec_builder_s::strings_len.
Referenced by main().
dedup_spec_builder_destroy()
void dedup_spec_builder_destroy (dedup_spec_builder_t * b)
Destroy a spec builder and release memory.
Parameters
b Builder pointer (may be NULL).
Definition at line 70 of file spec.c.
{
   if (!b) return;
   free(b->entries);
   free(b->strings);
   free(b);
 }
References dedup_spec_builder_s::entries, and dedup_spec_builder_s::strings.
Referenced by main().
dedup_spec_builder_intern_string()
uint64_t dedup_spec_builder_intern_string (dedup_spec_builder_t * b, const char * s)
Add (or reuse) a string in the builder's string table.
Parameters
b Builder.
s NUL-terminated string.
Returns
Offset into the eventual string table (name_off), or 0 on failure.
Note
Offset 0 is valid if the string table starts at offset 0; however this builder uses a leading '\0' sentinel so offset 0 is reserved, and failures return 0.
Definition at line 77 of file spec.c.
{
   if (!b || !s) return 0;
   const uint64_t slen = (uint64_t)strlen(s) + 1u;
   /* Linear scan for identical string. */
   uint64_t off = 1u;
   while (off < b->strings_len) {
     const char* cur = b->strings + off;
     if (strcmp(cur, s) == 0) return off;
     off += (uint64_t)strlen(cur) + 1u;
   }
   const uint64_t need = b->strings_len + slen;
   if (ensure_strings_cap(b, need) != 0) return 0;
   const uint64_t out_off = b->strings_len;
   memcpy(b->strings + b->strings_len, s, (size_t)slen);
   b->strings_len += slen;
   return out_off;
 }
References ensure_strings_cap(), dedup_spec_builder_s::strings, and dedup_spec_builder_s::strings_len.
Referenced by main().
dedup_spec_builder_write_file()
int dedup_spec_builder_write_file (dedup_spec_builder_t * b, const char * path, uint64_t defaults_bytes, uint64_t exceptions_bytes, uint64_t masks_bytes)
Write the spec binary file.
Parameters
b Builder.
path Output path (e.g., "dedup.spec.bin").
defaults_bytes Total bytes written to defaults.bin (for header info).
exceptions_bytes Total bytes written to exceptions.bin (for header info).
masks_bytes Total bytes written to masks.bin (for header info).
Returns
0 on success, non-zero on error.
Definition at line 111 of file spec.c.
   {
   if (!b || !path) return -1;
   FILE* f = fopen(path, "wb");
   if (!f) return -1;
   dedup_spec_header_t hdr;
   memset(&hdr, 0, sizeof(hdr));
   hdr.magic[0] = (uint8_t)DEDUP_SPEC_MAGIC0;
   hdr.magic[1] = (uint8_t)DEDUP_SPEC_MAGIC1;
   hdr.magic[2] = (uint8_t)DEDUP_SPEC_MAGIC2;
   hdr.magic[3] = (uint8_t)DEDUP_SPEC_MAGIC3;
   hdr.magic[4] = (uint8_t)DEDUP_SPEC_MAGIC4;
   hdr.magic[5] = (uint8_t)DEDUP_SPEC_MAGIC5;
   hdr.magic[6] = (uint8_t)DEDUP_SPEC_MAGIC6;
   hdr.magic[7] = (uint8_t)DEDUP_SPEC_MAGIC7;
   hdr.version = DEDUP_SPEC_VERSION;
   hdr.entry_count = b->entry_count;
   hdr.entries_off = (uint64_t)sizeof(dedup_spec_header_t);
   hdr.strings_off = hdr.entries_off + b->entry_count * (uint64_t)sizeof(dedup_spec_entry_t);
   hdr.strings_bytes = b->strings_len;
   hdr.defaults_bytes = defaults_bytes;
   hdr.exceptions_bytes = exceptions_bytes;
   hdr.masks_bytes = masks_bytes;
   if (write_all(f, &hdr, sizeof(hdr)) != 0) { fclose(f); return -1; }
   if (b->entry_count) {
     if (write_all(f, b->entries, (size_t)b->entry_count * sizeof(dedup_spec_entry_t)) != 0) { fclose(f); return -1; }
   }
   if (b->strings_len) {
     if (write_all(f, b->strings, (size_t)b->strings_len) != 0) { fclose(f); return -1; }
   }
   fclose(f);
   return 0;
 }
References DEDUP_SPEC_MAGIC0, DEDUP_SPEC_MAGIC1, DEDUP_SPEC_MAGIC2, DEDUP_SPEC_MAGIC3, DEDUP_SPEC_MAGIC4, DEDUP_SPEC_MAGIC5, DEDUP_SPEC_MAGIC6, DEDUP_SPEC_MAGIC7, DEDUP_SPEC_VERSION, dedup_spec_header_s::defaults_bytes, dedup_spec_builder_s::entries, dedup_spec_header_s::entries_off, dedup_spec_header_s::entry_count, dedup_spec_builder_s::entry_count, dedup_spec_header_s::exceptions_bytes, dedup_spec_header_s::magic, dedup_spec_header_s::masks_bytes, dedup_spec_builder_s::strings, dedup_spec_header_s::strings_bytes, dedup_spec_builder_s::strings_len, dedup_spec_header_s::strings_off, dedup_spec_header_s::version, and write_all().
Referenced by main().
ensure_entries_cap()
static int ensure_entries_cap (dedup_spec_builder_t * b, uint64_t need) static
Ensure capacity for the entry array.
Definition at line 33 of file spec.c.
{
   if (need <= b->entry_cap) return 0;
   uint64_t new_cap = (b->entry_cap == 0) ? 64u : b->entry_cap;
   while (new_cap < need) new_cap *= 2u;
   dedup_spec_entry_t* p = (dedup_spec_entry_t*)realloc(b->entries, (size_t)new_cap * sizeof(dedup_spec_entry_t));
   if (!p) return -1;
   b->entries = p;
   b->entry_cap = new_cap;
   return 0;
 }
References dedup_spec_builder_s::entries, and dedup_spec_builder_s::entry_cap.
Referenced by dedup_spec_builder_add_entry().
ensure_strings_cap()
static int ensure_strings_cap (dedup_spec_builder_t * b, uint64_t need) static
Ensure capacity for the string table.
Definition at line 45 of file spec.c.
{
   if (need <= b->strings_cap) return 0;
   uint64_t new_cap = (b->strings_cap == 0) ? 4096u : b->strings_cap;
   while (new_cap < need) new_cap *= 2u;
   char* p = (char*)realloc(b->strings, (size_t)new_cap);
   if (!p) return -1;
   b->strings = p;
   b->strings_cap = new_cap;
   return 0;
 }
References dedup_spec_builder_s::strings, and dedup_spec_builder_s::strings_cap.
Referenced by dedup_spec_builder_create(), and dedup_spec_builder_intern_string().
write_all()
static int write_all (FILE * f, const void * p, size_t n) static
Write bytes to a stream or fail.
Definition at line 106 of file spec.c.
{
   if (n == 0) return 0;
   return (fwrite(p, 1, n, f) == n) ? 0 : -1;
 }
Referenced by dedup_spec_builder_write_file().