Inference Engine (Clocher): engine/include/spec.h File Reference
spec.h File Reference
Lossless deduplication specification (binary) for INT4 weight blobs.
#include <stdint.h>
#include <stddef.h>
Data Structures
struct dedup_spec_header_s
On-disk header for dedup.spec.bin.
struct dedup_spec_entry_s
A single dedup mapping entry for one tensor blob.
Macros
#define DEDUP_SPEC_VERSION 1u
Current on-disk spec version.
#define DEDUP_SPEC_MAGIC0 0x44u /* 'D' */
File magic for dedup spec ("DEDSPEC\0").
#define DEDUP_SPEC_MAGIC1 0x45u /* 'E' */
#define DEDUP_SPEC_MAGIC2 0x44u /* 'D' */
#define DEDUP_SPEC_MAGIC3 0x53u /* 'S' */
#define DEDUP_SPEC_MAGIC4 0x50u /* 'P' */
#define DEDUP_SPEC_MAGIC5 0x45u /* 'E' */
#define DEDUP_SPEC_MAGIC6 0x43u /* 'C' */
#define DEDUP_SPEC_MAGIC7 0x00u /* '\0' */
Typedefs
typedef enum dedup_payload_kind_e dedup_payload_kind_t
Kind of payload described by a tensor entry.
typedef struct dedup_spec_header_s dedup_spec_header_t
On-disk header for dedup.spec.bin.
typedef struct dedup_spec_entry_s dedup_spec_entry_t
A single dedup mapping entry for one tensor blob.
typedef struct dedup_spec_builder_s dedup_spec_builder_t
Opaque builder used by the extractor to assemble and write spec files.
Enumerations
enum dedup_payload_kind_e { DEDUP_PAYLOAD_UNKNOWN = 0 , DEDUP_PAYLOAD_INT4_BLOCKS = 1 , DEDUP_PAYLOAD_SCALES = 2 , DEDUP_PAYLOAD_OTHER = 3 }
Kind of payload described by a tensor entry.
Functions
dedup_spec_builder_t * dedup_spec_builder_create (void)
Create a new spec builder.
void dedup_spec_builder_destroy (dedup_spec_builder_t *b)
Destroy a spec builder and release memory.
uint64_t dedup_spec_builder_intern_string (dedup_spec_builder_t *b, const char *s)
Add (or reuse) a string in the builder's string table.
int dedup_spec_builder_add_entry (dedup_spec_builder_t *b, const dedup_spec_entry_t *e)
Append a spec entry.
int dedup_spec_builder_write_file (dedup_spec_builder_t *b, const char *path, uint64_t defaults_bytes, uint64_t exceptions_bytes, uint64_t masks_bytes)
Write the spec binary file.
uint64_t dedup_fnv1a64 (const void *data, size_t n)
Compute a 64-bit FNV-1a hash for bytes (helper).
Detailed Description
Lossless deduplication specification (binary) for INT4 weight blobs.
This module defines a compact, mmap-friendly "spec" format describing how to reconstruct original weight blobs from:
a shared "defaults" blob file (per group, stored once), and
per-tensor exception masks + exception data blocks (stored only for deltas).
Design goals:
Zero third-party dependencies.
Deterministic, stable binary layout (little-endian).
Runtime-friendly: reconstruction can be a tight loop over fixed-size blocks.
Lossless: every byte of the original tensor payload is reproducible.
The extractor (dedup_extract.c) produces:
dedup.spec.bin (this spec format)
dedup.defaults.bin (concatenated default blobs)
dedup.exceptions.bin (concatenated exception blocks)
dedup.masks.bin (concatenated bitset masks)
A "tensor blob" here is an opaque byte array representing the packed weights for a tensor (or sub-tensor) exactly as they appear on disk (e.g., q4 blocks, scales, etc.).
Definition in file spec.h.
Macro Definition Documentation
DEDUP_SPEC_MAGIC0
#define DEDUP_SPEC_MAGIC0 0x44u /* 'D' */
File magic for dedup spec ("DEDSPEC\0").
Definition at line 40 of file spec.h.
DEDUP_SPEC_MAGIC1
#define DEDUP_SPEC_MAGIC1 0x45u /* 'E' */
Definition at line 41 of file spec.h.
DEDUP_SPEC_MAGIC2
#define DEDUP_SPEC_MAGIC2 0x44u /* 'D' */
Definition at line 42 of file spec.h.
DEDUP_SPEC_MAGIC3
#define DEDUP_SPEC_MAGIC3 0x53u /* 'S' */
Definition at line 43 of file spec.h.
DEDUP_SPEC_MAGIC4
#define DEDUP_SPEC_MAGIC4 0x50u /* 'P' */
Definition at line 44 of file spec.h.
DEDUP_SPEC_MAGIC5
#define DEDUP_SPEC_MAGIC5 0x45u /* 'E' */
Definition at line 45 of file spec.h.
DEDUP_SPEC_MAGIC6
#define DEDUP_SPEC_MAGIC6 0x43u /* 'C' */
Definition at line 46 of file spec.h.
DEDUP_SPEC_MAGIC7
#define DEDUP_SPEC_MAGIC7 0x00u /* '\0' */
Definition at line 47 of file spec.h.
DEDUP_SPEC_VERSION
#define DEDUP_SPEC_VERSION 1u
Current on-disk spec version.
Definition at line 37 of file spec.h.
Typedef Documentation
dedup_payload_kind_t
typedef enum dedup_payload_kind_e dedup_payload_kind_t
Kind of payload described by a tensor entry.
This is deliberately generic: "blob" can represent int4 blocks, int4 scales, fp16 scales, or any other packed stream, as long as the extractor and runtime agree on interpretation and block sizing.
dedup_spec_builder_t
typedef struct dedup_spec_builder_s dedup_spec_builder_t
Opaque builder used by the extractor to assemble and write spec files.
Definition at line 1 of file spec.h.
dedup_spec_entry_t
typedef struct dedup_spec_entry_s dedup_spec_entry_t
A single dedup mapping entry for one tensor blob.
Reconstruction:
The blob is partitioned into fixed-size blocks: block_bytes.
For block i: if mask[i] == 0: copy block i from defaults at (defaults_off + i*block_bytes) else: copy block i from exceptions at exceptions_off + ex_index(i)*block_bytes
Where ex_index(i) is the number of set bits in mask[0..i-1].
Masks are stored as a packed bitset in masks.bin:
bit i corresponds to block i
LSB-first within each byte (bit0 is block 0)
Notes:
defaults_off points to a per-group default blob; multiple entries may share it.
original_* fields are informational and can be used for validation/debug.
dedup_spec_header_t
typedef struct dedup_spec_header_s dedup_spec_header_t
On-disk header for dedup.spec.bin.
All offsets are file-relative offsets into the spec file itself. All other streams (defaults/exceptions/masks) are separate files; their offsets are relative to their own file starts.
The spec file stores:
header
entry table [entry_count]
string table (NUL-terminated names)
Each entry references its name via name_off (offset into string table).
Enumeration Type Documentation
dedup_payload_kind_e
enum dedup_payload_kind_e
Kind of payload described by a tensor entry.
This is deliberately generic: "blob" can represent int4 blocks, int4 scales, fp16 scales, or any other packed stream, as long as the extractor and runtime agree on interpretation and block sizing.
Enumerator
DEDUP_PAYLOAD_UNKNOWN
DEDUP_PAYLOAD_INT4_BLOCKS
DEDUP_PAYLOAD_SCALES
DEDUP_PAYLOAD_OTHER
Definition at line 56 of file spec.h.
{
   DEDUP_PAYLOAD_UNKNOWN = 0,
   DEDUP_PAYLOAD_INT4_BLOCKS = 1,
   DEDUP_PAYLOAD_SCALES = 2,
   DEDUP_PAYLOAD_OTHER = 3
 } dedup_payload_kind_t;
Function Documentation
dedup_fnv1a64()
uint64_t dedup_fnv1a64 (const void * data, size_t n)
Compute a 64-bit FNV-1a hash for bytes (helper).
Parameters
data Byte pointer.
n Bytes length.
Returns
64-bit hash.
Definition at line 156 of file spec.c.
{
   const uint8_t* p = (const uint8_t*)data;
   uint64_t h = 1469598103934665603ULL;
   for (size_t i = 0; i < n; i++) {
     h ^= (uint64_t)p[i];
     h *= 1099511628211ULL;
   }
   return h;
 }
dedup_spec_builder_add_entry()
int dedup_spec_builder_add_entry (dedup_spec_builder_t * b, const dedup_spec_entry_t * e)
Append a spec entry.
Parameters
b Builder.
e Entry to append (copied by value).
Returns
0 on success, non-zero on failure.
Definition at line 98 of file spec.c.
{
   if (!b || !e) return -1;
   if (ensure_entries_cap(b, b->entry_count + 1u) != 0) return -1;
   b->entries[b->entry_count++] = *e;
   return 0;
 }
References ensure_entries_cap(), dedup_spec_builder_s::entries, and dedup_spec_builder_s::entry_count.
Referenced by main().
dedup_spec_builder_create()
dedup_spec_builder_t* dedup_spec_builder_create (void)
Create a new spec builder.
Returns
Pointer to a new builder, or NULL on allocation failure.
Definition at line 56 of file spec.c.
{
   dedup_spec_builder_t* b = (dedup_spec_builder_t*)calloc(1, sizeof(dedup_spec_builder_t));
   if (!b) return NULL;
   /* Reserve offset 0 as failure/sentinel by starting with a '\0'. */
   if (ensure_strings_cap(b, 1u) != 0) {
     free(b);
     return NULL;
   }
   b->strings[0] = '\0';
   b->strings_len = 1u;
   return b;
 }
References ensure_strings_cap(), dedup_spec_builder_s::strings, and dedup_spec_builder_s::strings_len.
Referenced by main().
dedup_spec_builder_destroy()
void dedup_spec_builder_destroy (dedup_spec_builder_t * b)
Destroy a spec builder and release memory.
Parameters
b Builder pointer (may be NULL).
Definition at line 70 of file spec.c.
{
   if (!b) return;
   free(b->entries);
   free(b->strings);
   free(b);
 }
References dedup_spec_builder_s::entries, and dedup_spec_builder_s::strings.
Referenced by main().
dedup_spec_builder_intern_string()
uint64_t dedup_spec_builder_intern_string (dedup_spec_builder_t * b, const char * s)
Add (or reuse) a string in the builder's string table.
Parameters
b Builder.
s NUL-terminated string.
Returns
Offset into the eventual string table (name_off), or 0 on failure.
Note
Offset 0 is valid if the string table starts at offset 0; however this builder uses a leading '\0' sentinel so offset 0 is reserved, and failures return 0.
Definition at line 77 of file spec.c.
{
   if (!b || !s) return 0;
   const uint64_t slen = (uint64_t)strlen(s) + 1u;
   /* Linear scan for identical string. */
   uint64_t off = 1u;
   while (off < b->strings_len) {
     const char* cur = b->strings + off;
     if (strcmp(cur, s) == 0) return off;
     off += (uint64_t)strlen(cur) + 1u;
   }
   const uint64_t need = b->strings_len + slen;
   if (ensure_strings_cap(b, need) != 0) return 0;
   const uint64_t out_off = b->strings_len;
   memcpy(b->strings + b->strings_len, s, (size_t)slen);
   b->strings_len += slen;
   return out_off;
 }
References ensure_strings_cap(), dedup_spec_builder_s::strings, and dedup_spec_builder_s::strings_len.
Referenced by main().
dedup_spec_builder_write_file()
int dedup_spec_builder_write_file (dedup_spec_builder_t * b, const char * path, uint64_t defaults_bytes, uint64_t exceptions_bytes, uint64_t masks_bytes)
Write the spec binary file.
Parameters
b Builder.
path Output path (e.g., "dedup.spec.bin").
defaults_bytes Total bytes written to defaults.bin (for header info).
exceptions_bytes Total bytes written to exceptions.bin (for header info).
masks_bytes Total bytes written to masks.bin (for header info).
Returns
0 on success, non-zero on error.
Definition at line 111 of file spec.c.
   {
   if (!b || !path) return -1;
   FILE* f = fopen(path, "wb");
   if (!f) return -1;
   dedup_spec_header_t hdr;
   memset(&hdr, 0, sizeof(hdr));
   hdr.magic[0] = (uint8_t)DEDUP_SPEC_MAGIC0;
   hdr.magic[1] = (uint8_t)DEDUP_SPEC_MAGIC1;
   hdr.magic[2] = (uint8_t)DEDUP_SPEC_MAGIC2;
   hdr.magic[3] = (uint8_t)DEDUP_SPEC_MAGIC3;
   hdr.magic[4] = (uint8_t)DEDUP_SPEC_MAGIC4;
   hdr.magic[5] = (uint8_t)DEDUP_SPEC_MAGIC5;
   hdr.magic[6] = (uint8_t)DEDUP_SPEC_MAGIC6;
   hdr.magic[7] = (uint8_t)DEDUP_SPEC_MAGIC7;
   hdr.version = DEDUP_SPEC_VERSION;
   hdr.entry_count = b->entry_count;
   hdr.entries_off = (uint64_t)sizeof(dedup_spec_header_t);
   hdr.strings_off = hdr.entries_off + b->entry_count * (uint64_t)sizeof(dedup_spec_entry_t);
   hdr.strings_bytes = b->strings_len;
   hdr.defaults_bytes = defaults_bytes;
   hdr.exceptions_bytes = exceptions_bytes;
   hdr.masks_bytes = masks_bytes;
   if (write_all(f, &hdr, sizeof(hdr)) != 0) { fclose(f); return -1; }
   if (b->entry_count) {
     if (write_all(f, b->entries, (size_t)b->entry_count * sizeof(dedup_spec_entry_t)) != 0) { fclose(f); return -1; }
   }
   if (b->strings_len) {
     if (write_all(f, b->strings, (size_t)b->strings_len) != 0) { fclose(f); return -1; }
   }
   fclose(f);
   return 0;
 }
References DEDUP_SPEC_MAGIC0, DEDUP_SPEC_MAGIC1, DEDUP_SPEC_MAGIC2, DEDUP_SPEC_MAGIC3, DEDUP_SPEC_MAGIC4, DEDUP_SPEC_MAGIC5, DEDUP_SPEC_MAGIC6, DEDUP_SPEC_MAGIC7, DEDUP_SPEC_VERSION, dedup_spec_header_s::defaults_bytes, dedup_spec_builder_s::entries, dedup_spec_header_s::entries_off, dedup_spec_header_s::entry_count, dedup_spec_builder_s::entry_count, dedup_spec_header_s::exceptions_bytes, dedup_spec_header_s::magic, dedup_spec_header_s::masks_bytes, dedup_spec_builder_s::strings, dedup_spec_header_s::strings_bytes, dedup_spec_builder_s::strings_len, dedup_spec_header_s::strings_off, dedup_spec_header_s::version, and write_all().
Referenced by main().