Inference Engine (Clocher): engine/src/opt/stream.c File Reference
stream.c File Reference
#include "ie_stream.h"
#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define _POSIX_C_SOURCE 200809L
#define IE_X86 0
Functions
static size_t ie_read_cache_size_file (const char *path)
Parse a sysfs cache size file containing values like "32K\n" or "12M\n".
static void ie_detect_caches_linux (size_t *l1, size_t *l2, size_t *l3)
Best-effort cache discovery on Linux sysfs.
static double ie_clamp01 (double x)
Clamp a double to [0.0, 1.0].
int ie_stream_policy_init (struct ie_stream_policy *p)
Initialize an ie_stream_policy with detected cache sizes and defaults.
bool ie_stream_should_use_nt (size_t bytes, const struct ie_stream_policy *p)
Decide whether a memory operation of bytes should use non-temporal stores.
size_t ie_stream_recommend_prefetch_distance (const struct ie_stream_policy *p, size_t stride_bytes)
Recommend a prefetch lead distance for a given stride.
void ie_stream_prefetch_t0 (const void *base, size_t distance)
Issue a temporal (T0) prefetch at base+distance (best-effort).
void ie_stream_prefetch_nta (const void *base, size_t distance)
Issue a non-temporal (NTA) prefetch at base+distance (best-effort).
void ie_stream_prefetch_range_t0 (const void *base, size_t bytes, size_t stride, size_t distance)
Prefetch a range with temporal (T0) hint.
void ie_stream_prefetch_range_nta (const void *base, size_t bytes, size_t stride, size_t distance)
Prefetch a range with non-temporal (NTA) hint.
static void ie_scalar_copy_f32 (float *dst, const float *src, size_t n)
Scalar copy fallback for float arrays.
static void ie_scalar_set_f32 (float *dst, float v, size_t n)
Scalar set fallback for float arrays.
static void ie_nt_copy_f32_avx512 (float *dst, const float *src, size_t n)
Streaming store copy using AVX-512F (compile-time gated).
static void ie_nt_copy_f32_avx2 (float *dst, const float *src, size_t n)
Streaming store copy using AVX2 (compile-time gated).
static void ie_nt_set_f32_avx512 (float *dst, float value, size_t n)
Streaming store set using AVX-512F (compile-time gated).
static void ie_nt_set_f32_avx2 (float *dst, float value, size_t n)
Streaming store set using AVX2 (compile-time gated).
void ie_stream_copy_f32 (float *dst, const float *src, size_t n, const struct ie_stream_policy *p, double nt_ratio)
Copy a float array, optionally using non-temporal stores.
void ie_stream_memset_f32 (float *dst, float value, size_t n, const struct ie_stream_policy *p, double nt_ratio)
Set a float array, optionally using non-temporal stores.
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 22 of file stream.c.
IE_X86
#define IE_X86 0
Definition at line 37 of file stream.c.
Function Documentation
ie_clamp01()
static double ie_clamp01 (double x) static
Clamp a double to [0.0, 1.0].
Parameters
x Input value.
Returns
Clamped value in [0,1].
Definition at line 131 of file stream.c.
{
   if (x < 0.0) return 0.0;
   if (x > 1.0) return 1.0;
   return x;
 }
Referenced by ie_stream_copy_f32(), and ie_stream_memset_f32().
ie_detect_caches_linux()
static void ie_detect_caches_linux (size_t * l1, size_t * l2, size_t * l3) static
Best-effort cache discovery on Linux sysfs.
Vendor sysfs layouts vary; we read a small fixed set of potential index paths and rank the discovered sizes. The mapping "largest => L3, second => L2, third => L1" is a rough approximation but works reasonably well for tuning thresholds without hard dependencies.
If nothing is found, outputs remain zero.
Parameters
l1 Out: L1D size in bytes (best-effort).
l2 Out: L2 size in bytes (best-effort).
l3 Out: L3/LLC size in bytes (best-effort).
Definition at line 93 of file stream.c.
{
   if (l1) *l1 = 0;
   if (l2) *l2 = 0;
   if (l3) *l3 = 0;
   const char *paths[] = {
     "/sys/devices/system/cpu/cpu0/cache/index0/size",
     "/sys/devices/system/cpu/cpu0/cache/index1/size",
     "/sys/devices/system/cpu/cpu0/cache/index2/size",
     "/sys/devices/system/cpu/cpu0/cache/index3/size",
     "/sys/devices/system/cpu/cpu0/cache/index4/size",
   };
   size_t found[5] = {0};
   for (int i = 0; i < 5; ++i) found[i] = ie_read_cache_size_file(paths[i]);
   /* Sort descending (N=5 selection sort). */
   for (int i = 0; i < 5; ++i) {
     for (int j = i + 1; j < 5; ++j) {
       if (found[j] > found[i]) {
         size_t t = found[i];
         found[i] = found[j];
         found[j] = t;
       }
     }
   }
   if (l3) *l3 = found[0];
   if (l2) *l2 = found[1];
   if (l1) *l1 = found[2];
 }
References ie_read_cache_size_file().
Referenced by ie_stream_policy_init().
ie_nt_copy_f32_avx2()
static void ie_nt_copy_f32_avx2 (float * dst, const float * src, size_t n) static
Streaming store copy using AVX2 (compile-time gated).
Uses _mm256_stream_ps for aligned streaming stores when available. Falls back to scalar behavior when AVX2 is not enabled.
Parameters
dst Destination float array.
src Source float array.
n Number of float elements.
Definition at line 420 of file stream.c.
{
 #if IE_X86 && defined(__AVX2__)
   size_t i = 0;
   /* Align to 32B for 256-bit streams. */
   uintptr_t addr = (uintptr_t)dst;
   size_t mis = (size_t)(addr & (32u - 1u));
   if (mis) {
     size_t pro = (32u - mis) / sizeof(float);
     if (pro > n) pro = n;
     ie_scalar_copy_f32(dst, src, pro);
     dst += pro;
     src += pro;
     n -= pro;
   }
   for (; i + 8 <= n; i += 8) {
     __m256 v = _mm256_loadu_ps(src + i);
     _mm256_stream_ps(dst + i, v);
   }
   ie_scalar_copy_f32(dst + i, src + i, n - i);
 #else
   (void)dst;
   (void)src;
   (void)n;
 #endif
 }
References ie_scalar_copy_f32().
Referenced by ie_stream_copy_f32().
ie_nt_copy_f32_avx512()
static void ie_nt_copy_f32_avx512 (float * dst, const float * src, size_t n) static
Streaming store copy using AVX-512F (compile-time gated).
Uses _mm512_stream_ps for aligned streaming stores when available. Falls back to scalar behavior when AVX-512F is not enabled.
Parameters
dst Destination float array.
src Source float array.
n Number of float elements.
Definition at line 381 of file stream.c.
{
 #if IE_X86 && defined(__AVX512F__)
   size_t i = 0;
   /* Prologue until destination aligns to 64B (best for 512-bit streams). */
   uintptr_t addr = (uintptr_t)dst;
   size_t mis = (size_t)(addr & (64u - 1u));
   if (mis) {
     size_t pro = (64u - mis) / sizeof(float);
     if (pro > n) pro = n;
     ie_scalar_copy_f32(dst, src, pro);
     dst += pro;
     src += pro;
     n -= pro;
   }
   for (; i + 16 <= n; i += 16) {
     __m512 v = _mm512_loadu_ps(src + i);
     _mm512_stream_ps(dst + i, v);
   }
   ie_scalar_copy_f32(dst + i, src + i, n - i);
 #else
   (void)dst;
   (void)src;
   (void)n;
 #endif
 }
References ie_scalar_copy_f32().
Referenced by ie_stream_copy_f32().
ie_nt_set_f32_avx2()
static void ie_nt_set_f32_avx2 (float * dst, float value, size_t n) static
Streaming store set using AVX2 (compile-time gated).
Uses _mm256_stream_ps for aligned streaming stores when available. Falls back to scalar behavior when AVX2 is not enabled.
Parameters
dst Destination float array.
value Value to write.
n Number of float elements.
Definition at line 494 of file stream.c.
{
 #if IE_X86 && defined(__AVX2__)
   size_t i = 0;
   uintptr_t addr = (uintptr_t)dst;
   size_t mis = (size_t)(addr & (32u - 1u));
   if (mis) {
     size_t pro = (32u - mis) / sizeof(float);
     if (pro > n) pro = n;
     ie_scalar_set_f32(dst, value, pro);
     dst += pro;
     n -= pro;
   }
   __m256 v = _mm256_set1_ps(value);
   for (; i + 8 <= n; i += 8) _mm256_stream_ps(dst + i, v);
   ie_scalar_set_f32(dst + i, value, n - i);
 #else
   (void)dst;
   (void)value;
   (void)n;
 #endif
 }
References ie_scalar_set_f32().
Referenced by ie_stream_memset_f32().
ie_nt_set_f32_avx512()
static void ie_nt_set_f32_avx512 (float * dst, float value, size_t n) static
Streaming store set using AVX-512F (compile-time gated).
Uses _mm512_stream_ps for aligned streaming stores when available. Falls back to scalar behavior when AVX-512F is not enabled.
Parameters
dst Destination float array.
value Value to write.
n Number of float elements.
Definition at line 459 of file stream.c.
{
 #if IE_X86 && defined(__AVX512F__)
   size_t i = 0;
   uintptr_t addr = (uintptr_t)dst;
   size_t mis = (size_t)(addr & (64u - 1u));
   if (mis) {
     size_t pro = (64u - mis) / sizeof(float);
     if (pro > n) pro = n;
     ie_scalar_set_f32(dst, value, pro);
     dst += pro;
     n -= pro;
   }
   __m512 v = _mm512_set1_ps(value);
   for (; i + 16 <= n; i += 16) _mm512_stream_ps(dst + i, v);
   ie_scalar_set_f32(dst + i, value, n - i);
 #else
   (void)dst;
   (void)value;
   (void)n;
 #endif
 }
References ie_scalar_set_f32().
Referenced by ie_stream_memset_f32().
ie_read_cache_size_file()
static size_t ie_read_cache_size_file (const char * path) static
Parse a sysfs cache size file containing values like "32K\n" or "12M\n".
Sysfs cache size strings commonly encode units as K/M. This helper parses the numeric prefix and optional unit suffix, returning bytes.
If the file cannot be opened/read or parsing fails, returns 0.
Parameters
path NUL-terminated file path.
Returns
Cache size in bytes (>=0), or 0 if unavailable/unreadable.
Definition at line 54 of file stream.c.
{
   FILE *f = fopen(path, "r");
   if (!f) return 0;
   char buf[64] = {0};
   if (!fgets(buf, sizeof buf, f)) {
     fclose(f);
     return 0;
   }
   fclose(f);
   char *p = buf;
   while (*p && (*p == ' ' || *p == '\t')) p++;
   long long v = 0;
   char unit = 0;
   if (sscanf(p, "%lld%c", &v, &unit) < 1) return 0;
   if (v <= 0) return 0;
   if (unit == 'M' || unit == 'm') return (size_t)v * 1024ull * 1024ull;
   if (unit == 'K' || unit == 'k') return (size_t)v * 1024ull;
   return (size_t)v;
 }
Referenced by ie_detect_caches_linux().
ie_scalar_copy_f32()
static void ie_scalar_copy_f32 (float * dst, const float * src, size_t n) inline static
Scalar copy fallback for float arrays.
Parameters
dst Destination float array.
src Source float array.
n Number of float elements.
Definition at line 355 of file stream.c.
{
   for (size_t i = 0; i < n; ++i) dst[i] = src[i];
 }
Referenced by ie_nt_copy_f32_avx2(), ie_nt_copy_f32_avx512(), and ie_stream_copy_f32().
ie_scalar_set_f32()
static void ie_scalar_set_f32 (float * dst, float v, size_t n) inline static
Scalar set fallback for float arrays.
Parameters
dst Destination float array.
v Value to write.
n Number of float elements.
Definition at line 366 of file stream.c.
{
   for (size_t i = 0; i < n; ++i) dst[i] = v;
 }
Referenced by ie_nt_set_f32_avx2(), ie_nt_set_f32_avx512(), and ie_stream_memset_f32().
ie_stream_copy_f32()
void ie_stream_copy_f32 (float * dst, const float * src, size_t n, const struct ie_stream_policy * p, double nt_ratio)
Copy a float array, optionally using non-temporal stores.
Copy n floats from src to dst using optional non-temporal stores.
The function uses policy thresholds plus nt_ratio to decide whether to use non-temporal streaming stores. If nt_ratio is 0, the function forces a scalar copy even if the policy would otherwise stream.
Parameters
dst Destination float array.
src Source float array.
n Number of float elements.
p Stream policy (must be non-NULL).
nt_ratio Ratio in [0,1]; 0 disables NT, >0 enables if policy allows.
Definition at line 534 of file stream.c.
{
   if (!dst || !src || !p) return;
   const size_t bytes = n * sizeof(float);
   const bool want_nt =
       ie_stream_should_use_nt(bytes, p) && (ie_clamp01(nt_ratio) > 0.0);
   if (!want_nt) {
     ie_scalar_copy_f32(dst, src, n);
     return;
   }
 #if IE_X86 && defined(__AVX512F__)
   ie_nt_copy_f32_avx512(dst, src, n);
 #elif IE_X86 && defined(__AVX2__)
   ie_nt_copy_f32_avx2(dst, src, n);
 #else
   ie_scalar_copy_f32(dst, src, n);
 #endif
 }
References ie_clamp01(), ie_nt_copy_f32_avx2(), ie_nt_copy_f32_avx512(), ie_scalar_copy_f32(), and ie_stream_should_use_nt().
Referenced by main().
ie_stream_memset_f32()
void ie_stream_memset_f32 (float * dst, float value, size_t n, const struct ie_stream_policy * p, double nt_ratio)
Set a float array, optionally using non-temporal stores.
Set n floats at dst to value using optional non-temporal stores.
The function uses policy thresholds plus nt_ratio to decide whether to use non-temporal streaming stores. If nt_ratio is 0, the function forces a scalar set even if the policy would otherwise stream.
Parameters
dst Destination float array.
value Value to write.
n Number of float elements.
p Stream policy (must be non-NULL).
nt_ratio Ratio in [0,1]; 0 disables NT, >0 enables if policy allows.
Definition at line 570 of file stream.c.
{
   if (!dst || !p) return;
   const size_t bytes = n * sizeof(float);
   const bool want_nt =
       ie_stream_should_use_nt(bytes, p) && (ie_clamp01(nt_ratio) > 0.0);
   if (!want_nt) {
     ie_scalar_set_f32(dst, value, n);
     return;
   }
 #if IE_X86 && defined(__AVX512F__)
   ie_nt_set_f32_avx512(dst, value, n);
 #elif IE_X86 && defined(__AVX2__)
   ie_nt_set_f32_avx2(dst, value, n);
 #else
   ie_scalar_set_f32(dst, value, n);
 #endif
 }
References ie_clamp01(), ie_nt_set_f32_avx2(), ie_nt_set_f32_avx512(), ie_scalar_set_f32(), and ie_stream_should_use_nt().
ie_stream_policy_init()
int ie_stream_policy_init (struct ie_stream_policy * p)
Initialize an ie_stream_policy with detected cache sizes and defaults.
Initialize policy with detected cache sizes and sane defaults.
Cache detection is best-effort (Linux sysfs). If detection fails, conservative defaults are used:
L1D: 32 KiB
L2: 1 MiB
L3: 8 MiB
Defaults:
prefetch_distance: 6 cache lines
nt_threshold_bytes: 2x LLC
Env overrides:
IE_STREAM_PREFETCH
IE_STREAM_NT_THRESHOLD
IE_STREAM_FORCE_NT
Parameters
p Output policy to initialize.
Returns
0 on success, or -EINVAL on invalid arguments.
Definition at line 161 of file stream.c.
{
   if (!p) return -EINVAL;
   memset(p, 0, sizeof *p);
   size_t l1 = 0, l2 = 0, l3 = 0;
   ie_detect_caches_linux(&l1, &l2, &l3);
   p->l1_bytes = l1;
   p->l2_bytes = l2;
   p->l3_bytes = l3;
   if (p->l1_bytes == 0) p->l1_bytes = 32u * 1024u;
   if (p->l2_bytes == 0) p->l2_bytes = 1u * 1024u * 1024u;
   if (p->l3_bytes == 0) p->l3_bytes = 8u * 1024u * 1024u;
   p->prefetch_distance = 6u * IE_CACHELINE_BYTES;
   p->nt_threshold_bytes = 2u * p->l3_bytes;
   p->prefetch_hint = 0;
   p->enable_prefetch = true;
   p->force_nt_on = false;
   p->force_nt_off = false;
   const char *s = NULL;
   s = getenv("IE_STREAM_PREFETCH");
   if (s && *s) {
     size_t v = (size_t)strtoull(s, NULL, 10);
     if (v > 0) p->prefetch_distance = v;
   }
   s = getenv("IE_STREAM_NT_THRESHOLD");
   if (s && *s) {
     size_t v = (size_t)strtoull(s, NULL, 10);
     if (v > 0) p->nt_threshold_bytes = v;
   }
   /* IE_STREAM_FORCE_NT:
    *  - "1" => always use non-temporal stores
    *  - "0" => never use non-temporal stores
    *  - otherwise => ignore (keep heuristic)
    */
   s = getenv("IE_STREAM_FORCE_NT");
   if (s && *s) {
     int v = atoi(s);
     if (v == 1) {
       p->force_nt_on = true;
       p->force_nt_off = false;
     } else if (v == 0) {
       p->force_nt_on = false;
       p->force_nt_off = true;
     }
   }
   return 0;
 }
References ie_stream_policy::enable_prefetch, ie_stream_policy::force_nt_off, ie_stream_policy::force_nt_on, IE_CACHELINE_BYTES, ie_detect_caches_linux(), ie_stream_policy::l1_bytes, ie_stream_policy::l2_bytes, ie_stream_policy::l3_bytes, ie_stream_policy::nt_threshold_bytes, ie_stream_policy::prefetch_distance, and ie_stream_policy::prefetch_hint.
Referenced by main().
ie_stream_prefetch_nta()
void ie_stream_prefetch_nta (const void * base, size_t distance)
Issue a non-temporal (NTA) prefetch at base+distance (best-effort).
Issue a non-temporal (NTA) prefetch distance bytes ahead of base.
On non-x86 builds this function is a no-op.
Parameters
base Base pointer.
distance Byte offset from base to prefetch.
Definition at line 295 of file stream.c.
{
   const char *p = (const char *)base + distance;
 #if IE_X86
   _mm_prefetch(p, _MM_HINT_NTA);
 #else
   (void)p;
 #endif
 }
Referenced by ie_stream_prefetch_range_nta().
ie_stream_prefetch_range_nta()
void ie_stream_prefetch_range_nta (const void * base, size_t bytes, size_t stride, size_t distance)
Prefetch a range with non-temporal (NTA) hint.
Prefetch a range using NTA hint at a given stride and lead distance.
Walks the byte range [base, base+bytes) and issues prefetches at (current + distance), stepping by stride (or cacheline if stride==0).
Parameters
base Base pointer of the range.
bytes Number of bytes to cover.
stride Step size in bytes (0 => cacheline).
distance Prefetch lead distance in bytes.
Definition at line 337 of file stream.c.
{
   const char *c = (const char *)base;
   size_t step = (stride > 0 ? stride : IE_CACHELINE_BYTES);
   for (size_t off = 0; off < bytes; off += step) {
     ie_stream_prefetch_nta(c + off, distance);
   }
 }
References IE_CACHELINE_BYTES, and ie_stream_prefetch_nta().
ie_stream_prefetch_range_t0()
void ie_stream_prefetch_range_t0 (const void * base, size_t bytes, size_t stride, size_t distance)
Prefetch a range with temporal (T0) hint.
Prefetch a range using T0 hint at a given stride and lead distance.
Walks the byte range [base, base+bytes) and issues prefetches at (current + distance), stepping by stride (or cacheline if stride==0).
Parameters
base Base pointer of the range.
bytes Number of bytes to cover.
stride Step size in bytes (0 => cacheline).
distance Prefetch lead distance in bytes.
Definition at line 316 of file stream.c.
{
   const char *c = (const char *)base;
   size_t step = (stride > 0 ? stride : IE_CACHELINE_BYTES);
   for (size_t off = 0; off < bytes; off += step) {
     ie_stream_prefetch_t0(c + off, distance);
   }
 }
References IE_CACHELINE_BYTES, and ie_stream_prefetch_t0().
Referenced by main().
ie_stream_prefetch_t0()
void ie_stream_prefetch_t0 (const void * base, size_t distance)
Issue a temporal (T0) prefetch at base+distance (best-effort).
Issue a T0 (cache-hot) prefetch distance bytes ahead of base.
On non-x86 builds this function is a no-op.
Parameters
base Base pointer.
distance Byte offset from base to prefetch.
Definition at line 277 of file stream.c.
{
   const char *p = (const char *)base + distance;
 #if IE_X86
   _mm_prefetch(p, _MM_HINT_T0);
 #else
   (void)p;
 #endif
 }
Referenced by ie_stream_prefetch_range_t0().
ie_stream_recommend_prefetch_distance()
size_t ie_stream_recommend_prefetch_distance (const struct ie_stream_policy * p, size_t stride_bytes)
Recommend a prefetch lead distance for a given stride.
Recommend a prefetch distance in bytes for the given stride.
This clamps the configured distance to a practical range:
at least one cache line,
at most half of L1,
at least stride_bytes when stride_bytes is provided.
Parameters
p Policy (may be NULL).
stride_bytes Access stride in bytes (0 => assume cacheline stride).
Returns
Recommended prefetch lead distance in bytes.
Definition at line 251 of file stream.c.
{
   if (!p) return 4u * IE_CACHELINE_BYTES;
   size_t lead = p->prefetch_distance ? p->prefetch_distance
                                      : (6u * IE_CACHELINE_BYTES);
   if (lead < IE_CACHELINE_BYTES) lead = IE_CACHELINE_BYTES;
   if (lead > p->l1_bytes / 2u) lead = p->l1_bytes / 2u;
   if (stride_bytes > 0 && lead < stride_bytes) lead = stride_bytes;
   return lead;
 }
References IE_CACHELINE_BYTES, ie_stream_policy::l1_bytes, and ie_stream_policy::prefetch_distance.
ie_stream_should_use_nt()
bool ie_stream_should_use_nt (size_t bytes, const struct ie_stream_policy * p)
Decide whether a memory operation of bytes should use non-temporal stores.
Decide if non-temporal stores should be used for a given transfer size.
The decision uses the policy threshold unless forced on/off via IE_STREAM_FORCE_NT.
Parameters
bytes Size of the memory operation in bytes.
p Policy (must be non-NULL).
Returns
true if non-temporal stores are recommended, else false.
Definition at line 231 of file stream.c.
{
   if (!p) return false;
   if (p->force_nt_on) return true;
   if (p->force_nt_off) return false;
   return bytes >= p->nt_threshold_bytes;
 }
References ie_stream_policy::force_nt_off, ie_stream_policy::force_nt_on, and ie_stream_policy::nt_threshold_bytes.
Referenced by ie_stream_copy_f32(), and ie_stream_memset_f32().