Inference Engine (Clocher): ie_device_vtbl Struct Reference
ie_device_vtbl Struct Reference
Virtual method table for a device backend.
Data Fields
int(* caps)(const void *self, ie_device_caps_t *out)
int(* gemv_f32)(void *self, const float *W, const float *x, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k)
int(* gemv_q4_0_f32)(void *self, const uint8_t *w_q4, const uint8_t *w_scales, size_t scale_bytes, const float *x, float *y, size_t rows, size_t cols, const uint16_t *bias_bf16)
int(* memcpy)(void *self, void *dst, const void *src, size_t nbytes)
int(* gemv_block_sparse_f32)(void *self, const ie_block_sparse_matrix_t *m, const float *x, float *y, const float *bias)
void(* destroy)(void *self)
Detailed Description
Virtual method table for a device backend.
Definition at line 34 of file ie_device_common.c.
Field Documentation
caps
int(* ie_device_vtbl::caps) (const void *self, ie_device_caps_t *out)
Definition at line 35 of file ie_device_common.c.
Referenced by cuda_try_create(), ie_device_caps(), ie_device_create(), and ze_try_create().
destroy
void(* ie_device_vtbl::destroy) (void *self)
Definition at line 53 of file ie_device_common.c.
Referenced by cuda_try_create(), ie_device_create(), ie_device_destroy(), and ze_try_create().
gemv_block_sparse_f32
int(* ie_device_vtbl::gemv_block_sparse_f32) (void *self, const ie_block_sparse_matrix_t *m, const float *x, float *y, const float *bias)
Definition at line 48 of file ie_device_common.c.
Referenced by cuda_try_create(), ie_device_create(), ie_device_gemv_block_sparse_f32(), and ze_try_create().
gemv_f32
int(* ie_device_vtbl::gemv_f32) (void *self, const float *W, const float *x, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k)
Definition at line 36 of file ie_device_common.c.
Referenced by cuda_try_create(), ie_device_create(), ie_device_gemv_f32(), and ze_try_create().
gemv_q4_0_f32
int(* ie_device_vtbl::gemv_q4_0_f32) (void *self, const uint8_t *w_q4, const uint8_t *w_scales, size_t scale_bytes, const float *x, float *y, size_t rows, size_t cols, const uint16_t *bias_bf16)
Definition at line 38 of file ie_device_common.c.
Referenced by cuda_try_create(), ie_device_create(), ie_device_gemv_q4_0_f32(), and ze_try_create().
memcpy
int(* ie_device_vtbl::memcpy) (void *self, void *dst, const void *src, size_t nbytes)
Definition at line 47 of file ie_device_common.c.
Referenced by cuda_try_create(), ie_device_create(), ie_device_memcpy(), and ze_try_create().
The documentation for this struct was generated from the following file:
engine/src/devices/ie_device_common.c