Inference Engine (Clocher): engine/include/tensor_map.h File Reference
tensor_map.h File Reference
Loader and lookup API for tensor_map.json.
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
Data Structures
struct tensor_desc_s
Tensor descriptor resolved from tensor_map.json.
struct tensor_map_s
In-memory tensor map.
Typedefs
typedef enum tensor_dtype_e tensor_dtype_t
Tensor data type tag.
typedef struct tensor_desc_s tensor_desc_t
Tensor descriptor resolved from tensor_map.json.
typedef struct tensor_map_s tensor_map_t
In-memory tensor map.
Enumerations
enum tensor_dtype_e {
TENSOR_DTYPE_F32 = 0 , TENSOR_DTYPE_F16 = 1 , TENSOR_DTYPE_INT4 = 2 , TENSOR_DTYPE_BF16 = 3 ,
TENSOR_DTYPE_U8 = 4 , TENSOR_DTYPE_UNKNOWN = 255
}
Tensor data type tag.
Functions
static size_t tensor_dtype_size_bytes (tensor_dtype_t dt)
Return the byte size for a dtype when representable as plain elements.
static const char * tensor_dtype_name (tensor_dtype_t dt)
Convert dtype tag to a stable human-readable name.
static int tensor_shape_to_string (const uint32_t *shape, uint32_t ndim, char *out, size_t outsz)
Format a shape into a compact string like "[a,b,c]".
static int tensor_desc_to_string (const tensor_desc_t *td, char *out, size_t outsz)
Format a tensor descriptor into a compact debug string.
int tensor_map_load (const char *path, tensor_map_t *out)
Load tensor_map.json from disk.
void tensor_map_free (tensor_map_t *map)
Free tensor map and all owned memory.
const tensor_desc_t * tensor_map_find (const tensor_map_t *map, const char *name)
Find a tensor descriptor by exact name.
int tensor_map_validate_against_bin (const tensor_map_t *map, size_t bin_size, char *err, size_t errsz)
Validate a loaded tensor map against a mapped weights binary.
Detailed Description
Loader and lookup API for tensor_map.json.
tensor_map.json describes how logical tensor names map to byte offsets, shapes, and dtypes inside model.ie.bin.
Supported input shapes:
Array style: { "tensors": [ { "name": "...", "offset": ..., ... }, ... ] }
Direct array: [ { "name": "...", ... }, ... ]
Map style: { "tensor.name": { "offset": ..., ... }, ... }
Logging philosophy:
The map container is "data-only"; it does not print by itself.
Callers should log failures with tensor_desc_t using the helper formatters provided below (dtype name, shape string, and a compact debug string).
Definition in file tensor_map.h.
Typedef Documentation
tensor_desc_t
typedef struct tensor_desc_s tensor_desc_t
Tensor descriptor resolved from tensor_map.json.
tensor_dtype_t
typedef enum tensor_dtype_e tensor_dtype_t
Tensor data type tag.
Note
tensor_map.json may omit dtype; loaders may leave dtype as TENSOR_DTYPE_UNKNOWN. Callers must not assume dtype is populated unless their loader guarantees it.
tensor_map_t
typedef struct tensor_map_s tensor_map_t
In-memory tensor map.
The loader owns all memory referenced by tensor_desc_t entries.
Enumeration Type Documentation
tensor_dtype_e
enum tensor_dtype_e
Tensor data type tag.
Note
tensor_map.json may omit dtype; loaders may leave dtype as TENSOR_DTYPE_UNKNOWN. Callers must not assume dtype is populated unless their loader guarantees it.
Enumerator
TENSOR_DTYPE_F32
TENSOR_DTYPE_F16
TENSOR_DTYPE_INT4
TENSOR_DTYPE_BF16
TENSOR_DTYPE_U8
TENSOR_DTYPE_UNKNOWN
Definition at line 46 of file tensor_map.h.
{
  TENSOR_DTYPE_F32 = 0,
  TENSOR_DTYPE_F16 = 1,
  TENSOR_DTYPE_INT4 = 2,
  TENSOR_DTYPE_BF16 = 3,
  TENSOR_DTYPE_U8 = 4,
  TENSOR_DTYPE_UNKNOWN = 255
} tensor_dtype_t;
Function Documentation
tensor_desc_to_string()
static int tensor_desc_to_string (const tensor_desc_t * td, char * out, size_t outsz) inline static
Format a tensor descriptor into a compact debug string.
Format: "name=... off=... bytes=... dtype=... shape=[...]"
Parameters
td Tensor descriptor (may be NULL).
out Output buffer.
outsz Output buffer size.
Returns
Number of bytes written (excluding NUL) on success, or -1 on error.
Definition at line 189 of file tensor_map.h.
{
  if (!out || outsz == 0u) return -1;
  out[0] = '\0';
  if (!td) {
    int n0 = snprintf(out, outsz, "<null tensor_desc>");
    return (n0 < 0 || (size_t)n0 >= outsz) ? -1 : n0;
  }
  char shape_buf[128];
  if (tensor_shape_to_string(td->shape, td->ndim, shape_buf, sizeof(shape_buf)) < 0) {
    snprintf(shape_buf, sizeof(shape_buf), "[?]");
  }
  int n = snprintf(out, outsz,
                   "name=%s off=%llu bytes=%llu dtype=%s shape=%s",
                   (td->name ? td->name : "<null>"),
                   (unsigned long long)td->offset,
                   (unsigned long long)td->size_bytes,
                   tensor_dtype_name(td->dtype),
                   shape_buf);
  return (n < 0 || (size_t)n >= outsz) ? -1 : n;
}
References tensor_desc_s::dtype, tensor_desc_s::name, tensor_desc_s::ndim, tensor_desc_s::offset, tensor_desc_s::shape, tensor_desc_s::size_bytes, tensor_dtype_name(), and tensor_shape_to_string().
Referenced by ie_require_size_eq(), ie_resolve_moe_layer(), ie_w_get_first_view(), ie_w_get_layer_fmt_view(), and tensor_map_validate_against_bin().
tensor_dtype_name()
static const char * tensor_dtype_name (tensor_dtype_t dt) inline static
Convert dtype tag to a stable human-readable name.
Parameters
dt Dtype tag.
Returns
Constant string name.
Definition at line 78 of file tensor_map.h.
{
  switch (dt) {
    case TENSOR_DTYPE_F32: return "f32";
    case TENSOR_DTYPE_F16: return "f16";
    case TENSOR_DTYPE_INT4: return "int4";
    case TENSOR_DTYPE_BF16: return "bf16";
    case TENSOR_DTYPE_U8:  return "u8";
    default: return "unknown";
  }
}
References TENSOR_DTYPE_BF16, TENSOR_DTYPE_F16, TENSOR_DTYPE_F32, TENSOR_DTYPE_INT4, and TENSOR_DTYPE_U8.
Referenced by tensor_desc_to_string().
tensor_dtype_size_bytes()
static size_t tensor_dtype_size_bytes (tensor_dtype_t dt) inline static
Return the byte size for a dtype when representable as plain elements.
Parameters
dt Dtype tag.
Returns
Element size in bytes for dense element types; 0 for packed/unknown.
Definition at line 61 of file tensor_map.h.
{
  switch (dt) {
    case TENSOR_DTYPE_F32: return 4u;
    case TENSOR_DTYPE_F16: return 2u;
    case TENSOR_DTYPE_BF16: return 2u;
    case TENSOR_DTYPE_U8:  return 1u;
    case TENSOR_DTYPE_INT4: return 0u; /* packed, size is tensor-specific */
    default: return 0u;
  }
}
References TENSOR_DTYPE_BF16, TENSOR_DTYPE_F16, TENSOR_DTYPE_F32, TENSOR_DTYPE_INT4, and TENSOR_DTYPE_U8.
tensor_map_find()
const tensor_desc_t * tensor_map_find (const tensor_map_t * map, const char * name)
Find a tensor descriptor by exact name.
Parameters
map Loaded tensor map.
name Tensor name.
Returns
Pointer to descriptor, or NULL if not found.
Definition at line 662 of file tensor_map.c.
{
  if (!map || !map->loaded || !name) return NULL;
  for (uint32_t i = 0; i < map->count; ++i) {
    if (map->tensors[i].name && strcmp(map->tensors[i].name, name) == 0)
      return &map->tensors[i];
  }
  return NULL;
}
References tensor_map_s::count, tensor_map_s::loaded, tensor_desc_s::name, and tensor_map_s::tensors.
Referenced by ie_w_find(), maybe_correct_head_dim_(), widx_detect_arch(), widx_find_any(), widx_resolve_layer_llama(), and widx_resolve_layer_neox().
tensor_map_free()
void tensor_map_free (tensor_map_t * map)
Free tensor map and all owned memory.
Parameters
map Tensor map (may be NULL).
Definition at line 650 of file tensor_map.c.
{
  if (!map || !map->tensors) return;
  for (uint32_t i = 0; i < map->count; ++i) {
    free(map->tensors[i].name);
    free(map->tensors[i].shape);
  }
  free(map->tensors);
  memset(map, 0, sizeof(*map));
}
References tensor_map_s::count, tensor_desc_s::name, tensor_desc_s::shape, and tensor_map_s::tensors.
Referenced by gptoss_weights_index_close(), gptoss_weights_index_open(), ie_gptoss_infer_create(), ie_gptoss_infer_destroy(), and maybe_correct_head_dim_().
tensor_map_load()
int tensor_map_load (const char * path, tensor_map_t * out)
Load tensor_map.json from disk.
Parameters
path Path to tensor_map.json.
out Output tensor map.
Returns
0 on success, non-zero on failure.
Definition at line 484 of file tensor_map.c.
{
  if (!path || !out) return -1;
  memset(out, 0, sizeof(*out));
  char *json = NULL;
  if (read_file(path, &json) != 0) return -1;
  const char *p = skip_ws(json);
  if (!*p) { free(json); return -1; }
  tensor_desc_t *arr = NULL;
  uint32_t count = 0;
  uint32_t cap = 0;
  if (*p == '[') {
    ++p;
    for (;;) {
      p = skip_ws(p);
      if (!*p) break;
      if (*p == ']') { ++p; break; }
      if (*p != '{') { p = skip_value(p); if (!p) break; }
      else {
        tensor_desc_t td;
        int ok = 0;
        const char *q = parse_tensor_object(p, NULL, &td, &ok);
        if (!q || !ok) break;
        p = q;
        if (push_tensor(&arr, &count, &cap, &td) != 0) {
          tensor_desc_free(&td);
          break;
        }
      }
      p = skip_ws(p);
      if (*p == ',') { ++p; continue; }
      if (*p == ']') { ++p; break; }
    }
  } else if (*p == '{') {
    ++p;
    int found_tensors_array = 0;
    const char *scan = p;
    while (*scan) {
      scan = skip_ws(scan);
      if (*scan == '}') break;
      if (*scan != '"') { ++scan; continue; }
      char *key = NULL;
      const char *qk = parse_string(scan, &key);
      if (!qk) { free(key); break; }
      scan = skip_ws(qk);
      if (*scan != ':') { free(key); break; }
      ++scan;
      scan = skip_ws(scan);
      if (key && strcmp(key, "tensors") == 0 && *scan == '[') {
        found_tensors_array = 1;
        ++scan;
        for (;;) {
          scan = skip_ws(scan);
          if (!*scan) break;
          if (*scan == ']') { ++scan; break; }
          if (*scan != '{') {
            scan = skip_value(scan);
            if (!scan) break;
          } else {
            tensor_desc_t td;
            int ok = 0;
            const char *qt = parse_tensor_object(scan, NULL, &td, &ok);
            if (!qt || !ok) break;
            scan = qt;
            if (push_tensor(&arr, &count, &cap, &td) != 0) {
              tensor_desc_free(&td);
              break;
            }
          }
          scan = skip_ws(scan);
          if (*scan == ',') { ++scan; continue; }
          if (*scan == ']') { ++scan; break; }
        }
        free(key);
        break;
      }
      if (*scan == '{') scan = skip_object(scan);
      else if (*scan == '[') scan = skip_array(scan);
      else scan = skip_value(scan);
      free(key);
      if (!scan) break;
      scan = skip_ws(scan);
      if (*scan == ',') ++scan;
    }
    if (!found_tensors_array) {
      while (*p) {
        p = skip_ws(p);
        if (!*p) break;
        if (*p == '}') { ++p; break; }
        if (*p == ',') { ++p; continue; }
        if (*p != '"') { p = skip_value(p); if (!p) break; continue; }
        char *name = NULL;
        p = parse_string(p, &name);
        if (!p) { free(name); break; }
        p = skip_ws(p);
        if (*p != ':') { free(name); break; }
        ++p;
        p = skip_ws(p);
        if (*p == '{') {
          tensor_desc_t td;
          int ok = 0;
          const char *q = parse_tensor_object(p, name, &td, &ok);
          if (!q || !ok) { free(name); break; }
          p = q;
          if (push_tensor(&arr, &count, &cap, &td) != 0) {
            tensor_desc_free(&td);
            free(name);
            break;
          }
        } else {
          p = skip_value(p);
          free(name);
          if (!p) break;
        }
        free(name);
        p = skip_ws(p);
        if (*p == ',') ++p;
      }
    }
  } else {
    free(json);
    return -1;
  }
  free(json);
  if (!arr || count == 0u) {
    free(arr);
    return -1;
  }
  if (cap > count) {
    tensor_desc_t *na = (tensor_desc_t *)realloc(arr, (size_t)count * sizeof(tensor_desc_t));
    if (na) arr = na;
  }
  out->tensors = arr;
  out->count = count;
  out->loaded = 1;
  return 0;
}
References parse_string(), parse_tensor_object(), push_tensor(), read_file(), skip_array(), skip_object(), skip_value(), skip_ws(), and tensor_desc_free().
Referenced by gptoss_weights_index_open(), ie_gptoss_infer_create(), and maybe_correct_head_dim_().
tensor_map_validate_against_bin()
int tensor_map_validate_against_bin (const tensor_map_t * map, size_t bin_size, char * err, size_t errsz)
Validate a loaded tensor map against a mapped weights binary.
This is a hard consistency check intended to catch stale/mismatched tensor_map.json versus model.ie.bin before any inference occurs. It validates:
name is present
size_bytes is non-zero
offset + size_bytes fits within bin_size
no overlaps (after sorting by offset)
Parameters
map Loaded tensor map.
bin_size Size in bytes of the mapped weights file.
err Optional error buffer for a human-readable error message.
errsz Size of err buffer.
Returns
0 if valid, non-zero if invalid.
Definition at line 696 of file tensor_map.c.
{
  if (!map || !map->loaded || !map->tensors || map->count == 0u) {
    tm_set_err(err, errsz, "tensor_map not loaded");
    return -1;
  }
  tm_sort_ref_t *refs = (tm_sort_ref_t *)malloc((size_t)map->count * sizeof(*refs));
  if (!refs) {
    tm_set_err(err, errsz, "OOM allocating validation refs");
    return -2;
  }
  for (uint32_t i = 0; i < map->count; ++i) {
    const tensor_desc_t *td = &map->tensors[i];
    if (!td->name || td->name[0] == '\0') {
      tm_set_err(err, errsz, "tensor_map contains entry with empty name");
      free(refs);
      return -3;
    }
    if (td->size_bytes == 0u) {
      char buf[256];
      if (tensor_desc_to_string(td, buf, sizeof(buf)) >= 0) {
        (void)snprintf(err, errsz, "tensor_map contains zero-sized tensor: %s", buf);
      } else {
        tm_set_err(err, errsz, "tensor_map contains zero-sized tensor");
      }
      free(refs);
      return -4;
    }
    const uint64_t end = td->offset + td->size_bytes;
    if (end < td->offset) {
      tm_set_err(err, errsz, "tensor_map offset+size overflow");
      free(refs);
      return -5;
    }
    if (end > (uint64_t)bin_size) {
      char buf[256];
      if (tensor_desc_to_string(td, buf, sizeof(buf)) >= 0) {
        (void)snprintf(err, errsz,
                       "tensor_map entry out of bounds: bin_size=%llu %s",
                       (unsigned long long)bin_size, buf);
      } else {
        tm_set_err(err, errsz, "tensor_map entry out of bounds");
      }
      free(refs);
      return -6;
    }
    refs[i].off = td->offset;
    refs[i].end = end;
    refs[i].idx = i;
  }
  qsort(refs, (size_t)map->count, sizeof(*refs), tm_sort_ref_cmp);
  uint64_t prev_end = refs[0].end;
  for (uint32_t k = 1; k < map->count; ++k) {
    if (refs[k].off < prev_end) {
      const tensor_desc_t *A = &map->tensors[refs[k - 1].idx];
      const tensor_desc_t *B = &map->tensors[refs[k].idx];
      char a_buf[256], b_buf[256];
      (void)tensor_desc_to_string(A, a_buf, sizeof(a_buf));
      (void)tensor_desc_to_string(B, b_buf, sizeof(b_buf));
      (void)snprintf(err, errsz,
                     "tensor_map overlap detected:\n  A: %s\n  B: %s",
                     a_buf, b_buf);
      free(refs);
      return -7;
    }
    prev_end = refs[k].end;
  }
  free(refs);
  if (err && errsz) err[0] = '\0';
  return 0;
}
References tensor_map_s::count, tm_sort_ref_s::end, tm_sort_ref_s::idx, tensor_map_s::loaded, tensor_desc_s::name, tm_sort_ref_s::off, tensor_desc_s::offset, tensor_desc_s::size_bytes, tensor_desc_to_string(), tensor_map_s::tensors, tm_set_err(), and tm_sort_ref_cmp().
tensor_shape_to_string()
static int tensor_shape_to_string (const uint32_t * shape, uint32_t ndim, char * out, size_t outsz) inline static
Format a shape into a compact string like "[a,b,c]".
Parameters
shape Shape pointer (may be NULL).
ndim Number of dims.
out Output buffer.
outsz Output buffer size.
Returns
Number of bytes written (excluding NUL) on success, or -1 on error.
Definition at line 140 of file tensor_map.h.
{
  if (!out || outsz == 0u) return -1;
  out[0] = '\0';
  size_t used = 0;
  if (used + 1u >= outsz) return -1;
  out[used++] = '[';
  if (!shape || ndim == 0u) {
    if (used + 2u >= outsz) return -1;
    out[used++] = ']';
    out[used] = '\0';
    return (int)(used);
  }
  for (uint32_t i = 0; i < ndim; ++i) {
    char tmp[32];
    int n = 0;
    if (i == 0u) {
      n = snprintf(tmp, sizeof(tmp), "%u", (unsigned)shape[i]);
    } else {
      n = snprintf(tmp, sizeof(tmp), ",%u", (unsigned)shape[i]);
    }
    if (n < 0) return -1;
    const size_t nn = (size_t)n;
    if (used + nn + 2u >= outsz) return -1; /* + ']' + NUL */
    for (size_t k = 0; k < nn; ++k) out[used++] = tmp[k];
  }
  if (used + 2u >= outsz) return -1;
  out[used++] = ']';
  out[used] = '\0';
  return (int)used;
}
Referenced by tensor_desc_to_string().