Inference Engine (Clocher): tests/c/test_kernels.c File Reference
test_kernels.c File Reference
Unit tests for GEMV kernels (row-major path, bias epilogue).
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "ie_kernels.h"
Functions
static int vec_allclose (const float *a, const float *b, size_t n, float tol)
Compare two float vectors with absolute tolerance.
static void fill_matrix (float *W, size_t rows, size_t cols)
Fill a small, deterministic row-major matrix W[r,c] = (r+1)*0.1 + (c+1)*0.01.
static void fill_vector (float *x, size_t n)
Fill a small, deterministic vector x[i] = 0.05 * (i+1).
static void ref_gemv_nominal (const float *W, const float *x, float *y, size_t rows, size_t cols)
Compute reference row-major GEMV y = W*x (no bias).
static void ref_gemv_bias (const float *W, const float *x, float *y, const float *bias, size_t rows, size_t cols)
Compute reference y = W*x + bias.
static int test_gemv_rowmajor_no_bias (void)
Test: GEMV without bias, row-major, blk_k=0.
static int test_gemv_rowmajor_with_bias (void)
Test: GEMV with bias epilogue, row-major, blk_k=0.
int main (void)
Program entry: run all kernel tests and print "ok test_kernels" on success.
Detailed Description
Unit tests for GEMV kernels (row-major path, bias epilogue).
This test validates:
Row-major GEMV without bias (blk_k = 0)
Row-major GEMV with epilogue bias (blk_k = 0)
NOTE: The blocked-K layout is exercised indirectly by integration tests.
Definition in file test_kernels.c.
Function Documentation
fill_matrix()
static void fill_matrix (float * W, size_t rows, size_t cols) static
Fill a small, deterministic row-major matrix W[r,c] = (r+1)*0.1 + (c+1)*0.01.
Parameters
W Output buffer (size rows*cols).
rows Number of rows.
cols Number of columns.
Definition at line 47 of file test_kernels.c.
{
   for (size_t r = 0; r < rows; ++r) {
     for (size_t c = 0; c < cols; ++c) {
       W[r*cols + c] = (float)(0.1 * (double)(r + 1) + 0.01 * (double)(c + 1));
     }
   }
 }
Referenced by test_gemv_rowmajor_no_bias(), and test_gemv_rowmajor_with_bias().
fill_vector()
static void fill_vector (float * x, size_t n) static
Fill a small, deterministic vector x[i] = 0.05 * (i+1).
Parameters
x Output buffer (length n).
n Number of elements.
Definition at line 61 of file test_kernels.c.
{
   for (size_t i = 0; i < n; ++i) x[i] = 0.05f * (float)(i + 1);
 }
Referenced by test_gemv_rowmajor_no_bias(), and test_gemv_rowmajor_with_bias().
main()
int main (void)
Program entry: run all kernel tests and print "ok test_kernels" on success.
Returns
0 on success; non-zero on assertion failure.
Definition at line 149 of file test_kernels.c.
                {
   ie_kernels_install(/*use_avx2=*/0);
   if (test_gemv_rowmajor_no_bias() != 0) {
     fprintf(stderr, "FAIL: test_gemv_rowmajor_no_bias\n");
     return 1;
   }
   if (test_gemv_rowmajor_with_bias() != 0) {
     fprintf(stderr, "FAIL: test_gemv_rowmajor_with_bias\n");
     return 1;
   }
   puts("ok test_kernels");
   return 0;
 }
References ie_kernels_install(), test_gemv_rowmajor_no_bias(), and test_gemv_rowmajor_with_bias().
ref_gemv_bias()
static void ref_gemv_bias (const float * W, const float * x, float * y, const float * bias, size_t rows, size_t cols) static
Compute reference y = W*x + bias.
Parameters
W Row-major weights (rows x cols).
x Input vector (length cols).
y Output vector (length rows).
bias Bias vector (length rows).
rows Rows.
cols Cols.
Definition at line 94 of file test_kernels.c.
{
   for (size_t r = 0; r < rows; ++r) {
     float acc = 0.0f;
     const float *wrow = W + r * cols;
     for (size_t c = 0; c < cols; ++c) acc += wrow[c] * x[c];
     y[r] = acc + bias[r];
   }
 }
Referenced by test_gemv_rowmajor_with_bias().
ref_gemv_nominal()
static void ref_gemv_nominal (const float * W, const float * x, float * y, size_t rows, size_t cols) static
Compute reference row-major GEMV y = W*x (no bias).
Parameters
W Row-major weights (rows x cols).
x Input vector (length cols).
y Output vector (length rows).
rows Rows.
cols Cols.
Definition at line 74 of file test_kernels.c.
{
   for (size_t r = 0; r < rows; ++r) {
     float acc = 0.0f;
     const float *wrow = W + r * cols;
     for (size_t c = 0; c < cols; ++c) acc += wrow[c] * x[c];
     y[r] = acc;
   }
 }
Referenced by test_gemv_rowmajor_no_bias().
test_gemv_rowmajor_no_bias()
static int test_gemv_rowmajor_no_bias (void) static
Test: GEMV without bias, row-major, blk_k=0.
Returns
0 on success; non-zero on failure.
Definition at line 109 of file test_kernels.c.
{
   const size_t R = 3, C = 4;
   float W[R*C], x[C], y[R], y_ref[R];
   fill_matrix(W, R, C);
   fill_vector(x, C);
   ref_gemv_nominal(W, x, y_ref, R, C);
   /* bias=NULL, blk_k=0 => row-major path */
   memset(y, 0, sizeof(y));
   ie_gemv_f32(W, x, y, R, C, /*bias*/NULL, /*blk_k*/0);
   return vec_allclose(y, y_ref, R, 1e-6f);
 }
References fill_matrix(), fill_vector(), ie_gemv_f32(), ref_gemv_nominal(), and vec_allclose().
Referenced by main().
test_gemv_rowmajor_with_bias()
static int test_gemv_rowmajor_with_bias (void) static
Test: GEMV with bias epilogue, row-major, blk_k=0.
Returns
0 on success; non-zero on failure.
Definition at line 129 of file test_kernels.c.
{
   const size_t R = 3, C = 4;
   float W[R*C], x[C], bias[R], y[R], y_ref[R];
   fill_matrix(W, R, C);
   fill_vector(x, C);
   for (size_t r = 0; r < R; ++r) bias[r] = 0.001f * (float)(r + 1);
   ref_gemv_bias(W, x, y_ref, bias, R, C);
   memset(y, 0, sizeof(y));
   ie_gemv_f32(W, x, y, R, C, /*bias*/bias, /*blk_k*/0);
   return vec_allclose(y, y_ref, R, 1e-6f);
 }
References fill_matrix(), fill_vector(), ie_gemv_f32(), ref_gemv_bias(), and vec_allclose().
Referenced by main().
vec_allclose()
static int vec_allclose (const float * a, const float * b, size_t n, float tol) static
Compare two float vectors with absolute tolerance.
Parameters
a First vector.
b Second vector.
n Number of elements to compare.
tol Absolute tolerance.
Returns
0 if all elements are within tol; non-zero otherwise.
Definition at line 28 of file test_kernels.c.
{
   for (size_t i = 0; i < n; ++i) {
     float d = fabsf(a[i] - b[i]);
     if (d > tol) {
       fprintf(stderr, "mismatch at %zu: a=%.6f b=%.6f |diff|=%.6f > %.6f\n",
               i, a[i], b[i], d, tol);
       return 1;
     }
   }
   return 0;
 }
Referenced by test_gemv_rowmajor_no_bias(), and test_gemv_rowmajor_with_bias().