Inference Engine (Clocher): tests/c/test_block_sparse.c File Reference
test_block_sparse.c File Reference
Unit tests for block-sparse format helpers and GEMV kernel.
#include "sparse_format.h"
#include <assert.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static int feq (float a, float b, float eps)
Compare two floats with absolute tolerance.
static void dump_vec (const char *name, const float *v, uint32_t n)
Dump a dense vector to stderr (debug helper).
static void build_dense_4x4 (float *W_out)
Build a 4x4 dense matrix used for testing.
static void build_block_sparse_4x4 (ie_block_sparse_matrix_t *m)
Build block-sparse descriptor for the 4x4 test matrix.
static int test_block_sparse_helpers (void)
Test helper functions for block grid sizes and density.
static int test_block_sparse_init_release (void)
Test that init and release leave descriptor in a safe state.
static int test_block_sparse_gemv_basic (void)
Test GEMV on the 4x4 example with a simple vector.
static int test_block_sparse_load_missing (void)
Test that loader fails with a missing file.
int main (void)
Entry point: run all block-sparse tests.
Detailed Description
Unit tests for block-sparse format helpers and GEMV kernel.
Definition in file test_block_sparse.c.
Function Documentation
build_block_sparse_4x4()
static void build_block_sparse_4x4 (ie_block_sparse_matrix_t * m) static
Build block-sparse descriptor for the 4x4 test matrix.
The layout is BSR with 2x2 blocks:
rows = 4, cols = 4
block_rows = 2, block_cols = 2
n_block_rows = 2, n_block_cols = 2
nnzb = 2 (two diagonal blocks)
Row pointers: row_ptr = [0, 1, 2] Column indices: col_idx = [0, 1] Values (two 2x2 blocks, row-major each): B0 = [1 2; 3 4] B1 = [5 6; 7 8]
Parameters
m Descriptor to populate (must not be NULL).
Definition at line 93 of file test_block_sparse.c.
{
   assert(m != NULL);
   ie_block_sparse_init(m);
   m->rows       = 4u;
   m->cols       = 4u;
   m->block_rows = 2u;
   m->block_cols = 2u;
   m->n_block_rows = ie_block_sparse_n_block_rows(m->rows, m->block_rows);
   m->n_block_cols = ie_block_sparse_n_block_cols(m->cols, m->block_cols);
   m->nnzb         = 2u;
   const uint32_t n_block_rows = m->n_block_rows;
   const uint32_t nnzb         = m->nnzb;
   const size_t   block_elems  =
       (size_t)m->block_rows * (size_t)m->block_cols;
   uint32_t *row_ptr = (uint32_t *)malloc((size_t)(n_block_rows + 1u) *
                                          sizeof(uint32_t));
   uint32_t *col_idx = (uint32_t *)malloc((size_t)nnzb * sizeof(uint32_t));
   float    *values  = (float *)malloc((size_t)nnzb * block_elems *
                                       sizeof(float));
   assert(row_ptr != NULL);
   assert(col_idx != NULL);
   assert(values  != NULL);
   /* Row pointers: first block-row -> block 0; second block-row -> block 1. */
   row_ptr[0] = 0u;
   row_ptr[1] = 1u;
   row_ptr[2] = 2u;
   /* Column indices: both diagonal blocks. */
   col_idx[0] = 0u;
   col_idx[1] = 1u;
   /* Values: B0 then B1, each 2x2 row-major. */
   values[0] = 1.0f; values[1] = 2.0f;
   values[2] = 3.0f; values[3] = 4.0f;
   values[4] = 5.0f; values[5] = 6.0f;
   values[6] = 7.0f; values[7] = 8.0f;
   m->row_ptr = row_ptr;
   m->col_idx = col_idx;
   m->values  = values;
 }
References ie_block_sparse_matrix::block_cols, ie_block_sparse_matrix::block_rows, ie_block_sparse_matrix::col_idx, ie_block_sparse_matrix::cols, ie_block_sparse_init(), ie_block_sparse_n_block_cols(), ie_block_sparse_n_block_rows(), ie_block_sparse_matrix::n_block_cols, ie_block_sparse_matrix::n_block_rows, ie_block_sparse_matrix::nnzb, ie_block_sparse_matrix::row_ptr, ie_block_sparse_matrix::rows, and ie_block_sparse_matrix::values.
Referenced by test_block_sparse_gemv_basic(), and test_block_sparse_init_release().
build_dense_4x4()
static void build_dense_4x4 (float * W_out) static
Build a 4x4 dense matrix used for testing.
Layout (row-major): [ 1 2 0 0 ] [ 3 4 0 0 ] [ 0 0 5 6 ] [ 0 0 7 8 ]
This can be represented with two non-zero 2x2 blocks on the diagonal.
Parameters
W_out Destination array of length 16 (row-major).
Definition at line 64 of file test_block_sparse.c.
{
   static const float W[16] = {
     1.0f, 2.0f, 0.0f, 0.0f,
     3.0f, 4.0f, 0.0f, 0.0f,
     0.0f, 0.0f, 5.0f, 6.0f,
     0.0f, 0.0f, 7.0f, 8.0f
   };
   memcpy(W_out, W, sizeof(W));
 }
Referenced by test_block_sparse_gemv_basic().
dump_vec()
static void dump_vec (const char * name, const float * v, uint32_t n) static
Dump a dense vector to stderr (debug helper).
Parameters
name Name to print.
v Vector pointer.
n Number of elements.
Definition at line 39 of file test_block_sparse.c.
{
   fprintf(stderr, "%s:", name);
   for (uint32_t i = 0; i < n; ++i) {
     fprintf(stderr, " %.6f", v[i]);
   }
   fprintf(stderr, "\n");
 }
Referenced by test_block_sparse_gemv_basic().
feq()
static int feq (float a, float b, float eps) static
Compare two floats with absolute tolerance.
Parameters
a First value.
b Second value.
eps Absolute tolerance.
Returns
1 if |a-b| <= eps, 0 otherwise.
Definition at line 27 of file test_block_sparse.c.
{
   const float diff = (float)fabsf(a - b);
   return diff <= eps;
 }
Referenced by test_block_sparse_gemv_basic(), and test_block_sparse_helpers().
main()
int main (void)
Entry point: run all block-sparse tests.
Returns
0 on success, non-zero if any subtest fails.
Definition at line 296 of file test_block_sparse.c.
                {
   int rc = 0;
   rc = test_block_sparse_helpers();
   if (rc != 0) {
     fprintf(stderr, "[FAIL] test_block_sparse_helpers (rc=%d)\n", rc);
     return rc;
   }
   rc = test_block_sparse_init_release();
   if (rc != 0) {
     fprintf(stderr, "[FAIL] test_block_sparse_init_release (rc=%d)\n", rc);
     return rc;
   }
   rc = test_block_sparse_gemv_basic();
   if (rc != 0) {
     fprintf(stderr, "[FAIL] test_block_sparse_gemv_basic (rc=%d)\n", rc);
     return rc;
   }
   rc = test_block_sparse_load_missing();
   if (rc != 0) {
     fprintf(stderr, "[FAIL] test_block_sparse_load_missing (rc=%d)\n", rc);
     return rc;
   }
   printf("[OK] block-sparse tests passed\n");
   return 0;
 }
References test_block_sparse_gemv_basic(), test_block_sparse_helpers(), test_block_sparse_init_release(), and test_block_sparse_load_missing().
test_block_sparse_gemv_basic()
static int test_block_sparse_gemv_basic (void) static
Test GEMV on the 4x4 example with a simple vector.
Returns
0 on success, non-zero on failure.
Definition at line 214 of file test_block_sparse.c.
{
   ie_block_sparse_matrix_t m;
   build_block_sparse_4x4(&m);
   float x[4] = {1.0f, 2.0f, 3.0f, 4.0f};
   float y[4] = {0.0f, 0.0f, 0.0f, 0.0f};
   float b[4] = {0.0f, 0.0f, 0.0f, 0.0f};
   /* Expected dense result: y = W * x (with W from build_dense_4x4). */
   float W_dense[16];
   build_dense_4x4(W_dense);
   float y_ref[4] = {0.0f, 0.0f, 0.0f, 0.0f};
   for (uint32_t r = 0; r < 4u; ++r) {
     float acc = 0.0f;
     const float *row = &W_dense[r * 4u];
     for (uint32_t c = 0; c < 4u; ++c) {
       acc += row[c] * x[c];
     }
     y_ref[r] = acc;
   }
   ie_gemv_block_sparse_f32(&m, x, y, b);
   int err = 0;
   for (uint32_t i = 0; i < 4u; ++i) {
     if (!feq(y[i], y_ref[i], 1e-5f)) {
       fprintf(stderr,
               "gemv mismatch at %u: got %.6f, expected %.6f\n",
               i, y[i], y_ref[i]);
       dump_vec("y", y, 4u);
       dump_vec("y_ref", y_ref, 4u);
       err = 1;
       break;
     }
   }
   ie_block_sparse_release(&m);
   return err;
 }
References build_block_sparse_4x4(), build_dense_4x4(), dump_vec(), feq(), ie_block_sparse_release(), and ie_gemv_block_sparse_f32().
Referenced by main().
test_block_sparse_helpers()
static int test_block_sparse_helpers (void) static
Test helper functions for block grid sizes and density.
Returns
0 on success, non-zero on failure.
Definition at line 152 of file test_block_sparse.c.
{
   const uint32_t nbr = ie_block_sparse_n_block_rows(4u, 2u);
   const uint32_t nbc = ie_block_sparse_n_block_cols(4u, 2u);
   if (nbr != 2u || nbc != 2u) {
     fprintf(stderr, "n_block_rows/cols mismatch: got (%u,%u)\n", nbr, nbc);
     return 1;
   }
   const float d = ie_block_sparse_density(2u, nbr, nbc);
   if (!feq(d, 0.5f, 1e-6f)) {
     fprintf(stderr, "density mismatch: got %f, expected 0.5\n", d);
     return 2;
   }
   const uint32_t bad_rows = ie_block_sparse_n_block_rows(0u, 2u);
   const uint32_t bad_cols = ie_block_sparse_n_block_cols(4u, 0u);
   if (bad_rows != 0u || bad_cols != 0u) {
     fprintf(stderr, "expected zero for invalid grid sizes\n");
     return 3;
   }
   return 0;
 }
References feq(), ie_block_sparse_density(), ie_block_sparse_n_block_cols(), and ie_block_sparse_n_block_rows().
Referenced by main().
test_block_sparse_init_release()
static int test_block_sparse_init_release (void) static
Test that init and release leave descriptor in a safe state.
Returns
0 on success, non-zero on failure.
Definition at line 182 of file test_block_sparse.c.
{
   ie_block_sparse_matrix_t m;
   ie_block_sparse_init(&m);
   if (m.rows != 0u || m.cols != 0u ||
       m.row_ptr != NULL || m.col_idx != NULL || m.values != NULL) {
     fprintf(stderr, "init did not zero descriptor\n");
     return 1;
   }
   /* Allocate some storage and then release. */
   build_block_sparse_4x4(&m);
   if (m.row_ptr == NULL || m.col_idx == NULL || m.values == NULL) {
     fprintf(stderr, "build_block_sparse_4x4 produced NULL storage\n");
     return 2;
   }
   ie_block_sparse_release(&m);
   if (m.rows != 0u || m.cols != 0u ||
       m.row_ptr != NULL || m.col_idx != NULL || m.values != NULL) {
     fprintf(stderr, "release did not zero descriptor\n");
     return 3;
   }
   return 0;
 }
References build_block_sparse_4x4(), ie_block_sparse_matrix::col_idx, ie_block_sparse_matrix::cols, ie_block_sparse_init(), ie_block_sparse_release(), ie_block_sparse_matrix::row_ptr, ie_block_sparse_matrix::rows, and ie_block_sparse_matrix::values.
Referenced by main().
test_block_sparse_load_missing()
static int test_block_sparse_load_missing (void) static
Test that loader fails with a missing file.
This just checks error handling and status codes.
Returns
0 on success, non-zero on failure.
Definition at line 262 of file test_block_sparse.c.
{
   ie_block_sparse_matrix_t m;
   ie_block_sparse_init(&m);
   const ie_sparse_status_t st =
       ie_block_sparse_load("this_file_should_not_exist.iebs", &m);
   if (st != IE_SPARSE_ERR_OPEN) {
     fprintf(stderr, "expected IE_SPARSE_ERR_OPEN, got %d (%s)\n",
             (int)st, ie_sparse_status_str(st));
     ie_block_sparse_release(&m);
     return 1;
   }
   /* Descriptor must remain empty. */
   if (m.rows != 0u || m.cols != 0u ||
       m.row_ptr != NULL || m.col_idx != NULL || m.values != NULL) {
     fprintf(stderr, "loader left non-empty descriptor on error\n");
     ie_block_sparse_release(&m);
     return 2;
   }
   return 0;
 }
References ie_block_sparse_matrix::col_idx, ie_block_sparse_matrix::cols, ie_block_sparse_init(), ie_block_sparse_load(), ie_block_sparse_release(), IE_SPARSE_ERR_OPEN, ie_sparse_status_str(), ie_block_sparse_matrix::row_ptr, ie_block_sparse_matrix::rows, and ie_block_sparse_matrix::values.
Referenced by main().