Inference Engine (Clocher): tests/c/test_topology.c File Reference
test_topology.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "ie_topology.h"
Functions
static void dump_topology (const ie_topology_t *t)
Dump a short human-readable view of the topology.
int main (void)
Main test entry: build topology, print, and basic assertions.
Function Documentation
dump_topology()
static void dump_topology (const ie_topology_t * t) static
Dump a short human-readable view of the topology.
Parameters
t Initialized topology handle.
Definition at line 17 of file test_topology.c.
{
  const int n_cpu     = ie_topology_cpus(t);
  const int n_socket  = ie_topology_sockets(t);
  const int n_node    = ie_topology_nodes(t);
  printf("topology: cpus=%d sockets=%d nodes=%d\n", n_cpu, n_socket, n_node);
  for (int s = 0; s < n_socket; ++s) {
    int c0 = ie_topology_first_cpu_on_socket(t, s);
    printf("  socket %d: first-cpu=%d\n", s, c0);
  }
  for (int i = 0; i < n_cpu; ++i) {
    int sid = ie_topology_cpu_to_socket(t, i);
    int nid = ie_topology_cpu_to_node(t, i);
    printf("  cpu %d -> socket %d, node %d\n", i, sid, nid);
  }
}
References ie_topology_cpu_to_node(), ie_topology_cpu_to_socket(), ie_topology_cpus(), ie_topology_first_cpu_on_socket(), ie_topology_nodes(), and ie_topology_sockets().
Referenced by main().
main()
int main (void)
Main test entry: build topology, print, and basic assertions.
Returns
0 on success; non-zero on failure.
Definition at line 41 of file test_topology.c.
               {
  ie_topology_t *t = NULL;
  int rc = ie_topology_init(&t);
  if (rc != 0 || !t) {
    fprintf(stderr, "ie_topology_init failed: %d\n", rc);
    return 1;
  }
  /* Basic invariants */
  if (ie_topology_cpus(t) <= 0) {
    fprintf(stderr, "invalid cpu count\n");
    ie_topology_destroy(t);
    return 2;
  }
  if (ie_topology_sockets(t) <= 0) {
    fprintf(stderr, "invalid socket count\n");
    ie_topology_destroy(t);
    return 3;
  }
  if (ie_topology_nodes(t) <= 0) {
    fprintf(stderr, "invalid node count\n");
    ie_topology_destroy(t);
    return 4;
  }
  dump_topology(t);
  ie_topology_destroy(t);
  puts("ok test_topology");
  return 0;
}
References dump_topology(), ie_topology_cpus(), ie_topology_destroy(), ie_topology_init(), ie_topology_nodes(), and ie_topology_sockets().