Inference Engine (Clocher): engine/src/io/tokenizer_hf.c File Reference
tokenizer_hf.c File Reference
#include "tokenizer_hf.h"
#include <ctype.h>
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct byte_map_entry_t
Macros
#define _POSIX_C_SOURCE 200809L
Functions
static const char * skip_ws (const char *p)
static int read_file (const char *path, char **out, size_t *sz)
static const char * parse_string (const char *p, char **out)
static const char * parse_u32 (const char *p, uint32_t *out)
static void build_gpt2_byte_decoder (void)
static int gpt2_cp_to_byte (uint32_t cp, uint8_t *out)
int tokenizer_hf_load (const char *path, tokenizer_hf_t *out)
Load tokenizer.json from disk.
void tokenizer_hf_free (tokenizer_hf_t *tok)
Free tokenizer resources.
int tokenizer_hf_decode (const tokenizer_hf_t *tok, const int *ids, size_t n_ids, char *out, size_t out_sz)
Decode token IDs into UTF-8 text.
Variables
static byte_map_entry_t gpt2_map [256]
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 1 of file tokenizer_hf.c.
Function Documentation
build_gpt2_byte_decoder()
static void build_gpt2_byte_decoder (void) static
Definition at line 111 of file tokenizer_hf.c.
{
  static int built = 0;
  if (built) return;
  built = 1;
  int used[256] = {0};
  int n = 0;
  for (int i = 33; i <= 126; ++i) {
    gpt2_map[n++] = (byte_map_entry_t){ (uint32_t)i, (uint8_t)i };
    used[i] = 1;
  }
  for (int i = 161; i <= 172; ++i) {
    gpt2_map[n++] = (byte_map_entry_t){ (uint32_t)i, (uint8_t)i };
    used[i] = 1;
  }
  for (int i = 174; i <= 255; ++i) {
    gpt2_map[n++] = (byte_map_entry_t){ (uint32_t)i, (uint8_t)i };
    used[i] = 1;
  }
  uint32_t extra = 0;
  for (int i = 0; i < 256; ++i) {
    if (!used[i]) {
      gpt2_map[n++] = (byte_map_entry_t){ 256u + extra, (uint8_t)i };
      ++extra;
    }
  }
}
References gpt2_map.
Referenced by tokenizer_hf_load().
gpt2_cp_to_byte()
static int gpt2_cp_to_byte (uint32_t cp, uint8_t * out) static
Definition at line 141 of file tokenizer_hf.c.
{
  for (int i = 0; i < 256; ++i) {
    if (gpt2_map[i].key == cp) {
      *out = gpt2_map[i].val;
      return 1;
    }
  }
  return 0;
}
References gpt2_map, and byte_map_entry_t::val.
Referenced by tokenizer_hf_decode().
parse_string()
static const char * parse_string (const char * p, char ** out) static
Definition at line 46 of file tokenizer_hf.c.
{
  if (*p != '"') return NULL;
  ++p;
  size_t cap = 64, len = 0;
  char *buf = malloc(cap);
  if (!buf) return NULL;
  while (*p) {
    if (*p == '"') {
      buf[len] = 0;
      *out = buf;
      return p + 1;
    }
    if (*p == '\\') {
      ++p;
      if (!*p) break;
      char c = *p;
      if (c == 'n') c = '\n';
      else if (c == 't') c = '\t';
      else if (c == 'r') c = '\r';
      if (len + 1 >= cap) {
        cap *= 2;
        buf = realloc(buf, cap);
        if (!buf) return NULL;
      }
      buf[len++] = c;
      ++p;
      continue;
    }
    if (len + 1 >= cap) {
      cap *= 2;
      buf = realloc(buf, cap);
      if (!buf) return NULL;
    }
    buf[len++] = *p++;
  }
  free(buf);
  return NULL;
}
Referenced by tokenizer_hf_load().
parse_u32()
static const char * parse_u32 (const char * p, uint32_t * out) static
Definition at line 88 of file tokenizer_hf.c.
{
  uint64_t v = 0;
  if (!isdigit((unsigned char)*p)) return NULL;
  while (isdigit((unsigned char)*p)) {
    v = v * 10 + (uint64_t)(*p - '0');
    if (v > 0xFFFFFFFFu) return NULL;
    ++p;
  }
  *out = (uint32_t)v;
  return p;
}
Referenced by tokenizer_hf_load().
read_file()
static int read_file (const char * path, char ** out, size_t * sz) static
Definition at line 21 of file tokenizer_hf.c.
{
  FILE *f = fopen(path, "rb");
  if (!f) return -1;
  fseek(f, 0, SEEK_END);
  long n = ftell(f);
  fseek(f, 0, SEEK_SET);
  if (n <= 0) { fclose(f); return -1; }
  char *buf = malloc((size_t)n + 1);
  if (!buf) { fclose(f); return -1; }
  if (fread(buf, 1, (size_t)n, f) != (size_t)n) {
    free(buf);
    fclose(f);
    return -1;
  }
  fclose(f);
  buf[n] = 0;
  *out = buf;
  if (sz) *sz = (size_t)n;
  return 0;
}
Referenced by tokenizer_hf_load().
skip_ws()
static const char * skip_ws (const char * p) static
Definition at line 16 of file tokenizer_hf.c.
{
  while (*p && (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r')) ++p;
  return p;
}
Referenced by tokenizer_hf_load().
tokenizer_hf_decode()
int tokenizer_hf_decode (const tokenizer_hf_t * tok, const int * ids, size_t n_ids, char * out, size_t out_sz)
Decode token IDs into UTF-8 text.
Uses GPT-2 byte-level decoding.
Parameters
tok Loaded tokenizer
ids Token ID array
n_ids Number of token IDs
out Output buffer
out_sz Output buffer capacity
Returns
0 on success, non-zero on failure
Definition at line 233 of file tokenizer_hf.c.
{
  if (!tok || !tok->loaded || !out || out_sz == 0) return -1;
  size_t w = 0;
  out[0] = 0;
  for (size_t i = 0; i < n_ids; ++i) {
    int id = ids[i];
    if (id < 0 || (uint32_t)id >= tok->vocab_size) continue;
    const char *s = tok->id_to_token[id];
    if (!s) continue;
    while (*s) {
      uint32_t cp = (unsigned char)*s++;
      uint8_t b;
      if (gpt2_cp_to_byte(cp, &b)) {
        if (w + 1 >= out_sz) return -1;
        out[w++] = (char)b;
      } else {
        if (w + 1 >= out_sz) return -1;
        out[w++] = (char)cp;
      }
    }
  }
  out[w] = 0;
  return 0;
}
References gpt2_cp_to_byte(), tokenizer_hf_s::id_to_token, tokenizer_hf_s::loaded, and tokenizer_hf_s::vocab_size.
tokenizer_hf_free()
void tokenizer_hf_free (tokenizer_hf_t * tok)
Free tokenizer resources.
Parameters
tok Tokenizer object
Definition at line 225 of file tokenizer_hf.c.
{
  if (!tok) return;
  for (uint32_t i = 0; i < tok->vocab_size; ++i)
    free(tok->id_to_token[i]);
  free(tok->id_to_token);
  memset(tok, 0, sizeof(*tok));
}
References tokenizer_hf_s::id_to_token, and tokenizer_hf_s::vocab_size.
tokenizer_hf_load()
int tokenizer_hf_load (const char * path, tokenizer_hf_t * out)
Load tokenizer.json from disk.
Parameters
path Path to HuggingFace tokenizer.json
out Tokenizer object to initialize
Returns
0 on success, non-zero on failure
Definition at line 155 of file tokenizer_hf.c.
{
  if (!path || !out) return -1;
  memset(out, 0, sizeof(*out));
  char *json = NULL;
  if (read_file(path, &json, NULL) != 0) return -1;
  const char *p = strstr(json, "\"vocab\"");
  if (!p) { free(json); return -1; }
  p = strchr(p, '{');
  if (!p) { free(json); return -1; }
  ++p;
  uint32_t max_id = 0;
  const char *scan = p;
  while (*scan && *scan != '}') {
    char *tok = NULL;
    scan = skip_ws(scan);
    scan = parse_string(scan, &tok);
    if (!scan) break;
    scan = skip_ws(scan);
    if (*scan != ':') { free(tok); break; }
    ++scan;
    scan = skip_ws(scan);
    uint32_t id = 0;
    scan = parse_u32(scan, &id);
    if (!scan) { free(tok); break; }
    if (id > max_id) max_id = id;
    free(tok);
    scan = skip_ws(scan);
    if (*scan == ',') ++scan;
  }
  out->vocab_size = max_id + 1;
  out->id_to_token = calloc(out->vocab_size, sizeof(char*));
  if (!out->id_to_token) { free(json); return -1; }
  scan = p;
  while (*scan && *scan != '}') {
    char *tok = NULL;
    scan = skip_ws(scan);
    scan = parse_string(scan, &tok);
    if (!scan) break;
    scan = skip_ws(scan);
    if (*scan != ':') { free(tok); break; }
    ++scan;
    scan = skip_ws(scan);
    uint32_t id = 0;
    scan = parse_u32(scan, &id);
    if (!scan) { free(tok); break; }
    if (id < out->vocab_size) out->id_to_token[id] = tok;
    else free(tok);
    scan = skip_ws(scan);
    if (*scan == ',') ++scan;
  }
  free(json);
  build_gpt2_byte_decoder();
  out->loaded = 1;
  return 0;
}
References build_gpt2_byte_decoder(), parse_string(), parse_u32(), read_file(), and skip_ws().
Variable Documentation
gpt2_map
byte_map_entry_t gpt2_map[256] static
Definition at line 109 of file tokenizer_hf.c.
Referenced by build_gpt2_byte_decoder(), and gpt2_cp_to_byte().