Inference Engine (Clocher): engine/src/opt/topology.c File Reference
topology.c File Reference
#include "ie_topology.h"
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sched.h>
Data Structures
struct ie_topology
Internal representation.
Macros
#define _GNU_SOURCE 1
#define _POSIX_C_SOURCE 200809L
Functions
static int get_online_cpus (void)
Return number of online CPUs using sysconf.
static int read_int_file (const char *path, int *out)
Read an integer from a text file.
static void apply_cpulist_to_node (const char *s, int node_id, int *cpu2node, int cap)
Apply a Linux cpulist string (e.g., "0-3,8,10-11") to mark node for CPUs.
static int discover_sockets_sysfs (int n_cpus, int *cpu2socket)
Discover sockets using per-CPU physical_package_id in sysfs.
static int discover_nodes_sysfs (int n_cpus, int *cpu2node)
Discover NUMA nodes by parsing node cpulist files in sysfs.
static void compute_first_cpu_per_socket (int n_cpus, int n_sockets, const int *cpu2socket, int *out_first)
Compute a small representative CPU per socket.
int ie_topology_init (ie_topology_t **out_topo)
Initialize and build a topology handle.
void ie_topology_destroy (ie_topology_t *topo)
Free topology handle created by ie_topology_init().
int ie_topology_cpus (const ie_topology_t *topo)
Get number of CPUs.
int ie_topology_sockets (const ie_topology_t *topo)
Get number of sockets.
int ie_topology_nodes (const ie_topology_t *topo)
Get number of NUMA nodes.
int ie_topology_cpu_to_socket (const ie_topology_t *topo, int cpu)
CPU -> socket mapping.
int ie_topology_cpu_to_node (const ie_topology_t *topo, int cpu)
CPU -> NUMA node mapping.
int ie_topology_first_cpu_on_socket (const ie_topology_t *topo, int socket)
First (smallest id) CPU present on a given socket.
int ie_topology_bind_thread_to_socket (const ie_topology_t *topo, int socket)
Bind the current thread/process to a representative CPU of a socket.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE 1
Definition at line 8 of file topology.c.
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 9 of file topology.c.
Function Documentation
apply_cpulist_to_node()
static void apply_cpulist_to_node (const char * s, int node_id, int * cpu2node, int cap) static
Apply a Linux cpulist string (e.g., "0-3,8,10-11") to mark node for CPUs.
Parameters
s cpulist string (NUL-terminated).
node_id Node id to assign.
cpu2node Array of length cap; will be set to node_id for listed CPUs.
cap Array capacity (number of CPUs).
Definition at line 83 of file topology.c.
{
   const char *p = s ? s : "";
   while (*p) {
     /* skip separators and whitespace */
     while (*p == ' ' || *p == '\t' || *p == ',' || *p == '\n' || *p == '\r') ++p;
     if (!*p) break;
     char *end = NULL;
     long a = strtol(p, &end, 10);
     if (end == p) { /* skip invalid token */
       while (*p && *p != ',' && *p != '\n' && *p != '\r') ++p;
       continue;
     }
     p = end;
     long b = a;
     if (*p == '-') {
       ++p;
       b = strtol(p, &end, 10);
       if (end == p) b = a; /* treat lone '-' weirdness as single */
       p = end;
     }
     if (a < 0) a = 0;
     if (b < 0) b = 0;
     if (a > b) { long t = a; a = b; b = t; }
     for (long i = a; i <= b; ++i) {
       if (i >= 0 && i < cap) cpu2node[(int)i] = node_id;
     }
   }
 }
Referenced by discover_nodes_sysfs().
compute_first_cpu_per_socket()
static void compute_first_cpu_per_socket (int n_cpus, int n_sockets, const int * cpu2socket, int * out_first) static
Compute a small representative CPU per socket.
Parameters
n_cpus Number of CPUs.
n_sockets Number of sockets.
cpu2socket Array length n_cpus.
out_first Output length n_sockets; filled with first CPU id or -1.
Definition at line 192 of file topology.c.
{
   for (int s = 0; s < n_sockets; ++s) out_first[s] = -1;
   for (int cpu = 0; cpu < n_cpus; ++cpu) {
     int s = cpu2socket[cpu];
     if (s >= 0 && s < n_sockets) {
       if (out_first[s] == -1 || cpu < out_first[s]) out_first[s] = cpu;
     }
   }
 }
Referenced by ie_topology_init().
discover_nodes_sysfs()
static int discover_nodes_sysfs (int n_cpus, int * cpu2node) static
Discover NUMA nodes by parsing node cpulist files in sysfs.
Probes "/sys/devices/system/node/node<N>/cpulist" for existing node directories and applies their ranges to the cpu->node map.
Missing directories or files are tolerated. Unknown entries are ignored.
Parameters
n_cpus Number of CPUs to consider.
cpu2node Output array length n_cpus (initialized to -1 before call).
Returns
Count of nodes discovered (>=0). 0 means not found.
Definition at line 150 of file topology.c.
{
   const char *root = "/sys/devices/system/node";
   DIR *d = opendir(root);
   if (!d) return 0;
   int max_node_id = -1;
   struct dirent *de;
   while ((de = readdir(d)) != NULL) {
     if (strncmp(de->d_name, "node", 4) != 0) continue;
     char *end = NULL;
     long nid = strtol(de->d_name + 4, &end, 10);
     if (end == de->d_name + 4 || nid < 0 || nid > INT_MAX) continue;
     char path[512];
     snprintf(path, sizeof(path), "%s/%s/cpulist", root, de->d_name);
     FILE *f = fopen(path, "r");
     if (!f) continue;
     char buf[4096];
     size_t n = fread(buf, 1, sizeof(buf) - 1, f);
     fclose(f);
     buf[n] = '\0';
     apply_cpulist_to_node(buf, (int)nid, cpu2node, n_cpus);
     if ((int)nid > max_node_id) max_node_id = (int)nid;
   }
   closedir(d);
   if (max_node_id < 0) return 0;
   /* Normalize: nodes are 0..max_node_id, but some may be sparse; still fine. */
   return max_node_id + 1;
 }
References apply_cpulist_to_node().
Referenced by ie_topology_init().
discover_sockets_sysfs()
static int discover_sockets_sysfs (int n_cpus, int * cpu2socket) static
Discover sockets using per-CPU physical_package_id in sysfs.
Probes "/sys/devices/system/cpu/cpu<N>/topology/physical_package_id" for N = 0..n_cpus-1.
Parameters
n_cpus Number of CPUs to probe.
cpu2socket Output array length n_cpus (initialized to -1 before call).
Returns
Count of distinct sockets (>=0). 0 means not found.
Definition at line 122 of file topology.c.
{
   int max_socket_id = -1;
   for (int cpu = 0; cpu < n_cpus; ++cpu) {
     char path[256];
     snprintf(path, sizeof(path),
              "/sys/devices/system/cpu/cpu%d/topology/physical_package_id", cpu);
     int sid = -1;
     if (read_int_file(path, &sid) == 0 && sid >= 0) {
       cpu2socket[cpu] = sid;
       if (sid > max_socket_id) max_socket_id = sid;
     }
   }
   if (max_socket_id < 0) return 0;
   return max_socket_id + 1;
 }
References read_int_file().
Referenced by ie_topology_init().
get_online_cpus()
static int get_online_cpus (void) static
Return number of online CPUs using sysconf.
Returns
CPUs (>=1) on success; 1 as a conservative fallback.
Definition at line 42 of file topology.c.
{
   long onln = sysconf(_SC_NPROCESSORS_ONLN);
   if (onln <= 0) return 1;
   if (onln > INT_MAX) onln = INT_MAX;
   return (int)onln;
 }
Referenced by ie_topology_init().
ie_topology_bind_thread_to_socket()
int ie_topology_bind_thread_to_socket (const ie_topology_t * topo, int socket)
Bind the current thread/process to a representative CPU of a socket.
Picks ie_topology_first_cpu_on_socket() and applies sched_setaffinity().
Parameters
topo Handle (non-NULL).
socket Socket id (0..n_sockets-1).
Returns
0 on success; negative errno-like on failure.
Definition at line 338 of file topology.c.
{
   if (!topo) return -EINVAL;
   if (socket < 0 || socket >= topo->n_sockets) return -EINVAL;
   int cpu = ie_topology_first_cpu_on_socket(topo, socket);
   if (cpu < 0) return -EINVAL;
   cpu_set_t set;
   CPU_ZERO(&set);
   CPU_SET((unsigned)cpu, &set);
   if (sched_setaffinity(0, sizeof(set), &set) != 0) {
     return -errno ? -errno : -1;
   }
   return 0;
 }
References ie_topology_first_cpu_on_socket(), and ie_topology::n_sockets.
Referenced by ie_hot_replicate_build(), and ie_hot_replicate_build_fill().
ie_topology_cpu_to_node()
int ie_topology_cpu_to_node (const ie_topology_t * topo, int cpu)
CPU -> NUMA node mapping.
Map a CPU id to its NUMA node id.
Parameters
topo Handle (non-NULL).
cpu Zero-based CPU id.
Returns
Node id (>=0) or -1 if invalid.
Definition at line 313 of file topology.c.
{
   if (!topo || cpu < 0 || cpu >= topo->n_cpus) return -1;
   return topo->cpu_to_node[cpu];
 }
References ie_topology::cpu_to_node, and ie_topology::n_cpus.
Referenced by dump_topology().
ie_topology_cpu_to_socket()
int ie_topology_cpu_to_socket (const ie_topology_t * topo, int cpu)
CPU -> socket mapping.
Map a CPU id to its socket id.
Parameters
topo Handle (non-NULL).
cpu Zero-based CPU id.
Returns
Socket id (>=0) or -1 if invalid.
Definition at line 302 of file topology.c.
{
   if (!topo || cpu < 0 || cpu >= topo->n_cpus) return -1;
   return topo->cpu_to_socket[cpu];
 }
References ie_topology::cpu_to_socket, and ie_topology::n_cpus.
Referenced by dump_topology().
ie_topology_cpus()
int ie_topology_cpus (const ie_topology_t * topo)
Get number of CPUs.
Return the number of online CPUs observed during discovery.
Parameters
topo Handle (non-NULL).
Returns
CPU count (>=1).
Definition at line 274 of file topology.c.
{
   return topo ? topo->n_cpus : 0;
 }
References ie_topology::n_cpus.
Referenced by dump_topology(), and main().
ie_topology_destroy()
void ie_topology_destroy (ie_topology_t * topo)
Free topology handle created by ie_topology_init().
Free a previously created topology handle.
Parameters
topo Topology handle (nullable).
Definition at line 261 of file topology.c.
{
   if (!topo) return;
   free(topo->cpu_to_socket);
   free(topo->cpu_to_node);
   free(topo->first_cpu_socket);
   free(topo);
 }
References ie_topology::cpu_to_node, ie_topology::cpu_to_socket, and ie_topology::first_cpu_socket.
Referenced by main().
ie_topology_first_cpu_on_socket()
int ie_topology_first_cpu_on_socket (const ie_topology_t * topo, int socket)
First (smallest id) CPU present on a given socket.
Return a representative CPU id that belongs to the given socket.
Parameters
topo Handle (non-NULL).
socket Socket id.
Returns
CPU id (>=0) or -1 on invalid socket.
Definition at line 324 of file topology.c.
{
   if (!topo || socket < 0 || socket >= topo->n_sockets) return -1;
   return topo->first_cpu_socket[socket];
 }
References ie_topology::first_cpu_socket, and ie_topology::n_sockets.
Referenced by dump_topology(), and ie_topology_bind_thread_to_socket().
ie_topology_init()
int ie_topology_init (ie_topology_t ** topo)
Initialize and build a topology handle.
This probes the host to discover:
total online CPUs
socket id for each CPU
NUMA node id for each CPU A best-effort approach is used; missing information is replaced by a consistent single-socket, single-node fallback.
Parameters
[out] topo Output pointer to receive a newly allocated handle (non-NULL).
Returns
0 on success; negative errno-like value on failure (e.g., -12 for OOM).
Definition at line 205 of file topology.c.
{
   if (!out_topo) return -EINVAL;
   int n_cpus = get_online_cpus();
   ie_topology_t *t = (ie_topology_t *)calloc(1, sizeof(*t));
   if (!t) return -ENOMEM;
   t->n_cpus = n_cpus;
   t->cpu_to_socket = (int *)malloc(sizeof(int) * n_cpus);
   t->cpu_to_node   = (int *)malloc(sizeof(int) * n_cpus);
   if (!t->cpu_to_socket || !t->cpu_to_node) {
     free(t->cpu_to_socket);
     free(t->cpu_to_node);
     free(t);
     return -ENOMEM;
   }
   for (int i = 0; i < n_cpus; ++i) {
     t->cpu_to_socket[i] = -1;
     t->cpu_to_node[i] = -1;
   }
   /* Best-effort discovery */
   int sockets = discover_sockets_sysfs(n_cpus, t->cpu_to_socket);
   int nodes   = discover_nodes_sysfs(n_cpus, t->cpu_to_node);
   if (sockets <= 0) {
     sockets = 1;
     for (int i = 0; i < n_cpus; ++i) t->cpu_to_socket[i] = 0;
   }
   if (nodes <= 0) {
     nodes = 1;
     for (int i = 0; i < n_cpus; ++i) t->cpu_to_node[i] = 0;
   }
   t->n_sockets = sockets;
   t->n_nodes   = nodes;
   t->first_cpu_socket = (int *)malloc(sizeof(int) * sockets);
   if (!t->first_cpu_socket) {
     free(t->cpu_to_socket);
     free(t->cpu_to_node);
     free(t);
     return -ENOMEM;
   }
   compute_first_cpu_per_socket(n_cpus, sockets, t->cpu_to_socket, t->first_cpu_socket);
   *out_topo = t;
   return 0;
 }
References compute_first_cpu_per_socket(), ie_topology::cpu_to_node, ie_topology::cpu_to_socket, discover_nodes_sysfs(), discover_sockets_sysfs(), ie_topology::first_cpu_socket, get_online_cpus(), ie_topology::n_cpus, ie_topology::n_nodes, and ie_topology::n_sockets.
Referenced by main().
ie_topology_nodes()
int ie_topology_nodes (const ie_topology_t * topo)
Get number of NUMA nodes.
Return the number of NUMA nodes discovered.
Parameters
topo Handle (non-NULL).
Returns
Node count (>=1).
Definition at line 292 of file topology.c.
{
   return topo ? topo->n_nodes : 0;
 }
References ie_topology::n_nodes.
Referenced by dump_topology(), and main().
ie_topology_sockets()
int ie_topology_sockets (const ie_topology_t * topo)
Get number of sockets.
Return the number of sockets (physical packages).
Parameters
topo Handle (non-NULL).
Returns
Socket count (>=1).
Definition at line 283 of file topology.c.
{
   return topo ? topo->n_sockets : 0;
 }
References ie_topology::n_sockets.
Referenced by dump_topology(), ie_hot_replicate_build(), ie_hot_replicate_build_fill(), ie_numa_policy_init(), and main().
read_int_file()
static int read_int_file (const char * path, int * out) static
Read an integer from a text file.
Accepts trailing newline. Ignores leading whitespace.
Parameters
path File path.
out Output integer.
Returns
0 on success; negative errno-like on error.
Definition at line 58 of file topology.c.
{
   FILE *f = fopen(path, "r");
   if (!f) return -errno ? -errno : -1;
   char buf[64];
   if (!fgets(buf, sizeof(buf), f)) {
     int e = ferror(f) ? -errno : -1;
     fclose(f);
     return e ? e : -1;
   }
   fclose(f);
   char *end = NULL;
   long v = strtol(buf, &end, 10);
   if (end == buf) return -EINVAL;
   *out = (int)v;
   return 0;
 }
Referenced by discover_sockets_sysfs().