Inference Engine (Clocher): engine/src/util_metrics.c File Reference
util_metrics.c File Reference
Implementation of runtime metrics (KV counters + RSS sampling).
#include "util_metrics.h"
#include <errno.h>
#include <stdatomic.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/resource.h>
#include <strings.h>
Macros
#define _POSIX_C_SOURCE 200809L
Functions
static int env_flag (const char *name)
Return 1 if the environment variable name is a truthy flag.
static void dbg (const char *fmt,...)
Debug print controlled by IE_DEBUG_RSS=1.
static uint32_t kib_to_mib_ceil (uint64_t kib)
Round up KiB to MiB using ceil(), clamped to 32-bit.
static int parse_status_kb_line (const char *line, const char *key, uint64_t *out_kb)
Parse an integer KiB value from a "Key: 12345 kB" style procfs line.
static int read_proc_kb_single (const char *path, const char *key, uint64_t *out_kb)
Read a single numeric (KiB) field from a procfs text file.
void ie_metrics_reset (void)
Reset all process-wide counters (KV hits/misses).
void ie_metrics_add_kv_hit (uint64_t n)
Add n KV hits to the global counter.
void ie_metrics_add_kv_miss (uint64_t n)
Add n KV misses to the global counter.
void ie_metrics_add_kv (uint64_t hits, uint64_t misses)
Add both hits and misses to the global counters.
void ie_metrics_snapshot (ie_metrics_t *out, int reset_after)
Snapshot KV counters into out.
uint32_t ie_metrics_sample_rss_peak (void)
Sample best-effort process peak RSS in MiB.
Variables
static _Atomic uint64_t g_kv_hits = 0
Process-wide KV hit counter (relaxed atomic).
static _Atomic uint64_t g_kv_miss = 0
Process-wide KV miss counter (relaxed atomic).
Detailed Description
Implementation of runtime metrics (KV counters + RSS sampling).
This module backs the helpers declared in util_metrics.h:
Process-wide accumulators for KV hits/misses using C11 atomics.
A best-effort function that samples the process peak RSS in MiB.
Environment:
Set IE_DEBUG_RSS=1 to log which source (VmHWM/VmRSS/smaps_rollup/ getrusage/mach) was used and its raw units before conversion.
Definition in file util_metrics.c.
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 16 of file util_metrics.c.
Function Documentation
dbg()
static void dbg (const char * fmt, ...) static
Debug print controlled by IE_DEBUG_RSS=1.
Parameters
fmt printf-style format string.
Definition at line 75 of file util_metrics.c.
{
  if (!env_flag("IE_DEBUG_RSS")) return;
  va_list ap;
  va_start(ap, fmt);
  vfprintf(stderr, fmt, ap);
  va_end(ap);
}
References env_flag(), and ie_gemv_rowwise_f32_kernel().
Referenced by ie_metrics_sample_rss_peak().
env_flag()
static int env_flag (const char * name) static
Return 1 if the environment variable name is a truthy flag.
Accepted truthy values (case-insensitive):
"1", "true", "yes", "on"
Parameters
name Environment variable name.
Returns
1 if truthy, 0 otherwise.
Definition at line 64 of file util_metrics.c.
{
  const char *s = getenv(name);
  if (!s || !*s) return 0;
  return (!strcasecmp(s, "1") || !strcasecmp(s, "true") ||
          !strcasecmp(s, "yes") || !strcasecmp(s, "on"));
}
References ie_gemv_rowwise_f32_kernel().
Referenced by dbg().
ie_metrics_add_kv()
void ie_metrics_add_kv (uint64_t hits, uint64_t misses)
Add both hits and misses to the global counters.
Add KV cache hits and misses to the process-wide counters.
Parameters
hits Hits to add.
misses Misses to add.
Definition at line 177 of file util_metrics.c.
{
  if (hits)   (void)atomic_fetch_add_explicit(&g_kv_hits, hits,  memory_order_relaxed);
  if (misses) (void)atomic_fetch_add_explicit(&g_kv_miss, misses, memory_order_relaxed);
}
References g_kv_hits, g_kv_miss, and ie_gemv_rowwise_f32_kernel().
ie_metrics_add_kv_hit()
void ie_metrics_add_kv_hit (uint64_t n)
Add n KV hits to the global counter.
Add KV cache hits to the process-wide counter.
Parameters
n Number of hits to add.
Definition at line 167 of file util_metrics.c.
{
  if (!n) return;
  (void)atomic_fetch_add_explicit(&g_kv_hits, n, memory_order_relaxed);
}
References g_kv_hits, and ie_gemv_rowwise_f32_kernel().
ie_metrics_add_kv_miss()
void ie_metrics_add_kv_miss (uint64_t n)
Add n KV misses to the global counter.
Add KV cache misses to the process-wide counter.
Parameters
n Number of misses to add.
Definition at line 172 of file util_metrics.c.
{
  if (!n) return;
  (void)atomic_fetch_add_explicit(&g_kv_miss, n, memory_order_relaxed);
}
References g_kv_miss, and ie_gemv_rowwise_f32_kernel().
ie_metrics_reset()
void ie_metrics_reset (void)
Reset all process-wide counters (KV hits/misses).
Reset all process-wide metrics counters.
Definition at line 162 of file util_metrics.c.
{
  atomic_store_explicit(&g_kv_hits, 0, memory_order_relaxed);
  atomic_store_explicit(&g_kv_miss, 0, memory_order_relaxed);
}
References g_kv_hits, g_kv_miss, and ie_gemv_rowwise_f32_kernel().
ie_metrics_sample_rss_peak()
uint32_t ie_metrics_sample_rss_peak (void)
Sample best-effort process peak RSS in MiB.
Returns
Peak RSS in MiB, or 0 if unavailable.
Definition at line 201 of file util_metrics.c.
{
  uint32_t best_mib = 0;
#if defined(__linux__)
  /* 1) Prefer VmHWM (KiB): process peak resident set size. */
  {
    uint64_t kb = 0;
    const int rc = read_proc_kb_single("/proc/self/status", "VmHWM:", &kb);
    if (rc == 0) {
      const uint32_t mib = kib_to_mib_ceil(kb);
      if (mib > best_mib) best_mib = mib;
      dbg("[RSS] VmHWM: %llu kB -> %u MiB\n", (unsigned long long)kb, mib);
    } else {
      dbg("[RSS] VmHWM not found (rc=%d)\n", rc);
    }
  }
  /* 2) Fallback: VmRSS (KiB): current resident set size. */
  if (best_mib == 0) {
    uint64_t kb = 0;
    const int rc = read_proc_kb_single("/proc/self/status", "VmRSS:", &kb);
    if (rc == 0) {
      const uint32_t mib = kib_to_mib_ceil(kb);
      if (mib > best_mib) best_mib = mib;
      dbg("[RSS] VmRSS: %llu kB -> %u MiB\n", (unsigned long long)kb, mib);
    } else {
      dbg("[RSS] VmRSS not found (rc=%d)\n", rc);
    }
  }
  /* 3) Try smaps_rollup Rss: (KiB): often useful with mmaps. */
  if (best_mib == 0) {
    uint64_t kb = 0;
    const int rc = read_proc_kb_single("/proc/self/smaps_rollup", "Rss:", &kb);
    if (rc == 0) {
      const uint32_t mib = kib_to_mib_ceil(kb);
      if (mib > best_mib) best_mib = mib;
      dbg("[RSS] smaps_rollup Rss: %llu kB -> %u MiB\n", (unsigned long long)kb, mib);
    } else {
      dbg("[RSS] smaps_rollup Rss not found (rc=%d)\n", rc);
    }
  }
  /* 4) Final fallback: getrusage (Linux ru_maxrss is KiB). */
  if (best_mib == 0) {
    struct rusage ru;
    if (getrusage(RUSAGE_SELF, &ru) == 0) {
      const uint64_t kb = (uint64_t)ru.ru_maxrss;
      const uint32_t mib = kib_to_mib_ceil(kb);
      if (mib > best_mib) best_mib = mib;
      dbg("[RSS] getrusage ru_maxrss: %llu kB -> %u MiB\n", (unsigned long long)kb, mib);
    } else {
      dbg("[RSS] getrusage failed: errno=%d\n", errno);
    }
  }
#elif defined(__APPLE__)
  /* macOS primary: mach_task_basic_info (bytes). */
  {
    mach_task_basic_info info;
    mach_msg_type_number_t count = MACH_TASK_BASIC_INFO_COUNT;
    const kern_return_t kr = task_info(mach_task_self(),
                                       MACH_TASK_BASIC_INFO,
                                       (task_info_t)&info,
                                       &count);
    if (kr == KERN_SUCCESS) {
      uint64_t bytes = (uint64_t)info.resident_size_max;
      if (bytes == 0) bytes = (uint64_t)info.resident_size;
      const uint32_t mib = (uint32_t)((bytes + (1024u * 1024u - 1)) / (1024u * 1024u));
      if (mib > best_mib) best_mib = mib;
      dbg("[RSS] mach_task_basic_info: %llu bytes -> %u MiB\n",
          (unsigned long long)bytes, mib);
    } else {
      dbg("[RSS] mach task_info failed: kr=%d\n", (int)kr);
    }
  }
  /* Fallback: getrusage (macOS ru_maxrss is bytes). */
  if (best_mib == 0) {
    struct rusage ru;
    if (getrusage(RUSAGE_SELF, &ru) == 0) {
      const uint64_t bytes = (uint64_t)ru.ru_maxrss;
      const uint32_t mib = (uint32_t)((bytes + (1024u * 1024u - 1)) / (1024u * 1024u));
      if (mib > best_mib) best_mib = mib;
      dbg("[RSS] getrusage ru_maxrss(bytes): %llu -> %u MiB\n",
          (unsigned long long)bytes, mib);
    }
  }
#else
  /* Other OS: getrusage and conservatively treat ru_maxrss as KiB. */
  {
    struct rusage ru;
    if (getrusage(RUSAGE_SELF, &ru) == 0) {
      const uint64_t kb = (uint64_t)ru.ru_maxrss;
      const uint32_t mib = kib_to_mib_ceil(kb);
      if (mib > best_mib) best_mib = mib;
      dbg("[RSS] generic getrusage ru_maxrss: %llu kB -> %u MiB\n",
          (unsigned long long)kb, mib);
    }
  }
#endif
  return best_mib;
}
References dbg(), ie_gemv_rowwise_f32_kernel(), kib_to_mib_ceil(), and read_proc_kb_single().
ie_metrics_snapshot()
void ie_metrics_snapshot (ie_metrics_t * out, int reset_after)
Snapshot KV counters into out.
Parameters
out Destination snapshot (required).
reset_after If nonzero, reset counters after snapshot.
Definition at line 182 of file util_metrics.c.
{
  if (!out) return;
  const uint64_t hits = atomic_load_explicit(&g_kv_hits, memory_order_relaxed);
  const uint64_t miss = atomic_load_explicit(&g_kv_miss, memory_order_relaxed);
  out->kv_hits   = hits;
  out->kv_misses = miss;
  if (reset_after) {
    atomic_store_explicit(&g_kv_hits, 0, memory_order_relaxed);
    atomic_store_explicit(&g_kv_miss, 0, memory_order_relaxed);
  }
}
References g_kv_hits, g_kv_miss, and ie_gemv_rowwise_f32_kernel().
kib_to_mib_ceil()
static uint32_t kib_to_mib_ceil (uint64_t kib) static
Round up KiB to MiB using ceil(), clamped to 32-bit.
Parameters
kib Size in KiB.
Returns
Size in MiB (ceil), or 0 if kib is 0.
Definition at line 88 of file util_metrics.c.
{
  if (kib == 0) return 0u;
  /* ceil(kib/1024) = (kib + 1023) >> 10 */
  const uint64_t mib = (kib + 1023u) >> 10;
  return (mib > 0xFFFFFFFFu) ? 0xFFFFFFFFu : (uint32_t)mib;
}
References ie_gemv_rowwise_f32_kernel().
Referenced by ie_metrics_sample_rss_peak().
parse_status_kb_line()
static int parse_status_kb_line (const char * line, const char * key, uint64_t * out_kb) static
Parse an integer KiB value from a "Key: 12345 kB" style procfs line.
Parameters
line Input line (NUL-terminated).
key Key prefix to match exactly (e.g., "VmHWM:", "VmRSS:", "Rss:").
out_kb Receives the parsed KiB value on success.
Returns
1 if parsed successfully, 0 otherwise.
Definition at line 103 of file util_metrics.c.
{
  if (!line || !key || !out_kb) return 0;
  const size_t klen = strlen(key);
  if (strncmp(line, key, klen) != 0) return 0;
  const char *p = line + klen;
  while (*p == ' ' || *p == '\t') ++p;
  uint64_t val = 0;
  int matched = 0;
  while (*p >= '0' && *p <= '9') {
    matched = 1;
    val = val * 10 + (uint64_t)(*p - '0');
    ++p;
  }
  if (!matched) return 0;
  *out_kb = val;
  return 1;
}
References ie_gemv_rowwise_f32_kernel().
Referenced by read_proc_kb_single().
read_proc_kb_single()
static int read_proc_kb_single (const char * path, const char * key, uint64_t * out_kb) static
Read a single numeric (KiB) field from a procfs text file.
Parameters
path File path (e.g., "/proc/self/status").
key Key to match, e.g., "VmHWM:", "VmRSS:", or "Rss:".
out_kb Receives parsed value (KiB) on success.
Returns
0 on success, -ENOENT if not found, negative errno otherwise.
Definition at line 133 of file util_metrics.c.
{
#if defined(__linux__)
  FILE *f = fopen(path, "r");
  if (!f) return (errno ? -errno : -1);
  char buf[512];
  while (fgets(buf, sizeof buf, f)) {
    uint64_t kb = 0;
    if (parse_status_kb_line(buf, key, &kb)) {
      fclose(f);
      *out_kb = kb;
      return 0;
    }
  }
  fclose(f);
  return -ENOENT;
#else
  (void)path;
  (void)key;
  (void)out_kb;
  return -ENOSYS;
#endif
}
References ie_gemv_rowwise_f32_kernel(), and parse_status_kb_line().
Referenced by ie_metrics_sample_rss_peak().
Variable Documentation
g_kv_hits
_Atomic uint64_t g_kv_hits = 0 static
Process-wide KV hit counter (relaxed atomic).
Definition at line 46 of file util_metrics.c.
Referenced by ie_metrics_add_kv(), ie_metrics_add_kv_hit(), ie_metrics_reset(), and ie_metrics_snapshot().
g_kv_miss
_Atomic uint64_t g_kv_miss = 0 static
Process-wide KV miss counter (relaxed atomic).
Definition at line 49 of file util_metrics.c.
Referenced by ie_metrics_add_kv(), ie_metrics_add_kv_miss(), ie_metrics_reset(), and ie_metrics_snapshot().