Inference Engine (Clocher): engine/include/weights_dedup.h File Reference
weights_dedup.h File Reference
Lossless deduplicated-weights loader (mmap-friendly) and uniform weight view API.
#include <stddef.h>
#include <stdint.h>
Data Structures
struct ie_weight_view
A uniform weight view describing either direct or deduplicated storage.
struct ie_weights_dedup_opts
Options controlling mapping and paging policy.
Macros
#define IE_WDEDUP_MAX_RANK 8
Maximum rank supported for shapes carried in the view.
Typedefs
typedef struct ie_weights_dedup ie_weights_dedup_t
Opaque handle to a deduplicated-weights mapping.
typedef enum ie_wdedup_status ie_wdedup_status_t
Status codes returned by the dedup loader.
typedef enum ie_wdtype ie_wdtype_t
Supported dtypes for dedup views.
typedef enum ie_weight_view_kind ie_weight_view_kind_t
Weight view kind.
typedef struct ie_weight_view ie_weight_view_t
A uniform weight view describing either direct or deduplicated storage.
typedef struct ie_weights_dedup_opts ie_weights_dedup_opts_t
Options controlling mapping and paging policy.
Enumerations
enum ie_wdedup_status {
IE_WDEDUP_OK = 0 , IE_WDEDUP_EINVAL = 1 , IE_WDEDUP_ENOENT = 2 , IE_WDEDUP_EIO = 3 ,
IE_WDEDUP_ENOMEM = 4 , IE_WDEDUP_EFORMAT = 5 , IE_WDEDUP_ERANGE = 6
}
Status codes returned by the dedup loader.
enum ie_wdtype {
IE_WDTYPE_UNKNOWN = 0 , IE_WDTYPE_FP32 , IE_WDTYPE_FP16 , IE_WDTYPE_BF16 ,
IE_WDTYPE_INT8 , IE_WDTYPE_INT4
}
Supported dtypes for dedup views.
enum ie_weight_view_kind { IE_WVIEW_DIRECT = 0 , IE_WVIEW_DEDUP = 1 }
Weight view kind.
Functions
ie_wdedup_status_t ie_weights_dedup_open (ie_weights_dedup_t **out, const char *model_dir, const ie_weights_dedup_opts_t *opts)
Open a deduplicated model directory.
void ie_weights_dedup_close (ie_weights_dedup_t **h)
Close a deduplicated-weights handle and release mappings.
ie_wdedup_status_t ie_weights_dedup_get_weight_view (const ie_weights_dedup_t *h, const char *name, ie_weight_view_t *out)
Lookup a tensor by name and return a uniform view.
size_t ie_weights_dedup_materialize (const ie_weight_view_t *view, void *dst, size_t dst_nbytes)
Materialize a weight view into a contiguous buffer (lossless).
ie_wdtype_t ie_weights_dedup_parse_dtype (const char *s)
Convert a dtype string ("fp32", "int4", ...) to ie_wdtype_t.
Detailed Description
Lossless deduplicated-weights loader (mmap-friendly) and uniform weight view API.
This module loads a deduplicated model representation described by model.dedup.json and maps the backing binary blobs (defaults/exceptions/masks) using mmap(2).
The loader exposes a uniform ie_weights_dedup_get_weight_view() API returning an ie_weight_view_t that can represent either:
A direct contiguous tensor view (rare in dedup artifacts but supported), or
A deduplicated tensor view referencing (defaults + mask + exceptions).
The intent is to keep this loader mmap-friendly:
all large blobs are memory-mapped read-only
tensor views are lightweight pointers into those mappings
A reference materializer (ie_weights_dedup_materialize()) is provided primarily for correctness tests (hash comparison against the non-dedup baseline path) and as a debugging aid.
JSON format expectations (minimal):
A top-level "files" object mapping logical names to relative file paths: { "files": { "defaults": "...bin", "exceptions": "...bin", "masks": "...bin" }, ... }
A top-level "tensors" array, each with:
"name" (string)
"dtype" (string) : "fp32","fp16","bf16","int8","int4" (others may be added later)
"shape" (int array)
"default" / "mask" / "exceptions" objects: { "file": "defaults", "offset": N, "nbytes": M }
The mask is interpreted as a bitset over elements (not bytes):
bit=0 => element equals defaults
bit=1 => element is overridden by the next value in exceptions (packed sequentially)
For int4 tensors, "elements" refers to nibbles (4-bit values) in row-major order.
Note
This header intentionally does not depend on engine-global tensor metadata types. The engine can bridge ie_weight_view_t into its internal representation.
Definition in file weights_dedup.h.
Macro Definition Documentation
IE_WDEDUP_MAX_RANK
#define IE_WDEDUP_MAX_RANK 8
Maximum rank supported for shapes carried in the view.
This is only for metadata conveyance; the engine may ignore shape here if it already has authoritative shape info elsewhere.
Definition at line 96 of file weights_dedup.h.
Typedef Documentation
ie_wdedup_status_t
typedef enum ie_wdedup_status ie_wdedup_status_t
Status codes returned by the dedup loader.
ie_wdtype_t
typedef enum ie_wdtype ie_wdtype_t
Supported dtypes for dedup views.
ie_weight_view_kind_t
typedef enum ie_weight_view_kind ie_weight_view_kind_t
Weight view kind.
ie_weight_view_t
typedef struct ie_weight_view ie_weight_view_t
A uniform weight view describing either direct or deduplicated storage.
For IE_WVIEW_DIRECT:
data points to the contiguous tensor bytes
nbytes is the tensor byte size
For IE_WVIEW_DEDUP:
defaults points to the defaults tensor bytes (same dtype/shape as logical tensor)
mask points to a bitset over elements/nibbles
exceptions points to packed exception values (same dtype packing)
Mask semantics:
bit 0 => use defaults value
bit 1 => consume next value from exceptions stream and override
ie_weights_dedup_opts_t
typedef struct ie_weights_dedup_opts ie_weights_dedup_opts_t
Options controlling mapping and paging policy.
ie_weights_dedup_t
typedef struct ie_weights_dedup ie_weights_dedup_t
Opaque handle to a deduplicated-weights mapping.
Definition at line 1 of file weights_dedup.h.
Enumeration Type Documentation
ie_wdedup_status
enum ie_wdedup_status
Status codes returned by the dedup loader.
Enumerator
IE_WDEDUP_OK
IE_WDEDUP_EINVAL
IE_WDEDUP_ENOENT
IE_WDEDUP_EIO
IE_WDEDUP_ENOMEM
IE_WDEDUP_EFORMAT
IE_WDEDUP_ERANGE
Definition at line 59 of file weights_dedup.h.
{
   IE_WDEDUP_OK = 0,
   IE_WDEDUP_EINVAL = 1,
   IE_WDEDUP_ENOENT = 2,
   IE_WDEDUP_EIO = 3,
   IE_WDEDUP_ENOMEM = 4,
   IE_WDEDUP_EFORMAT = 5,
   IE_WDEDUP_ERANGE = 6
 } ie_wdedup_status_t;
ie_wdtype
enum ie_wdtype
Supported dtypes for dedup views.
Enumerator
IE_WDTYPE_UNKNOWN
IE_WDTYPE_FP32
IE_WDTYPE_FP16
IE_WDTYPE_BF16
IE_WDTYPE_INT8
IE_WDTYPE_INT4
Definition at line 72 of file weights_dedup.h.
{
   IE_WDTYPE_UNKNOWN = 0,
   IE_WDTYPE_FP32,
   IE_WDTYPE_FP16,
   IE_WDTYPE_BF16,
   IE_WDTYPE_INT8,
   IE_WDTYPE_INT4
 } ie_wdtype_t;
ie_weight_view_kind
enum ie_weight_view_kind
Weight view kind.
Enumerator
IE_WVIEW_DIRECT
Direct contiguous bytes.
IE_WVIEW_DEDUP
Defaults + mask + exceptions.
Definition at line 84 of file weights_dedup.h.
{
   IE_WVIEW_DIRECT = 0,
   IE_WVIEW_DEDUP  = 1
 } ie_weight_view_kind_t;
Function Documentation
ie_weights_dedup_close()
void ie_weights_dedup_close (ie_weights_dedup_t ** h)
Close a deduplicated-weights handle and release mappings.
Parameters
[in,out] h Handle to close (set to NULL on return).
Close a deduplicated-weights handle and release mappings.
This unmaps all backing files, frees tensor metadata, and frees the handle.
Parameters
[in,out] h Handle pointer (set to NULL on return).
Definition at line 1088 of file weights_dedup.c.
{
   if (!h || !*h) return;
   ie_weights_dedup_t *x = *h;
   if (x->tensors) {
     for (size_t i = 0; i < x->tensors_count; i++) free(x->tensors[i].name);
     free(x->tensors);
   }
   if (x->files) {
     for (size_t i = 0; i < x->files_count; i++) ie_mmap_close(&x->files[i]);
     free(x->files);
   }
   free(x->model_dir);
   free(x);
   *h = NULL;
 }
References ie_weights_dedup::files, ie_weights_dedup::files_count, ie_mmap_close(), ie_weights_dedup::model_dir, ie_tensor_ref::name, ie_weights_dedup::tensors, and ie_weights_dedup::tensors_count.
Referenced by ie_weights_close(), and ie_weights_dedup_open().
ie_weights_dedup_get_weight_view()
ie_wdedup_status_t ie_weights_dedup_get_weight_view (const ie_weights_dedup_t * h, const char * name, ie_weight_view_t * out)
Lookup a tensor by name and return a uniform view.
The view's pointers remain valid until ie_weights_dedup_close().
Parameters
[in] h Open dedup handle.
[in] name Tensor name.
[out] out Filled view on success.
Returns
IE_WDEDUP_OK if found, otherwise an error code.
Lookup a tensor by name and return a uniform view.
For deduplicated tensors, the returned view points at:
a defaults byte-range (base tensor data),
a bitmask indicating which elements are overridden,
an exceptions stream providing the replacement values.
If a tensor has no mask/exceptions, the view is returned as IE_WVIEW_DIRECT.
Parameters
[in] h Handle.
[in] name Tensor name.
[out] out Output view descriptor.
Returns
Status code.
Definition at line 1122 of file weights_dedup.c.
{
   if (!h || !name || !out) return IE_WDEDUP_EINVAL;
   const ie_tensor_ref_t *tr = ie_find_tensor(h, name);
   if (!tr) return IE_WDEDUP_ENOENT;
   /* validate blob ranges */
   const ie_mmap_file_t *fdef = &h->files[tr->file_defaults];
   const ie_mmap_file_t *fmsk = &h->files[tr->file_mask];
   const ie_mmap_file_t *fexc = &h->files[tr->file_exceptions];
   if (tr->off_defaults + tr->nbytes_defaults > fdef->size) return IE_WDEDUP_ERANGE;
   if (tr->off_mask + tr->nbytes_mask > fmsk->size) return IE_WDEDUP_ERANGE;
   if (tr->off_exceptions + tr->nbytes_exceptions > fexc->size) return IE_WDEDUP_ERANGE;
   memset(out, 0, sizeof(*out));
   out->kind = IE_WVIEW_DEDUP;
   out->dtype = tr->dtype;
   out->rank = tr->rank;
   for (int32_t i = 0; i < tr->rank; i++) out->shape[i] = tr->shape[i];
   out->defaults = (const uint8_t *)fdef->base + (size_t)tr->off_defaults;
   out->defaults_nbytes = (size_t)tr->nbytes_defaults;
   out->mask = (const uint8_t *)fmsk->base + (size_t)tr->off_mask;
   out->mask_nbytes = (size_t)tr->nbytes_mask;
   out->exceptions = (const uint8_t *)fexc->base + (size_t)tr->off_exceptions;
   out->exceptions_nbytes = (size_t)tr->nbytes_exceptions;
   out->elem_count = tr->elem_count;
   out->elem_size = tr->elem_size;
   /* If there are no exceptions and no mask, allow this to be treated as direct. */
   if (out->mask_nbytes == 0 && out->exceptions_nbytes == 0) {
     out->kind = IE_WVIEW_DIRECT;
     out->data = out->defaults;
     out->nbytes = out->defaults_nbytes;
     out->defaults = NULL;
     out->mask = NULL;
     out->exceptions = NULL;
     out->defaults_nbytes = 0;
     out->mask_nbytes = 0;
     out->exceptions_nbytes = 0;
   }
   return IE_WDEDUP_OK;
 }
References ie_mmap_file::base, ie_weight_view::data, ie_weight_view::defaults, ie_weight_view::defaults_nbytes, ie_weight_view::dtype, ie_tensor_ref::dtype, ie_weight_view::elem_count, ie_tensor_ref::elem_count, ie_weight_view::elem_size, ie_tensor_ref::elem_size, ie_weight_view::exceptions, ie_weight_view::exceptions_nbytes, ie_tensor_ref::file_defaults, ie_tensor_ref::file_exceptions, ie_tensor_ref::file_mask, ie_weights_dedup::files, ie_find_tensor(), IE_WDEDUP_EINVAL, IE_WDEDUP_ENOENT, IE_WDEDUP_ERANGE, IE_WDEDUP_OK, IE_WVIEW_DEDUP, IE_WVIEW_DIRECT, ie_weight_view::kind, ie_weight_view::mask, ie_weight_view::mask_nbytes, ie_weight_view::nbytes, ie_tensor_ref::nbytes_defaults, ie_tensor_ref::nbytes_exceptions, ie_tensor_ref::nbytes_mask, ie_tensor_ref::off_defaults, ie_tensor_ref::off_exceptions, ie_tensor_ref::off_mask, ie_weight_view::rank, ie_tensor_ref::rank, ie_weight_view::shape, ie_tensor_ref::shape, and ie_mmap_file::size.
ie_weights_dedup_materialize()
size_t ie_weights_dedup_materialize (const ie_weight_view_t * view, void * dst, size_t dst_nbytes)
Materialize a weight view into a contiguous buffer (lossless).
This is primarily intended for tests:
Load baseline (non-dedup) tensor bytes and hash them.
Load dedup tensor view, materialize into scratch, hash, compare.
For IE_WVIEW_DIRECT, this performs a memcpy. For IE_WVIEW_DEDUP, this reconstructs defaults + overrides according to the mask.
Parameters
[in] view Weight view (direct or dedup).
[out] dst Destination buffer.
[in] dst_nbytes Capacity of destination buffer in bytes.
Returns
Number of bytes written on success, 0 on failure.
Materialize a weight view into a contiguous buffer (lossless).
Behavior:
If view is IE_WVIEW_DIRECT, this copies the referenced bytes verbatim.
If view is IE_WVIEW_DEDUP:
For non-int4 dtypes: copy defaults, then apply per-element overrides from the exceptions stream where the mask bit is set.
For int4: destination is a packed nibble array; defaults are copied, then overridden nibble-by-nibble from the exceptions stream.
The function returns 0 on any validation/size error.
Parameters
[in] view Parsed weight view.
[out] dst Destination buffer.
[in] dst_nbytes Capacity of dst in bytes.
Returns
Number of bytes written to dst, or 0 on failure.
Definition at line 1238 of file weights_dedup.c.
{
   if (!view || !dst) return 0;
   if (view->kind == IE_WVIEW_DIRECT) {
     if (!view->data) return 0;
     if (view->nbytes > dst_nbytes) return 0;
     memcpy(dst, view->data, view->nbytes);
     return view->nbytes;
   }
   if (view->kind != IE_WVIEW_DEDUP) return 0;
   if (!view->defaults || !view->mask) return 0;
   /* fp/int8 path: copy defaults then override elementwise */
   if (view->dtype != IE_WDTYPE_INT4) {
     if (view->elem_size == 0) return 0;
     size_t need = view->elem_count * view->elem_size;
     if (need > dst_nbytes) return 0;
     if (view->defaults_nbytes < need) return 0;
     memcpy(dst, view->defaults, need);
     const uint8_t *exc = (const uint8_t *)view->exceptions;
     size_t exc_off = 0;
     for (size_t i = 0; i < view->elem_count; i++) {
       if (!ie_bitset_get(view->mask, i)) continue;
       if (exc_off + view->elem_size > view->exceptions_nbytes) return 0;
       uint8_t *dst_b = (uint8_t *)dst + i * view->elem_size;
       memcpy(dst_b, exc + exc_off, view->elem_size);
       exc_off += view->elem_size;
     }
     /* It is valid for exceptions_nbytes to have padding; we only require not to underflow. */
     return need;
   }
   /* int4 path: dst is packed int4 bytes. */
   {
     size_t need = view->defaults_nbytes;
     if (need > dst_nbytes) return 0;
     if (view->defaults_nbytes == 0) return 0;
     memcpy(dst, view->defaults, need);
     const uint8_t *exc_bytes = (const uint8_t *)view->exceptions;
     size_t exc_nibbles = view->exceptions_nbytes * 2;
     size_t exc_idx = 0;
     for (size_t i = 0; i < view->elem_count; i++) {
       if (!ie_bitset_get(view->mask, i)) continue;
       if (exc_idx >= exc_nibbles) return 0;
       uint8_t v = ie_int4_get_nibble(exc_bytes, exc_idx++);
       ie_int4_set_nibble((uint8_t *)dst, i, v);
     }
     return need;
   }
 }
References ie_weight_view::data, ie_weight_view::defaults, ie_weight_view::defaults_nbytes, ie_weight_view::dtype, ie_weight_view::elem_count, ie_weight_view::elem_size, ie_weight_view::exceptions, ie_weight_view::exceptions_nbytes, ie_bitset_get(), ie_int4_get_nibble(), ie_int4_set_nibble(), IE_WDTYPE_INT4, IE_WVIEW_DEDUP, IE_WVIEW_DIRECT, ie_weight_view::kind, ie_weight_view::mask, and ie_weight_view::nbytes.
Referenced by hash_view().
ie_weights_dedup_open()
ie_wdedup_status_t ie_weights_dedup_open (ie_weights_dedup_t ** out, const char * model_dir, const ie_weights_dedup_opts_t * opts)
Open a deduplicated model directory.
This function expects to find model.dedup.json inside model_dir. It mmaps referenced files (defaults/exceptions/masks) read-only.
Parameters
[out] out Returned handle on success.
[in] model_dir Directory containing model.dedup.json and blobs.
[in] opts Optional mapping options (may be NULL).
Returns
IE_WDEDUP_OK on success, otherwise an error code.
Open a deduplicated model directory.
Reads model.dedup.json, mmaps the referenced backing files, parses the tensor table, and sorts it by tensor name for fast binary-search lookups.
Parameters
[out] out Output handle.
[in] model_dir Directory containing model.dedup.json and backing files.
[in] opts Options (may be NULL).
Returns
Status code.
Definition at line 996 of file weights_dedup.c.
{
   if (!out || !model_dir) return IE_WDEDUP_EINVAL;
   *out = NULL;
   ie_weights_dedup_t *h = (ie_weights_dedup_t *)calloc(1, sizeof(*h));
   if (!h) return IE_WDEDUP_ENOMEM;
   h->prefault_policy = opts ? opts->prefault_policy : 0;
   h->model_dir = ie_strdup(model_dir);
   if (!h->model_dir) { free(h); return IE_WDEDUP_ENOMEM; }
   char *json_path = ie_path_join(model_dir, "model.dedup.json");
   if (!json_path) { ie_weights_dedup_close(&h); return IE_WDEDUP_ENOMEM; }
   size_t json_n = 0;
   char *json = ie_read_file_text(json_path, &json_n);
   free(json_path);
   if (!json) { ie_weights_dedup_close(&h); return IE_WDEDUP_ENOENT; }
   /* parse top-level files */
   const char *files_val = NULL;
   if (!js_find_member_value(json, "files", &files_val)) {
     free(json);
     ie_weights_dedup_close(&h);
     return IE_WDEDUP_EFORMAT;
   }
   ie_file_ref_t *files = NULL;
   size_t files_n = 0;
   ie_wdedup_status_t st = ie_parse_files_object(files_val, &files, &files_n);
   if (st != IE_WDEDUP_OK) {
     free(json);
     ie_weights_dedup_close(&h);
     return st;
   }
   /* mmap each file */
   h->files = (ie_mmap_file_t *)calloc(files_n, sizeof(*h->files));
   if (!h->files) {
     for (size_t i = 0; i < files_n; i++) { free(files[i].logical); free(files[i].relpath); }
     free(files);
     free(json);
     ie_weights_dedup_close(&h);
     return IE_WDEDUP_ENOMEM;
   }
   h->files_count = files_n;
   for (size_t i = 0; i < files_n; i++) {
     char *full = ie_path_join(model_dir, files[i].relpath);
     if (!full) { st = IE_WDEDUP_ENOMEM; break; }
     st = ie_mmap_ro(&h->files[i], full, h->prefault_policy);
     free(full);
     if (st != IE_WDEDUP_OK) break;
   }
   /* parse tensors */
   if (st == IE_WDEDUP_OK) {
     const char *tensors_val = NULL;
     if (!js_find_member_value(json, "tensors", &tensors_val)) {
       st = IE_WDEDUP_EFORMAT;
     } else {
       st = ie_parse_tensors_array(tensors_val, files, files_n, &h->tensors, &h->tensors_count);
       if (st == IE_WDEDUP_OK && h->tensors_count > 1) {
         qsort(h->tensors, h->tensors_count, sizeof(h->tensors[0]), ie_tensor_cmp_name);
       }
     }
   }
   /* cleanup file-ref table + json buffer */
   for (size_t i = 0; i < files_n; i++) { free(files[i].logical); free(files[i].relpath); }
   free(files);
   free(json);
   if (st != IE_WDEDUP_OK) {
     ie_weights_dedup_close(&h);
     return st;
   }
   *out = h;
   return IE_WDEDUP_OK;
 }
References ie_weights_dedup::files, ie_weights_dedup::files_count, ie_mmap_ro(), ie_parse_files_object(), ie_parse_tensors_array(), ie_path_join(), ie_read_file_text(), ie_strdup(), ie_tensor_cmp_name(), IE_WDEDUP_EFORMAT, IE_WDEDUP_EINVAL, IE_WDEDUP_ENOENT, IE_WDEDUP_ENOMEM, IE_WDEDUP_OK, ie_weights_dedup_close(), js_find_member_value(), ie_weights_dedup::model_dir, ie_weights_dedup_opts::prefault_policy, ie_weights_dedup::prefault_policy, ie_weights_dedup::tensors, and ie_weights_dedup::tensors_count.
Referenced by ie_weights_open().
ie_weights_dedup_parse_dtype()
ie_wdtype_t ie_weights_dedup_parse_dtype (const char * s)
Convert a dtype string ("fp32", "int4", ...) to ie_wdtype_t.
Parameters
[in] s NUL-terminated dtype string.
Returns
Parsed dtype or IE_WDTYPE_UNKNOWN.
Convert a dtype string ("fp32", "int4", ...) to ie_wdtype_t.
Parameters
[in] s Dtype string (e.g., "fp16", "int4").
Returns
Parsed dtype enum value (or IE_WDTYPE_UNKNOWN).
Definition at line 564 of file weights_dedup.c.
{
   if (!s) return IE_WDTYPE_UNKNOWN;
   if (strcmp(s, "fp32") == 0) return IE_WDTYPE_FP32;
   if (strcmp(s, "fp16") == 0) return IE_WDTYPE_FP16;
   if (strcmp(s, "bf16") == 0) return IE_WDTYPE_BF16;
   if (strcmp(s, "int8") == 0) return IE_WDTYPE_INT8;
   if (strcmp(s, "int4") == 0) return IE_WDTYPE_INT4;
   return IE_WDTYPE_UNKNOWN;
 }
References IE_WDTYPE_BF16, IE_WDTYPE_FP16, IE_WDTYPE_FP32, IE_WDTYPE_INT4, IE_WDTYPE_INT8, and IE_WDTYPE_UNKNOWN.
Referenced by ie_parse_one_tensor().