Inference Engine (Clocher): engine/src/io/weights.c File Reference
weights.c File Reference
IEBIN v1 loader with relaxed JSON scanning and detailed diagnostics.
#include "ie_io.h"
#include "util_logging.h"
#include "weights_dedup.h"
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
Macros
#define _POSIX_C_SOURCE 200809L
#define IE_WEIGHTS_HAS_DEDUP_FIELDS 1
#define IE_WEIGHTS_ENABLE_INT4_DIAGNOSTICS 0
#define WLOGI(...)
Emit an info log if info logging is enabled.
#define WLOGD(...)
Emit a debug log if debug logging is enabled.
#define WLOGW(...)
Emit a warning log if info logging is enabled.
#define WLOGE(...)
Emit an error log if error logging is enabled.
Functions
static int ie_weights_log_level (void)
Read IE_LOG_LEVEL once and cache it for the process lifetime.
static int ie_weights_log_enabled (int level)
Return non-zero if the requested logging level is enabled.
static void wlog_errno_ (const char *what, const char *path)
Log an errno-based failure with contextual path information.
static const char * skip_ws (const char *p)
Skip ASCII whitespace characters in a string.
static void cpyz (char *dst, size_t dstsz, const char *src)
Copy a C-string into a bounded buffer and always NUL-terminate.
static const char * last_slash (const char *p)
Return a pointer to the last '/' in a path, or NULL if none.
static void join_path (char *out, size_t outsz, const char *dir, const char *file)
Join directory and filename into an output buffer (NUL-terminated).
static int read_all_text (const char *path, char **buf, size_t *len_out)
Read an entire file into a newly allocated NUL-terminated buffer.
static int scan_json_key_int (const char *json, const char *key, int *out_val)
Scan a relaxed JSON blob for an integer value at a given key.
static size_t json_unescape_into (char *dst, size_t dstsz, const char *src, size_t srclen)
Unescape a JSON string into a destination buffer (best-effort).
static int scan_json_key_string (const char *json, const char *key, char *dst, size_t dstsz)
Scan a relaxed JSON blob for a string value at a given key.
static int scan_json_object_range (const char *json, const char *key, const char **out_begin, const char **out_end)
Locate the interior byte range of an object value "{ ... }" for a key.
static int scan_json_key_string_in_range (const char *begin, const char *end, const char *key, char *dst, size_t dstsz)
Scan for a string key within a bounded [begin,end] range.
static int scan_json_best_effort_bin (const char *json, char *dst, size_t dstsz)
Try multiple schema variants to locate the weights binary path.
static ssize_t ie_pread (int fd, void *buf, size_t count, off_t offset)
Portable pread wrapper with fallback.
static int ascii_ieq (const char *a, const char *b)
ASCII-only case-insensitive equality.
static int env_flag_get (const char *name, int default_value)
Parse environment flag-like strings into a boolean.
static int file_exists_readable (const char *path)
Check if a path exists and is readable.
static int write_all_bytes_ (const char *path, const void *data, size_t len)
Create a best-effort model.dedup.json manifest for runtime dedup.
static int find_dedup_manifest_source_ (const char *dir, char *out_rel, size_t out_rel_n, char *out_abs, size_t out_abs_n)
static int ensure_dedup_manifest_link (const char *dir)
static int touch_file_small (const char *path)
Touch a file by doing small reads near start/end.
int ie_weights_open (const char *json_path, const char *bin_path, ie_weights_t *out)
Open and parse an IEBIN v1 model description.
int ie_weights_touch (const ie_weights_t *w)
Touch the weights binary to verify readability and warm OS caches.
void ie_weights_close (ie_weights_t *w)
Close an opened weights descriptor and release optional dedup handles.
Detailed Description
IEBIN v1 loader with relaxed JSON scanning and detailed diagnostics.
This module implements a minimal dependency, plain-C loader for the IEBIN v1 artifact pair:
model.ie.json (metadata and tensor descriptors)
model.ie.bin (raw tensor bytes, typically mmap'd by higher layers)
The loader is intentionally tolerant to extra fields and formatting changes in the JSON file. It does not use a third-party JSON parser. Instead, it performs targeted scans for a small set of required keys.
Logging
All logs in this module go to stderr via util_logging and will not interfere with stdout JSON outputs from benchmarks or CLI tools.
Logging verbosity is controlled via environment variable IE_LOG_LEVEL:
0: silent
1: errors only
2: errors + warnings + info (default)
3: errors + warnings + info + debug
The log messages are designed to make failures actionable by printing:
Which file path was attempted (json/bin/dedup artifacts)
Which schema keys were found or missing
File sizes and short-read conditions
Dedup enable/strict flags and decision outcomes
Definition in file weights.c.
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 38 of file weights.c.
IE_WEIGHTS_ENABLE_INT4_DIAGNOSTICS
#define IE_WEIGHTS_ENABLE_INT4_DIAGNOSTICS 0
Definition at line 73 of file weights.c.
IE_WEIGHTS_HAS_DEDUP_FIELDS
#define IE_WEIGHTS_HAS_DEDUP_FIELDS 1
Definition at line 59 of file weights.c.
WLOGD
#define WLOGD (...)
Value:
  do {                             \
    if (ie_weights_log_enabled(3)) \
      ie_log_info(__VA_ARGS__);    \
  } while (0)
Emit a debug log if debug logging is enabled.
Definition at line 149 of file weights.c.
     {                             \
    if (ie_weights_log_enabled(3)) \
      ie_log_info(__VA_ARGS__);    \
  } while (0)
WLOGE
#define WLOGE (...)
Value:
  do {                             \
    if (ie_weights_log_enabled(1)) \
      ie_log_error(__VA_ARGS__);   \
  } while (0)
Emit an error log if error logging is enabled.
Definition at line 163 of file weights.c.
     {                             \
    if (ie_weights_log_enabled(1)) \
      ie_log_error(__VA_ARGS__);   \
  } while (0)
WLOGI
#define WLOGI (...)
Value:
  do {                             \
    if (ie_weights_log_enabled(2)) \
      ie_log_info(__VA_ARGS__);    \
  } while (0)
Emit an info log if info logging is enabled.
Definition at line 142 of file weights.c.
     {                             \
    if (ie_weights_log_enabled(2)) \
      ie_log_info(__VA_ARGS__);    \
  } while (0)
WLOGW
#define WLOGW (...)
Value:
  do {                             \
    if (ie_weights_log_enabled(2)) \
      ie_log_warn(__VA_ARGS__);    \
  } while (0)
Emit a warning log if info logging is enabled.
Definition at line 156 of file weights.c.
     {                             \
    if (ie_weights_log_enabled(2)) \
      ie_log_warn(__VA_ARGS__);    \
  } while (0)
Function Documentation
ascii_ieq()
static int ascii_ieq (const char * a, const char * b) static
ASCII-only case-insensitive equality.
Parameters
a NUL-terminated string.
b NUL-terminated string.
Returns
1 if equal (ASCII case-insensitive), else 0.
Definition at line 736 of file weights.c.
{
  if (!a || !b) return 0;
  while (*a && *b) {
    if ((unsigned char)tolower((unsigned char)*a) != (unsigned char)tolower((unsigned char)*b)) {
      return 0;
    }
    ++a;
    ++b;
  }
  return *a == '\0' && *b == '\0';
}
Referenced by env_flag_get().
cpyz()
static void cpyz (char * dst, size_t dstsz, const char * src) static
Copy a C-string into a bounded buffer and always NUL-terminate.
Parameters
dst Destination buffer (may be NULL).
dstsz Capacity in bytes.
src Source string (may be NULL).
Definition at line 207 of file weights.c.
{
  if (!dst || dstsz == 0) return;
  if (!src) {
    dst[0] = '\0';
    return;
  }
  size_t n = strlen(src);
  if (n >= dstsz) n = dstsz - 1;
  memcpy(dst, src, n);
  dst[n] = '\0';
}
Referenced by find_dedup_manifest_source_(), ie_weights_open(), ie_weights_touch(), and join_path().
ensure_dedup_manifest_link()
static int ensure_dedup_manifest_link (const char * dir) static
Definition at line 867 of file weights.c.
{
  if (!dir || !*dir) return 0;
  char linkpath[512];
  linkpath[0] = '\0';
  join_path(linkpath, sizeof(linkpath), dir, "model.dedup.json");
  if (file_exists_readable(linkpath)) {
    WLOGD("ensure_dedup_manifest_link: already exists path='%s'", linkpath);
    return 1;
  }
  char src_rel[512];
  char src_abs[512];
  src_rel[0] = src_abs[0] = '\0';
  if (!find_dedup_manifest_source_(dir, src_rel, sizeof(src_rel), src_abs, sizeof(src_abs))) {
    WLOGD("ensure_dedup_manifest_link: no manifest candidates found in dir='%s'", dir);
    return 0;
  }
  WLOGI("ensure_dedup_manifest_link: creating model.dedup.json from source rel='%s' abs='%s'", src_rel,
        src_abs);
  int linked = 0;
  errno = 0;
  if (symlink(src_rel, linkpath) == 0 || errno == EEXIST) {
    linked = 1;
  } else {
    wlog_errno_("symlink", linkpath);
  }
  if (!file_exists_readable(linkpath)) {
    /* Fall back to a direct copy (some environments disallow symlink). */
    char *buf = NULL;
    size_t len = 0;
    if (read_all_text(src_abs, &buf, &len) == 0 && buf && len > 0) {
      if (write_all_bytes_(linkpath, buf, len)) {
        linked = 1;
      } else {
        WLOGW("ensure_dedup_manifest_link: copy failed dst='%s'", linkpath);
      }
    } else {
      WLOGW("ensure_dedup_manifest_link: failed to read source '%s'", src_abs);
    }
    free(buf);
  }
  if (!file_exists_readable(linkpath)) {
    WLOGW("ensure_dedup_manifest_link: model.dedup.json still not readable path='%s'", linkpath);
    return 0;
  }
  WLOGD("ensure_dedup_manifest_link: ok path='%s' (via %s)", linkpath, linked ? "link/copy" : "unknown");
  return 1;
}
References file_exists_readable(), find_dedup_manifest_source_(), join_path(), read_all_text(), wlog_errno_(), WLOGD, WLOGI, WLOGW, and write_all_bytes_().
Referenced by ie_weights_open(), and ie_weights_touch().
env_flag_get()
static int env_flag_get (const char * name, int default_value) static
Parse environment flag-like strings into a boolean.
Accepts: 0/1, false/true, no/yes, off/on (ASCII case-insensitive). Unknown values default to enabled (1).
Parameters
name Environment variable name.
default_value Default value if not set/empty.
Returns
0 or 1.
Definition at line 759 of file weights.c.
{
  const char *v = getenv(name);
  if (!v || !*v) return default_value;
  if (ascii_ieq(v, "0") || ascii_ieq(v, "false") || ascii_ieq(v, "no") || ascii_ieq(v, "off"))
    return 0;
  if (ascii_ieq(v, "1") || ascii_ieq(v, "true") || ascii_ieq(v, "yes") || ascii_ieq(v, "on"))
    return 1;
  return 1;
}
References ascii_ieq().
Referenced by ie_weights_open(), and ie_weights_touch().
file_exists_readable()
static int file_exists_readable (const char * path) static
Check if a path exists and is readable.
Parameters
path NUL-terminated path.
Returns
1 if readable, else 0.
Definition at line 775 of file weights.c.
{
  if (!path || !*path) return 0;
  return access(path, R_OK) == 0;
}
Referenced by ensure_dedup_manifest_link(), find_dedup_manifest_source_(), ie_weights_open(), and ie_weights_touch().
find_dedup_manifest_source_()
static int find_dedup_manifest_source_ (const char * dir, char * out_rel, size_t out_rel_n, char * out_abs, size_t out_abs_n) static
Definition at line 812 of file weights.c.
{
  if (!dir || !*dir || !out_rel || !out_abs || out_rel_n == 0 || out_abs_n == 0) return 0;
  out_rel[0] = '\0';
  out_abs[0] = '\0';
  /* 1) Explicit override: IE_DEDUP_MANIFEST may be absolute or relative. */
  const char *env = getenv("IE_DEDUP_MANIFEST");
  if (env && *env) {
    if (env[0] == '/') {
      if (file_exists_readable(env)) {
        cpyz(out_rel, out_rel_n, env);
        cpyz(out_abs, out_abs_n, env);
        return 1;
      }
    } else {
      char cand[512];
      cand[0] = '\0';
      join_path(cand, sizeof(cand), dir, env);
      if (file_exists_readable(cand)) {
        cpyz(out_rel, out_rel_n, env);
        cpyz(out_abs, out_abs_n, cand);
        return 1;
      }
    }
  }
  /* 2) Common alternative names produced by different toolchains. */
  const char *cands[] = {
      "dedup_manifest.json",
      "manifest.dedup.json",
      "manifest_dedup.json",
      "model.dedup.manifest.json",
      "dedup/model.dedup.json",
      "dedup/manifest.json",
      "dedup/manifest.dedup.json",
  };
  for (size_t i = 0; i < (sizeof(cands) / sizeof(cands[0])); ++i) {
    char abs[512];
    abs[0] = '\0';
    join_path(abs, sizeof(abs), dir, cands[i]);
    if (file_exists_readable(abs)) {
      cpyz(out_rel, out_rel_n, cands[i]);
      cpyz(out_abs, out_abs_n, abs);
      return 1;
    }
  }
  return 0;
}
References cpyz(), file_exists_readable(), and join_path().
Referenced by ensure_dedup_manifest_link().
ie_pread()
static ssize_t ie_pread (int fd, void * buf, size_t count, off_t offset) static
Portable pread wrapper with fallback.
When pread(2) is unavailable, falls back to lseek+read and restores the file offset. This is slower but sufficient for small diagnostic reads.
Parameters
fd Open file descriptor.
buf Destination buffer.
count Number of bytes to read.
offset Offset from start.
Returns
Bytes read, or -1 on error.
Definition at line 716 of file weights.c.
{
#if defined(_XOPEN_SOURCE) || defined(_POSIX_C_SOURCE)
  return pread(fd, buf, count, offset);
#else
  off_t cur = lseek(fd, 0, SEEK_CUR);
  if (cur == (off_t)-1) return -1;
  if (lseek(fd, offset, SEEK_SET) == (off_t)-1) return -1;
  ssize_t r = read(fd, buf, count);
  (void)lseek(fd, cur, SEEK_SET);
  return r;
#endif
}
Referenced by ie_weights_touch(), and touch_file_small().
ie_weights_close()
void ie_weights_close (ie_weights_t * w)
Close an opened weights descriptor and release optional dedup handles.
Close an opened weights descriptor.
This function is idempotent and safe to call on partially initialized structures. It does not unlink or delete any files; it only releases in-memory handles.
Parameters
w Weights descriptor (may be NULL).
Definition at line 1356 of file weights.c.
{
  if (!w) return;
  WLOGD("ie_weights_close: begin loaded=%d is_dedup=%d", w->loaded, w->is_dedup);
#if (IE_WEIGHTS_HAS_DEDUP_FIELDS == 1)
  if (w->is_dedup && w->dedup_handle) {
    ie_weights_dedup_t *dh = (ie_weights_dedup_t *)w->dedup_handle;
    ie_weights_dedup_close(&dh);
    w->dedup_handle = NULL;
    w->is_dedup = 0;
    WLOGD("ie_weights_close: dedup handle released");
  }
#endif
}
References ie_weights_s::dedup_handle, ie_weights_dedup_close(), ie_weights_s::is_dedup, ie_weights_s::loaded, and WLOGD.
Referenced by ie_engine_create(), ie_engine_destroy(), main(), main(), and open_and_touch().
ie_weights_log_enabled()
static int ie_weights_log_enabled (int level) static
Return non-zero if the requested logging level is enabled.
Parameters
level 1=error, 2=info, 3=debug.
Returns
1 if enabled, else 0.
Definition at line 137 of file weights.c.
{
  return ie_weights_log_level() >= level;
}
References ie_weights_log_level().
Referenced by wlog_errno_().
ie_weights_log_level()
static int ie_weights_log_level (void) static
Read IE_LOG_LEVEL once and cache it for the process lifetime.
This module uses a local log level cache to avoid repeated getenv calls. The log level defaults to 2 (info) to aid diagnostics during development.
Returns
Cached log level in range [0,3].
Definition at line 99 of file weights.c.
{
  static int init = 0;
  static int lvl = 2; /* Default: info. */
  if (init) return lvl;
  init = 1;
  const char *v = getenv("IE_LOG_LEVEL");
  if (!v || !*v) return lvl;
  char *end = NULL;
  long x = strtol(v, &end, 10);
  if (end && end != v) {
    if (x < 0) x = 0;
    if (x > 3) x = 3;
    lvl = (int)x;
    return lvl;
  }
  /* Best-effort string forms. */
  if (strcasecmp(v, "silent") == 0 || strcasecmp(v, "quiet") == 0) {
    lvl = 0;
  } else if (strcasecmp(v, "error") == 0 || strcasecmp(v, "errors") == 0) {
    lvl = 1;
  } else if (strcasecmp(v, "info") == 0) {
    lvl = 2;
  } else if (strcasecmp(v, "debug") == 0) {
    lvl = 3;
  }
  return lvl;
}
Referenced by ie_weights_log_enabled().
ie_weights_open()
int ie_weights_open (const char * json_path, const char * bin_path, ie_weights_t * out)
Open and parse an IEBIN v1 model description.
This function:
reads model.ie.json,
parses minimal metadata (version, dtype),
resolves the path to model.ie.bin using overrides and schema variants,
validates the weights binary size via stat(2),
optionally opens dedup artifacts when enabled.
In all error cases, the output structure is left in a safe-to-close state.
Parameters
json_path Path to model.ie.json.
bin_path Optional override for the binary path (may be NULL).
out Output weights descriptor.
Returns
IE_IO_OK on success; negative ie_io_status_t on failure.
Definition at line 988 of file weights.c.
{
  if (!out) return IE_IO_ERR_ARGS;
  memset(out, 0, sizeof(*out));
  if (!json_path || !*json_path) return IE_IO_ERR_ARGS;
  cpyz(out->json_path, sizeof(out->json_path), json_path);
  WLOGI("ie_weights_open: begin json_path='%s' bin_override='%s'", json_path,
        (bin_path && *bin_path) ? bin_path : "");
  char *jbuf = NULL;
  size_t jlen = 0;
  if (read_all_text(json_path, &jbuf, &jlen) != 0 || !jbuf || jlen == 0) {
    WLOGE("ie_weights_open: failed to read json (path='%s')", json_path);
    return IE_IO_ERR_JSON;
  }
  WLOGD("ie_weights_open: loaded json bytes=%zu", jlen);
  int ver = 0;
  int found_ver = scan_json_key_int(jbuf, "version", &ver);
  if (ver <= 0) ver = 1;
  out->version = ver;
  char dtype[16];
  dtype[0] = '\0';
  (void)scan_json_key_string(jbuf, "dtype", dtype, sizeof(dtype));
  if (dtype[0] == '\0') cpyz(dtype, sizeof(dtype), "float32");
  cpyz(out->dtype, sizeof(out->dtype), dtype);
  WLOGI("ie_weights_open: parsed version=%d (found=%d) dtype='%s'", out->version, found_ver,
        out->dtype);
  char resolved_bin[512];
  resolved_bin[0] = '\0';
  /* Priority order:
   *  1) explicit bin_path parameter
   *  2) IE_WEIGHTS_BIN env override
   *  3) JSON keys (bin / weights_bin / nested weights{bin} / iebin{bin})
   *  4) fallback: sibling 'model.ie.bin' next to json_path
   */
  if (bin_path && *bin_path) {
    cpyz(resolved_bin, sizeof(resolved_bin), bin_path);
    WLOGI("ie_weights_open: using bin override (arg) path='%s'", resolved_bin);
  } else {
    const char *env_bin = getenv("IE_WEIGHTS_BIN");
    if (env_bin && *env_bin) {
      cpyz(resolved_bin, sizeof(resolved_bin), env_bin);
      WLOGI("ie_weights_open: using bin override (env IE_WEIGHTS_BIN) path='%s'", resolved_bin);
    } else {
      char bin_key[256];
      bin_key[0] = '\0';
      const int found_bin_key = scan_json_best_effort_bin(jbuf, bin_key, sizeof(bin_key));
      if (found_bin_key == 1 && bin_key[0] != '\0') {
        const char *slash = last_slash(json_path);
        if (slash) {
          char dir[512];
          size_t dn = (size_t)(slash - json_path);
          if (dn >= sizeof(dir)) dn = sizeof(dir) - 1;
          memcpy(dir, json_path, dn);
          dir[dn] = '\0';
          join_path(resolved_bin, sizeof(resolved_bin), dir, bin_key);
          WLOGI("ie_weights_open: resolved bin from json key='%s' dir='%s' => '%s'", bin_key, dir,
                resolved_bin);
        } else {
          cpyz(resolved_bin, sizeof(resolved_bin), bin_key);
          WLOGI("ie_weights_open: resolved bin from json key='%s' => '%s'", bin_key, resolved_bin);
        }
      } else {
        const char *slash = last_slash(json_path);
        char dir[512];
        dir[0] = '\0';
        if (slash) {
          size_t dn = (size_t)(slash - json_path);
          if (dn >= sizeof(dir)) dn = sizeof(dir) - 1;
          memcpy(dir, json_path, dn);
          dir[dn] = '\0';
        } else {
          cpyz(dir, sizeof(dir), ".");
        }
        char fallback[512];
        fallback[0] = '\0';
        join_path(fallback, sizeof(fallback), dir, "model.ie.bin");
        if (file_exists_readable(fallback)) {
          cpyz(resolved_bin, sizeof(resolved_bin), fallback);
          WLOGW(
              "ie_weights_open: JSON did not specify weights bin path; defaulting to sibling "
              "model.ie.bin path='%s'",
              resolved_bin);
        } else {
          WLOGE("ie_weights_open: missing weights bin path in JSON (no known key matched)");
          WLOGE("ie_weights_open: also missing fallback sibling path='%s'", fallback);
          free(jbuf);
          return IE_IO_ERR_BIN_UNSPEC;
        }
      }
    }
  }
  cpyz(out->weights_path, sizeof(out->weights_path), resolved_bin);
  struct stat st;
  if (stat(out->weights_path, &st) != 0 || st.st_size < 0) {
    wlog_errno_("stat", out->weights_path);
    WLOGE("ie_weights_open: weights binary not accessible path='%s'", out->weights_path);
    free(jbuf);
    return IE_IO_ERR_STAT;
  }
  out->bin_size_bytes = (size_t)st.st_size;
  out->loaded = 1;
  WLOGI("ie_weights_open: weights binary ok path='%s' size_bytes=%zu", out->weights_path,
        out->bin_size_bytes);
#if (IE_WEIGHTS_HAS_DEDUP_FIELDS == 1)
  {
    const int dedup_enabled = env_flag_get("IE_DEDUP", 0);
    const int dedup_strict = env_flag_get("IE_DEDUP_STRICT", 0);
    WLOGD("ie_weights_open: dedup flags IE_DEDUP=%d IE_DEDUP_STRICT=%d", dedup_enabled,
          dedup_strict);
    if (dedup_enabled) {
      const char *slash = last_slash(json_path);
      char dir[512];
      dir[0] = '\0';
      if (slash) {
        size_t dn = (size_t)(slash - json_path);
        if (dn >= sizeof(dir)) dn = sizeof(dir) - 1;
        memcpy(dir, json_path, dn);
        dir[dn] = '\0';
      } else {
        cpyz(dir, sizeof(dir), ".");
      }
      char dedup_json[512];
      dedup_json[0] = '\0';
      join_path(dedup_json, sizeof(dedup_json), dir, "model.dedup.json");
      if (!file_exists_readable(dedup_json)) {
        WLOGI("ie_weights_open: dedup enabled but model.dedup.json missing; attempting link");
        (void)ensure_dedup_manifest_link(dir);
      }
      if (file_exists_readable(dedup_json)) {
        ie_weights_dedup_opts_t opts;
        memset(&opts, 0, sizeof(opts));
        opts.prefault_policy = 0;
        ie_weights_dedup_t *dh = NULL;
        ie_wdedup_status_t dst = ie_weights_dedup_open(&dh, dir, &opts);
        if (dst == IE_WDEDUP_OK && dh) {
          out->is_dedup = 1;
          out->dedup_handle = (void *)dh;
          WLOGI("ie_weights_open: dedup artifacts opened (dir='%s')", dir);
        } else {
          WLOGW("ie_weights_open: dedup open failed (status=%d dir='%s')", (int)dst, dir);
          if (dedup_strict) {
            WLOGE("ie_weights_open: dedup strict mode: failing open");
            free(jbuf);
            return IE_IO_ERR_JSON;
          }
          out->is_dedup = 0;
          out->dedup_handle = NULL;
        }
      } else {
        WLOGW("ie_weights_open: dedup enabled but model.dedup.json still missing (dir='%s')", dir);
        if (dedup_strict) {
          WLOGE("ie_weights_open: dedup strict mode: failing open");
          free(jbuf);
          return IE_IO_ERR_JSON;
        }
      }
    }
  }
#endif
  free(jbuf);
  WLOGI("ie_weights_open: success");
  return IE_IO_OK;
}
References cpyz(), ensure_dedup_manifest_link(), env_flag_get(), file_exists_readable(), IE_IO_ERR_ARGS, IE_IO_ERR_BIN_UNSPEC, IE_IO_ERR_JSON, IE_IO_ERR_STAT, IE_IO_OK, IE_WDEDUP_OK, ie_weights_dedup_open(), join_path(), last_slash(), ie_weights_dedup_opts_t::prefault_policy, read_all_text(), scan_json_best_effort_bin(), scan_json_key_int(), scan_json_key_string(), wlog_errno_(), WLOGD, WLOGE, WLOGI, and WLOGW.
Referenced by ie_engine_create(), main(), main(), and open_and_touch().
ie_weights_touch()
int ie_weights_touch (const ie_weights_t * w)
Touch the weights binary to verify readability and warm OS caches.
This performs small reads near the start and end of the binary. When dedup is enabled, also checks auxiliary dedup files.
Parameters
w Opened weights descriptor.
Returns
IE_IO_OK on success; negative ie_io_status_t on failure.
Definition at line 1183 of file weights.c.
{
  if (!w || !w->weights_path[0]) return IE_IO_ERR_ARGS;
  WLOGI("ie_weights_touch: begin path='%s' size_bytes=%zu", w->weights_path, w->bin_size_bytes);
  int fd = open(w->weights_path, O_RDONLY);
  if (fd < 0) {
    wlog_errno_("open", w->weights_path);
    return IE_IO_ERR_OPEN;
  }
  unsigned char buf[4096];
  ssize_t r1 = ie_pread(fd, buf, sizeof(buf), 0);
  ssize_t r2 = 0;
  if (w->bin_size_bytes > sizeof(buf)) {
    off_t off = (off_t)(w->bin_size_bytes - sizeof(buf));
    r2 = ie_pread(fd, buf, sizeof(buf), off);
  }
  close(fd);
  if (r1 < 0 || r2 < 0) {
    WLOGE("ie_weights_touch: read failed (r1=%zd r2=%zd) path='%s'", r1, r2, w->weights_path);
    return IE_IO_ERR_READ;
  }
  WLOGD("ie_weights_touch: ok primary binary reads (r1=%zd r2=%zd)", r1, r2);
#if (IE_WEIGHTS_HAS_DEDUP_FIELDS == 1)
  {
    const int dedup_enabled = env_flag_get("IE_DEDUP", 0);
    const int dedup_strict = env_flag_get("IE_DEDUP_STRICT", 0);
    WLOGD("ie_weights_touch: dedup flags IE_DEDUP=%d IE_DEDUP_STRICT=%d", dedup_enabled,
          dedup_strict);
    if (dedup_enabled) {
      const char *base = (w->json_path[0] ? w->json_path : w->weights_path);
      const char *slash = last_slash(base);
      char dir[512];
      dir[0] = '\0';
      if (slash) {
        size_t dn = (size_t)(slash - base);
        if (dn >= sizeof(dir)) dn = sizeof(dir) - 1;
        memcpy(dir, base, dn);
        dir[dn] = '\0';
      } else {
        cpyz(dir, sizeof(dir), ".");
      }
      /*
       * Touch dedup artifacts.
       *
       * Instead of hardcoding filenames, prefer reading relpaths from
       * model.dedup.json (it contains a files[] table).
       */
      char dedup_manifest[512];
      dedup_manifest[0] = '\0';
      join_path(dedup_manifest, sizeof(dedup_manifest), dir, "model.dedup.json");
      if (!file_exists_readable(dedup_manifest)) {
        WLOGI("ie_weights_touch: dedup enabled but model.dedup.json missing; attempting link");
        (void)ensure_dedup_manifest_link(dir);
      }
      int ok_manifest = touch_file_small(dedup_manifest);
      int ok_all = ok_manifest;
      char *mjson = NULL;
      size_t mlen = 0;
      if (ok_manifest && read_all_text(dedup_manifest, &mjson, &mlen) == 0 && mjson && mlen > 0) {
        /* Scan for \"relpath\" entries and touch each referenced file. */
        size_t touched = 0;
        const char *p = mjson;
        while ((p = strstr(p, "\"relpath\"")) != NULL) {
          p += strlen("\"relpath\"");
          while (*p && (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n')) ++p;
          if (*p != ':') continue;
          ++p;
          while (*p && (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n')) ++p;
          if (*p != '"') continue;
          ++p;
          char rel[512];
          size_t rn = 0;
          int esc = 0;
          for (; *p && rn + 1 < sizeof(rel); ++p) {
            char ch = *p;
            if (esc) {
              /* Minimal unescape (we only expect simple paths). */
              if (ch == '"' || ch == '\\' || ch == '/') {
                rel[rn++] = ch;
              } else if (ch == 'n') {
                rel[rn++] = '\n';
              } else if (ch == 'r') {
                rel[rn++] = '\r';
              } else if (ch == 't') {
                rel[rn++] = '\t';
              } else {
                rel[rn++] = ch;
              }
              esc = 0;
              continue;
            }
            if (ch == '\\') {
              esc = 1;
              continue;
            }
            if (ch == '"') {
              break;
            }
            rel[rn++] = ch;
          }
          rel[rn] = '\0';
          if (rel[0] != '\0') {
            char abs[512];
            abs[0] = '\0';
            join_path(abs, sizeof(abs), dir, rel);
            int ok = touch_file_small(abs);
            ok_all = ok_all && ok;
            ++touched;
          }
          if (*p == '"') ++p;
          if (touched > 128) break; /* sanity bound */
        }
        WLOGI("ie_weights_touch: dedup touch results manifest=%d ok_all=%d", ok_manifest, ok_all);
        if (touched == 0) {
          /* Fallback to canonical filenames used by the reference pipeline. */
          char p_def[512], p_exc[512], p_msk[512];
          p_def[0] = p_exc[0] = p_msk[0] = '\0';
          join_path(p_def, sizeof(p_def), dir, "model.defaults.bin");
          join_path(p_exc, sizeof(p_exc), dir, "model.exceptions.bin");
          join_path(p_msk, sizeof(p_msk), dir, "model.masks.bin");
          int ok_def = touch_file_small(p_def);
          int ok_exc = touch_file_small(p_exc);
          int ok_msk = touch_file_small(p_msk);
          ok_all = ok_all && ok_def && ok_exc && ok_msk;
          WLOGI("ie_weights_touch: dedup fallback touch defaults=%d exceptions=%d masks=%d", ok_def, ok_exc,
                ok_msk);
        }
      } else {
        WLOGW("ie_weights_touch: could not read dedup manifest '%s'", dedup_manifest);
        ok_all = 0;
      }
      free(mjson);
      if (dedup_strict && !ok_all) {
        WLOGE("ie_weights_touch: dedup strict mode: missing or unreadable artifact(s)");
        return IE_IO_ERR_JSON;
      }
    }
  }
#endif
  WLOGI("ie_weights_touch: success");
  return IE_IO_OK;
}
References ie_weights_s::bin_size_bytes, cpyz(), ensure_dedup_manifest_link(), env_flag_get(), file_exists_readable(), IE_IO_ERR_ARGS, IE_IO_ERR_JSON, IE_IO_ERR_OPEN, IE_IO_ERR_READ, IE_IO_OK, ie_pread(), join_path(), ie_weights_s::json_path, last_slash(), read_all_text(), touch_file_small(), ie_weights_s::weights_path, wlog_errno_(), WLOGD, WLOGE, WLOGI, and WLOGW.
Referenced by open_and_touch().
join_path()
static void join_path (char * out, size_t outsz, const char * dir, const char * file) static
Join directory and filename into an output buffer (NUL-terminated).
This function performs a bounded concatenation:
If dir ends with '/', it is not duplicated.
If dir is empty, file is copied verbatim.
Parameters
out Output buffer.
outsz Output capacity.
dir Directory path (may be NULL/empty).
file Filename (must be non-empty).
Definition at line 247 of file weights.c.
{
  if (!out || outsz == 0) return;
  out[0] = '\0';
  if (!file || !*file) return;
  if (!dir || !*dir) {
    cpyz(out, outsz, file);
    return;
  }
  const size_t ld = strlen(dir);
  const size_t lf = strlen(file);
  const int need_slash = (ld > 0 && dir[ld - 1] != '/');
  size_t pos = 0;
  size_t copyd = ld;
  if (copyd >= outsz) copyd = outsz - 1;
  if (copyd > 0) {
    memcpy(out + pos, dir, copyd);
    pos += copyd;
  }
  if (pos < outsz - 1 && need_slash) out[pos++] = '/';
  if (pos < outsz - 1) {
    size_t room = (outsz - 1) - pos;
    size_t copyf = (lf > room) ? room : lf;
    if (copyf > 0) {
      memcpy(out + pos, file, copyf);
      pos += copyf;
    }
  }
  out[pos] = '\0';
}
References cpyz().
Referenced by ensure_dedup_manifest_link(), find_dedup_manifest_source_(), ie_weights_open(), and ie_weights_touch().
json_unescape_into()
static size_t json_unescape_into (char * dst, size_t dstsz, const char * src, size_t srclen) static
Unescape a JSON string into a destination buffer (best-effort).
Supported escapes:
" \ \/
\r \t
Unknown escapes are handled by dropping the backslash and copying the escaped character verbatim.
Parameters
dst Destination buffer.
dstsz Destination capacity.
src Source buffer (not NUL-terminated; length provided).
srclen Source length in bytes.
Returns
Number of bytes written (excluding NUL terminator).
Definition at line 415 of file weights.c.
{
  if (!dst || dstsz == 0) return 0;
  size_t di = 0;
  for (size_t si = 0; si < srclen && di + 1 < dstsz; ++si) {
    char ch = src[si];
    if (ch == '\\' && si + 1 < srclen) {
      char n = src[si + 1];
      if (n == '"' || n == '\\' || n == '/') {
        dst[di++] = n;
        ++si;
        continue;
      }
      if (n == 'n') {
        dst[di++] = '\n';
        ++si;
        continue;
      }
      if (n == 'r') {
        dst[di++] = '\r';
        ++si;
        continue;
      }
      if (n == 't') {
        dst[di++] = '\t';
        ++si;
        continue;
      }
      /* Unknown escape: drop backslash, keep char. */
      dst[di++] = n;
      ++si;
      continue;
    }
    dst[di++] = ch;
  }
  dst[di] = '\0';
  return di;
}
Referenced by scan_json_key_string(), and scan_json_key_string_in_range().
last_slash()
static const char * last_slash (const char * p) static
Return a pointer to the last '/' in a path, or NULL if none.
Parameters
p NUL-terminated path.
Returns
Pointer to last '/', or NULL.
Definition at line 225 of file weights.c.
{
  const char *s = NULL;
  if (!p) return NULL;
  for (const char *q = p; *q; ++q) {
    if (*q == '/') s = q;
  }
  return s;
}
Referenced by ie_weights_open(), and ie_weights_touch().
read_all_text()
static int read_all_text (const char * path, char ** buf, size_t * len_out) static
Read an entire file into a newly allocated NUL-terminated buffer.
Reads in binary mode.
Strips a UTF-8 BOM if present.
Always NUL-terminates the returned buffer.
Parameters
path File path.
buf Output pointer to malloc'd buffer (caller frees).
len_out Optional output length (bytes, excluding NUL).
Returns
0 on success, negative on failure.
Definition at line 297 of file weights.c.
{
  if (!path || !buf) return -1;
  *buf = NULL;
  if (len_out) *len_out = 0;
  WLOGD("read_all_text: path='%s'", path);
  FILE *f = fopen(path, "rb");
  if (!f) {
    wlog_errno_("fopen", path);
    return -2;
  }
  if (fseek(f, 0, SEEK_END) != 0) {
    wlog_errno_("fseek", path);
    fclose(f);
    return -3;
  }
  long n = ftell(f);
  if (n < 0) {
    wlog_errno_("ftell", path);
    fclose(f);
    return -3;
  }
  if (fseek(f, 0, SEEK_SET) != 0) {
    wlog_errno_("fseek", path);
    fclose(f);
    return -3;
  }
  size_t size = (size_t)n;
  char *mem = (char *)malloc(size + 1);
  if (!mem) {
    WLOGE("read_all_text: malloc failed (bytes=%zu) path='%s'", size + 1, path);
    fclose(f);
    return -4;
  }
  size_t rd = fread(mem, 1, size, f);
  fclose(f);
  if (rd != size) {
    WLOGE("read_all_text: short read (got=%zu want=%zu) path='%s'", rd, size, path);
    free(mem);
    return -5;
  }
  if (size >= 3 && (unsigned char)mem[0] == 0xEF && (unsigned char)mem[1] == 0xBB &&
      (unsigned char)mem[2] == 0xBF) {
    WLOGD("read_all_text: stripping UTF-8 BOM path='%s'", path);
    size -= 3;
    memmove(mem, mem + 3, size);
  }
  mem[size] = '\0';
  *buf = mem;
  if (len_out) *len_out = size;
  WLOGD("read_all_text: ok (bytes=%zu) path='%s'", size, path);
  return 0;
}
References wlog_errno_(), WLOGD, and WLOGE.
Referenced by ensure_dedup_manifest_link(), ie_weights_open(), and ie_weights_touch().
scan_json_best_effort_bin()
static int scan_json_best_effort_bin (const char * json, char * dst, size_t dstsz) static
Try multiple schema variants to locate the weights binary path.
The loader tolerates different JSON shapes by checking:
"bin"
"weights_bin"
"weightsBin"
"weights_path"
"weightsPath"
"weights": { "bin": ... }
"iebin": { "bin": ... }
Parameters
json NUL-terminated JSON-ish text.
dst Output buffer for the path value.
dstsz Output capacity.
Returns
1 if found, 0 if not found, negative on invalid args.
Definition at line 643 of file weights.c.
{
  if (!json || !dst || dstsz == 0) return -1;
  dst[0] = '\0';
  /* Common direct keys. */
  if (scan_json_key_string(json, "bin", dst, dstsz) == 1 && dst[0]) {
    WLOGD("scan_json_best_effort_bin: found key='bin' value='%s'", dst);
    return 1;
  }
  if (scan_json_key_string(json, "weights_bin", dst, dstsz) == 1 && dst[0]) {
    WLOGD("scan_json_best_effort_bin: found key='weights_bin' value='%s'", dst);
    return 1;
  }
  if (scan_json_key_string(json, "weightsBin", dst, dstsz) == 1 && dst[0]) {
    WLOGD("scan_json_best_effort_bin: found key='weightsBin' value='%s'", dst);
    return 1;
  }
  if (scan_json_key_string(json, "weights_path", dst, dstsz) == 1 && dst[0]) {
    WLOGD("scan_json_best_effort_bin: found key='weights_path' value='%s'", dst);
    return 1;
  }
  if (scan_json_key_string(json, "weightsPath", dst, dstsz) == 1 && dst[0]) {
    WLOGD("scan_json_best_effort_bin: found key='weightsPath' value='%s'", dst);
    return 1;
  }
  /* Nested objects. */
  {
    const char *b = NULL;
    const char *e = NULL;
    if (scan_json_object_range(json, "weights", &b, &e) == 1 && b && e && b <= e) {
      if (scan_json_key_string_in_range(b, e, "bin", dst, dstsz) == 1 && dst[0]) {
        WLOGD("scan_json_best_effort_bin: found key='weights.bin' value='%s'", dst);
        return 1;
      }
      if (scan_json_key_string_in_range(b, e, "weights_bin", dst, dstsz) == 1 && dst[0]) {
        WLOGD("scan_json_best_effort_bin: found key='weights.weights_bin' value='%s'", dst);
        return 1;
      }
    }
  }
  {
    const char *b = NULL;
    const char *e = NULL;
    if (scan_json_object_range(json, "iebin", &b, &e) == 1 && b && e && b <= e) {
      if (scan_json_key_string_in_range(b, e, "bin", dst, dstsz) == 1 && dst[0]) {
        WLOGD("scan_json_best_effort_bin: found key='iebin.bin' value='%s'", dst);
        return 1;
      }
      if (scan_json_key_string_in_range(b, e, "weights_bin", dst, dstsz) == 1 && dst[0]) {
        WLOGD("scan_json_best_effort_bin: found key='iebin.weights_bin' value='%s'", dst);
        return 1;
      }
    }
  }
  WLOGW("scan_json_best_effort_bin: no recognized bin key found");
  return 0;
}
References scan_json_key_string(), scan_json_key_string_in_range(), scan_json_object_range(), WLOGD, and WLOGW.
Referenced by ie_weights_open().
scan_json_key_int()
static int scan_json_key_int (const char * json, const char * key, int * out_val) static
Scan a relaxed JSON blob for an integer value at a given key.
This is a best-effort scan that:
searches for "key" occurrences,
expects a ':' after the key,
parses a base-10 integer with strtol().
It does not validate full JSON structure.
Parameters
json NUL-terminated text.
key Key name without quotes (e.g., "version").
out_val Output integer.
Returns
1 if found, 0 if not found, negative on invalid args.
Definition at line 374 of file weights.c.
{
  if (!json || !key || !out_val) return -1;
  const char *p = json;
  const size_t klen = strlen(key);
  while ((p = strstr(p, "\""))) {
    ++p;
    if (strncmp(p, key, klen) == 0 && p[klen] == '"') {
      const char *c = p + klen + 1;
      c = skip_ws(c);
      if (!c || *c != ':') continue;
      ++c;
      c = skip_ws(c);
      if (!c) continue;
      char *end = NULL;
      long v = strtol(c, &end, 10);
      if (end && end != c) {
        *out_val = (int)v;
        return 1;
      }
    }
  }
  return 0;
}
References skip_ws().
Referenced by ie_weights_open().
scan_json_key_string()
static int scan_json_key_string (const char * json, const char * key, char * dst, size_t dstsz) static
Scan a relaxed JSON blob for a string value at a given key.
Finds "key": "value" and copies a minimally unescaped value into dst. This scan does not validate full JSON structure; it is tolerant to extra whitespace and unrelated fields.
Parameters
json NUL-terminated JSON-ish text.
key Key name without quotes.
dst Output buffer.
dstsz Output capacity.
Returns
1 if found, 0 if not found, negative on invalid args.
Definition at line 467 of file weights.c.
{
  if (!json || !key || !dst || dstsz == 0) return -1;
  dst[0] = '\0';
  const char *p = json;
  const size_t klen = strlen(key);
  while ((p = strstr(p, "\""))) {
    ++p;
    if (strncmp(p, key, klen) == 0 && p[klen] == '"') {
      const char *c = p + klen + 1;
      c = skip_ws(c);
      if (!c || *c != ':') continue;
      ++c;
      c = skip_ws(c);
      if (!c || *c != '"') continue;
      ++c;
      const char *start = c;
      while (*c) {
        if (*c == '"' && (c == start || c[-1] != '\\')) break;
        ++c;
      }
      if (*c != '"') return 0;
      size_t raw_len = (size_t)(c - start);
      (void)json_unescape_into(dst, dstsz, start, raw_len);
      return 1;
    }
  }
  return 0;
}
References json_unescape_into(), and skip_ws().
Referenced by ie_weights_open(), and scan_json_best_effort_bin().
scan_json_key_string_in_range()
static int scan_json_key_string_in_range (const char * begin, const char * end, const char * key, char * dst, size_t dstsz) static
Scan for a string key within a bounded [begin,end] range.
This is used for nested objects discovered by scan_json_object_range().
Parameters
begin Range begin.
end Range end (inclusive, points to closing brace or last valid byte).
key Key name.
dst Output buffer.
dstsz Output capacity.
Returns
1 if found, 0 if not found, negative on invalid args.
Definition at line 580 of file weights.c.
{
  if (!begin || !end || !key || !dst || dstsz == 0) return -1;
  dst[0] = '\0';
  if (end < begin) return -1;
  const size_t klen = strlen(key);
  const char *p = begin;
  const char *limit = end + 1;
  while (p < limit) {
    const char *q = memchr(p, '"', (size_t)(limit - p));
    if (!q) break;
    ++q;
    if ((size_t)(limit - q) >= klen && memcmp(q, key, klen) == 0 && q[klen] == '"') {
      const char *c = q + klen + 1;
      c = skip_ws(c);
      if (!c || c >= limit || *c != ':') {
        p = q + 1;
        continue;
      }
      ++c;
      c = skip_ws(c);
      if (!c || c >= limit || *c != '"') {
        p = q + 1;
        continue;
      }
      ++c;
      const char *start = c;
      while (c < limit) {
        if (*c == '"' && (c == start || c[-1] != '\\')) break;
        ++c;
      }
      if (c >= limit || *c != '"') return 0;
      size_t raw_len = (size_t)(c - start);
      (void)json_unescape_into(dst, dstsz, start, raw_len);
      return 1;
    }
    p = q + 1;
  }
  return 0;
}
References json_unescape_into(), and skip_ws().
Referenced by scan_json_best_effort_bin().
scan_json_object_range()
static int scan_json_object_range (const char * json, const char * key, const char ** out_begin, const char ** out_end) static
Locate the interior byte range of an object value "{ ... }" for a key.
This helper attempts to locate "key": { ... } and returns a range that covers the interior of the braces. Strings are respected when tracking brace depth to avoid premature termination.
Parameters
json JSON-ish text.
key Object key to find.
out_begin Output begin pointer (inside the braces).
out_end Output end pointer (points to closing brace).
Returns
1 if found, 0 if not found/malformed, negative on invalid args.
Definition at line 512 of file weights.c.
{
  if (!json || !key || !out_begin || !out_end) return -1;
  *out_begin = *out_end = NULL;
  const size_t klen = strlen(key);
  const char *p = json;
  while ((p = strstr(p, "\""))) {
    ++p;
    if (strncmp(p, key, klen) == 0 && p[klen] == '"') {
      const char *c = p + klen + 1;
      c = skip_ws(c);
      if (!c || *c != ':') continue;
      ++c;
      c = skip_ws(c);
      if (!c || *c != '{') return 0;
      int depth = 0;
      const char *start = c + 1;
      const char *q = c;
      int in_str = 0;
      while (*q) {
        char ch = *q;
        if (in_str) {
          if (ch == '\\' && q[1]) {
            q += 2;
            continue;
          }
          if (ch == '"') in_str = 0;
          ++q;
          continue;
        }
        if (ch == '"') {
          in_str = 1;
          ++q;
          continue;
        }
        if (ch == '{') ++depth;
        if (ch == '}') {
          --depth;
          if (depth == 0) {
            *out_begin = start;
            *out_end = q;
            return 1;
          }
        }
        ++q;
      }
      return 0;
    }
  }
  return 0;
}
References skip_ws().
Referenced by scan_json_best_effort_bin().
skip_ws()
static const char * skip_ws (const char * p) static
Skip ASCII whitespace characters in a string.
Parameters
p Input pointer (may be NULL).
Returns
Pointer advanced past whitespace, or NULL if p is NULL.
Definition at line 194 of file weights.c.
{
  if (!p) return NULL;
  while (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n') ++p;
  return p;
}
Referenced by scan_json_key_int(), scan_json_key_string(), scan_json_key_string_in_range(), and scan_json_object_range().
touch_file_small()
static int touch_file_small (const char * path) static
Touch a file by doing small reads near start/end.
This is intended as a fast readability check and optional OS cache warming. It is deliberately minimal and does not attempt to validate file contents.
Parameters
path Path to file.
Returns
1 if read succeeded, 0 otherwise.
Definition at line 933 of file weights.c.
{
  if (!path || !*path) return 0;
  int fd = open(path, O_RDONLY);
  if (fd < 0) {
    wlog_errno_("open", path);
    return 0;
  }
  struct stat st;
  if (fstat(fd, &st) != 0 || st.st_size < 0) {
    wlog_errno_("fstat", path);
    close(fd);
    return 0;
  }
  unsigned char buf[4096];
  ssize_t r1 = ie_pread(fd, buf, sizeof(buf), 0);
  ssize_t r2 = 0;
  if ((size_t)st.st_size > sizeof(buf)) {
    off_t off = (off_t)((size_t)st.st_size - sizeof(buf));
    r2 = ie_pread(fd, buf, sizeof(buf), off);
  }
  close(fd);
  if (r1 < 0 || r2 < 0) {
    WLOGW("touch_file_small: read failed path='%s' size=%zu", path, (size_t)st.st_size);
    return 0;
  }
  WLOGD("touch_file_small: ok path='%s' size=%zu", path, (size_t)st.st_size);
  return 1;
}
References ie_pread(), wlog_errno_(), WLOGD, and WLOGW.
Referenced by ie_weights_touch().
wlog_errno_()
static void wlog_errno_ (const char * what, const char * path) static
Log an errno-based failure with contextual path information.
Parameters
what Short operation label (e.g., "fopen", "stat").
path Associated file path (may be NULL).
Definition at line 175 of file weights.c.
{
  if (!ie_weights_log_enabled(1)) return;
  if (path && *path) {
    WLOGE("%s failed: path='%s' errno=%d (%s)", what, path, errno, strerror(errno));
  } else {
    WLOGE("%s failed: errno=%d (%s)", what, errno, strerror(errno));
  }
}
References ie_weights_log_enabled(), and WLOGE.
Referenced by ensure_dedup_manifest_link(), ie_weights_open(), ie_weights_touch(), read_all_text(), touch_file_small(), and write_all_bytes_().
write_all_bytes_()
static int write_all_bytes_ (const char * path, const void * data, size_t len) static
Create a best-effort model.dedup.json manifest for runtime dedup.
The runtime dedup loader expects a file named "model.dedup.json" in the model directory. Some pipelines emit the same JSON under different names.
This helper attempts to:
locate an existing manifest under a set of common alternative filenames (or a user-provided IE_DEDUP_MANIFEST override), then
create "model.dedup.json" as a symlink pointing at that file, and
fall back to copying the file if symlinks are unavailable.
Failures are not fatal unless the caller is operating under strict mode.
Parameters
dir Directory containing the artifacts.
Returns
1 if model.dedup.json ends up readable, else 0.
Definition at line 798 of file weights.c.
{
  if (!path || !*path || (!data && len != 0)) return 0;
  FILE *f = fopen(path, "wb");
  if (!f) {
    wlog_errno_("fopen", path);
    return 0;
  }
  size_t w = fwrite(data, 1, len, f);
  if (fclose(f) != 0) {
    wlog_errno_("fclose", path);
  }
  return (w == len) ? 1 : 0;
}
References wlog_errno_().
Referenced by ensure_dedup_manifest_link().