Inference Engine (Clocher): engine/src/opt/cpu_features.c File Reference
cpu_features.c File Reference
Runtime CPU feature detection via CPUID/XGETBV (x86) with safe fallbacks.
#include "ie_cpu.h"
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdatomic.h>
#include <strings.h>
Functions
static int ie_env_flag (const char *name)
Return 1 if the environment variable name is set to a truthy value.
static void ie_cpuid_ex (unsigned leaf, unsigned subleaf, unsigned *eax, unsigned *ebx, unsigned *ecx, unsigned *edx)
Query CPUID with leaf and subleaf.
static unsigned ie_xgetbv_xcr0 (void)
Read XCR0 via XGETBV to validate OS support for XMM/YMM state.
bool ie_cpu_features_detect (ie_cpu_features_t *out)
Alias for ie_cpu_detect for clearer call sites.
size_t ie_cpu_features_to_string (const ie_cpu_features_t *f, char *buf, size_t cap)
Serialize CPU features into a stable one-line string.
Detailed Description
Runtime CPU feature detection via CPUID/XGETBV (x86) with safe fallbacks.
This module performs best-effort feature detection with no external deps:
AVX2 and FMA (CPUID leaf 1 + leaf 7 and XGETBV validation).
Optional AVX-512 BF16 capability (CPUID leaf 7 subleaf 1) if present in the ABI.
It is intended to drive runtime kernel selection and logging.
Environment:
Set IE_DEBUG_KERNELS=1 to print a one-line CPU feature summary.
Definition in file cpu_features.c.
Function Documentation
ie_cpu_features_detect()
bool ie_cpu_features_detect (ie_cpu_features_t * out)
Alias for ie_cpu_detect for clearer call sites.
Some call sites prefer "features_detect" naming (e.g., instrumentation).
Parameters
[out] out Receives the detected capabilities.
Returns
See ie_cpu_detect.
Definition at line 111 of file cpu_features.c.
{
  if (!out) return false;
  out->avx2 = false;
  out->fma  = false;
  /* If your ie_cpu_features_t includes this field, we fill it. */
#if defined(__GNUC__) || defined(_MSC_VER)
  /* Some builds may not include avx512_bf16 in the struct; keep this guarded
   * at the source level by only referencing the member name used in your ABI.
   */
  out->avx512_bf16 = false;
#endif
#if defined(__x86_64__) || defined(__i386__) || defined(_M_X64) || defined(_M_IX86)
  unsigned a=0,b=0,c=0,d=0;
  /* Leaf 0: max leaf availability */
  ie_cpuid_ex(0, 0, &a, &b, &c, &d);
  if (a == 0) {
    return true; /* CPUID unsupported or unavailable */
  }
  /* Leaf 1: baseline features (AVX, OSXSAVE, FMA) */
  ie_cpuid_ex(1, 0, &a, &b, &c, &d);
  const int osxsave = (int)((c >> 27) & 1u);
  const int avx     = (int)((c >> 28) & 1u);
  const int fma     = (int)((c >> 12) & 1u);
  /* Validate OS has enabled XMM/YMM via XGETBV */
  unsigned xcr0 = osxsave ? ie_xgetbv_xcr0() : 0u;
  const int ymm_ok = ((xcr0 & 0x6u) == 0x6u);
  /* Leaf 7 subleaf 0: extended features (AVX2) */
  ie_cpuid_ex(7, 0, &a, &b, &c, &d);
  const int avx2 = (int)((b >> 5) & 1u);
  out->avx2 = (avx && ymm_ok && avx2);
  out->fma  = (fma != 0);
  /* Leaf 7 subleaf 1: AVX512_BF16 is in EAX bit 5 on supporting CPUs.
   * We still store it even if the OS might not enable ZMM state; this flag is
   * primarily used as a capability indicator for "do we even try BF16 kernels".
   */
  ie_cpuid_ex(7, 1, &a, &b, &c, &d);
  {
    const int avx512bf16 = (int)((a >> 5) & 1u);
    out->avx512_bf16 = (avx512bf16 != 0);
  }
#endif
  if (ie_env_flag("IE_DEBUG_KERNELS")) {
    char buf[256];
    (void)ie_cpu_features_to_string(out, buf, sizeof buf);
    fprintf(stderr, "[cpu] %s\n", buf);
  }
  return true;
}
References ie_cpu_features_to_string(), ie_cpuid_ex(), ie_env_flag(), and ie_xgetbv_xcr0().
Referenced by ie_gemv_q4_0_f32(), ie_kernels_install(), and ie_q4_kernel_selected_name().
ie_cpu_features_to_string()
size_t ie_cpu_features_to_string (const ie_cpu_features_t * f, char * buf, size_t cap)
Serialize CPU features into a stable one-line string.
Format a feature set as a compact, stable string.
Parameters
f Feature struct.
buf Output buffer.
cap Output capacity in bytes.
Returns
Number of bytes written (excluding NUL), clamped to cap-1.
Definition at line 179 of file cpu_features.c.
{
  if (!buf || cap == 0) return 0;
  if (!f) {
    buf[0] = 0;
    return 0;
  }
  const int n = snprintf(buf, cap,
                         "avx2=%d fma=%d avx512_bf16=%d",
                         f->avx2 ? 1 : 0,
                         f->fma ? 1 : 0,
                         f->avx512_bf16 ? 1 : 0);
  if (n < 0) {
    buf[0] = 0;
    return 0;
  }
  /* Clamp without signedness warnings under -Werror. */
  return ((size_t)n >= cap) ? (cap - 1) : (size_t)n;
}
References ie_cpu_features::avx2, ie_cpu_features::avx512_bf16, and ie_cpu_features::fma.
Referenced by ie_cpu_features_detect().
ie_cpuid_ex()
static void ie_cpuid_ex (unsigned leaf, unsigned subleaf, unsigned * eax, unsigned * ebx, unsigned * ecx, unsigned * edx) static
Query CPUID with leaf and subleaf.
On non-x86 builds, outputs are zeroed.
Parameters
leaf CPUID leaf.
subleaf CPUID subleaf (ECX input).
eax Output EAX.
ebx Output EBX.
ecx Output ECX.
edx Output EDX.
Definition at line 66 of file cpu_features.c.
{
#if defined(__x86_64__) || defined(__i386__) || defined(_M_X64) || defined(_M_IX86)
  #if defined(_MSC_VER)
    int regs[4];
    __cpuidex(regs, (int)leaf, (int)subleaf);
    *eax = (unsigned)regs[0];
    *ebx = (unsigned)regs[1];
    *ecx = (unsigned)regs[2];
    *edx = (unsigned)regs[3];
  #else
    unsigned a, b, c, d;
    __cpuid_count(leaf, subleaf, a, b, c, d);
    *eax = a; *ebx = b; *ecx = c; *edx = d;
  #endif
#else
  (void)leaf; (void)subleaf;
  *eax = *ebx = *ecx = *edx = 0u;
#endif
}
Referenced by ie_cpu_features_detect().
ie_env_flag()
static int ie_env_flag (const char * name) static
Return 1 if the environment variable name is set to a truthy value.
Truthy values (case-insensitive): "1", "true", "yes", "on".
Parameters
name Environment variable name.
Returns
1 if truthy, 0 otherwise.
Definition at line 47 of file cpu_features.c.
{
  const char *s = getenv(name);
  if (!s || !*s) return 0;
  return (!strcasecmp(s, "1") || !strcasecmp(s, "true") ||
          !strcasecmp(s, "yes") || !strcasecmp(s, "on"));
}
Referenced by ie_cpu_features_detect().
ie_xgetbv_xcr0()
static unsigned ie_xgetbv_xcr0 (void) static
Read XCR0 via XGETBV to validate OS support for XMM/YMM state.
On non-x86 builds, returns 0.
Returns
Lower 32 bits of XCR0.
Definition at line 95 of file cpu_features.c.
{
#if (defined(__x86_64__) || defined(__i386__)) && defined(__GNUC__)
  unsigned a, d;
  __asm__ volatile (".byte 0x0f, 0x01, 0xd0" : "=a"(a), "=d"(d) : "c"(0));
  return a;
#elif defined(_MSC_VER) && (defined(_M_IX86) || defined(_M_X64))
  return (unsigned)_xgetbv(0);
#else
  return 0u;
#endif
}
Referenced by ie_cpu_features_detect().