Inference Engine (Clocher): engine/include/gptoss_weights_index.h File Reference
gptoss_weights_index.h File Reference
GPT-OSS weight indexing and name-resolution over tensor_map.json and (optional) dedup views.
#include <stddef.h>
#include <stdint.h>
#include "ie_infer.h"
#include "ie_io.h"
#include "tensor_map.h"
#include "weights_dedup.h"
Data Structures
struct gptoss_tensor_t
A resolved tensor handle.
struct gptoss_layer_weights_t
Per-layer weight handles for a GPT-OSS transformer block.
struct gptoss_model_weights_t
Resolved weight handles for the full model.
Macros
#define _POSIX_C_SOURCE 200809L
Typedefs
typedef enum gptoss_arch_kind_t gptoss_arch_kind_t
typedef struct gptoss_tensor_t gptoss_tensor_t
typedef struct gptoss_layer_weights_t gptoss_layer_weights_t
typedef struct gptoss_model_weights_t gptoss_model_weights_t
typedef struct gptoss_weights_index_t gptoss_weights_index_t
Enumerations
enum gptoss_arch_kind_t { GPTOSS_ARCH_UNKNOWN = 0 , GPTOSS_ARCH_LLAMA = 1 , GPTOSS_ARCH_GPTNEOX = 2 }
Logical weight naming scheme detected in tensor_map.json.
Functions
int gptoss_weights_index_open (gptoss_weights_index_t *out, const char *model_dir, const ie_weights_t *weights)
Open a weights index for a given model directory and weights descriptor.
void gptoss_weights_index_close (gptoss_weights_index_t *idx)
Close an index and free all owned resources.
int gptoss_weights_index_build_model (const gptoss_weights_index_t *idx, const ie_gptoss_hparams_t *hp, gptoss_model_weights_t *out)
Resolve and validate all tensors required by the GPT-OSS forward pass.
void gptoss_model_weights_free (gptoss_model_weights_t *mw)
Free the per-layer array allocated by gptoss_weights_index_build_model.
int gptoss_tensor_is_valid (const gptoss_tensor_t *t)
Check whether a tensor handle is populated.
const uint8_t * gptoss_tensor_bytes (const gptoss_tensor_t *t)
Return a direct pointer to tensor bytes if available.
size_t gptoss_tensor_materialize (const gptoss_tensor_t *t, void *dst, size_t dst_nbytes)
Materialize tensor bytes into a caller-provided buffer.
Detailed Description
GPT-OSS weight indexing and name-resolution over tensor_map.json and (optional) dedup views.
Real inference requires fast access to model tensors (embedding, per-layer projection matrices, norms, and the LM head). In this repository, tensor payloads are described by tensor_map.json (logical name → offset/shape/dtype) and stored in model.ie.bin. When IE_DEDUP is enabled, tensors may be stored losslessly in auxiliary blobs and materialized through the dedup loader.
This module provides:
A loader for tensor_map.json.
A stable, explicit mapping of logical model components to resolved tensor names.
A small "tensor handle" abstraction that supports:
direct pointers into model.ie.bin (non-dedup),
dedup views (direct or reconstructable),
best-effort shape/dtype validation.
The forward pass implementation should:
call gptoss_weights_index_open once per model,
call gptoss_weights_index_build_model once to resolve all needed tensors,
then reuse the returned gptoss_model_weights_t throughout inference.
Definition in file gptoss_weights_index.h.
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 34 of file gptoss_weights_index.h.
Typedef Documentation
gptoss_arch_kind_t
typedef enum gptoss_arch_kind_t gptoss_arch_kind_t
gptoss_layer_weights_t
typedef struct gptoss_layer_weights_t gptoss_layer_weights_t
gptoss_model_weights_t
typedef struct gptoss_model_weights_t gptoss_model_weights_t
gptoss_tensor_t
typedef struct gptoss_tensor_t gptoss_tensor_t
gptoss_weights_index_t
typedef struct gptoss_weights_index_t gptoss_weights_index_t
Definition at line 176 of file gptoss_weights_index.h.
Enumeration Type Documentation
gptoss_arch_kind_t
enum gptoss_arch_kind_t
Logical weight naming scheme detected in tensor_map.json.
GPT-OSS snapshots can be exported with different naming conventions. This module probes for common layouts and records the detected convention so the forward pass can choose the correct projection wiring (fused QKV vs. separate, SwiGLU vs. GeLU MLP, etc.).
Enumerator
GPTOSS_ARCH_UNKNOWN
Unrecognized naming scheme.
GPTOSS_ARCH_LLAMA
LLaMA-style: model.layers.N.
GPTOSS_ARCH_GPTNEOX
GPT-NeoX-style: gpt_neox.layers.N.
Definition at line 63 of file gptoss_weights_index.h.
{
  GPTOSS_ARCH_UNKNOWN = 0,
  GPTOSS_ARCH_LLAMA   = 1,
  GPTOSS_ARCH_GPTNEOX = 2
} gptoss_arch_kind_t;
Function Documentation
gptoss_model_weights_free()
void gptoss_model_weights_free (gptoss_model_weights_t * mw)
Free the per-layer array allocated by gptoss_weights_index_build_model.
This does not close the underlying gptoss_weights_index_t.
Parameters
mw Model weights.
Definition at line 954 of file gptoss_weights_index.c.
{
  if (!mw) return;
  free(mw->layers);
  memset(mw, 0, sizeof(*mw));
}
References gptoss_model_weights_t::layers.
Referenced by gptoss_weights_index_build_model().
gptoss_tensor_bytes()
const uint8_t * gptoss_tensor_bytes (const gptoss_tensor_t * t)
Return a direct pointer to tensor bytes if available.
For IE_WVIEW_DEDUP tensors, this returns NULL; callers must use gptoss_tensor_materialize.
Parameters
t Tensor handle.
Returns
Pointer to bytes, or NULL if materialization is required.
Definition at line 394 of file gptoss_weights_index.c.
{
  if (!t) return NULL;
  return t->direct;
}
References gptoss_tensor_t::direct.
gptoss_tensor_is_valid()
int gptoss_tensor_is_valid (const gptoss_tensor_t * t)
Check whether a tensor handle is populated.
Parameters
t Tensor handle.
Returns
Non-zero if populated, 0 otherwise.
Definition at line 390 of file gptoss_weights_index.c.
{
  return (t && t->desc != NULL);
}
References gptoss_tensor_t::desc.
gptoss_tensor_materialize()
size_t gptoss_tensor_materialize (const gptoss_tensor_t * t, void * dst, size_t dst_nbytes)
Materialize tensor bytes into a caller-provided buffer.
For non-dedup tensors, this copies from the mapped model.ie.bin.
For IE_WVIEW_DIRECT, this copies from view.data.
For IE_WVIEW_DEDUP, this reconstructs bytes via ie_weights_dedup_materialize.
Parameters
t Tensor handle.
dst Destination buffer.
dst_nbytes Capacity of destination buffer.
Returns
Number of bytes written (0 on failure).
Definition at line 399 of file gptoss_weights_index.c.
{
  if (!t || !t->desc || !dst || dst_nbytes == 0) return 0;
  if (t->direct) {
    size_t n = t->nbytes;
    if (n > dst_nbytes) return 0;
    memcpy(dst, t->direct, n);
    return n;
  }
  if (t->is_dedup) {
    return ie_weights_dedup_materialize(&t->view, dst, dst_nbytes);
  }
  return 0;
}
References gptoss_tensor_t::desc, gptoss_tensor_t::direct, ie_weights_dedup_materialize(), gptoss_tensor_t::is_dedup, gptoss_tensor_t::nbytes, and gptoss_tensor_t::view.
gptoss_weights_index_build_model()
int gptoss_weights_index_build_model (const gptoss_weights_index_t * idx, const ie_gptoss_hparams_t * hp, gptoss_model_weights_t * out)
Resolve and validate all tensors required by the GPT-OSS forward pass.
This performs name-resolution for a known set of tensors (embedding, norms, per-layer projections, and LM head). It allocates out->layers and fills every gptoss_tensor_t with a descriptor and a pointer/view.
Missing optional tensors (e.g., pos_embed, lm_head when tied) are left empty (desc == NULL). Missing required tensors produce an error.
Parameters
idx Opened weights index.
hp Hyperparameters (used for layer count).
out Output model weights index (written on success).
Returns
IE_IO_OK on success, negative ie_io_status_t on failure.
Definition at line 860 of file gptoss_weights_index.c.
{
  if (!idx || !hp || !out) return IE_IO_ERR_ARGS;
  memset(out, 0, sizeof(*out));
  gptoss_arch_kind_t arch;
  int fused_qkv = 0;
  int swiglu = 0;
  {
    int rc = widx_detect_arch(idx, &arch, &fused_qkv, &swiglu);
    if (rc != IE_IO_OK) return rc;
  }
  out->arch = arch;
  out->attn_fused_qkv = fused_qkv;
  out->mlp_swiglu = swiglu;
  out->n_layers = hp->n_layers;
  {
    const char *embed_names[] = {
      "model.embed_tokens.weight",
      "tok_embeddings.weight",
      "model.tok_embeddings.weight",
      "transformer.wte.weight",
      "gpt_neox.embed_in.weight"
    };
    int rc = widx_resolve_required(idx, embed_names, sizeof(embed_names)/sizeof(embed_names[0]), &out->tok_embed_w);
    if (rc != IE_IO_OK) return rc;
  }
  {
    const char *pos_names[] = {
      "model.embed_positions.weight",
      "transformer.wpe.weight",
      "gpt_neox.embed_positions.weight"
    };
    int rc = widx_resolve_optional(idx, pos_names, sizeof(pos_names)/sizeof(pos_names[0]), &out->pos_embed_w);
    if (rc != IE_IO_OK) return rc;
  }
  {
    const char *norm_names[] = {
      "model.norm.weight",
      "transformer.norm.weight",
      "gpt_neox.final_layer_norm.weight",
      "final_layer_norm.weight"
    };
    int rc = widx_resolve_required(idx, norm_names, sizeof(norm_names)/sizeof(norm_names[0]), &out->final_norm_w);
    if (rc != IE_IO_OK) return rc;
  }
  {
    const char *lm_head_names[] = {
      "lm_head.weight",
      "model.lm_head.weight",
      "transformer.lm_head.weight",
      "embed_out.weight",
      "gpt_neox.embed_out.weight"
    };
    int rc = widx_resolve_optional(idx, lm_head_names, sizeof(lm_head_names)/sizeof(lm_head_names[0]), &out->lm_head_w);
    if (rc != IE_IO_OK) return rc;
    if (!out->lm_head_w.desc) {
      out->lm_head_w = out->tok_embed_w;
    }
  }
  if (hp->n_layers == 0) return IE_IO_ERR_ARGS;
  out->layers = (gptoss_layer_weights_t*)calloc((size_t)hp->n_layers, sizeof(gptoss_layer_weights_t));
  if (!out->layers) return IE_IO_ERR_OOM;
  for (uint32_t l = 0; l < hp->n_layers; ++l) {
    int rc;
    if (arch == GPTOSS_ARCH_LLAMA) {
      rc = widx_resolve_layer_llama(idx, l, fused_qkv, swiglu, &out->layers[l]);
    } else if (arch == GPTOSS_ARCH_GPTNEOX) {
      rc = widx_resolve_layer_neox(idx, l, &out->layers[l]);
    } else {
      rc = IE_IO_ERR_JSON;
    }
    if (rc != IE_IO_OK) {
      gptoss_model_weights_free(out);
      return rc;
    }
  }
  return IE_IO_OK;
}
References GPTOSS_ARCH_GPTNEOX, GPTOSS_ARCH_LLAMA, gptoss_model_weights_free(), IE_IO_ERR_ARGS, IE_IO_ERR_JSON, IE_IO_ERR_OOM, IE_IO_OK, ie_gptoss_hparams::n_layers, widx_detect_arch(), widx_resolve_layer_llama(), widx_resolve_layer_neox(), widx_resolve_optional(), and widx_resolve_required().
gptoss_weights_index_close()
void gptoss_weights_index_close (gptoss_weights_index_t * idx)
Close an index and free all owned resources.
Parameters
idx Index handle (may be NULL).
Definition at line 492 of file gptoss_weights_index.c.
{
  if (!idx) return;
  if (idx->dedup_owned) {
    ie_weights_dedup_t *h = idx->dedup_owned;
    ie_weights_dedup_close(&h);
    idx->dedup_owned = NULL;
    idx->dedup = NULL;
  }
  tensor_map_free(&idx->tmap);
  widx_mapped_close(&idx->bin);
  memset(idx, 0, sizeof(*idx));
  idx->bin.fd = -1;
}
References gptoss_weights_index_t::bin, gptoss_weights_index_t::dedup, gptoss_weights_index_t::dedup_owned, gptoss_mapped_file_t::fd, ie_weights_dedup_close(), tensor_map_free(), gptoss_weights_index_t::tmap, and widx_mapped_close().
gptoss_weights_index_open()
int gptoss_weights_index_open (gptoss_weights_index_t * out, const char * model_dir, const ie_weights_t * weights)
Open a weights index for a given model directory and weights descriptor.
This loads tensor_map.json and maps model.ie.bin.
If weights->is_dedup != 0 and weights->dedup_handle != NULL, this function will reuse that dedup loader (borrowed, not owned). If dedup is requested but no handle is present, it attempts to open a dedup loader from model_dir.
Parameters
out Output index (written on success).
model_dir Model directory (used to locate tensor_map.json and dedup files).
weights Weights descriptor opened by ie_weights_open.
Returns
IE_IO_OK on success, negative ie_io_status_t on failure.
Definition at line 417 of file gptoss_weights_index.c.
{
  if (!out || !model_dir || !weights) return IE_IO_ERR_ARGS;
  memset(out, 0, sizeof(*out));
  out->bin.fd = -1;
  out->weights = weights;
  {
    const char *tr = getenv("IE_TRACE_LOOKUPS");
    out->trace = (tr && tr[0] && strcmp(tr, "0") != 0);
  }
  if (strlen(model_dir) >= sizeof(out->model_dir)) return IE_IO_ERR_ARGS;
  memcpy(out->model_dir, model_dir, strlen(model_dir) + 1u);
  char tmap_path[1024];
  memset(tmap_path, 0, sizeof(tmap_path));
  if (widx_path_join(tmap_path, sizeof(tmap_path), model_dir, "tensor_map.json") != 0) {
    return IE_IO_ERR_ARGS;
  }
  if (tensor_map_load(tmap_path, &out->tmap) != 0) {
    if (widx_path_join(tmap_path, sizeof(tmap_path), model_dir, "hf/original/tensor_map.json") != 0) {
      return IE_IO_ERR_JSON;
    }
    if (tensor_map_load(tmap_path, &out->tmap) != 0) {
      return IE_IO_ERR_JSON;
    }
  }
  if (widx_trace_enabled(out)) {
    widx_tracef(out, "[widx] tensor_map loaded from '%s'\n", tmap_path);
  }
  if (!weights->weights_path[0]) {
    tensor_map_free(&out->tmap);
    return IE_IO_ERR_BIN_UNSPEC;
  }
  {
    int rc = widx_mapped_open(&out->bin, weights->weights_path);
    if (rc != IE_IO_OK) {
      tensor_map_free(&out->tmap);
      return rc;
    }
  }
  out->dedup = NULL;
  out->dedup_owned = NULL;
  if (weights->is_dedup) {
    if (weights->dedup_handle) {
      out->dedup = (const ie_weights_dedup_t*)weights->dedup_handle;
    } else {
      ie_weights_dedup_t *h = NULL;
      ie_weights_dedup_opts_t opts;
      memset(&opts, 0, sizeof(opts));
      opts.prefault_policy = 0;
      ie_wdedup_status_t st = ie_weights_dedup_open(&h, model_dir, &opts);
      if (st != IE_WDEDUP_OK) {
        out->dedup = NULL;
        out->dedup_owned = NULL;
      } else {
        out->dedup = h;
        out->dedup_owned = h;
      }
    }
  }
  return IE_IO_OK;
}
References ie_weights_s::dedup_handle, IE_IO_ERR_ARGS, IE_IO_ERR_BIN_UNSPEC, IE_IO_ERR_JSON, IE_IO_OK, IE_WDEDUP_OK, ie_weights_dedup_open(), ie_weights_s::is_dedup, ie_weights_dedup_opts_t::prefault_policy, tensor_map_free(), tensor_map_load(), ie_weights_s::weights_path, widx_mapped_open(), widx_path_join(), widx_trace_enabled(), and widx_tracef().