Inference Engine (Clocher): engine/include/gptoss_hparams.h File Reference
gptoss_hparams.h File Reference
Load GPT-OSS hyperparameters from a HuggingFace-style config.json.
#include <stdint.h>
#include "ie_infer.h"
#include "ie_io.h"
Data Structures
struct gptoss_hparams_ex_t
Extended hyperparameters typically required by a GPT-OSS forward pass.
Macros
#define _POSIX_C_SOURCE 200809L
Typedefs
typedef struct gptoss_hparams_ex_t gptoss_hparams_ex_t
Functions
int gptoss_hparams_load (const char *model_dir, ie_gptoss_hparams_t *out_hp)
Load core hyperparameters from a model directory.
int gptoss_hparams_load_ex (const char *model_dir, gptoss_hparams_ex_t *out_ex)
Load extended hyperparameters from a model directory.
int gptoss_hparams_load_ex_from_file (const char *config_json_path, gptoss_hparams_ex_t *out_ex)
Load extended hyperparameters from an explicit HuggingFace config path.
Detailed Description
Load GPT-OSS hyperparameters from a HuggingFace-style config.json.
Real inference needs a small set of model hyperparameters (layer/head counts, embedding dimensions, vocabulary size, and maximum sequence length).
The engine’s stable inference interface uses ie_gptoss_hparams_t (declared in ie_infer.h). This module provides a dependency-free loader that reads a HuggingFace config.json and fills those fields.
The parser is intentionally relaxed:
no third-party JSON library,
tolerant of extra fields and whitespace,
extracts only the keys required by the forward pass.
In addition to the core fields, this module can also extract commonly-needed extras (RMSNorm epsilon, RoPE configuration, and tie_word_embeddings) through gptoss_hparams_ex_t.
Definition in file gptoss_hparams.h.
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 31 of file gptoss_hparams.h.
Typedef Documentation
gptoss_hparams_ex_t
typedef struct gptoss_hparams_ex_t gptoss_hparams_ex_t
Function Documentation
gptoss_hparams_load()
int gptoss_hparams_load (const char * model_dir, ie_gptoss_hparams_t * out_hp)
Load core hyperparameters from a model directory.
This function searches for a HuggingFace config.json in: 1) <model_dir>/config.json 2) <model_dir>/hf/original/config.json
It fills ie_gptoss_hparams_t with:
n_layers (HF key: num_hidden_layers)
n_heads (HF key: num_attention_heads)
n_kv_heads (HF key: num_key_value_heads, defaults to n_heads)
d_model (HF key: hidden_size)
d_ff (HF key: intermediate_size)
vocab_size (HF key: vocab_size)
max_seq (HF key: max_position_embeddings)
It also derives:
d_head = d_model / n_heads (must divide evenly)
Parameters
model_dir Model directory containing HuggingFace artifacts.
out_hp Output hyperparameter struct (written on success).
Returns
IE_IO_OK on success, negative ie_io_status_t on failure.
Definition at line 789 of file gptoss_hparams.c.
{
  if (!model_dir || !out_hp) return IE_IO_ERR_ARGS;
  gptoss_hparams_ex_t ex;
  const int rc = gptoss_hparams_load_ex(model_dir, &ex);
  if (rc != IE_IO_OK) return rc;
  *out_hp = ex.core;
  return IE_IO_OK;
}
References gptoss_hparams_ex_t::core, gptoss_hparams_load_ex(), IE_IO_ERR_ARGS, and IE_IO_OK.
Referenced by ie_engine_create(), and ie_generate_gptoss().
gptoss_hparams_load_ex()
int gptoss_hparams_load_ex (const char * model_dir, gptoss_hparams_ex_t * out_ex)
Load extended hyperparameters from a model directory.
Same search behavior as gptoss_hparams_load, but also extracts:
RMSNorm epsilon (keys: rms_norm_eps, rms_epsilon, layer_norm_eps)
RoPE theta (rope_theta)
RoPE scaling object (rope_scaling.type, rope_scaling.factor)
tie_word_embeddings (tie_word_embeddings)
Missing optional fields are filled with conservative defaults:
rms_norm_eps = 1e-5f
rope_theta = 10000.0f
rope_scaling_type = "", rope_scaling_factor = 1.0f
rope_scaling_original_max_position_embeddings = 0
tie_word_embeddings = 0
Parameters
model_dir Model directory containing HuggingFace artifacts.
out_ex Output extended hyperparameter struct (written on success).
Returns
IE_IO_OK on success, negative ie_io_status_t on failure.
Definition at line 776 of file gptoss_hparams.c.
{
  if (!model_dir || !out_ex) return IE_IO_ERR_ARGS;
  char cfg[1024];
  const int r = gptoss_resolve_config_path(model_dir, cfg, sizeof(cfg));
  if (r != IE_IO_OK) return r;
  const int rc = gptoss_hparams_load_ex_from_file(cfg, out_ex);
  if (rc != IE_IO_OK) return rc;
  return gptoss_finalize_and_validate(model_dir, out_ex);
}
References gptoss_finalize_and_validate(), gptoss_hparams_load_ex_from_file(), gptoss_resolve_config_path(), IE_IO_ERR_ARGS, and IE_IO_OK.
Referenced by gptoss_hparams_load(), and ie_engine_create().
gptoss_hparams_load_ex_from_file()
int gptoss_hparams_load_ex_from_file (const char * config_json_path, gptoss_hparams_ex_t * out_ex)
Load extended hyperparameters from an explicit HuggingFace config path.
Parameters
config_json_path Path to a HuggingFace config.json.
out_ex Output extended hyperparameter struct (written on success).
Returns
IE_IO_OK on success, negative ie_io_status_t on failure.
Definition at line 757 of file gptoss_hparams.c.
{
  if (!config_json_path || !out_ex) return IE_IO_ERR_ARGS;
  gptoss_hparams_ex_defaults(out_ex);
  char *buf = NULL;
  size_t len = 0;
  const int rc = gptoss_read_all_text(config_json_path, &buf, &len);
  if (rc != IE_IO_OK) return rc;
  if (!buf || len == 0) {
    free(buf);
    return IE_IO_ERR_READ;
  }
  const int prc = gptoss_parse_config_json(buf, out_ex);
  free(buf);
  return prc;
}
References gptoss_hparams_ex_defaults(), gptoss_parse_config_json(), gptoss_read_all_text(), IE_IO_ERR_ARGS, IE_IO_ERR_READ, and IE_IO_OK.
Referenced by gptoss_hparams_load_ex().