Inference Engine (Clocher): engine/include/ie_api.h File Reference
ie_api.h File Reference
Public C API for creating an inference engine instance and generating tokens.
#include <stddef.h>
Data Structures
struct ie_engine_params
Engine creation parameters.
struct ie_generate_stats
Optional generation timing statistics.
Typedefs
typedef enum ie_status ie_status_t
Status codes returned by the public API.
typedef struct ie_engine_params ie_engine_params_t
Engine creation parameters.
typedef struct ie_engine ie_engine_t
Opaque engine type.
typedef struct ie_generate_stats ie_generate_stats_t
Optional generation timing statistics.
Enumerations
enum ie_status {
IE_OK = 0 , IE_ERR_BADARG = 1 , IE_ERR_OOM = 2 , IE_ERR_MODEL = 3 ,
IE_ERR_UNSUPPORTED = 4 , IE_ERR_INTERNAL = 5
}
Status codes returned by the public API.
Functions
ie_status_t ie_engine_create (const ie_engine_params_t *p, const char *device, const char *model_dir, ie_engine_t **out)
Create an engine instance.
void ie_engine_destroy (ie_engine_t *e)
Destroy an engine instance.
ie_status_t ie_engine_generate (const ie_engine_t *e, const char *prompt, size_t max_new, int *out_tokens, size_t *out_n_tokens)
Generate up to max_new tokens for the given prompt.
ie_status_t ie_engine_generate_ex (const ie_engine_t *e, const char *prompt, size_t max_new, int *out_tokens, size_t *out_n_tokens, ie_generate_stats_t *out_stats)
Generate tokens and optionally return timing statistics.
Detailed Description
Public C API for creating an inference engine instance and generating tokens.
This header intentionally keeps the interface small and stable:
The CLI can create an engine for a given (device, model_dir) pair.
Generation emits integer token ids into a caller-provided buffer.
The extended generation entrypoint can optionally return timing statistics:
Total wall time
Prefill time
Decode-loop time
Decode-only TPS (cannot be inflated by prefill)
Definition in file ie_api.h.
Typedef Documentation
ie_engine_params_t
typedef struct ie_engine_params ie_engine_params_t
Engine creation parameters.
All string fields are expected to be long-lived for the duration of engine use (or copied by the implementation).
ie_engine_t
typedef struct ie_engine ie_engine_t
Opaque engine type.
Definition at line 99 of file ie_api.h.
ie_generate_stats_t
typedef struct ie_generate_stats ie_generate_stats_t
Optional generation timing statistics.
Times are in seconds.
Interpretation:
wall_time_s: total time inside generation call (includes encode, KV alloc, prefill, decode loop).
prefill_time_s: time spent in prefill only.
decode_time_s: time spent in the decode loop only.
tps_decode: tokens per second computed from decode_time_s only.
tps_total: tokens per second computed from wall_time_s (can be useful, but not for decode-only comparisons).
ttft_s: best-effort time-to-first-token (prefill + first decode step).
ie_status_t
typedef enum ie_status ie_status_t
Status codes returned by the public API.
Enumeration Type Documentation
ie_status
enum ie_status
Status codes returned by the public API.
Enumerator
IE_OK
Success.
IE_ERR_BADARG
Invalid argument.
IE_ERR_OOM
Allocation failed.
IE_ERR_MODEL
Model could not be loaded or accessed.
IE_ERR_UNSUPPORTED
Unsupported device or configuration.
IE_ERR_INTERNAL
Internal failure.
Definition at line 32 of file ie_api.h.
                       {
  IE_OK = 0,
  IE_ERR_BADARG = 1,
  IE_ERR_OOM = 2,
  IE_ERR_MODEL = 3,
  IE_ERR_UNSUPPORTED = 4,
  IE_ERR_INTERNAL = 5
} ie_status_t;
Function Documentation
ie_engine_create()
ie_status_t ie_engine_create (const ie_engine_params_t * p, const char * device, const char * model_dir, ie_engine_t ** out)
Create an engine instance.
Parameters
p Engine params (may be NULL for defaults).
device Device string (e.g., "cpu", "cuda", "auto").
model_dir Directory that contains model artifacts.
out Receives the created engine pointer on success.
Returns
Status code.
Definition at line 535 of file ie_api.c.
{
  if (!model_dir || !out) {
    ie_log_error("ie_engine_create: bad args (model_dir=%p out=%p)", (const void *)model_dir, (void *)out);
    return IE_ERR_BADARG;
  }
  *out = NULL;
  const char *dev_str = device ? device : "cpu";
  ie_log_info("ie_engine_create: begin (device=%s model_dir=%s)", dev_str, model_dir);
  if (p) {
    ie_log_info("ie_engine_create: params precision=%s sparsity=%s affinity=%s pretranspose=%s prefetch=%s threads=%d",
                (p->precision ? p->precision : "(null)"),
                (p->sparsity ? p->sparsity : "(null)"),
                (p->affinity ? p->affinity : "(null)"),
                (p->pretranspose ? p->pretranspose : "(null)"),
                (p->prefetch ? p->prefetch : "(null)"),
                p->threads);
  if (is_precision_int4_(p)) {
    ie_log_info("ie_engine_create: q4 kernel=%s (runtime-dispatched)", ie_q4_kernel_selected_name());
  }
  }
  ie_engine_t *e = (ie_engine_t *)calloc(1, sizeof(*e));
  if (!e) {
    ie_log_error("ie_engine_create: OOM allocating engine struct");
    return IE_ERR_OOM;
  }
  ie_log_info("ie_engine_create: device_create (device=%s)", dev_str);
  const ie_device_kind_t kind = ie_device_kind_from_str(dev_str);
  const int dev_rc = ie_device_create(kind, &e->dev);
  if (dev_rc != 0 || !e->dev) {
    ie_log_error("ie_engine_create: device_create failed (rc=%d device=%s)", dev_rc, dev_str);
    free(e);
    return IE_ERR_UNSUPPORTED;
  }
  const char *tok_path = NULL;
  char tok_path_buf[4096];
  if (p && p->tokenizer_path && p->tokenizer_path[0] != '\0') {
    tok_path = p->tokenizer_path;
  } else {
    join_path_(tok_path_buf, sizeof(tok_path_buf), model_dir, "tokenizer.json");
    tok_path = tok_path_buf;
  }
  ie_log_info("ie_engine_create: tokenizer_open (path=%s)", tok_path);
  const int tok_rc = ie_tok_gptoss_open(tok_path, &e->tok);
  if (tok_rc != 0 || !e->tok) {
    ie_log_error("ie_engine_create: tokenizer_open failed (rc=%d path=%s)", tok_rc, tok_path);
    ie_device_destroy(e->dev);
    free(e);
    return IE_ERR_MODEL;
  }
  const uint32_t tok_vocab = ie_tok_gptoss_vocab_size(e->tok);
  ie_log_info("ie_engine_create: tokenizer_open ok (vocab=%" PRIu32 ")", tok_vocab);
  const char *weights_json = NULL;
  const char *bin_override = "";
  char weights_json_buf[PATH_MAX];
  char compat_json_buf[PATH_MAX];
  char q4_bin_buf[PATH_MAX];
  const int want_int4 = (p && is_precision_int4_(p));
  if (p && p->weights_json_path && p->weights_json_path[0] != '\0') {
    weights_json = p->weights_json_path;
  } else if (want_int4) {
    join_path_(compat_json_buf, sizeof(compat_json_buf), model_dir, "model.ie.compat.json");
    if (path_exists_(compat_json_buf)) {
      weights_json = compat_json_buf;
    }
  }
  if (weights_json == NULL) {
    join_path_(weights_json_buf, sizeof(weights_json_buf), model_dir, "model.ie.json");
    weights_json = weights_json_buf;
  }
  if (p && p->weights_bin_path && p->weights_bin_path[0] != '\0') {
    bin_override = p->weights_bin_path;
  } else if (want_int4) {
    join_path_(q4_bin_buf, sizeof(q4_bin_buf), model_dir, "model.q4.bin");
    if (path_exists_(q4_bin_buf)) {
      bin_override = q4_bin_buf;
    }
  }
  ie_log_info("ie_engine_create: weights_open (json=%s bin_override=%s)", weights_json,
              (bin_override[0] != '\0' ? bin_override : "(null)"));
  const int w_rc = ie_weights_open(weights_json, bin_override, &e->w);
  if (w_rc != 0) {
    ie_log_error("ie_engine_create: weights_open failed (rc=%d json=%s)", w_rc, weights_json);
    ie_tok_gptoss_close(e->tok);
    ie_device_destroy(e->dev);
    free(e);
    return IE_ERR_MODEL;
  }
  ie_log_info("ie_engine_create: weights_open ok (dtype=%s bin=%s bin_size_bytes=%zu dedup=%d)",
              e->w.dtype,
              e->w.weights_path,
              e->w.bin_size_bytes,
              e->w.is_dedup ? 1 : 0);
  /* Load base hparams first (shapes/sizes). */
  ie_log_info("ie_engine_create: hparams_load (dir=%s)", model_dir);
  const int hp_rc = gptoss_hparams_load(model_dir, &e->hp);
  if (hp_rc != 0) {
    ie_log_error("ie_engine_create: hparams_load failed (rc=%d dir=%s)", hp_rc, model_dir);
    ie_weights_close(&e->w);
    ie_tok_gptoss_close(e->tok);
    ie_device_destroy(e->dev);
    free(e);
    return IE_ERR_MODEL;
  }
  /* Load extended config (eps/theta/rope scaling). */
  ie_log_info("ie_engine_create: hparams_load_ex (dir=%s)", model_dir);
  const int ex_rc = gptoss_hparams_load_ex(model_dir, &e->hpx);
  if (ex_rc != 0) {
    ie_log_warn("ie_engine_create: hparams_load_ex failed (rc=%d dir=%s). Continuing with base hparams only.", ex_rc, model_dir);
    memset(&e->hpx, 0, sizeof(e->hpx));
  }
  log_hparams_(&e->hp);
  if (ex_rc == 0) log_hparams_ex_(&e->hpx);
  if (tok_vocab != 0 && e->hp.vocab_size != 0 && tok_vocab != e->hp.vocab_size) {
    ie_log_warn("ie_engine_create: tokenizer vocab (%" PRIu32 ") != hparams vocab (%" PRIu32 ")",
                tok_vocab,
                e->hp.vocab_size);
  }
  maybe_correct_head_dim_(model_dir, &e->hp);
  ie_log_info("ie_engine_create: infer_create");
  const int inf_rc = ie_gptoss_infer_create(e->dev, &e->w, &e->hp, &e->infer);
  if (inf_rc != 0 || !e->infer) {
    ie_log_error("ie_engine_create: infer_create failed (rc=%d)", inf_rc);
    ie_weights_close(&e->w);
    ie_tok_gptoss_close(e->tok);
    ie_device_destroy(e->dev);
    free(e);
    return IE_ERR_INTERNAL;
  }
  e->logits_len = (size_t)e->hp.vocab_size;
  if (e->logits_len == 0) {
    ie_log_error("ie_engine_create: invalid vocab_size=0; cannot allocate logits");
    ie_gptoss_infer_destroy(e->infer);
    ie_weights_close(&e->w);
    ie_tok_gptoss_close(e->tok);
    ie_device_destroy(e->dev);
    free(e);
    return IE_ERR_MODEL;
  }
  const size_t bytes_logits = e->logits_len * sizeof(float);
  const size_t bytes_idx = e->logits_len * sizeof(uint32_t);
  const size_t bytes_prob = e->logits_len * sizeof(float);
  ie_log_info("ie_engine_create: allocating scratch (logits=%zu bytes idx=%zu bytes prob=%zu bytes)",
              bytes_logits,
              bytes_idx,
              bytes_prob);
  e->logits = (float *)malloc(bytes_logits);
  e->scratch_idx = (uint32_t *)malloc(bytes_idx);
  e->scratch_prob = (float *)malloc(bytes_prob);
  e->scratch_cap = e->logits_len;
  if (!e->logits || !e->scratch_idx || !e->scratch_prob) {
    ie_log_error("ie_engine_create: OOM allocating scratch (logits=%p idx=%p prob=%p)",
                 (void *)e->logits,
                 (void *)e->scratch_idx,
                 (void *)e->scratch_prob);
    free(e->scratch_prob);
    free(e->scratch_idx);
    free(e->logits);
    ie_gptoss_infer_destroy(e->infer);
    ie_weights_close(&e->w);
    ie_tok_gptoss_close(e->tok);
    ie_device_destroy(e->dev);
    free(e);
    return IE_ERR_OOM;
  }
  /*
   * Sampling configuration
   *
   * The benchmarking harness measures token-id generation. For deterministic
   * verification runs, the CLI can set IE_GREEDY=1 (via --greedy) or you can
   * set IE_SAMPLE_KIND=greedy to force greedy decoding.
   */
  ie_sample_cfg_t sample_cfg;
  sample_cfg.kind = IE_SAMPLE_TOPP;
  sample_cfg.temperature = 0.8000f;
  sample_cfg.top_p = 0.9500f;
  sample_cfg.top_k = 0u;
  sample_cfg.disallow_token0 = 1u;
  const char *kind_env = getenv("IE_SAMPLE_KIND");
  if (kind_env && kind_env[0]) {
    if (streq_icase_(kind_env, "greedy")) {
      sample_cfg.kind = IE_SAMPLE_GREEDY;
    } else if (streq_icase_(kind_env, "topk")) {
      sample_cfg.kind = IE_SAMPLE_TOPK;
    } else if (streq_icase_(kind_env, "topp")) {
      sample_cfg.kind = IE_SAMPLE_TOPP;
    } else {
      ie_log_warn("ie_engine_create: unrecognized IE_SAMPLE_KIND=\"%s\"; using defaults", kind_env);
    }
  }
  if (env_flag_("IE_GREEDY", 0)) {
    sample_cfg.kind = IE_SAMPLE_GREEDY;
  }
  if (sample_cfg.kind == IE_SAMPLE_GREEDY) {
    /* Greedy ignores temperature/top-p/top-k; keep them in a neutral state. */
    sample_cfg.temperature = 1.0000f;
    sample_cfg.top_p = 1.0000f;
    sample_cfg.top_k = 0u;
  }
  ie_log_info("ie_engine_create: sampling config (kind=%d/%s temp=%.4f top_p=%.4f top_k=%u disallow_token0=%u)",
              (int)sample_cfg.kind,
              sample_kind_str_(sample_cfg.kind),
              (double)sample_cfg.temperature,
              (double)sample_cfg.top_p,
              (unsigned)sample_cfg.top_k,
              (unsigned)sample_cfg.disallow_token0);
  e->sample_cfg = sample_cfg;
  unsigned long long seed = env_u64_("IE_SEED", 1ull, 0ull, ~0ull);
  if (seed == 0ull) seed = 1ull;
  ie_rng_init(&e->rng, (uint64_t)seed);
  ie_log_info("ie_engine_create: RNG seeded (seed=%llu)", seed);
  *out = e;
  ie_log_info("ie_engine_create: success (engine=%p)", (void *)e);
  return IE_OK;
}
References ie_engine_params::affinity, ie_weights_s::bin_size_bytes, ie_engine::dev, ie_sample_cfg_s::disallow_token0, ie_weights_s::dtype, env_flag_(), env_u64_(), gptoss_hparams_load(), gptoss_hparams_load_ex(), ie_engine::hp, ie_engine::hpx, ie_device_create(), ie_device_destroy(), ie_device_kind_from_str(), IE_ERR_BADARG, IE_ERR_INTERNAL, IE_ERR_MODEL, IE_ERR_OOM, IE_ERR_UNSUPPORTED, ie_gptoss_infer_create(), ie_gptoss_infer_destroy(), ie_log_error(), ie_log_info(), ie_log_warn(), IE_OK, ie_q4_kernel_selected_name(), ie_rng_init(), IE_SAMPLE_GREEDY, IE_SAMPLE_TOPK, IE_SAMPLE_TOPP, ie_tok_gptoss_close(), ie_tok_gptoss_open(), ie_tok_gptoss_vocab_size(), ie_weights_close(), ie_weights_open(), ie_engine::infer, ie_weights_s::is_dedup, is_precision_int4_(), join_path_(), ie_sample_cfg_s::kind, log_hparams_(), log_hparams_ex_(), ie_engine::logits, ie_engine::logits_len, maybe_correct_head_dim_(), path_exists_(), PATH_MAX, ie_engine_params::precision, ie_engine_params::prefetch, ie_engine_params::pretranspose, ie_engine::rng, ie_engine::sample_cfg, sample_kind_str_(), ie_engine::scratch_cap, ie_engine::scratch_idx, ie_engine::scratch_prob, ie_engine_params::sparsity, streq_icase_(), ie_sample_cfg_s::temperature, ie_engine_params::threads, ie_engine::tok, ie_engine_params::tokenizer_path, ie_sample_cfg_s::top_k, ie_sample_cfg_s::top_p, ie_gptoss_hparams::vocab_size, ie_engine::w, ie_engine_params::weights_bin_path, ie_engine_params::weights_json_path, and ie_weights_s::weights_path.
Referenced by main(), and main().
ie_engine_destroy()
void ie_engine_destroy (ie_engine_t * e)
Destroy an engine instance.
Parameters
e Engine pointer (may be NULL).
Definition at line 788 of file ie_api.c.
{
  if (!e) return;
  ie_log_info("ie_engine_destroy: begin (engine=%p)", (void *)e);
  free(e->scratch_prob);
  free(e->scratch_idx);
  free(e->logits);
  if (e->infer) {
    ie_log_info("ie_engine_destroy: infer_destroy");
    ie_gptoss_infer_destroy(e->infer);
  }
  ie_log_info("ie_engine_destroy: weights_close");
  ie_weights_close(&e->w);
  if (e->tok) {
    ie_log_info("ie_engine_destroy: tokenizer_close");
    ie_tok_gptoss_close(e->tok);
  }
  if (e->dev) {
    ie_log_info("ie_engine_destroy: device_destroy");
    ie_device_destroy(e->dev);
  }
  free(e);
  ie_log_info("ie_engine_destroy: done");
}
References ie_engine::dev, ie_device_destroy(), ie_gptoss_infer_destroy(), ie_log_info(), ie_tok_gptoss_close(), ie_weights_close(), ie_engine::infer, ie_engine::logits, ie_engine::scratch_idx, ie_engine::scratch_prob, ie_engine::tok, and ie_engine::w.
Referenced by main(), and main().
ie_engine_generate()
ie_status_t ie_engine_generate (const ie_engine_t * e, const char * prompt, size_t max_new, int * out_tokens, size_t * out_n_tokens)
Generate up to max_new tokens for the given prompt.
This is the stable entrypoint that only returns token ids. For timing breakdowns, use ie_engine_generate_ex.
Parameters
e Engine pointer (required).
prompt Prompt string (may be empty, must be non-NULL).
max_new Maximum number of tokens to generate.
out_tokens Output buffer (length at least max_new when max_new>0).
out_n_tokens Receives number of generated tokens.
Returns
Status code.
Definition at line 818 of file ie_api.c.
{
  return ie_engine_generate_ex(e, prompt, max_new, out_tokens, out_n_tokens, NULL);
}
References ie_engine_generate_ex().
Referenced by main(), and main().
ie_engine_generate_ex()
ie_status_t ie_engine_generate_ex (const ie_engine_t * e, const char * prompt, size_t max_new, int * out_tokens, size_t * out_n_tokens, ie_generate_stats_t * out_stats)
Generate tokens and optionally return timing statistics.
Parameters
e Engine pointer (required).
prompt Prompt string (may be empty, must be non-NULL).
max_new Maximum number of tokens to generate.
out_tokens Output buffer (length at least max_new when max_new>0).
out_n_tokens Receives number of generated tokens.
out_stats Optional timing breakdown (may be NULL).
Returns
Status code.
Definition at line 826 of file ie_api.c.
{
  if (!e || !prompt || !out_n_tokens) {
    ie_log_error("ie_engine_generate_ex: bad args (e=%p prompt=%p out_n_tokens=%p)",
                 (const void *)e,
                 (const void *)prompt,
                 (void *)out_n_tokens);
    return IE_ERR_BADARG;
  }
  if (max_new > 0 && !out_tokens) {
    ie_log_error("ie_engine_generate_ex: bad args (max_new=%zu out_tokens=NULL)", max_new);
    return IE_ERR_BADARG;
  }
  *out_n_tokens = 0;
  if (out_stats) {
    memset(out_stats, 0, sizeof(*out_stats));
  }
  if (max_new == 0) {
    ie_log_info("ie_engine_generate_ex: max_new=0; nothing to do");
    return IE_OK;
  }
  const double t_total0 = now_s_();
  ie_log_info("ie_engine_generate_ex: begin (engine=%p max_new=%zu)", (const void *)e, max_new);
  log_prompt_preview_(prompt);
  const int log_tokens = env_flag_("IE_API_LOG_TOKENS", 0);
  const int log_every = env_int_("IE_API_LOG_EVERY", 0, 0, 1000000);
  const int dbg_decode = env_flag_("IE_API_DEBUG_DECODE", 0);
  const int dbg_decode_every = env_int_("IE_API_DEBUG_DECODE_EVERY", 0, 0, 1000000);
  const int dbg_topk = env_int_("IE_DEBUG_TOPK", 0, 0, 64);
  const int dbg_topk_every = env_int_("IE_DEBUG_TOPK_EVERY", 0, 0, 1000000);
  uint32_t need = 0;
  int rc = ie_tok_gptoss_encode(e->tok, prompt, NULL, &need);
  if (rc != 0) {
    ie_log_error("ie_engine_generate_ex: tokenizer encode size-query failed (rc=%d)", rc);
    return IE_ERR_MODEL;
  }
  ie_log_info("ie_engine_generate_ex: tokenizer size-query ok (need_tokens=%" PRIu32 ")", need);
  uint32_t n_prompt = (need == 0) ? 1u : need;
  uint32_t *prompt_ids = (uint32_t *)malloc((size_t)n_prompt * sizeof(uint32_t));
  if (!prompt_ids) {
    ie_log_error("ie_engine_generate_ex: OOM allocating prompt_ids (n_prompt=%" PRIu32 ")", n_prompt);
    return IE_ERR_OOM;
  }
  if (need == 0) {
    prompt_ids[0] = 0;
    n_prompt = 1;
    ie_log_warn("ie_engine_generate_ex: prompt encoded to empty; forcing token_id=0");
  } else {
    uint32_t inout = n_prompt;
    rc = ie_tok_gptoss_encode(e->tok, prompt, prompt_ids, &inout);
    if (rc != 0) {
      ie_log_error("ie_engine_generate_ex: tokenizer encode failed (rc=%d capacity=%" PRIu32 ")", rc, n_prompt);
      free(prompt_ids);
      return IE_ERR_MODEL;
    }
    n_prompt = inout;
    if (n_prompt == 0) {
      prompt_ids[0] = 0;
      n_prompt = 1;
      ie_log_warn("ie_engine_generate_ex: encode returned 0 tokens; forcing token_id=0");
    }
  }
  ie_log_info("ie_engine_generate_ex: encoded prompt tokens=%" PRIu32, n_prompt);
  size_t trace_prompt_index = 0;
  const int trace_prompt = trace_ids_prompt_index_(&trace_prompt_index);
  if (trace_prompt) {
    trace_ids_prompt_(trace_prompt_index, prompt, prompt_ids, n_prompt);
  }
  if (log_tokens) {
    const uint32_t cap = (n_prompt < 32u) ? n_prompt : 32u;
    char line[512];
    size_t pos = 0;
    pos += (size_t)snprintf(line + pos, sizeof(line) - pos, "prompt_ids[0..%u):", (unsigned)cap);
    for (uint32_t i = 0; i < cap && pos + 16 < sizeof(line); ++i) {
      pos += (size_t)snprintf(line + pos, sizeof(line) - pos, " %u", (unsigned)prompt_ids[i]);
    }
    if (cap < n_prompt && pos + 8 < sizeof(line)) {
      (void)snprintf(line + pos, sizeof(line) - pos, " ...");
    }
    ie_log_info("%s", line);
  }
  if (e->hp.n_layers == 0) {
    ie_log_error("ie_engine_generate_ex: invalid hparams (n_layers=0)");
    free(prompt_ids);
    return IE_ERR_MODEL;
  }
  const size_t n_layers = (size_t)e->hp.n_layers;
  ie_kv_cache *kv_layers = (ie_kv_cache *)calloc(n_layers, sizeof(*kv_layers));
  if (!kv_layers) {
    ie_log_error("ie_engine_generate_ex: OOM allocating kv_layers (n_layers=%zu)", n_layers);
    free(prompt_ids);
    return IE_ERR_OOM;
  }
  ie_kv_opts kv_opts;
  memset(&kv_opts, 0, sizeof(kv_opts));
  kv_opts.storage = IE_KV_STORAGE_F32;
  kv_opts.heads = (int32_t)e->hp.n_kv_heads;
  kv_opts.head_dim = (int32_t)e->hp.d_head;
  int32_t want_seq = (int32_t)n_prompt + (int32_t)max_new + 8;
  if (want_seq < 16) want_seq = 16;
  int32_t hp_seq = (int32_t)e->hp.max_seq;
  if (hp_seq <= 0) hp_seq = want_seq;
  kv_opts.max_seq = (want_seq < hp_seq) ? want_seq : hp_seq;
  ie_log_info("ie_engine_generate_ex: kv_opts heads=%" PRIi32 " head_dim=%" PRIi32 " want_seq=%" PRIi32 " hp_seq=%" PRIi32 " max_seq=%" PRIi32,
              kv_opts.heads,
              kv_opts.head_dim,
              want_seq,
              hp_seq,
              kv_opts.max_seq);
  if (kv_opts.heads <= 0 || kv_opts.head_dim <= 0 || kv_opts.max_seq <= 0) {
    ie_log_error("ie_engine_generate_ex: invalid kv_opts (heads=%" PRIi32 " head_dim=%" PRIi32 " max_seq=%" PRIi32 ")",
                 kv_opts.heads,
                 kv_opts.head_dim,
                 kv_opts.max_seq);
    free(kv_layers);
    free(prompt_ids);
    return IE_ERR_MODEL;
  }
  if (ie_kv_init_layers(kv_layers, (int)e->hp.n_layers, &kv_opts) != 0) {
    ie_log_error("ie_engine_generate_ex: kv_init_layers failed (n_layers=%" PRIu32 ")", e->hp.n_layers);
    free(kv_layers);
    free(prompt_ids);
    return IE_ERR_OOM;
  }
  const double t_prefill0 = now_s_();
  ie_log_info("ie_engine_generate_ex: prefill begin (n_prompt=%" PRIu32 " logits_len=%zu)", n_prompt, e->logits_len);
  rc = ie_gptoss_infer_prefill(e->infer, kv_layers, prompt_ids, n_prompt, e->logits);
  const double t_prefill1 = now_s_();
  if (rc != 0) {
    const ie_status_t st = status_from_rc_(rc);
    ie_log_error("ie_engine_generate_ex: prefill failed (rc=%d -> %s)", rc, status_str_(st));
    ie_kv_free_layers(kv_layers, (int)e->hp.n_layers);
    free(kv_layers);
    free(prompt_ids);
    return st;
  }
  ie_log_info("ie_engine_generate_ex: prefill ok (time=%.6fs)", (t_prefill1 > t_prefill0) ? (t_prefill1 - t_prefill0) : 0.0);
  if (dbg_topk > 0) {
    debug_dump_topk_(e->tok, e->logits, e->logits_len, dbg_topk, "prefill");
  }
  const double t_decode0 = now_s_();
  size_t produced = 0;
  double ttft_s = 0.0;
  for (; produced < max_new; ++produced) {
    uint32_t next = 0;
    rc = ie_sample_next(e->logits,
                        e->logits_len,
                        &e->sample_cfg,
                        (ie_rng_t *)&e->rng,
                        e->scratch_idx,
                        e->scratch_prob,
                        e->scratch_cap,
                        &next);
    if (rc != 0) {
      ie_log_error("ie_engine_generate_ex: sample_next failed at step=%zu (rc=%d). Stopping early.", produced, rc);
      break;
    }
    out_tokens[produced] = (int)next;
    if (trace_prompt) {
      trace_ids_step_(trace_prompt_index, produced, next);
    }
    if (log_every > 0 && (produced % (size_t)log_every) == 0) {
      ie_log_info("ie_engine_generate_ex: step=%zu next_token=%" PRIu32, produced, next);
    }
    rc = ie_gptoss_infer_step(e->infer, kv_layers, next, e->logits);
    if (rc != 0) {
      const ie_status_t st = status_from_rc_(rc);
      ie_log_error("ie_engine_generate_ex: infer_step failed at step=%zu token=%" PRIu32 " (rc=%d -> %s)",
                   produced,
                   next,
                   rc,
                   status_str_(st));
      ie_kv_free_layers(kv_layers, (int)e->hp.n_layers);
      free(kv_layers);
      free(prompt_ids);
      return st;
    }
    if (produced == 0) {
      const double t_now = now_s_();
      ttft_s = (t_now > t_total0) ? (t_now - t_total0) : 0.0;
    }
    if (dbg_topk > 0 && dbg_topk_every > 0 && (produced % (size_t)dbg_topk_every) == 0) {
      char tag[64];
      (void)snprintf(tag, sizeof(tag), "step_%zu", produced);
      debug_dump_topk_(e->tok, e->logits, e->logits_len, dbg_topk, tag);
    }
    if (dbg_decode && dbg_decode_every > 0 && (produced % (size_t)dbg_decode_every) == 0) {
      size_t need_bytes = 0;
      const uint32_t cnt = (uint32_t)(produced + 1);
      const int drc = ie_tok_gptoss_decode(e->tok, (const uint32_t *)out_tokens, cnt, NULL, &need_bytes);
      if (drc == 0 && need_bytes > 0 && need_bytes < (size_t)(1u << 22)) {
        char *txt = (char *)malloc(need_bytes);
        if (txt) {
          size_t inout = need_bytes;
          const int drc2 = ie_tok_gptoss_decode(e->tok, (const uint32_t *)out_tokens, cnt, txt, &inout);
          if (drc2 == 0) {
            txt[need_bytes - 1] = '\0';
            ie_log_info("ie_engine_generate_ex: decoded[%u] bytes=%zu preview=\"%s%s\"",
                        cnt,
                        inout,
                        txt,
                        (inout > 120 ? "..." : ""));
          } else {
            ie_log_warn("ie_engine_generate_ex: decode failed (rc=%d) at step=%zu", drc2, produced);
          }
          free(txt);
        }
      } else {
        ie_log_warn("ie_engine_generate_ex: decode size-query failed (rc=%d need_bytes=%zu) at step=%zu",
                    drc,
                    need_bytes,
                    produced);
      }
    }
  }
  const double t_decode1 = now_s_();
  *out_n_tokens = produced;
  ie_log_info("ie_engine_generate_ex: done (produced=%zu requested=%zu)", produced, max_new);
  ie_kv_free_layers(kv_layers, (int)e->hp.n_layers);
  free(kv_layers);
  free(prompt_ids);
  const double t_total1 = now_s_();
  if (out_stats) {
    out_stats->wall_time_s = (t_total1 > t_total0) ? (t_total1 - t_total0) : 0.0;
    out_stats->prefill_time_s = (t_prefill1 > t_prefill0) ? (t_prefill1 - t_prefill0) : 0.0;
    out_stats->decode_time_s = (t_decode1 > t_decode0) ? (t_decode1 - t_decode0) : 0.0;
    out_stats->ttft_s = ttft_s;
    out_stats->tps_decode = (out_stats->decode_time_s > 0.0) ? ((double)produced / out_stats->decode_time_s) : 0.0;
    out_stats->tps_total = (out_stats->wall_time_s > 0.0) ? ((double)produced / out_stats->wall_time_s) : 0.0;
  }
  return IE_OK;
}
References ie_gptoss_hparams::d_head, debug_dump_topk_(), ie_generate_stats::decode_time_s, env_flag_(), env_int_(), ie_kv_opts::head_dim, ie_kv_opts::heads, ie_engine::hp, IE_ERR_BADARG, IE_ERR_MODEL, IE_ERR_OOM, ie_gptoss_infer_prefill(), ie_gptoss_infer_step(), ie_kv_free_layers(), ie_kv_init_layers(), IE_KV_STORAGE_F32, ie_log_error(), ie_log_info(), ie_log_warn(), IE_OK, ie_sample_next(), ie_tok_gptoss_decode(), ie_tok_gptoss_encode(), ie_engine::infer, log_prompt_preview_(), ie_engine::logits, ie_engine::logits_len, ie_gptoss_hparams::max_seq, ie_kv_opts::max_seq, ie_gptoss_hparams::n_kv_heads, ie_gptoss_hparams::n_layers, now_s_(), ie_generate_stats::prefill_time_s, ie_engine::rng, ie_engine::sample_cfg, ie_engine::scratch_cap, ie_engine::scratch_idx, ie_engine::scratch_prob, status_from_rc_(), status_str_(), ie_kv_opts::storage, ie_engine::tok, ie_generate_stats::tps_decode, ie_generate_stats::tps_total, trace_ids_prompt_(), trace_ids_prompt_index_(), trace_ids_step_(), ie_generate_stats::ttft_s, and ie_generate_stats::wall_time_s.
Referenced by ie_engine_generate(), and main().