Inference Engine (Clocher): engine/src/devices/ie_device_cuda_stub.c File Reference
ie_device_cuda_stub.c File Reference
#include "ie_device_cuda.h"
#include <stddef.h>
#include <stdint.h>
Functions
int ie_cuda_is_available (void)
Returns non-zero if at least one CUDA device is available.
int ie_cuda_init (int device_ordinal, char *out_name, size_t name_cap, char *out_driver, size_t driver_cap)
Initialize CUDA for a given device ordinal and return basic identity strings.
void * ie_cuda_malloc (size_t nbytes)
Allocate device memory.
void ie_cuda_free (void *p)
Free device memory allocated by ie_cuda_malloc().
int ie_cuda_memcpy (void *dst, const void *src, size_t nbytes, ie_cuda_copy_kind_t kind)
Copy memory using CUDA.
int ie_cuda_gemv_f32 (const float *dW, const float *dx, float *dy, size_t rows, size_t cols, const float *dbias)
Launch a GEMV FP32 kernel: y = W*x + bias (bias optional).
int ie_cuda_gemv_q4_0_f32 (const uint8_t *dW_q4, const uint8_t *dW_scales, size_t scale_bytes, const float *dx, float *dy, size_t rows, size_t cols, const uint16_t *dbias_bf16)
Launch a GEMV Q4_0 kernel: y = dequant(Wq4) * x (+ optional BF16 bias).
const char * ie_cuda_last_error_string (void)
Retrieve the last CUDA error string (C ABI).
Function Documentation
ie_cuda_free()
void ie_cuda_free (void * p)
Free device memory allocated by ie_cuda_malloc().
Parameters
p Device pointer (may be NULL).
Free device memory allocated by ie_cuda_malloc().
Parameters
p Device pointer (may be NULL).
Definition at line 25 of file ie_device_cuda_stub.c.
{
  (void)p;
}
References ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_destroy_thunk(), and cuda_ensure_capacity().
ie_cuda_gemv_f32()
int ie_cuda_gemv_f32 (const float * dW, const float * dx, float * dy, size_t rows, size_t cols, const float * dbias)
Launch a GEMV FP32 kernel: y = W*x + bias (bias optional).
All pointers must be device pointers. bias may be NULL.
Parameters
dW Device pointer to row-major matrix W (rows x cols).
dx Device pointer to vector x (cols).
dy Device pointer to vector y (rows).
rows Number of rows in W / entries in y.
cols Number of cols in W / entries in x.
dbias Optional device pointer to bias (rows) or NULL.
Returns
0 on success, negative on failure.
Launch a GEMV FP32 kernel: y = W*x + bias (bias optional).
Parameters
dW Device pointer to row-major weights (rows x cols).
dx Device pointer to input vector (cols).
dy Device pointer to output vector (rows).
rows Rows.
cols Cols.
dbias Optional bias vector (rows) or NULL.
Returns
0 on success, negative on failure.
Definition at line 37 of file ie_device_cuda_stub.c.
{
  (void)dW;
  (void)dx;
  (void)dy;
  (void)rows;
  (void)cols;
  (void)dbias;
  return -1;
}
References g_last_err, ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_gemv_f32_thunk().
ie_cuda_gemv_q4_0_f32()
int ie_cuda_gemv_q4_0_f32 (const uint8_t * dW_q4, const uint8_t * dW_scales, size_t scale_bytes, const float * dx, float * dy, size_t rows, size_t cols, const uint16_t * dbias_bf16)
Launch a GEMV Q4_0 kernel: y = dequant(Wq4) * x (+ optional BF16 bias).
All pointers must be device pointers. bias may be NULL.
Parameters
dW_q4 Device pointer to packed Q4_0 weights.
dW_scales Device pointer to per-block scales.
scale_bytes Bytes per scale (1 or 2).
dx Device pointer to input vector (FP32).
dy Device pointer to output vector (FP32).
rows Rows.
cols Cols (multiple of 32).
dbias_bf16 Optional device pointer to BF16 bias (rows) or NULL.
Returns
0 on success, negative on failure.
Launch a GEMV Q4_0 kernel: y = dequant(Wq4) * x (+ optional BF16 bias).
Definition at line 52 of file ie_device_cuda_stub.c.
{
  (void)dW_q4;
  (void)dW_scales;
  (void)scale_bytes;
  (void)dx;
  (void)dy;
  (void)rows;
  (void)cols;
  (void)dbias_bf16;
  return -1;
}
References g_last_err, ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_gemv_q4_0_f32_thunk().
ie_cuda_init()
int ie_cuda_init (int device_ordinal, char * out_name, size_t name_cap, char * out_driver, size_t driver_cap)
Initialize CUDA for a given device ordinal and return basic identity strings.
This performs cudaSetDevice() and a minimal runtime initialization (cudaFree(0)) so that driver activity is observable (e.g., /dev/nvidiactl gets touched).
Parameters
device_ordinal CUDA device ordinal (0..N-1).
out_name Output buffer for the GPU name (may be NULL if name_cap=0).
name_cap Capacity of out_name in bytes.
out_driver Output buffer for a driver/runtime version string (may be NULL if driver_cap=0).
driver_cap Capacity of out_driver in bytes.
Returns
0 on success, negative on failure.
Initialize CUDA for a given device ordinal and return basic identity strings.
This forces runtime/driver initialization via cudaFree(0) so preflight checks can observe real driver activity.
Parameters
device_ordinal CUDA device ordinal.
out_name Output buffer for device name (may be NULL).
name_cap Capacity of out_name in bytes.
out_driver Output buffer for driver/runtime versions (may be NULL).
driver_cap Capacity of out_driver in bytes.
Returns
0 on success, negative on failure.
Definition at line 11 of file ie_device_cuda_stub.c.
{
  (void)device_ordinal;
  if (out_name && name_cap) out_name[0] = '\0';
  if (out_driver && driver_cap) out_driver[0] = '\0';
  return -1;
}
References ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_try_create().
ie_cuda_is_available()
int ie_cuda_is_available (void)
Returns non-zero if at least one CUDA device is available.
This call will initialize the CUDA runtime enough to query device count.
Returns
1 if devices exist, 0 otherwise.
Returns non-zero if at least one CUDA device is available.
Returns
1 if at least one CUDA device is visible, 0 otherwise.
Definition at line 7 of file ie_device_cuda_stub.c.
{
  return 0;
}
References ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_try_create().
ie_cuda_malloc()
void * ie_cuda_malloc (size_t nbytes)
Allocate device memory.
Parameters
nbytes Number of bytes.
Returns
Device pointer on success, NULL on failure.
Allocate device memory.
Parameters
nbytes Number of bytes.
Returns
Device pointer on success, NULL on failure.
Definition at line 20 of file ie_device_cuda_stub.c.
{
  (void)nbytes;
  return NULL;
}
References ie_cuda_clear_last_error(), and ie_cuda_set_last_error_cuda().
Referenced by cuda_ensure_capacity().
ie_cuda_memcpy()
int ie_cuda_memcpy (void * dst, const void * src, size_t nbytes, ie_cuda_copy_kind_t kind)
Copy memory using CUDA.
For IE_CUDA_COPY_DEFAULT, cudaMemcpyDefault is used.
Parameters
dst Destination pointer.
src Source pointer.
nbytes Number of bytes.
kind Copy kind.
Returns
0 on success, negative on failure.
Copy memory using CUDA.
Parameters
dst Destination pointer.
src Source pointer.
nbytes Number of bytes.
kind Copy direction.
Returns
0 on success, negative on failure.
Definition at line 29 of file ie_device_cuda_stub.c.
{
  (void)dst;
  (void)src;
  (void)nbytes;
  (void)kind;
  return -1;
}
References ie_cuda_clear_last_error(), IE_CUDA_COPY_D2D, IE_CUDA_COPY_D2H, IE_CUDA_COPY_DEFAULT, IE_CUDA_COPY_H2D, and ie_cuda_set_last_error_cuda().
Referenced by cuda_gemv_f32_thunk(), cuda_gemv_q4_0_f32_thunk(), and cuda_memcpy_thunk().