Inference Engine (Clocher): engine/include/ie_sampler.h File Reference
ie_sampler.h File Reference
Logits sampling utilities (greedy, temperature, top-k, top-p).
#include <stddef.h>
#include <stdint.h>
Data Structures
struct ie_sampler_cfg
Sampling configuration.
Typedefs
typedef enum ie_sampler_status ie_sampler_status_t
Sampler status codes.
typedef struct ie_sampler_cfg ie_sampler_cfg_t
Sampling configuration.
typedef struct ie_sampler ie_sampler_t
Opaque sampler handle.
Enumerations
enum ie_sampler_status { IE_SAMPLER_OK = 0 , IE_SAMPLER_EINVAL = -1 , IE_SAMPLER_ENOMEM = -2 , IE_SAMPLER_EINTERNAL = -3 }
Sampler status codes.
Functions
void ie_sampler_cfg_default (ie_sampler_cfg_t *cfg)
Fill a configuration struct with sane defaults.
ie_sampler_status_t ie_sampler_create (ie_sampler_t **out, size_t vocab_size, const ie_sampler_cfg_t *cfg, uint64_t seed)
Create a sampler for a fixed vocabulary size.
void ie_sampler_destroy (ie_sampler_t **ps)
Destroy a sampler and release all resources.
ie_sampler_status_t ie_sampler_set_cfg (ie_sampler_t *s, const ie_sampler_cfg_t *cfg)
Update sampler configuration.
ie_sampler_status_t ie_sampler_set_seed (ie_sampler_t *s, uint64_t seed)
Reset sampler RNG seed.
ie_sampler_status_t ie_sampler_sample (ie_sampler_t *s, const float *logits, size_t logits_len, uint32_t *out_id, float *out_prob)
Sample a token id from logits.
const char * ie_sampler_status_str (ie_sampler_status_t st)
Convert status to string.
Detailed Description
Logits sampling utilities (greedy, temperature, top-k, top-p).
This module converts a logits vector into a next-token id using common decoding strategies. It is designed to be:
deterministic given a seed and identical logits
independent of tokenizer and model I/O
safe under -Wall/-Wextra/-Werror/-pedantic
Typical usage: 1) Create a sampler for a fixed vocab size: ie_sampler_cfg_t cfg; ie_sampler_cfg_default(&cfg); cfg.temperature = 0.8f; cfg.top_p = 0.95f;
ie_sampler_t *s = NULL; ie_sampler_create(&s, vocab_size, &cfg, 1234);
2) For each step: uint32_t next_id = 0; ie_sampler_sample(s, logits, vocab_size, &next_id, NULL);
3) Destroy when done: ie_sampler_destroy(&s);
Definition in file ie_sampler.h.
Typedef Documentation
ie_sampler_cfg_t
typedef struct ie_sampler_cfg ie_sampler_cfg_t
Sampling configuration.
Interpretation:
If temperature <= 0, sampling defaults to greedy argmax.
top_k == 0 disables top-k filtering.
top_p >= 1 disables nucleus (top-p) filtering.
If both top_k and top_p are enabled, filtering applies as:
compute probabilities (softmax)
sort descending by probability
apply top_k truncation (keep first K)
apply top_p truncation (keep smallest prefix with cumulative >= top_p)
renormalize and sample
ie_sampler_status_t
typedef enum ie_sampler_status ie_sampler_status_t
Sampler status codes.
ie_sampler_t
typedef struct ie_sampler ie_sampler_t
Opaque sampler handle.
The sampler owns scratch buffers sized for the vocab size.
Definition at line 86 of file ie_sampler.h.
Enumeration Type Documentation
ie_sampler_status
enum ie_sampler_status
Sampler status codes.
Enumerator
IE_SAMPLER_OK
Success.
IE_SAMPLER_EINVAL
Invalid argument.
IE_SAMPLER_ENOMEM
Allocation failure.
IE_SAMPLER_EINTERNAL
Internal error (unexpected state).
Definition at line 44 of file ie_sampler.h.
{
  IE_SAMPLER_OK = 0,
  IE_SAMPLER_EINVAL = -1,
  IE_SAMPLER_ENOMEM = -2,
  IE_SAMPLER_EINTERNAL = -3
} ie_sampler_status_t;
Function Documentation
ie_sampler_cfg_default()
void ie_sampler_cfg_default (ie_sampler_cfg_t * cfg)
Fill a configuration struct with sane defaults.
Defaults:
temperature = 1.0
top_p = 1.0 (disabled)
top_k = 0 (disabled)
allow_nan_logits = 0
Parameters
[out] cfg Configuration to initialize.
Definition at line 344 of file ie_sampler.c.
{
  if (!cfg) return;
  cfg->temperature = 1.0f;
  cfg->top_p = 1.0f;
  cfg->top_k = 0;
  cfg->allow_nan_logits = 0;
}
References ie_sampler_cfg::allow_nan_logits, ie_sampler_cfg::temperature, ie_sampler_cfg::top_k, and ie_sampler_cfg::top_p.
Referenced by ie_sampler_create().
ie_sampler_create()
ie_sampler_status_t ie_sampler_create (ie_sampler_t ** out, size_t vocab_size, const ie_sampler_cfg_t * cfg, uint64_t seed)
Create a sampler for a fixed vocabulary size.
Parameters
[out] out Receives newly allocated sampler on success.
[in] vocab_size Vocabulary size (logits length).
[in] cfg Sampling configuration (may be NULL for defaults).
[in] seed Initial RNG seed (deterministic).
Returns
IE_SAMPLER_OK on success, negative on error.
Definition at line 352 of file ie_sampler.c.
{
  if (!out || vocab_size == 0) return IE_SAMPLER_EINVAL;
  *out = NULL;
  ie_sampler_t *s = (ie_sampler_t *)calloc(1, sizeof(*s));
  if (!s) return IE_SAMPLER_ENOMEM;
  s->vocab_size = vocab_size;
  ie_sampler_cfg_default(&s->cfg);
  if (cfg) s->cfg = *cfg;
  s->rng = seed ? seed : 0x9e3779b97f4a7c15ULL;
  s->probs = (float *)malloc(sizeof(float) * vocab_size);
  s->items = (ie_prob_item_t *)malloc(sizeof(ie_prob_item_t) * vocab_size);
  if (!s->probs || !s->items) {
    free(s->probs);
    free(s->items);
    free(s);
    return IE_SAMPLER_ENOMEM;
  }
  *out = s;
  return IE_SAMPLER_OK;
}
References ie_sampler::cfg, ie_sampler_cfg_default(), IE_SAMPLER_EINVAL, IE_SAMPLER_ENOMEM, IE_SAMPLER_OK, ie_sampler::items, ie_sampler::probs, ie_sampler::rng, and ie_sampler::vocab_size.
ie_sampler_destroy()
void ie_sampler_destroy (ie_sampler_t ** ps)
Destroy a sampler and release all resources.
Safe to call with NULL or *ps == NULL.
Parameters
[in,out] ps Address of sampler handle; set to NULL on return.
Definition at line 381 of file ie_sampler.c.
{
  if (!ps || !*ps) return;
  ie_sampler_t *s = *ps;
  free(s->probs);
  free(s->items);
  free(s);
  *ps = NULL;
}
References ie_sampler::items, and ie_sampler::probs.
ie_sampler_sample()
ie_sampler_status_t ie_sampler_sample (ie_sampler_t * s, const float * logits, size_t logits_len, uint32_t * out_id, float * out_prob)
Sample a token id from logits.
If sampling degenerates to greedy (temperature <= 0, or all mass collapses), this returns argmax.
Parameters
[in,out] s Sampler handle.
[in] logits Pointer to logits array (length = logits_len).
[in] logits_len Length of logits array (should equal vocab_size).
[out] out_id Receives sampled token id.
[out] out_prob Optional. Receives probability of selected token under the filtered distribution.
Returns
IE_SAMPLER_OK on success, negative on error.
Definition at line 404 of file ie_sampler.c.
{
  if (!s || !logits || !out_id) return IE_SAMPLER_EINVAL;
  if (logits_len != s->vocab_size) return IE_SAMPLER_EINVAL;
  static uint64_t g_call_idx = 0;
  g_call_idx++;
  const float temperature = s->cfg.temperature;
  const uint32_t top_k = s->cfg.top_k;
  const float top_p = s->cfg.top_p;
  const int allow_nan = s->cfg.allow_nan_logits;
  if (!(temperature > 0.0f)) {
    uint32_t id = 0;
    if (!argmax_logits(logits, logits_len, allow_nan, &id)) return IE_SAMPLER_EINVAL;
    *out_id = id;
    if (out_prob) *out_prob = 1.0f;
    if (debug_topk_should_dump_(g_call_idx)) {
      const int k = debug_topk_k_();
      debug_dump_topk_logits_(logits, NULL, logits_len, temperature, allow_nan, k, g_call_idx);
      fprintf(stderr, "[sampler][chosen] call=%" PRIu64 " id=%" PRIu32 " prob=1\n",
              (uint64_t)g_call_idx, id);
    }
    return IE_SAMPLER_OK;
  }
  if (!softmax_probs(logits, logits_len, temperature, allow_nan, s->probs)) {
    uint32_t id = 0;
    if (!argmax_logits(logits, logits_len, allow_nan, &id)) return IE_SAMPLER_EINVAL;
    *out_id = id;
    if (out_prob) *out_prob = 1.0f;
    if (debug_topk_should_dump_(g_call_idx)) {
      const int k = debug_topk_k_();
      debug_dump_topk_logits_(logits, NULL, logits_len, temperature, allow_nan, k, g_call_idx);
      fprintf(stderr, "[sampler][chosen] call=%" PRIu64 " id=%" PRIu32 " prob=1 (softmax_failed)\n",
              (uint64_t)g_call_idx, id);
    }
    return IE_SAMPLER_OK;
  }
  if (debug_topk_should_dump_(g_call_idx)) {
    const int k = debug_topk_k_();
    debug_dump_topk_logits_(logits, s->probs, logits_len, temperature, allow_nan, k, g_call_idx);
  }
  for (size_t i = 0; i < logits_len; ++i) {
    s->items[i].id = (uint32_t)i;
    s->items[i].p = s->probs[i];
  }
  qsort(s->items, logits_len, sizeof(s->items[0]), prob_item_cmp_desc);
  size_t kept = logits_len;
  if (top_k != 0 && top_k < kept) kept = (size_t)top_k;
  if (top_p < 1.0f) {
    float cum = 0.0f;
    size_t k = 0;
    while (k < kept) {
      cum += s->items[k].p;
      ++k;
      if (cum >= top_p) break;
    }
    if (k == 0) k = 1;
    kept = k;
  }
  float sum = 0.0f;
  for (size_t i = 0; i < kept; ++i) sum += s->items[i].p;
  if (!(sum > 0.0f) || isnan(sum) || isinf(sum)) {
    uint32_t id = s->items[0].id;
    *out_id = id;
    if (out_prob) *out_prob = 1.0f;
    if (debug_topk_should_dump_(g_call_idx)) {
      fprintf(stderr, "[sampler][chosen] call=%" PRIu64 " id=%" PRIu32 " prob=1 (degenerate_sum)\n",
              (uint64_t)g_call_idx, id);
    }
    return IE_SAMPLER_OK;
  }
  float r = rng_next_f01(&s->rng);
  float acc = 0.0f;
  uint32_t chosen = s->items[kept - 1].id;
  float chosen_p = s->items[kept - 1].p / sum;
  for (size_t i = 0; i < kept; ++i) {
    float p = s->items[i].p / sum;
    acc += p;
    if (r < acc) {
      chosen = s->items[i].id;
      chosen_p = p;
      break;
    }
  }
  *out_id = chosen;
  if (out_prob) *out_prob = chosen_p;
  if (debug_topk_should_dump_(g_call_idx)) {
    char piece[160];
    decode_preview_(chosen, piece, sizeof(piece));
    fprintf(stderr,
            "[sampler][chosen] call=%" PRIu64 " id=%" PRIu32 " prob=%.9g piece=\"%s\"\n",
            (uint64_t)g_call_idx,
            chosen,
            (double)chosen_p,
            piece);
  }
  return IE_SAMPLER_OK;
}
References ie_sampler_cfg::allow_nan_logits, argmax_logits(), ie_sampler::cfg, debug_dump_topk_logits_(), debug_topk_k_(), debug_topk_should_dump_(), decode_preview_(), ie_prob_item::id, IE_SAMPLER_EINVAL, IE_SAMPLER_OK, ie_sampler::items, ie_prob_item::p, prob_item_cmp_desc(), ie_sampler::probs, ie_sampler::rng, rng_next_f01(), softmax_probs(), ie_sampler_cfg::temperature, ie_sampler_cfg::top_k, ie_sampler_cfg::top_p, and ie_sampler::vocab_size.
ie_sampler_set_cfg()
ie_sampler_status_t ie_sampler_set_cfg (ie_sampler_t * s, const ie_sampler_cfg_t * cfg)
Update sampler configuration.
Parameters
[in,out] s Sampler handle.
[in] cfg New configuration (must be non-NULL).
Returns
IE_SAMPLER_OK on success, negative on error.
Definition at line 392 of file ie_sampler.c.
{
  if (!s || !cfg) return IE_SAMPLER_EINVAL;
  s->cfg = *cfg;
  return IE_SAMPLER_OK;
}
References ie_sampler::cfg, IE_SAMPLER_EINVAL, and IE_SAMPLER_OK.
ie_sampler_set_seed()
ie_sampler_status_t ie_sampler_set_seed (ie_sampler_t * s, uint64_t seed)
Reset sampler RNG seed.
Parameters
[in,out] s Sampler handle.
[in] seed New seed value.
Returns
IE_SAMPLER_OK on success, negative on error.
Definition at line 398 of file ie_sampler.c.
{
  if (!s) return IE_SAMPLER_EINVAL;
  s->rng = seed ? seed : 0x9e3779b97f4a7c15ULL;
  return IE_SAMPLER_OK;
}
References IE_SAMPLER_EINVAL, IE_SAMPLER_OK, and ie_sampler::rng.
ie_sampler_status_str()
const char * ie_sampler_status_str (ie_sampler_status_t st)
Convert status to string.
Parameters
[in] st Status code.
Returns
Constant string describing the status.
Definition at line 525 of file ie_sampler.c.
{
  switch (st) {
    case IE_SAMPLER_OK: return "IE_SAMPLER_OK";
    case IE_SAMPLER_EINVAL: return "IE_SAMPLER_EINVAL";
    case IE_SAMPLER_ENOMEM: return "IE_SAMPLER_ENOMEM";
    case IE_SAMPLER_EINTERNAL: return "IE_SAMPLER_EINTERNAL";
    default: return "IE_SAMPLER_UNKNOWN";
  }
}
References IE_SAMPLER_EINTERNAL, IE_SAMPLER_EINVAL, IE_SAMPLER_ENOMEM, and IE_SAMPLER_OK.