Inference Engine (Clocher): engine/include/ie_sampling.h File Reference
ie_sampling.h File Reference
Token sampling utilities for next-token selection from logits.
#include <stddef.h>
#include <stdint.h>
Data Structures
struct ie_sample_cfg_s
Sampling configuration.
struct ie_rng_s
Simple RNG state (xorshift64*).
Typedefs
typedef enum ie_sample_kind_e ie_sample_kind_t
Sampling strategy selector.
typedef struct ie_sample_cfg_s ie_sample_cfg_t
Sampling configuration.
typedef struct ie_rng_s ie_rng_t
Simple RNG state (xorshift64*).
Enumerations
enum ie_sample_kind_e { IE_SAMPLE_GREEDY = 0 , IE_SAMPLE_TOPK = 1 , IE_SAMPLE_TOPP = 2 }
Sampling strategy selector.
Functions
void ie_rng_init (ie_rng_t *rng, uint64_t seed)
Initialize RNG with a seed (must be non-zero; 0 is remapped).
uint32_t ie_rng_u32 (ie_rng_t *rng)
Return a random uint32.
float ie_rng_f32 (ie_rng_t *rng)
Return a random float in [0, 1).
int ie_sample_next (const float *logits, size_t vocab_size, const ie_sample_cfg_t *cfg, ie_rng_t *rng, uint32_t *idx_scratch, float *prob_scratch, size_t scratch_cap, uint32_t *out_id)
Choose next token id from logits using the given configuration.
Detailed Description
Token sampling utilities for next-token selection from logits.
This module provides small, allocation-free (caller-provided scratch) helpers to choose the next token id from a logits vector.
Supported strategies:
Greedy (argmax)
Top-k (sample from k highest logits)
Top-p / nucleus (sample from smallest set with cumulative probability >= p)
Notes:
Logits are assumed to be unnormalized. Softmax is computed over the filtered set only (or full vocab for top-p before truncation).
For determinism, provide an explicit RNG seed and update it per step.
No dependency on libc RNG; uses xorshift64*.
Thread-safety:
All functions are pure with respect to inputs, except RNG state which the caller owns and mutates.
Definition in file ie_sampling.h.
Typedef Documentation
ie_rng_t
typedef struct ie_rng_s ie_rng_t
Simple RNG state (xorshift64*).
Initialize with any non-zero seed.
ie_sample_cfg_t
typedef struct ie_sample_cfg_s ie_sample_cfg_t
Sampling configuration.
ie_sample_kind_t
typedef enum ie_sample_kind_e ie_sample_kind_t
Sampling strategy selector.
Enumeration Type Documentation
ie_sample_kind_e
enum ie_sample_kind_e
Sampling strategy selector.
Enumerator
IE_SAMPLE_GREEDY
IE_SAMPLE_TOPK
IE_SAMPLE_TOPP
Definition at line 36 of file ie_sampling.h.
{
  IE_SAMPLE_GREEDY = 0,
  IE_SAMPLE_TOPK = 1,
  IE_SAMPLE_TOPP = 2
} ie_sample_kind_t;
Function Documentation
ie_rng_f32()
float ie_rng_f32 (ie_rng_t * rng)
Return a random float in [0, 1).
Parameters
rng RNG state.
Returns
Random float.
Return a random float in [0, 1).
Produces 24 bits of mantissa using the high bits of a 32-bit random value.
Parameters
rng RNG state.
Returns
Random float in [0,1). If rng is NULL, returns 0.
Definition at line 176 of file sampling.c.
{
  uint32_t x = ie_rng_u32(rng);
  uint32_t m = x >> 8; /* 24 bits */
  return (float)m / (float)(1u << 24);
}
References ie_rng_u32().
Referenced by sample_from_probs().
ie_rng_init()
void ie_rng_init (ie_rng_t * rng, uint64_t seed)
Initialize RNG with a seed (must be non-zero; 0 is remapped).
Parameters
rng RNG state.
seed Seed value.
Initialize RNG with a seed (must be non-zero; 0 is remapped).
Uses xorshift64* for cheap non-cryptographic randomness. If seed is 0, a fixed non-zero seed is used to avoid the zero lock state.
Parameters
rng RNG state (output).
seed Seed value.
Definition at line 136 of file sampling.c.
{
  if (!rng) return;
  rng->s = (seed == 0) ? 0x9E3779B97F4A7C15ull : seed;
}
References ie_rng_s::s.
Referenced by ie_engine_create(), and ie_generate_gptoss().
ie_rng_u32()
uint32_t ie_rng_u32 (ie_rng_t * rng)
Return a random uint32.
Parameters
rng RNG state.
Returns
Random number.
Return a random uint32.
Parameters
rng RNG state.
Returns
Random 32-bit value (0 on NULL rng).
Definition at line 162 of file sampling.c.
{
  if (!rng) return 0;
  return (uint32_t)(xorshift64star(&rng->s) >> 32);
}
References ie_rng_s::s, and xorshift64star().
Referenced by ie_rng_f32().
ie_sample_next()
int ie_sample_next (const float * logits, size_t vocab_size, const ie_sample_cfg_t * cfg, ie_rng_t * rng, uint32_t * idx_scratch, float * prob_scratch, size_t scratch_cap, uint32_t * out_id)
Choose next token id from logits using the given configuration.
This function may require scratch buffers for indices and probabilities. The caller provides them to avoid allocations.
Scratch requirements:
idx_scratch: capacity >= vocab_size (used for partial selection / sorting).
prob_scratch: capacity >= vocab_size (used for softmax over candidate set).
If you only use greedy mode, scratch may be NULL.
Parameters
logits Input logits array of length vocab_size.
vocab_size Vocabulary size.
cfg Sampling config.
rng RNG state (used for stochastic sampling).
idx_scratch Scratch indices array (uint32_t).
prob_scratch Scratch probabilities array (float).
scratch_cap Capacity of idx_scratch and prob_scratch.
out_id Output token id.
Returns
0 on success, negative on error.
Definition at line 326 of file sampling.c.
{
  if (!logits || vocab_size == 0 || !cfg_in || !out_id) return -1;
  ie_sample_cfg_t cfg;
  if (cfg_sanitize(cfg_in, &cfg) != 0) return -1;
  if (sampling_trace_allow()) {
    fprintf(stderr,
            "[sampling] kind=%s temp=%.6g top_k=%u top_p=%.6g disallow0=%d vocab=%zu\n",
            kind_name(cfg.kind),
            (double)cfg.temperature,
            (unsigned)cfg.top_k,
            (double)cfg.top_p,
            (int)cfg.disallow_token0,
            vocab_size);
  }
  if (cfg.kind == IE_SAMPLE_GREEDY) {
    const uint32_t id = argmax_logits(logits, vocab_size, cfg.disallow_token0);
    *out_id = id;
    if (sampling_trace_allow()) {
      fprintf(stderr, "[sampling] greedy -> id=%u logit=%.6g\n", (unsigned)id, (double)logits[id]);
    }
    return 0;
  }
  if (!idx_scratch || !prob_scratch || scratch_cap < vocab_size) return -1;
  if (!rng) return -1;
  if (cfg.kind == IE_SAMPLE_TOPK) {
    uint32_t k = cfg.top_k;
    if (k > (uint32_t)vocab_size) k = (uint32_t)vocab_size;
    uint32_t sel_n = 0;
    for (size_t i = 0; i < vocab_size && sel_n < k; ++i) {
      if (cfg.disallow_token0 && i == 0) continue;
      idx_scratch[sel_n++] = (uint32_t)i;
    }
    if (sel_n == 0) {
      *out_id = 0;
      if (sampling_trace_allow()) fprintf(stderr, "[sampling] topk -> empty selection, id=0\n");
      return 0;
    }
    /* Keep selection sorted ascending by logit so idx_scratch[0] is the current worst. */
    for (uint32_t i = 1; i < sel_n; ++i) {
      uint32_t key = idx_scratch[i];
      float v = logits[key];
      uint32_t j = i;
      while (j > 0) {
        uint32_t prev = idx_scratch[j - 1];
        if (logits[prev] <= v) break;
        idx_scratch[j] = prev;
        --j;
      }
      idx_scratch[j] = key;
    }
    for (size_t i = 0; i < vocab_size; ++i) {
      if (cfg.disallow_token0 && i == 0) continue;
      float v = logits[i];
      uint32_t worst = idx_scratch[0];
      if (v <= logits[worst]) continue;
      idx_scratch[0] = (uint32_t)i;
      for (uint32_t j = 1; j < sel_n; ++j) {
        uint32_t a = idx_scratch[j - 1];
        uint32_t b = idx_scratch[j];
        if (logits[a] <= logits[b]) continue;
        idx_scratch[j - 1] = b;
        idx_scratch[j] = a;
      }
    }
    float maxl = -INFINITY;
    for (uint32_t i = 0; i < sel_n; ++i) {
      float v = logits[idx_scratch[i]] / cfg.temperature;
      if (v > maxl) maxl = v;
    }
    for (uint32_t i = 0; i < sel_n; ++i) {
      float v = (logits[idx_scratch[i]] / cfg.temperature) - maxl;
      prob_scratch[i] = safe_exp(v);
    }
    softmax_inplace(prob_scratch, sel_n);
    const uint32_t id = sample_from_probs(prob_scratch, idx_scratch, sel_n, rng);
    *out_id = id;
    if (sampling_trace_allow()) {
      fprintf(stderr, "[sampling] topk(k=%u sel=%u) -> id=%u logit=%.6g\n",
              (unsigned)k, (unsigned)sel_n, (unsigned)id, (double)logits[id]);
    }
    return 0;
  }
  if (cfg.kind == IE_SAMPLE_TOPP) {
    float maxl = -INFINITY;
    for (size_t i = 0; i < vocab_size; ++i) {
      if (cfg.disallow_token0 && i == 0) continue;
      float v = logits[i] / cfg.temperature;
      if (v > maxl) maxl = v;
    }
    float sum = 0.0f;
    for (size_t i = 0; i < vocab_size; ++i) {
      if (cfg.disallow_token0 && i == 0) {
        prob_scratch[i] = 0.0f;
        continue;
      }
      float v = (logits[i] / cfg.temperature) - maxl;
      float e = safe_exp(v);
      prob_scratch[i] = e;
      sum += e;
    }
    if (sum <= 0.0f) {
      const uint32_t id = argmax_logits(logits, vocab_size, cfg.disallow_token0);
      *out_id = id;
      if (sampling_trace_allow()) {
        fprintf(stderr, "[sampling] topp -> degenerate sum, fallback greedy id=%u\n", (unsigned)id);
      }
      return 0;
    }
    float inv = 1.0f / sum;
    for (size_t i = 0; i < vocab_size; ++i) prob_scratch[i] *= inv;
    size_t nidx = 0;
    for (size_t i = 0; i < vocab_size; ++i) {
      if (cfg.disallow_token0 && i == 0) continue;
      idx_scratch[nidx++] = (uint32_t)i;
    }
    sort_desc_by_prob(idx_scratch, prob_scratch, nidx);
    float cum = 0.0f;
    size_t cut = 0;
    for (; cut < nidx; ++cut) {
      cum += prob_scratch[idx_scratch[cut]];
      if (cum >= cfg.top_p) {
        ++cut;
        break;
      }
    }
    if (cut == 0) cut = 1;
    if (cut > nidx) cut = nidx;
    float local_sum = 0.0f;
    for (size_t i = 0; i < cut; ++i) local_sum += prob_scratch[idx_scratch[i]];
    if (local_sum <= 0.0f) {
      *out_id = idx_scratch[0];
      if (sampling_trace_allow()) fprintf(stderr, "[sampling] topp -> degenerate local_sum, id=%u\n", (unsigned)*out_id);
      return 0;
    }
    float linv = 1.0f / local_sum;
    for (size_t i = 0; i < cut; ++i) {
      prob_scratch[i] = prob_scratch[idx_scratch[i]] * linv;
    }
    const uint32_t id = sample_from_probs(prob_scratch, idx_scratch, cut, rng);
    *out_id = id;
    if (sampling_trace_allow()) {
      fprintf(stderr, "[sampling] topp(p=%.6g cut=%zu cum=%.6g) -> id=%u logit=%.6g\n",
              (double)cfg.top_p, cut, (double)cum, (unsigned)id, (double)logits[id]);
    }
    return 0;
  }
  return -1;
}
References argmax_logits(), cfg_sanitize(), ie_sample_cfg_s::disallow_token0, IE_SAMPLE_GREEDY, IE_SAMPLE_TOPK, IE_SAMPLE_TOPP, ie_sample_cfg_s::kind, kind_name(), safe_exp(), sample_from_probs(), sampling_trace_allow(), softmax_inplace(), sort_desc_by_prob(), ie_sample_cfg_s::temperature, ie_sample_cfg_s::top_k, and ie_sample_cfg_s::top_p.
Referenced by ie_engine_generate_ex(), and ie_generate_gptoss().