Inference Engine (Clocher): engine/src/devices/ie_device_common.c File Reference
ie_device_common.c File Reference
C11 device abstraction with CPU backend and a real CUDA backend.
#include "ie_device.h"
#include "ie_device_cuda.h"
#include "ie_kernels.h"
#include "sparse_format.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct ie_device_vtbl
Virtual method table for a device backend.
struct ie_device
Public device object combining vtable and backend-specific impl pointer.
struct cpu_impl
struct cuda_impl
CUDA backend implementation state.
struct ze_impl
Typedefs
typedef struct ie_device_vtbl ie_device_vtbl_t
Virtual method table for a device backend.
typedef struct cpu_impl cpu_impl_t
typedef struct cuda_impl cuda_impl_t
CUDA backend implementation state.
typedef struct ze_impl ze_impl_t
Functions
static cpu_impl_t * cpu_new (void)
Allocate a CPU backend instance.
static int cpu_caps (const void *self, ie_device_caps_t *out)
Report CPU device capabilities.
static int cpu_gemv_f32 (void *self, const float *W, const float *x, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k)
Execute dense GEMV FP32 on CPU using existing kernels.
static int cpu_gemv_q4_0_f32 (void *self, const uint8_t *w_q4, const uint8_t *w_scales, size_t scale_bytes, const float *x, float *y, size_t rows, size_t cols, const uint16_t *bias_bf16)
Execute Q4_0 GEMV on CPU using existing kernels.
static int cpu_memcpy (void *self, void *dst, const void *src, size_t nbytes)
CPU memcpy implementation.
static int cpu_gemv_block_sparse_f32 (void *self, const ie_block_sparse_matrix_t *m, const float *x, float *y, const float *bias)
CPU implementation of block-sparse GEMV FP32.
static void cpu_destroy (void *self)
Destroy CPU backend instance.
static int cuda_ensure_capacity (void **pbuf, size_t *pcap, size_t nbytes)
Ensure a device buffer has at least nbytes capacity.
static int cuda_caps_thunk (const void *self, ie_device_caps_t *out)
Report CUDA device capabilities.
static int cuda_memcpy_thunk (void *self, void *dst, const void *src, size_t nbytes)
CUDA memcpy implementation using the CUDA wrapper.
static int cuda_gemv_f32_thunk (void *self, const float *W, const float *x, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k)
CUDA GEMV FP32 implementation.
static int cuda_gemv_q4_0_f32_thunk (void *self, const uint8_t *w_q4, const uint8_t *w_scales, size_t scale_bytes, const float *x, float *y, size_t rows, size_t cols, const uint16_t *bias_bf16)
CUDA GEMV Q4_0 implementation.
static int cuda_gemv_block_sparse_f32_unimpl (void *self, const ie_block_sparse_matrix_t *m, const float *x, float *y, const float *bias)
CUDA block-sparse GEMV implementation.
static void cuda_destroy_thunk (void *self)
Destroy CUDA backend instance and free device buffers.
static int cuda_try_create (void **out_impl, ie_device_vtbl_t *out_vt)
Initialize CUDA backend.
static int ze_caps_thunk (const void *self, ie_device_caps_t *out)
Level Zero caps thunk used in the vtable.
static int ze_gemv_f32_stub (void *self, const float *W, const float *x, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k)
Level Zero GEMV FP32 stub (unimplemented).
static int ze_gemv_q4_0_f32_stub (void *self, const uint8_t *w_q4, const uint8_t *w_scales, size_t scale_bytes, const float *x, float *y, size_t rows, size_t cols, const uint16_t *bias_bf16)
Level Zero GEMV Q4_0 stub (unimplemented).
static int ze_memcpy_stub (void *self, void *dst, const void *src, size_t nbytes)
Level Zero memcpy stub (unimplemented).
static int ze_gemv_block_sparse_f32_stub (void *self, const ie_block_sparse_matrix_t *m, const float *x, float *y, const float *bias)
Level Zero block-sparse GEMV FP32 stub (unimplemented).
static void ze_destroy_thunk (void *self)
Destroy Level Zero backend instance.
static int ze_try_create (void **out_impl, ie_device_vtbl_t *out_vt)
Try to initialize Level Zero backend (stub).
int ie_device_create (ie_device_kind_t kind, ie_device_t **out_dev)
Create a device backend.
void ie_device_destroy (ie_device_t *dev)
Destroy a device instance.
int ie_device_caps (const ie_device_t *dev, ie_device_caps_t *out_caps)
Query device capabilities.
int ie_device_gemv_f32 (ie_device_t *dev, const float *W, const float *x, float *y, size_t rows, size_t cols, const float *bias, size_t blk_k)
Execute dense GEMV FP32 through backend.
int ie_device_gemv_q4_0_f32 (ie_device_t *dev, const uint8_t *w_q4, const uint8_t *w_scales, size_t scale_bytes, const float *x, float *y, size_t rows, size_t cols, const uint16_t *bias_bf16)
Execute GEMV Q4_0 through backend.
int ie_device_gemv_block_sparse_f32 (ie_device_t *dev, const ie_block_sparse_matrix_t *m, const float *x, float *y, const float *bias)
Execute block-sparse GEMV FP32 through backend.
int ie_device_memcpy (ie_device_t *dev, void *dst, const void *src, size_t nbytes)
Execute memcpy through backend.
ie_device_kind_t ie_device_kind (const ie_device_t *dev)
Return the device kind.
ie_device_kind_t ie_device_kind_from_str (const char *s)
Parse a device kind from string.
Detailed Description
C11 device abstraction with CPU backend and a real CUDA backend.
The CUDA backend is implemented through a narrow C ABI wrapper layer (ie_device_cuda.cu + ie_device_cuda.h) to avoid including CUDA headers in C translation units.
Key properties:
If CUDA is explicitly requested and initialization fails, we return an error (no silent CPU fallback that would create fake GPU reports).
GEMV FP32 on CUDA is correctness-first: it copies inputs to the device, launches a simple kernel, and copies outputs back. Optimization (persistent weight residency, streams, fusion, etc.) can follow.
Definition in file ie_device_common.c.
Typedef Documentation
cpu_impl_t
typedef struct cpu_impl cpu_impl_t
cuda_impl_t
typedef struct cuda_impl cuda_impl_t
CUDA backend implementation state.
This implementation is correctness-first and uses temporary device buffers. A later optimization step should keep weights resident on-device and use streams to overlap transfers and compute.
ie_device_vtbl_t
typedef struct ie_device_vtbl ie_device_vtbl_t
Virtual method table for a device backend.
ze_impl_t
typedef struct ze_impl ze_impl_t
Function Documentation
cpu_caps()
static int cpu_caps (const void * self, ie_device_caps_t * out) static
Report CPU device capabilities.
CPU backend supports GEMV FP32 and memcpy.
Definition at line 90 of file ie_device_common.c.
{
  (void)self;
  if (!out) return -1;
  memset(out, 0, sizeof(*out));
  out->has_gemv_f32 = 1;
  out->has_mem_copy = 1;
  out->has_streams  = 0;
  snprintf(out->name,   sizeof(out->name),   "CPU");
  snprintf(out->driver, sizeof(out->driver), "N/A");
  return 0;
}
Referenced by ie_device_create().
cpu_destroy()
static void cpu_destroy (void * self) static
Destroy CPU backend instance.
Definition at line 159 of file ie_device_common.c.
{
  free(self);
}
Referenced by ie_device_create().
cpu_gemv_block_sparse_f32()
static int cpu_gemv_block_sparse_f32 (void * self, const ie_block_sparse_matrix_t * m, const float * x, float * y, const float * bias) static
CPU implementation of block-sparse GEMV FP32.
Definition at line 145 of file ie_device_common.c.
{
  (void)self;
  if (!m || !x || !y) return -1;
  ie_gemv_block_sparse_f32(m, x, y, bias);
  return 0;
}
References ie_gemv_block_sparse_f32().
Referenced by ie_device_create().
cpu_gemv_f32()
static int cpu_gemv_f32 (void * self, const float * W, const float * x, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k) static
Execute dense GEMV FP32 on CPU using existing kernels.
Definition at line 105 of file ie_device_common.c.
{
  (void)self;
  (void)blk_k;
  if (!W || !x || !y || rows == 0 || cols == 0) return -1;
  ie_gemv_f32(W, x, y, rows, cols, bias, 0);
  return 0;
}
References ie_gemv_f32().
Referenced by ie_device_create().
cpu_gemv_q4_0_f32()
static int cpu_gemv_q4_0_f32 (void * self, const uint8_t * w_q4, const uint8_t * w_scales, size_t scale_bytes, const float * x, float * y, size_t rows, size_t cols, const uint16_t * bias_bf16) static
Execute Q4_0 GEMV on CPU using existing kernels.
Definition at line 119 of file ie_device_common.c.
{
  (void)self;
  return ie_gemv_q4_0_f32(w_q4, w_scales, scale_bytes, x, y, rows, cols, bias_bf16);
}
References ie_gemv_q4_0_f32().
Referenced by ie_device_create().
cpu_memcpy()
static int cpu_memcpy (void * self, void * dst, const void * src, size_t nbytes) static
CPU memcpy implementation.
Definition at line 135 of file ie_device_common.c.
{
  (void)self;
  if (!dst || !src) return -1;
  memcpy(dst, src, nbytes);
  return 0;
}
Referenced by ie_device_create().
cpu_new()
static cpu_impl_t * cpu_new (void) static
Allocate a CPU backend instance.
Returns
Pointer to newly allocated cpu_impl_t or NULL on OOM.
Definition at line 78 of file ie_device_common.c.
{
  cpu_impl_t *p = (cpu_impl_t*)calloc(1, sizeof(*p));
  if (!p) return NULL;
  snprintf(p->name, sizeof(p->name), "CPU");
  return p;
}
References cpu_impl::name.
Referenced by ie_device_create().
cuda_caps_thunk()
static int cuda_caps_thunk (const void * self, ie_device_caps_t * out) static
Report CUDA device capabilities.
Definition at line 225 of file ie_device_common.c.
{
  const cuda_impl_t *ci = (const cuda_impl_t*)self;
  if (!out || !ci) return -1;
  memset(out, 0, sizeof(*out));
  out->has_gemv_f32 = 1;
  out->has_mem_copy = 1;
  out->has_streams  = 0;
  snprintf(out->name,   sizeof(out->name),   "%s", ci->name);
  snprintf(out->driver, sizeof(out->driver), "%s", ci->driver);
  return 0;
}
References cuda_impl::driver, and cuda_impl::name.
Referenced by cuda_try_create().
cuda_destroy_thunk()
static void cuda_destroy_thunk (void * self) static
Destroy CUDA backend instance and free device buffers.
Definition at line 386 of file ie_device_common.c.
{
  cuda_impl_t *ci = (cuda_impl_t*)self;
  if (!ci) return;
  if (ci->dW)    ie_cuda_free(ci->dW);
  if (ci->dW_scales) ie_cuda_free(ci->dW_scales);
  if (ci->dx)    ie_cuda_free(ci->dx);
  if (ci->dy)    ie_cuda_free(ci->dy);
  if (ci->dbias) ie_cuda_free(ci->dbias);
  free(ci);
}
References cuda_impl::dbias, cuda_impl::dW, cuda_impl::dW_scales, cuda_impl::dx, cuda_impl::dy, and ie_cuda_free().
Referenced by cuda_try_create().
cuda_ensure_capacity()
static int cuda_ensure_capacity (void ** pbuf, size_t * pcap, size_t nbytes) static
Ensure a device buffer has at least nbytes capacity.
Parameters
pbuf Pointer to device buffer pointer.
pcap Pointer to capacity value.
nbytes Required bytes.
Returns
0 on success, negative on failure.
Definition at line 204 of file ie_device_common.c.
{
  if (!pbuf || !pcap) return -1;
  if (*pbuf && *pcap >= nbytes) return 0;
  if (*pbuf) {
    ie_cuda_free(*pbuf);
    *pbuf = NULL;
    *pcap = 0;
  }
  void *p = ie_cuda_malloc(nbytes);
  if (!p) return -2;
  *pbuf = p;
  *pcap = nbytes;
  return 0;
}
References ie_cuda_free(), and ie_cuda_malloc().
Referenced by cuda_gemv_f32_thunk(), and cuda_gemv_q4_0_f32_thunk().
cuda_gemv_block_sparse_f32_unimpl()
static int cuda_gemv_block_sparse_f32_unimpl (void * self, const ie_block_sparse_matrix_t * m, const float * x, float * y, const float * bias) static
CUDA block-sparse GEMV implementation.
Not implemented yet. We return an error to avoid silently producing CPU results under a CUDA label.
Definition at line 370 of file ie_device_common.c.
{
  (void)self;
  (void)m;
  (void)x;
  (void)y;
  (void)bias;
  return -2;
}
Referenced by cuda_try_create().
cuda_gemv_f32_thunk()
static int cuda_gemv_f32_thunk (void * self, const float * W, const float * x, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k) static
CUDA GEMV FP32 implementation.
This copies W/x/bias to device buffers, launches a CUDA kernel, then copies y back.
Definition at line 261 of file ie_device_common.c.
{
  (void)blk_k;
  cuda_impl_t *ci = (cuda_impl_t*)self;
  if (!ci || !W || !x || !y || rows == 0 || cols == 0) return -1;
  const size_t W_bytes = rows * cols * sizeof(float);
  const size_t x_bytes = cols * sizeof(float);
  const size_t y_bytes = rows * sizeof(float);
  const size_t b_bytes = bias ? (rows * sizeof(float)) : 0;
  if (cuda_ensure_capacity(&ci->dW, &ci->dW_cap, W_bytes) != 0) return -2;
  if (cuda_ensure_capacity(&ci->dx, &ci->dx_cap, x_bytes) != 0) return -3;
  if (cuda_ensure_capacity(&ci->dy, &ci->dy_cap, y_bytes) != 0) return -4;
  if (bias) {
    if (cuda_ensure_capacity(&ci->dbias, &ci->dbias_cap, b_bytes) != 0) return -5;
  }
  if (ie_cuda_memcpy(ci->dW, W, W_bytes, IE_CUDA_COPY_H2D) != 0) return -6;
  if (ie_cuda_memcpy(ci->dx, x, x_bytes, IE_CUDA_COPY_H2D) != 0) return -7;
  if (bias) {
    if (ie_cuda_memcpy(ci->dbias, bias, b_bytes, IE_CUDA_COPY_H2D) != 0) return -8;
  }
  if (ie_cuda_gemv_f32((const float*)ci->dW,
                      (const float*)ci->dx,
                      (float*)ci->dy,
                      rows,
                      cols,
                      bias ? (const float*)ci->dbias : NULL) != 0) {
    return -9;
  }
  if (ie_cuda_memcpy(y, ci->dy, y_bytes, IE_CUDA_COPY_D2H) != 0) return -10;
  return 0;
}
References cuda_ensure_capacity(), cuda_impl::dbias, cuda_impl::dbias_cap, cuda_impl::dW, cuda_impl::dW_cap, cuda_impl::dx, cuda_impl::dx_cap, cuda_impl::dy, cuda_impl::dy_cap, IE_CUDA_COPY_D2H, IE_CUDA_COPY_H2D, ie_cuda_gemv_f32(), and ie_cuda_memcpy().
Referenced by cuda_try_create().
cuda_gemv_q4_0_f32_thunk()
static int cuda_gemv_q4_0_f32_thunk (void * self, const uint8_t * w_q4, const uint8_t * w_scales, size_t scale_bytes, const float * x, float * y, size_t rows, size_t cols, const uint16_t * bias_bf16) static
CUDA GEMV Q4_0 implementation.
This copies packed weights/scales/x/bias to device buffers, launches a CUDA kernel, then copies y back.
Definition at line 311 of file ie_device_common.c.
{
  cuda_impl_t *ci = (cuda_impl_t*)self;
  if (!ci || !w_q4 || !w_scales || !x || !y || rows == 0 || cols == 0) return -1;
  if (scale_bytes != 1u && scale_bytes != 2u) return -2;
  const size_t blocks_per_row = (cols + 31u) / 32u;
  const size_t row_w_bytes = blocks_per_row * 16u;
  const size_t row_s_bytes = blocks_per_row * (size_t)scale_bytes;
  const size_t W_bytes = rows * row_w_bytes;
  const size_t S_bytes = rows * row_s_bytes;
  const size_t x_bytes = cols * sizeof(float);
  const size_t y_bytes = rows * sizeof(float);
  const size_t b_bytes = bias_bf16 ? (rows * sizeof(uint16_t)) : 0;
  if (cuda_ensure_capacity(&ci->dW, &ci->dW_cap, W_bytes) != 0) return -3;
  if (cuda_ensure_capacity(&ci->dW_scales, &ci->dW_scales_cap, S_bytes) != 0) return -4;
  if (cuda_ensure_capacity(&ci->dx, &ci->dx_cap, x_bytes) != 0) return -5;
  if (cuda_ensure_capacity(&ci->dy, &ci->dy_cap, y_bytes) != 0) return -6;
  if (bias_bf16) {
    if (cuda_ensure_capacity(&ci->dbias, &ci->dbias_cap, b_bytes) != 0) return -7;
  }
  if (ie_cuda_memcpy(ci->dW, w_q4, W_bytes, IE_CUDA_COPY_H2D) != 0) return -8;
  if (ie_cuda_memcpy(ci->dW_scales, w_scales, S_bytes, IE_CUDA_COPY_H2D) != 0) return -9;
  if (ie_cuda_memcpy(ci->dx, x, x_bytes, IE_CUDA_COPY_H2D) != 0) return -10;
  if (bias_bf16) {
    if (ie_cuda_memcpy(ci->dbias, bias_bf16, b_bytes, IE_CUDA_COPY_H2D) != 0) return -11;
  }
  if (ie_cuda_gemv_q4_0_f32((const uint8_t*)ci->dW,
                            (const uint8_t*)ci->dW_scales,
                            scale_bytes,
                            (const float*)ci->dx,
                            (float*)ci->dy,
                            rows,
                            cols,
                            bias_bf16 ? (const uint16_t*)ci->dbias : NULL) != 0) {
    return -12;
  }
  if (ie_cuda_memcpy(y, ci->dy, y_bytes, IE_CUDA_COPY_D2H) != 0) return -13;
  return 0;
}
References cuda_ensure_capacity(), cuda_impl::dbias, cuda_impl::dbias_cap, cuda_impl::dW, cuda_impl::dW_cap, cuda_impl::dW_scales, cuda_impl::dW_scales_cap, cuda_impl::dx, cuda_impl::dx_cap, cuda_impl::dy, cuda_impl::dy_cap, IE_CUDA_COPY_D2H, IE_CUDA_COPY_H2D, ie_cuda_gemv_q4_0_f32(), and ie_cuda_memcpy().
Referenced by cuda_try_create().
cuda_memcpy_thunk()
static int cuda_memcpy_thunk (void * self, void * dst, const void * src, size_t nbytes) static
CUDA memcpy implementation using the CUDA wrapper.
This uses IE_CUDA_COPY_DEFAULT to allow the runtime to decide direction under unified virtual addressing.
Definition at line 245 of file ie_device_common.c.
{
  (void)self;
  if (!dst || !src) return -1;
  if (nbytes == 0) return 0;
  if (ie_cuda_memcpy(dst, src, nbytes, IE_CUDA_COPY_DEFAULT) != 0) {
    return -2;
  }
  return 0;
}
References IE_CUDA_COPY_DEFAULT, and ie_cuda_memcpy().
Referenced by cuda_try_create().
cuda_try_create()
static int cuda_try_create (void ** out_impl, ie_device_vtbl_t * out_vt) static
Initialize CUDA backend.
This calls ie_cuda_init(), which forces CUDA runtime initialization (driver activity).
Parameters
out_impl Output impl pointer.
out_vt Output vtable.
Returns
0 on success, negative on failure.
Definition at line 408 of file ie_device_common.c.
{
  if (!out_impl || !out_vt) return -1;
  if (!ie_cuda_is_available()) {
    return -2;
  }
  cuda_impl_t *ci = (cuda_impl_t*)calloc(1, sizeof(*ci));
  if (!ci) return -3;
  ci->device_ordinal = 0;
  if (ie_cuda_init(ci->device_ordinal,
                   ci->name, sizeof(ci->name),
                   ci->driver, sizeof(ci->driver)) != 0) {
    free(ci);
    return -4;
  }
  out_vt->caps                   = cuda_caps_thunk;
  out_vt->gemv_f32               = cuda_gemv_f32_thunk;
  out_vt->gemv_q4_0_f32           = cuda_gemv_q4_0_f32_thunk;
  out_vt->memcpy                 = cuda_memcpy_thunk;
  out_vt->gemv_block_sparse_f32  = cuda_gemv_block_sparse_f32_unimpl;
  out_vt->destroy                = cuda_destroy_thunk;
  *out_impl = ci;
  return 0;
}
References ie_device_vtbl::caps, cuda_caps_thunk(), cuda_destroy_thunk(), cuda_gemv_block_sparse_f32_unimpl(), cuda_gemv_f32_thunk(), cuda_gemv_q4_0_f32_thunk(), cuda_memcpy_thunk(), ie_device_vtbl::destroy, cuda_impl::device_ordinal, cuda_impl::driver, ie_device_vtbl::gemv_block_sparse_f32, ie_device_vtbl::gemv_f32, ie_device_vtbl::gemv_q4_0_f32, ie_cuda_init(), ie_cuda_is_available(), ie_device_vtbl::memcpy, and cuda_impl::name.
Referenced by ie_device_create().
ie_device_caps()
int ie_device_caps (const ie_device_t * dev, ie_device_caps_t * out_caps)
Query device capabilities.
Parameters
dev Device handle.
out_caps Output capabilities structure (non-NULL).
Returns
0 on success; non-zero on error.
Definition at line 615 of file ie_device_common.c.
{
  if (!dev || !out_caps) return -1;
  return dev->vt.caps ? dev->vt.caps(dev->impl, out_caps) : -2;
}
References ie_device_vtbl::caps, ie_device::impl, and ie_device::vt.
ie_device_create()
int ie_device_create (ie_device_kind_t kind, ie_device_t ** out_dev)
Create a device backend.
Create a device handle for the requested kind (with fallback).
If CUDA is requested and cannot be initialized, this returns an error to avoid producing CPU output labeled as CUDA.
Definition at line 554 of file ie_device_common.c.
{
  if (!out_dev) return -1;
  ie_device_t *d = (ie_device_t*)calloc(1, sizeof(*d));
  if (!d) return -2;
  if (kind == IE_DEV_CPU) {
    cpu_impl_t *ci = cpu_new();
    if (!ci) {
      free(d);
      return -3;
    }
    d->impl                     = ci;
    d->vt.caps                  = cpu_caps;
    d->vt.gemv_f32              = cpu_gemv_f32;
    d->vt.gemv_q4_0_f32          = cpu_gemv_q4_0_f32;
    d->vt.memcpy                = cpu_memcpy;
    d->vt.gemv_block_sparse_f32 = cpu_gemv_block_sparse_f32;
    d->vt.destroy               = cpu_destroy;
    d->kind                     = IE_DEV_CPU;
    *out_dev = d;
    return 0;
  }
  if (kind == IE_DEV_CUDA) {
    if (cuda_try_create(&d->impl, &d->vt) != 0) {
      free(d);
      return -4;
    }
    d->kind = IE_DEV_CUDA;
    *out_dev = d;
    return 0;
  }
  if (kind == IE_DEV_ZE) {
    if (ze_try_create(&d->impl, &d->vt) != 0) {
      free(d);
      return -5;
    }
    d->kind = IE_DEV_ZE;
    *out_dev = d;
    return 0;
  }
  free(d);
  return -6;
}
References ie_device_vtbl::caps, cpu_caps(), cpu_destroy(), cpu_gemv_block_sparse_f32(), cpu_gemv_f32(), cpu_gemv_q4_0_f32(), cpu_memcpy(), cpu_new(), cuda_try_create(), ie_device_vtbl::destroy, ie_device_vtbl::gemv_block_sparse_f32, ie_device_vtbl::gemv_f32, ie_device_vtbl::gemv_q4_0_f32, IE_DEV_CPU, IE_DEV_CUDA, IE_DEV_ZE, ie_device::impl, ie_device::kind, ie_device_vtbl::memcpy, ie_device::vt, and ze_try_create().
Referenced by ie_engine_create(), test_cpu_caps(), and test_gpu_fallback().
ie_device_destroy()
void ie_device_destroy (ie_device_t * dev)
Destroy a device instance.
Destroy a device handle and release resources.
Definition at line 606 of file ie_device_common.c.
{
  if (!dev) return;
  if (dev->vt.destroy) dev->vt.destroy(dev->impl);
  free(dev);
}
References ie_device_vtbl::destroy, ie_device::impl, and ie_device::vt.
Referenced by ie_engine_create(), ie_engine_destroy(), test_cpu_caps(), and test_gpu_fallback().
ie_device_gemv_block_sparse_f32()
int ie_device_gemv_block_sparse_f32 (ie_device_t * dev, const ie_block_sparse_matrix_t * m, const float * x, float * y, const float * bias)
Execute block-sparse GEMV FP32 through backend.
Block-sparse GEMV (FP32): y = W * x (+ optional bias).
Definition at line 651 of file ie_device_common.c.
{
  if (!dev || !dev->vt.gemv_block_sparse_f32) return -1;
  return dev->vt.gemv_block_sparse_f32(dev->impl, m, x, y, bias);
}
References ie_device_vtbl::gemv_block_sparse_f32, ie_device::impl, and ie_device::vt.
ie_device_gemv_f32()
int ie_device_gemv_f32 (ie_device_t * dev, const float * W, const float * x, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k)
Execute dense GEMV FP32 through backend.
Device-side GEMV (FP32): y = W * x (+ optional bias).
Definition at line 623 of file ie_device_common.c.
{
  if (!dev || !dev->vt.gemv_f32) return -1;
  return dev->vt.gemv_f32(dev->impl, W, x, y, rows, cols, bias, blk_k);
}
References ie_device_vtbl::gemv_f32, ie_device::impl, and ie_device::vt.
Referenced by test_gpu_fallback().
ie_device_gemv_q4_0_f32()
int ie_device_gemv_q4_0_f32 (ie_device_t * dev, const uint8_t * w_q4, const uint8_t * w_scales, size_t scale_bytes, const float * x, float * y, size_t rows, size_t cols, const uint16_t * bias_bf16)
Execute GEMV Q4_0 through backend.
Device-side GEMV (Q4_0 weights, FP32 activations).
Definition at line 634 of file ie_device_common.c.
{
  if (!dev || !dev->vt.gemv_q4_0_f32) return -1;
  return dev->vt.gemv_q4_0_f32(dev->impl, w_q4, w_scales, scale_bytes,
                              x, y, rows, cols, bias_bf16);
}
References ie_device_vtbl::gemv_q4_0_f32, ie_device::impl, and ie_device::vt.
ie_device_kind()
ie_device_kind_t ie_device_kind (const ie_device_t * dev)
Return the device kind.
Return the logical kind of a device handle.
Definition at line 671 of file ie_device_common.c.
{
  if (!dev) return IE_DEV_CPU;
  return dev->kind;
}
References IE_DEV_CPU, and ie_device::kind.
ie_device_kind_from_str()
ie_device_kind_t ie_device_kind_from_str (const char * s)
Parse a device kind from string.
Parse a device kind from a string.
Definition at line 679 of file ie_device_common.c.
{
  if (!s) return IE_DEV_CPU;
  char tmp[16] = {0};
  size_t n = strlen(s);
  if (n >= sizeof(tmp)) n = sizeof(tmp) - 1;
  for (size_t i = 0; i < n; ++i) {
    tmp[i] = (char)tolower((unsigned char)s[i]);
  }
  if (!strcmp(tmp, "cpu"))  return IE_DEV_CPU;
  if (!strcmp(tmp, "cuda")) return IE_DEV_CUDA;
  if (!strcmp(tmp, "ze"))   return IE_DEV_ZE;
  return IE_DEV_CPU;
}
References IE_DEV_CPU, IE_DEV_CUDA, and IE_DEV_ZE.
Referenced by ie_engine_create(), and test_kind_parse().
ie_device_memcpy()
int ie_device_memcpy (ie_device_t * dev, void * dst, const void * src, size_t nbytes)
Execute memcpy through backend.
Copy memory using the device backend.
Definition at line 663 of file ie_device_common.c.
{
  if (!dev || !dev->vt.memcpy) return -1;
  return dev->vt.memcpy(dev->impl, dst, src, nbytes);
}
References ie_device::impl, ie_device_vtbl::memcpy, and ie_device::vt.
ze_caps_thunk()
static int ze_caps_thunk (const void * self, ie_device_caps_t * out) static
Level Zero caps thunk used in the vtable.
Definition at line 450 of file ie_device_common.c.
{
  const ze_impl_t *zi = (const ze_impl_t*)self;
  if (!out || !zi) return -1;
  memset(out, 0, sizeof(*out));
  snprintf(out->name,   sizeof(out->name),   "%s", zi->name);
  snprintf(out->driver, sizeof(out->driver), "%s", zi->driver);
  out->has_gemv_f32 = 0;
  out->has_mem_copy = 0;
  out->has_streams  = 0;
  return 0;
}
References ze_impl::driver, and ze_impl::name.
Referenced by ze_try_create().
ze_destroy_thunk()
static void ze_destroy_thunk (void * self) static
Destroy Level Zero backend instance.
Definition at line 517 of file ie_device_common.c.
{
  free(self);
}
Referenced by ze_try_create().
ze_gemv_block_sparse_f32_stub()
static int ze_gemv_block_sparse_f32_stub (void * self, const ie_block_sparse_matrix_t * m, const float * x, float * y, const float * bias) static
Level Zero block-sparse GEMV FP32 stub (unimplemented).
Definition at line 505 of file ie_device_common.c.
{
  (void)self; (void)m; (void)x; (void)y; (void)bias;
  return -2;
}
Referenced by ze_try_create().
ze_gemv_f32_stub()
static int ze_gemv_f32_stub (void * self, const float * W, const float * x, float * y, size_t rows, size_t cols, const float * bias, size_t blk_k) static
Level Zero GEMV FP32 stub (unimplemented).
Definition at line 465 of file ie_device_common.c.
{
  (void)self; (void)W; (void)x; (void)y; (void)rows; (void)cols; (void)bias; (void)blk_k;
  return -2;
}
Referenced by ze_try_create().
ze_gemv_q4_0_f32_stub()
static int ze_gemv_q4_0_f32_stub (void * self, const uint8_t * w_q4, const uint8_t * w_scales, size_t scale_bytes, const float * x, float * y, size_t rows, size_t cols, const uint16_t * bias_bf16) static
Level Zero GEMV Q4_0 stub (unimplemented).
Definition at line 480 of file ie_device_common.c.
{
  (void)self; (void)w_q4; (void)w_scales; (void)scale_bytes;
  (void)x; (void)y; (void)rows; (void)cols; (void)bias_bf16;
  return -2;
}
Referenced by ze_try_create().
ze_memcpy_stub()
static int ze_memcpy_stub (void * self, void * dst, const void * src, size_t nbytes) static
Level Zero memcpy stub (unimplemented).
Definition at line 497 of file ie_device_common.c.
{
  (void)self; (void)dst; (void)src; (void)nbytes;
  return -2;
}
Referenced by ze_try_create().
ze_try_create()
static int ze_try_create (void ** out_impl, ie_device_vtbl_t * out_vt) static
Try to initialize Level Zero backend (stub).
Definition at line 524 of file ie_device_common.c.
{
  if (!out_impl || !out_vt) return -1;
  ze_impl_t *zi = (ze_impl_t*)calloc(1, sizeof(*zi));
  if (!zi) return -2;
  snprintf(zi->name, sizeof(zi->name), "LevelZero");
  snprintf(zi->driver, sizeof(zi->driver), "stub");
  out_vt->caps                  = ze_caps_thunk;
  out_vt->gemv_f32              = ze_gemv_f32_stub;
  out_vt->gemv_q4_0_f32          = ze_gemv_q4_0_f32_stub;
  out_vt->memcpy                = ze_memcpy_stub;
  out_vt->gemv_block_sparse_f32 = ze_gemv_block_sparse_f32_stub;
  out_vt->destroy               = ze_destroy_thunk;
  *out_impl = zi;
  return 0;
}
References ie_device_vtbl::caps, ie_device_vtbl::destroy, ze_impl::driver, ie_device_vtbl::gemv_block_sparse_f32, ie_device_vtbl::gemv_f32, ie_device_vtbl::gemv_q4_0_f32, ie_device_vtbl::memcpy, ze_impl::name, ze_caps_thunk(), ze_destroy_thunk(), ze_gemv_block_sparse_f32_stub(), ze_gemv_f32_stub(), ze_gemv_q4_0_f32_stub(), and ze_memcpy_stub().
Referenced by ie_device_create().