Inference Engine (Clocher): engine/include/ie_rope.h File Reference
ie_rope.h File Reference
Rotary Position Embedding (RoPE) interfaces.
#include <stddef.h>
#include <stdint.h>
Functions
int ie_rope_apply_one_f32 (float *x, size_t head_dim, uint32_t pos, float theta)
Apply RoPE to a single head vector in-place.
int ie_rope_apply_f32 (float *q, float *k, size_t heads, size_t head_dim, uint32_t pos, float theta)
Apply RoPE to Q and/or K for multiple heads.
Detailed Description
Rotary Position Embedding (RoPE) interfaces.
RoPE rotates interleaved pairs (2*i, 2*i+1) in each head.
This header matches the runtime usage where calls may pass only q or only k (the other pointer may be NULL), and the function returns an int status code.
RoPE scaling:
Scaling is implemented inside the RoPE helper (see engine/src/math/rope.c).
Environment variables supported by the implementation:
IE_ROPE_LINEAR_SCALE: positive float factor f, effective pos = pos / f
IE_ROPE_POS_SCALE: positive float multiplier m, effective pos = pos * m
Definition in file ie_rope.h.
Function Documentation
ie_rope_apply_f32()
int ie_rope_apply_f32 (float * q, float * k, size_t heads, size_t head_dim, uint32_t pos, float theta)
Apply RoPE to Q and/or K for multiple heads.
Either q or k may be NULL. If both are NULL, this is a no-op returning 0.
Buffers are expected in row-major layout: q layout: [heads, head_dim] k layout: [heads, head_dim]
Parameters
q Q buffer, layout [heads, head_dim], may be NULL.
k K buffer, layout [heads, head_dim], may be NULL.
heads Number of heads in q/k (must be > 0 if q or k is non-NULL).
head_dim Per-head dimension (must be even and >= 2).
pos Position index.
theta RoPE base theta (must be > 0).
Returns
0 on success, negative on error.
Apply RoPE to Q and/or K for multiple heads.
This function applies RoPE on the first head_dim elements, interpreted as interleaved pairs (even, odd): (x0, x1) -> (x0*cos - x1*sin, x0*sin + x1*cos)
The caller passes Q and K shaped as [heads, head_dim] flattened.
Parameters
q Q buffer, [heads * head_dim].
k K buffer, [heads * head_dim].
heads Number of heads in q/k.
head_dim Head dimension (must be even for paired rotation).
pos Sequence position (0-based).
theta RoPE base (commonly 10000.0f).
Returns
0 on success, negative on invalid args.
Definition at line 171 of file rope.c.
{
  if (!q && !k) return 0;
  if (heads == 0u) return -1;
  if ((head_dim & 1u) != 0u) return -2;
  if (head_dim < 2u) return -3;
  if (!(theta > 0.0f)) return -4;
  for (size_t h = 0; h < heads; ++h) {
    if (q) {
      const int rc = ie_rope_apply_one_f32(q + h * head_dim, head_dim, pos, theta);
      if (rc != 0) return rc;
    }
    if (k) {
      const int rc = ie_rope_apply_one_f32(k + h * head_dim, head_dim, pos, theta);
      if (rc != 0) return rc;
    }
  }
  return 0;
}
Referenced by ie_forward_one_token().
ie_rope_apply_one_f32()
int ie_rope_apply_one_f32 (float * x, size_t head_dim, uint32_t pos, float theta)
Apply RoPE to a single head vector in-place.
The head vector is treated as interleaved pairs: (x[0], x[1]), (x[2], x[3]), ...
Parameters
x Pointer to head vector (length head_dim).
head_dim Per-head dimension (must be even and >= 2).
pos Position index.
theta RoPE base theta (must be > 0).
Returns
0 on success, negative on error.
Definition at line 141 of file rope.c.
{
  if (!x) return -1;
  if (head_dim < 2u) return -2;
  if ((head_dim & 1u) != 0u) return -3;
  if (!(theta > 0.0f)) return -4;
  const size_t pairs = head_dim / 2u;
  /* Apply optional position scaling inside the helper. */
  const float p = (float)pos * ie_rope_pos_mul();
  for (size_t i = 0; i < pairs; ++i) {
    const size_t j = 2u * i;
    const float invf = ie_rope_inv_freq(theta, i, head_dim);
    const float ang = p * invf;
    const float c = cosf(ang);
    const float s = sinf(ang);
    const float x0 = x[j + 0u];
    const float x1 = x[j + 1u];
    x[j + 0u] = x0 * c - x1 * s;
    x[j + 1u] = x0 * s + x1 * c;
  }
  return 0;
}
References ie_rope_inv_freq(), and ie_rope_pos_mul().
Referenced by ie_rope_apply_f32().