Inference Engine (Clocher): engine/include/ie_kv_cache.h File Reference
ie_kv_cache.h File Reference
Key/Value attention cache with INT8/FP8 compression and FP32 round-trip.
#include <stddef.h>
#include <stdint.h>
#include "ie_quant_act.h"
Data Structures
struct ie_kv_opts
Options to initialize a KV cache.
struct ie_kv_cache
A KV cache storing K/V for one transformer layer.
Typedefs
typedef enum ie_kv_storage_type ie_kv_storage_type
KV cache storage encoding.
typedef struct ie_kv_opts ie_kv_opts
Options to initialize a KV cache.
typedef struct ie_kv_cache ie_kv_cache
A KV cache storing K/V for one transformer layer.
Enumerations
enum ie_kv_storage_type { IE_KV_STORAGE_F32 = 0 , IE_KV_STORAGE_INT8 = 1 , IE_KV_STORAGE_FP8 = 2 }
KV cache storage encoding.
Functions
size_t ie_kv_element_size (ie_kv_storage_type storage)
Return element size in bytes for a given storage encoding.
int ie_kv_init (ie_kv_cache *kv, const ie_kv_opts *opts)
Initialize a single KV cache, allocating its backing memory.
int ie_kv_init_layers (ie_kv_cache *kv_layers, int n_layers, const ie_kv_opts *opts)
Initialize an array of KV caches (one per layer) using one shared slab.
void ie_kv_free (ie_kv_cache *kv)
Free a KV cache and release its backing memory if owned.
void ie_kv_free_layers (ie_kv_cache *kv_layers, int n_layers)
Convenience to free an array of KV caches created by ie_kv_init_layers().
int ie_kv_store_token_f32 (ie_kv_cache *kv, size_t t, const float *K_f32, const float *V_f32)
Store a token's K/V slice into an FP32 cache.
int ie_kv_store_token_int8_per_tensor (ie_kv_cache *kv, size_t t, const float *K_f32, const float *V_f32)
Store a token's K/V slice into an INT8 cache using per-tensor params.
int ie_kv_store_token_int8_per_group (ie_kv_cache *kv, size_t t, const float *K_f32, const float *V_f32)
Store a token's K/V slice into an INT8 cache using per-group params.
int ie_kv_store_token_fp8 (ie_kv_cache *kv, size_t t, const float *K_f32, const float *V_f32)
Store a token's K/V slice into an FP8 cache.
int ie_kv_load_token_f32 (const ie_kv_cache *kv, size_t t, float *K_out, float *V_out)
Load token t as FP32 K/V slices from any storage encoding.
int ie_kv_raw_ptrs (ie_kv_cache *kv, void **out_K, void **out_V, size_t *out_lds)
Get raw payload pointers and leading dimension for [t][h][d] layout.
int ie_kv_raw_strides (const ie_kv_cache *kv, size_t *stride_t, size_t *stride_h, size_t *stride_d)
Get logical strides (in elements) for the [t][h][d] layout.
Detailed Description
Key/Value attention cache with INT8/FP8 compression and FP32 round-trip.
This module provides a compact KV cache for transformer attention. The cache stores per-token K/V slices laid out as [heads, head_dim] per token, flattened with head_dim as the fastest-varying dimension:
index(t,h,d) = ((t * H + h) * D + d)
where:
H = heads
D = head_dim
t in [0, max_seq)
Storage types:
IE_KV_STORAGE_F32: raw FP32 K/V payloads.
IE_KV_STORAGE_INT8: INT8 payloads with per-group affine parameters (scale, zero_point) for each (token, head).
IE_KV_STORAGE_FP8: FP8 payloads (E4M3/E5M2), no per-group parameters.
Per-group parameters (INT8): param_index(t,h,g) = ((t * H + h) * G + g) where:
group_size is provided by opts (defaults to 1 for INT8 if not provided)
G = ceil(D / group_size)
Layered KV specification: GPT-OSS inference uses an array of caches (one per layer). To maximize TPS, this module provides ie_kv_init_layers() which allocates one contiguous slab for all layers and slices it into per-layer ie_kv_cache views.
Performance notes:
The implementation avoids per-token heap allocations by keeping small scratch buffers inside the cache for INT8-per-group and FP8 paths.
The [t][h][d] layout makes each token slice contiguous (H*D), enabling memcpy for FP32 store/load and predictable streaming access for attention.
Definition in file ie_kv_cache.h.
Typedef Documentation
ie_kv_cache
typedef struct ie_kv_cache ie_kv_cache
A KV cache storing K/V for one transformer layer.
The cache owns one backing allocation (a single slab) when created via ie_kv_init() or as the owner slice of ie_kv_init_layers(). Non-owner slices created by ie_kv_init_layers() point inside the owner's backing slab and must not free it.
ie_kv_opts
typedef struct ie_kv_opts ie_kv_opts
Options to initialize a KV cache.
ie_kv_storage_type
typedef enum ie_kv_storage_type ie_kv_storage_type
KV cache storage encoding.
Enumeration Type Documentation
ie_kv_storage_type
enum ie_kv_storage_type
KV cache storage encoding.
Enumerator
IE_KV_STORAGE_F32
Raw FP32 payloads.
IE_KV_STORAGE_INT8
INT8 payloads + affine params (per-group).
IE_KV_STORAGE_FP8
FP8 payloads (E4M3/E5M2) stored as uint8_t codes.
Definition at line 64 of file ie_kv_cache.h.
{
  IE_KV_STORAGE_F32  = 0,
  IE_KV_STORAGE_INT8 = 1,
  IE_KV_STORAGE_FP8  = 2
} ie_kv_storage_type;
Function Documentation
ie_kv_element_size()
size_t ie_kv_element_size (ie_kv_storage_type storage)
Return element size in bytes for a given storage encoding.
Parameters
storage KV storage encoding.
Returns
Element size (bytes), or 0 for unknown storage.
Return element size in bytes for a given storage encoding.
Parameters
storage Storage type.
Returns
Element size in bytes; 0 for unknown.
Definition at line 361 of file kv_cache.c.
{
  switch (storage) {
    case IE_KV_STORAGE_F32:  return sizeof(float);
    case IE_KV_STORAGE_INT8: return sizeof(int8_t);
    case IE_KV_STORAGE_FP8:  return sizeof(uint8_t);
    default: return 0;
  }
}
References IE_KV_STORAGE_F32, IE_KV_STORAGE_FP8, and IE_KV_STORAGE_INT8.
Referenced by kv_assign_from_slab(), and kv_compute_slab_bytes().
ie_kv_free()
void ie_kv_free (ie_kv_cache * kv)
Free a KV cache and release its backing memory if owned.
Parameters
kv Cache to free.
Free a KV cache and release its backing memory if owned.
Only the cache marked as owner frees the shared slab. After freeing, the structure is zeroed to prevent accidental reuse.
Parameters
kv Cache instance.
Definition at line 464 of file kv_cache.c.
{
  if (!kv) return;
  if (kv->backing_owner && kv->backing) {
    free(kv->backing);
  }
  memset(kv, 0, sizeof(*kv));
}
References ie_kv_cache::backing, and ie_kv_cache::backing_owner.
Referenced by ie_kv_free_layers().
ie_kv_free_layers()
void ie_kv_free_layers (ie_kv_cache * kv_layers, int n_layers)
Convenience to free an array of KV caches created by ie_kv_init_layers().
Parameters
kv_layers Array of KV caches.
n_layers Number of layers.
Convenience to free an array of KV caches created by ie_kv_init_layers().
Freeing the owner (layer 0) is sufficient; other layers are cleared.
Parameters
kv_layers Array of layer caches.
n_layers Number of layers.
Definition at line 483 of file kv_cache.c.
{
  if (!kv_layers || n_layers <= 0) return;
  ie_kv_free(&kv_layers[0]);
  for (int i = 1; i < n_layers; ++i) {
    memset(&kv_layers[i], 0, sizeof(kv_layers[i]));
  }
}
References ie_kv_free().
Referenced by ie_engine_generate_ex(), and ie_generate_gptoss().
ie_kv_init()
int ie_kv_init (ie_kv_cache * kv, const ie_kv_opts * opts)
Initialize a single KV cache, allocating its backing memory.
Parameters
kv Cache object to initialize.
opts Initialization options.
Returns
0 on success; non-zero on error.
Initialize a single KV cache, allocating its backing memory.
Parameters
kv Cache to initialize.
opts Options describing cache geometry and storage format.
Returns
0 on success; non-zero on failure.
Definition at line 377 of file kv_cache.c.
{
  if (!kv) return -1;
  if (kv_validate_and_derive(kv, opts) != 0) return -1;
  size_t slab_bytes = 0;
  if (kv_compute_slab_bytes(kv, &slab_bytes) != 0) return -2;
  uint8_t *slab = (uint8_t *)calloc(1, slab_bytes);
  if (!slab) return -3;
  if (kv_assign_from_slab(kv, slab, slab_bytes) != 0) {
    free(slab);
    return -4;
  }
  kv->backing = slab;
  kv->backing_bytes = slab_bytes;
  kv->backing_owner = 1;
  return 0;
}
References ie_kv_cache::backing, ie_kv_cache::backing_bytes, ie_kv_cache::backing_owner, kv_assign_from_slab(), kv_compute_slab_bytes(), and kv_validate_and_derive().
ie_kv_init_layers()
int ie_kv_init_layers (ie_kv_cache * kv_layers, int n_layers, const ie_kv_opts * opts)
Initialize an array of KV caches (one per layer) using one shared slab.
This is the preferred initialization for transformer inference. It allocates one contiguous backing slab that contains K/V payloads and any parameter/scratch arrays for all layers, then slices it into n_layers independent cache views.
Ownership:
kv_layers[0] is marked as the backing owner and will free the slab.
kv_layers[i>0] are non-owners; calling ie_kv_free() on them is safe and will not free the slab.
Parameters
kv_layers Array of length n_layers.
n_layers Number of layers.
opts Initialization options (applies to every layer).
Returns
0 on success; non-zero on error.
Initialize an array of KV caches (one per layer) using one shared slab.
This allocates a single slab large enough for n_layers caches and then assigns each cache view to its slice. The first layer is marked as the owner of the slab and will free it when ie_kv_free_layers() is called.
Parameters
kv_layers Array of caches, length n_layers.
n_layers Number of layers (must be > 0).
opts Cache options applied to every layer.
Returns
0 on success; non-zero on failure.
Definition at line 411 of file kv_cache.c.
{
  if (!kv_layers || n_layers <= 0 || !opts) return -1;
  /* Derive one layer to compute per-layer slab bytes. */
  ie_kv_cache tmp;
  memset(&tmp, 0, sizeof(tmp));
  if (kv_validate_and_derive(&tmp, opts) != 0) return -2;
  size_t per_layer_bytes = 0;
  if (kv_compute_slab_bytes(&tmp, &per_layer_bytes) != 0) return -3;
  /* Make each slice start aligned. */
  per_layer_bytes = align_up_sz(per_layer_bytes, 64u);
  size_t total_bytes = 0;
  if (mul_overflow_sz((size_t)n_layers, per_layer_bytes, &total_bytes)) return -4;
  uint8_t *slab_all = (uint8_t *)calloc(1, total_bytes);
  if (!slab_all) return -5;
  for (int l = 0; l < n_layers; ++l) {
    ie_kv_cache *kv = &kv_layers[l];
    memset(kv, 0, sizeof(*kv));
    if (kv_validate_and_derive(kv, opts) != 0) {
      free(slab_all);
      for (int j = 0; j < l; ++j) memset(&kv_layers[j], 0, sizeof(kv_layers[j]));
      return -6;
    }
    uint8_t *slice = slab_all + (size_t)l * per_layer_bytes;
    if (kv_assign_from_slab(kv, slice, per_layer_bytes) != 0) {
      free(slab_all);
      for (int j = 0; j < l; ++j) memset(&kv_layers[j], 0, sizeof(kv_layers[j]));
      return -7;
    }
    kv->backing = slab_all;
    kv->backing_bytes = total_bytes;
    kv->backing_owner = (l == 0) ? 1 : 0;
  }
  return 0;
}
References align_up_sz(), ie_kv_cache::backing, ie_kv_cache::backing_bytes, ie_kv_cache::backing_owner, kv_assign_from_slab(), kv_compute_slab_bytes(), kv_validate_and_derive(), and mul_overflow_sz().
Referenced by ie_engine_generate_ex(), and ie_generate_gptoss().
ie_kv_load_token_f32()
int ie_kv_load_token_f32 (const ie_kv_cache * kv, size_t t, float * K_out, float * V_out)
Load token t as FP32 K/V slices from any storage encoding.
Parameters
kv Cache.
t Token index.
K_out Output K slice [H*D].
V_out Output V slice [H*D].
Returns
0 on success; non-zero on error.
Load token t as FP32 K/V slices from any storage encoding.
Performs dequantization for INT8/FP8 caches. On success, reports a KV hit. If t is out of range, reports a KV miss and returns an error.
Parameters
kv Cache (const).
t Token index.
K_out Output buffer for K (length heads*head_dim).
V_out Output buffer for V (length heads*head_dim).
Returns
0 on success; non-zero on failure.
Definition at line 694 of file kv_cache.c.
{
  if (!kv || !K_out || !V_out) return -1;
  if (t >= (size_t)kv->max_seq) {
    ie_kv_miss_add_local(1);
    return -2;
  }
  const size_t H = (size_t)kv->heads;
  const size_t D = (size_t)kv->head_dim;
  const size_t slice = H * D;
  if (kv->storage == IE_KV_STORAGE_F32) {
    const float *Ksrc = (const float *)kv->K;
    const float *Vsrc = (const float *)kv->V;
    memcpy(K_out, Ksrc + t * slice, slice * sizeof(float));
    memcpy(V_out, Vsrc + t * slice, slice * sizeof(float));
    ie_kv_hit_add_local(1);
    return 0;
  }
  if (kv->storage == IE_KV_STORAGE_INT8) {
    const int8_t *Kq = (const int8_t *)kv->K;
    const int8_t *Vq = (const int8_t *)kv->V;
    const size_t G   = kv->group_count;
    const size_t Gs  = kv->group_size;
    for (size_t h = 0; h < H; ++h) {
      const size_t off = (t * H + h) * D;
      for (size_t d = 0; d < D; ++d) {
        const size_t g  = d / Gs;
        const size_t pi = param_index(t, h, g, H, G);
        const float s   = kv->scales_K[pi];
        const int   z   = (int)kv->zeros_K[pi];
        K_out[h * D + d] = s * ((int)Kq[off + d] - z);
      }
      for (size_t d = 0; d < D; ++d) {
        const size_t g  = d / Gs;
        const size_t pi = param_index(t, h, g, H, G);
        const float s   = kv->scales_V[pi];
        const int   z   = (int)kv->zeros_V[pi];
        V_out[h * D + d] = s * ((int)Vq[off + d] - z);
      }
    }
    ie_kv_hit_add_local(1);
    return 0;
  }
  if (kv->storage == IE_KV_STORAGE_FP8) {
    const uint8_t *K8 = (const uint8_t *)kv->K;
    const uint8_t *V8 = (const uint8_t *)kv->V;
    for (size_t h = 0; h < H; ++h) {
      const size_t off = (t * H + h) * D;
      ie_dequantize_act_fp8(K8 + off, K_out + h * D, D, kv->fp8_format);
      ie_dequantize_act_fp8(V8 + off, V_out + h * D, D, kv->fp8_format);
    }
    ie_kv_hit_add_local(1);
    return 0;
  }
  ie_kv_miss_add_local(1);
  return -3;
}
References ie_kv_cache::fp8_format, ie_kv_cache::group_count, ie_kv_cache::group_size, ie_kv_cache::head_dim, ie_kv_cache::heads, ie_dequantize_act_fp8(), ie_kv_hit_add_local(), ie_kv_miss_add_local(), IE_KV_STORAGE_F32, IE_KV_STORAGE_FP8, IE_KV_STORAGE_INT8, ie_kv_cache::K, ie_kv_cache::max_seq, param_index(), ie_kv_cache::scales_K, ie_kv_cache::scales_V, ie_kv_cache::storage, ie_kv_cache::V, ie_kv_cache::zeros_K, and ie_kv_cache::zeros_V.
ie_kv_raw_ptrs()
int ie_kv_raw_ptrs (ie_kv_cache * kv, void ** out_K, void ** out_V, size_t * out_lds)
Get raw payload pointers and leading dimension for [t][h][d] layout.
Parameters
kv Cache.
out_K Output K payload pointer (may be NULL).
out_V Output V payload pointer (may be NULL).
out_lds Output leading dimension for the d axis (equals head_dim).
Returns
0 on success; non-zero on error.
Get raw payload pointers and leading dimension for [t][h][d] layout.
This is intended for debug/interop. The returned pointers reference internal cache storage and remain valid until the cache is freed.
Parameters
kv Cache.
out_K Output pointer for K base address (optional).
out_V Output pointer for V base address (optional).
out_lds Output leading dimension (head_dim) (optional).
Returns
0 on success; non-zero on failure.
Definition at line 777 of file kv_cache.c.
{
  if (!kv) return -1;
  if (out_K)   *out_K   = kv->K;
  if (out_V)   *out_V   = kv->V;
  if (out_lds) *out_lds = (size_t)kv->head_dim;
  return 0;
}
References ie_kv_cache::head_dim, ie_kv_cache::K, and ie_kv_cache::V.
ie_kv_raw_strides()
int ie_kv_raw_strides (const ie_kv_cache * kv, size_t * stride_t, size_t * stride_h, size_t * stride_d)
Get logical strides (in elements) for the [t][h][d] layout.
Strides are independent of storage encoding and describe the logical layout: stride_d = 1 stride_h = D stride_t = H*D
Parameters
kv Cache.
stride_t Output stride in elements for token dimension (may be NULL).
stride_h Output stride in elements for head dimension (may be NULL).
stride_d Output stride in elements for dim dimension (may be NULL).
Returns
0 on success; non-zero on error.
Get logical strides (in elements) for the [t][h][d] layout.
Strides are returned in units of elements of the underlying storage type (not bytes). The layout is:
d stride = 1
h stride = head_dim
t stride = heads * head_dim
Parameters
kv Cache (const).
stride_t Output stride for token index (optional).
stride_h Output stride for head index (optional).
stride_d Output stride for dim index (optional).
Returns
0 on success; non-zero on failure.
Definition at line 801 of file kv_cache.c.
{
  if (!kv) return -1;
  if (stride_d) *stride_d = 1u;
  if (stride_h) *stride_h = (size_t)kv->head_dim;
  if (stride_t) *stride_t = (size_t)kv->heads * (size_t)kv->head_dim;
  return 0;
}
References ie_kv_cache::head_dim, and ie_kv_cache::heads.
ie_kv_store_token_f32()
int ie_kv_store_token_f32 (ie_kv_cache * kv, size_t t, const float * K_f32, const float * V_f32)
Store a token's K/V slice into an FP32 cache.
Expects K_f32 and V_f32 laid out as [heads, head_dim] (contiguous).
Parameters
kv Cache (must be IE_KV_STORAGE_F32).
t Token index.
K_f32 K slice [H*D].
V_f32 V slice [H*D].
Returns
0 on success; non-zero on error.
Store a token's K/V slice into an FP32 cache.
Parameters
kv Cache.
t Token index.
K_f32 K data (length heads*head_dim).
V_f32 V data (length heads*head_dim).
Returns
0 on success; non-zero on failure.
Definition at line 501 of file kv_cache.c.
{
  if (!kv || !K_f32 || !V_f32) return -1;
  if (kv->storage != IE_KV_STORAGE_F32) return -2;
  if (t >= (size_t)kv->max_seq) return -3;
  const size_t H = (size_t)kv->heads;
  const size_t D = (size_t)kv->head_dim;
  const size_t slice = H * D;
  float *Kdst = (float *)kv->K;
  float *Vdst = (float *)kv->V;
  memcpy(Kdst + t * slice, K_f32, slice * sizeof(float));
  memcpy(Vdst + t * slice, V_f32, slice * sizeof(float));
  return 0;
}
References ie_kv_cache::head_dim, ie_kv_cache::heads, IE_KV_STORAGE_F32, ie_kv_cache::K, ie_kv_cache::max_seq, ie_kv_cache::storage, and ie_kv_cache::V.
Referenced by ie_forward_one_token().
ie_kv_store_token_fp8()
int ie_kv_store_token_fp8 (ie_kv_cache * kv, size_t t, const float * K_f32, const float * V_f32)
Store a token's K/V slice into an FP8 cache.
This path uses an internal scratch buffer to avoid per-token allocations.
Parameters
kv Cache (must be IE_KV_STORAGE_FP8).
t Token index.
K_f32 K slice [H*D].
V_f32 V slice [H*D].
Returns
0 on success; non-zero on error.
Store a token's K/V slice into an FP8 cache.
Quantizes activations to FP8 using the configured fp8_format and stores the packed bytes into the cache. Uses a per-head scratch buffer of length head_dim.
Parameters
kv Cache.
t Token index.
K_f32 K data (length heads*head_dim).
V_f32 V data (length heads*head_dim).
Returns
0 on success; non-zero on failure.
Definition at line 651 of file kv_cache.c.
{
  if (!kv || !K_f32 || !V_f32) return -1;
  if (kv->storage != IE_KV_STORAGE_FP8) return -2;
  if (t >= (size_t)kv->max_seq) return -3;
  const size_t H = (size_t)kv->heads;
  const size_t D = (size_t)kv->head_dim;
  uint8_t *Kdst = (uint8_t *)kv->K;
  uint8_t *Vdst = (uint8_t *)kv->V;
  uint8_t *tmp = kv->scratch_u8;
  if (!tmp) return -4;
  for (size_t h = 0; h < H; ++h) {
    const float *Ksrc = K_f32 + h * D;
    const float *Vsrc = V_f32 + h * D;
    const size_t off  = (t * H + h) * D;
    ie_quantize_act_fp8(Ksrc, tmp, D, kv->fp8_format);
    memcpy(Kdst + off, tmp, D * sizeof(uint8_t));
    ie_quantize_act_fp8(Vsrc, tmp, D, kv->fp8_format);
    memcpy(Vdst + off, tmp, D * sizeof(uint8_t));
  }
  return 0;
}
References ie_kv_cache::fp8_format, ie_kv_cache::head_dim, ie_kv_cache::heads, IE_KV_STORAGE_FP8, ie_quantize_act_fp8(), ie_kv_cache::K, ie_kv_cache::max_seq, ie_kv_cache::scratch_u8, ie_kv_cache::storage, and ie_kv_cache::V.
ie_kv_store_token_int8_per_group()
int ie_kv_store_token_int8_per_group (ie_kv_cache * kv, size_t t, const float * K_f32, const float * V_f32)
Store a token's K/V slice into an INT8 cache using per-group params.
Per-group means one (scale, zero) per (token, head, group). This path uses scratch buffers inside kv to avoid per-token allocations.
Parameters
kv Cache (must be IE_KV_STORAGE_INT8).
t Token index.
K_f32 K slice [H*D].
V_f32 V slice [H*D].
Returns
0 on success; non-zero on error.
Store a token's K/V slice into an INT8 cache using per-group params.
Computes affine scale/zero per group of size group_size along head_dim and stores those parameters into (token, head, group). Quantization is applied group-wise to the payload.
Parameters
kv Cache.
t Token index.
K_f32 K data (length heads*head_dim).
V_f32 V data (length heads*head_dim).
Returns
0 on success; non-zero on failure.
Definition at line 595 of file kv_cache.c.
{
  if (!kv || !K_f32 || !V_f32) return -1;
  if (kv->storage != IE_KV_STORAGE_INT8) return -2;
  if (t >= (size_t)kv->max_seq) return -3;
  const size_t H  = (size_t)kv->heads;
  const size_t D  = (size_t)kv->head_dim;
  const size_t G  = kv->group_count;
  const size_t Gs = kv->group_size;
  int8_t *Kdst = (int8_t *)kv->K;
  int8_t *Vdst = (int8_t *)kv->V;
  float  *scales = kv->scratch_scales;
  int8_t *zeros  = kv->scratch_zeros;
  if (!scales || !zeros) return -4;
  for (size_t h = 0; h < H; ++h) {
    const float *Ksrc = K_f32 + h * D;
    const float *Vsrc = V_f32 + h * D;
    const size_t off  = (t * H + h) * D;
    ie_act_i8_group_params_from_data(Ksrc, D, Gs, kv->symmetric, scales, zeros);
    ie_quantize_act_int8_per_group(Ksrc, Kdst + off, D, Gs, scales, zeros, kv->symmetric);
    for (size_t g = 0; g < G; ++g) {
      const size_t pi = param_index(t, h, g, H, G);
      kv->scales_K[pi] = scales[g];
      kv->zeros_K[pi]  = zeros[g];
    }
    ie_act_i8_group_params_from_data(Vsrc, D, Gs, kv->symmetric, scales, zeros);
    ie_quantize_act_int8_per_group(Vsrc, Vdst + off, D, Gs, scales, zeros, kv->symmetric);
    for (size_t g = 0; g < G; ++g) {
      const size_t pi = param_index(t, h, g, H, G);
      kv->scales_V[pi] = scales[g];
      kv->zeros_V[pi]  = zeros[g];
    }
  }
  return 0;
}
References ie_kv_cache::group_count, ie_kv_cache::group_size, ie_kv_cache::head_dim, ie_kv_cache::heads, ie_act_i8_group_params_from_data(), IE_KV_STORAGE_INT8, ie_quantize_act_int8_per_group(), ie_kv_cache::K, ie_kv_cache::max_seq, param_index(), ie_kv_cache::scales_K, ie_kv_cache::scales_V, ie_kv_cache::scratch_scales, ie_kv_cache::scratch_zeros, ie_kv_cache::storage, ie_kv_cache::symmetric, ie_kv_cache::V, ie_kv_cache::zeros_K, and ie_kv_cache::zeros_V.
ie_kv_store_token_int8_per_tensor()
int ie_kv_store_token_int8_per_tensor (ie_kv_cache * kv, size_t t, const float * K_f32, const float * V_f32)
Store a token's K/V slice into an INT8 cache using per-tensor params.
Per-tensor means one (scale, zero) per (token, head), replicated across all groups for that (token, head) to keep dequantization consistent.
Parameters
kv Cache (must be IE_KV_STORAGE_INT8).
t Token index.
K_f32 K slice [H*D].
V_f32 V slice [H*D].
Returns
0 on success; non-zero on error.
Store a token's K/V slice into an INT8 cache using per-tensor params.
Computes a single affine scale/zero for each (token, head) using min/max over the whole head_dim, then quantizes all D values. The same parameters are replicated into every group slot to keep the load path consistent.
Parameters
kv Cache.
t Token index.
K_f32 K data (length heads*head_dim).
V_f32 V data (length heads*head_dim).
Returns
0 on success; non-zero on failure.
Definition at line 533 of file kv_cache.c.
{
  if (!kv || !K_f32 || !V_f32) return -1;
  if (kv->storage != IE_KV_STORAGE_INT8) return -2;
  if (t >= (size_t)kv->max_seq) return -3;
  const size_t H = (size_t)kv->heads;
  const size_t D = (size_t)kv->head_dim;
  const size_t G = kv->group_count;
  int8_t *Kdst = (int8_t *)kv->K;
  int8_t *Vdst = (int8_t *)kv->V;
  for (size_t h = 0; h < H; ++h) {
    const float *Ksrc = K_f32 + h * D;
    const float *Vsrc = V_f32 + h * D;
    float Kmn = Ksrc[0], Kmx = Ksrc[0];
    float Vmn = Vsrc[0], Vmx = Vsrc[0];
    for (size_t d = 1; d < D; ++d) {
      const float kvv = Ksrc[d];
      const float vvv = Vsrc[d];
      if (kvv < Kmn) Kmn = kvv;
      if (kvv > Kmx) Kmx = kvv;
      if (vvv < Vmn) Vmn = vvv;
      if (vvv > Vmx) Vmx = vvv;
    }
    ie_act_i8_params pK, pV;
    ie_act_i8_params_from_minmax(Kmn, Kmx, kv->symmetric, &pK.scale, &pK.zero_point);
    ie_act_i8_params_from_minmax(Vmn, Vmx, kv->symmetric, &pV.scale, &pV.zero_point);
    const size_t off = (t * H + h) * D;
    ie_quantize_act_int8(Ksrc, Kdst + off, D, pK, kv->symmetric);
    ie_quantize_act_int8(Vsrc, Vdst + off, D, pV, kv->symmetric);
    for (size_t g = 0; g < G; ++g) {
      const size_t pi = param_index(t, h, g, H, G);
      kv->scales_K[pi] = pK.scale;
      kv->zeros_K[pi]  = pK.zero_point;
      kv->scales_V[pi] = pV.scale;
      kv->zeros_V[pi]  = pV.zero_point;
    }
  }
  return 0;
}
References ie_kv_cache::group_count, ie_kv_cache::head_dim, ie_kv_cache::heads, ie_act_i8_params_from_minmax(), IE_KV_STORAGE_INT8, ie_quantize_act_int8(), ie_kv_cache::K, ie_kv_cache::max_seq, param_index(), ie_act_i8_params::scale, ie_kv_cache::scales_K, ie_kv_cache::scales_V, ie_kv_cache::storage, ie_kv_cache::symmetric, ie_kv_cache::V, ie_act_i8_params::zero_point, ie_kv_cache::zeros_K, and ie_kv_cache::zeros_V.