Inference Engine (Clocher): build_hybrid_moe_int4 Namespace Reference
build_hybrid_moe_int4 Namespace Reference
Data Structures
class TensorRec
Functions
None _die (str msg)
int _align_up (int x, int a)
Dict[str, Any] _load_json (str path)
None _write_json (str path, Dict[str, Any] obj)
str _infer_in_bin (str model_dir, Dict[str, Any] m, Optional[str] in_bin_override)
List[TensorRec] _parse_tensors (Dict[str, Any] m)
None _copy_range (fin, fout, int src_off, int nbytes)
None _repack (str model_dir, str in_map_path, str in_bin_path, str out_bin_path, str out_map_path, int align)
int main ()
Detailed Description
build_hybrid_moe_int4.py
Repack an existing IEBIN tensor map + weights binary into a new aligned binary,
and emit a compatible tensor map that points to the new weights bin.
This tool is intentionally tolerant of older tensor-map JSON formats that do not
include a top-level "weights_bin" field. In that case, it defaults to
"model.ie.bin" inside --model-dir (or --in-bin if provided).
Typical usage (matches your invocation):
  MODEL_DIR=".../models/gpt-oss-20b"
  python3 tools/build_hybrid_moe_int4.py \
    --model-dir "$MODEL_DIR" \
    --out-bin "$MODEL_DIR/model.q4.bin" \
    --out-map "$MODEL_DIR/model.ie.compat.json" \
    --align 256
Notes:
- This script does not perform quantization. It repacks whatever tensors already
  exist in the input weights bin (BF16 weights, INT4 blocks/scales, etc.).
- The engine selects the INT4 artifact pair via --precision int4, which maps to
  model.ie.compat.json + model.q4.bin.
Function Documentation
_align_up()
int build_hybrid_moe_int4._align_up (int x, int a) protected
Definition at line 53 of file build_hybrid_moe_int4.py.
def _align_up(x: int, a: int) -> int:
    if a <= 0:
        return x
    r = x % a
    return x if r == 0 else x + (a - r)
Referenced by _repack().
_copy_range()
None build_hybrid_moe_int4._copy_range (fin, fout, int src_off, int nbytes) protected
Definition at line 158 of file build_hybrid_moe_int4.py.
def _copy_range(fin, fout, src_off: int, nbytes: int) -> None:
    fin.seek(src_off, os.SEEK_SET)
    remaining = nbytes
    buf_sz = 4 * 1024 * 1024
    while remaining > 0:
        take = buf_sz if remaining > buf_sz else remaining
        chunk = fin.read(take)
        if not chunk or len(chunk) != take:
            _die(f"short read at offset={src_off} (wanted {nbytes} bytes)")
        fout.write(chunk)
        remaining -= take
References _die().
Referenced by _repack().
_die()
None build_hybrid_moe_int4._die (str msg) protected
Definition at line 48 of file build_hybrid_moe_int4.py.
def _die(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(2)
Referenced by _copy_range(), _infer_in_bin(), _parse_tensors(), and main().
_infer_in_bin()
str build_hybrid_moe_int4._infer_in_bin (str model_dir, Dict[str, Any] m, Optional[str] in_bin_override) protected
Definition at line 72 of file build_hybrid_moe_int4.py.
def _infer_in_bin(model_dir: str, m: Dict[str, Any], in_bin_override: Optional[str]) -> str:
    if in_bin_override:
        p = in_bin_override
        if not os.path.isabs(p):
            p = os.path.join(model_dir, p)
        if not os.path.exists(p):
            _die(f"--in-bin {p} does not exist")
        return p
    wb = m.get("weights_bin")
    if isinstance(wb, str) and wb.strip():
        p = wb
        if not os.path.isabs(p):
            p = os.path.join(model_dir, p)
        if os.path.exists(p):
            return p
    # Back-compat default.
    p = os.path.join(model_dir, "model.ie.bin")
    if os.path.exists(p):
        return p
    # Last resort: find the largest *.bin file in model_dir.
    best = None
    best_sz = -1
    try:
        for fn in os.listdir(model_dir):
            if not fn.endswith(".bin"):
                continue
            fp = os.path.join(model_dir, fn)
            try:
                sz = os.path.getsize(fp)
            except OSError:
                continue
            if sz > best_sz:
                best_sz = sz
                best = fp
    except FileNotFoundError:
        pass
    if best:
        return best
    _die(f"could not infer input weights bin (no weights_bin, no model.ie.bin, no *.bin in {model_dir})")
    return ""
References _die().
Referenced by main().
_load_json()
Dict[str, Any] build_hybrid_moe_int4._load_json (str path) protected
Definition at line 60 of file build_hybrid_moe_int4.py.
def _load_json(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)
Referenced by _repack(), and main().
_parse_tensors()
List[TensorRec] build_hybrid_moe_int4._parse_tensors (Dict[str, Any] m) protected
Definition at line 119 of file build_hybrid_moe_int4.py.
def _parse_tensors(m: Dict[str, Any]) -> List[TensorRec]:
    ts = m.get("tensors")
    if not isinstance(ts, list) or not ts:
        _die("tensor map missing/invalid tensors[]")
    out: List[TensorRec] = []
    for t in ts:
        if not isinstance(t, dict):
            _die("tensor map tensors[] contains non-object")
        name = t.get("name")
        dtype = t.get("dtype")
        shape = t.get("shape")
        offset = t.get("offset")
        nbytes = t.get("nbytes")
        if not isinstance(name, str) or not name:
            _die("tensor missing/invalid name")
        if not isinstance(dtype, str) or not dtype:
            _die(f"{name}: tensor missing/invalid dtype")
        if not isinstance(shape, list) or not all(isinstance(x, int) for x in shape):
            _die(f"{name}: tensor missing/invalid shape")
        if not isinstance(offset, int) or offset < 0:
            _die(f"{name}: tensor missing/invalid offset")
        if not isinstance(nbytes, int) or nbytes <= 0:
            _die(f"{name}: tensor missing/invalid nbytes")
        out.append(TensorRec(
            name=name,
            dtype=dtype,
            shape=shape,
            offset=offset,
            nbytes=nbytes,
            raw=t,
        ))
    # Sort by file offset so we can stream copies.
    out.sort(key=lambda r: r.offset)
    return out
References _die().
Referenced by _repack().
_repack()
None build_hybrid_moe_int4._repack (str model_dir, str in_map_path, str in_bin_path, str out_bin_path, str out_map_path, int align) protected
Definition at line 171 of file build_hybrid_moe_int4.py.
            align: int) -> None:
    m = _load_json(in_map_path)
    tensors = _parse_tensors(m)
    os.makedirs(os.path.dirname(out_bin_path) or ".", exist_ok=True)
    # Stream-copy each tensor into the new bin with alignment.
    new_tensors: List[Dict[str, Any]] = []
    cur = 0
    with open(in_bin_path, "rb") as fin, open(out_bin_path, "wb") as fout:
        for r in tensors:
            cur = _align_up(cur, align)
            dst_off = cur
            # Ensure output file is positioned correctly.
            fout.seek(dst_off, os.SEEK_SET)
            _copy_range(fin, fout, r.offset, r.nbytes)
            cur = dst_off + r.nbytes
            t2 = dict(r.raw)
            t2["offset"] = dst_off
            t2["nbytes"] = r.nbytes
            new_tensors.append(t2)
    out_map = dict(m)
    out_map["weights_bin"] = os.path.basename(out_bin_path)
    out_map["tensors"] = new_tensors
    _write_json(out_map_path, out_map)
    out_sz = os.path.getsize(out_bin_path)
    print(f"[int4-artifacts] in_map={in_map_path}", file=sys.stderr)
    print(f"[int4-artifacts] in_bin={in_bin_path}", file=sys.stderr)
    print(f"[int4-artifacts] out_bin={out_bin_path} ({out_sz} bytes)", file=sys.stderr)
    print(f"[int4-artifacts] out_map={out_map_path}", file=sys.stderr)
References _align_up(), _copy_range(), _load_json(), _parse_tensors(), and _write_json().
Referenced by main().
_write_json()
None build_hybrid_moe_int4._write_json (str path, Dict[str, Any] obj) protected
Definition at line 65 of file build_hybrid_moe_int4.py.
def _write_json(path: str, obj: Dict[str, Any]) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, sort_keys=False)
        f.write("\n")
Referenced by _repack().
main()
int build_hybrid_moe_int4.main (void)
Definition at line 216 of file build_hybrid_moe_int4.py.
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model-dir", required=True, help="Model directory containing model.ie.json/bin.")
    ap.add_argument("--out-bin", required=True, help="Output weights bin path (e.g., model.q4.bin).")
    ap.add_argument("--out-map", required=True, help="Output map path (e.g., model.ie.compat.json).")
    ap.add_argument("--align", type=int, default=256, help="Byte alignment for each tensor start.")
    ap.add_argument("--in-map", default=None, help="Override input map path (default: model.ie.json in model-dir).")
    ap.add_argument("--in-bin", default=None, help="Override input weights bin (default: infer).")
    args = ap.parse_args()
    model_dir = os.path.abspath(args.model_dir)
    in_map_path = args.in_map
    if in_map_path is None:
        in_map_path = os.path.join(model_dir, "model.ie.json")
    elif not os.path.isabs(in_map_path):
        in_map_path = os.path.join(model_dir, in_map_path)
    if not os.path.exists(in_map_path):
        _die(f"input map does not exist: {in_map_path}")
    m = _load_json(in_map_path)
    in_bin_path = _infer_in_bin(model_dir, m, args.in_bin)
    out_bin_path = args.out_bin
    if not os.path.isabs(out_bin_path):
        out_bin_path = os.path.join(model_dir, out_bin_path)
    out_map_path = args.out_map
    if not os.path.isabs(out_map_path):
        out_map_path = os.path.join(model_dir, out_map_path)
    if args.align < 1 or (args.align & (args.align - 1)) != 0:
        _die("--align must be a positive power of two (e.g., 256)")
    _repack(
        model_dir=model_dir,
        in_map_path=in_map_path,
        in_bin_path=in_bin_path,
        out_bin_path=out_bin_path,
        out_map_path=out_map_path,
        align=args.align,
    )
    return 0
References _die(), _infer_in_bin(), _load_json(), _repack(), and main().
Referenced by main().