Inference Engine (Clocher): openai_compat_server Namespace Reference
openai_compat_server Namespace Reference
Data Structures
class Handler
Functions
_read_json (req)
_send_json (req, code, obj)
_run_hf (python_exe, script, model_id, model_path, device, max_new, prompt, temperature)
main ()
Function Documentation
_read_json()
openai_compat_server._read_json (req) protected
Definition at line 9 of file openai_compat_server.py.
def _read_json(req):
    n = int(req.headers.get("Content-Length", "0") or "0")
    if n <= 0:
        return None
    raw = req.rfile.read(n)
    try:
        return json.loads(raw.decode("utf-8", errors="replace"))
    except Exception:
        return None
Referenced by openai_compat_server.Handler.do_POST().
_run_hf()
openai_compat_server._run_hf (python_exe, script, model_id, model_path, device, max_new, prompt, temperature) protected
Definition at line 27 of file openai_compat_server.py.
def _run_hf(python_exe, script, model_id, model_path, device, max_new, prompt, temperature):
    cmd = [
        python_exe,
        script,
        "--device", device,
        "--max-new", str(max_new),
        "--prompt", prompt,
    ]
    if model_path:
        cmd += ["--model", model_path]
    else:
        cmd += ["--model", model_id]
    if temperature is not None:
        cmd += ["--temperature", str(temperature)]
    p = subprocess.run(cmd, capture_output=True, text=True)
    stdout = (p.stdout or "").strip()
    stderr = (p.stderr or "").strip()
    details = {
        "returncode": p.returncode,
        "stdout": stdout,
        "stderr": stderr,
        "model": model_path or model_id,
        "device": device,
        "max_new": max_new,
    }
    if p.returncode != 0:
        return None, details
    if not stdout:
        return None, details
    try:
        out = json.loads(stdout)
    except Exception:
        details["parse_error"] = "stdout was not valid JSON"
        return None, details
    return out, details
Referenced by openai_compat_server.Handler.do_POST().
_send_json()
openai_compat_server._send_json (req, code, obj) protected
Definition at line 19 of file openai_compat_server.py.
def _send_json(req, code, obj):
    body = json.dumps(obj, ensure_ascii=False).encode("utf-8")
    req.send_response(code)
    req.send_header("Content-Type", "application/json")
    req.send_header("Content-Length", str(len(body)))
    req.end_headers()
    req.wfile.write(body)
Referenced by openai_compat_server.Handler.do_GET(), and openai_compat_server.Handler.do_POST().
main()
openai_compat_server.main (void)
Definition at line 170 of file openai_compat_server.py.
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=8080)
    ap.add_argument("--python", dest="python_exe", default="python3")
    ap.add_argument("--script", required=True)
    ap.add_argument("--model-id", default="gpt-oss-20b")
    ap.add_argument("--model-path", default="")
    ap.add_argument("--model", default="", help="Alias for --model-path")
    ap.add_argument("--device", default="cpu")
    args = ap.parse_args()
    model_path = args.model_path or args.model
    httpd = HTTPServer((args.host, args.port), Handler)
    httpd.python_exe = args.python_exe
    httpd.script_path = args.script
    httpd.model_id = args.model_id
    httpd.model_path = model_path
    httpd.device = args.device
    httpd.serve_forever()