Inference Engine (Clocher): engine/src/math/rope.c File Reference
rope.c File Reference
Rotary Position Embedding (RoPE) fp32 implementation.
#include "ie_rope.h"
#include <math.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
Macros
#define _POSIX_C_SOURCE 200809L
Functions
static int ie_rope_env_pos_float (const char *name, float *out)
Parse a positive float from an environment variable.
static float ie_rope_pos_mul (void)
Get the effective RoPE position multiplier.
static float ie_rope_inv_freq (float theta, size_t i, size_t head_dim)
Compute theta^(-2i/head_dim) as a float.
int ie_rope_apply_one_f32 (float *x, size_t head_dim, uint32_t pos, float theta)
Apply RoPE to a single head vector in-place.
int ie_rope_apply_f32 (float *q, float *k, size_t heads, size_t head_dim, uint32_t pos, float theta)
Apply Rotary Positional Embedding (RoPE) to Q and K for a single position.
Variables
static float ie_rope_pos_mul_cached = -1.0f
Cached position multiplier for RoPE angle computation.
Detailed Description
Rotary Position Embedding (RoPE) fp32 implementation.
This file implements standard RoPE rotation for interleaved pairs of channels. It is intended as a correctness-first implementation for the initial CPU forward pass.
The rotation is applied per pair (2*i, 2*i+1) using:
inv_freq(i) = theta^(-2i / head_dim) angle = pos * inv_freq(i) [y0] = [ cos -sin ] [x0] [y1] [ sin cos ] [x1]
RoPE scaling:
This module supports optional position scaling inside the RoPE helper.
Set exactly one of the environment variables below:
IE_ROPE_LINEAR_SCALE: a positive float factor f. Effective pos = pos / f.
IE_ROPE_POS_SCALE: a positive float multiplier m. Effective pos = pos * m.
If neither is set, scaling defaults to 1.0 (vanilla RoPE).
Notes:
Scaling is applied by modifying the effective position used to compute angles, keeping all callers unchanged.
Definition in file rope.c.
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Definition at line 34 of file rope.c.
Function Documentation
ie_rope_apply_f32()
int ie_rope_apply_f32 (float * q, float * k, size_t heads, size_t head_dim, uint32_t pos, float theta)
Apply Rotary Positional Embedding (RoPE) to Q and K for a single position.
Apply RoPE to Q and/or K for multiple heads.
This function applies RoPE on the first head_dim elements, interpreted as interleaved pairs (even, odd): (x0, x1) -> (x0*cos - x1*sin, x0*sin + x1*cos)
The caller passes Q and K shaped as [heads, head_dim] flattened.
Parameters
q Q buffer, [heads * head_dim].
k K buffer, [heads * head_dim].
heads Number of heads in q/k.
head_dim Head dimension (must be even for paired rotation).
pos Sequence position (0-based).
theta RoPE base (commonly 10000.0f).
Returns
0 on success, negative on invalid args.
Definition at line 171 of file rope.c.
{
  if (!q && !k) return 0;
  if (heads == 0u) return -1;
  if ((head_dim & 1u) != 0u) return -2;
  if (head_dim < 2u) return -3;
  if (!(theta > 0.0f)) return -4;
  for (size_t h = 0; h < heads; ++h) {
    if (q) {
      const int rc = ie_rope_apply_one_f32(q + h * head_dim, head_dim, pos, theta);
      if (rc != 0) return rc;
    }
    if (k) {
      const int rc = ie_rope_apply_one_f32(k + h * head_dim, head_dim, pos, theta);
      if (rc != 0) return rc;
    }
  }
  return 0;
}
ie_rope_apply_one_f32()
int ie_rope_apply_one_f32 (float * x, size_t head_dim, uint32_t pos, float theta)
Apply RoPE to a single head vector in-place.
The head vector is treated as interleaved pairs: (x[0], x[1]), (x[2], x[3]), ...
Parameters
x Pointer to head vector (length head_dim).
head_dim Per-head dimension (must be even and >= 2).
pos Position index.
theta RoPE base theta (must be > 0).
Returns
0 on success, negative on error.
Definition at line 141 of file rope.c.
{
  if (!x) return -1;
  if (head_dim < 2u) return -2;
  if ((head_dim & 1u) != 0u) return -3;
  if (!(theta > 0.0f)) return -4;
  const size_t pairs = head_dim / 2u;
  /* Apply optional position scaling inside the helper. */
  const float p = (float)pos * ie_rope_pos_mul();
  for (size_t i = 0; i < pairs; ++i) {
    const size_t j = 2u * i;
    const float invf = ie_rope_inv_freq(theta, i, head_dim);
    const float ang = p * invf;
    const float c = cosf(ang);
    const float s = sinf(ang);
    const float x0 = x[j + 0u];
    const float x1 = x[j + 1u];
    x[j + 0u] = x0 * c - x1 * s;
    x[j + 1u] = x0 * s + x1 * c;
  }
  return 0;
}
References ie_rope_inv_freq(), and ie_rope_pos_mul().
Referenced by ie_rope_apply_f32().
ie_rope_env_pos_float()
static int ie_rope_env_pos_float (const char * name, float * out) static
Parse a positive float from an environment variable.
Parameters
name Environment variable name.
out Output value on success.
Returns
1 if parsed successfully and value is positive, 0 otherwise.
Definition at line 66 of file rope.c.
{
  if (!name || !out) return 0;
  const char *s = getenv(name);
  if (!s || !*s) return 0;
  char *end = NULL;
  const double v = strtod(s, &end);
  if (end == s) return 0;
  if (!(v > 0.0)) return 0;
  *out = (float)v;
  return 1;
}
Referenced by ie_rope_pos_mul().
ie_rope_inv_freq()
static float ie_rope_inv_freq (float theta, size_t i, size_t head_dim) static
Compute theta^(-2i/head_dim) as a float.
This helper uses exp/log for stability across a wide range of head sizes.
Parameters
theta RoPE base theta.
i Pair index (0-based).
head_dim Per-head dimension.
Returns
Inverse frequency for the given pair index.
Definition at line 127 of file rope.c.
{
  if (!(theta > 0.0f) || head_dim == 0u) return 0.0f;
  const float di = (float)i;
  const float dh = (float)head_dim;
  const float exponent = (-2.0f * di) / dh;
  return expf(exponent * logf(theta));
}
Referenced by ie_rope_apply_one_f32().
ie_rope_pos_mul()
static float ie_rope_pos_mul (void) static
Get the effective RoPE position multiplier.
Resolution order: 1) IE_ROPE_POS_SCALE: multiplier m, effective_pos = pos * m 2) IE_ROPE_LINEAR_SCALE: factor f, effective_pos = pos / f 3) default: 1.0
Returns
Position multiplier to apply to pos.
Definition at line 92 of file rope.c.
{
  if (ie_rope_pos_mul_cached > 0.0f) return ie_rope_pos_mul_cached;
  float m = 1.0f;
  float pos_scale = 0.0f;
  if (ie_rope_env_pos_float("IE_ROPE_POS_SCALE", &pos_scale)) {
    m = pos_scale;
  } else {
    float linear_scale = 0.0f;
    if (ie_rope_env_pos_float("IE_ROPE_LINEAR_SCALE", &linear_scale)) {
      m = 1.0f / linear_scale;
    }
  }
  if (!(m > 0.0f)) m = 1.0f;
  ie_rope_pos_mul_cached = m;
  return m;
}
References ie_rope_env_pos_float(), and ie_rope_pos_mul_cached.
Referenced by ie_rope_apply_one_f32().
Variable Documentation
ie_rope_pos_mul_cached
float ie_rope_pos_mul_cached = -1.0f static
Cached position multiplier for RoPE angle computation.
If set to 1.0, RoPE is vanilla. If set to m != 1.0, RoPE uses effective_pos = pos * m.
This is initialized lazily from environment variables to keep callers simple.
Definition at line 57 of file rope.c.
Referenced by ie_rope_pos_mul().