Inference Engine (Clocher): engine/src/util_logging.c File Reference
util_logging.c File Reference
Minimal logging helpers (stderr) used across the engine.
#include "util_logging.h"
#include <stdarg.h>
#include <stdio.h>
Functions
static void ie_vlog_ (const char *tag, const char *fmt, va_list ap)
void ie_log_info (const char *fmt,...)
Log an informational message (printf-style).
void ie_log_warn (const char *fmt,...)
Log a warning message (printf-style).
void ie_log_error (const char *fmt,...)
Log an error message (printf-style).
Detailed Description
Minimal logging helpers (stderr) used across the engine.
This project intentionally avoids third-party dependencies. This module provides a small, stable logging surface that other components can link against without pulling in any extra libraries.
Definition in file util_logging.c.
Function Documentation
ie_log_error()
void ie_log_error (const char * fmt, ...)
Log an error message (printf-style).
Parameters
fmt Format string.
... Arguments.
Definition at line 41 of file util_logging.c.
{
  va_list ap;
  va_start(ap, fmt);
  ie_vlog_("error", fmt, ap);
  va_end(ap);
}
References ie_vlog_().
Referenced by cmd_decode(), cmd_encode(), cmd_roundtrip(), ie_engine_create(), ie_engine_generate_ex(), ie_gemv_qi8_stub_impl(), ie_tok_decode(), ie_tok_encode(), ie_vocab_load(), and main().
ie_log_info()
void ie_log_info (const char * fmt, ...)
Log an informational message (printf-style).
Parameters
fmt Format string.
... Arguments.
Definition at line 27 of file util_logging.c.
{
  va_list ap;
  va_start(ap, fmt);
  ie_vlog_("info", fmt, ap);
  va_end(ap);
}
References ie_vlog_().
Referenced by debug_dump_topk_(), ie_engine_create(), ie_engine_destroy(), ie_engine_generate_ex(), ie_log_kernel_once(), ie_tok_decode(), ie_tok_encode(), ie_vocab_load(), log_hparams_(), log_hparams_ex_(), log_prompt_preview_(), and tok_log_preview_().
ie_log_warn()
void ie_log_warn (const char * fmt, ...)
Log a warning message (printf-style).
Parameters
fmt Format string.
... Arguments.
Definition at line 34 of file util_logging.c.
{
  va_list ap;
  va_start(ap, fmt);
  ie_vlog_("warn", fmt, ap);
  va_end(ap);
}
References ie_vlog_().
Referenced by ie_engine_create(), ie_engine_generate_ex(), maybe_correct_head_dim_(), and trace_ids_open_().
ie_vlog_()
static void ie_vlog_ (const char * tag, const char * fmt, va_list ap) static
Definition at line 15 of file util_logging.c.
{
  if (!fmt) return;
  if (tag && tag[0]) {
    fputs(tag, stderr);
    fputs(": ", stderr);
  }
  vfprintf(stderr, fmt, ap);
  fputc('\n', stderr);
}
Referenced by ie_log_error(), ie_log_info(), and ie_log_warn().