"""tests/python/test_harness.py

Harness smoke tests (stdlib-only).

The harness drives the compiled binary and writes benchmark reports.
This requires a working model, so the test is treated as an integration
test and is skipped unless enabled.

Enable integration tests with:
  IE_TEST_INTEGRATION=1 make test
"""

import json
import os
import subprocess
import time
import unittest
from pathlib import Path


def _env_truthy(name: str) -> bool:
    v = os.environ.get(name, "")
    v = v.strip().lower()
    return v in ("1", "true", "yes", "on")


class HarnessTests(unittest.TestCase):
    def setUp(self):
        if not _env_truthy("IE_TEST_INTEGRATION"):
            self.skipTest("integration tests disabled (set IE_TEST_INTEGRATION=1 to enable)")

        self.repo_root = Path(__file__).resolve().parents[2]
        self.bin_path = self.repo_root / "build" / "inference-engine"
        self.reports_dir = self.repo_root / "benchmarks" / "reports"
        self.harness_script = self.repo_root / "benchmarks" / "harness.py"

    def test_harness_generates_reports(self):
        self.assertTrue(self.bin_path.exists(), msg="Binary not found. Run: make build")
        self.assertTrue(self.harness_script.exists(), msg="Missing benchmarks/harness.py")

        cp = subprocess.run(
            ["python3", str(self.harness_script)],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=600,
        )
        _ = cp

        # Allow filesystem timestamp granularity.
        time.sleep(0.05)

        candidates = sorted(self.reports_dir.glob("*/summary.json"))
        self.assertTrue(candidates, msg="No summary.json generated by harness")
        summary_path = candidates[-1]

        data = json.loads(summary_path.read_text(encoding="utf-8"))
        for key in ("avg_tps_true", "total_tokens", "samples"):
            self.assertIn(key, data, msg=f"Missing summary field: {key}")
        self.assertGreater(data["samples"], 0)
        self.assertGreaterEqual(data["total_tokens"], 0)


if __name__ == "__main__":
    unittest.main(verbosity=2)
