name: ci
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { cc: [gcc, clang] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Build
        run: CC=${{ matrix.cc }} make build
      - name: Tests
        run: CC=${{ matrix.cc }} make test
      - name: Smoke bench
        run: CC=${{ matrix.cc }} make bench
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ie-artifacts-${{ matrix.cc }}
          path: |
            build/inference-engine
            benchmarks/reports/**
