name: ci
on:
  push:
    branches: [ main, master, develop, '**' ]
  pull_request:
    branches: [ main, master, develop, '**' ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build
        run: CC=${{ matrix.cc }} make build

      - name: Run tests
        run: CC=${{ matrix.cc }} make test

      - name: Smoke bench
        run: CC=${{ matrix.cc }} make bench

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ie-artifacts-${{ matrix.cc }}
          path: |
            build/inference-engine
            benchmarks/reports/**
